### ISSUE TITLE
[Question] MQTT X509 Authentication With Kotlin/Java And Eclipse Paho

### ISSUE THREAD

**Issue by Neuman968** [thingsboard/thingsboard#10018]
**MQTT**

 * Generic

**Description**
Hello! I am trying to get X509 authentication working with the Paho MQTT Client in Kotlin.
I have followed the example in https://thingsboard.io/docs/pe/user-guide/certificates/ and was able to have success sending telemetry with the command 
```bash
mosquitto_pub --cafile thingsboard-root.pem -d -q 1 -h "mqtt.thingsboard.cloud" -p "8883" -t "v1/devices/me/telemetry" --key deviceKey.pem --cert chain.pem -m {"temperature":25}
```

My certificates have been set up with a device profile and auto provision the device based on the device certificate, the above mosquitto_pub command works. However, I am struggling to replicate this in Java/Kotlin.

I am getting the following error 

```bash
Not authorized. (135)
	at org.eclipse.paho.mqttv5.client.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:32)
	at org.eclipse.paho.mqttv5.client.internal.ClientState.notifyReceivedAck(ClientState.java:1074)
	at org.eclipse.paho.mqttv5.client.internal.CommsReceiver.run(CommsReceiver.java:153)
```

Note, I was able to validate that the certificates and keys work via the mosquitto_pub command

** tools **

```bash
openssl -v
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
```

```bash
mosquitto_pub --version
mosquitto_pub version 2.0.18 running on libmosquitto 2.0.18.
```

```bash
java -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)
```

**Environment**

 * OS:  MacOS
 * ThingsBoard: Cloud
 * Browser: N/A

Here is a link to a repo replicating my issue. https://github.com/Neuman968/mqtt-thingsboard-x509

Here is the relevant code as well.

```kotlin
package com.example
import org.bouncycastle.asn1.pkcs.PrivateKeyInfo
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.bouncycastle.openssl.PEMParser
import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter
import org.eclipse.paho.mqttv5.client.*
import org.eclipse.paho.mqttv5.client.persist.MemoryPersistence
import org.eclipse.paho.mqttv5.common.MqttException
import org.eclipse.paho.mqttv5.common.MqttMessage
import org.eclipse.paho.mqttv5.common.packet.MqttProperties
import java.io.ByteArrayInputStream
import java.io.File
import java.io.StringReader
import java.security.KeyStore
import java.security.PrivateKey
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext
import javax.net.ssl.TrustManagerFactory

/**
 * Certificates were generated following guide
 * https://thingsboard.io/docs/pe/user-guide/certificates/
 *
 * Attempting to publish telemetry with X509 authentication. Replicating mosquitto_pub command
 * mosquitto_pub --cafile thingsboard-root.pem -d -q 1 -h "mqtt.thingsboard.cloud" -p "8883" -t "v1/devices/me/telemetry" --key deviceKey.pem --cert chain.pem -m {"temperature":25}
 * NOTE: No Passwords for keys were used.
 */
fun main() {
    val broker = "ssl://mqtt.thingsboard.cloud:8883"

    // replace file paths with the location of the certificates generated in https://thingsboard.io/docs/pe/user-guide/certificates/
    val privateKeyPEM = File("deviceKey.pem").readText()
    val clientCertPEM = File("chain.pem").readText()

    // thingsboard certificate provided in guide, renamaed from "ca-cert.pem" in user guide.
    val caCertPEM = File("thingsboard-root.pem").readText()

    val key = getPrivateKey(privateKeyPEM)
    val clientCert = getCertificate(clientCertPEM)
    val caCert = getCertificate(caCertPEM)

    val keyStore = KeyStore.getInstance("PKCS12")
    keyStore.load(null, null)
    keyStore.setCertificateEntry("certificate", clientCert)
    keyStore.setKeyEntry("private-key", key, null, arrayOf(clientCert))

    val trustStore = KeyStore.getInstance("PKCS12")
    trustStore.load(null, null)
    trustStore.setCertificateEntry("ca-certificate", caCert)

    val keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm())
    keyManagerFactory.init(keyStore, null)

    val trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm())
    trustManagerFactory.init(trustStore)

    val sslContext = SSLContext.getInstance("TLSv1.2")
    sslContext.init(keyManagerFactory.keyManagers, trustManagerFactory.trustManagers, null)

    try {
        val mqttOpts = MqttConnectionOptions()
        mqttOpts.socketFactory = sslContext.socketFactory
        mqttOpts.setAutomaticReconnect(true)
        mqttOpts.setKeepAliveInterval(10000)
        mqttOpts.setConnectionTimeout(30)

        val client = MqttClient(broker, null, MemoryPersistence())

        client.setCallback(object : MqttCallback {
            override fun disconnected(disconnectResponse: MqttDisconnectResponse) {
                println("Disconnected!")
            }

            override fun mqttErrorOccurred(exception: MqttException) {
                println("Disconnected!")
            }

            override fun messageArrived(topic: String, message: MqttMessage) {
                println("Message Arrived!")
            }

            override fun deliveryComplete(p0: IMqttToken?) {
                println("Delivery Complete!")
            }

            override fun connectComplete(reconnect: Boolean, serverURI: String) {
                println("Disconnected!")
            }

            override fun authPacketArrived(auth: Int, mqttAuth: MqttProperties) {
                println("Auth Packed Arrived!")
            }
        })

        client.connect(mqttOpts)

        val payload = """{"temperature": 350}"""
        val message = MqttMessage(payload.toByteArray(Charsets.UTF_8))
        message.qos = 2

        client.publish("v1/devices/me/telemetry", message)
        println("Message published! Message: $payload")
        client.disconnect()

    } catch (exp: Exception) {
        exp.printStackTrace()
    }
}

/**
 * Retrieves the private key from a PEM format.
 *
 * @param pem The PEM-formatted private key string.
 * @return The private key object.
 */
fun getPrivateKey(pem: String): PrivateKey {
    val reader = PEMParser(StringReader(pem))
    val converter = JcaPEMKeyConverter().setProvider(BouncyCastleProvider())
    return converter.getPrivateKey(reader.readObject() as PrivateKeyInfo)
}

/**
 * Retrieves an X509 certificate from a PEM-encoded string.
 *
 * @param pem The PEM-encoded string representing the certificate.
 * @return The X509 certificate.
 */
fun getCertificate(pem: String): X509Certificate {
    val reader = ByteArrayInputStream(pem.toByteArray())
    val cf = CertificateFactory.getInstance("X.509")
    return cf.generateCertificate(reader) as X509Certificate
}
```

I have tried a few different versions, such as adding each certificate individually to the trust store rather than the entire `chain.pem` file. 

Thank you for any help with this matter!

**Comment by Neuman968** [comment]
Closing this issue as I solved the problem. ill follow up with my solution and post it to the repository linked earlier for those interested. Long story short, I needed to use org.apache.httpcomponents in order to construct an SSLContext that will encrypt the 2 way SSL connection with the client certificate. Still not entirely sure why the default does not work, but will update on the solution.

**Comment by Neuman968** [comment]
Solution is now in the main branch of the repository I linked for anyone interested.  https://github.com/Neuman968/mqtt-thingsboard-x509 using org.apache.httpcomponents to construct an SSLContext corrects the issue.
