### ISSUE TITLE
[Question] How can I update a device shared attribute after inactivity is raised?

### ISSUE THREAD

**Issue by jabr0ni** [thingsboard/thingsboard#10026]
**Component**

 * Rule Engine

**Description**
I am trying to set a shared attribute update when a device becomes inactive. The logic is:
If device == innactive then update shared_attribute item.

In the innactivity rule chain I have created a set of nodes as follows:
![image](https://github.com/thingsboard/thingsboard/assets/50448490/8bfca186-4c3d-4046-ba1e-01cd0bca659e)
1. The filter script just filters the device
2. Transformation script checks `metadata.scope_item` and sets it and then returns `return {msg: msg, metadata: metadata, msgType: msgType};`
3. Shared attributes saved

However, when monitoring the debug events, I can see it succeed up until the save attributes node where the error message complains about INACTIVITY_EVENT:
```
java.lang.IllegalArgumentException: Unsupported msg type: INACTIVITY_EVENT
	at org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode.onMsg(TbMsgAttributesNode.java:84)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:168)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:116)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:75)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:56)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Environment**

 * ThingsBoard: 3.5.1

**Comment by jabr0ni** [comment]
Just an update - I have added the following to the transformation script:
```
metadata.scope = "SHARED_SCOPE";
msgType = "POST_ATTRIBUTES_REQUEST";
``` 

However, this does not update the shared attribute I have defined for the device, and instead adds these from the metadata to the shared attributes:
![image](https://github.com/thingsboard/thingsboard/assets/50448490/6d2a7752-88b3-4964-8bbb-d86a4c8e8836)

**Comment by devaskim** [comment]
Attribute should be places in `msg`, not in `metadata`. Also there is no need to setup attribute scope, because it doesn't in `Save Attributes` node.

**Comment by jabr0ni** [comment]
Hi @devaskim, that is understandable. I have modified it a little, however now the shared scope key:value pair I want to update is not updating, and instead the rule chain is adding/creating a new server attributes with the key:value pair from my transformation script:

```
if(msg.scope_item!= "A" || typeof msg.scope_item== 'undefined'){
    msg.scope_item= "B";
}
else msg.scope_item= 'C';

msgType = "POST_ATTRIBUTES_REQUEST";

return {msg: msg, metadata: metadata, msgType: msgType};
```

**Comment by devaskim** [comment]
Seems like your `Save attribute` node has wrong configuration (save to server attribute)

**Comment by ashvayka** [comment]
Please attach the exact code of your script. Also please enable debug mode in the "save attributes" and attach the screen of the incoming message and the error. This will help us.

**Comment by AndriichnekoDm** [comment]
Hi @jabr0ni !
Can you add the information we asked for earlier? Or have you already solved your problem?

**Comment by Ultrazombie** [comment]
closed due to inactivity
