### ISSUE TITLE
[Question] What to do with old requestIds

### ISSUE THREAD

**Issue by pintify** [thingsboard/thingsboard#10047]
**Description**
I'm trying to build a client that integrates with Thingsboard platform, but I'm not sure what to do in case some topic (response or request) has a requestId lower than the last I received. Am I expected to discard it? Or should I process it anyway? Or maybe the platform does guarantee that it will not send a given message unless all the lower-requestId messages are sent? If it is so, do I have to guarantee it too from the client?

**Comment by ashvayka** [comment]
I assume your question is related to the requestId in the RPC that the client receives from the server. I have doubts that we may send the requested lower than we already sent. Except for the case when the RPC are persisted ones and the transport layer does not guarantee the order of the messages. So I suspect you should simply ignore them.

**Comment by pintify** [comment]
Well, I was also considering the attributes API. I guess the answer is the same.

Regarding the client, is it important if I send an old requestId? I'm managing some priority on the messages for the RPC and on unstable connection scenario it could impact on the order of the requestIds. I was wondering if the platform would ignore a requestId older than the last received

**Comment by mixo3891** [comment]
hello I need help too.
I can not update Thingsboard from 3.6.1->3.6.2
please check problem:

root@orangepi5:~# sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.6.1

/_ / / / () ____ ____ _ _____ / __ ) ____ ____ _ _____ / /
/ / / __ \ / / / __ \ / __ / / / / __ | / __ \ / __ / / / / __ /
/ / / / / / / / / / / / / // / ( ) / // / / // // // / / / / // /
// // // // // // , / // /_/ / ,/ // ,/
//

===================================================
:: ThingsBoard :: (v3.6.2)
Starting ThingsBoard Upgrade from version 3.6.1 ...
Clearing cache to upgrade from version 3.6.1 to 3.6.2
Clearing cache [securitySettings]
Clearing cache [resourceInfo]
Upgrading ThingsBoard from version 3.6.1 to 3.6.2 ...
Updating schema ...
Skip schema re-update to version 3.6.2. Use env flag 'SKIP_SCHEMA_VERSION_CHECK' to force the re-update.
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating system data...
Starting rule nodes upgrade ...
Finished rule nodes upgrade. Upgraded rule nodes count: 0
Loading system widgets
Unable to load widget type from json: [/usr/share/thingsboard/data/json/system/widget_types/update_server_location_attribute.json]
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to load widget type from json
at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:249)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.thingsboard.server.service.install.InstallScripts.loadSystemWidgets(InstallScripts.java:241)
at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.loadSystemWidgets(DefaultSystemDataLoaderService.java:538)
at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:288)
at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
at org.thingsboard.server.dao.resource.BaseImageService$$EnhancerBySpringCGLIB$$2298e34d.replaceBase64WithImageUrl()
at org.thingsboard.server.dao.widget.WidgetTypeServiceImpl.saveWidgetType(WidgetTypeServiceImpl.java:97)
at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:246)
... 13 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with a full description of your request.
