### ISSUE TITLE
[Bug] Unable to downlink to edge (CE > CE Edge)

### ISSUE THREAD

**Issue by fg0578fg0578** [thingsboard/thingsboard#10079]
**Describe the bug**

**Your Server Environment**

* own setup
  * Docker Deployment
  * ThingsBoard Version: CE 3.6.2
  * ThingsBoard Edge Version: CE Edge 3.6.2
  * Os for CE: Ubuntu22.04
  * Os for CE Edge: Ubuntu22.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: WIN11
* Browser: chrome
* Version: 121.0.6167.85

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
Steps to reproduce the behaviour:
1. Install CE on ubuntu22.04, with Kafka as the [Queue](https://github.com/thingsboard/thingsboard/assets/88201416/708afc72-4713-46fc-b390-d5009f45088b)
![ce docker](https://github.com/thingsboard/thingsboard/assets/88201416/708afc72-4713-46fc-b390-d5009f45088b)
2. Install CE Edge on another machine (ubuntu22.04)
3. Firstly, everything works well. Edge can push data to CE, and vice versa (CE able to push data to Edge)
![image](https://github.com/thingsboard/thingsboard/assets/88201416/ecddf4aa-3b5e-46d8-82f8-66fdbfb15128)
4. Then the two machines are shut down.
5. Reboot two machines again, and do the following to the two machines
`docker compose down`
`docker compose up -d`
`docker logs -f mytb/mytbedge`
6. Login Edge UI, go to 'Devices', device data are coming
![image](https://github.com/thingsboard/thingsboard/assets/88201416/8fc9fc52-edd7-4ad5-b013-f3721614fc8a)
7. Login CE UI, go to 'Devices', device data are coming as well
![image](https://github.com/thingsboard/thingsboard/assets/88201416/6e0b7d76-76c6-4c58-9ad4-bee7698180bd)
8. On Edge UI, go to 'Edge'>‘Cloud events’, all are **Deployed**
![image](https://github.com/thingsboard/thingsboard/assets/88201416/29cb92ee-3e48-4eaf-954c-18872e5fa928)
9. On CE UI, go to 'Edge Management'>'Instances', choose the Edge, go to 'Downlinks', many things are in 'Pending' status
![image](https://github.com/thingsboard/thingsboard/assets/88201416/1419cce5-cf86-45c7-8f05-fa71915574eb)
10. Same page, go to 'Details', click 'Sync Edge'
![image](https://github.com/thingsboard/thingsboard/assets/88201416/3e2c0d62-8ebd-4021-90bd-bb1b0bca9a98)
11. Back to 'Downlinks'
![image](https://github.com/thingsboard/thingsboard/assets/88201416/f74f3336-7b61-400c-9fbf-2f90284a9b14)
12. In the machine, check the logs and see error

**Consider the 8 hours difference since the machine time is UTC and my time is GMT+8**

![image](https://github.com/thingsboard/thingsboard/assets/88201416/0c7569d4-f288-4f21-8833-7548bedf78a2)

**Expected behavior**
CE could push data (downlink) to Edge

**Screenshots**
Added

**Additional context**
1. Detailed logs

```
mytb-1  | 2024-01-28 21:40:33,437 [edge-service-31-thread-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 1, class = TenantEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:33,462 [GrpcCallbackExecutorService-1-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 2, class = QueuesEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:33,527 [GrpcCallbackExecutorService-1-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 3, class = RuleChainsEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:33,840 [GrpcCallbackExecutorService-1-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 4, class = AdminSettingsEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:33,960 [GrpcCallbackExecutorService-1-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 5, class = TenantAdminUsersEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:34,128 [GrpcCallbackExecutorService-1-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 6, class = CustomerEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:34,234 [GrpcCallbackExecutorService-1-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 7, class = DashboardsEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:34,236 [GrpcCallbackExecutorService-1-1] INFO  o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] starting sync process, cursor current idx = 8, class = DefaultProfilesEdgeEventFetcher
mytb-1  | 2024-01-28 21:40:34,237 [GrpcCallbackExecutorService-1-1] ERROR o.t.s.s.edge.rpc.EdgeGrpcSession - [63c0c004-9690-4a5d-b04e-7b58c19ee8c2] Failed to fetch edge events
mytb-1  | java.lang.NullPointerException: null
mytb-1  |       at org.thingsboard.server.service.edge.rpc.fetch.DefaultProfilesEdgeEventFetcher.fetchEdgeEvents(DefaultProfilesEdgeEventFetcher.java:58)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession.processEdgeEvents(EdgeGrpcSession.java:407)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession.startProcessingEdgeEvents(EdgeGrpcSession.java:401)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession.doSync(EdgeGrpcSession.java:232)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession$2.onSuccess(EdgeGrpcSession.java:236)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession$2.onSuccess(EdgeGrpcSession.java:233)
mytb-1  |       at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
mytb-1  | 2024-01-28 21:40:34,237 [GrpcCallbackExecutorService-1-1] ERROR o.t.s.s.edge.rpc.EdgeGrpcSession - [4a5bdec0-bd67-11ee-9124-4bfdc72be317][b3cab9c0-bd68-11ee-bd64-6f21a424b1ba] Exception during sync process
mytb-1  | java.lang.NullPointerException: null
mytb-1  |       at org.thingsboard.server.service.edge.rpc.fetch.DefaultProfilesEdgeEventFetcher.fetchEdgeEvents(DefaultProfilesEdgeEventFetcher.java:58)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession.processEdgeEvents(EdgeGrpcSession.java:407)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession.startProcessingEdgeEvents(EdgeGrpcSession.java:401)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession.doSync(EdgeGrpcSession.java:232)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession$2.onSuccess(EdgeGrpcSession.java:236)
mytb-1  |       at org.thingsboard.server.service.edge.rpc.EdgeGrpcSession$2.onSuccess(EdgeGrpcSession.java:233)
mytb-1  |       at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
mytb-1  |       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by fg0578fg0578** [comment]
@volodymyr-babak Cool, it does solve my problem. Thanks a lot.
