### ISSUE TITLE
[Question]Exception while mqtt transport application is  up and running

### ISSUE THREAD

**Issue by anil123lalam** [thingsboard/thingsboard#10123]
**Component**

 * Installation
 

**Description**
When i try to make the mqtt transport service application(**ThingsboardMqttTransportApplication.java)** i am getting below error

**2024-02-03 08:19:15,714 [main] INFO  o.t.s.m.ThingsboardMqttTransportApplication - Started ThingsboardMqttTransportApplication in 21.927 seconds (JVM running for 24.785)
2024-02-03 08:19:15,719 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:19:29,231 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:19:39,238 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:19:49,255 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:19:59,258 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:20:09,289 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:20:15,716 [scheduling-1] INFO  o.t.s.c.t.s.DefaultTransportService - Transport Stats: openConnections [0]
2024-02-03 08:20:19,290 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:20:29,319 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:20:39,333 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:20:49,350 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:20:59,363 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:21:09,381 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:21:15,717 [scheduling-1] INFO  o.t.s.c.t.s.DefaultTransportService - Transport Stats: openConnections [0]
2024-02-03 08:21:19,389 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:21:29,408 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:21:39,417 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:21:59,436 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:22:09,448 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:22:15,719 [scheduling-1] INFO  o.t.s.c.t.s.DefaultTransportService - Transport Stats: openConnections [0]
2024-02-03 08:22:19,466 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:22:29,476 [main] INFO  o.t.s.q.d.HashPartitionService - Try to get queue routing info.
2024-02-03 08:22:39,495 [main] INFO  o.t.s.q.d.HashPartitionService - Failed to get queues routing info: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException!
2024-02-03 08:22:49,719 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.RuntimeException: Failed to await queues routing info!
	at org.thingsboard.server.queue.discovery.HashPartitionService.getQueueRoutingInfos(HashPartitionService.java:160)
	at org.thingsboard.server.queue.discovery.HashPartitionService.doInitRuleEnginePartitions(HashPartitionService.java:129)
	at org.thingsboard.server.queue.discovery.HashPartitionService.partitionsInit(HashPartitionService.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at org.thingsboard.server.mqtt.ThingsboardMqttTransportApplication.main(ThingsboardMqttTransportApplication.java:38)
2024-02-03 08:22:49,737 [main] INFO  o.t.s.t.mqtt.MqttTransportService - Stopping MQTT transport!
2024-02-03 08:22:49,751 [main] INFO  o.t.s.t.mqtt.MqttTransportService - MQTT transport stopped!**

Can any body help me with this ?

**Environment**

 * OS:  windos and 10
 * ThingsBoard: 3.6.3
 * Browser: name and version

**Comment by anil123lalam** [comment]
Resolved

**Comment by LlorandoLau** [comment]
hi, could you share your solution? I'm running on the same error
