### ISSUE TITLE
Thingsboard Cloud throws Authentication failed error while generating report

### ISSUE THREAD

**Issue by digikloud** [thingsboard/thingsboard#10237]
**Describe the bug**
I m trying to generate report using scheduler. I followed the standard documentation and configure the scheduler but reports are not getting generated. I m getting **_Failed to open dashboard. Authentication failed error_**

I used tenant admin, customer admin & customer user credentials but getting same error for all creds. I tried for different tenant account also getting same error. Looks like something wrong on thingsboard end

**Your Server Environment**
Thingsboard Cloud PE 3.6.2

Error Message:

org.thingsboard.server.common.data.exception.ThingsboardException: Failed to load dashboard page: Error: Authentication failed!
	at org.thingsboard.server.service.report.DefaultReportService$1.onFailure(DefaultReportService.java:218)
	at org.springframework.util.concurrent.ListenableFutureAdapter$1.onFailure(ListenableFutureAdapter.java:76)
	at org.springframework.util.concurrent.ListenableFutureAdapter$1.onSuccess(ListenableFutureAdapter.java:64)
	at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.notifySuccess(ListenableFutureCallbackRegistry.java:76)
	at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.success(ListenableFutureCallbackRegistry.java:142)
	at org.springframework.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:84)
	at org.springframework.util.concurrent.SettableListenableFuture$SettableTask.done(SettableListenableFuture.java:177)
	at java.base/java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.base/java.util.concurrent.FutureTask.set(FutureTask.java:232)
	at org.springframework.util.concurrent.SettableListenableFuture$SettableTask.setResultValue(SettableListenableFuture.java:160)
	at org.springframework.util.concurrent.SettableListenableFuture.set(SettableListenableFuture.java:58)
	at org.springframework.http.client.Netty4ClientHttpRequest$RequestExecuteHandler.channelRead0(Netty4ClientHttpRequest.java:178)
	at org.springframework.http.client.Netty4ClientHttpRequest$RequestExecuteHandler.channelRead0(Netty4ClientHttpRequest.java:168)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty....[truncated 207 symbols]

Scheduer configuraiton
![image](https://github.com/thingsboard/thingsboard/assets/118111106/4dbec012-3f0a-487a-b7f0-6531d4ba2636)

**Comment by AndriichnekoDm** [comment]
Hi @digikloud !
Thanks for reporting this issue. I've forwarded it to our QA team for reproduction. We'll make sure to update you with the fix version details once available.

**Comment by digikloud** [comment]
@AndriichnekoDm Thanks. Will wait for your update
