### ISSUE TITLE
http-transport log optimization

### ISSUE THREAD

**Issue by smatvienko-tb** [thingsboard/thingsboard#10303]
**Is your feature request related to a problem? Please describe.**

http-transport logs on the production have too much overhead and are hard to read under high-load

ThingsBoard version 3.6.2

**Describe the solution you'd like**

HttpMessageNotReadableException -> DEBUG level on "Required request body is missing: public"

JsonSyntaxException -> DEBUG level, log error message without stack trace

🍒ClientAbortException, IOException -> find a way to reduce log severity on input-output exceptions for Tomcat

**Describe alternatives you've considered**

My vision is something like this:

![image](https://github.com/thingsboard/thingsboard/assets/79898499/66c34e39-3305-4afb-8570-c16b52f0dc35)

**Additional context**

`kubectl logs -f tb-http-transport-0 --tail 99`

```
2024-03-05 19:30:13,590 [http-nio-0.0.0.0-8080-exec-11] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
2024-03-05 19:30:13,591 [http-nio-0.0.0.0-8080-exec-4] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
2024-03-05 19:30:13,594 [http-nio-0.0.0.0-8080-exec-13] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
2024-03-05 19:30:13,596 [http-nio-0.0.0.0-8080-exec-5] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
2024-03-05 19:30:13,606 [http-nio-0.0.0.0-8080-exec-1] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
2024-03-05 19:30:13,619 [http-nio-0.0.0.0-8080-exec-14] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
2024-03-05 19:30:54,256 [DefaultTransportService-11-3] WARN  o.t.s.t.http.DeviceApiController - Failed to process request
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 29 path $[1].50
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:85)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:60)
	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
	at com.google.gson.JsonParser.parse(JsonParser.java:98)
	at org.thingsboard.server.transport.http.DeviceApiController.lambda$postTelemetry$2(DeviceApiController.java:224)
	at org.thingsboard.server.transport.http.DeviceApiController$DeviceAuthCallback.onSuccess(DeviceApiController.java:477)
	at org.thingsboard.server.transport.http.DeviceApiController$DeviceAuthCallback.onSuccess(DeviceApiController.java:463)
	at org.thingsboard.server.queue.common.AsyncCallbackTemplate$1.onSuccess(AsyncCallbackTemplate.java:64)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 29 path $[1].50
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:530)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:703)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:726)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:718)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:697)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 15 common frames omitted
2024-03-05 19:31:02,575 [http-nio-0.0.0.0-8080-exec-11] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
2024-03-05 19:31:02,576 [http-nio-0.0.0.0-8080-exec-11] ERROR o.a.c.c.C.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=0, location=/error]
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:309)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:271)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:118)
	at java.base/java.io.FilterOutputStream.flush(FilterOutputStream.java:153)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1187)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1009)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:456)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290)
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:502)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:427)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:373)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:237)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:166)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:237)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:240)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:462)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:136)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1431)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:768)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:732)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:716)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.flush(Http11OutputBuffer.java:566)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.flush(ChunkedOutputFilter.java:157)
	at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:220)
	at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1244)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:397)
	at org.apache.coyote.Response.action(Response.java:207)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:305)
	... 53 common frames omitted
2024-03-05 19:31:04,569 [http-nio-0.0.0.0-8080-exec-2] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
2024-03-05 19:31:05,281 [http-nio-0.0.0.0-8080-exec-9] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity> org.thingsboard.server.transport.http.DeviceApiController.postTelemetry(java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
```

![2024-03-05_21-28](https://github.com/thingsboard/thingsboard/assets/79898499/6aa45096-917b-426f-ae20-52f6ada85805)

**Comment by zzzeebra** [comment]
I'll work on it.
