### ISSUE TITLE
sum latest telemetry depend on attribute key

### ISSUE THREAD

**Issue by m3relec** [thingsboard/thingsboard#10342]
Hello
I want to collect and display the last saved data of several devices that have the same attributes.
I made the first one through the link below and then added my device, but it seems that there have been changes in the new versions.
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/function-based-on-telemetry-from-two-devices/

At first, I created a profile called Fars Power.
After the section, I created a new section named Fars and added the devices I needed in the relation section.
![asset](https://github.com/thingsboard/thingsboard/assets/45573721/d228d6f6-e8dc-403b-9df5-16acb139053f)

After the rules section, I added the following node and enabled the debug.
![rule chain](https://github.com/thingsboard/thingsboard/assets/45573721/68c47bd2-c318-4326-a8bf-4f31447f12a9)

And the debug output is like this:
`java.util.NoSuchElementException: Failed to find new originator!
	at org.thingsboard.rule.engine.transform.TbChangeOriginatorNode.lambda$transform$0(TbChangeOriginatorNode.java:74)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

Thank you for helping me solve the problem.

**Comment by AlexDoanTB** [comment]
@m3relec what are you trying to build? The error states you do not have an outbound relation from the Change originator node. In other words, you are telling the platform to change smth, but what and how to do that has not been populated. If you change the originator, the new msg author (originator) should be configured.

**Comment by m3relec** [comment]
@AlexDoanTB I have 50 devices that calculate power and store data in a telemetry.
Now I want to sum the last number stored in these 50 devices together.

**Comment by AlexDoanTB** [comment]
@m3relec ThinngsBoard has [the Aggregate Latest telemetry](https://thingsboard.io/docs/pe/user-guide/rule-engine-2-0/analytics-nodes/) analytics node for that purpose.

**Comment by m3relec** [comment]
@AlexDoanTB i use CE version and Aggregate Stream Node Does not exist in CE.

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
