### ISSUE TITLE
Device Alaram Rules Rule Node Exception After Server Restart 

### ISSUE THREAD

**Issue by kitaniman** [thingsboard/thingsboard#10439]
**Describe the bug**
I got the following exception after restarting the server, the exception was found in the rule chain in the device profile alarms action rule node debug events tab (debug mode is on). I tried removing alarms rules that use a dynamic value in their conditions and hardcoding the value but the exception was still present. Then I tried to replicate the exact same alarm rules on a new device profile and updated the devices to the new profile and the exception has disappeared (only a quick fix and doesn't solve the root cause of the issue)

org.thingsboard.server.dao.exception.IncorrectParameterException: Incorrect attribute key null
	at org.thingsboard.server.dao.service.Validator.validateString(Validator.java:58)
	at org.thingsboard.server.dao.attributes.CachedAttributesService.lambda$find$1(CachedAttributesService.java:140)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.thingsboard.server.dao.attributes.CachedAttributesService.find(CachedAttributesService.java:140)
	at org.thingsboard.rule.engine.profile.DeviceState.addEntityKeysToSnapshot(DeviceState.java:385)
	at org.thingsboard.rule.engine.profile.DeviceState.fetchLatestValues(DeviceState.java:334)
	at org.thingsboard.rule.engine.profile.DeviceState.process(DeviceState.java:147)
	at org.thingsboard.rule.engine.profile.TbDeviceProfileNode.onMsg(TbDeviceProfileNode.java:136)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:153)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:101)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:41)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Your Server Environment**
* own setup
  * Deployment: monolith (Postgres + Cassandra)
  * Deployment type: deb
  * ThingsBoard Version: 3.6.0
  * Community Edition
  * OS Name and Version: Ubuntu 22

**Your Client Environment**
* OS: Windows
* Browser: Chrome
* Version 123

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
1. Restart the server using service ThingsBoard restart.
2. Turn on debug mode in the device profile alarms action rule node.
3. Scroll down in the events tab.
4. See error.

**Expected behavior**
The message should pass as usual with no issues, as all telemetry keys and  attributes are present with nothing changed after restart, 

**Additional context**
There were no errors before restarting the server, everything was working fine. 
I also got the following error in the logs file after restart, it might be related, the ID de933eb0-deb6-11ee-8a79-6f3406ab65aa is the same as the ID of the rule node causing errors.

2024-03-25 15:32:19,298 [rule-dispatcher-3-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|de933eb0-deb6-11ee-8a79-6f3406ab65aa] Failed to init actor, attempt 1, going to stop attempts.
org.thingsboard.server.actors.TbActorException: Failed to init actor
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:72)
        at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
        at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:68)
        at org.thingsboard.server.actors.TbActorMailbox.lambda$initActor$0(TbActorMailbox.java:61)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.thingsboard.rule.engine.api.TbNodeException: Entity with id: '63da3960-a939-11ee-8326-c9726cd0d641' specified in the configuration doesn't belong to the current tenant.
        at org.thingsboard.server.actors.ruleChain.DefaultTbContext.checkTenantEntity(DefaultTbContext.java:908)
        at org.thingsboard.rule.engine.flow.TbRuleChainInputNode.init(TbRuleChainInputNode.java:56)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:173)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:64)
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
        ... 9 common frames omitted
2024-03-25 15:32:19,306 [rule-dispatcher-3-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|de938cd0-deb6-11ee-8a79-6f3406ab65aa] Failed to init actor, attempt 1, going to stop attempts.
org.thingsboard.server.actors.TbActorException: Failed to init actor
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:72)
        at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
        at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:68)
        at org.thingsboard.server.actors.TbActorMailbox.lambda$initActor$0(TbActorMailbox.java:61)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.thingsboard.rule.engine.api.TbNodeException: Entity with id: 'dcf43cc0-bb6c-11ee-bb53-0341923b2f55' specified in the configuration doesn't belong to the current tenant.
        at org.thingsboard.server.actors.ruleChain.DefaultTbContext.checkTenantEntity(DefaultTbContext.java:908)
        at org.thingsboard.rule.engine.flow.TbRuleChainInputNode.init(TbRuleChainInputNode.java:56)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:173)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:64)
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
        ... 9 common frames omitted

**Comment by ssakharova** [comment]
Hello @kitaniman,

We're letting you know that this issue, labeled as "help wanted", has been open for a while. This label is used to seek support from the GitHub community, especially for issues that fall outside the scope of the ThingsBoard support team's expertise.
Unfortunately, there hasn't been any community input or progress on this issue over the past three months. We're closing this ticket to keep our repository well-maintained and focused on active issues.

Thank you for your understanding.
