### ISSUE TITLE
AccessDenied when install on windows.

### ISSUE THREAD

**Issue by haibaoyf** [thingsboard/thingsboard#105]
2017-04-15 12:56:25,864 INFO  - Starting ServiceWrapper in the CLI mode
2017-04-15 12:56:26,020 FATAL - WMI Operation failure: AccessDenied
WMI.WmiException: AccessDenied
   在 WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   在 WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   在 WMI.Win32ServicesProxy.Create(String , String , String , ServiceType , ErrorControl , StartMode , Boolean , String , String , String[] )
   在 winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   在 winsw.WrapperService.Main(String[] args)
2017-04-15 16:36:00,375 INFO  - Starting ServiceWrapper in the CLI mode
2017-04-15 16:36:00,813 FATAL - WMI Operation failure: AccessDenied
WMI.WmiException: AccessDenied
   在 WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   在 WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   在 WMI.Win32ServicesProxy.Create(String , String , String , ServiceType , ErrorControl , StartMode , Boolean , String , String , String[] )
   在 winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   在 winsw.WrapperService.Main(String[] args)

**Comment by ashvayka** [comment]
You are probably executing the script without administrative rights, right?

**Comment by JohnzBallad** [comment]
Same with me. I had to execute the script with adminstrative rights, just like @ashvayka said. Thanks!

**Comment by ikulikov** [comment]
Closing due an inactivity.

**Comment by shrutiraoniit25** [comment]
hey !! I am stuck with the same problem does anyone have any idea how to sort my error

Uninstalling thingsboard ...
2019-07-02 10:51:37,970 INFO  - Starting ServiceWrapper in the CLI mode
2019-07-02 10:51:38,604 INFO  - Uninstalling the service with id 'thingsboard'
2019-07-02 10:51:38,621 FATAL - Failed to uninstall the service with id 'thingsboard'. WMI Error code is 'AccessDenied'
2019-07-02 10:51:38,629 FATAL - WMI Operation failure: AccessDenied
WMI.WmiException: AccessDenied
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: AccessDenied
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
DONE.

**Comment by firas22** [comment]
the same thing for me when i call the MyApp.exe install from inside powershell with cmd , the script is triggered from control-m
WMI.WmiException: AccessDenied is there a solution
