### ISSUE TITLE
How to use Notification rule node?

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#10601]
**Component**
 * Rule Node

**Description**
Wanna trigger notification rule node, but I can't sucessfully get correct  output. Can anyone help how to do this correctly??
here what I did
I see in documentation these params: 

- recipientTitle - title of the recipient (first and last name if specified, email otherwise);
- recipientEmail - email of the recipient;
- recipientFirstName - first name of the recipient;
- recipientLastName - last name of the recipient.
- values from the incoming message metadata referenced using the metadata key name;
- values from the incoming message data referenced using the data key name;
- originatorType - type of the originator, e.g. ‘Device’;
- originatorId - id of the originator;
- msgType - type of the message;
- recipientEmail - email of the recipient;
- recipientFirstName - first name of the recipient;
- recipientLastName - last name of the recipient

then I try put that in message 
```
{
    "originatorName": "ctMtr_Site2_1",
    "originatorLabel": "ctMtr_Site2_1",
    "assignee": null,
    "name": "Evisi Test Alarm",
    "status": "ACTIVE_UNACK",
    "recipientTitle": "title",
    "recipientEmail": "my_email@gmail.com",
    "recipientFirstName": "Evan",
    "recipientLastName": "-",
    "originatorType": "pzemMtr",
    "originatorId": "84ec02d0-4f6e-11ed-adf7-d96e308e8034"
}
```
that's the input, I connect it to notification rule node like this
![image](https://github.com/thingsboard/thingsboard/assets/12267053/ec89b1f0-535f-43ce-8664-5e610733a521)
but I get error output
![image](https://github.com/thingsboard/thingsboard/assets/12267053/a20ee334-4035-4fef-b427-ce56cd88e2a8)

eror
```
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:280)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
```

**Comment by evanderbird** [comment]
I just find that my input msg is not corect. I try with this message it works 

```
{
    "temp": 42,
    "humidity": 77,
    "recipientTitle": "title",
    "recipientEmail": "evan_mail@gmail",
    "recipientFirstName": "Evan",
    "recipientLastName": "-",
    "originatorId": "12162ab0-4492-11ed-adf7-d96e308e8034"
}
```
