### ISSUE TITLE
How to configure "Aggregate stream" Node on Rule Chain correctly ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1063]
Hi,

I am configuring "Aggregate Stream" Node on Thingsboard PE. I follow "User Guide" (https://thingsboard.io/docs/user-guide/rule-engine-2-0/pe/analytics-nodes/) to do the configuration. But I always receive "Failure"  with Error.

The Error Message is :

java.util.concurrent.ExecutionException: java.lang.NullPointerException 

Does anyone know how to configure it correctly ?

Or, Where can I get the material of tutorial ?

Regards,

Paul Wang

**Comment by vparomskiy** [comment]
You can use these tutorials as a reference:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/

**Comment by paulwang55** [comment]
Hi vparomskiy,


I follow the tutorial (https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/) to configure it. But I still get the error.

[https://thingsboard.io/images/thingsboard_logo.png]<https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/>

Aggregate incoming data stream<https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/>
thingsboard.io
Aggregate data about water consumption in the building




There error message is :


java.util.concurrent.ExecutionException: java.lang.NullPointerException
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
at org.thingsboard.rule.engine.analytics.incoming.TbIntervalTable.getByEntityIdAndTs(TbIntervalTable.java:116)
at org.thingsboard.rule.engine.analytics.incoming.TbSimpleAggMsgNode.onDataMsg(TbSimpleAggMsgNode.java:149)
at org.thingsboard.rule.engine.analytics.incoming.TbSimpleAggMsgNode.onMsg(TbSimpleAggMsgNode.java:134)
at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:125)
at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:91)
at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:61)
at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:58)
at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
at akka.actor.ActorCell.invoke(ActorCell.scala:495)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Optional.<init>(Optional.java:96)
at java.util.Optional.of(Optional.java:108)
at org.thingsboard.server.common.data.kv.StringDataEntry.getStrValue(StringDataEntry.java:53)
at org.thingsboard.server.common.data.kv.BasicTsKvEntry.getStrValue(BasicTsKvEntry.java:58)
at org.thingsboard.rule.engine.analytics.incoming.TbIntervalTable.lambda$fetchIntervalState$11(TbIntervalTable.java:190)
at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239)
at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229)
at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:655)
at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)


I always get the same error. I need assistance to solve this issue.


Our Thingsboard PE is running on AWS. It is the latest version.


Regards,


Paul Wang


________________________________
寄件者: vparomskiy <notifications@github.com>
寄件日期: 2018年9月11日 下午 04:40
收件者: thingsboard/thingsboard
副本: Jen-le Wang; Author
主旨: Re: [thingsboard/thingsboard] How to configure "Aggregate stream" Node on Rule Chain correctly ? (#1063)


You can use these tutorials as a reference:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-incoming-data-stream/<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fthingsboard.io%2Fdocs%2Fuser-guide%2Frule-engine-2-0%2Ftutorials%2Faggregate-incoming-data-stream%2F&data=02%7C01%7C%7C303564b96f704341357408d617c22f51%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636722520116415357&sdata=nVkZVsDSeHQ3fELQKSR5ZdbjYote0wiSrgHyDM42pBQ%3D&reserved=0>

https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fthingsboard.io%2Fdocs%2Fuser-guide%2Frule-engine-2-0%2Ftutorials%2Faggregate-latest-data%2F&data=02%7C01%7C%7C303564b96f704341357408d617c22f51%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636722520116415357&sdata=ny7Tpn6rMbirGwnMe8i%2BCaPJpQotftERzKihOwxXwXw%3D&reserved=0>

**Comment by brandlyze** [comment]
Hi Paul

I had the same issue in the PE-Version End of July. It required a bugfix for it to work. But if you have the latest version, it should be fine...

Andreas

**Comment by vparomskiy** [comment]
This bug was fixed 2 months ago. 

Please write what Thingsboard version you are using.

**Comment by paulwang55** [comment]
Hi,


I digest the information of install.log from /var/log/thingsboard.


2018-08-21 02:10:18,039 [main] INFO  o.t.s.i.ThingsboardInstallService - Starting ThingsBoard Upgrade from version 2.0.0 ...
2018-08-21 02:10:18,039 [main] INFO  o.t.s.i.ThingsboardInstallService - Upgrading ThingsBoard from version 2.0.0 to 2.1.0PE ...


I migrate Thingsboard from v2.0.0 PE to v2.1.0 PE  at 2018/08/21. We run it on AWS marketplace.


https://aws.amazon.com/marketplace/pp/B07CSTDN9W
[https://d32gc0xr2ho6pa.cloudfront.net/img/general/v2/socialPreview.png]<https://aws.amazon.com/marketplace/pp/B07CSTDN9W>

AWS Marketplace: ThingsBoard Professional Edition with ...<https://aws.amazon.com/marketplace/pp/B07CSTDN9W>
aws.amazon.com
ThingsBoard Professional Edition is a closed-source advanced version of open-source ThingsBoard IoT platform with several significant value-add features: white-labeling, platform integrations, data converters, scheduler, reporting, device and asset groups, csv/xls data export.


I hope it is useful for you to reply the solution.


Best Regards,


Paul Wang

________________________________
寄件者: vparomskiy <notifications@github.com>
寄件日期: 2018年9月12日 下午 02:44
收件者: thingsboard/thingsboard
副本: Jen-le Wang; Author
主旨: Re: [thingsboard/thingsboard] How to configure "Aggregate stream" Node on Rule Chain correctly ? (#1063)


This bug was fixed 2 months ago.

Please write what Thingsboard version you are using.

**Comment by paulwang55** [comment]
Hi vparomskiy,


Thanks for your assistance and information. We will wait for the email notification from Thingsboard.


Regards,


Paul Wang


________________________________
寄件者: vparomskiy <notifications@github.com>
寄件日期: 2018年9月19日 上午 12:25
收件者: thingsboard/thingsboard
副本: Jen-le Wang; Author
主旨: Re: [thingsboard/thingsboard] How to configure "Aggregate stream" Node on Rule Chain correctly ? (#1063)


Soon we will prepare upgrade to the latest version of the Thingsboard fro AWS marketplace image.
You will receive an email about upgrade availability.

**Comment by paulwang55** [comment]
Hi vparomskiy,

Do you know the Thingsboard fro AWS marketplace image are upgraded or not ?

We are still waiting for the lastest version to fix the current bug issue.

Regards,

Paul Wang

**Comment by vparomskiy** [comment]
new version already available
