### ISSUE TITLE
TB PE 3.6.4 installation error

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#10660]
When installing TB PE 3.6.4 on ubuntu 22.04 according to the documentation, a DB error occurs and TB does not start.
Installation is new, not an upgrade.

The queue service is using In Memory.

I get an error that the "seq_id" column is missing.

I think "seq_id" is a recently added column, but the installer may have omitted the setting.

 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.6.4PE)
 ===================================================
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: column "seq_id" of relation "edge_event" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.executeQueryFromFile(SqlAbstractDatabaseSchemaService.java:97)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:78)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:72)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:179)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

**Comment by trikimiki** [comment]
Hi!
Are you sure that DB is empty before you run the installation script?

**Comment by h-takado** [comment]
Yes, definitely.
I did not upgrade. I installed TB on a new Ubuntu installation following the instructions.

**Comment by trikimiki** [comment]
Could you also check if you connect to the right DB in the /etc/things board/conf/thingsboard.conf ?
Also, does your DB user have enough permissions to perform all operations.

**Comment by h-takado** [comment]
I don't know why, but I did a fresh install of Ubuntu again and followed the instructions, and it installed without any problems!
