### ISSUE TITLE
MQTT not working on Thingboard PE

### ISSUE THREAD

**Issue by rajatksud** [thingsboard/thingsboard#10693]
**Component**
MQTT Transport 

**Description**
 MQTT not working on Thingboard PE 3.6.4 running on ubuntu 22.04 running on Oracle Cloud. MQTT is accessible only on local host and not accessible outside. Not able to use tb-gateway, RPC and mqtt based transport. No issues with connecting to my server directly over https and all pages are opening without errors other than Post requests for RPC. 

**Environment**
 * OS:   ubuntu 22.04
 * ThingsBoard:  Thingboard PE 3.6.4
 * Browser: mozilla 125.0.2 

**Settings**
My thingsboard.conf file settings are these 
export MQTT_BIND_ADDRESS=0.0.0.0
export MQTT_BIND_PORT=1883

I have been through following trouble shooting 
`sudo iptables -L | grep 1883`
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:1883

ufw status inactive

Security list allows ingress from 0.0.0.0/0 source all destination 1883 on tcp

Network path analyzer on OCI shows that both the route to my public IP and security status is success for destination port 1883 

Checking port is listening 
`netstat -tuln | grep 1883`
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN

Checking logs related to mqtt
`cat /var/log/thingsboard/thingsboard.log | grep mqtt`
2024-05-02 05:57:50,285 [SpringApplicationShutdownHook] INFO  o.t.s.t.mqtt.MqttTransportService - Stopping MQTT transport!
2024-05-02 05:57:50,289 [SpringApplicationShutdownHook] INFO  o.t.s.t.mqtt.MqttTransportService - MQTT transport stopped!
2024-05-02 05:57:50,312 [SpringApplicationShutdownHook] INFO  o.t.s.q.c.AbstractTbQueueConsumerTemplate - Unsubscribing and stopping consumer for topics [tb_ie.downlink.mqtt.2, tb_ie.downlink.mqtt.0, tb_ie.downlink.mqtt.1]
2024-05-02 05:58:27,624 [main] INFO  o.t.s.t.mqtt.MqttTransportService - Setting resource leak detector level to DISABLED
2024-05-02 05:58:27,624 [main] INFO  o.t.s.t.mqtt.MqttTransportService - Starting MQTT transport...
2024-05-02 05:58:27,638 [main] INFO  o.t.s.t.mqtt.MqttTransportService - Mqtt transport started!
2024-05-02 05:58:38,521 [ie-downlink-consumer-74-thread-2 | MQTT] INFO  o.t.s.q.c.AbstractTbQueueConsumerTemplate - Subscribing to topics [tb_ie.downlink.mqtt.2, tb_ie.downlink.mqtt.0, tb_ie.downlink.mqtt.1]

From local ssh terminal
`mosquitto_pub -d -q 1 -h localhost -p 1883 -t v1/devices/me/telemetry -u "######################" -m "{temperature:25}"`
Client (null) sending CONNECT
Client (null) received CONNACK (0)
Client (null) sending PUBLISH (d0, q1, r0, m1, 'v1/devices/me/telemetry', ... (16 bytes))
Client (null) received PUBACK (Mid: 1, RC:0)
Client (null) sending DISCONNECT

From the internet
`mosquitto_pub -d -q 1 -h iot.pwxs.live -p 1883 -t v1/devices/me/telemetry -u "#################" -m "{temperature:25}"`
Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Any help greatly appreciated

**Comment by rajatksud** [comment]
I was able to connect my gateway to TBMQ node i hosted. I was also able to integrate TBMQ with PE server using PE Integration as well. On my gateway mqtt works with public brokers like test.mosquitto.org but not with my TB PE.
Here is the output trace from mqtt_client working with my TB PE instance
`python3 mqtt-client.py'

> `Traceback (most recent call last):
> File "/home/rajat/dev/venv/mqtt-client.py", line 7, in <module>
> client.connect()
> File "/home/rajat/dev/venv/lib/python3.11/site-packages/tb_device_mqtt.py", line 451, in connect
> self._client.connect(self.__host, self.__port, keepalive=keepalive)
> File "/home/rajat/dev/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 915, in connect
> return self.reconnect()
> ^^^^^^^^^^^^^^^^
> File "/home/rajat/dev/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1057, in reconnect
> sock = self._create_socket_connection()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/home/rajat/dev/venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 3731, in _create_socket_connection
> return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/lib/python3.11/socket.py", line 851, in create_connection
> raise exceptions[0]
> File "/usr/lib/python3.11/socket.py", line 836, in create_connection
> sock.connect(sa)
> OSError: [Errno 113] No route to host
Here is the output from same script by TBMQ instance
` python3 mqtt-client.py`
> Waiting for connection to be established before sending data to ThingsBoard!
> MQTT client was disconnected with reason code 0 (The operation completed successfully.)
same error is happening on my windows desktop. The socket.create_connection fails - if there is no tcp socket then mqtt will not work. 
@trikimiki please share any ideas to troubleshoot this further

**Comment by rajatksud** [comment]
Check on the server infrastructure side - have following 
Security List for the VCN show following List of ingress rules 

>       Stateless Source IP    Protocol      Source Port Range Destination Port Range Type   
> I.D. 0 No       0.0.0.0/0       TCP               All                       1883                            TCP traffic for ports: 1883 mqtt 

Also the NSG associated with the instance allows  non-stateless tcp traffic from 0.0.0.0/0 and ::/0 to go from any port to 1883 port and egress is allowed for all traffic
Route tables forward all 0.0.0.0/0 and ::/0 to the internet gateway
The internet gateway is associated and it works as the other ports are working only this has an issue

The connections of TBMQ (two nodes are incidently on the server side are not on 1883)
```
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      -                    off (0.00/0/0)
tcp        0      0 10.2.1.185:59366        xx.20.xx.29:1883       ESTABLISHED -                    off (0.00/0/0)
tcp        0      0 10.2.1.185:55492        xx.xx.173.254:1883      ESTABLISHED -                    off (0.00/0/0)
```

**Comment by rajatksud** [comment]
Issue is with order of iptables this entry for mqtt should be before the line which rejects traffic from all other ports. Once this line is encountered the rest of ACCEPT do not matter. Check the port with a port scanner

> REJECT all -- anywhere anywhere reject-with icmp-host-prohibited
check the order using the command below
`sudo iptables -L --line-numbers`
reorder the list by deleting the entry and adding it back as the last entry
```
sudo iptables -D INPUT 11
sudo iptables -I INPUT 20 -j REJECT --reject-with icmp-host-prohibited
```
assuming 11 was the original location and 20 is the last entry
