### ISSUE TITLE
Cannot connect to hivemq broker with certificates

### ISSUE THREAD

**Issue by bodev1406** [thingsboard/thingsboard#10865]
Hello together,

i'm using Thingsboard Cloud. 
I want to connect my thingsboard to my hivemq cloud broker. The broker using certificates for authentication. 
But i cannot connect to the broker. 
I can find only this error message:

`java.lang.RuntimeException: Failed to connect to MQTT broker at dehnvironment-hs7wis.a01.euc1.aws.hivemq.cloud:8883.
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initClient(AbstractMqttIntegration.java:266)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.init(BasicMqttIntegration.java:91)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.update(AbstractMqttIntegration.java:113)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.processUpdateEvent(DefaultIntegrationManagerService.java:633)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.update(DefaultIntegrationManagerService.java:578)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.tryUpdate(DefaultIntegrationManagerService.java:544)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.lambda$scheduleIntegrationEvent$12(DefaultIntegrationManagerService.java:718)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

I'm using the MQTT integration to etablish a connection. The integration is set up with the Authentication type PEM and the certificates are working. I tested it with a script that uses this certificates. 

Thanks for your help

**Comment by ashaforost** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the fresh ticket if this problem still exists.
