### ISSUE TITLE
Trendz version 1.11.0-RC17 error "HTTP Status 500 – Internal Server Error"

### ISSUE THREAD

**Issue by xang555** [thingsboard/thingsboard#10888]
**Component**
 * Installation

**Description**

When I run Trendz version 1.11.0-RC17 with Docker and create a new volume, I encounter an "HTTP Status 500 – Internal Server Error" when accessing Trendz. The error logs show the following details:

```
mytrendz-1      | 2024-05-29 | 08:53:18.750 | WARN  [http-nio-0.0.0.0-8888-exec-8            ] o.h.e.j.s.SqlExceptionHelper                    : SQL Error: 0, SQLState: 42703 
mytrendz-1      | 2024-05-29 | 08:53:18.751 | ERROR [http-nio-0.0.0.0-8888-exec-8            ] o.h.e.j.s.SqlExceptionHelper                    : ERROR: column customview0_.help_mode_enabled does not exist
mytrendz-1      |   Position: 89 
mytrendz-1      | 2024-05-29 | 08:53:18.753 | INFO  [http-nio-0.0.0.0-8888-exec-8            ] o.h.e.i.DefaultLoadEventListener                : HHH000327: Error performing load command 
mytrendz-1      | org.hibernate.exception.SQLGrammarException: could not extract ResultSet
mytrendz-1      |       at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
mytrendz-1      |       at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
mytrendz-1      |       at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
mytrendz-1      |       at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
mytrendz-1      |       at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
mytrendz-1      |       at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.getResultSet(AbstractLoadPlanBasedLoader.java:390)
mytrendz-1      |       at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:163)
mytrendz-1      |       at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:104)
mytrendz-1      |       at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:285)
mytrendz-1      |       at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:4437)
mytrendz-1      |       at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4427)
mytrendz-1      |       at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:576)
mytrendz-1      |       at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:544)
mytrendz-1      |       at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208)
mytrendz-1      |       at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:332)
mytrendz-1      |       at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108)
mytrendz-1      |       at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74)
mytrendz-1      |       at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:110)
mytrendz-1      |       at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1186)
mytrendz-1      |       at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1175)
mytrendz-1      |       at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:193)
mytrendz-1      |       at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2786)
mytrendz-1      |       at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2767)
mytrendz-1      |       at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2723)
mytrendz-1      |       at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2767)
mytrendz-1      |       at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3322)
mytrendz-1      |       at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3289)
mytrendz-1      |       at jdk.internal.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
mytrendz-1      |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mytrendz-1      |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
mytrendz-1      |       at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:311)
mytrendz-1      |       at com.sun.proxy.$Proxy129.find(Unknown Source)
mytrendz-1      |       at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById(SimpleJpaRepository.java:282)
mytrendz-1      |       at jdk.internal.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
mytrendz-1      |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mytrendz-1      |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
mytrendz-1      |       at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289)
mytrendz-1      |       at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
mytrendz-1      |       at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
mytrendz-1      |       at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:524)
mytrendz-1      |       at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
mytrendz-1      |       at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:531)
mytrendz-1      |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
mytrendz-1      |       at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:156)
mytrendz-1      |       at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131)
mytrendz-1      |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
mytrendz-1      |       at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
mytrendz-1      |       at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
mytrendz-1      |       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
mytrendz-1      |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
mytrendz-1      |       at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
mytrendz-1      |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
mytrendz-1      |       at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
mytrendz-1      |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
mytrendz-1      |       at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
mytrendz-1      |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
mytrendz-1      |       at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
mytrendz-1      |       at com.sun.proxy.$Proxy139.findById(Unknown Source)
mytrendz-1      |       at org.thingsboard.trendz.dao.customize.CustomViewSettingsDao.findCustomSettings(CustomViewSettingsDao.java:23)
mytrendz-1      |       at org.thingsboard.trendz.service.customize.CustomizationService.lambda$provideCustomViewSettings$2(CustomizationService.java:236)
mytrendz-1      |       at org.springframework.cache.caffeine.CaffeineCache$LoadFunction.apply(CaffeineCache.java:168)
mytrendz-1      |       at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2029)
mytrendz-1      |       at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
mytrendz-1      |       at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2027)
mytrendz-1      |       at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2010)
mytrendz-1      |       at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
mytrendz-1      |       at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
mytrendz-1      |       at org.springframework.cache.caffeine.CaffeineCache.get(CaffeineCache.java:90)
mytrendz-1      |       at org.thingsboard.trendz.service.customize.CustomizationService.provideCustomViewSettings(CustomizationService.java:234)
mytrendz-1      |       at org.thingsboard.trendz.service.customize.CustomizationService.getCustomViewSettings(CustomizationService.java:133)
mytrendz-1      |       at org.thingsboard.trendz.service.customize.CustomizationService.getCustomViewSettings(CustomizationService.java:122)
mytrendz-1      |       at org.thingsboard.trendz.interceptor.WhitelabelingRedirectionInterceptor.preHandle(WhitelabelingRedirectionInterceptor.java:41)
mytrendz-1      |       at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
mytrendz-1      |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1059)
mytrendz-1      |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
mytrendz-1      |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
mytrendz-1      |       at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
mytrendz-1      |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
mytrendz-1      |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
mytrendz-1      |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
mytrendz-1      |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:106)
mytrendz-1      |       at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
mytrendz-1      |       at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:87)
mytrendz-1      |       at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
mytrendz-1      |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
mytrendz-1      |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
mytrendz-1      |       at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
mytrendz-1      |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
mytrendz-1      |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
mytrendz-1      |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
mytrendz-1      |       at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
mytrendz-1      |       at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
mytrendz-1      |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
mytrendz-1      |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
mytrendz-1      |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
mytrendz-1      |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
mytrendz-1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
mytrendz-1      |       at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
mytrendz-1      |       at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
mytrendz-1      |       at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
mytrendz-1      |       at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
mytrendz-1      |       at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:390)
mytrendz-1      |       at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:249)
mytrendz-1      |       at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:344)
mytrendz-1      |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
mytrendz-1      |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
mytrendz-1      |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
mytrendz-1      |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
mytrendz-1      |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
mytrendz-1      |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
mytrendz-1      |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
mytrendz-1      |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
mytrendz-1      |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
mytrendz-1      |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
mytrendz-1      |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
mytrendz-1      |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
mytrendz-1      |       at java.base/java.lang.Thread.run(Thread.java:829)
mytrendz-1      | Caused by: org.postgresql.util.PSQLException: ERROR: column customview0_.help_mode_enabled does not exist
mytrendz-1      |   Position: 89
mytrendz-1      |       at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
mytrendz-1      |       at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
mytrendz-1      |       at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
mytrendz-1      |       at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
mytrendz-1      |       at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
mytrendz-1      |       at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
mytrendz-1      |       at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
mytrendz-1      |       at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
mytrendz-1      |       at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
mytrendz-1      |       at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)

```

this is my `docker-compose.yml`
```yaml

version: '3.0'

services:
  mytrendz:
    restart: always
    image: "thingsboard/trendz:1.11.0-RC17"
    ports:
      - "8899:8888"
    environment:
      TB_API_URL: http://mytb:9090
      TRENDZ_LICENSE_SECRET:xxxxxxxxxxxxxxxxx
      TRENDZ_LICENSE_INSTANCE_DATA_FILE: /data/license.data
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trendz
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SCRIPT_ENGINE_PROVIDER: DOCKER_CONTAINER
      SCRIPT_ENGINE_DOCKER_PROVIDER_URL: mypyexecutor:8181
      SCRIPT_ENGINE_TIMEOUT: 30000
    volumes:
      - mytrendz-rc17-data:/data
      - mytrendz-rc17-logs:/var/log/trendz
    networks:
      - tbnet
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: '3G'
        reservations:
          cpus: '0.5'
          memory: '1G'

  mypyexecutor:
    restart: always
    image: "thingsboard/trendz-python-executor:1.11.0-RC17"
    ports:
      - "8181:8181"
    environment:
      MAX_HEAP_SIZE: 750M
      SCRIPT_ENGINE_RUNTIME_TIMEOUT: 30000
      EXECUTOR_MANAGER: 1
      EXECUTOR_SCRIPT_ENGINE: 6
      THROTTLING_QUEUE_CAPACITY: 10
      THROTTLING_THREAD_POOL_SIZE: 6
      NETWORK_BUFFER_SIZE: 5242880
    networks:
      - tbnet
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: '3G'
        reservations:
          cpus: '0.5'
          memory: '1G'

  postgres:
    restart: always
    image: "postgres:15"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: trendz
      POSTGRES_PASSWORD: postgres
    volumes:
      - mytrendz-rc17-db:/var/lib/postgresql/data
    networks:
      - tbnet
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: '3G'
        reservations:
          cpus: '0.5'
          memory: '1G'


volumes:
  mytrendz-rc17-data:
    driver: local
  mytrendz-rc17-logs:
    driver: local
  mytrendz-rc17-db:
    driver: local


networks:
  tbnet:
    external: true


```

How can I fix this?

# Environment

- OS: Ubuntu
- ThingsBoard CE: 3.6.4 (installed using Docker)
- Trendz: 1.11.0-RC17 (installed using Docker)

**Comment by Ltutamen** [comment]
Hello,
This is known issue, to fix it please use latest version of Trendz from [docker hub](https://hub.docker.com/r/thingsboard/trendz/tags) - use latest image tagged '1.11.0'.
Also, to add missing column to database, use upgrade guide [from here](https://thingsboard.io/docs/trendz/install/docker/#upgrade-trendz-service)
Based on the guide, steps to fix should look like this:
 - run `docker compose exec mytrendz sh -c "echo '1.10.3' > /data/.upgradeversion" ` command
 - update docker image to 1.11.0 inside docker-compose.yml
 - run 
  ```
 docker compose stop mytrendz
   docker compose up -d
```
to restart Trendz. 
This should fix the issue, but if you encounter any problem, tell us.
