### ISSUE TITLE
NPE - Failed to parse constant value from filter: AlarmConditionFilter

### ISSUE THREAD

**Issue by sudhirbits** [thingsboard/thingsboard#10939]
**Describe the bug**

Exception stack trace: 
2024-06-05 13:27:01,532 [rule-dispatcher-0-8] WARN  o.t.r.engine.profile.AlarmRuleState - Failed to parse constant value from filter: AlarmConditionFilter(key=AlarmConditionFilterKey(type=CONSTANT, key=deviceIsInactive), valueType=BOOLEAN, value=null, predicate=BooleanFilterPredicate(operation=EQUAL, value=FilterPredicateValue(defaultValue=false, userValue=null, dynamicValue=DynamicValue(resolvedValue=null, sourceType=CURRENT_DEVICE, sourceAttribute=active, inherit=false))))
java.lang.NullPointerException: null
        at org.thingsboard.rule.engine.profile.AlarmRuleState.getConstantValue(AlarmRuleState.java:347)
        at org.thingsboard.rule.engine.profile.AlarmRuleState.eval(AlarmRuleState.java:329)
        at org.thingsboard.rule.engine.profile.AlarmRuleState.eval(AlarmRuleState.java:126)
        at org.thingsboard.rule.engine.profile.AlarmState.createOrClearAlarms(AlarmState.java:103)
        at org.thingsboard.rule.engine.profile.AlarmState.process(AlarmState.java:79)
        at org.thingsboard.rule.engine.profile.DeviceState.processAttributes(DeviceState.java:261)
        at org.thingsboard.rule.engine.profile.DeviceState.processDeviceActivityEvent(DeviceState.java:183)
        at org.thingsboard.rule.engine.profile.DeviceState.process(DeviceState.java:155)
        at org.thingsboard.rule.engine.profile.TbDeviceProfileNode.onMsg(TbDeviceProfileNode.java:136)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:158)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:101)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
        at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:41)
        at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type: deb
  * ThingsBoard Version: 3.6.4
  * Community or Professional Edition: CE
  * OS Name and Version: Ubuntu 22.

**Comment by Ultrazombie** [comment]
Hello @sudhirbits,
Could you please provide detailed steps to reproduce to investigate this bug.

**Comment by sudhirbits** [comment]
Hi @Ultrazombie 

I am just seeing these messages in the thingsboard.log 
There are corresponding NullPointerException shown in the API Usage --> Rule Engine Statistics also. 

My Device Profile is configured for Activity and Inactivity as follows: 
![image](https://github.com/thingsboard/thingsboard/assets/838136/46acf633-d307-4c22-bab3-90bc3a85da65)
![image](https://github.com/thingsboard/thingsboard/assets/838136/21faf2ae-2b53-4f77-9bde-9ff89955a4d6)

Is there a possibility that device attribute for `state` is sometimes being queried as `null`?

**Comment by sudhirbits** [comment]
@Ultrazombie hi. Do let me know if more info is needed.

**Comment by sudhirbits** [comment]
@Ultrazombie we keep seeing these exceptions in the logs, is there any solution to this?

**Comment by mykhailokornieiev** [comment]
Hi. 
The root cause is probably in the Device Profile alarm rule settings. Although the alarm rule is configured to use a static duration, it is displayed as dynamic in the Device profile. This likely causes the Device Profile rule node to attempt to retrieve a non-existent attribute from the device, resulting in the NullPointerException. Please refer to the screenshots below for clarity
We previously added to our backlog a ticket for a product team.
As a temporary workaround, you need to reinitialize the alarm rules that use a duration condition for each Device Profile. 
For this, you need to edit Alarm Rule, change condition type (Duration → Simple, for instance), save it, and then change it back.
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
