### ISSUE TITLE
tb-web-report failing after 3.7 pe upgrade

### ISSUE THREAD

**Issue by manuelalvarez** [thingsboard/thingsboard#11109]
Hello,

**Component**
tb-web-report

**Description**
After upgrading to TB-3.7-PE, tb-web-report fails to start:

```
root@app:~# sudo service tb-web-report status
● tb-web-report.service - tb-web-report
     Loaded: loaded (/lib/systemd/system/tb-web-report.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-06-30 12:37:40 UTC; 1s ago
    Process: 2545 ExecStart=/usr/share/tb-web-report/init/tb-web-report (code=exited, status=1/FAILURE)
   Main PID: 2545 (code=exited, status=1/FAILURE)
        CPU: 1.001s

Jun 30 12:37:37 app systemd[1]: Started tb-web-report.
Jun 30 12:37:37 app tb-web-report[2557]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Jun 30 12:37:37 app tb-web-report[2557]: WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
Jun 30 12:37:40 app systemd[1]: tb-web-report.service: Main process exited, code=exited, status=1/FAILURE
Jun 30 12:37:40 app systemd[1]: tb-web-report.service: Failed with result 'exit-code'.
Jun 30 12:37:40 app systemd[1]: tb-web-report.service: Consumed 1.001s CPU time.
```

Getting theses errors in the log:

```
2024-06-30 12:37:37,918 [ReportController] ERROR: uncaughtException: Configuration property "browser.useNewPage" is not defined
Error: Configuration property "browser.useNewPage" is not defined
    at Config.get (/snapshot/web-report/node_modules/config/lib/config.js:182:11)
    at Object.<anonymous> (/snapshot/web-report/target/src/api/controllers/tbWebReportPage.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/web-report/target/src/api/controllers/tbWebReportPageQueue.js):
Error: Configuration property "browser.useNewPage" is not defined
    at Config.get (/snapshot/web-report/node_modules/config/lib/config.js:182:11)
    at Object.<anonymous> (/snapshot/web-report/target/src/api/controllers/tbWebReportPage.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/web-report/target/src/api/controllers/tbWebReportPageQueue.js)

```

**Environment**
 * OS:  Debian 11
 * ThingsBoard: 3.7 PE

I have tried uninstalling tb-web-report and re-installing and have had no luck. tb-web-report working fine with 3.6.4. 

Please advise.

Regards,

Manuel.-

**Comment by manuelalvarez** [comment]
Ok, I fixed it by adding to my tb-web-report yml file:

# This parameter determines whether to create a new page for each web report.
  # When set to 'true', each web report will open on a separate page, providing clear separation and convenient viewing of reports.
  #
  # Caution:
  # - If this parameter is enabled ('true'), data caching functionality will be disabled.
  #   This means that data for each report will be reloaded every time the report is opened,
  #   which may increase page load times and server load.
  # - When this parameter is disabled ('false'), all web reports will open on a single page,
  #   allowing caching to be used for improved performance and faster page loading.
  useNewPage: "false"
