### ISSUE TITLE
How to solve "java.lang.OutOfMemoryError: Java heap space" ?

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1111]
Hi,

We are using "ThingsBoard Professional Edition ::       (v2.1.0PE)". We subscribe the TB PE2.0 from AWS marketplace.

We did not modify any default configuration about Thingsboard PE 2.1.0. We will get the following error message from Thingsboard PE 2.1.0 when we restart the related EC2 instance.

Here are error messages. Please review it.

Does anyone know how to solve this error ?  We need the solution and detail procedure to solve it.

Here is our OS version information :
Linux ip-xxx-xx-xx-xx **4.15.0-1023-aws #23-Ubuntu SMP Mon Sep 24 16:31:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

 ===================================================
 :: ThingsBoard Professional Edition ::       (v2.1.0PE)
 ===================================================

java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1130.hprof ...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5d9b013cbb, pid=1130, tid=0x00007f5d84fff700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x699cbb]  java_lang_Class::signers(oopDesc*)+0x1b
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/share/thingsboard/bin/hs_err_pid1130.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

 ===================================================
 :: ThingsBoard Professional Edition ::       (v2.1.0PE)
 ===================================================

java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1125.hprof ...
Dump file is incomplete: No space left on device

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "https-jsse-nio-0.0.0.0-8080-ClientPoller-1"
SLF4J: Failed toString() invocation on an object of type [org.thingsboard.server.common.data.id.IntegrationId]
Exception in thread "pool-6-thread-1199" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at java.lang.String.substring(String.java:1933)
        at java.util.UUID.digits(UUID.java:386)
        at java.util.UUID.toString(UUID.java:379)
        at org.thingsboard.server.common.data.id.UUIDBased.toString(UUIDBased.java:83)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:305)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:277)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:231)
        at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
        at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
        at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
        at ch.qos.logback.classic.Logger.info(Logger.java:587)
        at org.thingsboard.server.service.integration.mqtt.basic.BasicMqttIntegration$1.connectionLost(BasicMqttIntegration.java:77)
        at org.thingsboard.mqtt.MqttClientImpl.lambda$null$0(MqttClientImpl.java:149)
        at org.thingsboard.mqtt.MqttClientImpl$$Lambda$56/1845562791.operationComplete(Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$CloseFuture.setClos ===================================================
 :: ThingsBoard Professional Edition ::       (v2.1.0PE)
 ===================================================

 ===================================================
 :: ThingsBoard Professional Edition ::       (v2.1.0PE)
 ===================================================

**Comment by vparomskiy** [comment]
Please provide full log files for investigation

**Comment by paulwang55** [comment]
Hi vparomskiy,

The log files are "thingsboard.log", "thingsboard.out" and "thingsboard.2018-10-04.423.log".

[thingsboard.log](https://github.com/thingsboard/thingsboard/files/2448663/thingsboard.log)

Please use the following link to download full files. Because "thingsboard.2018-10-04.423.log" are too big ( about 20M bytes), I can not put it into GitHub.

[Log Files - thingsboard.log, thingsboard.out, thingsboard.2018-10-04.423.log](https://www.dropbox.com/sh/nl4jaapf6pqm0p6/AABHPYl9nTXcPGi1fos6ah-Oa?dl=0)

Please review it and help us to solve this issues.

Thanks.

**Comment by vparomskiy** [comment]
It is a known issue that is resolved in the next Thingsboard PE release. We are working on releasing the new version in the nearest time.

**Comment by paulwang55** [comment]
Hi vparomskiy,

Do you know when the next Thingsboard PE will be released ? Our Thingsboard PE 2.1 is running on AWS (We pay the service through AWS marketplace to thingsboard). We also wait for the fix of "aggregate stream"  (Rule Chain).

Before the new Thingsboard PE released, What is the workaround solution ?

We need the futher suggestion. 

Thanks,

Regards,

Paul Wang

**Comment by vparomskiy** [comment]
new version is already available.
