### ISSUE TITLE
How to send alarm to email? Help me pls ;-;

### ISSUE THREAD

**Issue by GKritZAZA** [thingsboard/thingsboard#11130]
![image](https://github.com/thingsboard/thingsboard/assets/97632533/aaae44d9-5ce4-49e1-98fb-784c749b825b)
![image](https://github.com/thingsboard/thingsboard/assets/97632533/ea2e3ac4-d06f-47a0-a09f-1bb451ae6d17)
![image](https://github.com/thingsboard/thingsboard/assets/97632533/e787eeb7-2d87-4e6d-9be9-59b2c0d5508d)
![image](https://github.com/thingsboard/thingsboard/assets/97632533/cd9ab1e6-8720-4d6f-8fe0-544afcb37b91)
![image](https://github.com/thingsboard/thingsboard/assets/97632533/1f3ac16e-4c98-40e0-b08a-29568602da29)
![image](https://github.com/thingsboard/thingsboard/assets/97632533/b150001f-c905-48ec-b29e-f39cbb1a48a0)

**Comment by Backdraft007** [comment]
You can enable "Debug" on your nodes and see what happen or shows errors.

**Comment by GKritZAZA** [comment]
> You can enable "Debug" on your nodes and see what happen or shows errors.

![image](https://github.com/thingsboard/thingsboard/assets/97632533/98012ac0-7e62-402c-a059-d0af8e13f334)
I opened it but didn't see anything in the Event. It was empty.
![image](https://github.com/thingsboard/thingsboard/assets/97632533/653b1aba-69e0-4de7-b94f-9fddd6500ca0)

**Comment by Backdraft007** [comment]
You have to save the whole rule chain not only the node to activate the debug mode. When you don't get any data in tthat node, the error occurs in the previous node.
Enable debug on all nodes to see where the error occurs.

**Comment by AldirchEugene** [comment]
If an alarm occurs, you need to clear the alarm and then try generating the alarm again. You can debug each node one by onev

**Comment by GKritZAZA** [comment]
I found it but it says
org.thingsboard.server.common.data.exception.ThingsboardException: Unable to send mail: org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 450 The from.email domain must be verified in your account to send emails. #MS42207 The from.email domain must be verified in your account to send emails. #MS42207
; message exceptions (1) are:
Failed message 1: com.sun.mail.smtp.SMTPSendFailedException: 450 The from.email domain must be verified in your account to send emails. #MS42207 The from.email domain must be verified in your account to send emails. #MS42207

	at org.thingsboard.server.service.mail.DefaultMailService.handleException(DefaultMailService.java:445)
	at org.thingsboard.server.service.mail.DefaultMailService.sendMail(DefaultMailService.java:244)
	at org.thingsboard.server.service.mail.DefaultMailService.send(DefaultMailService.java:211)
	at org.thingsboard.rule.engine.mail.TbSendEmailNode.sendEmail(TbSendEmailNode.java:91)
	at org.thingsboard.rule.engine.mail.TbSendEmailNode.lambda$onMsg$0(TbSendEmailNode.java:77)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Backdraft007** [comment]
Put your gmail address in "From email".

**Comment by GKritZAZA** [comment]
> Put your gmail address in "From email". Why is the smtp host brevo.com?

Thank you very much after I use smtp.gmail.com I was able to send an email that I used brevo because my friend recommended it.

**Comment by Civilduino** [comment]
Had the same problem. As @Backdraft007 wrote, it is important to have the same domain in your email as the one you register in your email sending service, in this case in the Brevo.com settings.
For example, if you register `updates.mydomain.com` then your email should be `test@updates.mydomain.com`
