### ISSUE TITLE
Saving telemetry back in time

### ISSUE THREAD

**Issue by norex94** [thingsboard/thingsboard#11214]
**Component**
 * Rule Engine

**Description**
I am trying to save telemetry data back in time in a rule chain. While I can save telemetry from the date 01.08.2023, I encounter an error when attempting to add data from 01.07.2023. The issue occurs specifically with the date we started using Thingsboard PE self-hosted. Below is the data I am trying to save:
```
[{
        "ts": 1688169600000,
        "values": {
            "kw": 474
        }
    }, {
        "ts": 1688173200000,
        "values": {
            "kw": 474
        }
    }, {
        "ts": 1688176800000,
        "values": {
            "kw": 474
        }
    }, {
....

```
When attempting to save this data, I receive the following error:
```
java.lang.RuntimeException: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [CREATE TABLE IF NOT EXISTS ts_kv_2023_07 PARTITION OF ts_kv FOR VALUES FROM (1688169600000) TO (1690848000000)]; ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row; nested exception is org.postgresql.util.PSQLException: ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row
	at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.savePartition(JpaSqlTimeseriesDao.java:171)
	at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.savePartitionIfNotExist(JpaSqlTimeseriesDao.java:152)
	at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.save(JpaSqlTimeseriesDao.java:99)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.doSaveAndRegisterFuturesFor(BaseTimeseriesService.java:244)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.saveWithoutLatestAndRegisterFutures(BaseTimeseriesService.java:236)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.doSave(BaseTimeseriesService.java:215)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.saveWithoutLatest(BaseTimeseriesService.java:205)
	at org.thingsboard.server.service.telemetry.DefaultTelemetrySubscriptionService.saveWithoutLatestAndNotifyInternal(DefaultTelemetrySubscriptionService.java:199)
	at org.thingsboard.server.service.telemetry.DefaultTelemetrySubscriptionService.doSaveAndNotify(DefaultTelemetrySubscriptionService.java:161)
	at org.thingsboard.server.service.telemetry.DefaultTelemetrySubscriptionService.saveWithoutLatestAndNotify(DefaultTelemetrySubscriptionService.java:150)
	at org.thingsboard.rule.engine.telemetry.TbMsgTimeseriesNode.onMsg(TbMsgTimeseriesNode.java:123)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:173)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:116)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:75)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:56)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:172)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [CREATE TABLE IF NOT EXISTS ts_kv_2023_07 PARTITION OF ts_kv FOR VALUES FROM (1688169600000) TO (1690848000000)]; ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row; nested exception is org.postgresql.util.PSQLException: ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:393)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:431)
	at org.thingsboard.server.dao.sqlts.insert.sql.SqlPartitioningRepository.save(SqlPartitioningRepository.java:67)
	at org.thingsboard.server.dao.sqlts.insert.sql.SqlPartitioningRepository$$FastClassBySpringCGLIB$$7d66494c.invoke(<ge

```
Is there a parameter that needs to be adjusted to save telemetry back in time or is some other issue? 

**Environment**
OS: Ubuntu 20.04
ThingsBoard: v3.3.2PE
Browser: Chrome 91.0.4472.114

**Comment by mykhailokornieiev** [comment]
Hi
Could you please provide thignsboard.conf and the output of the \d+ ts_kv command from psql in the thignsboard table? It seems that ts_kv_indefinite intersects with other tables.

**Comment by norex94** [comment]
Output of command:

```
thingsboard=# \dt+ ts_kv
                           List of relations
 Schema | Name  |       Type        |  Owner   |  Size   | Description 
--------+-------+-------------------+----------+---------+-------------
 public | ts_kv | partitioned table | postgres | 0 bytes | 
(1 row)
```
And the conf file:
```
export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/data"
export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/thingsboard/${TB_SERVICE_ID}-heapdump.bin"
export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
export JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError"
export LOG_FILENAME=thingsboard.out
export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
```

I think we will manually add the data to the table, but would be nice to know why this happens. 

Cheers

**Comment by mykhailokornieiev** [comment]
Please provide output of `/d+ ts_kv` command, not `/dt+`

**Comment by norex94** [comment]
[d.log](https://github.com/user-attachments/files/16267353/d.log)
Sorry.

**Comment by mykhailokornieiev** [comment]
You've sent list of all tables, but it's necessary to check the relations
Please provide an output of `/d+ ts_kv;`

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by cos-gl** [comment]
Sorry if I reopen this issue but I have a very similar behaviour and I don't want to open a new issue if the problem is the same.
I have a quite similar situation, probably some telemetry data of the 31 of July was sent on 01 og August. Can you help me?

The log output is quite the same as the OC

```
java.lang.RuntimeException: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [CREATE TABLE IF NOT EXISTS ts_kv_2024_07_01 PARTITION OF ts_kv FOR VALUES FROM (1719792000000) TO (1719878400000)]; ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row
        at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.savePartition(JpaSqlTimeseriesDao.java:159)
        at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.savePartitionIfNotExist(JpaSqlTimeseriesDao.java:140)
[...]
```

I have a postgresql db (no timescale, no cassandra) with this configuration (I'm using daily partitioning)

```
export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/data"
export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard/gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError"
export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
export LOG_FILENAME=thingsboard.out
export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql
# DB Configuration
export DATABASE_TS_TYPE=sql
export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/thingsboard
export SPRING_DATASOURCE_USERNAME=xxxx
export SPRING_DATASOURCE_PASSWORD=xxxx
# Specify partitioning size for timestamp key-value storage. Allowed values: DAYS, MONTHS, YEARS, INDEFINITE.
export SQL_POSTGRES_TS_KV_PARTITIONING=DAYS
export TB_QUEUE_TYPE=rabbitmq
export TB_QUEUE_RABBIT_MQ_USERNAME=yyyy
export TB_QUEUE_RABBIT_MQ_PASSWORD=yyyy
export TB_QUEUE_RABBIT_MQ_HOST=localhost
export TB_QUEUE_RABBIT_MQ_PORT=5672
```

This is the output of the tables ts_kv in postgres (started to use this server in July):

```
thingsboard=# \d+ ts_kv
                                                Partitioned table "public.ts_kv"
  Column   |            Type             | Collation | Nullable | Default | Storage  | Compression | Stats target | Description
-----------+-----------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 entity_id | uuid                        |           | not null |         | plain    |             |              |
 key       | integer                     |           | not null |         | plain    |             |              |
 ts        | bigint                      |           | not null |         | plain    |             |              |
 bool_v    | boolean                     |           |          |         | plain    |             |              |
 str_v     | character varying(10000000) |           |          |         | extended |             |              |
 long_v    | bigint                      |           |          |         | plain    |             |              |
 dbl_v     | double precision            |           |          |         | plain    |             |              |
 json_v    | json                        |           |          |         | extended |             |              |
Partition key: RANGE (ts)
Indexes:
    "ts_kv_pkey" PRIMARY KEY, btree (entity_id, key, ts)
Partitions: ts_kv_2024_07_08 FOR VALUES FROM ('1720396800000') TO ('1720483200000'),
            ts_kv_2024_07_09 FOR VALUES FROM ('1720483200000') TO ('1720569600000'),
            ts_kv_2024_07_10 FOR VALUES FROM ('1720569600000') TO ('1720656000000'),
            ts_kv_2024_07_11 FOR VALUES FROM ('1720656000000') TO ('1720742400000'),
            ts_kv_2024_07_12 FOR VALUES FROM ('1720742400000') TO ('1720828800000'),
            ts_kv_2024_07_13 FOR VALUES FROM ('1720828800000') TO ('1720915200000'),
            ts_kv_2024_07_14 FOR VALUES FROM ('1720915200000') TO ('1721001600000'),
            ts_kv_2024_07_15 FOR VALUES FROM ('1721001600000') TO ('1721088000000'),
            ts_kv_2024_07_16 FOR VALUES FROM ('1721088000000') TO ('1721174400000'),
            ts_kv_2024_07_17 FOR VALUES FROM ('1721174400000') TO ('1721260800000'),
            ts_kv_2024_07_18 FOR VALUES FROM ('1721260800000') TO ('1721347200000'),
            ts_kv_2024_07_19 FOR VALUES FROM ('1721347200000') TO ('1721433600000'),
            ts_kv_2024_07_20 FOR VALUES FROM ('1721433600000') TO ('1721520000000'),
            ts_kv_2024_07_21 FOR VALUES FROM ('1721520000000') TO ('1721606400000'),
            ts_kv_2024_07_22 FOR VALUES FROM ('1721606400000') TO ('1721692800000'),
            ts_kv_2024_07_23 FOR VALUES FROM ('1721692800000') TO ('1721779200000'),
            ts_kv_2024_07_24 FOR VALUES FROM ('1721779200000') TO ('1721865600000'),
            ts_kv_2024_07_25 FOR VALUES FROM ('1721865600000') TO ('1721952000000'),
            ts_kv_2024_07_26 FOR VALUES FROM ('1721952000000') TO ('1722038400000'),
            ts_kv_2024_07_27 FOR VALUES FROM ('1722038400000') TO ('1722124800000'),
            ts_kv_2024_07_28 FOR VALUES FROM ('1722124800000') TO ('1722211200000'),
            ts_kv_2024_07_29 FOR VALUES FROM ('1722211200000') TO ('1722297600000'),
            ts_kv_2024_07_30 FOR VALUES FROM ('1722297600000') TO ('1722384000000'),
            ts_kv_2024_07_31 FOR VALUES FROM ('1722384000000') TO ('1722470400000'),
            ts_kv_indefinite DEFAULT


```

OS: Ubuntu 24.04
Thingsboard version: 3.7.0-1 (installed using apt)
Java version: openjdk-17-jre | java17-runtime | oracle-java17-installer | openjdk-17-jre-headless

Thanks a lot!

**Comment by mykhailokornieiev** [comment]
Hi @cos-gl 
Please specify if you experimented with `SQL_POSTGRES_TS_KV_PARTITIONING` parameter and with partitioning in general. If yes, then how exactly?

**Comment by cos-gl** [comment]
Sorry @mykhailokornieiev, I didn't see the notification about your comment.
Yes, you are right, I started using TB with monthly partitioning and after changed to daily... this was the reason of the mess. 
Thankyou!

**Comment by mykhailokornieiev** [comment]
Hi. Thank you for clarifying. In this case, I close ticket as solved
