### ISSUE TITLE
Rule engine can't load entity fields from Integration

### ISSUE THREAD

**Issue by willjones9** [thingsboard/thingsboard#11237]
I have a device, and an integration linked to said device. I need to set a rule chain up so that when I update certain attributes, it pushes a downlink to that device. Given that I may have multiple integrations, I need to be able to dynamically select the integration. 

When I update the attribute, I'm attempting to get the integration by using the "related entity data" node, and I get the following exception:

org.thingsboard.rule.engine.api.TbNodeException: Unexpected originator EntityType: INTEGRATION
at org.thingsboard.rule.engine.util.EntitiesFieldsAsyncLoader.findAsync(EntitiesFieldsAsyncLoader.java:86)
at org.thingsboard.rule.engine.metadata.TbAbstractGetMappedDataNode.getEntityFieldsAsync(TbAbstractGetMappedDataNode.java:135) 
at org.thingsboard.rule.engine.metadata.TbAbstractGetMappedDataNode.processFieldsData(TbAbstractGetMappedDataNode.java:67)
at org.thingsboard.rule.engine.metadata.TbAbstractGetEntityDataNode.processDataAndTell(TbAbstractGetEntityDataNode.java:83)
at org.thingsboard.rule.engine.metadata.TbAbstractGetEntityDataNode.lambda$onMsg$0(TbAbstractGetEntityDataNode.java:61)
	at org.thingsboard.common.util.DonAsynchron$1.onSuccess(DonAsynchron.java:55)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

Your Server Environment

Kubernetes deployment in AWS using MSK & Elasticache for Redis
ThingsBoard Version 3.7.0
Your Client Environment
Desktop (please complete the following information):
OS: MacOS 14.4.1
Browser: Safari 17.4.1

Related entity data node in rule engine

To Reproduce

Have an integration create a device, so there is a relation named "ManagedByIntegration" that links to your integration
In Rule Engine create message type switch and related entity data nodes and link the first to the second via attributes updated.
In the related entity data node, direction should be "To Originator" and relation type should be "ManagedByIntegration"
Expected behavior
The expected behaviour is that the "originator fields" node could load the fields without errors.

Manually linking an integration via the UI and configuring the related entity data node so that relation type is "Contains" also results in the same error.

**Comment by Torya121** [comment]
Hey @willjones9 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID LIK07638
Please see the link below to our dedicated support line:
[chainlink Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by ashaforost** [comment]
Hi @willjones9 

ThingsBoard rule nodes were not designed for this use case, where you want to retrieve entity fields from an Integration. 
Instead, you can set a metadata key 'IntegrationName', for example, and save this key to the device attributes. After this, you can use it in the rule engine to route your downlink message to an appropriate integration.
![image](https://github.com/user-attachments/assets/77e7d875-c0c8-49c8-aded-74d3d95dd0bc)

**Comment by willjones9** [comment]
I see. That's a bit strange, considering this screenshot suggests otherwise:

<img width="756" alt="image" src="https://github.com/user-attachments/assets/b88415ab-b0f2-4ced-ab47-5cc77a13a0f0">

In any case, is it then possible to dynamically select the integration to use in the integration downlink node? I'd like to avoid the overhead of having to modify rule chains whenever a new integration gets added

**Comment by ashaforost** [comment]
it's not possible to dynamically select an integration, so, as a workaround, you can create a routing section in your rule chain that will pass the message to one of several 'integration downlink' rule nodes. 
In any case, it may be a useful addition to our platform to allow dynamic integration selection in the 'integration downlink' rule node based on the relation the device and integration already have. I've created a feature request for our developers to review.

**Comment by mykhailokornieiev** [comment]
Hi. The feature request was previously added to our backlog for developers.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.
