### ISSUE TITLE
TBEL / Rule Chain script: Is p.key property of map.entrySet() consumed?

### ISSUE THREAD

**Issue by lukas-k** [thingsboard/thingsboard#11377]
**Describe the bug**
This bug first occurs after updating to v3.7.0.

Before v3.7.0, we were successfully using these lines of code in a TBEL script node:

```
foreach( p : msg.entrySet()) {
    if(whitelist.indexOf(p.key) >= 0) {
        res[p.key] = p.value;
    }
}
```

After upgrading to v3.7.0, the execution exits with the following error:

```
org.thingsboard.script.api.TbScriptException: [Error: unknown exception in expression: p.key]
[Near : {... oreach( p : msg.entrySet()) { ....}]
                                 ^
[Line: 26, Column: 22]
	at org.thingsboard.script.api.tbel.DefaultTbelInvokeService.lambda$doInvokeFunction$8(DefaultTbelInvokeService.java:235)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: [Error: unknown exception in expression: p.key]
[Near : {... oreach( p : msg.entrySet()) { ....}]
                                 ^
[Line: 26, Column: 22]
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:170)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:125)
	at org.mvel2.ast.ASTNode.getReducedValue(ASTNode.java:190)
	at org.mvel2.MVELInterpretedRuntime.parseAndExecuteInterpreted(MVELInterpretedRuntime.java:113)
	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:59)
	at org.mvel2.MVEL.eval(MVEL.java:157)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeSetAccessor(ReflectiveAccessorOptimizer.java:262)
	at org.mvel2.compiler.CompiledAccExpression.setValue(CompiledAccExpression.java:55)
	at org.mvel2.ast.AssignmentNode.getReducedValueAccelerated(AssignmentNode.java:111)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:74)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.ForEachNode.getReducedValueAccelerated(ForEachNode.java:129)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:102)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.MVEL.executeExpression(MVEL.java:939)
	at org.mvel2.MVEL.executeTbExpression(MVEL.java:952)
	at org.thingsboard.script.api.tbel.DefaultTbelInvokeService.lambda$doInvokeFunction$8(DefaultTbelInvokeService.java:231)
	... 9 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public final java.lang.Object java.util.HashMap$Node.getKey() accessible: module java.base does not "opens java.util" to unnamed module @4681c175
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
	at org.mvel2.PropertyAccessor.getBeanProperty(PropertyAccessor.java:601)
	at org.mvel2.PropertyAccessor.getNormal(PropertyAccessor.java:178)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:145)
	... 27 more
```

I tested a few changes of the code, and figured that the map.entrySet() is working as expected. Also, the p.key and p.value properties are generally accessible. p.key just cannot be accessed while putting an entry into result, re-using p.key as the property name. The following code works. I have just temporarily read and kept the value of p.key:

```
foreach( p : msg.entrySet()) {
    var key = p.key;
    if(whitelist.indexOf(key) >= 0) {
        res[key] = p.value;
    }
}
```

**Environment**
    OS: Ubuntu 22.04
    ThingsBoard: 3.7.0PE

**Comment by epalchenko** [comment]
Hello,
Please provide "Payload"(message) and "function Transform" in .json format for a detailed investigation your issues:

![2024-08-07_17-32](https://github.com/user-attachments/assets/84d8c7ad-ecc9-4959-845d-3a18a1716c1d)

**Comment by epalchenko** [comment]
Close due to inactive.

**Comment by sudhirbits** [comment]
We are hitting this issue after upgrading from TB CE: 3.6.4 to 3.7.0

**Comment by sudhirbits** [comment]
@epalchenko what's the fix for this issue? Was it fixed in 3.8.0?
