### ISSUE TITLE
CalculateDeltaNode: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.cache" is null

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#11688]
**Describe the bug**
NPE if `Use caching` configuration option is disabled.

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.cache" is null
	at org.thingsboard.rule.engine.metadata.CalculateDeltaNode.getLatestFromCacheOrFetchFromDb(CalculateDeltaNode.java:184)
	at org.thingsboard.rule.engine.metadata.CalculateDeltaNode.processMsgAsync(CalculateDeltaNode.java:152)
	at org.thingsboard.rule.engine.util.SemaphoreWithTbMsgQueue.tryProcessQueue(SemaphoreWithTbMsgQueue.java:94)
	at org.thingsboard.rule.engine.util.SemaphoreWithTbMsgQueue.addToQueueAndTryProcess(SemaphoreWithTbMsgQueue.java:59)
	at org.thingsboard.rule.engine.metadata.CalculateDeltaNode.onMsg(CalculateDeltaNode.java:95)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:158)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:101)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:41)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Your Server Environment**
* own setup
  * Deployment: monolith
  * Deployment type: docker-compose
  * ThingsBoard 3.7.0
  * Community

**Comment by sumin-denys** [comment]
Hi @devaskim,

Thank you for your report! This issue has been confirmed, and our product team is already processing a product ticket, PROD-4012. Currently, this rule node only functions properly when the "Use caching" option is enabled.

This issue will be fixed in the upcoming minor release - 3.7.1. For now, please set "Use caching" to true.

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)
