### ISSUE TITLE
Failed to process device connect command

### ISSUE THREAD

**Issue by andre-aktivconsultancy** [thingsboard/thingsboard#11703]
**Component**
 * Generic

**Description**
When we deploy Thingsboard in a microservices setup with tb-mqtt-transport, tb-node, tb-jsexecutor, redis, kafka, and zookeeper we run into the following problem.

tb-mqtt-transport shows these errors: 
```
2024-09-19 11:46:00,945 [MqttTransportContext-0-6] WARN  o.t.s.t.m.s.AbstractGatewaySessionHandler - [91981460-767c-11ef-9661-514bcddb7bf9][9590c5d0-767c-11ef-9661-514bcddb7bf9][2d1c65a0-9dce-4c7f-8201-f8ecb832b4a0] Failed to process device connect command: [P-2-12-1]
java.util.concurrent.TimeoutException: null
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.setTimeoutException(DefaultTbQueueRequestTemplate.java:165)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$tryCleanStaleRequests$0(DefaultTbQueueRequestTemplate.java:134)
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.tryCleanStaleRequests(DefaultTbQueueRequestTemplate.java:130)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:119)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:103)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
 ```

tb-node shows these:
```
2024-09-19 12:48:02,795 [device-state-scheduled-23-thread-1] WARN  o.t.s.s.s.DefaultDeviceStateService - [b2c85370-767c-11ef-9661-514bcddb7bf9] Failed to push inactivity alarm: DeviceState(active=false, lastConnectTime=1726748873448, lastActivityTime=1726749473469, lastDisconnectTime=1726749473469, lastInactivityAlarmTime=1726750082793, inactivityTimeout=600000)
java.lang.IllegalStateException: Partitions info for queue QK(Main,TB_RULE_ENGINE,system) is missing
        at org.thingsboard.server.queue.discovery.HashPartitionService.resolve(HashPartitionService.java:311)
        at org.thingsboard.server.queue.discovery.HashPartitionService.resolveAll(HashPartitionService.java:285)
        at org.thingsboard.server.queue.common.TbRuleEngineProducerService.sendToRuleEngine(TbRuleEngineProducerService.java:42)
        at org.thingsboard.server.service.queue.DefaultTbClusterService.pushMsgToRuleEngine(DefaultTbClusterService.java:210)
        at org.thingsboard.server.service.state.DefaultDeviceStateService.pushRuleEngineMessage(DefaultDeviceStateService.java:858)
        at org.thingsboard.server.service.state.DefaultDeviceStateService.onDeviceActivityStatusChange(DefaultDeviceStateService.java:600)
        at org.thingsboard.server.service.state.DefaultDeviceStateService.reportInactivity(DefaultDeviceStateService.java:572)
        at org.thingsboard.server.service.state.DefaultDeviceStateService.updateInactivityStateIfExpired(DefaultDeviceStateService.java:556)
        at org.thingsboard.server.service.state.DefaultDeviceStateService.lambda$checkStates$3(DefaultDeviceStateService.java:505)
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
        at org.thingsboard.server.service.state.DefaultDeviceStateService.checkStates(DefaultDeviceStateService.java:493)
        at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:741)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
        ```

We don't get any events in the root rule chain as well. Any help on what is going on, or how to further debug would be much appreciated.

**Environment**

 * OS:  Deployed on kubernetes
 * ThingsBoard: 3.7

**Comment by sumin-denys** [comment]
Hi @andre-aktivconsultancy,

Could you please provide additional information for further investigation, such as:
- Result of `kubectl get pod -o wide`
- Logs: `kubectl logs tb-node-x > tb-node-x.log` (x - if you have more than one container)
- Result of `kubectl get node`
- Deployment files

**Comment by sumin-denys** [comment]
Hi @andre-aktivconsultancy,

I am closing this issue due to inactivity. Please open the new one if you have additional questions regarding this topic.

**Comment by can-git** [comment]
I also have the same problem

```
tb-vc-executor-1      | 2025-04-16 12:04:16,843 [kafka-consumer-stats-1-thread-1] ERROR o.t.c.u.ThingsBoardScheduledThreadPoolExecutor - Uncaught exception occurred during periodic task execution!
tb-vc-executor-1      | java.lang.IllegalStateException: Partitions info for queue QK(Main,TB_RULE_ENGINE,system) is missing
tb-vc-executor-1      |         at org.thingsboard.server.queue.discovery.HashPartitionService.resolve(HashPartitionService.java:355)
tb-vc-executor-1      |         at org.thingsboard.server.queue.discovery.HashPartitionService.resolve(HashPartitionService.java:308)
tb-vc-executor-1      |         at org.thingsboard.server.queue.discovery.HashPartitionService.resolve(HashPartitionService.java:323)
tb-vc-executor-1      |         at org.thingsboard.server.queue.discovery.HashPartitionService.isMyPartition(HashPartitionService.java:387)
tb-vc-executor-1      |         at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
tb-vc-executor-1      |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tb-vc-executor-1      |         at java.base/java.lang.reflect.Method.invoke(Method.java:569)
tb-vc-executor-1      |         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
tb-vc-executor-1      |         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:216)
tb-vc-executor-1      |         at jdk.proxy2/jdk.proxy2.$Proxy65.isMyPartition(Unknown Source)
tb-vc-executor-1      |         at org.thingsboard.server.queue.kafka.TbKafkaConsumerStatsService.isStatsPrintRequired(TbKafkaConsumerStatsService.java:129)
tb-vc-executor-1      |         at org.thingsboard.server.queue.kafka.TbKafkaConsumerStatsService.lambda$startLogScheduling$0(TbKafkaConsumerStatsService.java:99)
tb-vc-executor-1      |         at org.thingsboard.common.util.ThingsBoardScheduledThreadPoolExecutor$PeriodicRunnable.run(ThingsBoardScheduledThreadPoolExecutor.java:67)
tb-vc-executor-1      |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
tb-vc-executor-1      |         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
tb-vc-executor-1      |         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
tb-vc-executor-1      |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tb-vc-executor-1      |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tb-vc-executor-1      |         at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by fjpanag** [comment]
I am also getting the same issue on v3.9.1.

**Comment by sumin-denys** [comment]
Hi @fjpanag,

Could you please provide additional information for further investigation, such as:

- Result of `kubectl get pod -o wide`
- Logs: `kubectl logs tb-node-x > tb-node-x.log` (x - if you have more than one container)
- Result of `kubectl get node`
- Deployment files

**Comment by sumin-denys** [comment]
Hi @andre-aktivconsultancy, 

I am closing this ticket. 

Please refer to #13166 to avoid duplication of the issues.
