### ISSUE TITLE
io.netty.channel.ConnectTimeoutException when calling an https endpoint outside Thingsboard inside a Client Side Rule Chain

### ISSUE THREAD

**Issue by Gaburiere-Remira** [thingsboard/thingsboard#11799]
we have a rule chain that is triggered by a client side rpc. in this rulechain we call an external api to apply business logic and then return to device the result of the logic. 

here an image describing the rule chain

![image](https://github.com/user-attachments/assets/e3365fba-984f-43dd-869b-e0d20407a64b)

we have a very frequent issue when the rule chain invoke the http request resulting in the following netty exception.

`io.netty.channel.ConnectTimeoutException: connection timed out:
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

Checking out api's log it seems that the request can't connect to it and remain pending inside Thingsboard netty code.

We tried to increase the timeout in the rest api call 

![image](https://github.com/user-attachments/assets/c3420a03-77c9-4d69-97d6-0af1b8717621)
 
and to increase the env variable HTTP_REQUEST_TIMEOUT but with no effects.

Is there a way to increase the timeout of the library inside thinsgboard, probably netty?

**Server Environment**
Deployment: docker-compose on dedicated vm
TB version: 3.4.4PE
OS: 22.04.1-Ubuntu

**Comment by trikimiki** [comment]
I think the root cause is either of those:

* ThingsBoard cannot connect to REST API endpoint
check if endpoint is reachable from the server where ThingsBoard is installed
* bug in cluster deployment with persistent RPC
see https://thingsboard.io/docs/reference/releases/#:~:text=%239733%20Fixed%20persistent%20RPC
fix - please upgrade to v3.8.0
