### ISSUE TITLE
Problems with running thingsboard in docker

### ISSUE THREAD

**Issue by Remington-Hunter** [thingsboard/thingsboard#11870]
The log always reports an error：

```
2024-10-15 11:01:52,454 [http-nio-0.0.0.0-9090-exec-3] ERROR o.s.w.s.s.s.DefaultHandshakeHandler - "Handshake failed due to invalid Connection header[close]"
2024-10-15 11:01:53,101 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-0 [Attributes] queueSize [0] totalAdded [2] totalSaved [2] totalFailed [0]
2024-10-15 11:01:53,102 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-2 [Attributes] queueSize [0] totalAdded [8] totalSaved [8] totalFailed [0]
2024-10-15 11:01:53,283 [nioEventLoopGroup-4-8] INFO  o.t.s.t.mqtt.MqttTransportHandler - [42731d7c-b46b-4ab5-a6af-eabff8557c5e][null][] IOException: Connection reset
2024-10-15 11:01:53,410 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-0 [TS] queueSize [0] totalAdded [8] totalSaved [8] totalFailed [0]
2024-10-15 11:01:53,410 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-1 [TS] queueSize [0] totalAdded [8] totalSaved [8] totalFailed [0]
2024-10-15 11:01:53,436 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-0 [TS Latest] queueSize [0] totalAdded [8] totalSaved [8] totalFailed [0]
2024-10-15 11:01:53,436 [sql-log-1-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - Queue-1 [TS Latest] queueSize [0] totalAdded [8] totalSaved [8] totalFailed [0]
2024-10-15 11:01:53,815 [nioEventLoopGroup-4-9] INFO  o.t.s.t.mqtt.MqttTransportHandler - [aae4e1ee-0926-47ae-aeda-33542cd6453c][null][] IOException: Connection reset
2024-10-15 11:01:55,267 [nioEventLoopGroup-4-10] INFO  o.t.s.t.mqtt.MqttTransportHandler - [41cfe770-9305-4397-8fa7-d442fb7e206b][null][] IOException: Connection reset
2024-10-15 11:01:55,805 [nioEventLoopGroup-4-11] INFO  o.t.s.t.mqtt.MqttTransportHandler - [6a3b79c4-359f-480b-99e2-5eda98090e75][null][] IOException: Connection reset
2024-10-15 11:01:56,531 [http-nio-0.0.0.0-9090-exec-4] ERROR o.s.w.s.s.s.DefaultHandshakeHandler - "Handshake failed due to invalid Connection header[close]"
```

However, the connection to mqtt is normal, and the thingsboard front-end stores telemetry data normally, but the telemetry data cannot be viewed. Why?

**Comment by Ultrazombie** [comment]
Please describe the steps to reproduce.
Did you see any msgs on the API usage page?
Did you see any messages on the device's telemetry tab?

**Comment by Remington-Hunter** [comment]
Hello：
I deployed Thingsboard on an Alibaba Cloud server using the thingsboard/tb-postgres service. The front end is mapped from port 8080 to 9090, and MQTT is mapped from port 1883 to 1883. A domain name is associated with the front-end, and I have set up another domain name on the Alibaba server associated with the MQTT 1883 port. Although everything functions correctly, the logs still show the following errors:

`2024-10-15 11:01:55,267 [nioEventLoopGroup-4-10] INFO  o.t.s.t.mqtt.MqttTransportHandler - [41cfe770-9305-4397-8fa7-d442fb7e206b][null][] IOException: Connection reset`

**Comment by Remington-Hunter** [comment]
```
2024-11-21 08:10:25,078 [DefaultTransportService-25-1] INFO  o.t.s.t.mqtt.MqttTransportHandler - DeviceInfo: TransportDeviceInfo(tenantId=546eefe0-132c-11ef-8fd9-17806ef2bf34, customerId=13814000-1dd2-11b2-8080-808080808080, deviceProfileId=86c12df0-674b-11ef-8fbf-39922c825e51, deviceId=1e366e70-66a7-11ef-8fbf-39922c825e51, deviceName=KU12426A005AA0020G9Z, deviceType=Test Video, powerMode=null, additionalInfo={"gateway":true,"overwriteActivityTime":false,"description":""}, edrxCycle=null, psmActivityTimer=null, pagingTransmissionWindow=null) TransportDeviceInfo(tenantId=546eefe0-132c-11ef-8fd9-17806ef2bf34, customerId=13814000-1dd2-11b2-8080-808080808080, deviceProfileId=86c12df0-674b-11ef-8fbf-39922c825e51, deviceId=1e366e70-66a7-11ef-8fbf-39922c825e51, deviceName=KU12426A005AA0020G9Z, deviceType=Test Video, powerMode=null, additionalInfo={"gateway":true,"overwriteActivityTime":false,"description":""}, edrxCycle=null, psmActivityTimer=null, pagingTransmissionWindow=null) nodeId: "4078c4920c7f"
sessionIdMSB: -1864147275303334238
sessionIdLSB: -6563214540423207269
tenantIdMSB: 6084063892297486831
tenantIdLSB: -8081402215954989260
deviceIdMSB: 2177048898917831151
deviceIdLSB: -8088683105759371695
deviceName: "KU12426A005AA0020G9Z"
deviceType: "Test Video"
deviceProfileIdMSB: -8736651291573677585
deviceProfileIdLSB: -8088683105759371695
customerIdMSB: 1405474927960789426
customerIdLSB: -9187201950435737472

2024-11-21 08:10:25,083 [DefaultTransportService-25-1] INFO  o.t.s.t.mqtt.MqttTransportHandler - [e62137ee-0688-4ea2-a4ea-c7261d65669b] Client connected!
2024-11-21 08:10:25,743 [nioEventLoopGroup-4-2] ERROR o.t.s.t.mqtt.MqttTransportHandler - [ae1aa8d8-ac91-4a5a-9b1f-6fd00d1d63b6] Exception caught {}
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-11-21 08:10:25,743 [nioEventLoopGroup-4-2] INFO  o.t.s.t.mqtt.MqttTransportHandler - Test: null null
2024-11-21 08:10:25,743 [nioEventLoopGroup-4-2] INFO  o.t.s.t.mqtt.MqttTransportHandler - [ae1aa8d8-ac91-4a5a-9b1f-6fd00d1d63b6][null][] IOException: Connection reset by peer
```
@Ultrazombie Hello, I printed some logs again to track down the problem. Now I found that the device is connected normally, but I don’t know where this error is caught. I can see that the sessionId is different. I can’t find the root cause of this error. Do you have any suggestions?

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.

**Comment by bcblr1993** [comment]
hi~
How to solve this problem?
I also encountered the same problem. There are a large number of such errors on the server.
