### ISSUE TITLE
How to sovle the error --->  java.util.concurrent.ExecutionException: java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!

### ISSUE THREAD

**Issue by paulwang55** [thingsboard/thingsboard#1193]
Hi,

We meet the error as the following message . When the error was found, the rest of tasks will not be executed anymore.

Do Anyone know how we can solve it ? How can we disable the limitation.

java.util.concurrent.ExecutionException: java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.service.converter.js.JSUplinkEvaluator.execute(JSUplinkEvaluator.java:51)
	at org.thingsboard.server.service.converter.js.JSUplinkDataConverter.doConvertUplink(JSUplinkDataConverter.java:72)
	at org.thingsboard.server.service.converter.AbstractUplinkDataConverter.convertUplink(AbstractUplinkDataConverter.java:72)
	at org.thingsboard.server.service.integration.AbstractIntegration.convertToUplinkDataList(AbstractIntegration.java:185)
	at org.thingsboard.server.service.integration.mqtt.basic.BasicMqttIntegration.doProcess(BasicMqttIntegration.java:118)
	at org.thingsboard.server.service.integration.mqtt.basic.BasicMqttIntegration.doProcess(BasicMqttIntegration.java:61)
	at org.thingsboard.server.service.integration.mqtt.AbstractMqttIntegration.process(AbstractMqttIntegration.java:97)
	at org.thingsboard.server.service.integration.mqtt.basic.BasicMqttIntegration.lambda$subscribeToTopics$1(BasicMqttIntegration.java:99)
	at org.thingsboard.mqtt.MqttChannelHandler.invokeHandlersForIncomingPublish(MqttChannelHandler.java:124)
	at org.thingsboard.mqtt.MqttChannelHandler.handlePublish(MqttChannelHandler.java:198)
	at org.thingsboard.mqtt.MqttChannelHandler.channelRead0(MqttChannelHandler.java:61)
	at org.thingsboard.mqtt.MqttChannelHandler.channelRead0(MqttChannelHandler.java:41)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.thingsboard.mqtt.MqttPingHandler.channelRead(MqttPingHandler.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at org.thingsboard.server.service.script.AbstractNashornJsSandboxService.invokeFunction(AbstractNashornJsSandboxService.java:134)
	... 41 more

**Comment by vparomskiy** [comment]
In the latest Thingsboard version you should see the reason why the script was blacklisted. 
There are 2 reasons why script can be blacklisted:
1. A wrong script that throws an error - you will need to update your script for correct handling your corner cases.
2. Execution time is too high - by default max script execution time is 100 ms. If it is higher - the script will be added into the blacklist.

**Comment by skangmy** [comment]
@vparomskiy where can I find out the reasons why a script is blacklisted?

I'm using version 2.3.0 and my script keeps being blacklisted even though I tested multiple times without error.

**Comment by efeeyuboglu** [comment]
> @vparomskiy where can I find out the reasons why a script is blacklisted?
> 
> I'm using version 2.3.0 and my script keeps being blacklisted even though I tested multiple times without error.

same
