### ISSUE TITLE
Can't install thingsboard server on armbian with postgresql

### ISSUE THREAD

**Issue by pavellzubkov** [thingsboard/thingsboard#1194]
> root@orangepipc:~#
 sudo /usr/share/thingsboard/bin/install/install.sh --loadDemoThingsBoard installation failed!
root@orangepipc:~# sudo /usr/share/thingsboard/bin/install/install.sh
ThingsBoard installation failed!
root@orangepipc:~# java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Client VM (build 25.191-b12, mixed mode)
root@orangepipc:~# psql -U postgres
Password for user postgres:
psql (10.5 (Ubuntu 10.5-0ubuntu0.18.04))
Type "help" for help.
postgres=# \q
root@orangepipc:~# ls
thingsboard-2.1.3.deb
root@orangepipc:~#

ThingsBoard installation failed! without logs. But i can install it with HSQLDB config.

**Comment by pavellzubkov** [comment]
I created manually tables in thingsboard postgresql data base, then i modified thingsboard.yml file and restart thingsboard service. After that in file thingsboard.out i can see 
 ===================================================
 :: ThingsBoard ::       (v2.1.3)
 ===================================================

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: while parsing a block mapping
 in 'reader', line 17, column 1:
    server:
    ^
expected <block end>, but found BlockMappingStart
 in 'reader', line 374, column 2:
     spring:
     ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:104)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:502)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:160)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:138)
	at org.springframework.boot.env.YamlPropertySourceLoader$Processor.process(YamlPropertySourceLoader.java:101)
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:58)
	at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourcesLoader.java:127)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:466)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:453)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:377)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:212)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:181)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:168)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:154)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:38)
	... 8 more``

**Comment by vparomskiy** [comment]
According to the provided log file, your thingsboard.yml file is not correct.
Please validate the config file, speciali line 374 (note that for postgres DAO config, '**spring:**' tag should not have whitespaces before tag)

```
at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
in 'reader', line 17, column 1:
server:
expected , but found BlockMappingStart
in 'reader', line 374, column 2:
spring:
```

**Comment by pavellzubkov** [comment]
vparomskiy, thank you! it was whitespace before 'spring:' tag . strange thing...
