### ISSUE TITLE
Error while running performance test

### ISSUE THREAD

**Issue by ssmaurya** [thingsboard/thingsboard#120]
While executing performance test using gatling with default configuration, I am getting the following error on thingsboard server:

Exception in thread "nioEventLoopGroup-6-10" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.warn(Logger.java:692)
	at io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:880)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

  What is the cause for this issue? Do we have some packages missing as part of the build?

**Comment by ashvayka** [comment]
We will get back to you on this. This is an error inside the test process or TB process? Can you attach a build log please?

**Comment by ssmaurya** [comment]
This error was in TB Server Process not test process. We tried again but could not reproduce. We will monitor for reproduction and will provide details if the issue is seen again.

**Comment by ssmaurya** [comment]
Closing this issue as we have not been able to reproduce the issue so far during our performance runs.
