### ISSUE TITLE
Compress Base64 with Custom Action HTM:

### ISSUE THREAD

**Issue by strangerCatLv** [thingsboard/thingsboard#12087]
**Description**
hello, I have a problem in image input.
so I input the image from my computer file. then the result becomes BASE64.
then I want to save the 'eviden' data to timeseries data, but there is an error in rule chain as below.
org.thingsboard.script.api.TbScriptException: java.lang.IllegalArgumentException: Script input arguments exceed maximum allowed total args size of 150000 symbols
	at org.thingsboard.script.api.AbstractScriptInvokeService.invokeScript(AbstractScriptInvokeService.java:153)
	at org.thingsboard.server.service.script.RuleNodeScriptEngine.executeScriptAsync(RuleNodeScriptEngine.java:139)
	at org.thingsboard.server.service.script.RuleNodeScriptEngine.executeScriptAsync(RuleNodeScriptEngine.java:135)

how to compress the 'eviden' data in the custom action HTML?

`const $injector = widgetContext.$scope.$injector;
const customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
const deviceService = $injector.get(widgetContext.servicesMap.get('deviceService'));
const attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
const rxjs = widgetContext.rxjs;

openEditEntityDialog();

function openEditEntityDialog() {
    customDialog.customDialog(htmlTemplate, EditEntityDialogController).subscribe();
}

function EditEntityDialogController(instance) {
    const vm = instance;

    vm.entityId = entityId;
    vm.entityName = entityName;
    vm.entityLabel = entityLabel;
    vm.sensor = null;
    vm.attributes = {};

    vm.editEntityFormGroup = vm.fb.group({
        entityName: ['', [vm.validators.required]],
        entityLabel: ['', [vm.validators.required]],
        attributes: vm.fb.group({
            issue: [null],
            impact: [null],
            action: [null],
            finding: [null],
            analysis: [null],
            statusAlarm: [null],
            eviden: [null, [vm.validators.required]], // THIS IS BASE64
        })
    });

    getEntityInfo();

    vm.save = () => {
        vm.editEntityFormGroup.markAsPristine();
        const formValues = vm.editEntityFormGroup.value;
        vm.sensor.name = formValues.entityName;
        vm.sensor.label = formValues.entityLabel;
        deviceService.saveDevice(vm.sensor).pipe(
            rxjs.concatMap(() => {
                return saveAttributes();
            })
        ).subscribe(() => {
            widgetContext.updateAliases();
            vm.dialogRef.close(null);
        });
    };

    vm.cancel = function() {
        vm.dialogRef.close(null);
    };

    function getEntityAttributes(attributes) {
        for (let i = 0; i < attributes.length; i++) {
            vm.attributes[attributes[i].key] = attributes[i].value;
        }
    }

    function getEntityInfo() {
        rxjs.forkJoin([
            attributeService.getEntityAttributes(entityId, 'SERVER_SCOPE', ['issue', 'impact', 'action', 'finding', 'analysis', 'statusAlarm', 'eviden']),
            deviceService.getDevice(entityId.id)
        ]).subscribe(
            (data) => {
                const attrs = data[0];
                vm.sensor = data[1];
                getEntityAttributes(attrs);
                vm.editEntityFormGroup.patchValue({
                    entityName: vm.entityName,
                    entityLabel: vm.entityLabel,
                    attributes: vm.attributes
                });
            }
        );
    }

    function saveAttributes() {
        const attributes = vm.editEntityFormGroup.get('attributes').value;
        const attributesArray = [];
        for (let key in attributes) {
            if (attributes[key] !== vm.attributes[key]) {
                attributesArray.push({key: key, value: attributes[key]});
            }
        }
        if (attributesArray.length > 0) {
            return attributeService.saveEntityAttributes(vm.entityId, "SERVER_SCOPE", attributesArray);
        } else {
            return widgetContext.rxjs.of([]);
        }
    }
}`

**Environment**
 * ThingsBoard: v.3.8.1. version

**Comment by ssakharova** [comment]
Hello @strangerCatLv,

We're letting you know that this issue, labeled as "help wanted", has been open for a while. This label is used to seek support from the GitHub community, especially for issues that fall outside the scope of the ThingsBoard support team's expertise.
Unfortunately, there hasn't been any community input or progress on this issue over the past three months. We're closing this ticket to keep our repository well-maintained and focused on active issues.

We appreciate your patience and understanding.
