### ISSUE TITLE
Control version bug

### ISSUE THREAD

**Issue by dpergarc-c** [thingsboard/thingsboard#12081]
**Describe the bug**
* The error:
The control version is not working when we try to restore one, giving us the error _"Entity Group with such name, type and owner already exists!"_.

* Context
We have both a develop and a production ThingsBoard environments, and the idea is to migrate all stable versions from the first one to the second.

* Further information
Apparently, the version creation seems to work fine, but we are not sure if the issue is there.

**Your Server Environment**
* Own setup
  * Deployment: monolith
  * Deployment type: k8s
  * ThingsBoard Version: 3.7.0
  * Professional Edition

**Your Client Environment**
* Browser: Chrome
* Version: 130.0.6723.70

**To Reproduce**
1. Go to ThingsBoard dev environment
2. Go to settings, repository, and configure it as desired. 
3. Go to the version control option and create a new one: branch, version name and merge, selecting all entities.
4. Go to ThingsBoard prod environment
5. Go to settings, repository, and configure it like the point number 2. 
6. Click over restore version.

**Expected behavior**
The process should create the same version from develop in production, but it give us the error shown in the picture section.

**Screenshots**
![image](https://github.com/user-attachments/assets/83dc7534-50df-45b7-8f1f-4885d9b6a39b)

**Additional context**
Nothing yet.

**Comment by epalchenko** [comment]
Hello,
We tested this behavior on an empty tenant with the same Entity Groups name and we were unable to reproduce it.
When you restore the version, Entity Group already exists on the platform (and it is not tied to a tracked entity (no external id))

**Comment by dpergarc-c** [comment]
Hi @epalchenko 

Thank you very much for your reply.

Maybe the guy in charge of mounting the ThingsBoard for production environment created some things just by instinct (we do not know that actually). 

Let me ask you something, just for me to have it clear: In order to restore the version, what should be the Thingsboard initial state? Could you give us a piece of advice to perform this sequence correctly? According to your answer, we may dial back to a certain status or something like that.

Thanks beforehand, sorry for the inconveniences, and looking forward to hearing from you.

Kind regards.
Daniel.

**Comment by epalchenko** [comment]
Hello,
I created a new(clean) tenant profile on the platform(the exact version of the platform on which you created version control) through the system administrator. Then, restore the version.
When restoring the version, you need to uncheck this box:
![Screenshot_4](https://github.com/user-attachments/assets/8d022afd-c3c3-48f7-a877-346454a4cbf8)
And check this box:
![Screenshot_6](https://github.com/user-attachments/assets/8c81cfb6-5d77-490d-af2f-59a912f81007)

**Comment by dpergarc-c** [comment]
Hi @epalchenko,

Thank you very much for your reply! I have just tried what you say in the previous reply, but unfortunately, it is giving the same outcome :(

The devops guys have told me that the instance has been upgraded to the 3.8.1 version, perhaps it might give you a clue of what could be going on.

Looking forward to hearing from you.

Kind regards.
Daniel.

**Comment by mixo3891** [comment]
hello I need help too.
I can not update Thingsboard from 3.6.1->3.6.2
please check problem:

root@orangepi5:~# sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.6.1

/_ / / / () ____ ____ _ _____ / __ ) ____ ____ _ _____ / /
/ / / __ \ / / / __ \ / __ / / / / __ | / __ \ / __ / / / / __ /
/ / / / / / / / / / / / / // / ( ) / // / / // // // / / / / // /
// // // // // // , / // /_/ / ,/ // ,/
//

===================================================
:: ThingsBoard :: (v3.6.2)
Starting ThingsBoard Upgrade from version 3.6.1 ...
Clearing cache to upgrade from version 3.6.1 to 3.6.2
Clearing cache [securitySettings]
Clearing cache [resourceInfo]
Upgrading ThingsBoard from version 3.6.1 to 3.6.2 ...
Updating schema ...
Skip schema re-update to version 3.6.2. Use env flag 'SKIP_SCHEMA_VERSION_CHECK' to force the re-update.
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating system data...
Starting rule nodes upgrade ...
Finished rule nodes upgrade. Upgraded rule nodes count: 0
Loading system widgets
Unable to load widget type from json: [/usr/share/thingsboard/data/json/system/widget_types/update_server_location_attribute.json]
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to load widget type from json
at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:249)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.thingsboard.server.service.install.InstallScripts.loadSystemWidgets(InstallScripts.java:241)
at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.loadSystemWidgets(DefaultSystemDataLoaderService.java:538)
at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:288)
at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
at org.thingsboard.server.dao.resource.BaseImageService$$EnhancerBySpringCGLIB$$2298e34d.replaceBase64WithImageUrl()
at org.thingsboard.server.dao.widget.WidgetTypeServiceImpl.saveWidgetType(WidgetTypeServiceImpl.java:97)
at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:246)
... 13 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!

**Comment by dpergarc-c** [comment]
Hi @mixo3891 ,

FYI: This is a topic related with the _"Version Control"_, not with a ThingsBoard upgrade :)

Kind regards.
Daniel.

**Comment by dpergarc-c** [comment]
Hi @epalchenko,

We have achieve it without the _"rollback on error"_ option enabled, and surprisingly, it worked giving no error! Should it be that way?

I hope this may give you more clues, looking forward to your feedback.

Kind regards.
Daniel.

**Comment by epalchenko** [comment]
Hello,
Thanks to your additional information, I was able to reproduce this issue. 
We spoke with the Version Control developer about the error "Entity Group with such name, type and owner already exists!", who confirmed this unexpected behavior. I have already created a ticket (PROD-5053) for the product team to address it.

> We have achieve it without the "rollback on error" option enabled, and surprisingly, it worked giving no error! Should it be that way?

When we tested version control without the “Rollback on error” option enabled, we got a long process of "Restoring entities... Please wait" and then the following error:
![Screenshot from 2024-11-26 15-12-54](https://github.com/user-attachments/assets/dcacc3c9-88b7-4d65-aafb-5f75a14aa415)
![Screenshot from 2024-11-26 15-13-49](https://github.com/user-attachments/assets/a5ffd6b9-7056-4019-adfa-55e581719d50)

We will close this ticket as it is already in our backlog.
Please follow our Release Notes (https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by dpergarc-c** [comment]
Hi @epalchenko,

Thank you very much for your reply, and glad to help!

Looking forward to new releases.

Kind regards.
Daniel.

**Comment by ViacheslavKlimov** [comment]
Hi @dpergarc-c,
The fix is ready and will be available in 3.9.0.

**Comment by dpergarc-c** [comment]
Hi @ViacheslavKlimov ,

Glad to know that! Thank you very much for the whole support!

Kind regards.
Daniel.
