### ISSUE TITLE
Only one physical connection per device (gateway), bug or feature

### ISSUE THREAD

**Issue by ChristianLutz** [thingsboard/thingsboard#1210]
I just wondered why I am not able to connect to a gateway anymore, always got 

```
java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more
```

The reason another physical device connected with a different clientId to the same gateway. The first device receive the error message above. Is this intended?

**Comment by ChristianLutz** [comment]
Thank you very much. 

Maybe an additional setting like 
```
max_concurrent_sessions_per_device_gatway: "${ACTORS_MAX_CONCURRENT_SESSION_PER_DEVICE_GATEWAY:1}"
```
could be an option. For example you have one gateway to for several devices. But to one device only one connection is allowed. So a separate option may be helpful.

Sincerely

**Comment by Ultrazombie** [comment]
Closed due to inactivity
