### ISSUE TITLE
Upgrade docker Thingsboard from 3.7.0-->3.8.1, docker su password required?

### ISSUE THREAD

**Issue by glossyio** [thingsboard/thingsboard#12122]
**Component**

 * Thingsboard Docker (3.8.1)

**Description**
I upgraded my container from 3.7.0 to 3.8.1, but I received a `InvalidDataAccessResourceUsageException` error.  I see from https://github.com/thingsboard/thingsboard/issues/11856 that I need to run the upgrade command inside the Docker Thingsboard container which requires su / sudo / admin privileges.  However, I do not know and cannot find the container super user password--it is not my sysadmin username password.  What is the default container password?  

To replicate, I attach to the running container:  

```
docker exec -ti tb-thingsboard /bin/bash
```

Then I try to run the upgrade command and get asked for a password:

```
thingsboard@a4b02dc47894:/$ /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.7.0
Password: 
su: Authentication failure
ThingsBoard upgrade failed!

```

And for the future... Is there an environment variable I can specify to set the su password?

**Alternative**
I also follwed `upgrade-tb.sh` from the https://thingsboard.io/docs/user-guide/install/docker/#upgrading but after it launches the container, it gives an `unsupported fromVersion: 3.8.1` error:

Ran command:

```
docker run -it -v ~/mydatadir:/data --rm thingsboard/tb-postgres upgrade-tb.sh --fromVersion=3.7.0
```

Still didn't like the fromVersion

```
/_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard ::       (v3.8.1)
 ===================================================

Starting ThingsBoard Upgrade from version 3.8.1 ...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 3.8.1
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:148)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.PropertiesLauncher.main(PropertiesLauncher.java:574)
Unexpected error during ThingsBoard installation!
waiting for server to shut down...2024-11-25 17:44:41.191 UTC [12] LOG:  received fast shutdown request
.2024-11-25 17:44:41.242 UTC [12] LOG:  aborting any active transactions
2024-11-25 17:44:41.245 UTC [12] LOG:  background worker "logical replication launcher" (PID 19) exited with exit code 1
2024-11-25 17:44:41.245 UTC [14] LOG:  shutting down
2024-11-25 17:44:41.682 UTC [12] LOG:  database system is shut down
```

**Environment**

 * OS:  Docker 
 * ThingsBoard: 3.7.0 --> 3.8.1
 * Browser: Firefox

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by glossyio** [comment]
I was able to successfully run `upgrade-tb.sh` by modifying `/data/.upgradeversion` to 3.7.0.  It had been overwritten to the latest version, not my previous version.   the `upgrade-tb.sh` only looks for that file, and it does not take command line arguments.
