### ISSUE TITLE
Rule Chain not working.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#12168]
I am testing below rule chain but in the save time series node give the below error:- 
```
java.lang.IllegalArgumentException: Unsupported msg type: ENTITY_UPDATED
	at org.thingsboard.rule.engine.telemetry.TbMsgTimeseriesNode.onMsg(TbMsgTimeseriesNode.java:101)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:174)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:116)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:75)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:56)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:172)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
[tutorial_rule_chain.json](https://github.com/user-attachments/files/17988735/tutorial_rule_chain.json)

**Comment by Backdraft007** [comment]
You need a "Message type switch" node after device profile and before "Save timeseries". Node link btween Save and switch ist "Post telemetry"

**Comment by Vaibhav0216** [comment]
added "Message type switch" node but now message not coming also in the "Save timeseries" node.
[tutorial_rule_chain (1).json](https://github.com/user-attachments/files/17991576/tutorial_rule_chain.1.json)

**Comment by Backdraft007** [comment]
Please have a look in the default root rule chain from Thingsboard.
To save timeseries only use "Post telemtry" from "Message type switch" to "Save timeseries". And from "device profile" "Success" to "Message type switch".

**Comment by Vaibhav0216** [comment]
Hi @Backdraft007 ,
This is my root rule chain. I tested on "Post telemtry" from "Message type switch" to "Save timeseries". And from "device profile" "Success" to "Message type switch". But still message not coming to in the "Save timeseries" node.
[tutorial_rule_chain (2).json](https://github.com/user-attachments/files/17992298/tutorial_rule_chain.2.json)

**Comment by Backdraft007** [comment]
As already mentioned in other posts, turn on debug in all nodes and see where the problem is.

**Comment by Vaibhav0216** [comment]
In "Save timeseries". Problem is not coming any message in debug field.

**Comment by Backdraft007** [comment]
Sorry, but it's really tiring. I wrote activate in all nodes and see which is the last node where data arrives.

**Comment by Backdraft007** [comment]
@Vaibhav0216 ,

are you sure that this rule chain is used by your device? Did you play with device profiles? Maybe you setup your device profile wrong. https://github.com/thingsboard/thingsboard/issues/12169

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
