### ISSUE TITLE
Basic Auth in REST API call block not working

### ISSUE THREAD

**Issue by David-Glom** [thingsboard/thingsboard#12178]
**Describe the bug**
If you try to use the credentials type basic in the REST API call block in a rule chain, you get a Java Illegal Argument exception, that there are some illegal base64 characters. If you use a "@" in your username, then you first get some, but even if not, you get the  Illegal Argument exception due to 

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type:  docker-compose
  * 3.8.1 
  * Community  Edition
  * Ubuntu

* Connectivity
  * HTTP

**To Reproduce**
1. Go to rule chains
2. Open a new api rest call block
3. Scroll down to credentials 
4. choose basic
5. try your credentials
6. Click on events
8. See error

**Expected behavior**
I would expect, that the credential function works

**exception code**

```
java.lang.IllegalArgumentException: Illegal base64 character 40
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at org.thingsboard.rule.engine.rest.TbHttpClient.prepareHeaders(TbHttpClient.java:346)
	at org.thingsboard.rule.engine.rest.TbHttpClient.lambda$processMessage$6(TbHttpClient.java:222)
	at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.headers(DefaultWebClient.java:281)
	at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.headers(DefaultWebClient.java:197)
	at org.thingsboard.rule.engine.rest.TbHttpClient.processMessage(TbHttpClient.java:222)
	at org.thingsboard.rule.engine.rest.TbRestApiCallNode.onMsg(TbRestApiCallNode.java:69)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:159)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:101)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:41)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by mykhailokornieiev** [comment]
Hi. As far as I know, this is not a credentials for endpoint login, but for Redis. 
For authorization you will need to specify the necessary username and password in the body of the message, then you can use auth endpoint to get Bearer token (JWT)
![image](https://github.com/user-attachments/assets/34444492-714f-4523-9cd8-869ab17a5b42)
![image](https://github.com/user-attachments/assets/4a722603-0669-4716-83f1-7da78897bf23)
![image](https://github.com/user-attachments/assets/733b4bff-5e8c-4fde-bf93-3a91090739eb)
![image](https://github.com/user-attachments/assets/15431ff3-0d89-4366-8a16-1de3e19bacdf)
![image](https://github.com/user-attachments/assets/0d88124c-6647-4909-b9e6-b7e05f1196e5)
![image](https://github.com/user-attachments/assets/284682a7-ce0c-44e3-a73f-f3b808128ffb)

**Comment by David-Glom** [comment]
Thanks you for the very detailed answer! I will try it. Maybe adding this hint to the documentation could help other users too 😄
