### ISSUE TITLE
Cannot upgrade TB from 3.6.4 to 3.7.0. Error during COPY: cannot drop table `attribute_kv_old`

### ISSUE THREAD

**Issue by AVTaran** [thingsboard/thingsboard#12205]
**Component**

 * Installation

**Description**

Hello all.

Trying to update the ThingsBoard to the 3.7.0 version.
Following the instruction:
https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#upgrading-to-37pe

On the step:
Execute regular upgrade script:
`sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.6.4`
received the error:
```
org.postgresql.util.PSQLException: ERROR: Error during COPY: cannot drop table attribute_kv_old because other objects depend on it
```

I found a similar issue: https://github.com/thingsboard/thingsboard/issues/2993
And follow the comment: https://github.com/thingsboard/thingsboard/issues/2993#issuecomment-652945611 I can add: that we copied over our database in order to test the upgrade before applying it on production. Maybe, it could have some impact.

The question is: how can we be sure - it's not going to happen on the original database?
Which objects depend on the attribute_kv_old table? And should we modify the database to make `upgrade.sh` script work?

The full output:
```
~$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.6.4
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.7.0PE)
 ===================================================

Starting ThingsBoard Upgrade from version 3.6.4 ...
Clearing cache to upgrade from version 3.6.4 to 3.7.0
Clearing cache [relations]
Clearing cache [deviceCredentials]
Clearing cache [devices]
Clearing cache [sessions]
Clearing cache [assets]
Clearing cache [customers]
Clearing cache [users]
Clearing cache [entityViews]
Clearing cache [claimDevices]
Clearing cache [securitySettings]
Clearing cache [tenantProfiles]
Clearing cache [tenants]
Clearing cache [tenantsExist]
Clearing cache [deviceProfiles]
Clearing cache [assetProfiles]
Clearing cache [notificationSettings]
Clearing cache [sentNotifications]
Clearing cache [attributes]
Clearing cache [userSessionsInvalidation]
Clearing cache [otaPackages]
Clearing cache [otaPackagesData]
Clearing cache [edges]
Clearing cache [repositorySettings]
Clearing cache [autoCommitSettings]
Clearing cache [twoFaVerificationCodes]
Clearing cache [versionControlTask]
Clearing cache [userSettings]
Clearing cache [dashboardTitles]
Clearing cache [entityCount]
Clearing cache [resourceInfo]
Clearing cache [alarmTypes]
Clearing cache [mobileAppSettings]
Clearing cache [mobileSecretKey]
Clearing cache [downlink]
Clearing cache [roles]
Clearing cache [permissions]
Clearing cache [owners]
Clearing cache [remoteIntegrations]
Clearing cache [integrations]
Clearing cache [whiteLabeling]
Clearing cache [customTranslation]
Upgrading ThingsBoard from version 3.6.4 to 3.7.0 ...
Updating schema ...
Failed updating schema!!!
org.postgresql.util.PSQLException: ERROR: Error during COPY: cannot drop table attribute_kv_old because other objects depend on it
  Where: PL/pgSQL function inline_code_block line 25 at RAISE
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.loadSql(SqlDatabaseUpgradeService.java:327)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.updateSchema(SqlDatabaseUpgradeService.java:309)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:166)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:150)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:65)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.PropertiesLauncher.main(PropertiesLauncher.java:574)
Updating data from version 3.6.4 to 3.7.0 ...
Unexpected error during ThingsBoard installation!
org.springframework.dao.InvalidDataAccessResourceUsageException: Unable to find column position by name: is_public [The column name is_public was not found in this ResultSet.] [n/a]; SQL [n/a]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:277)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:241)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
        at jdk.proxy2/jdk.proxy2.$Proxy332.findCustomersWithTheSameTitle(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at jdk.proxy2/jdk.proxy2.$Proxy213.findCustomersWithTheSameTitle(Unknown Source)
        at org.thingsboard.server.dao.sql.customer.JpaCustomerDao.findCustomersWithTheSameTitle(JpaCustomerDao.java:161)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.thingsboard.server.dao.aspect.SqlDaoCallsAspect.handleSqlCall(SqlDaoCallsAspect.java:173)
        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:173)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
        at org.thingsboard.server.dao.sql.customer.JpaCustomerDao$$SpringCGLIB$$0.findCustomersWithTheSameTitle(<generated>)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService.lambda$updateCustomersWithTheSameTitle$6(DefaultDataUpdateService.java:296)
        at org.thingsboard.server.common.data.page.PageDataIterable.fetchPageData(PageDataIterable.java:44)
        at org.thingsboard.server.common.data.page.BasePageDataIterable.fetch(BasePageDataIterable.java:81)
        at org.thingsboard.server.common.data.page.BasePageDataIterable.hasNext(BasePageDataIterable.java:61)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateCustomersWithTheSameTitle(DefaultDataUpdateService.java:297)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:196)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:151)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:65)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.PropertiesLauncher.main(PropertiesLauncher.java:574)
Caused by: org.hibernate.exception.SQLGrammarException: Unable to find column position by name: is_public [The column name is_public was not found in this ResultSet.] [n/a]
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:91)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
        at org.hibernate.sql.results.jdbc.internal.AbstractResultSetAccess.resolveColumnPosition(AbstractResultSetAccess.java:70)
        at org.hibernate.query.results.ResultsHelper.lambda$resolveSqlExpression$0(ResultsHelper.java:63)
        at org.hibernate.query.results.DomainResultCreationStateImpl.resolveSqlExpression(DomainResultCreationStateImpl.java:278)
        at org.hibernate.query.results.ResultsHelper.resolveSqlExpression(ResultsHelper.java:57)
        at org.hibernate.query.results.implicit.ImplicitFetchBuilderBasic.buildFetch(ImplicitFetchBuilderBasic.java:97)
        at org.hibernate.query.results.implicit.ImplicitFetchBuilderBasic.buildFetch(ImplicitFetchBuilderBasic.java:37)
        at org.hibernate.query.results.DomainResultCreationStateImpl.lambda$createFetchableConsumer$3(DomainResultCreationStateImpl.java:539)
        at org.hibernate.metamodel.mapping.internal.ImmutableAttributeMappingList.forEach(ImmutableAttributeMappingList.java:44)
        at org.hibernate.persister.entity.AbstractEntityPersister.visitFetchables(AbstractEntityPersister.java:6134)
        at org.hibernate.query.results.DomainResultCreationStateImpl.visitFetches(DomainResultCreationStateImpl.java:454)
        at org.hibernate.sql.results.graph.AbstractFetchParent.afterInitialize(AbstractFetchParent.java:30)
        at org.hibernate.sql.results.graph.entity.AbstractEntityResultGraphNode.afterInitialize(AbstractEntityResultGraphNode.java:69)
        at org.hibernate.persister.entity.AbstractEntityPersister.createDomainResult(AbstractEntityPersister.java:1319)
        at org.hibernate.query.results.dynamic.DynamicResultBuilderEntityCalculated.buildResult(DynamicResultBuilderEntityCalculated.java:129)
        at org.hibernate.query.results.dynamic.DynamicResultBuilderEntityCalculated.buildResult(DynamicResultBuilderEntityCalculated.java:30)
        at org.hibernate.query.results.ResultSetMappingImpl.resolve(ResultSetMappingImpl.java:229)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.resolveJdbcValuesSource(JdbcSelectExecutorStandardImpl.java:325)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:115)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)
        at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:138)
        at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:621)
        at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427)
        at org.hibernate.query.Query.getResultList(Query.java:120)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:415)
        at jdk.proxy2/jdk.proxy2.$Proxy333.getResultList(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:204)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:149)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:137)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        ... 54 common frames omitted
Caused by: org.postgresql.util.PSQLException: The column name is_public was not found in this ResultSet.
        at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:3085)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.findColumn(HikariProxyResultSet.java)
        at org.hibernate.sql.results.jdbc.internal.AbstractResultSetAccess.resolveColumnPosition(AbstractResultSetAccess.java:65)
        ... 100 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
```

**Environment**

 * OS:  Linux 20.04.1-Ubuntu
 * ThingsBoard: 3.7.0PE

___________________________________________________________
**Disclaimer**

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by AVTaran** [comment]
Hello trikimiki,
Thank you for your answer.

1. Yes, it is postgres superuser.
2. For that environment, I installed a fresh 3.6.4 version. And copied over the database from prod. I do not recall any issues with getting it to work. 
3. PostgreSQL 16.3
4. It has some differences between the files and the database:
4.1 schema-entities-idx.sql: Some of the indexes from the file don't exist in the Database.
4.2 schema-views-and-functions.sql: Several views and a function are different in the file and the database.
4.3 schema-entities.sql: There are differences. The comparison is still in progress.

So, does it mean - the 3.7.0 changes for the database haven't been applied, right?
Can I go through these sql files and try to implement them manually? If it is - in which order?

**Comment by trikimiki** [comment]
apologies, I actually meant "check your DB schema if they correlate to **_v3.6.4_** DB schema"
please try checking your DB against v3.6.4 schema

the upgrade definitely did not finish - since, as per error log, some stages failed

**Comment by AVTaran** [comment]
I see

Ok, a comparison of the database with the 3.6.4 files:

 - /usr/share/thingsboard/data/sql/schema-entities-idx.sql:
   `idx_asset_external_id` doesn't exist in DB
   `idx_customer_external_id` doesn't exist in DB
   `idx_dashboard_external_id` doesn't exist in DB
   `idx_device_external_id` doesn't exist in DB
   `idx_device_profile_external_id` doesn't exist in DB
   `idx_edge_event_id` doesn't exist in DB
   `idx_entity_view_external_id` doesn't exist in DB
   `idx_rule_chain_external_id` doesn't exist in DB
   `idx_rule_node_type` doesn't exist in DB
   `idx_widgets_bundle_external_id` doesn't exist in DB

 - /usr/share/thingsboard/data/sql/schema-views-and-functions.sql:
   views and functions(procedures) are the same.

 - /usr/share/thingsboard/data/sql/schema-entities.sql:
    There are several differences:

      1. Table alarm.
        It should be:
          `created_time bigint NOT NULL,`
          `propagate_to_owner boolean,`
          `propagate_to_owner_hierarchy boolean,`
          `propagate_to_tenant boolean,`
        but in DB:
          `created_time int8 NULL,`
          `propagate_to_owner bool DEFAULT false NULL,`
          `propagate_to_tenant bool DEFAULT false NULL,`
          `propagate_to_owner_hierarchy bool DEFAULT false NULL,`

      2. In the Table `tenant_profile` the column `isolated_tb_core` doesn't exist in DB

      3. The Table device_profile.
        it should be:
          `CONSTRAINT fk_software_device_profile FOREIGN KEY (software_id) REFERENCES ota_package(id)`
        in DB:
          `CONSTRAINT fk_software_device_profile FOREIGN KEY (firmware_id) REFERENCES ota_package(id)`


An update on the question `did you have any issues during previous upgrades`: 
Yes, it was some issues with the previous upgrades on the prod env, but the logs unfortunately are lost. 
There was some incapability in the custom rule-nodes for the 3.6.4 version.

**Comment by AVTaran** [comment]
I found the custom-created view, which utilizes the `attribute_kv` table. 
So during the execution of the `upgrade/3.6.4/schema_update.sql` script, particularly the line: 
`DROP TABLE IF EXISTS attribute_kv_old;` it couldn't delete the table, because it has been used in the view. 

Sorry for the disturbance and thank you for the help.

**Comment by trikimiki** [comment]
glad to help!

note that your DB schema should be as close as possible (ideally - the same) for the successfull upgrade.
re-create missing indexes, constraints and columns; having "default" values in tables should be OK

> Yes, it was some issues with the previous upgrades on the prod env, but the logs unfortunately are lost.
There was some incapability in the custom rule-nodes for the 3.6.4 version.

previous upgrade failures might affect future upgrades; the root cause and fix widely depends, but overall - checking difference between "reference" schema and your DB, and fixing these is a way to go

specifically about custom extensions - rarely, custom code affects upgrade procedure (usually, "method already exists" sort of errors); in my experience, the best way to go is to remove extensions from related directory for a time of upgrades - and, of course, checking for compatibility and if any changes are required in your extension (if required, this is noted in upgrade instructions, e.g. [here](https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#:~:text=net%20start%20thingsboard-,Upgrading%20to%203.5PE,-Ubuntu/CentOS))

**Comment by AVTaran** [comment]
Thank you one more time. 
Yes - we will adjust the database accordingly.
