### ISSUE TITLE
thingsboard pe docker can't upgrade from 3.6.1 version

### ISSUE THREAD

**Issue by adideju** [thingsboard/thingsboard#12250]
`**Describe` the bug**
When I try to upgrade from version 3.6.1 as per documentation I get the following error: 

admin@docker:~/containers/thingsboard$ docker compose stop mytbpe
[+] Stopping 1/1
 ✔ Container thingsboard-mytbpe-1  Stopped                                                                                                                           11.0s 
bsbadmin@docker:~/containers/thingsboard$ echo '3.6.1' | sudo tee ~/.mytbpe-data/.upgradeversion
3.6.1
admin@docker:~/containers/thingsboard$ docker compose run mytbpe upgrade-tb.sh
[+] Creating 1/0
 ✔ Container thingsboard-kafka-1  Running                                                                                                                             0.0s 
Starting ThingsBoard upgrade ...
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.6.1PE)
 ===================================================

Starting ThingsBoard Upgrade from version 3.6.1 ...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 3.6.1
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:295)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:66)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!

**Your Server Environment**
  * Deployment type: docker-compose
  * ThingsBoard Version : Professional Edition 3.6.1
  * Debian 11
  * 
docker-compose.yml

`services:
  kafka:
     restart: always
     image: bitnami/kafka:3.6.1
     ports:
       - 9092:9092 #to localhost:9092 from host machine
       - 9093 #for Kraft
       - 9094 #to kafka:9094 from within Docker network
     environment:
       ALLOW_PLAINTEXT_LISTENER: "yes"
       KAFKA_CFG_LISTENERS: "OUTSIDE://:9092,CONTROLLER://:9093,INSIDE://:9094"
       KAFKA_CFG_ADVERTISED_LISTENERS: "OUTSIDE://localhost:9092,INSIDE://kafka:9094"
       KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT"
       KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INSIDE"
       KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
       KAFKA_CFG_PROCESS_ROLES: "controller,broker" #KRaft
       KAFKA_CFG_NODE_ID: "0" #KRaft
       KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #KRaft
       KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093" #KRaft
     volumes:
       - kafka-data:/bitnami
     networks: 
       - proxy  

  mytbpe:
    restart: always
    image: "thingsboard/tb-pe:3.6.1PE"
    depends_on:
      - kafka
    ports:
#     - "8080:8080"
      - "1893:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iot.rule=Host(`iot.britishschool.ro`)"
      - "traefik.http.routers.iot.service=iot"
      - "traefik.http.routers.iot.entrypoints=websecure"
      - "traefik.http.services.iot.loadbalancer.server.port=8080"
      - "traefik.http.routers.iot.tls=true"
      - "traefik.http.routers.iot.tls.certresolver=letsencrypt"
      - "traefik.http.services.iot.loadbalancer.passhostheader=true"
      - "traefik.http.routers.iot.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"

    environment:
      TB_QUEUE_TYPE: kafka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      TB_KAFKA_SERVERS: kafka:9094
      TB_LICENSE_SECRET: CpWIq9B2RJ0P8jiRvGVG7Mq5
      TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
    volumes:
      - ./mytbpe-data:/data
      - ./mytbpe-logs:/var/log/thingsboard
    networks: 
      - proxy  

  postgres:
    restart: always
    image: "postgres:12"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./mytbpe-data/db:/var/lib/postgresql/data
    networks: 
      - proxy  

networks:
    proxy:
      external: true
volumes:
    kafka-data:
      driver: local
`

**Comment by pon0marev** [comment]
The error indicates that Thingsboard cannot upgrade from version 3.6.1. This is true because you are running version 3.6.1.
![image](https://github.com/user-attachments/assets/f6a61929-237e-4e01-aefe-7759985b8112)
What version did you have before upgrading? If you had version 3.6.1, please change the version of the image to `thingsboard/tb-pe:3.6.2PE` and run the upgrade from version 3.6.1.

**Comment by adideju** [comment]
The Thingsboard documentation clearly states otherwise: 
![ksnip_20241216-071928](https://github.com/user-attachments/assets/b3ba8de3-0f73-4d13-a41c-049392060945)

**Comment by pon0marev** [comment]
If you are already using version 3.6.1, you do not need to upgrade to version 3.6.1.
If you want to upgrade to a newer version, you should set the next version of the [thingsboard image](https://hub.docker.com/r/thingsboard/tb-pe/tags) in the file docker-compose.yml and set your current version of the thingsboard in the file `~/.mytbpe-data/.upgradeversion`.
The upgrade sequence can be seen here: https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/

**Comment by adideju** [comment]
Is the documentation  wrong? 
https://thingsboard.io/docs/user-guide/install/pe/docker/#upgrading

**Comment by adideju** [comment]
Ok. So I edited the composer file - kafka image 3.6.2 and tb-pe 3.6.2. The upgrade fails: 
Starting ThingsBoard upgrade ...
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.6.2PE)
 ===================================================

Starting ThingsBoard Upgrade from version 3.6.1 ...
Clearing cache to upgrade from version 3.6.1 to 3.6.2
Clearing cache [securitySettings]
Clearing cache [resourceInfo]
Upgrading ThingsBoard from version 3.6.1 to 3.6.2 ...
Updating schema ...
Skip schema re-update to version 3.6.2. Use env flag 'SKIP_SCHEMA_VERSION_CHECK' to force the re-update.
Updating schema ...
relation "entity_group" already exists, skipping
relation "converter" already exists, skipping
relation "integration" already exists, skipping
relation "scheduler_event" already exists, skipping
relation "blob_entity" already exists, skipping
relation "role" already exists, skipping
relation "group_permission" already exists, skipping
relation "device_group_ota_package" already exists, skipping
relation "converter_debug_event" already exists, skipping
relation "integration_debug_event" already exists, skipping
relation "raw_data_event" already exists, skipping
relation "white_labeling" already exists, skipping
column "customer_id" of relation "resource" already exists, skipping
relation "idx_entity_group_by_type_name_and_owner_id" already exists, skipping
relation "idx_converter_external_id" already exists, skipping
relation "idx_integration_external_id" already exists, skipping
relation "idx_role_external_id" already exists, skipping
relation "idx_entity_group_external_id" already exists, skipping
relation "idx_converter_debug_event_main" already exists, skipping
relation "idx_integration_debug_event_main" already exists, skipping
relation "idx_raw_data_event_main" already exists, skipping
Schema updated.
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating data ...
Unexpected error during ThingsBoard installation!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy249.findById(Unknown Source)
        at org.thingsboard.server.dao.sql.whitelabeling.JpaWhiteLabelingDao.findById(JpaWhiteLabelingDao.java:67)
        at org.thingsboard.server.dao.sql.whitelabeling.JpaWhiteLabelingDao$$FastClassBySpringCGLIB$$67662b4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at org.thingsboard.server.dao.aspect.SqlDaoCallsAspect.handleSqlCall(SqlDaoCallsAspect.java:173)
        at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at org.thingsboard.server.dao.sql.whitelabeling.JpaWhiteLabelingDao$$EnhancerBySpringCGLIB$$66c7eac1.findById(<generated>)
        at org.thingsboard.server.dao.wl.BaseWhiteLabelingService.findMailTemplatesByTenantId(BaseWhiteLabelingService.java:502)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:331)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:311)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:66)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.getResultSet(AbstractLoadPlanBasedLoader.java:390)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:163)
        at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:104)
        at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:285)
        at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:4550)
        at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4540)
        at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:571)
        at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:539)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:327)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:108)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:74)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
        at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1231)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1220)
        at org.hibernate.internal.SessionImpl.access$2100(SessionImpl.java:202)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.doLoad(SessionImpl.java:2848)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2825)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2781)
        at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2825)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3413)
        at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3380)
        at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:315)
        at com.sun.proxy.$Proxy186.find(Unknown Source)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById(SimpleJpaRepository.java:335)
        at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:530)
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:286)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:640)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:81)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        ... 40 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column whitelabel0_.customer_id does not exist
  Position: 8
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
        ... 88 common frames omitted
Unexpected error during ThingsBoard installation!

**Comment by pon0marev** [comment]
The `white_labeling.customer_id` column was not created for some reason, and it caused an error. Please attach the `~/.mytbpe-logs/install.log` for investigation.
Also, attach the schema of your white_labeling table:
```
psql -U POSTGRES_USER -h POSTGRES_HOST
\c thingsboard
\d+ white_labeling
```

**Comment by pon0marev** [comment]
The schema of your white_labeling table has not been updated. Try to update the schema manually. Make a backup of the database and run the following queries:
```
psql -U POSTGRES_USER -h POSTGRES_HOST -d thingsboard < schema_update_from_3.6.1.txt
```

[schema_update_from_3.6.1.txt](https://github.com/user-attachments/files/18164731/schema_update_from_3.6.1.txt)
You can also find the database schema update file by [installing ThingsBoard package](https://thingsboard.io/docs/user-guide/install/pe/ubuntu/#step-2-thingsboard-service-installation) and navigating to `/usr/share/thingsboard/data/upgrade/3.6.1/`
Then rerun the upgrade from version 3.6.1.

**Comment by adideju** [comment]
I run the schema update. 
root@c2fed770bc7d:/# psql -U postgres -d thingsboard < schema.txt
ALTER TABLE
ALTER TABLE
ALTER TABLE
NOTICE:  column "customer_id" of relation "resource" already exists, skipping
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
CREATE INDEX
CREATE FUNCTION
DO
DROP FUNCTION
DO
CREATE INDEX

I tried to upgrade TB and I got the same error.

Caused by: org.postgresql.util.PSQLException: ERROR: column whitelabel0_.entity_id does not exist
  Position: 8
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)

**Comment by adideju** [comment]
Nevermind, I forgot to edit the upgradeversion file. I managed to update to 3.6.2 and it seems to be working. I will check everything and get back.

**Comment by adideju** [comment]
Successfully updated to 3.8.1 
Thank you for your support.
