### ISSUE TITLE
Issue upgrading thingsboard to 3.8.0 from 3.7.0

### ISSUE THREAD

**Issue by sjthings** [thingsboard/thingsboard#12362]
While upgrading thingsboard to version 3.8 from 3.7, I am facing below issue. 

[install.log](https://github.com/user-attachments/files/18279382/install.log)

Clearing cache [customTranslation]
Clearing cache [customMenu]
Clearing cache [entityGroups]
Upgrading ThingsBoard from version 3.7.0 to 3.8.0 ...
Updating schema ...
**Failed updating schema!!!
org.postgresql.util.PSQLException: ERROR: extension "uuid-ossp" is not available**
  Detail: Could not open extension control file "/usr/pgsql-15/share/extension/uuid-ossp.control": No such file or directory.
  Hint: The extension must first be installed on the system where PostgreSQL is running.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)

	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	... 60 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column te1_0.version does not exist
  Hint: Perhaps you meant to reference the column "te1_0.region".
  Position: 197
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInte

Need urgent support to resolve, as our server is down now :(

**Comment by Ultrazombie** [comment]
Hello @sjthings,
Please check if the **contrib** extension is installed.
```
SELECT * FROM pg_available_extensions WHERE name = 'uuid-ossp';
```

Try to install it if there is a local database.
```
 sudo apt-get install postgresql-contrib
```

**Comment by sjthings** [comment]
Thank you, this helped.
