### ISSUE TITLE
Custom Widget -> onUpdateTimewindow error

### ISSUE THREAD

**Issue by glancia** [thingsboard/thingsboard#1268]
Dear community,

I'm desgining my first time-series custom widget. I'd like to create some buttons to shortcut the timewindow change, such as "Today", "Yesterday", etc.

I'm using the following statement: self.ctx.timewindowFunctions.onUpdateTimewindow(start,end);

Sometimes it works, but most of the times it just changes the widget timewindow string on the title, but doesn't refresh data.

I get the following error message.

Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.5.8/$rootScope/inprog?p0=%24apply
    at angular.js:68
    at m (angular.js:18042)
    at p.$digest (angular.js:17472)
    at p.$apply (angular.js:17790)
    at Object.timeWindowUpdated (widget.controller.js:318)
    at e.value (subscription.js:602)
    at Object.onUpdateTimewindow (widget.controller.js:81)
    at t.eval [as Hoje] (eval at G (widget.service.js:607), <anonymous>:157:38)
    at fn (eval at compile (angular.js:14817), <anonymous>:4:203)
    at t (angular.js:15906)

Any ideas?

Tks

**Comment by vparomskiy** [comment]
Did you implement onDataUpdated function? It is called when time window is changed.
Does this method triggered when you update a time-window?

**Comment by vparomskiy** [comment]
Close since no updates available

**Comment by asadshaik1103** [comment]
Hey,
I tried to use same function onUpdateTimewindow(new Date(1568120400 * 1000), new Date(), 10); 
This just updates the timewindow title, but doesn't update the data. I have also checked the onDataUpdated() does not execute. I get the error in my browser console, 
 Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.8/$rootScope/inprog?p0=%24digest
    at http://localhost:3000/bundle.js:215557:13
    at beginPhase (http://localhost:3000/bundle.js:233531:16)
    at Scope.$digest (http://localhost:3000/bundle.js:232961:10)
    at Scope.$apply (http://localhost:3000/bundle.js:233279:25)
    at Object.timeWindowUpdated (http://localhost:3000/bundle.js:283314:25)
    at Subscription.onUpdateTimewindow (http://localhost:3000/bundle.js:271637:33)
    at Object.onUpdateTimewindow (http://localhost:3000/bundle.js:283086:56)
    at http://localhost:3000/bundle.js:312059:41
    at Scope.$broadcast (http://localhost:3000/bundle.js:233494:29)
    at http://localhost:3000/bundle.js:123575:25 undefined

Any help is appreciated.

**Comment by Manusisko** [comment]
Anyone has found any luck with this issue? I've successfully updated the dashboard timewindow, but not the widget's one. The title does change, and  onDataUpdated actually fires but data does not change.

**Comment by Manusisko** [comment]
For anyone still looking, found the solution, the problem is that in some cases, attemting to change the timewindow during the life-cycle of the AngularJS front-end causes an issue with overlapping $apply calls. I was able to run the command forcing it to execute after the $digest event finished.

scope.updateTs = function(data){
        console.log("Updating");
        self.ctx.timewindowFunctions.onUpdateTimewindow(
            data.startTime, data.endTime);
    }
    
    scope.$root.$on('flot-update-timewindow', function(event, data){
        self.ctx.$scope.$$postDigest(function(){
            scope.updateTs(data);
        });
    });
