### ISSUE TITLE
Error filter script

### ISSUE THREAD

**Issue by leonmyburg** [thingsboard/thingsboard#1274]
Hi get the following error from filter script. When I make a new filter script with the same code it works. I am not sure what causes the filter script to fail. Once the script fails (even though it worked before) it never recovers. I have to delete it and add a new one with same code.

javax.script.ScriptException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeScript(RuleNodeJsScriptEngine.java:174)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeFilter(RuleNodeJsScriptEngine.java:135)
	at org.thingsboard.rule.engine.filter.TbJsFilterNode.lambda$onMsg$0(TbJsFilterNode.java:54)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeScript(RuleNodeJsScriptEngine.java:168)
	... 8 more
Caused by: java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at org.thingsboard.server.service.script.AbstractNashornJsSandboxService.invokeFunction(AbstractNashornJsSandboxService.java:129)
	... 9 more
Caused by: javax.script.ScriptException: java.lang.RuntimeException: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.NashornSandboxImpl$1.invokeFunction(NashornSandboxImpl.java:353)
	at org.thingsboard.server.service.script.AbstractNashornJsSandboxService.invoke(AbstractNashornJsSandboxService.java:146)
	at org.thingsboard.server.service.script.AbstractNashornJsSandboxService.invokeFunction(AbstractNashornJsSandboxService.java:135)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.ThreadMonitor.run(ThreadMonitor.java:130)
	at delight.nashornsandbox.internal.JsEvaluator.runMonitor(JsEvaluator.java:47)
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:161)
	at delight.nashornsandbox.internal.NashornSandboxImpl.access$000(NashornSandboxImpl.java:36)
	at delight.nashornsandbox.internal.NashornSandboxImpl$1.invokeFunction(NashornSandboxImpl.java:349)
	... 11 more
Caused by: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.ThreadMonitor.run(ThreadMonitor.java:91)
	... 15 more

**Comment by vparomskiy** [comment]
1. For refreshing all blacklisted scripts inside Rule Chain - you do not have to edit js nodes, you just need to resave Rule Chain.
2. Scripts can be blacklisted if script execution time is more than 100 ms. Or if script execution throws an error.
There are 2 reasons why script can have a long execution time 
1) heavy script 
2)high total system load. I think that your case is a high system load.
`Caused by: javax.script.ScriptException: java.lang.RuntimeException: java.lang.IllegalStateException: Executor thread not set after 100 ms`

3. You can disable script execution time monitoring by disabling js sandbox in the thingsboard.yml (use_js_sandbox = false)


What is your current system load (messages per second) and what DB are you using?

**Comment by leonmyburg** [comment]
1. Have tried re-saving but did not seem to have any affect.
2. I do see the "Executor thread not set after 100 ms" in some of the error messages. 

Can the execution time be set to say 500ms? If I disable use_js_sandbox what will happen to a script that has an actual issue during execution?

The current load is low less than 10 messages per second and the JSON payload has less than 40 key value pairs. TB is installed on 1 CPU 6.5Gb machine with Cassandra DB.

I have about 40 nodes in my rule chain. Might this also cause an issue?

**Comment by leonmyburg** [comment]
I increased the system resources from 1 core to 2 cores with 2GB extra RAM. Seems to have fixed the problem so far.
