### ISSUE TITLE
TB crash after a day or so

### ISSUE THREAD

**Issue by BarlowHall** [thingsboard/thingsboard#1279]
Hi.

I have TB community version 2.1 running on an Ubuntu AWS free tier 1GB RAM system. It crashes every day or 2. I have the java heap options set to:

export JAVA_OPTS="$JAVA_OPTS -Xms256M -Xmx512M"

The crash reports always contain:

2018-11-23 10:13:08,886 [nioEventLoopGroup-6-11] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt11] Unexpected Exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
...etc

Is this a known issue with known fix? Is there a way to use systemd to restart the service? to keep it going?

**Comment by vparomskiy** [comment]
I can help if you will:
1. share your thingsboard.log file
2. what DB are you using (hsqldb, postgres, cassandra)?
3. what load is generated/how many requests per second?
4. What is Database size (Gb/MB)

**Comment by BarlowHall** [comment]
Thanks for jumping in so quickly.

The logfile is attached.

I'm using hsqldb. 
I have 5 devices created and only 3 reporting in every 15min. 
If the data base file is the one here: 
/usr/share/thingsboard/data/sql/thingsboardDb.script then it's 79MB

[thingsboard.log](https://github.com/thingsboard/thingsboard/files/2610435/thingsboard.log)

**Comment by BarlowHall** [comment]
Hi,

I uploaded the information as requested. I’m looking to build an IoT tech startup around thingsboard and it’s excellent functionality so hope we can resolve it’s instability soon.


Regards

Neale

Neale A Hall
nabh@me.com
www.linkedin.com/in/nealeahall

**Comment by vparomskiy** [comment]
You are using old version of the Thingsboard (v2.1.0). Pelase use the letest version (2.1.3)

**Comment by BarlowHall** [comment]
Will be happy to. I tried to install it over the current version following the instructions for the 2.1 update I have and it failed. I substituted the 2.1.3 file and used the same procedure. What are the update instructions?

Regards

Neale
nabh@icloud.com
Tel: +44 7453299543

**Comment by IvanSemenenko** [comment]
Hi Neale,

In the case with 2.1.3 version
you should stop thingsboard service

sudo systemctl stop thingsboard

and run the upgrade script:

sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.0.0

Start thingsboard service
sudo systemctl  start thingsboard

Regards,

**Comment by BarlowHall** [comment]
OK thanks. I will try that.

Is there a procedure to move the database to Postgres? I think I’d like to try out that but don’t want to loose the current data set.

Regards

Neale

Neale A Hall
nabh@me.com
www.linkedin.com/in/nealeahall

**Comment by IvanSemenenko** [comment]
You are welcome.

Unfortunately, it is impossible.
We don't have such a procedure.

Regards,

**Comment by BarlowHall** [comment]
OK I shall try the procedure and report back if it fails.


Regards

Neale

Neale A Hall
nabh@me.com
www.linkedin.com/in/nealeahall

**Comment by BarlowHall** [comment]
Hi,

Tried this procedure and got the following error:

ubuntu@ip-172-31-25-57:~/thingsboard$ sudo dpkg --unpack thingsboard-2.1.3.deb 
(Reading database ... 135002 files and directories currently installed.)
Preparing to unpack thingsboard-2.1.3.deb ...
Unpacking thingsboard (2.1.3-1) over (2.1.0-1) ...
Processing triggers for systemd (229-4ubuntu21.9) ...
Processing triggers for ureadahead (0.100.0-19) ...
ubuntu@ip-172-31-25-57:~/thingsboard$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.0.0
 ===================================================
 :: ThingsBoard ::       (v2.1.3)
 ===================================================

Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
ThingsBoard upgrade failed!

So then I tried using dpkg -I and then your commend line and got this error:

sudo dpkg -i thingsboard-2.1.3.deb 
(Reading database ... 135010 files and directories currently installed.)
Preparing to unpack thingsboard-2.1.3.deb ...
Unpacking thingsboard (2.1.3-1) over (2.1.3-1) ...
Setting up thingsboard (2.1.3-1) ...
Installing new version of config file /usr/share/thingsboard/conf/thingsboard.yml ...
Processing triggers for systemd (229-4ubuntu21.9) ...
Processing triggers for ureadahead (0.100.0-19) ...
ubuntu@ip-172-31-25-57:~/thingsboard$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.0.0
 ===================================================
 :: ThingsBoard ::       (v2.1.3)
 ===================================================

Starting ThingsBoard Upgrade from version 2.0.0 ...
Upgrading ThingsBoard from version 2.0.0 to 2.1.1 ...
Updating schema ...
Unexpected error during ThingsBoard installation!
java.sql.SQLSyntaxErrorException: object name already exists: ENTITY_VIEW_PKEY in statement [CREATE TABLE IF NOT EXISTS entity_views (
    id varchar(31) NOT NULL CONSTRAINT entity_view_pkey PRIMARY KEY,
    entity_id varchar(31),
    entity_type varchar(255),
    tenant_id varchar(31),
    customer_id varchar(31),
    name varchar(255),
    keys varchar(255),
    start_ts bigint,
    end_ts bigint,
    search_text varchar(255),
    additional_info varchar
)]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.loadSql(SqlDatabaseUpgradeService.java:160)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:124)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:98)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.hsqldb.HsqlException: object name already exists: ENTITY_VIEW_PKEY
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.SchemaObjectSet.add(Unknown Source)
	at org.hsqldb.Schema.addSchemaObject(Unknown Source)
	at org.hsqldb.SchemaManager.addSchemaObject(Unknown Source)
	at org.hsqldb.ParserTable.addTableConstraintDefinitions(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 14 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
So I tried specifying upgrade from version 2.1.0 that I’m actually running and got this:
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.1.0
 ===================================================
 :: ThingsBoard ::       (v2.1.3)
 ===================================================

Starting ThingsBoard Upgrade from version 2.1.0 ...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 2.1.0
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:122)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
When I start up the the dashboards report version 2.1.3. Is this safe to run having had the errors above? 

Regards

Neale

Neale A Hall
nabh@me.com
www.linkedin.com/in/nealeahall

**Comment by BarlowHall** [comment]
I've just noticed that I now have a tab control called entity-view.management that when clicked has a blank window with the text "ENTITY-VIEW.NO-ENTITY-VIEWS-TEXT" in the middle

Is this normal after an upgrade or is something broken as a result of the above?

**Comment by IvanSemenenko** [comment]
Hi Neale,

It is an artifact in your browser.
Refresh the page or clear cache, please.

Regards,

**Comment by BarlowHall** [comment]
Just tried it from my iphone using chrome for the first time and its still there 

Any other ideas?

Regards

Neale
nabh@icloud.com
Tel: +44 7453299543

**Comment by IvanSemenenko** [comment]
Could you try to check it from a laptop or PC, please?

Regards,

**Comment by BarlowHall** [comment]
OK went to a laptop and tried that. Cleared the caches and it now says Entity views so I guess that is OK now. Thanks.

Any comments on the install script failures?


Regards

Neale

Neale A Hall
nabh@me.com
www.linkedin.com/in/nealeahall

**Comment by volodymyr-babak** [comment]
here is the official documentation for ThingsBoard upgrade process:
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/
