### ISSUE TITLE
thingsboard  carsh ,  log report ERROR got more than one input and Unknow message WARN 

### ISSUE THREAD

**Issue by zouhr** [thingsboard/thingsboard#1337]
2018-12-15 11:57:18,946 [Akka-akka.actor.default-dispatcher-14811] WARN  o.t.s.actors.ruleChain.RuleNodeActor - Unknown message: org.thingsboard.server.actors.stats.StatsPersistTick@3786377d!
this WARN will display per hour， next time 12.57.18 will display WARN。
how to find the error reason?

**Comment by zouhr** [comment]
2018-12-15 09:33:02,514 [pool-9-thread-19608] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
2018-12-15 09:33:02,514 [pool-9-thread-19607] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
2018-12-15 09:33:02,514 [pool-9-thread-19604] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
2018-12-15 09:33:02,514 [pool-9-thread-19622] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures

**Comment by zouhr** [comment]
2018-12-15 08:44:31,894 [pool-9-thread-12872] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
        at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:131)
        at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.isDone(RateLimitedResultSetFuture.java:95)
        at com.google.common.util.concurrent.AggregateFuture$RunningState.handleOneInputDone(AggregateFuture.java:204)
        at com.google.common.util.concurrent.AggregateFuture$RunningState.access$200(AggregateFuture.java:78)
        at com.google.common.util.concurrent.AggregateFuture$RunningState$1.run(AggregateFuture.java:133)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
        at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:636)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:100)
        at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.lambda$addListener$2(RateLimitedResultSetFuture.java:122)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:677)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:112)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
        at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:713)
        at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:185)
        at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:162)
        at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:138)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
        at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:553)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.cancel(AbstractFuture.java:106)
        at org.thingsboard.server.dao.util.BufferedRateLimiter$LockedFuture.cancelFuture(BufferedRateLimiter.java:171)
        at org.thingsboard.server.dao.util.BufferedRateLimiter.printStats(BufferedRateLimiter.java:148)
        at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
        at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:129)
        ... 40 common frames omitted
Caused by: java.util.concurrent.CancellationException: Task was cancelled.
        at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1114)
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
        at com.google.common.util.concurrent.Futures.getDone(Futures.java:1174)
        at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:110)
        ... 19 common frames omitted

**Comment by vparomskiy** [comment]
please provide full log file

**Comment by ashvayka** [comment]
This error usually means that there were too many DB operations and they got rate limited.

**Comment by zouhr** [comment]
when i upgrade to 2.2.0 from 2.1 , error is not show . thankyou
