### ISSUE TITLE
use  CoAP-CLI request attribute values from the server timeout

### ISSUE THREAD

**Issue by ShengtianM** [thingsboard/thingsboard#1341]
I use coap api to request attribute values from the server，it has no response and a timeout error occurred.Thingsboard version is 2.1.The coap command is "coap get -o coap://localhost/api/v1/Le2g709J4c3MHOjLX7rg/attributes".The log is
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: No reply in 30s
    at null._onTimeout (C:\Users\tian\AppData\Roaming\npm\node_modules\coap-cli\node_modules\coap\lib\retry_send.js:69:18)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by ShengtianM** [comment]
The reason is the coap service in thingsboard is off by default. Change coap.enabled false to true in thingsboard.yml.
