### ISSUE TITLE
thingsboard 2.2.0 packet loss 

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#1387]
Hello,

I am using thingsboard 2.2.0 and tb gateway 2.1.1. I notice, not every message are not arived to the thingsboard. I have found this message in the log file.

java.io.IOException: Connection reset by peer

                at sun.nio.ch.FileDispatcherImpl.read0(Native Method)

                at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)

                at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)

                at sun.nio.ch.IOUtil.read(IOUtil.java:192)

                at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)

                at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)

                at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)

                at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)

                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)

                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)

                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)

                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)

                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)

                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)

                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

                at java.lang.Thread.run(Thread.java:748)

**Comment by JozsefGuyas** [comment]
I have tried to downgrade the tb gateway to 1.2.2, and the problem have been eliminated.
I suspect the tbgateway 2.1.1 loses some message
