### ISSUE TITLE
thingsboard javascript error.

### ISSUE THREAD

**Issue by mysty-mystic** [thingsboard/thingsboard#1419]
[DEBUG] All known ContainerDescriptorHandler components: [metaInf-spring, metaInf-services, plexus, file-aggregator]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [ 20.576 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  8.062 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.259 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 15.468 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  4.092 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  2.423 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.148 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [ 10.461 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  2.673 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  1.128 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.538 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [06:41 min]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.127 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  2.126 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [ 14.431 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.624 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 15.571 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 14.278 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 13.773 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [04:20 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  1.014 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [24:27 min]
[INFO] ThingsBoard Microservices .......................... SUCCESS [  4.942 s]
[INFO] ThingsBoard Docker Images .......................... SUCCESS [02:00 min]
[INFO] ThingsBoard JavaScript Executor Microservice ....... FAILURE [ 13.845 s]
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40:00 min
[INFO] Finished at: 2019-01-25T12:31:30+05:30
[INFO] Final Memory: 80M/423M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (assembly) on project js-executor: Failed to create assembly: Error adding file to archive: /home/tarun/work/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (assembly) on project js-executor: Failed to create assembly: Error adding file to archive: /home/tarun/work/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create assembly: Error adding file to archive: /home/tarun/work/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:530)
	at org.apache.maven.plugins.assembly.mojos.SingleAssemblyMojo.execute(SingleAssemblyMojo.java:58)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.plugins.assembly.archive.ArchiveCreationException: Error adding file to archive: /home/tarun/work/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at org.apache.maven.plugins.assembly.archive.phase.FileItemAssemblyPhase.execute(FileItemAssemblyPhase.java:131)
	at org.apache.maven.plugins.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
	at org.apache.maven.plugins.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:476)
	... 23 more
Caused by: java.nio.file.NoSuchFileException: /home/tarun/work/thingsboard/msa/js-executor/target/package/windows/bin/tb-js-executor.exe
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:218)
	at sun.nio.fs.UnixFileAttributeViews$Unix.readAttributes(UnixFileAttributeViews.java:345)
	at sun.nio.fs.AbstractFileSystemProvider.readAttributes(AbstractFileSystemProvider.java:92)
	at java.nio.file.Files.readAttributes(Files.java:1964)
	at org.codehaus.plexus.components.io.attributes.Java7FileAttributes.<init>(Java7FileAttributes.java:65)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPathJava7(PlexusIoResourceAttributeUtils.java:336)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPath(PlexusIoResourceAttributeUtils.java:198)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributes(PlexusIoResourceAttributeUtils.java:175)
	at org.codehaus.plexus.components.io.resources.ResourceFactory.createResource(ResourceFactory.java:40)
	at org.apache.maven.plugins.assembly.archive.phase.FileItemAssemblyPhase.execute(FileItemAssemblyPhase.java:120)
	... 25 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :js-executor

**Comment by mysty-mystic** [comment]
this error occurs when i try to build from source using ****mvn clean install -Ddockerfile.skip=false 
 kindly help me fix this error.

**Comment by m0o0hammad** [comment]
https://github.com/thingsboard/thingsboard/issues/1412     Please read this

**Comment by mysty-mystic** [comment]
From which folder are you running the command? I am running from
thingsboard folder,.  Do I need to go to any sub folder to run the command?

**Comment by m0o0** [comment]
Just change the two folders below:
$nano (directory thingsboard)/msa/web-ui/pom.xml and 
$nano (directory thingsboard)/msa/js-executor/pom.xml

remove block in pom.xml:
<plugin> 
<groupId>org.apache.maven.plugins</groupId> 
<artifactId>maven-assembly-plugin</artifactId> 
<version>3.0.0</version> <configuration> 
<finalName>${pkg.name}</finalName> 
<descriptors> <descriptor>src/main/assembly/windows.xml</descriptor> </descriptors> </configuration> <executions> <execution> 
<id>assembly</id> 
<phase>package</phase> 
<goals> <goal>single</goal> </goals> 
</execution> </executions> 
</plugin>

**Comment by googlehim** [comment]
> Just change the two folders below:
> $nano (directory thingsboard)/msa/web-ui/pom.xml and
> $nano (directory thingsboard)/msa/js-executor/pom.xml
> 
> remove block in pom.xml:
> `<plugin> <groupId>org.apache.maven.plugins</groupId> <artifactId>maven-assembly-plugin</artifactId> <version>3.0.0</version> <configuration> <finalName>${pkg.name}</finalName> <descriptors> <descriptor>src/main/assembly/windows.xml</descriptor> </descriptors> </configuration> <executions> <execution> <id>assembly</id> <phase>package</phase> <goals> <goal>single</goal> </goals> </execution> </executions> </plugin>`

Can you explain why,  and why these lines are here?
