### ISSUE TITLE
Problem with adding new dependency (devtool) for live reload 

### ISSUE THREAD

**Issue by arsenal120496** [thingsboard/thingsboard#1428]
```java
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:396)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:373)
        at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:251)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:227)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
        at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:38)
Caused by: java.lang.NoSuchMethodException: org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:391)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:21 min
[INFO] Finished at: 2019-01-29T10:03:27+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.3.RELEASE:run (default-cli) on project application: Could not exec java: Application finished with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I try to add new dependency:
```java
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <version>1.3.0.RELEASE</version>
</dependency>
```

I got a problem with this. I add this into pom.xml in application folder and main pom.xml of project and both of them but can't run with 
```java 
mvn spring-boot:run
```

Can some one help me? Tks a

**Comment by Ultrazombie** [comment]
Please reopen if the problem still exists
