### ISSUE TITLE
BUILD FAILURE -  unpack should be executed after packaging

### ISSUE THREAD

**Issue by win32cpp** [thingsboard/thingsboard#1512]
**This error happends when i compile thingsboard 2.3.0**
[INFO] ---------------------< org.thingsboard.msa:web-ui >---------------------
[INFO] Building ThingsBoard Web UI Microservice 2.3.0                   [26/32]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy (copy-protoc) @ web-ui ---
[INFO] Configured Artifact: com.google.protobuf:protoc:windows-x86_64:3.0.2:exe
[INFO] Copying protoc-3.0.2-windows-x86_64.exe to C:\thingsboard-2.3\msa\web-ui\
target\protoc-3.0.2-windows-x86_64.exe
[INFO]
[INFO] --- maven-dependency-plugin:2.8:unpack (extract-web-ui) @ web-ui ---
[INFO] Configured Artifact: org.thingsboard:ui:?:jar
[INFO] Unpacking C:\thingsboard-2.3\ui\target\classes to C:\thingsboard-2.3\msa\
web-ui\target\web with includes "" and excludes ""
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 2.3.0:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  0.120 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  1.999 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.028 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  0.824 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [ 13.454 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  0.342 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.034 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [ 13.175 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  0.619 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.556 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.338 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [  2.528 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.051 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.237 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  2.480 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.069 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [  0.673 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [  0.458 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [  0.463 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [02:54 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  0.130 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [ 26.845 s]
[INFO] ThingsBoard Microservices .......................... SUCCESS [  0.040 s]
[INFO] ThingsBoard Docker Images .......................... SUCCESS [  0.216 s]
[INFO] ThingsBoard JavaScript Executor Microservice ....... SUCCESS [ 37.579 s]
**[INFO] ThingsBoard Web UI Microservice .................... FAILURE [  0.099 s]**
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:41 min
[INFO] Finished at: 2019-02-23T18:48:25+03:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:
2.8:unpack (extract-web-ui) on project web-ui: Artifact has not been packaged ye
t. When used on reactor artifact, unpack should be executed after packaging: see
 MDEP-98. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :web-ui

**Comment by ericyansuzhou** [comment]
I was seen same issue and trying to find solution but still failed, please support, thanks

**Comment by ericyansuzhou** [comment]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:40 min
[INFO] Finished at: 2019-02-26T10:43:25+08:00
[INFO] Final Memory: 66M/937M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (extract-web-ui) on project web-ui: Error unpacking file: /home/thingsboard-source-2.3/ui/target/classes to: /home/Eric/thingsboard-source-2.3/msa/web-ui/target/web
[ERROR] org.codehaus.plexus.archiver.ArchiverException: The source file /home/Eric/thingsboard-source-2.3/ui/target/classes doesn't exist.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (extract-web-ui) on project web-ui: Error unpacking file: /home/Eric/thingsboard-source-2.3/ui/target/classes to: /home/thingsboard-source-2.3/msa/web-ui/target/web
org.codehaus.plexus.archiver.ArchiverException: The source file /home/thingsboard-source-2.3/ui/target/classes doesn't exist.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error unpacking file: /home/Eric/thingsboard-source-2.3/ui/target/classes to: /home/Eric/thingsboard-source-2.3/msa/web-ui/target/web
org.codehaus.plexus.archiver.ArchiverException: The source file /home/Eric/thingsboard-source-2.3/ui/target/classes doesn't exist.
        at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:323)
        at org.apache.maven.plugin.dependency.fromConfiguration.UnpackMojo.unpackArtifact(UnpackMojo.java:128)
        at org.apache.maven.plugin.dependency.fromConfiguration.UnpackMojo.doExecute(UnpackMojo.java:106)
        at org.apache.maven.plugin.dependency.AbstractDependencyMojo.execute(AbstractDependencyMojo.java:167)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: The source file /home/Eric/thingsboard-source-2.3/ui/target/classes doesn't exist.
        at org.codehaus.plexus.archiver.AbstractUnArchiver.validate(AbstractUnArchiver.java:191)
        at org.codehaus.plexus.archiver.AbstractUnArchiver.extract(AbstractUnArchiver.java:119)
        at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:315)
        ... 25 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :web-ui

**Comment by alexsmartens** [comment]
@ericyansuzhou,
have you seen #1518? It seems to be similar to what you are seeing

**Comment by ericyansuzhou** [comment]
> @ericyansuzhou,
> have you seen #1518? It seems to be similar to what you are seeing

Thank you, Alex, the issue have solved.

**Comment by masterchen** [comment]
> > @ericyansuzhou,
> > have you seen #1518? It seems to be similar to what you are seeing
> 
> Thank you, Alex, the issue have solved.

@ericyansuzhou  hi, how did you solve te problem, can you share the solution ?

**Comment by sungravity** [comment]
try this:

https://stackoverflow.com/questions/13170860/failed-to-execute-goal-org-apache-maven-pluginsmaven-surefire-plugin2-10test

mvn clean install -U

**Comment by xujingzhou** [comment]
I met same issue on windows, could you tell me how to slove?.

**Comment by Ultrazombie** [comment]
Closed due inactivity
