### ISSUE TITLE
Building ThingsBoard 2.3 on CentOS 7 (or RHEL 7)

### ISSUE THREAD

**Issue by musskopf** [thingsboard/thingsboard#1518]
This is not much as of an issue, but more of a guide for those who might be having similar issues when building ThingsBoard on a CentOS.

# Step 1: Install and configure the Building Tools
On a fresh CentOS OS 7.0 - CentOS Linux release 7.6.1810 (Core) on Google Cloud. I've prepared the building environment as the following:

## Install basic OS Tools:
```
$ sudo yum install git wget
$ sudo yum groups install "Development Tools"
```

## Java and Maven on my Homedir
Note that the Java link below might not work for you. Have a look at the Oracle site and find a way to download the Java JDK ".tar.gz" for your system.
At this point, I was trying to use the latest JDK 8 release, jdk-8u201 (which didn't work - see til the end).
```
$ cd ~/
$ mkdir build && cd build
$ wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
$ tar -xvzf apache-maven-3.5.4-bin.tar.gz
$ ln -s apache-maven-3.5.4 apache-maven

$ wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz"
$ tar -xvzf jdk-8u201-linux-x64.tar.gz
$ ln -s jdk1.8.0_201 java
```
Note: There's no need to install NodeJs as it's configured by the Build Process itseld

## Configure session Environment Variables
With the Tools Installed I configure the JAVA_HOME, M2_HOME and PATH
```
$ cd ~/
$ export JAVA_HOME=~/build/java
$ export M2_HOME=~/build/apache-maven
$ export PATH=${JAVA_HOME}/bin:${M2_HOME}/bin:${PATH}
```
Those are set only for the current session, if you loging again, you need to re-defice. There are many ways to make thoses environment variables permanent, I'll leave that with you.

### Configuring GIT to use only HTTP/HTTPS
Because my network doesn't allow SSH traffic I set some GIT parameters:
```
$ git config --global url."https://github.com/".insteadOf git@github.com:
$ git config --global url."https://".insteadOf git://
```
Many parts of the build process will try to download dependencies using GIT.

## Test the Build Tools
You can test if everything is fine by running:
```
$ mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /home/user1/build/apache-maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /home/user1/build/jdk1.8.0_201/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.el7.x86_64", arch: "amd64", family: "unix"

$ git ls-remote -h -t git://github.com/thingsboard/thingsboard.git
e86de7f30a9d20f15e5a0da6176aef87eb6f6026        refs/heads/feature/spring-boot-2
c5171f003e85ecdc57f9d44a0eaffa188a6bc4db        refs/heads/master
71a64fe7b5535e6adc854e28900eb91fc398b77d        refs/heads/release-1.0
dd2f88f7b7c2f1513a6540d1f50034030cef5657        refs/heads/release-1.1
2cfaf8f0f345c2ad535b5e2d476cbc44b6b6a26c        refs/heads/release-1.2
(...)
```
Pay attention to the Maven and Java versions and locations to confirm those are the ones you want to use.

# Step 2: Download and Build thingsboard

## Clean-up any Maven, NPM, etc Caches
To make sure I start a fresh build, I removed all cache/downloaded files used during any previous build.
```
$ cd ~/
$ rm -Rf ~/.config ~/.cache ~/.gradle ~/.m2 ~/.npm ~/.oracle_jre_usage ~/.pkg-cache ~/.pki
```
This step can be repeated as many times you wish. It just will slow down things a bit because of the need to re-download dependencies.

## Building it the first time (and failing)
Basically, download the source, and checkout the Tag you wish to build, and build it.
You need to make sure you environment still happy with the correct Java and Maven environment variables and PATH.
```
$ cd ~/
$ mkdir src && cd src
$ git clone https://github.com/thingsboard/thingsboard.git
$ cd thingsboard
$ git checkout v2.3

$ mvn clean install
(this will take a while, and in my case failed few times)
```

# Step 4: Try again until the build passes
Apart from some more specific issues, it's important to make sure that your build server has access to the Internet to download dependencies as well plenty of memory (probably at least 2-4Gb?) and no other heavy process running on the same machine. Maven tests can be demanding tasks, spawining other Java processes chewing plenty of resources.

Note that some tests will actually produce error dumps on the screen, but those are not real errors. Unfortunately this can be confusing when looking for the real issues.

## First issue: UI component - NPM pngquant
One of the NPM modules requires a specific version of libpng.

### Build error output
```
(...)
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ ui ---
[INFO] Running 'npm install' in /home/user1/src/thingsboard/ui
[INFO]
[INFO] > node-sass@4.10.0 install /home/user1/src/thingsboard/ui/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO]
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-48_binding.node
[INFO] Download complete
[INFO] Binary saved to /home/user1/src/thingsboard/ui/node_modules/node-sass/vendor/linux-x64-48/binding.node
[INFO] Caching binary to /home/user1/.npm/node-sass/4.10.0/linux-x64-48_binding.node
[INFO]
[INFO] > gifsicle@3.0.4 postinstall /home/user1/src/thingsboard/ui/node_modules/gifsicle
[INFO] > node lib/install.js
[INFO]
[ERROR]   ✔ gifsicle pre-build test passed successfully
[INFO]
[INFO] > jpegtran-bin@3.2.0 postinstall /home/user1/src/thingsboard/ui/node_modules/jpegtran-bin
[INFO] > node lib/install.js
[INFO]
[ERROR]   ✔ jpegtran pre-build test passed successfully
[INFO]
[INFO] > optipng-bin@3.1.4 postinstall /home/user1/src/thingsboard/ui/node_modules/optipng-bin
[INFO] > node lib/install.js
[INFO]
[ERROR]   ✔ optipng pre-build test passed successfully
[INFO]
[INFO] > pngquant-bin@4.0.0 postinstall /home/user1/src/thingsboard/ui/node_modules/pngquant-bin
[INFO] > node lib/install.js
[INFO]
[ERROR]   ⚠ The `/home/user1/src/thingsboard/ui/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
[ERROR]   ⚠ pngquant pre-build test failed
[ERROR]   ℹ compiling from source
[ERROR]   ✔ pngquant pre-build test passed successfully
[ERROR]   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
[ERROR]     at Promise.all.then.arr (/home/user1/src/thingsboard/ui/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
[ERROR]     at process._tickCallback (internal/process/next_tick.js:103:7)
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR]
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/user1/.npm/_logs/2019-02-27T01_23_18_526Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard 2.3.0 .................................. SUCCESS [ 54.402 s]
[INFO] Netty MQTT Client .................................. SUCCESS [01:09 min]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.108 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 38.939 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [ 16.373 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [ 18.453 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.045 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [ 29.847 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [ 16.145 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  2.042 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  2.740 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [06:11 min]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.069 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.785 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [01:23 min]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.055 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 54.735 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [  8.433 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [  7.931 s]
[INFO] Thingsboard Server UI .............................. FAILURE [01:57 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests 2.3.0 .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:21 min
[INFO] Finished at: 2019-02-27T01:23:18Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Failed to run task: 'npm install' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ui
```

### Simple fix
After some research I discover that the standard libpng installed by CentOS is not compatible.
```
$ sudo yum install libpng12
```

### NPM Additional investigation
If you need to investigate a bit more about the NPM install, you can try to run:
```
$ cd ~/src/thingsboard/ui
$ target/node/node "target/node/node_modules/npm/bin/npm-cli.js" "install" --scripts-prepend-node-path
```
The command above is quicker than re-running all Maven build just to test NPM.

## Second issue: Java JDK version
It took some time to figure out, but not all tests for the "Server Application" componente were passing. Without looking deep at the code I ended up (by luck) using another JDK version: jdk-8u161 and the tests started to pass.

### Build error output
```
(...)
2019-02-27 01:58:15,722 [Akka-akka.actor.default-dispatcher-4] INFO  akka.actor.LocalActorRef - Message [akka.dispatch.sysmsg.Suspend] from Actor[akka://Akka/user/appActor/24f65fa0-3a33-11e9-89a0-f924eec77a7a/24f74a00-3a33-11e9-89a0-f924eec77a7a/24f993f0-3a33-11e9-89a0-f924eec77a7a#-409927080] to Actor[akka://Akka/user/appActor/24f65fa0-3a33-11e9-89a0-f924eec77a7a/24f74a00-3a33-11e9-89a0-f924eec77a7a/24f993f0-3a33-11e9-89a0-f924eec77a7a#-409927080] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
2019-02-27 01:58:15,726 [Akka-akka.actor.default-dispatcher-6] INFO  akka.actor.RepointableActorRef - Message [org.thingsboard.server.service.transport.msg.TransportToDeviceActorMsgWrapper] from Actor[akka://Akka/deadLetters] to Actor[akka://Akka/user/appActor#-1878275766] was not delivered. [4] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 57.359 sec - in org.thingsboard.server.mqtt.MqttNoSqlTestSuite

Results :

Failed tests:
  AuditLogControllerSqlTest>BaseAuditLogControllerTest.testAuditLogs:91 expected:<178> but was:<175>

Tests run: 266, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard 2.3.0 .................................. SUCCESS [ 13.004 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  2.872 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.100 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  7.958 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.234 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  1.180 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.044 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  5.434 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.172 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.592 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.789 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [04:17 min]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.057 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.598 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  8.621 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.041 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [  8.288 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [  7.687 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [  7.109 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [03:12 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  3.284 s]
[INFO] ThingsBoard Server Application ..................... FAILURE [18:27 min]
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests 2.3.0 .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:10 min
[INFO] Finished at: 2019-02-27T01:58:26Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project application: There are test failures.
[ERROR]
[ERROR] Please refer to /home/user1/src/thingsboard/application/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :application
```

### Simple fix
So to fix the issue I basically downloaded an older Java version, re-create a symbolic link and rebuild it:
```
$ cd ~/build
$ wget https://github.com/frekele/oracle-java/releases/download/8u161-b12/jdk-8u161-linux-x64.tar.gz
$ tar -xvzf jdk-8u161-linux-x64.tar.gz
$ rm java
$ ln -s jdk1.8.0_161 java
```

Make sure you check the Java Version at the `mvn -version` output:
```
$ mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /home/user1/build/apache-maven
Java version: 1.8.0_161, vendor: Oracle Corporation, runtime: /home/user1/build/jdk1.8.0_161/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.el7.x86_64", arch: "amd64", family: "unix"
```

Clean-up all, and rebuild again:
```
$ cd ~/src/thingsboard
$ mvn clean install

(...)
[INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ black-box-tests ---
[INFO] Installing /home/user1/src/thingsboard/msa/black-box-tests/target/black-box-tests-2.3.0.jar to /home/user1/.m2/repository/org/thingsboard/msa/black-box-tests/2.3.0/black-box-tests-2.3.0.jar
[INFO] Installing /home/user1/src/thingsboard/msa/black-box-tests/pom.xml to /home/user1/.m2/repository/org/thingsboard/msa/black-box-tests/2.3.0/black-box-tests-2.3.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard 2.3.0 .................................. SUCCESS [ 45.716 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  6.179 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.498 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 12.290 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  4.236 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  1.722 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.155 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  6.743 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.878 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.817 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.203 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [06:12 min]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.256 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  3.140 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [ 14.763 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.348 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 18.805 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [  9.402 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [  8.669 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [01:52 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  0.866 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [18:11 min]
[INFO] ThingsBoard Microservices .......................... SUCCESS [  0.089 s]
[INFO] ThingsBoard Docker Images .......................... SUCCESS [ 42.554 s]
[INFO] ThingsBoard JavaScript Executor Microservice ....... SUCCESS [01:05 min]
[INFO] ThingsBoard Web UI Microservice .................... SUCCESS [ 35.556 s]
[INFO] ThingsBoard Node Microservice ...................... SUCCESS [  0.160 s]
[INFO] ThingsBoard Transport Microservices ................ SUCCESS [  0.018 s]
[INFO] ThingsBoard MQTT Transport Microservice ............ SUCCESS [  0.089 s]
[INFO] ThingsBoard HTTP Transport Microservice ............ SUCCESS [  0.079 s]
[INFO] ThingsBoard COAP Transport Microservice ............ SUCCESS [  0.080 s]
[INFO] ThingsBoard Black Box Tests 2.3.0 .................. SUCCESS [ 19.925 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31:22 min
[INFO] Finished at: 2019-02-27T02:41:39Z
[INFO] ------------------------------------------------------------------------
```

You should have the RPM package (.deb and .jar as well) ready at ~/src/thingsboard/application/targert:
```
$ ls application/target/
archive-tmp  conf     debian             generated-test-sources         protoc-dependencies  test-classes                thingsboard.changes  thingsboard-windows.zip
bin          control  embeddedCassandra  maven-archiver                 protoc-plugins       thingsboard-2.3.0-boot.jar  thingsboard.deb      tmp
classes      data     generated-sources  protoc-3.0.2-linux-x86_64.exe  surefire-reports     thingsboard-2.3.0.jar       thingsboard.rpm      windows
```

**Comment by alexsmartens** [comment]
Hi @ @musskopf,
I am having the same error as you do.
What repo did you install `libpng12` from?

**Comment by alexsmartens** [comment]
Removing `-XX:+UseCondCardMark` JVM flag from thingsboard.conf file as suggested in #890 solved the problem for me

**Comment by musskopf** [comment]
Hey @alexsmartens, I know it's a bit late, but the libpng12 is from the main Centos 7 repo: http://mirror.centos.org/centos/7/os/x86_64/Packages/ - I assume RHEL7 would be the same.

**Comment by sanshengshui** [comment]
Based on the above operations, the Thingsboard v2.3 on Ubuntu 18.04 has been successfully compiled and executed.  @Thank!

**Comment by immuhammadadil** [comment]
Well, it's good if everything is set up. By the way, docker is the best option to avoid all the trouble of setting it up natively.

**Comment by xujingzhou** [comment]
the thingsboard 2.4.2 has same issue on windows.  what good solution ?

error: "Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (extract-web-ui) on project web-ui: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98."

**Comment by ashvayka** [comment]
I am closing this as solved since there are multiple solutions listed above.

**Comment by pradeep-pradhan** [comment]
Please help me when i am trying to build thingsboard relese v2.5.0  
getting below error.


[INFO] --- maven-dependency-plugin:2.8:copy (copy-winsw-service) @ tb ---
[INFO] Configured Artifact: com.sun.winsw:winsw:bin:?:exe
[INFO] Copying winsw-1.9-bin.exe to D:\Mobilogix\other\mobilogix_merge_2.5.6_new\fusion\msa\tb\target\windows\service.exe
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy (copy-tb-deb) @ tb ---
[INFO] Configured Artifact: org.thingsboard:application:deb:?:deb
Downloading from jenkins: https://repo.jenkins-ci.org/releases/org/thingsboard/application/2.5.6/application-2.5.6-deb.deb
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 2.5.6:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  3.278 s]
[INFO] Netty MQTT Client .................................. SUCCESS [ 14.588 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.321 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 13.570 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  2.629 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [ 12.831 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  5.050 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  2.657 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [ 33.773 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.204 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  6.506 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  7.232 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  4.640 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  4.879 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  6.104 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.177 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  5.277 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 33.236 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [ 23.741 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.356 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [02:19 min]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [01:33 min]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [01:14 min]
[INFO] Thingsboard Server UI .............................. SUCCESS [48:55 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [ 59.236 s]
[INFO] Thingsboard Rest Client ............................ SUCCESS [ 11.328 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [03:53 min]
[INFO] ThingsBoard Microservices .......................... SUCCESS [  1.800 s]
[INFO] ThingsBoard Docker Images .......................... FAILURE [ 17.713 s]
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 h
[INFO] Finished at: 2021-02-05T14:30:41+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (copy-tb-deb) on project tb: Unable to find artifact.: Could not find artifact org.thingsboard:application:deb:deb:2.5.6 in jenkins (https://repo.jenkins-ci.org/releases)
[ERROR]
[ERROR] Try downloading the file manually from the project website.

**Comment by awsafrica** [comment]
Thank You :)
2 days with loads of errors, now followed your guide and it worked 1st time like a dream.
