### ISSUE TITLE
openAPI 2.0 description file validation

### ISSUE THREAD

**Issue by wenzul** [thingsboard/thingsboard#1522]
I treid to use the openAPI 2.0 description file `/v2/api-docs?group=thingsboard` for a Swagger client in Python.

```
from bravado.client import SwaggerClient
from bravado.requests_client import RequestsClient

http_client = RequestsClient()
client = SwaggerClient.from_url('https://demo.thingsboard.io/v2/api-docs?group=thingsboard', http_client=http_client)
```

With my example and online validators as well I get validation errors. Should it be possible to use this description file, is it broken or is my used client the wrong.

```
Traceback (most recent call last):
  File "test-swagger.py", line 13, in <module>
    http_client=http_client,
  File "bravado\client.py", line 107, in from_url
    return cls.from_spec(spec_dict, spec_url, http_client, config)
  File "bravado\client.py", line 134, in from_spec
    spec_dict, origin_url, http_client, config,
  File "bravado_core\spec.py", line 180, in from_dict
    spec.build()
  File "bravado_core\spec.py", line 192, in build
    self._validate_spec()
  File "bravado_core\spec.py", line 188, in _validate_spec
    http_handlers=build_http_handlers(self.http_client),
  File "swagger_spec_validator\validator20.py", line 170, in validate_spec
    validate_apis(apis, bound_deref)
  File "swagger_spec_validator\validator20.py", line 376, in validate_apis
    validate_unresolvable_path_params(api_name, all_path_params)
  File "swagger_spec_validator\validator20.py", line 602, in validate_unresolvable_path_params
    raise SwaggerValidationError(msg)
swagger_spec_validator.common.SwaggerValidationError: Path parameter '?searchStatus,status' used is not documented on '/api/alarm/highestSeverity/{entityType}/{entityId}{?searchStatus,status}'
```

**Comment by Karabiy** [comment]
you can refer to the ThingsBoard REST client written in Python on this link:  https://thingsboard.io/docs/reference/python-rest-client/
