### ISSUE TITLE
java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#1549]
2019-03-13 00:00:00,277 [nioEventLoopGroup-11-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110)
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2019-03-13 00:00:00,522 [http-nio-0.0.0.0-8080-Acceptor-0] ERROR o.apache.tomcat.util.net.NioEndpoint - Socket accept failed
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:456)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gopirathnamt** [comment]
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/2959796/thingsboard.log)
i enclosed the log file too

**Comment by IvanSemenenko** [comment]
Hi gopirathnamt,

You ought to configure your system environment
 https://askubuntu.com/questions/181215/too-many-open-files-how-to-find-the-culprit

Regards,

**Comment by gopirathnamt** [comment]
@IvanSemenenko  thanks i configured my environment ,i hope it will work fine

**Comment by waytai** [comment]
I have the same error, when connect is upto about 3500, then, it will report the error.

**Comment by waytai** [comment]
ubuntu18.04
ulimit -n
vim  /etc/security/limits.conf
add:
# End of file
* hard nofile 65535
* soft nofile 65535
root    soft    nofile  65535
root    hard    nofile  65535
root    soft    noproc  65535
root    hard    noproc  65535

vim /etc/system/user.conf, /etc/system/system.conf
add
DefaultLimitNOFILE=65535

**Comment by chenmingzhang** [comment]
Does anyone have more update on this?
