### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by colognebroker** [thingsboard/thingsboard#1552]
my 
devices are connected via gateway …
tenant admin-role can do everything, so far so good ....
the customer role fails with all control widgets … and their setvalue and getvalue access to devices

org.thingsboard.server.service.telemetry.exception.AccessDeniedException: You don't have permission to perform this operation!
	at org.thingsboard.server.service.security.ValidationCallback.getException(ValidationCallback.java:62)
	at org.thingsboard.server.service.security.ValidationCallback.onSuccess(ValidationCallback.java:42)
	at org.thingsboard.server.service.security.ValidationCallback.onSuccess(ValidationCallback.java:27)
	at org.thingsboard.server.service.security.AccessValidator$2.onSuccess(AccessValidator.java:334)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1135)

Reading ist no problem … the customer role can read all values from his  devices
but could not set values, also with the input widgets it is also not possible to set values ...

**Comment by Ultrazombie** [comment]
closed, as not active
