### ISSUE TITLE
Second level kafka WARN log

### ISSUE THREAD

**Issue by maddff** [thingsboard/thingsboard#1565]
When I run up the thingsboard, it will output a lot of logs as follows.
 This is also the case when I set the `kafka.enabled` option to `false`.

```
2019-03-21 14:37:42,686 [kafka-producer-network-thread | producer-tb-kafka-node-50af3350-aa8d-11e8-b7f0-576be3f73150-totoro] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-50af3350-aa8d-11e8-b7f0-576be3f73150-totoro] Connection to node -1 could not be established. Broker may not be available.
2019-03-21 14:37:42,795 [kafka-producer-network-thread | producer-tb-kafka-node-ce40bd20-aa8d-11e8-b7f0-576be3f73150-totoro] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-ce40bd20-aa8d-11e8-b7f0-576be3f73150-totoro] Connection to node -1 could not be established. Broker may not be available.
2019-03-21 14:37:43,696 [kafka-producer-network-thread | producer-tb-kafka-node-ce40bd20-aa8d-11e8-b7f0-576be3f73150-totoro] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-ce40bd20-aa8d-11e8-b7f0-576be3f73150-totoro] Connection to node -1 could not be established. Broker may not be available.
2019-03-21 14:37:43,805 [kafka-producer-network-thread | producer-tb-kafka-node-50af3350-aa8d-11e8-b7f0-576be3f73150-totoro] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-50af3350-aa8d-11e8-b7f0-576be3f73150-totoro] Connection to node -1 could not be established. Broker may not be available.
2019-03-21 14:37:44,596 [kafka-producer-network-thread | producer-tb-kafka-node-ce40bd20-aa8d-11e8-b7f0-576be3f73150-totoro] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=producer-tb-kafka-node-ce40bd20-aa8d-11e8-b7f0-576be3f73150-totoro] Connection to node -1 could not be established. Broker may not be available.
```

**Comment by maddff** [comment]
When running the thingboard, it will throw the following exception.
But I don't think they have a relationship.
```
2019-03-20 15:53:03,538 [Akka-rule-dispatcher-9] WARN  o.t.s.actors.ruleChain.RuleNodeActor - [d2119330-8bec-11e8-87c0-f11f0e1da309][50a12990-aa8d-11e8-b7f0-576be3f73150] Failed to start RULE_NODE processor.
2019-03-20 15:53:03,547 [Akka-rule-dispatcher-9] WARN  o.t.s.actors.ruleChain.RuleNodeActor - Error:
org.thingsboard.rule.engine.api.TbNodeException: java.net.ConnectException: Connection refused (Connection refused)
        at org.thingsboard.rule.engine.rabbitmq.TbRabbitMqNode.init(TbRabbitMqNode.java:72)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:127)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:57)
        at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:54)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:57)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1157)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1109)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1224)
        at org.thingsboard.rule.engine.rabbitmq.TbRabbitMqNode.init(TbRabbitMqNode.java:69)
        ... 15 common frames omitted
2019-03-20 15:53:03,550 [Akka-rule-dispatcher-9] WARN  o.t.s.actors.ruleChain.RuleNodeActor - [50a12990-aa8d-11e8-b7f0-576be3f73150][d2119330-8bec-11e8-87c0-f11f0e1da309][x1] Failed to process OnStart msg: {}
2019-03-20 15:53:03,550 [Akka-rule-dispatcher-9] WARN  o.t.s.actors.ruleChain.RuleNodeActor - Critical Error: 
org.thingsboard.rule.engine.api.TbNodeException: java.net.ConnectException: Connection refused (Connection refused)
        at org.thingsboard.rule.engine.rabbitmq.TbRabbitMqNode.init(TbRabbitMqNode.java:72)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:127)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:57)
        at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:54)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:57)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1157)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1109)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1224)
        at org.thingsboard.rule.engine.rabbitmq.TbRabbitMqNode.init(TbRabbitMqNode.java:69)

```

**Comment by mes20a42** [comment]
Hey may I check was this resolved?
