### ISSUE TITLE
Scheduler saves, does not work, generates exception

### ISSUE THREAD

**Issue by mcpicoli** [thingsboard/thingsboard#1608]
The scenario is the following:

- Latest PE version as of 2019-03-13 (date of last update)
- One device with a RPC method called "clear_data", which takes no parameters (or any parameters)
- One scheduler item to call this RPC method at a given time of the day (say 00:00, for example) and repeat it daily until ten years later (see issue #1049). Scheduler uses "single device" as setting.

When scheduler item is saved, the following exception is logged into thingsboard.log:

`
2019-04-04 14:00:26,954 [pool-24-thread-1] ERROR o.t.s.s.s.DefaultSchedulerService - Failed to read scheduler config
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "repeatInterval" (class org.thingsboard.server.service.scheduler.DailyRepeat), not marked as ignorable (one known property: "endsOn"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.thingsboard.server.service.scheduler.DailyRepeat["repeatInterval"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1489)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1467)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
        at org.thingsboard.server.service.scheduler.DefaultSchedulerService.getSchedulerEventMetaData(DefaultSchedulerService.java:219)
        at org.thingsboard.server.service.scheduler.DefaultSchedulerService.scheduleAndAddToMap(DefaultSchedulerService.java:332)
        at org.thingsboard.server.service.scheduler.DefaultSchedulerService.onSchedulerEventUpdatedSync(DefaultSchedulerService.java:312)
        at org.thingsboard.server.service.scheduler.DefaultSchedulerService.lambda$onSchedulerEventUpdated$1(DefaultSchedulerService.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

And at the selected time, nothing happens.
Changing the repeat interval to "weekly" (and selecting every week day) results in the same.
Deleting the item and recreating it solves the issue (at least for the items I tried).

_However it is not reasonable to ask my customers to delete EVERY scheduler item they've created and recreate them, in the hope it will fix this issue._

Thanks

**Comment by ashaforost** [comment]
the issue can't be reproduced on the latest v3.3.3.
