### ISSUE TITLE
could not start up via cmd java -jar thingsboard-2.3.1-SNAPSHOT-boot.jar 

### ISSUE THREAD

**Issue by gavingu81** [thingsboard/thingsboard#1617]
when I run java -jar thingsboard-2.3.1-SNAPSHOT-boot.jar 
**I got the failure on output:** , it seems it could not load the template/ resources (*.vm)
2019-04-09 20:25:41,013 [main] ERROR o.a.v.runtime.log.Log4JLogChute - Problem instantiating the template loader: org.thingsboard.server.config.ThingsboardMessageConfiguration$SpringResourceLoader.
Look at your properties file and make sure the
name of the template loader is correct.
java.lang.IllegalAccessException: Class org.apache.velocity.util.ClassUtils can not access a member of class org.thingsboard.server.config.ThingsboardMessageConfiguration$SpringResourceLoader with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at org.apache.velocity.util.ClassUtils.getNewInstance(ClassUtils.java:105)
	at org.apache.velocity.runtime.resource.loader.ResourceLoaderFactory.getLoader(ResourceLoaderFactory.java:46)
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.initialize(ResourceManagerImpl.java:130)
	at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:730)
	at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:263)
	at org.apache.velocity.app.VelocityEngine.init(VelocityEngine.java:93)
	at org.thingsboard.server.config.ThingsboardMessageConfiguration.velocityEngine(ThingsboardMessageConfiguration.java:69)
	at org.thingsboard.server.config.ThingsboardMessageConfiguration$$EnhancerBySpringCGLIB$$607061f7.CGLIB$velocityEngine$1(<generated>)

**Comment by Hanane95** [comment]
Coulde you please give me  the answer if is not  still give you in error thank you

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
