### ISSUE TITLE
408 when send twoway RPC call

### ISSUE THREAD

**Issue by vicuzz** [thingsboard/thingsboard#1621]
Hello,
after 10 seconds all twoway RPC Request are timeout with this error:

java.lang.RuntimeException: TIMEOUT at org.thingsboard.rule.engine.rpc.TbSendRPCRequestNode.lambda$onMsg$0(TbSendRPCRequestNode.java:124)	at org.thingsboard.server.actors.ruleChain.DefaultTbContext$1.lambda$sendRpcRequest$0(DefaultTbContext.java:287)	at org.thingsboard.server.service.rpc.DefaultDeviceRpcService.lambda$scheduleTimeout$0(DefaultDeviceRpcService.java:215)	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)	at java.lang.Thread.run(Thread.java:748)

where i can raise the timeout?????
Tried in rule editor "Timeout in seconds" but without success

**Comment by faithware** [comment]
I have the same issue, sending rpc requests from the dashboard using control button works perfectly.
When using REST API most of the time it doesn't work.
java.lang.RuntimeException: TIMEOUT
	at org.thingsboard.rule.engine.rpc.TbSendRPCRequestNode.lambda$onMsg$0(TbSendRPCRequestNode.java:124)
	at org.thingsboard.server.actors.ruleChain.DefaultTbContext$1.lambda$sendRpcRequest$0(DefaultTbContext.java:287)
	at org.thingsboard.server.service.rpc.DefaultDeviceRpcService.lambda$scheduleTimeout$0(DefaultDeviceRpcService.java:215)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create the new ticket if this problem still exists.
