### ISSUE TITLE
centos7 Installation failed java 1.8-201 PostgreSQL9.8

### ISSUE THREAD

**Issue by he77pc** [thingsboard/thingsboard#1632]
2019-04-15 09:32:30,349 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:206)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154)
	... 14 common frames omitted
2019-04-15 09:32:30,350 [main] ERROR o.t.s.ThingsboardInstallApplication - Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.

2019-04-15 09:52:08,294 [main] ERROR o.s.boot.SpringApplication - Application run failed
2019-04-15 09:52:08,298 [main] ERROR o.t.s.ThingsboardInstallApplication - Failed to load property source from location 'classpath:/thingsboard.yml'
2019-04-15 09:52:35,968 [main] ERROR o.s.boot.SpringApplication - Application run failed
2019-04-15 09:57:59,673 [main] ERROR o.s.boot.SpringApplication - Application run failed
2019-04-15 09:57:59,677 [main] ERROR o.t.s.ThingsboardInstallApplication - Failed to load property source frothingsboard.ymlm location 'classpath:/thingsboard.yml'

**Comment by ban2derlog** [comment]
Hi, do you try on latest TihngsBoard release and PostgreSQL 12?
