### ISSUE TITLE
Error: Failed to initialize cassandra cluster

### ISSUE THREAD

**Issue by alexsmartens** [thingsboard/thingsboard#1643]
On one of my computers I am having a " Failed to initialize cassandra cluster" error right after successfully compiling thingsboard. Could someone please help with this issue?

Here's my log:
```
$ java -jar application/target/thingsboard-2.3.0-boot.jar 
 ===================================================
 :: ThingsBoard ::       (v2.3.0)
 ===================================================

2019-04-16 13:34:57,769 [main] INFO  o.t.s.ThingsboardServerApplication - Starting ThingsboardServerApplication v2.3.0 on my-PC with PID 20427 (/_myPath_s/thingsboard/application/target/thingsboard-2.3.0-boot.jar started by me in /_myPath_s/thingsboard)
2019-04-16 13:34:57,772 [main] INFO  o.t.s.ThingsboardServerApplication - No active profile set, falling back to default profiles: default
2019-04-16 13:34:57,836 [main] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@641147d0: startup date [Tue Apr 16 13:34:57 EDT 2019]; root of context hierarchy
2019-04-16 13:34:57,947 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.4.Final
2019-04-16 13:35:00,544 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2019-04-16 13:35:00,808 [main] INFO  o.s.d.r.c.RepositoryConfigurationExtensionSupport - Spring Data Redis - Could not safely identify store assignment for repository candidate interface org.thingsboard.server.dao.sql.settings.AdminSettingsRepository.
2019-04-16 13:35:00,811 [main] INFO  o.s.d.r.c.RepositoryConfigurationExtensionSupport - Spring Data Redis - Could not safely identify store assignment for repository candidate interface org.thingsboard.server.dao.sql.audit.AuditLogRepository.
2019-04-16 13:35:01,340 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cache.annotation.ProxyCachingConfiguration' of type [class org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$5fa9ce14] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-04-16 13:35:01,415 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [class org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$af456030] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-04-16 13:35:01,430 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'objectPostProcessor' of type [class org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-04-16 13:35:01,432 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@77825085' of type [class org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-04-16 13:35:01,439 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [class org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$d41a02e2] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-04-16 13:35:01,455 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'methodSecurityMetadataSource' of type [class org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-04-16 13:35:02,035 [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat initialized with port(s): 8080 (http)
2019-04-16 13:35:02,047 [main] INFO  o.a.catalina.core.StandardService - Starting service Tomcat
2019-04-16 13:35:02,048 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.6
2019-04-16 13:35:02,136 [localhost-startStop-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2019-04-16 13:35:02,136 [localhost-startStop-1] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 4302 ms
2019-04-16 13:35:02,953 [localhost-startStop-1] INFO  com.datastax.driver.core - DataStax Java driver 3.5.0 for Apache Cassandra
2019-04-16 13:35:02,957 [localhost-startStop-1] INFO  c.d.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
2019-04-16 13:35:03,154 [localhost-startStop-1] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2019-04-16 13:35:03,264 [localhost-startStop-1] INFO  com.datastax.driver.core.NettyUtil - Found Netty's native epoll transport in the classpath, using it
2019-04-16 13:35:03,614 [localhost-startStop-1] INFO  c.d.d.c.p.DCAwareRoundRobinPolicy - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
2019-04-16 13:35:03,615 [localhost-startStop-1] INFO  com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
2019-04-16 13:35:03,651 [localhost-startStop-1] WARN  o.t.s.d.c.AbstractCassandraCluster - Failed to initialize cassandra cluster due to Keyspace 'thingsboard' does not exist. Will retry in 3000 ms
```

**Comment by alexsmartens** [comment]
I figured that my problem is coming up because I did not create database schema and populated demo data. 
So, I ran the following script form the [contribution guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/#optional-nosql-database-cassandra):
```
cd ${TB_WORK_DIR}/application/target/bin/install
chmod +x install_dev_db.sh
./install_dev_db.sh
```
And here is my new ERROR log:
```
$:~/_myPath_/thingsboard/application/target/bin/install$ ./install_dev_db.sh
Logging system failed to initialize using configuration from 'logback.xml'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Failed to create parent directories for [/var/log/thingsboard/install.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - openFile(/var/log/thingsboard/install.log,true) call failed. java.io.FileNotFoundException: /var/log/thingsboard/install.log (No such file or directory)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:161)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:47)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:114)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:304)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:272)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:235)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:208)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Failed to create parent directories for [/var/log/thingsboard/install.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - openFile(/var/log/thingsboard/install.log,true) call failed. java.io.FileNotFoundException: /var/log/thingsboard/install.log (No such file or directory)
ThingsBoard DB installation failed!
```
Any help will be appreciated

**Comment by alexsmartens** [comment]
Thanks to @Sioxas's comment https://github.com/thingsboard/thingsboard/issues/954#issuecomment-414651498 the problem is solved
