### ISSUE TITLE
Thingsboard 2.3.1 build from source failure

### ISSUE THREAD

**Issue by alexsmartens** [thingsboard/thingsboard#1689]
Hi,
for some reason I cannot build the new 2.3.1 TB release. Could someone please help to figure out what the problem is?

### Log  

```
Tests run: 266, Failures: 0, Errors: 266, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Thingsboard ........................................ SUCCESS [  7.439 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  1.277 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.043 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  2.880 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  0.681 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  0.327 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.019 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.999 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  0.384 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.189 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.245 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [02:02 min]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.027 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.372 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  3.594 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.042 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [  5.561 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [  4.792 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [  4.086 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [ 36.376 s]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  0.184 s]
[INFO] ThingsBoard Server Application ..................... FAILURE [14:54 min]
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:07 min
[INFO] Finished at: 2019-05-07T11:33:00-04:00
[INFO] Final Memory: 121M/1526M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project application: There are test failures.
[ERROR] 
[ERROR] Please refer to /_MY_PATH_/thingsboard-2.3.1/application/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project application: There are test failures.

Please refer to /_MY_PATH_/thingsboard-2.3.1/application/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /_MY_PATH_/thingsboard-2.3.1/application/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:320)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:892)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :application

```

**Comment by alexsmartens** [comment]
Problem solved,
I had thingsboard service running while trying to build it. 

I did not pay attention at first, but while building thingsboard the following problem was repeating all over again
```
...
	... 54 common frames omitted
 ===================================================
 ::  ::      
 ===================================================

2019-05-07 15:15:19,182 [Akka-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2019-05-07 15:15:19,187 [main] ERROR o.t.s.s.c.rpc.ClusterGrpcService - Failed to start RPC server!
java.io.IOException: Failed to bind
...

```

Running trivial `sudo service thingsboard stop` before the installation did the thing
