### ISSUE TITLE
MQTT Connection Aborted

### ISSUE THREAD

**Issue by Dionisseus** [thingsboard/thingsboard#1697]
Hi everyone.
I have a thingsboard community edition installation on a home server and Im using it to connect with one esp8266 device on another place with MQTT. Very often the connection get dropped.
This is the INFO log error: 

`2019-05-08 15:05:04,341 [ForkJoinPool-8-worker-7] INFO  o.t.s.t.mqtt.MqttTransportHandler - [d1c6525a-578e-4e14-b209-3d3168f478fa] Client connected!
2019-05-08 15:05:09,576 [nioEventLoopGroup-6-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [26e71b0a-1681-43df-b884-83fb646110ef] Processing connect msg for client: 084fe740-5c89-11e9-8441-4b74eb07b009!
2019-05-08 15:05:09,576 [nioEventLoopGroup-6-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [26e71b0a-1681-43df-b884-83fb646110ef] Processing connect msg for client with user name: Gw45Nqig8UIrF96gZuu8!
2019-05-08 15:05:09,576 [ForkJoinPool-8-worker-0] INFO  o.t.s.t.mqtt.MqttTransportHandler - [26e71b0a-1681-43df-b884-83fb646110ef] Client connected!
2019-05-08 15:06:19,123 [nioEventLoopGroup-6-7] INFO  o.t.s.t.mqtt.MqttTransportHandler - [e638afb4-06cc-4c4a-92c0-c11f4d7b3897] Processing connect msg for client: 084fe740-5c89-11e9-8441-4b74eb07b009!
2019-05-08 15:06:19,123 [nioEventLoopGroup-6-7] INFO  o.t.s.t.mqtt.MqttTransportHandler - [e638afb4-06cc-4c4a-92c0-c11f4d7b3897] Processing connect msg for client with user name: Gw45Nqig8UIrF96gZuu8!
2019-05-08 15:06:19,138 [ForkJoinPool-8-worker-7] INFO  o.t.s.t.mqtt.MqttTransportHandler - [e638afb4-06cc-4c4a-92c0-c11f4d7b3897] Client connected!
2019-05-08 15:06:19,185 [nioEventLoopGroup-6-7] ERROR o.t.s.t.mqtt.MqttTransportHandler - [e638afb4-06cc-4c4a-92c0-c11f4d7b3897] Unexpected Exception
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
2019-05-08 15:06:45,716 [nioEventLoopGroup-6-8] INFO  o.t.s.t.mqtt.MqttTransportHandler - [ccb1e175-2ca7-4a01-ae76-15744162bf2a] Processing connect msg for client: 084fe740-5c89-11e9-8441-4b74eb07b009!
2019-05-08 15:06:45,716 [nioEventLoopGroup-6-8] INFO  o.t.s.t.mqtt.MqttTransportHandler - [ccb1e175-2ca7-4a01-ae76-15744162bf2a] Processing connect msg for client with user name: Gw45Nqig8UIrF96gZuu8!
2019-05-08 15:06:45,748 [ForkJoinPool-8-worker-7] INFO  o.t.s.t.mqtt.MqttTransportHandler - [ccb1e175-2ca7-4a01-ae76-15744162bf2a] Client connected!
2019-05-08 15:09:25,123 [nioEventLoopGroup-6-3] INFO  o.t.s.t.mqtt.MqttTransportHandler - [e7f3deba-3eb7-4766-9237-6fabaf729307] Processing connect msg for client: 084fe740-5c89-11e9-8441-4b74eb07b009!`

Im thinking this may be related to my configuration in thingsboard.yml 👍 

[thingsboard.yml.txt](https://github.com/thingsboard/thingsboard/files/3159169/thingsboard.yml.txt)

Any assistance would be greatly appreciated.

**Comment by zachjacobs** [comment]
@Dionisseus did you figure this out?  I am having the same exact issue when trying to run the https://thingsboard.io/docs/samples/esp32/ota/ example.

**Comment by Nathan-ma** [comment]
Same problem here!
Any updates on this?

**Comment by ban2derlog** [comment]
Hi, does it persist on latest ThingsBoard version?
