### ISSUE TITLE
mvn clean install 

### ISSUE THREAD

**Issue by e-infotech** [thingsboard/thingsboard#1761]
Hi, I installed maven and after "git checkout release-2.3" command, I couldn't go further and build the project using "mvn clean install". Here is the error I got: (PS: My OS is CentOS7.4.)
`[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 3.10
[INFO] os.detected.version.major: 3
[INFO] os.detected.version.minor: 10
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 7
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-x86_64
[WARNING] Failed to inject repository session properties.
java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/eclipse/aether/RepositorySystemSession;
        at kr.motd.maven.os.RepositorySessionInjector.injectRepositorySession(RepositorySessionInjector.java:22)
        at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:151)
        at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:110)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Thingsboard
[INFO] Netty MQTT Client
[INFO] Thingsboard Server Commons
[INFO] Thingsboard Server Common Data
[INFO] Thingsboard Server Common Messages
[INFO] Thingsboard Server Queue components
[INFO] Thingsboard Server Commons
[INFO] Thingsboard Server Common Transport components
[INFO] Thingsboard MQTT Transport Common
[INFO] Thingsboard HTTP Transport Common
[INFO] Thingsboard CoAP Transport Common
[INFO] Thingsboard Server DAO Layer
[INFO] Thingsboard Extensions
[INFO] Thingsboard Rule Engine API
[INFO] Thingsboard Rule Engine Components
[INFO] Thingsboard Server Transport Modules
[INFO] Thingsboard HTTP Transport Service
[INFO] Thingsboard MQTT Transport Service
[INFO] Thingsboard CoAP Transport Service
[INFO] Thingsboard Server UI
[INFO] Thingsboard Server Tools
[INFO] ThingsBoard Server Application
[INFO] ThingsBoard Microservices
[INFO] ThingsBoard Docker Images
[INFO] ThingsBoard JavaScript Executor Microservice
[INFO] ThingsBoard Web UI Microservice
[INFO] ThingsBoard Node Microservice
[INFO] ThingsBoard Transport Microservices
[INFO] ThingsBoard MQTT Transport Microservice
[INFO] ThingsBoard HTTP Transport Microservice
[INFO] ThingsBoard COAP Transport Microservice
[INFO] ThingsBoard Black Box Tests
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Thingsboard 2.3.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ thingsboard ---
[INFO]
[INFO] --- license-maven-plugin:3.0:check (default) @ thingsboard ---
[INFO] Checking licenses...
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/kafka.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-coap-transport.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-http-transport.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-js-executor.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-mqtt-transport.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-node.cassandra.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-node.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-node.postgres.env
[WARNING] Unknown file extension: /home/centos/thingsboard/docker/tb-web-ui.env
[WARNING] Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions.
[INFO]
[INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ thingsboard ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Installing /home/centos/thingsboard/pom.xml to /home/centos/.m2/repository/org/thingsboard/thingsboard/2.3.1/thingsboard-2.3.1.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Netty MQTT Client 2.3.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ netty-mqtt ---
[INFO] Deleting /home/centos/thingsboard/netty-mqtt/target
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ netty-mqtt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/centos/thingsboard/netty-mqtt/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ netty-mqtt ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to /home/centos/thingsboard/netty-mqtt/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ netty-mqtt ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/centos/thingsboard/netty-mqtt/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ netty-mqtt ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M1:test (default-test) @ netty-mqtt ---
Jun 03, 2019 3:39:31 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: org.apache.maven.plugin.surefire.SurefirePlugin
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.codehaus.plexus.languages.java.jpms.LocationManager was bound.
  while locating org.apache.maven.plugin.surefire.SurefirePlugin

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1006)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1032)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ....................................... SUCCESS [1.415s]
[INFO] Netty MQTT Client ................................. FAILURE [2.465s]
[INFO] Thingsboard Server Commons ........................ SKIPPED
[INFO] Thingsboard Server Common Data .................... SKIPPED
[INFO] Thingsboard Server Common Messages ................ SKIPPED
[INFO] Thingsboard Server Queue components ............... SKIPPED
[INFO] Thingsboard Server Commons ........................ SKIPPED
[INFO] Thingsboard Server Common Transport components .... SKIPPED
[INFO] Thingsboard MQTT Transport Common ................. SKIPPED
[INFO] Thingsboard HTTP Transport Common ................. SKIPPED
[INFO] Thingsboard CoAP Transport Common ................. SKIPPED
[INFO] Thingsboard Server DAO Layer ...................... SKIPPED
[INFO] Thingsboard Extensions ............................ SKIPPED
[INFO] Thingsboard Rule Engine API ....................... SKIPPED
[INFO] Thingsboard Rule Engine Components ................ SKIPPED
[INFO] Thingsboard Server Transport Modules .............. SKIPPED
[INFO] Thingsboard HTTP Transport Service ................ SKIPPED
[INFO] Thingsboard MQTT Transport Service ................ SKIPPED
[INFO] Thingsboard CoAP Transport Service ................ SKIPPED
[INFO] Thingsboard Server UI ............................. SKIPPED
[INFO] Thingsboard Server Tools .......................... SKIPPED
[INFO] ThingsBoard Server Application .................... SKIPPED
[INFO] ThingsBoard Microservices ......................... SKIPPED
[INFO] ThingsBoard Docker Images ......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ...... SKIPPED
[INFO] ThingsBoard Web UI Microservice ................... SKIPPED
[INFO] ThingsBoard Node Microservice ..................... SKIPPED
[INFO] ThingsBoard Transport Microservices ............... SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ........... SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ........... SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ........... SKIPPED
[INFO] ThingsBoard Black Box Tests ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.703s
[INFO] Finished at: Mon Jun 03 15:39:31 UTC 2019
[INFO] Final Memory: 29M/488M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project netty-mqtt: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test failed: Unable to load the mojo 'test' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1': com.google.inject.ProvisionException: Guice provision errors:
[ERROR]
[ERROR] 1) No implementation for org.codehaus.plexus.languages.java.jpms.LocationManager was bound.
[ERROR] while locating org.apache.maven.plugin.surefire.SurefirePlugin
[ERROR] at ClassRealm[plugin>org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test)
[ERROR]
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-mqtt
`

**Comment by mkuhappy** [comment]
Hi @e-infotech, did you manage to solve this problem? I'm having the similar one.

**Comment by e-infotech** [comment]
Hi, not completely. I installed another version of Maven and it was built successfully, but for the next step, I encounter the same problem again.

**Comment by mkuhappy** [comment]
Hi, yeah, installing the latest maven worked for me (I used the approach described here: https://linuxize.com/post/how-to-install-apache-maven-on-centos-7). Although I still cannot build it successfully, but this particular issue is resolved fro me and it's able to proceed to the "Thingsboard Server UI" step. Btw, I'm using sudo mvn ...

**Comment by e-infotech** [comment]
So if you have a problem building it, what was the advantage of installing the latest maven? Because in my case after installing the latest version, it was built successfully. 
Yeah, I used sudo for all of the commands as well.

**Comment by mkuhappy** [comment]
WIth 3.0.5 version of Maven it failed on "Netty MQTT Client" step already.

**Comment by e-infotech** [comment]
Maven version should be at least 3.1.0 
I think I updated my maven using this link "https://computingforgeeks.com/installing-latest-apache-maven-on-centos-fedora/"
