### ISSUE TITLE
Shared attributes subscription not updated to subscribed devices

### ISSUE THREAD

**Issue by miguelrubima** [thingsboard/thingsboard#1764]
When updating a shared attribute, message is not received by the subscribed device and I can found the following exception in thingsboard.log:

2019-06-04 18:12:48,522 [ForkJoinPool-9-worker-11] WARN  o.t.s.t.http.DeviceApiController - Failed to process request
java.lang.NullPointerException: null
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:209)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:175)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:169)
	at org.springframework.security.web.servletapi.HttpServlet3RequestFactory$SecurityContextAsyncContext.dispatch(HttpServlet3RequestFactory.java:291)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:131)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:387)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:453)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
	at org.springframework.web.context.request.async.DeferredResult.setResult(DeferredResult.java:238)
	at org.thingsboard.server.transport.http.DeviceApiController$HttpOkCallback.onSuccess(DeviceApiController.java:252)
	at org.thingsboard.server.transport.http.DeviceApiController$HttpOkCallback.onSuccess(DeviceApiController.java:243)
	at org.thingsboard.server.service.transport.LocalTransportService.forwardToDeviceActor(LocalTransportService.java:175)
	at org.thingsboard.server.service.transport.LocalTransportService.doProcess(LocalTransportService.java:120)
	at org.thingsboard.server.common.transport.service.AbstractTransportService.process(AbstractTransportService.java:84)
	at org.thingsboard.server.transport.http.DeviceApiController.lambda$postDeviceAttributes$1(DeviceApiController.java:103)
	at org.thingsboard.server.transport.http.DeviceApiController$DeviceAuthCallback.onSuccess(DeviceApiController.java:211)
	at org.thingsboard.server.transport.http.DeviceApiController$DeviceAuthCallback.onSuccess(DeviceApiController.java:186)
	at org.thingsboard.server.service.transport.LocalTransportService.lambda$process$0(LocalTransportService.java:78)
	at org.thingsboard.rule.engine.api.util.DonAsynchron$1.onSuccess(DonAsynchron.java:39)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1135)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Command used:
curl -v -X POST -d @testAttributes.json http://$HOST:8080/api/v1/$DEVTOKEN/attributes --header "Content-Type:application/json" where:

$ cat testAttributes.json 
{"FWVersion":"FW003"}

Any help is appreciated.

**Comment by strautins** [comment]
Same here, Thingsboard v.2.4.2
```
2019-12-17 08:53:17,010 [pool-10-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - Calculating state updates for 17 devices
2019-12-17 08:53:21,701 [ForkJoinPool-10-worker-13] WARN  o.t.s.t.http.DeviceApiController - Failed to process request
java.lang.NullPointerException: null
        at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:209)
        at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:175)
        at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:169)
        at org.springframework.security.web.servletapi.HttpServlet3RequestFactory$SecurityContextAsyncContext.dispatch(HttpServlet3RequestFactory.java:291)
        at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:131)
        at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:387)
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:453)
        at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
        at org.springframework.web.context.request.async.DeferredResult.setResult(DeferredResult.java:238)
        at org.thingsboard.server.transport.http.DeviceApiController$HttpOkCallback.onSuccess(DeviceApiController.java:266)
        at org.thingsboard.server.transport.http.DeviceApiController$HttpOkCallback.onSuccess(DeviceApiController.java:257)
        at org.thingsboard.server.service.transport.LocalTransportService.forwardToDeviceActor(LocalTransportService.java:215)
        at org.thingsboard.server.service.transport.LocalTransportService.doProcess(LocalTransportService.java:138)
        at org.thingsboard.server.common.transport.service.AbstractTransportService.process(AbstractTransportService.java:77)
        at org.thingsboard.server.transport.http.DeviceApiController.lambda$postTelemetry$2(DeviceApiController.java:116)
        at org.thingsboard.server.transport.http.DeviceApiController$DeviceAuthCallback.onSuccess(DeviceApiController.java:225)
        at org.thingsboard.server.transport.http.DeviceApiController$DeviceAuthCallback.onSuccess(DeviceApiController.java:200)
        at org.thingsboard.server.service.transport.LocalTransportService.lambda$process$0(LocalTransportService.java:101)
        at org.thingsboard.common.util.DonAsynchron$1.onSuccess(DonAsynchron.java:38)
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1135)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2019-12-17 08:53:27,010 [pool-10-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - Calculating state updates for 17 devices
2019-12-17 08:53:27,637 [pool-3-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] queueSize [0] totalAdded [2] totalSaved [2] totalFailed [0]
```

**Comment by strautins** [comment]
Looks like https://bz.apache.org/bugzilla/show_bug.cgi?id=63246
So if I am not wrong...
Whats causes error is in spring framework. Thingsboard got 
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
<spring-boot.version>2.1.3.RELEASE</spring-boot.version> Feb, 2019 from https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web
this issue is
Status: | RESOLVED FIXED at 2019-03-08 22:08:30 UTC

So it could not be possibly included in that Spring version.

Solution would be upgrade spring-boot-starter-web version to x?.

newest 2.2.2.RELEASE | Central | 85 | Dec, 2019

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
