### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.readRetainedSlice(I)Lio/netty/buffer/ByteBuf;

### ISSUE THREAD

**Issue by wjx1018960145** [thingsboard/thingsboard#1770]
Report this error when I publish  why?
java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.readRetainedSlice(I)Lio/netty/buffer/ByteBuf;
	at io.netty.handler.codec.mqtt.MqttDecoder.decodePublishPayload(MqttDecoder.java:421) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.mqtt.MqttDecoder.decodePayload(MqttDecoder.java:325) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.mqtt.MqttDecoder.decode(MqttDecoder.java:100) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:491) ~[netty-codec-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367) ~[netty-codec-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-codec-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) [netty-transport-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-common-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.0.56.Final.jar:4.0.56.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

**Comment by Ultrazombie** [comment]
Closed, as not active
