### ISSUE TITLE
TypeError: on_connect() takes exactly 3 arguments (4 given)

### ISSUE THREAD

**Issue by frappierer** [thingsboard/thingsboard#179]
Hi there,

first of all thanks for that amazing piece of software! But i have a little problem and i would love to continue.

I was following the tutorial here.
https://thingsboard.io/docs/samples/raspberry/gpio/

* thingsboard is installed on a Raspberry. Host: localhost:8080
* i am trying to do the GPIO control on that same device.

In the gpio.py i added:
```
THINGSBOARD_HOST = 'localhost'
ACCESS_TOKEN = 'RASPBERRY_PI_DEMO_TOKEN'
```
and i get the following error:

```
gpio.py:54: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(pin, GPIO.OUT)
Traceback (most recent call last):
  File "gpio.py", line 67, in <module>
    client.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1838, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2291, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2349, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes exactly 3 arguments (4 given)
```
I tried working with 127.0.0.1 and the network ip, but that gave the same error.

I was thinking this might be related to the missing port.  So i tried:
```
THINGSBOARD_HOST = 'localhost:8080'
ACCESS_TOKEN = 'RASPBERRY_PI_DEMO_TOKEN'
```
But it gives me the following error:

```
gpio.py:54: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(pin, GPIO.OUT)
Traceback (most recent call last):
  File "gpio.py", line 64, in <module>
    client.connect(THINGSBOARD_HOST, 1883, 60)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 887, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

```

Can anyone help?

**Comment by jtfrow** [comment]
I am getting the same error message. Has anyone come up with a solution?

**Comment by iBrick** [comment]
I've added 2 lines before 'client.on_connect = on_connect' and it helped:
`# Register connect callback`
`def on_connect(self, mosq, obj, rc):`
`    self.subscribe('v1/devices/me/rpc/request/+', 0)`

`client.on_connect = on_connect`

**Comment by ikulikov** [comment]
Closing due to an inactivity.
