### ISSUE TITLE
Upgrade 2.3.1->2.4.0 failed!

### ISSUE THREAD

**Issue by pineful** [thingsboard/thingsboard#1863]
I upgraded our thingsboard v2.3.1 to v2.4.0, but it cannot be started!
Why it has problem on "latestTsKeyNames" ??

It has weird errors on logs below : 

2019-07-15 18:17:23,313 [Akka-rule-dispatcher-13] WARN  o.t.s.actors.ruleChain.RuleNodeActor - [4fb6b470-779f-11e9-8237-1d0983dd386f][4b7288f0-a47f-11e9-bf71-431d49d91c08] **Failed to start RULE_NODE processor.**
2019-07-15 18:17:23,317 [Akka-rule-dispatcher-13] WARN  o.t.s.actors.ruleChain.RuleNodeActor - Error:
**org.thingsboard.rule.engine.api.TbNodeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.thingsboard.rule.engine.metadata.TbGetTelemetryNodeConfiguration["latestTsKeyNames"])**
        at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:40)
        at org.thingsboard.rule.engine.metadata.TbGetTelemetryNode.init(TbGetTelemetryNode.java:82)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:127)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:57)
        at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:54)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.thingsboard.rule.engine.metadata.TbGetTelemetryNodeConfiguration["latestTsKeyNames"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:266)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:179)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:169)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:21)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2758)
        at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:38)
        ... 16 common frames omitted
2019-07-15 18:17:23,317 [Akka-rule-dispatcher-13] WARN  o.t.s.actors.ruleChain.RuleNodeActor - [4b7288f0-a47f-11e9-bf71-431d49d91c08][4fb6b470-779f-11e9-8237-1d0983dd386f][Latest 5 seconds] Failed to process OnStart msg: {}
2019-07-15 18:17:23,317 [Akka-rule-dispatcher-13] WARN  o.t.s.actors.ruleChain.RuleNodeActor - Critical Error:
org.thingsboard.rule.engine.api.TbNodeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.thingsboard.rule.engine.metadata.TbGetTelemetryNodeConfiguration["latestTsKeyNames"])
        at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:40)
        at org.thingsboard.rule.engine.metadata.TbGetTelemetryNode.init(TbGetTelemetryNode.java:82)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:127)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:57)
        at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:54)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.thingsboard.rule.engine.metadata.TbGetTelemetryNodeConfiguration["latestTsKeyNames"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:266)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:179)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:169)
        at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:21)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2758)
        at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:38)
        ... 16 common frames omitted

**Comment by pineful** [comment]
I found that it can be started after removing rule node of org.thingsboard.rule.engine.metadata.TbGetTelemetryNode.
