### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by madper** [thingsboard/thingsboard#1869]
Hey dear thingsboard team!

Recently I met the following issue every second (thingsboard 2.4):

> 2019-07-19 13:51:51,700 [nioEventLoopGroup-4-7] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by org.thingsboard.server.transport.mqtt.MqttTransportHandler.operationComplete()
> java.lang.NullPointerException: null

![Screenshot from 2019-07-19 13-53-41](https://user-images.githubusercontent.com/451815/61512468-a2e96b00-aa2c-11e9-85e8-1425cec35d47.png)
Is there something wrong with my client mqtt code?

BR.

**Comment by madper** [comment]
Does https://github.com/thingsboard/thingsboard/commit/4e71935d27ca12d6ffc630d2175e166d9bcbc4ad fix it?

**Comment by pineful** [comment]
I am also experiencing similar phenomenon and the device is disconnected abruptly at every 10 minutes.

2019-07-19 16:10:47,128 [nioEventLoopGroup-4-7] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by org.thingsboard.server.transport.mqtt.MqttTransportHandler.operationComplete()
java.lang.NullPointerException: null
        at org.thingsboard.server.common.transport.service.AbstractTransportService.deregisterSession(AbstractTransportService.java:203)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.operationComplete(MqttTransportHandler.java:484)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1183)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:769)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:745)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:616)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1350)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:611)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:595)
        at io.netty.handler.ssl.SslHandler$7.operationComplete(SslHandler.java:2066)
        at io.netty.handler.ssl.SslHandler$7.operationComplete(SslHandler.java:2055)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:152)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
        at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:2055)
        at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1843)
        at io.netty.handler.ssl.SslHandler.close(SslHandler.java:742)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:611)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:595)
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:611)
        at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:600)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by developersnively** [comment]
We have exactly the same problem since yesterday, when we updated to v.2.4. Connections are broken every 10 minutes. Anything that can be done (setting something in the configuration, etc.)? Any support would be much appreciated.

**Comment by madper** [comment]
I also met the disconnect every 10 minutes issue. Does it relate to the NPE? I plan to fill another GitHub issue for that.

**Comment by madper** [comment]
@pineful @developersnively And guys, did you met the oom issue as I filled on https://github.com/thingsboard/thingsboard/issues/1787 .

**Comment by developersnively** [comment]
@madper Not yet, but it has been running for less than 24 hrs since the update. I will keep posted if something new emerges. But I confirm that our devices (200 approx sending telemetry every 20 secs) are being disconnected every 10 mins, which is annoying.

**Comment by madper** [comment]
@developersnively Yeah, And enabling so_keepalive makes things worse. (more error logs.)

**Comment by pineful** [comment]
@madper No, I have not experienced this issue yet. But the 10 minutes disconnection issue is very critical for us. I need to rollback our configuration if it can't be fixed soon.

**Comment by madper** [comment]
@pineful @developersnively Hey! Big good news! I built the lastest master yesterday. And I can confirm that the issue has been fixed. Both the null pointer and 10 minutes reconnect.
The only issue is that I have to use 2.4.1-snapshot. And the official release seems to not have been well tested...

**Comment by pineful** [comment]
> @pineful @developersnively Hey! Big good news! I built the lastest master yesterday. And I can confirm that the issue has been fixed. Both the null pointer and 10 minutes reconnect.
> The only issue is that I have to use 2.4.1-snapshot. And the official release seems to not have been well tested...

I appreciate! But already I got the impact of upgrading to 2.4.0 was so big (some of devices have memory leak while reconnecting), so I already rollback the version except for the development environment.
I want to test 2.4.1-snapshot but I don't have experience building from source code and I saw some of comments about experiencing difficulty on building 2.4.0.
If I can apply 2.4.1-snapshot on my 2.4.0 development environment without building from sources, please let me know. I will apply it to test right now.
Thank you so much for the response.

**Comment by pineful** [comment]
@madper I appreciate! But already I got the impact of upgrading to 2.4.0 was so big (some of devices have memory leak while reconnecting), so I already rollback the version except for the development environment.
I want to test 2.4.1-snapshot but I don't have experience building from source code and I saw some of comments about experiencing difficulty on building 2.4.0.
If I can apply 2.4.1-snapshot on my 2.4.0 development environment without building from sources, please let me know. I will apply it to test right now.
Thank you so much for the response.

**Comment by madper** [comment]
@pineful I could provide the boot-jar to you. But maybe you shouldn't trust anyone who provides an unknown binary on the Internet... However, if you have a test environment without any sensitive data, feel free to download it from: http://ptuwip7u6.bkt.clouddn.com/thingsboard-2.4.1-SNAPSHOT-boot.jar

![Screenshot from 2019-07-24 15-14-54](https://user-images.githubusercontent.com/451815/61772874-df023e80-ae25-11e9-8fb8-964b11954863.png)

**Comment by madper** [comment]
@pineful And do you know when I need to use load balance? Currently I have about 3000 devices. I wonder the limitation of a single node. So that I can prepare for load balance in time...

**Comment by pineful** [comment]
@madper Wow thank you! I will apply your boot-jar right now and let you know! Actually we have to think more about the large scale as may factors. I am worrying about the storage (with PostgreSQL) for deleting old records without any performance loss or side effects. As just one table holds all of telemetry right now, it is the crucial point when it scales up.
I am running PostgreSQL because I want to limit just one cloud instance per one business section with small budget. I know the expiration feature on Cassandra but it needs huge configuration than I thought.
I think we should split the server with load balancing between 1k and 5k amount of devices as view of business/technical management, in my opinion. (not to make huge catastrophe for just a few server down)

**Comment by madper** [comment]
@pineful between 1k && 5k? I was hoping it should work well with the c100k problem with a 64G memory server.
BTW, I do not use the built-in telemetry due to issue: https://github.com/thingsboard/thingsboard/issues/1870 ... I export all data to kafka and calc them in real time.

**Comment by pineful** [comment]
@madper It would be very nice for stable operation. But in business environment in korea, I have to think more conservative way. I also consider whether to export telemetry data. I didn't get that issue yet.

**Comment by madper** [comment]
@pineful It's more difficult in China. Tons of people / devices with low unit returns.  :-D
So we have to reduce the pre device memory cost to make the balance of our cost and income...

In fact, there is a trading-off between developing a lightweight IoT service by our team and purchasing Thingsboard's support service for bugfix and consulting.
I think it all depends on the connection limit of a single node. I'd do a pressure test once my team finished the business logic.

**Comment by madper** [comment]
And the good parts of relying on kafka is: you can consider that thingsboard is just a broker. Most of your business logic only depends on the data that exported from kafka. So you are able to replace thingsboard if needed.

**Comment by pineful** [comment]
@madper Thank you for your suggestion and I will consider more. We are delivering electronic appliances such as smartplug, smart outlet/socket (wall embedded), smart light switch (wall embedded) that are operating as IoT Hub (WIFI/BLE). We manufacture and make value-added services with our IoT Engine powered by Thingsboard. It could deliver a lot of environmental sensor data - temperature, humidity, gas, etc. We are delivering these products/solution to our B2B customer - business branch owners, construction company, etc. and the user can control smart devices and enjoy advanced services.
So, we are focusing on 24x365 HA operation not to influence any fault from other partner server area.
Of course there are little B2C customer just buy a smart plug in retail market. It can be grow to control over 10K devices, but not now.
Thank you!

**Comment by ashishpatil09** [comment]
Hi Everyone
What was the resolution for this issue?
I am running thingsboard CE k8s 3.2.2 version and this issue is happening frequently for me.

Is there any resolution for this?
