### ISSUE TITLE
Update from 2.3.1 to 2.4.0 with Postgresql

### ISSUE THREAD

**Issue by lazaj** [thingsboard/thingsboard#1877]
After updating to version 2.4.0 from 2.3.1 thingsboard, using debian package doesn't find my devices.

I'm using PostgreSQL.

`cat /var/log/thingsboard/thingsboard.log | grep ERROR`

2019-07-23 05:30:52,089 [nioEventLoopGroup-6-8] ERROR o.t.s.t.mqtt.MqttTransportHandler - [e1d3825a-288b-4be1-ac7f-4332c493f869] Unexpected Exception
2019-07-23 07:14:30,003 [pool-33-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist
2019-07-23 07:14:33,064 [pool-7-thread-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column deviceenti0_.label does not exist
2019-07-23 07:14:33,548 [pool-7-thread-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column deviceenti0_.label does not exist
2019-07-23 07:14:34,715 [pool-7-thread-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column deviceenti0_.label does not exist
2019-07-23 07:14:35,186 [pool-7-thread-4] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column deviceenti0_.label does not exist
2019-07-23 07:14:36,376 [pool-7-thread-5] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column deviceenti0_.label does not exist
2019-07-23 07:14:36,822 [pool-7-thread-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: column deviceenti0_.label does not exist
Caused by: org.postgresql.util.PSQLException: ERROR: column deviceenti0_.label does not exist
...

`service thingsboard status`
* thingsboard.service - thingsboard
   Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-07-23 07:25:28 UTC; 4s ago
 Main PID: 29848 (thingsboard.jar)
    Tasks: 19 (limit: 4915)
   CGroup: /system.slice/thingsboard.service
           |-29848 /bin/bash /usr/share/thingsboard/bin/thingsboard.jar
           `-29863 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/d

Jul 23 07:25:28 cooxyVPS systemd[1]: thingsboard.service: Failed to reset devices.list: Operation not permitted
Jul 23 07:25:28 cooxyVPS systemd[1]: thingsboard.service: Failed to set invocation ID on control group /system.slice/thingsboard.service, i
Jul 23 07:25:28 cooxyVPS systemd[1]: Started thingsboard.
Jul 23 07:25:30 cooxyVPS thingsboard.jar[29848]:  ===================================================
Jul 23 07:25:30 cooxyVPS thingsboard.jar[29848]:  :: ThingsBoard ::       (v2.4.0)
Jul 23 07:25:30 cooxyVPS thingsboard.jar[29848]:  ===================================================
root@cooxyVPS:/etc/thingsboard/conf# service thingsboard status
* thingsboard.service - thingsboard
   Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-07-23 07:25:28 UTC; 36s ago
 Main PID: 29848 (thingsboard.jar)
    Tasks: 100 (limit: 4915)
   CGroup: /system.slice/thingsboard.service
           |-29848 /bin/bash /usr/share/thingsboard/bin/thingsboard.jar
           `-29863 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/d

**Comment by Backdraft007** [comment]
Did you run the upgrade-script?
```
# Execute upgrade script
$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.3.1 
```

**Comment by lazaj** [comment]
Sorry, I forgot this step ...

**Comment by sfvaleriano** [comment]
Hello,
I've this error:

org.postgresql.util.PSQLException: ERROR: syntax error at or near "NOT"
  Posizione: 632
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:265)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.loadSql(SqlDatabaseUpgradeService.java:186)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:172)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:117)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!

**Comment by Backdraft007** [comment]
@sfvaleriano ,
which version of postgres is installed? If lower than 9.5, have a look here: #2010

**Comment by sfvaleriano** [comment]
Hi,
postgres (PostgreSQL) 9.2.24 on CentOS Linux 7.6.1810
