### ISSUE TITLE
I got an error in running k8s-install-tb.sh

### ISSUE THREAD

**Issue by chenbiao123** [thingsboard/thingsboard#1891]
I use DATABASE=cassandra,but it tell me the pvc unbond the pv,so i edit the cassandra.yml file and add the pv ,but i met another error as flow,so who can help me to solve it ? Thank you!

**Comment by chenbiao123** [comment]
namespace/thingsboard unchanged
Context "kubernetes-admin@kubernetes" modified.
storageclass.storage.k8s.io/fast unchanged
persistentvolume/postgres-pv unchanged
configmap/cassandra-probe-config unchanged
statefulset.apps/cassandra configured
service/cassandra unchanged
configmap/tb-node-db-config unchanged
partitioned roll out complete: 1 new pods have been updated...
configmap/tb-node-config unchanged
pod/tb-db-setup created
pod/tb-db-setup condition met
Starting ThingsBoard installation ...
12:17:32,916 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:17:32,917 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
12:17:32,917 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/config/logback.xml]
12:17:32,919 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
12:17:32,919 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
12:17:32,919 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/config/logback.xml]
12:17:33,088 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
12:17:33,103 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/config/logback.xml] 
12:17:33,103 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 10 seconds
12:17:33,106 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
12:17:33,118 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
12:17:33,143 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - setting totalSizeCap to 3 GB
12:17:33,151 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - Archive files will be limited to [100 MB] each.
12:17:33,193 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - No compression will be used
12:17:33,196 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1717159510 - Will use the pattern /var/log/thingsboard/TB_HOST_IS_UNDEFINED/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
12:17:33,200 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d5380c2 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/TB_HOST_IS_UNDEFINED/thingsboard.%d{yyyy-MM-dd}.%i.log'.
12:17:33,200 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d5380c2 - Roll-over at midnight.
12:17:33,203 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d5380c2 - Setting initial period to Fri Jul 26 12:17:33 UTC 2019
12:17:33,206 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:17:33,254 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/TB_HOST_IS_UNDEFINED/thingsboard.log
12:17:33,254 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/TB_HOST_IS_UNDEFINED/thingsboard.log]
12:17:33,255 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
12:17:33,257 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
12:17:33,258 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:17:33,260 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
12:17:33,260 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.google.common.util.concurrent.AggregateFuture] to OFF
12:17:33,260 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
12:17:33,260 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
12:17:33,261 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
12:17:33,261 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
12:17:33,261 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@45ff54e6 - Registering current configuration as safe fallback point

 ===================================================
 :: ThingsBoard ::       (v2.4.0)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing Cassandra DataBase schema part: schema-entities.cql
Unexpected error during ThingsBoard installation!
java.lang.NullPointerException: null
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.lambda$loadCql$0(CassandraAbstractDatabaseSchemaService.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.loadCql(CassandraAbstractDatabaseSchemaService.java:56)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.createDatabaseSchema(CassandraAbstractDatabaseSchemaService.java:50)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:149)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
pod "tb-db-setup" deleted
