### ISSUE TITLE
io.netty.bootstrap.ServerBootstrap - Failed to register an accepted channel

### ISSUE THREAD

**Issue by madper** [thingsboard/thingsboard#1894]
Hey! 
I'm using thingsboard 2.4.1-snapshot built upon 4255bf48.
I encounter the following issues (amount many other issues) and the mqtt stop working. 

> 2019-07-30 11:22:58,526 [nioEventLoopGroup-4-12] WARN  io.netty.bootstrap.ServerBootstrap - Failed to register an accepted channel: [id: 0x07cf5bc2, L:0.0.0.0/0.0.0.0:1883]          
> java.lang.NullPointerException: null                                                                                                                                                  
>         at sun.nio.ch.EPollArrayWrapper.isEventsHighKilled(EPollArrayWrapper.java:174)                                                                                                
>         at sun.nio.ch.EPollArrayWrapper.setUpdateEvents(EPollArrayWrapper.java:190)                                                                                                   
>         at sun.nio.ch.EPollArrayWrapper.add(EPollArrayWrapper.java:239)                                                                                                               
>         at sun.nio.ch.EPollSelectorImpl.implRegister(EPollSelectorImpl.java:178)           
>         at sun.nio.ch.SelectorImpl.register(SelectorImpl.java:132)                                                                                                                    
>         at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:212)                                                                               
>         at io.netty.channel.nio.AbstractNioChannel.doRegister(AbstractNioChannel.java:382) 
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:497)                                                                                        
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)                                                                                       
>         at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)                                                                                            
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)                                               
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)                                        
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)                                                                                                               
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)                                              
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                                                                                                  
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                
>         at java.lang.Thread.run(Thread.java:748)

**Comment by madper** [comment]
Okay, It looks like that the open files reach the limit. I just increase the limitation and I can't reproduce the issue anymore. Let me close it.
