### ISSUE TITLE
When a get request is invoked using the restApi rule, an exception is returned

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#1895]
The URLConnection method is available for get requests and is normal for postman tools. But using private AsyncRestTemplate httpClient on tb; the method will fail, what is the reason?

![image](https://user-images.githubusercontent.com/10750404/62099874-1f4c3b80-b2c2-11e9-9ea7-e1b0d69ba5ec.png)

![image](https://user-images.githubusercontent.com/10750404/62099888-33903880-b2c2-11e9-9f02-1963bb44dbf3.png)

![image](https://user-images.githubusercontent.com/10750404/62099585-27f04200-b2c1-11e9-803f-2ed3d2c65ea7.png)

java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.springframework.http.client.SimpleBufferingAsyncClientHttpRequest$1.call(SimpleBufferingAsyncClientHttpRequest.java:96)
	at org.springframework.http.client.SimpleBufferingAsyncClientHttpRequest$1.call(SimpleBufferingAsyncClientHttpRequest.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ban2derlog** [comment]
Hello, are there same problems on latest ThingsBoard version?
