### ISSUE TITLE
MQTT error after upgrade to 2.4.0. NullPointerException

### ISSUE THREAD

**Issue by DIYGuy01** [thingsboard/thingsboard#1906]
After upgrade to 2.4.0 started to get error in log file for each device's connection:

> 2019-08-03 18:20:55,616 [nioEventLoopGroup-4-12] INFO  o.t.s.t.mqtt.MqttTransportHandler - [17375339-e011-4ef4-b9ec-969524a9335f] Processing connect msg for client: SS Fujitsu-General. Wemos 3xDS18B20+impulsu sk!
2019-08-03 18:20:55,617 [nioEventLoopGroup-4-12] INFO  o.t.s.t.mqtt.MqttTransportHandler - [17375339-e011-4ef4-b9ec-969524a9335f] Processing connect msg for client with user name: 1z8iV1wyXlFqnMtgiQe9!
2019-08-03 18:20:55,631 [ForkJoinPool-8-worker-23] INFO  o.t.s.t.mqtt.MqttTransportHandler - [17375339-e011-4ef4-b9ec-969524a9335f] Client connected!
2019-08-03 18:20:55,693 [nioEventLoopGroup-4-12] ERROR o.t.s.t.mqtt.MqttTransportHandler - [17375339-e011-4ef4-b9ec-969524a9335f] Unexpected Exception
java.lang.NullPointerException: null
	at org.thingsboard.server.common.transport.service.AbstractTransportService.deregisterSession(AbstractTransportService.java:203)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processDisconnect(MqttTransportHandler.java:409)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processMqttMsg(MqttTransportHandler.java:154)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.channelRead(MqttTransportHandler.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zouhr** [comment]
upgrade from 2.3.0 to2.4.0   the same WARN  log，how to fix。

2019-09-03 08:25:48,184 [TB-Scheduling-1] INFO  o.t.s.d.n.CassandraBufferedRateExecutor - Permits queueSize [0] totalAdded [186] totalLaunched [186] totalReleased [186] totalFailed [0] totalExpired [0] totalRejected [0] totalRateLimited [0] totalRateLimitedTenants [0] currBuffer [0] 
2019-09-03 08:25:58,184 [TB-Scheduling-1] INFO  o.t.s.d.n.CassandraBufferedRateExecutor - Permits queueSize [0] totalAdded [263] totalLaunched [263] totalReleased [263] totalFailed [0] totalExpired [0] totalRejected [0] totalRateLimited [0] totalRateLimitedTenants [0] currBuffer [0] 
2019-09-03 08:26:03,030 [nioEventLoopGroup-11-12] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by org.thingsboard.server.transport.mqtt.MqttTransportHandler.operationComplete()
java.lang.NullPointerException: null
        at org.thingsboard.server.common.transport.service.AbstractTransportService.deregisterSession(AbstractTransportService.java:203)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.operationComplete(MqttTransportHandler.java:484)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1183)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:769)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:745)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:616)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1350)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:611)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:595)
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:611)
        at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:600)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2019-09-03 08:26:04,334 [nioEventLoopGroup-11-8] INFO  o.t.s.t.mqtt.MqttTransportHandler - [c846aebf-715c-451e-b7c4-aa60b353976b] Processing connect msg for client: ifm8ulheVM3nUL6rUBJO!
2019-09-03 08:26:04,334 [nioEventLoopGroup-11-8] INFO  o.t.s.t.mqtt.MqttTransportHandler - [c846aebf-715c-451e-b7c4-aa60b353976b] Processing connect msg for client with user name: ifm8ulheVM3nUL6rUBJO!
2019-09-03 08:26:04,336 [ForkJoinPool-9-worker-12] INFO  o.t.s.t.mqtt.MqttTransportHandler - [c846aebf-715c-451e-b7c4-aa60b353976b] Client connected!

**Comment by Backdraft007** [comment]
Update to 2.4.1 should help.

**Comment by zachjacobs** [comment]
Still an issue in 2.4.1:
`
2019-10-09 12:03:25,510 [nioEventLoopGroup-6-3] INFO  o.t.s.t.mqtt.MqttTransportHandler - [7df0ac9d-d80b-432a-****-****] Processing connect msg for client: ****!
2019-10-09 12:03:25,510 [nioEventLoopGroup-6-3] INFO  o.t.s.t.mqtt.MqttTransportHandler - [7df0ac9d-d80b-432a-****-****] Processing connect msg for client with user name: *****!
2019-10-09 12:03:25,511 [ForkJoinPool-9-worker-25] INFO  o.t.s.t.mqtt.MqttTransportHandler - [7df0ac9d-d80b-432a-****-****] Client connected!
2019-10-09 12:03:27,484 [nioEventLoopGroup-6-3] ERROR o.t.s.t.mqtt.MqttTransportHandler - [7df0ac9d-d80b-432a-****-****] Unexpected Exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1140)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by thucar** [comment]
I'm running 2.4.1 but I'm still seeing this in my log. Is the reason for this error known and is there anything I can do to fix it?

```
2019-10-21 04:00:37,990 [nioEventLoopGroup-4-3] ERROR o.t.s.t.mqtt.MqttTransportHandler - [8e331568-8b9a-46b8-9bec-cbce2710b1c4] Unexpected Exception
java.lang.ClassCastException: null
2019-10-21 04:00:37,991 [nioEventLoopGroup-4-4] ERROR o.t.s.t.mqtt.MqttTransportHandler - [c21fd255-6607-453d-9886-621141d047e2] Unexpected Exception
java.lang.ClassCastException: null
2019-10-21 04:00:39,050 [nioEventLoopGroup-4-5] ERROR o.t.s.t.mqtt.MqttTransportHandler - [37a0f5c5-7118-47bf-abc9-6572cacdf430] Unexpected Exception
java.lang.ClassCastException: null
2019-10-21 04:00:39,051 [nioEventLoopGroup-4-6] ERROR o.t.s.t.mqtt.MqttTransportHandler - [63ed3241-e360-445e-b152-9d497a23c3e8] Unexpected Exception
java.lang.ClassCastException: null
```

**Comment by leex87** [comment]
I am experiencing the same issue. Running Thingsboard on Azure, which is available through the marketplace. I can provision devices and assets but devices can not receive telemetry due to the below issue. Mqtt client is connected to the host and successfully sends payload. Any suggestions?

java.lang.NullPointerException: null
        at org.thingsboard.server.common.transport.service.AbstractTransportService.deregisterSession(AbstractTransportService.java:218)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.operationComplete(MqttTransportHandler.java:499)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1183)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:769)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:745)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:616)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1350)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:611)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:595)
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:611)
        at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38)
        at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:600)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Navid007** [comment]
I have similar issue, client is connecting and showing that sending data however it does not show in device telemetry, interestingly it work with demo.thingsboard.io but it does not work with own thingsboard....   last error:
 2019-12-30 17:06:04,543 [nioEventLoopGroup-6-12] ERROR o.t.s.t.mqtt.MqttTransportHandler - [31e4b650-ebaa-4361-b590-e2d9d50b0733] Unexpected Exception

**Comment by Karabiy** [comment]
which exact payload you have for the MQTT API?

**Comment by ban2derlog** [comment]
Hi, does this issue persist on latest ThingsBoard version?
