### ISSUE TITLE
Switch Node : Lifecycle event is Started as Failed with error.

### ISSUE THREAD

**Issue by raheem52** [thingsboard/thingsboard#1940]
While using Switch Node : Lifecycle event is Started as Failed with error.

java.lang.IllegalArgumentException: Can't compile script: null
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.<init>(RuleNodeJsScriptEngine.java:55)
	at org.thingsboard.server.actors.ruleChain.DefaultTbContext.createJsScriptEngine(DefaultTbContext.java:227)
	at org.thingsboard.rule.engine.filter.TbJsSwitchNode.init(TbJsSwitchNode.java:50)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:127)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:57)
	at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:54)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
	at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.TimeoutException
	at org.thingsboard.server.kafka.TbKafkaRequestTemplate.lambda$null$1(TbKafkaRequestTemplate.java:152)
	at java.util.concurrent.ConcurrentHashMap$EntrySetView.forEach(ConcurrentHashMap.java:4795)
	at org.thingsboard.server.kafka.TbKafkaRequestTemplate.lambda$init$2(TbKafkaRequestTemplate.java:147)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by q82184828** [comment]
你好，请问问题解决了么，我也碰到一样的问题了，希望您能指导一下原因，谢谢！

**Comment by Ultrazombie** [comment]
As I can see, try to reproduce these steps on the latest versions of ThingsBoard. This problem is solved (3.3+)
