### ISSUE TITLE
Secure MQTT connection fails, Platform Integration with Private Hosted TTN

### ISSUE THREAD

**Issue by directcontrol** [thingsboard/thingsboard#1986]
Hi, I am trying to setup an Integration from PE to a Private TTN application with MQTT over SSL on port 8883. Wondering if anyone had the success. Here is the error I get. Is there any configuration setup required for outgoing MQTT connections?

```
java.lang.RuntimeException: Failed to connect to MQTT broker at <mycompany>.thethings.industries:8883.
at org.thingsboard.server.service.integration.mqtt.AbstractMqttIntegration.initClient(AbstractMqttIntegration.java:182)
at org.thingsboard.server.service.integration.mqtt.basic.BasicMqttIntegration.init(BasicMqttIntegration.java:71)
at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.initIntegration(DefaultPlatformIntegrationService.java:599)
at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.getOrCreateThingsboardPlatformIntegration(DefaultPlatformIntegrationService.java:579)
at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.lambda$createIntegration$0(DefaultPlatformIntegrationService.java:245)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
MQTT without SSL works fine. I have other MQTT clients which connect to our TTN Server over SSL successfully. The log file error is as below. 

```
2019-09-01 00:02:11,722 [nioEventLoopGroup-4-2] WARN i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by Ultrazombie** [comment]
Closed, as not active.
