### ISSUE TITLE
Error installing rpm

### ISSUE THREAD

**Issue by aljimgar** [thingsboard/thingsboard#2034]
Hi,

When I try to install rpm on version 2.4.1, I get this error :

error: thingsboard-2.4.1.rpm: tag[42]: BAD, tag 1096 type 5 offset 6256 count 58 len 232
error: thingsboard-2.4.1.rpm cannot be installed

Is there anyone with the same problem?

**Comment by I1Semenenko** [comment]
Hi aljimgar,
Thank you for your request.
Please, use Red Hat or CentOS
due to our guide.
https://thingsboard.io/docs/user-guide/install/rhel/

Fedora is not supported, currently.
Otherwise, please use docker installation.

Regards,

**Comment by aljimgar** [comment]
Hi @I1Semenenko ,

I am using CentOS...

Regards,

**Comment by calluminfra** [comment]
Bumping due to a similar issue. 

I'm attempting to install on an EC2 instance running RHEL and the provided command gives the following response:
```shell
$ sudo rpm -Uvh thingsboard-2.4.1pe.rpm
error: thingsboard-2.4.1pe.rpm: tag[42]: BAD, tag 1096 type 5 offset 24384 count 59 len 236
error: thingsboard-2.4.1pe.rpm cannot be installed
```

**Comment by IvanSemenenko** [comment]
Hi calluminfra,

Does your RHEL version meet with the requirements?
https://thingsboard.io/docs/user-guide/install/rhel/#prerequisites

> This guide describes how to install ThingsBoard on **RHEL/CentOS 7**. 

> 

Regards,

**Comment by calluminfra** [comment]
Hi,

Yes, my EC2 instance appears to have all the required memory (1GB) mentioned for the PostgreSQL deployment. 
The OS currently running on the instance is: Red Hat Enterprise Linux release 8.0.

I followed the directions in the guide and didn't encounter any issues until the rpm command.

**Comment by moferreira** [comment]
I got the same problem here when installing on CentOS 8. Installing on CentOS 7 will run with not problem.

**Comment by itivanr** [comment]
How did you successfully installed on CentOS 7 ?. When try to start thingsboad 2.4.3 loadDemo command, is no able to start:

[root@localhost ~]# sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
 ===================================================
 :: ThingsBoard ::       (v2.4.3)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing DataBase schema for timeseries...
Installing Cassandra DataBase schema part: schema-ts.cql
Unexpected error during ThingsBoard installation!
java.lang.NullPointerException: null
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.lambda$loadCql$0(CassandraAbstractDatabaseSchemaService.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.loadCql(CassandraAbstractDatabaseSchemaService.java:56)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.createDatabaseSchema(CassandraAbstractDatabaseSchemaService.java:50)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:165)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

I followed official CentOS guide.

Any clue about would be appreciate. 

Regards

**Comment by ashvayka** [comment]
Starting ThingsBoard 2.5.1 we support CentOS8 installation and this bug is fixed.
