### ISSUE TITLE
com.datastax.driver.core.exceptions.TransportException: [/192.168.1.131:9042] Cannot connect

### ISSUE THREAD

**Issue by xujingzhou** [thingsboard/thingsboard#2087]
Hi ,  I followed the official website installation, and an error occurred when I executed the following install command.  Thingsboard version: 2.4.1 and cassandra version 3.0.9.

Cassandra install command (https://thingsboard.io/docs/user-guide/install/rhel/?rhelThingsboardDatabase=hybrid):
    sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo 

1. Error info in console:
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing DataBase schema for timeseries...
Installing Cassandra DataBase schema part: schema-ts.cql
Unexpected error during ThingsBoard installation!
java.lang.NullPointerException: null
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.lambda$loadCql$0(CassandraAbstractDatabaseSchemaService.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.loadCql(CassandraAbstractDatabaseSchemaService.java:56)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.createDatabaseSchema(CassandraAbstractDatabaseSchemaService.java:50)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:155)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

2. Error info in install log:
2019-10-14 12:40:00,782 [main] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2019-10-14 12:40:00,789 [main] WARN  o.t.s.d.c.AbstractCassandraCluster - Failed to initialize cassandra cluster due to All host(s) tried for query failed (tried: /192.168.1.131:9042 (com.datastax.driver.core.exceptions.TransportException: [/192.168.1.131:9042] Cannot connect)). Will retry in 3000 ms
2019-10-14 12:40:03,789 [main] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
2019-10-14 12:40:03,796 [main] WARN  o.t.s.d.c.AbstractCassandraCluster - Failed to initialize cassandra cluster due to All host(s) tried for query failed (tried: /192.168.1.131:9042 (com.datastax.driver.core.exceptions.TransportException: [/192.168.1.131:9042] Cannot connect)). Will retry in 3000 ms
2019-10-14 12:40:06,804 [main] ERROR o.t.s.i.ThingsboardInstallService - Unexpected error during ThingsBoard installation!

java.lang.NullPointerException: null
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.lambda$loadCql$0(CassandraAbstractDatabaseSchemaService.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.loadCql(CassandraAbstractDatabaseSchemaService.java:56)
	at org.thingsboard.server.service.install.CassandraAbstractDatabaseSchemaService.createDatabaseSchema(CassandraAbstractDatabaseSchemaService.java:50)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:155)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)

3.  configration in thingsboard.conf(191.168.1.59 machine):
export JAVA_OPTS="$JAVA_OPTS -Dplatform=rpm -Dinstall.data_dir=/usr/share/thingsboard/data"
export JAVA_OPTS="$JAVA_OPTS -Xloggc:/var/log/thingsboard/gc.log -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCDateStamps"
export JAVA_OPTS="$JAVA_OPTS -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10"
export JAVA_OPTS="$JAVA_OPTS -XX:GCLogFileSize=10M -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:CMSWaitDuration=10000 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSParallelInitialMarkEnabled"
export JAVA_OPTS="$JAVA_OPTS -XX:+CMSEdenChunksRecordAlways -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly"
export LOG_FILENAME=thingsboard.out
export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql

export DATABASE_ENTITIES_TYPE=sql
export DATABASE_TS_TYPE=cassandra
export SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
export SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
export SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.1.131:5432/thingsboard
export SPRING_DATASOURCE_USERNAME=postgres
export SPRING_DATASOURCE_PASSWORD=123456

export CASSANDRA_CLUSTER_NAME=Thingsboard Cluster
export CASSANDRA_KEYSPACE_NAME=thingsboard
export CASSANDRA_URL=192.168.1.131:9042
export CASSANDRA_USE_CREDENTIALS=false
export CASSANDRA_USERNAME=
export CASSANDRA_PASSWORD=

**Comment by xujingzhou** [comment]
sloved. 

https://askubuntu.com/questions/435749/cant-start-an-application-as-service-but-running-as-standalone-process-simply
https://stackoverflow.com/questions/22006887/cassandra-saved-cluster-name-test-cluster-configured-name
https://stackoverflow.com/questions/36133127/how-to-configure-cassandra-for-remote-connection
