### ISSUE TITLE
restart raise NullPoint while some device is active

### ISSUE THREAD

**Issue by wenyuan138** [thingsboard/thingsboard#2088]
Hi, 
    It is ok when first time started.
    Then some device connect to system.
    After that, when i restart it, a NullPoint exception raise as below.
    Does anyone know how to fix this?
    Thanks :)

2019-10-14 11:42:24,533 [Akka-app-dispatcher-5] INFO  o.t.server.actors.app.AppActor - Starting main system actor.
2019-10-14 11:42:24,538 [ForkJoinPool-8-worker-25] INFO  o.t.s.t.mqtt.MqttTransportHandler - [9726cda6-06ea-4072-bb07-db1c72e60419] Client connected!
2019-10-14 11:42:24,561 [Akka-app-dispatcher-5] INFO  o.t.server.actors.app.AppActor - Main system actor started.
2019-10-14 11:42:24,563 [Akka-core-dispatcher-7] INFO  o.t.server.actors.tenant.TenantActor - [89f13480-5076-11e9-a28a-7f5695106cc0] Starting tenant actor.
2019-10-14 11:42:24,564 [Akka-core-dispatcher-8] INFO  o.t.server.actors.tenant.TenantActor - [ad62aa00-5cf8-11e9-b808-a56286a44583] Starting tenant actor.
2019-10-14 11:42:24,591 [Akka-core-dispatcher-7] INFO  o.t.server.actors.tenant.TenantActor - [89f13480-5076-11e9-a28a-7f5695106cc0] Tenant actor started.
2019-10-14 11:42:24,591 [Akka-core-dispatcher-8] INFO  o.t.server.actors.tenant.TenantActor - [ad62aa00-5cf8-11e9-b808-a56286a44583] Tenant actor started.
2019-10-14 11:42:24,563 [Akka-app-dispatcher-5] WARN  o.t.server.actors.app.AppActor - Rule Chains initialized by unexpected message: TransportToDeviceActorMsgWrapper(tenantId=ad62aa00-5cf8-11e9-b808-a56286a44583, deviceId=8868f860-c55a-11e9-8040-0defc9559c2c, msg=sessionInfo {
   ...
}
sessionEvent {
  sessionType: ASYNC
}
)
2019-10-14 11:42:25,401 [Akka-rule-dispatcher-9] WARN  o.t.s.actors.ruleChain.RuleNodeActor - [ad62aa00-5cf8-11e9-b808-a56286a44583][dcc58d10-b1d7-11e9-a39d-93a27741622c] Failed to start RULE_NODE processor.
2019-10-14 11:42:25,415 [Akka-rule-dispatcher-9] WARN  o.t.s.actors.ruleChain.RuleNodeActor - Error:
java.lang.NullPointerException: null
	at nari.eiot.rulenode.ApplicationContextHolder.getBean(ApplicationContextHolder.java:48)
	at nari.eiot.rulenode.RuleNodeContextAdaptor.init(RuleNodeContextAdaptor.java:32)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:127)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:57)
	at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:54)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
	at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by wenyuan138** [comment]
I develop an own node, which contains operation of trying to get a bean from application context of spring.

**Comment by wenyuan138** [comment]
I remove the spring operation from init function to avoid this issue currently.
