### ISSUE TITLE
sonSyntaxException: Can't parse value: [0,0,0,0,0,0,0,0,0,0] for payload from MQTT package

### ISSUE THREAD

**Issue by spanov1980** [thingsboard/thingsboard#2181]
Hello,

Our IoT device send MQTT payload like

`{"DetectedPersons":2,"DetectedPersonsZone":[0,0,0,0,0,0,0,0,0,0],"DetectionZonesPresent":0,"GlobalIlluminanceLux":98.0,"LuxZone":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"Temperature":"27.0","Humidity": "34.6"}`

When such payload receive by Thingsboard MQTT Broker, the connection terminated and the following error appears on logs:

> 2019-11-15 16:44:48,302 [nioEventLoopGroup-4-3] INFO  o.t.s.t.mqtt.MqttTransportHandler - [84b9f975-e38f-47a9-b81a-fe0d842efa5c] Processing connect msg for client: hps-01!
> 
> 2019-11-15 16:44:48,302 [nioEventLoopGroup-4-3] INFO  o.t.s.t.mqtt.MqttTransportHandler - [84b9f975-e38f-47a9-b81a-fe0d842efa5c] Processing connect msg for client with use
> 
> r name: wuuk8fbqwg4EvMVc5NGU!
> 
> 2019-11-15 16:44:48,304 [ForkJoinPool-8-worker-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [84b9f975-e38f-47a9-b81a-fe0d842efa5c] Client connected!
> 
> 2019-11-15 16:44:50,032 [nioEventLoopGroup-4-3] WARN  o.t.s.t.mqtt.MqttTransportHandler - [84b9f975-e38f-47a9-b81a-fe0d842efa5c] Failed to process publish msg [v1/devices/
> 
> me/telemetry][-1]
> 
> org.thingsboard.server.common.transport.adaptor.AdaptorException: com.google.gson.JsonSyntaxException: Can't parse value: [0,0,0,0,0,0,0,0,0,0]
> 
>         at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToPostTelemetry(JsonMqttAdaptor.java:64)
> 
>         at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processDevicePublish(MqttTransportHandler.java:218)
> 
>         at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processPublish(MqttTransportHandler.java:181)
> 
>         at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processMqttMsg(MqttTransportHandler.java:140)
> 
>         at org.thingsboard.server.transport.mqtt.MqttTransportHandler.channelRead(MqttTransportHandler.java:118)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
> 
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
> 
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
> 
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
> 
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
> 
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
> 
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
>         at java.lang.Thread.run(Thread.java:748)
> 
> Caused by: com.google.gson.JsonSyntaxException: Can't parse value: [0,0,0,0,0,0,0,0,0,0]
> 
>         at org.thingsboard.server.common.transport.adaptor.JsonConverter.parseProtoValues(JsonConverter.java:208)
> 
>         at org.thingsboard.server.common.transport.adaptor.JsonConverter.parseWithoutTs(JsonConverter.java:166)
> 
>         at org.thingsboard.server.common.transport.adaptor.JsonConverter.parseObject(JsonConverter.java:159)
> 
>         at org.thingsboard.server.common.transport.adaptor.JsonConverter.parseObject(JsonConverter.java:95)
> 
>         at org.thingsboard.server.common.transport.adaptor.JsonConverter.convertToTelemetry(JsonConverter.java:77)
> 
>         at org.thingsboard.server.common.transport.adaptor.JsonConverter.convertToTelemetryProto(JsonConverter.java:71)
> 
>         at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToPostTelemetry(JsonMqttAdaptor.java:62)
> 
>         ... 25 common frames omitted
> 
> 2019-11-15 16:44:50,032 [nioEventLoopGroup-4-3] INFO  o.t.s.t.mqtt.MqttTransportHandler - [84b9f975-e38f-47a9-b81a-fe0d842efa5c] Closing current session due to invalid publish msg [v1/devices/me/telemetry][-1]

We can change nothing on the device side. Any advices?

**Comment by Ultrazombie** [comment]
Is your problem still relevant?
