### ISSUE TITLE
cannot open web，found lots of mqtt connct，but in fact only 40 devices use mqtt push telemetry。

### ISSUE THREAD

**Issue by zouhr** [thingsboard/thingsboard#2203]
the thingsboard.log   and i use netstat -anp | grep 1883 session log。  
i think when the device restart(use 4G sim connect to the server),mqtt connect is become zombie process。  the thingsboard server cannot release the resource, when the connect is abort or abnormal  ??,so that  in order to  thingsboard.log error.
 
 2019-11-20 00:00:01,616 [nioEventLoopGroup-10-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:145)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2019-11-20 00:00:02,316 [http-nio-0.0.0.0-8088-Acceptor-0] ERROR org.apache.tomcat.util.net.Acceptor - Socket accept failed
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:448)
        at org.apache.tomcat.util.net.NioEndpoint.serverSocketAccept(NioEndpoint.java:70)
        at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:95)
        at java.lang.Thread.run(Thread.java:748)

use netstat -anp| grep 1883 | wc -l ,  the number about 2800.
netstat -anp | grep 1883  like this

tcp6       0      0 10.10.0.93:1883         203.168.10.88:29976     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.20.66:61037     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.26.139:57423    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.22.182:55557    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.8.227:1385      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.24.246:51737    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.22.35:42278     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.13.75:22935     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.16.244:19255    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.20.123:59744    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.15.106:64236    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.24.79:32830     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.31.182:23903    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.13.170:34167    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.24.114:34287    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.8.6:46152       ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.14.254:31439    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.28.183:65126    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.10.129:20910    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.23.156:4322     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.24.29:9230      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.10.131:54981    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.21.149:58644    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.15.7:24524      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.24.65:18375     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.13.2:1839       ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.16.183:51529    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.20.1:20245      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.11.53:45170     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.13.233:44006    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.14.111:35118    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.13.116:15795    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.31.132:10858    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.25.251:19775    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.12.59:16878     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.23.219:48197    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.31.21:38580     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.16.209:41493    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.31.69:52100     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.29.146:51178    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.26.119:44203    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.15.76:47880     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.10.50:52356     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.14.146:38965    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.24.116:16120    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.29.73:4307      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.9.7:57410       ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.17.92:58898     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.9.209:49943     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.15.224:35013    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.8.0:7573        ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.16.24:7263      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.12.20:3130      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.15.221:47916    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.10.253:10553    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.23.54:5281      ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.22.101:12699    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.27.87:26885     ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.22.148:20884    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.10.102:30394    ESTABLISHED 31539/java          
tcp6       0      0 10.10.0.93:1883         203.168.14.202:13068    ESTABLISHED 31539/java      
........

**Comment by zouhr** [comment]
is there any bug in netty-mqtt,  how to resovle the problem。

**Comment by zouhr** [comment]
in thingsboard.yml   , change 
so_keep_alive: "${NETTY_SO_KEEPALIVE:false}" 
to
so_keep_alive: "${NETTY_SO_KEEPALIVE:true}"
