### ISSUE TITLE
No Data in Server-side RPC

### ISSUE THREAD

**Issue by antaresf** [thingsboard/thingsboard#225]
hi All,

Really appreciated what you guys doing here.
We tried the Gateway, and when we test Server-side RPC subscribe to "v1/gateway/rpc", gateway received below logs :

2017-07-27 07:53:04,875 [MQTT Rec: ftI7DYQ+6i2tRrwy4luLNFmLSA6mhyt3mFcmqtXmh0I=] DEBUG o.e.p.c.m.i.wire.MqttInputStream - null: Automatic Reconnect Successful: PUBLISH qos:1 msgId:10 retained:false dup:false topic:"v1/gateway/rpc" payload:[hex:7b22646576696365223a22534e2d303033222c22 utf8:"{"device":"SN-003","" length:94]
2017-07-27 07:53:04,876 [MQTT Rec: ftI7DYQ+6i2tRrwy4luLNFmLSA6mhyt3mFcmqtXmh0I=] DEBUG o.e.p.c.mqttv3.internal.ClientState - 53e9e3f1-4049-4c6e-a8b1-675715b061c0: received key=10 message=PUBLISH qos:1 msgId:10 retained:false dup:false topic:"v1/gateway/rpc" payload:[hex:7b22646576696365223a22534e2d303033222c22 utf8:"{"device":"SN-003","" length:94]
2017-07-27 07:53:04,877 [MQTT Call: ftI7DYQ+6i2tRrwy4luLNFmLSA6mhyt3mFcmqtXmh0I=] DEBUG o.e.p.c.m.internal.CommsCallback - 53e9e3f1-4049-4c6e-a8b1-675715b061c0: call messageArrived key=10 topic=v1/gateway/rpc
2017-07-27 07:53:04,877 [MQTT Call: ftI7DYQ+6i2tRrwy4luLNFmLSA6mhyt3mFcmqtXmh0I=] TRACE o.t.g.service.MqttGatewayService - Message arrived [v1/gateway/rpc] 10

Gateway received : {"device":"SN-003",**""** length:94] ---> **Missing data.**

According to doc it should be : {"device": "Device A", **"data": {"id": $request_id, "method": "toggle_gpio", "params": {"pin":1}}}**

Below is the log in server, which already send correct set setGpioStatus :

2017-07-27 00:53:04,833 [Akka-system-plugin-dispatcher-24] TRACE o.t.s.a.p.SharedPluginProcessingContext - [a9123180-9fce-11e6-8080-808080808080] Forwarding msg ToDeviceRpcRequest(id=8f57609e-330a-4a98-bfd6-1285aa411359, tenantId=cba44a80-9fce-11e6-8080-808080808080, deviceId=66bceb60-6b8c-11e7-a213-7f5942033665, oneway=false, expirationTime=1501116785333, body=ToDeviceRpcRequestBody(**method=setGpioStatus, params={"pin":3,"enabled":true})) to device actor!**
2017-07-27 00:53:04,833 [Akka-system-plugin-dispatcher-24] TRACE o.t.s.a.p.SharedPluginProcessingContext - [a9123180-9fce-11e6-8080-808080808080] Forwarding msg ToDeviceRpcRequestPluginMsg(serverAddress=Optional.empty, pluginId=a9123180-9fce-11e6-8080-808080808080, pluginTenantId=13814000-1dd2-11b2-8080-808080808080, msg=ToDeviceRpcRequest(id=8f57609e-330a-4a98-bfd6-1285aa411359, tenantId=cba44a80-9fce-11e6-8080-808080808080, deviceId=66bceb60-6b8c-11e7-a213-7f5942033665, oneway=false, expirationTime=1501116785333, body=ToDeviceRpcRequestBody(method=setGpioStatus, params={"pin":3,"enabled":true}))) to local device actor!
2017-07-27 00:53:05,353 [Akka-system-plugin-dispatcher-24] TRACE o.t.s.e.core.plugin.rpc.RpcManager - [8f57609e-330a-4a98-bfd6-1285aa411359] Processing rpc timeout for local device [66bceb60-6b8c-11e7-a213-7f5942033665]
2017-07-27 00:53:05,354 [Akka-system-plugin-dispatcher-24] DEBUG o.a.catalina.core.AsyncContextImpl - Req: 65b2f5af  CReq: 3312f1bc  RP:  cfad204  Stage: 7  Thread: plugin-dispatcher-24  State:                  N/A  Method: dispatch     URI: /api/plugins/rpc/twoway/66bceb60-6b8c-11e7-a213-7f5942033665
	at org.thingsboard.server.extensions.core.plugin.rpc.handlers.RpcRestMsgHandler.reply(RpcRestMsgHandler.java:117)
	at org.thingsboard.server.extensions.core.plugin.rpc.RpcManager.process(RpcManager.java:65)
	at org.thingsboard.server.extensions.core.plugin.rpc.RpcPlugin.process(RpcPlugin.java:50)
2017-07-27 00:53:05,354 [Akka-system-plugin-dispatcher-24] TRACE o.t.s.e.core.plugin.rpc.RpcManager - [8f57609e-330a-4a98-bfd6-1285aa411359] Unknown or stale rpc response received [FromDeviceRpcResponse(id=8f57609e-330a-4a98-bfd6-1285aa411359, response=Optional.empty, **error=Optional[TIMEOUT])]**

Thanks
Cheers
Faisal

**Comment by ssmaurya** [comment]
Please ensure that content in storage folder is deleted and restart your gateway after that.
  Additionally ensure that device for which rpc from server is expected is in connected state from gateway to platform(success Connect message published)

**Comment by vparomskiy** [comment]
Please update to the latest Thingsboard and Tb Gateway version. The issue should be resolved
