### ISSUE TITLE
which directory/file  the default DB(HSQLDB) uses to save data? 

### ISSUE THREAD

**Issue by earnestXu** [thingsboard/thingsboard#2274]
sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v2.4.2.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts.sql
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!
	at org.thingsboard.server.dao.user.UserServiceImpl$1.validateDataImpl(UserServiceImpl.java:411)
	at org.thingsboard.server.dao.user.UserServiceImpl$1.validateDataImpl(UserServiceImpl.java:361)
	at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:41)
	at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:116)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createUser(DefaultSystemDataLoaderService.java:180)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createSysAdmin(DefaultSystemDataLoaderService.java:89)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:167)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

**Comment by pgrisu** [comment]
Under linux thingsboard HSQLDB is located here /usr/share/thingsboard/data/sql and it's directly opened and locked by thingsboard application without any DB server in the middle
Close this issue if no more info is required please
