### ISSUE TITLE
V2.4.3 PE upgrade failed

### ISSUE THREAD

**Issue by leonmyburg** [thingsboard/thingsboard#2342]
We have a hybrid DB setup but I changed it to cassandra for both as per instructions from https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#upgrading-to-243pe

Seems to fail at Upgrading ThingsBoard from version 2.4.3 to 2.4.3PE. 

sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.1
 ===================================================
 :: ThingsBoard Professional Edition ::       (v2.4.3PE)
 ===================================================

Starting ThingsBoard Upgrade from version 2.4.1 ...
Upgrading ThingsBoard from version 2.4.1 to 2.4.2 ...
Updating schema ...
Updating assets ...
Schema updated.
Upgrading ThingsBoard from version 2.4.2 to 2.4.3 ...
Updating schema ...
Updating alarms ...
Schema updated.
Upgrading ThingsBoard from version 2.4.3 to 2.4.3PE ...
Updating schema ...
Unexpected error during ThingsBoard installation!
com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table user
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:49)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:39)
        at org.thingsboard.server.service.install.CassandraDatabaseUpgradeService.lambda$loadCql$0(CassandraDatabaseUpgradeService.java:393)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.thingsboard.server.service.install.CassandraDatabaseUpgradeService.loadCql(CassandraDatabaseUpgradeService.java:392)
        at org.thingsboard.server.service.install.CassandraDatabaseUpgradeService.upgradeDatabase(CassandraDatabaseUpgradeService.java:315)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:148)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table user

**Comment by ricsdeol** [comment]
I Had problem with Timescale:


``` 
2020-02-01 00:28:05,861 [TB-Scheduling-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42P01
2020-02-01 00:28:05,861 [TB-Scheduling-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: relation "ts_kv" does not exist
  Position: 281
2020-02-01 00:28:05,861 [TB-Scheduling-1] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
java.util.concurrent.CompletionException: org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```

**Comment by Karabiy** [comment]
have you merged the configs for the thingsboard.conf and thingsboard.yml?
