### ISSUE TITLE
Thingsboard Docker - Unable To Connect To Cassandra...

### ISSUE THREAD

**Issue by Argental2019** [thingsboard/thingsboard#2399]
Dear team: 
 I pulled the TB Cassandra image from docker as stated, including parameters, ports, etc. 

After installing it, it cannot connect to Cassandra: 

Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...
Wait for cassandra db to start...

I am using Debian as root...

Any advice will be appreciated.

Kind regards.

**Comment by Argental2019** [comment]
at cassandra Logs I found this message: 

DEBUG [main] 2020-02-06 17:37:29,972 DatabaseDescriptor.java:497 - Error checking disk space
java.nio.file.AccessDeniedException: /var/lib/cassandra/commitlog
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[na:1.8.0_212]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_212]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_212]
        at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:57) ~[na:1.8.0_212]
        at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:64) ~[na:1.8.0_212]
        at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44) ~[na:1.8.0_212]
        at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51) ~[na:1.8.0_212]
        at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39) ~[na:1.8.0_212]
        at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368) ~[na:1.8.0_212]
        at java.nio.file.Files.getFileStore(Files.java:1461) ~[na:1.8.0_212]
        at org.apache.cassandra.io.util.FileUtils.getFileStore(FileUtils.java:682) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:1067) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:493) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:324) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:153) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:137) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:665) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:609) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:742) [apache-cassandra-3.11.5.jar:3.11.5]
ERROR [main] 2020-02-06 17:37:29,975 CassandraDaemon.java:759 - Exception encountered during startup
org.apache.cassandra.exceptions.ConfigurationException: Unable to check disk space available to /var/lib/cassandra/commitlog. Perhaps the Cassandra user does not have the necessary permissions

Seems to be a security issue, however I ran the docker pull as root, so what else could it be??

**Comment by datenheim** [comment]
without your complete docker command or even your docker-compose file nobody really can help.
beside that you might want to use the forum at https://groups.google.com/forum/#!forum/thingsboard and not flood the issue tracker ;)

**Comment by SergMeleshko** [comment]
Hello @Argental2019 
Is the issue still relevant?
