### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by fg0578** [thingsboard/thingsboard#2472]
Hi, I've tried to install the PE in vmware/ubuntu 18.04. when I followed INSTALLATION GUIDE ON UBUNTU till Step 6, I got this error:
 ===================================================
 :: ThingsBoard Professional Edition ::       (v2.4.3PE)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:443)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:217)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:75)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:184)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

Could anybody help me on this issue?

**Comment by fg0578** [comment]
BTW, my password configure is right to the user postgres

**Comment by fg0578** [comment]
I see the issue, the postgresql's password can not contain letters like "#" "&" in the script.

**Comment by garageeks** [comment]
@ashvayka I have followed the installation guide and proceeded to generate random password for PostgreSQL user, only to fail installation script because the password was wrong.
I removed special characters as suggested by @fg0578 and it worked. 
I suggest to add this note to the installation guide, which is otherwise well written :)
