### ISSUE TITLE
Can't connect my STM32 + Ethernet device using MQTT?

### ISSUE THREAD

**Issue by suryasundarraj** [thingsboard/thingsboard#250]
Hi, 

I have seen the following error on the thingsboard.log whenever connection establishes from my device.

2017-08-17 00:47:31,007 [nioEventLoopGroup-6-9] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt57] Unexpected Exception
java.lang.NullPointerException: null
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processMqttMsg(MqttTransportHandler.java:95)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.channelRead(MqttTransportHandler.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

Please let me know, how to fix this issue. Thanks.

**Comment by ralienpp** [comment]
Can you include some client-side code, so we can see how you are trying to connect?

**Comment by suryasundarraj** [comment]
Check out the main.cpp file from this link https://developer.mbed.org/users/hudakz/code/MQTT_Hello_ENC28J60/ I have edited according to the thingsboard ip and token as username

**Comment by ralienpp** [comment]
How did you provide the token? In the file you linked to: `MQTTClient          mqttClient(serverIP, 1883, onMqttMessage, ethernetClient);` there are no arguments related to authentication. How are you sure that you're authenticating?

**Comment by suryasundarraj** [comment]
I have provided on the line number 73,
connected = mqttClient.connect("myMQTTHelloClient", "AUTH_TOKEN", NULL);

**Comment by ralienpp** [comment]
If this is the library in question https://developer.mbed.org/users/hudakz/code/MQTTClient/file/ca17c5d846e7/MQTTClient.cpp and if you're using this particular function

```
bool MQTTClient::connect(char* id, char* user, char* pass) {
    return connect(id, user, pass, 0, 0, 0, 0);
}
```

then the logic looks good and to the best of my knowledge, you're passing the parameters correctly. This must be a server-side issue then.



p.s. your messages will be easier to read if you use backticks like this one ` to indicate that a piece of text is some code that requires syntax highlighting.

**Comment by ssmaurya** [comment]
Looks mostly connection issue. Can you get network capture logs to see the transaction between your device and platform? It will give pointers on point of failure?

**Comment by suryasundarraj** [comment]
I am having only the logs captured on thingsboard.log, that I have mentioned above. Please give me some pointers to obtain network captured logs.

**Comment by ralienpp** [comment]
The easiest solution is to use `Wireshark`. But if you run a headless server, you'll need `tcpdump`.

**Comment by suryasundarraj** [comment]
The issue was the client ID, I used '-' which is not allowed on the thingsboard. Thanks for the help

**Comment by ralienpp** [comment]
I wouldn't close this issue, because it should be reflected in the documentation or the software should be adjusted to tolerate such client identifiers or at least log it in a prominent place, so end users would be aware of it.

It took you a day to figure it out, + a few other people had to get involved in this thread and chime in with ideas. Can you imagine how awesome it would have been if all of us used this time for something else?

**Comment by ssmaurya** [comment]
Agree with@ralienpp. We should address it in platform so that no one else spends time again on this.

**Comment by ashvayka** [comment]
The client id that was used is not valid according to MQTT spec. The error related to this happens in netty MQTT codec. Any PR to fix this is welcome but I don't think that our team will have time to fix this in the nearest future.

**Comment by ssmaurya** [comment]
Agree with @ashvayka.  I mistook clientId as accesstoken. 
MQTT spec is very clear on this: The Server MUST allow ClientIds which are between 1 and 23 UTF-8 encoded bytes in length, and that
571 contain only the characters
572 "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
   In my opinion, this need not be taken up for fixing. There's already mechanism to identify clients with the use of device credentials so specifying clientIds explicitly is not needed.

**Comment by ralienpp** [comment]
I can tell you that I use `device_id` as a client identifier, which is a `UUID` with dashes in it, exactly as Thingsboard displays it when a new device is added. Although it is not valid per spec, Thingsboard tolerates it and works fine.

So it seems that all invalid clientids are equal, but some are more equal than others :-)

**Comment by ashvayka** [comment]
Maybe someone will find this article useful: 
https://forgge.github.io/B-L475E-IOT01A-thingsboard-read-temperature-and-humidity-using-mbed.html
