### ISSUE TITLE
Problems with PostgreSQL with SSL

### ISSUE THREAD

**Issue by sanru95** [thingsboard/thingsboard#2517]
Hello I'm trying to deploy a Thingsboard PE Edition hosted by DigitalOcean.
The idea is to run de application in a virtual machine and having as database one of the postgresql managed databases that DO offers. These database can be access remotly by my virtual machine, but SSL is required. I already try connecting to the database through psql and it's working correctly.
I managed to make the application work with a local database, but when I decided to move to the external i get this problem:

```
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnetionFactoryImpl.java:272)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
        at org.postgresql.Driver.makeConnection(Driver.java:404)
        at org.postgresql.Driver.connect(Driver.java:272)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:75)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:184)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: java.net.UnknownHostException: ????:????@db-postgresql-????????.ondigitalocean.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at org.postgresql.core.PGStream.<init>(PGStream.java:61)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
        ... 17 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

```
(I added the ???? for privacy)

The `thingsboard.conf` config file has been edited as follows:

```
# DB Configuration 
export DATABASE_ENTITIES_TYPE=sql
export DATABASE_TS_TYPE=sql
export SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
export SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
export SPRING_DATASOURCE_URL=jdbc:postgresql://database_host:database_port/thingsboard?sslmode=require
export SPRING_DATASOURCE_USERNAME=database_user
export SPRING_DATASOURCE_PASSWORD=database_password
```
It seems that the problem is with the `sslmode=require` (not verify mode).

**Comment by rjswal** [comment]
not sure if you are stll facing this problem or not.
But it seems you need to add rootcert/cert/key files as well in dburl path.

**Comment by xpbyte** [comment]
I have the same problem

**Comment by ban2derlog** [comment]
Hi, to use SSL for PostgreSQL you need to use such configuration:
`export SPRING_DATASOURCE_URL:jdbc:postgresql://PSQL_ENDPOINT/thingsboard?ssl=true&sslcert=CERT_FILE_PATH&sslkey=KEYFILE_PATH&sslrootcert=ROOTCERT_PATH&sslmode=require`
