### ISSUE TITLE
Websocket API can not work in version 2.5.0-snapshot

### ISSUE THREAD

**Issue by lsyer** [thingsboard/thingsboard#2577]
I run the  Websocket API example, but it shows "Error during WebSocket handshake: Unexpected response code: 500" on the console.

The code is :
var webSocket = new WebSocket("ws://127.0.0.1:8080/api/ws/plugins/telemetry?token=" + token);

And part of the error info in /var/log/thingsboard/thingsboard.log is:
2020-04-05 20:32:26,586 [http-nio-0.0.0.0-8080-exec-10] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.NullPointerException: null
	at org.thingsboard.server.service.security.model.token.JwtTokenFactory.parseAccessJwtToken(JwtTokenFactory.java:113)
	at org.thingsboard.server.service.security.auth.jwt.JwtAuthenticationProvider.authenticate(JwtAuthenticationProvider.java:42)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)

**Comment by lsyer** [comment]
Token here is not the refreshtoken.
Replacing refreshtoken with token, all is ok.

**Comment by Emerrv** [comment]
Having the same logs, cant load the page after configuring custom translation, 
![image](https://user-images.githubusercontent.com/53671211/86869745-19033980-c0a5-11ea-851f-413f9e0ca0f5.png)
