### ISSUE TITLE
ThingsBoard upgrade from 2.2.0 to 2.3.0 is failed!

### ISSUE THREAD

**Issue by destr1ke** [thingsboard/thingsboard#2623]
Hello, once again trying to update my platform and get the following:
**$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.2.0**
```
20:49:57,484 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
20:49:57,485 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
20:49:57,485 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/share/thingsboard/conf/logback.xml]
20:49:57,490 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
20:49:57,490 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/usr/share/thingsboard/conf/logback.xml]
20:49:57,490 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/lib/queue-2.3.0.jar!/logback.xml]
20:49:57,628 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:49:57,630 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
20:49:57,656 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [fileLogAppender]
20:49:57,685 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@668386784 - setting totalSizeCap to 3 GB
20:49:57,694 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@668386784 - Archive files will be limited to [100 MB] each.
20:49:57,734 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@668386784 - No compression will be used
20:49:57,736 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@668386784 - Will use the pattern /var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log for the active file
20:49:57,741 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4f3f5b24 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/thingsboard/thingsboard.%d{yyyy-MM-dd}.%i.log'.
20:49:57,741 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4f3f5b24 - Roll-over at midnight.
20:49:57,744 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4f3f5b24 - Setting initial period to Tue Apr 14 20:07:09 UTC 2020
20:49:57,749 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:49:57,799 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - Active log file name: /var/log/thingsboard/thingsboard.log
20:49:57,799 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[fileLogAppender] - File property is set to [/var/log/thingsboard/thingsboard.log]
20:49:57,802 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.thingsboard.server] to INFO
20:49:57,803 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
20:49:57,803 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
20:49:57,803 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [fileLogAppender] to Logger[ROOT]
20:49:57,808 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:49:57,809 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@15aeb7ab - Registering current configuration as safe fallback point

 ===================================================
 :: ThingsBoard ::       (v2.3.0)
 ===================================================

log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB717A4B4B5C.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting ThingsBoard Upgrade from version 2.2.0 ...
Upgrading ThingsBoard from version 2.2.0 to 2.3.0 ...
Updating system data...
Unexpected error during ThingsBoard installation!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select widgetsbun0_.id as id1_21_, widgetsbun0_.alias as alias2_21_, widgetsbun0_.search_text as search_t3_21_, widgetsbun0_.tenant_id as tenant_i4_21_, widgetsbun0_.title as title5_21_ from widgets_bundle widgetsbun0_ where widgetsbun0_.tenant_id=? and widgetsbun0_.alias=?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:242)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:436)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy130.findWidgetsBundleByTenantIdAndAlias(Unknown Source)
        at org.thingsboard.server.dao.sql.widget.JpaWidgetsBundleDao.findWidgetsBundleByTenantIdAndAlias(JpaWidgetsBundleDao.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy131.findWidgetsBundleByTenantIdAndAlias(Unknown Source)
        at org.thingsboard.server.dao.widget.WidgetsBundleServiceImpl.findWidgetsBundleByTenantIdAndAlias(WidgetsBundleServiceImpl.java:87)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.deleteSystemWidgetBundle(DefaultSystemDataLoaderService.java:159)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:114)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:182)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1929)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1898)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)
        at org.hibernate.loader.Loader.doQuery(Loader.java:919)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
        at org.hibernate.loader.Loader.doList(Loader.java:2617)
        at org.hibernate.loader.Loader.doList(Loader.java:2600)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)
        at org.hibernate.loader.Loader.list(Loader.java:2424)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1326)
        at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
        at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
        at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:529)
        at org.hibernate.jpa.criteria.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:368)
        at com.sun.proxy.$Proxy178.getSingleResult(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:210)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:82)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:116)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:106)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:482)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:460)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        ... 27 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: WIDGETS_BUNDLE in statement [select widgetsbun0_.id as id1_21_, widgetsbun0_.alias as alias2_21_, widgetsbun0_.search_text as search_t3_21_, widgetsbun0_.tenant_id as tenant_i4_21_, widgetsbun0_.title as title5_21_ from widgets_bundle widgetsbun0_ where widgetsbun0_.tenant_id=? and widgetsbun0_.alias=?]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
        at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at com.sun.proxy.$Proxy78.prepareStatement(Unknown Source)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:146)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:172)
        ... 65 common frames omitted
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: WIDGETS_BUNDLE
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.ParserDQL.readTableName(Unknown Source)
        at org.hsqldb.ParserDQL.readTableOrSubquery(Unknown Source)
        at org.hsqldb.ParserDQL.XreadTableReference(Unknown Source)
        at org.hsqldb.ParserDQL.XreadFromClause(Unknown Source)
        at org.hsqldb.ParserDQL.XreadTableExpression(Unknown Source)
        at org.hsqldb.ParserDQL.XreadQuerySpecification(Unknown Source)
        at org.hsqldb.ParserDQL.XreadSimpleTable(Unknown Source)
        at org.hsqldb.ParserDQL.XreadQueryPrimary(Unknown Source)
        at org.hsqldb.ParserDQL.XreadQueryTerm(Unknown Source)
        at org.hsqldb.ParserDQL.XreadQueryExpressionBody(Unknown Source)
        at org.hsqldb.ParserDQL.XreadQueryExpression(Unknown Source)
        at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
        at org.hsqldb.ParserCommand.compilePart(Unknown Source)
        at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
        at org.hsqldb.Session.compileStatement(Unknown Source)
        at org.hsqldb.StatementManager.compile(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        ... 77 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
ubuntu@ip:/etc/thingsboard/conf$
```
Help , please!

**Comment by CooL16** [comment]
You have to login via user postgres or grant all privilege to your user you are trying to connect to database.

**Comment by destr1ke** [comment]
> You have to login via user postgres or grant all privilege to your user you are trying to connect to database.

Hi, i'm trying to login via user postgres and then

**Comment by CooL16** [comment]
You can use this command to login via user postgres without postgres password: `sudo -i -u postgres psql`
Then to reset the password please execute `/password`

**Comment by destr1ke** [comment]
> You can use this command to login via user postgres without postgres password: `sudo -i -u postgres psql`
> Then to reset the password please execute `\password`


Thanks, i did as you said but the error is the same

**Comment by destr1ke** [comment]
Сan i upgrade immediately from 2.2.0 to 3.1 without intermediate updates?

**Comment by CooL16** [comment]
Yes (as soon as you have only PostgreSQL database mode). As well, please run the upgrade script not as postgres user, but as ubuntu or as root.
