### ISSUE TITLE
Data converter crashing trying to parse json from TTN. Json seems valid. Function works in test function mode with the same json message.

### ISSUE THREAD

**Issue by dajtxx** [thingsboard/thingsboard#2712]
I'm getting the exception below when trying to parse the json coming in from a TTN device. I have no payload formatters in TTN, as you can see there is only the payload_raw field.

com.google.gson.JsonSyntaxException: Can't parse value: {"app_id":"dt_test_app","dev_id":"pumpctrl-m0","hardware_serial":"000F71ED836EC4D2","port":1,"counter":0,"payload_raw":"AQ==","metadata":{"time":"2020-05-02T11:56:46.65198087Z"}}
	at org.thingsboard.server.common.adaptor.JsonConverter.parseProtoValues(JsonConverter.java:225)
	at org.thingsboard.server.common.adaptor.JsonConverter.parseWithoutTs(JsonConverter.java:183)
	at org.thingsboard.server.common.adaptor.JsonConverter.parseObject(JsonConverter.java:176)
	at org.thingsboard.server.common.adaptor.JsonConverter.parseObject(JsonConverter.java:112)
	at org.thingsboard.server.common.adaptor.JsonConverter.convertToTelemetry(JsonConverter.java:94)
	at org.thingsboard.server.common.adaptor.JsonConverter.convertToTelemetryProto(JsonConverter.java:88)
	at org.thingsboard.integration.api.converter.AbstractUplinkDataConverter.parseTelemetry(AbstractUplinkDataConverter.java:150)
	at org.thingsboard.integration.api.converter.AbstractUplinkDataConverter.parseUplinkData(AbstractUplinkDataConverter.java:115)
	at org.thingsboard.integration.api.converter.AbstractUplinkDataConverter.convertUplink(AbstractUplinkDataConverter.java:75)
	at org.thingsboard.integration.api.AbstractIntegration.convertToUplinkDataList(AbstractIntegration.java:226)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.doProcess(BasicMqttIntegration.java:121)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.doProcess(BasicMqttIntegration.java:61)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.process(AbstractMqttIntegration.java:114)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.lambda$subscribeToTopics$1(BasicMqttIntegration.java:102)
	at org.thingsboard.mqtt.MqttChannelHandler.invokeHandlersForIncomingPublish(MqttChannelHandler.java:124)
	at org.thingsboard.mqtt.MqttChannelHandler.handlePublish(MqttChannelHandler.java:198)

My TB data converter is based upon the sample ones:

// Decode an uplink message from a buffer
// payload - array of bytes
// metadata - key/value object

/** Decoder **/

// decode payload to string
//var payloadStr = decodeToString(payload);

// decode payload to JSON
var ttnObj = decodeToJson(payload);

var deviceName = 'Device A';
var deviceType = 'thermostat';

// Result object with device/asset attributes/telemetry data
var result = {
   deviceName: deviceName,
   deviceType: deviceType,
   attributes: {
       model: 'Model A',
       serialNumber: 'SN111',
       integrationName: metadata['integrationName']
   },
   telemetry: {
       temperature: 42,
       humidity: 80,
       rawData: ttnObj
   }
};

/** Helper functions **/

function decodeToString(payload) {
   return String.fromCharCode.apply(String, payload);
}

function decodeToJson(payload) {
   // covert payload to string.
   var str = decodeToString(payload);

   // parse string to JSON
   var data = JSON.parse(str);
   return data;
}

return result;

**Comment by taraskuzyk** [comment]
I believe Thingsboard has an issue with nested JSONs. Try flattening the JSON and see if you still get the same result

**Comment by dajtxx** [comment]
Thanks for the suggestion.

Turns out we can't use PE anyway so have to find another way to get TTN messages into TB. The TB IoT Gateway is the next thing to try I suppose.

If data converters cannot handle the default json sent by TTN it's still a bug so I'm going to leave this open.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
