### ISSUE TITLE
Wrong config location in ThingsBoard Installation guide

### ISSUE THREAD

**Issue by benjaminfuchs** [thingsboard/thingsboard#2749]
Hi,
I faced a little issue following the step-by-step guide:
[Installing ThingsBoard on Raspberry Pi 3 Model B](https://thingsboard.io/docs/user-guide/install/rpi/)

I followed the guide and when calling the install script it failed:

```
 ===================================================
 :: ThingsBoard ::       (v2.4.3)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:443)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:217)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
        at org.postgresql.Driver.makeConnection(Driver.java:404)
        at org.postgresql.Driver.connect(Driver.java:272)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:60)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:161)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!
```

Looking into the install script:

_cat /usr/share/thingsboard/bin/install/install.sh:_
```
...
CONF_FOLDER=/usr/share/thingsboard/conf
...
```

It seems the config file is at the wrong location...
```
sudo cp /etc/thingsboard/conf/thingsboard.conf /usr/share/thingsboard/conf
```
... and so the fix was:
```
 ===================================================
 :: ThingsBoard ::       (v2.4.3)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts.sql
Loading system data...
Installation finished successfully!
ThingsBoard installed successfully!
```

System was a fresh installed raspberry pi:
```
pi@raspberrypi:~ $ uname --all
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

And thanks for the cool IOT dashboard 👍

**Comment by zbeacon** [comment]
Hi @benjaminfuchs 

Thank you for your interest in ThingsBoard IoT platform.
Problem caused by improper uninstall of previous version. If you want to use a clean installation, but you have already installed ThingsBoard, you need to run the following command: 
`sudo dpkg -P thingboard` 
this command will remove all information about the previous installation from the system, and run the installation command:
`sudo dpkg -i thingsboard-2.4.3.deb`

**Comment by cbisum** [comment]
@[benjaminfuchs](https://github.com/benjaminfuchs) . Thank you. It worked for me.
