### ISSUE TITLE
Cannot add aggregate nodes after recent upgrade to V.3

### ISSUE THREAD

**Issue by Itgvs** [thingsboard/thingsboard#2793]
Currently I'm testing Thingsboard on cloud.thingsboard.io instance for 2 weeks

After the upgrade to V.3, any new aggregate node I add doesn't work.
When I try copy/paste an already exiting (working) node, it starts fine, but if I alter any data inside the node it fail to start due to same issue.
In the lifecycle event for the failed node, it indicates that the node failed to start due to the below issue.

Error Code below

`org.thingsboard.rule.engine.api.TbNodeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "rootEntityId" (class org.thingsboard.rule.engine.analytics.latest.ParentEntitiesGroup), not marked as ignorable (one known property: "entityGroupId"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.thingsboard.rule.engine.analytics.incoming.TbSimpleAggMsgNodeConfiguration["parentEntitiesQuery"]->org.thingsboard.rule.engine.analytics.latest.ParentEntitiesGroup["rootEntityId"])
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:55)
	at org.thingsboard.rule.engine.analytics.incoming.TbSimpleAggMsgNode.init(TbSimpleAggMsgNode.java:107)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:138)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:68)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onUpdate(RuleNodeActorMessageProcessor.java:85)
	at org.thingsboard.server.actors.service.ComponentActor.onComponentLifecycleMsg(ComponentActor.java:112)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:61)
	at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "rootEntityId" (class org.thingsboard.rule.engine.analytics.latest.ParentEntitiesGroup), not marked as ignorable (one known property: "entityGroupId"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.thingsboard.rule.engine.analytics.incoming.TbSimpleAggMsgNodeConfiguration["parentEntitiesQuery"]->org.thingsboard.rule.engine.analytics.latest.ParentEntitiesGroup["rootEntityId"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4173)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2467)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2920)
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:53)
	... 20 more
`

**Comment by ashvayka** [comment]
Hi @Itgvs ! Thank you for reporting this. We are investigating this now.

**Comment by vvlladd28** [comment]
Fixed in the cloud. Thank you for reporting this.
