### ISSUE TITLE
Problema whit filtration of data in thingsboard

### ISSUE THREAD

**Issue by Game0nPT** [thingsboard/thingsboard#2800]
Hi, i am new at thingsboard and i am trying to do a project using a nodemcu+mpu6050. This device send the data to thingsboard but when i try to run a script this error ocurrers:
java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at org.thingsboard.server.service.script.AbstractJsInvokeService.invokeFunction(AbstractJsInvokeService.java:54)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeScriptAsync(RuleNodeJsScriptEngine.java:222)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeFilterAsync(RuleNodeJsScriptEngine.java:169)
	at org.thingsboard.rule.engine.filter.TbJsFilterNode.onMsg(TbJsFilterNode.java:55)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:111)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:79)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:45)
	at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:46)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ashvayka** [comment]
There is a debug option in the script editor. Please add your script and the incoming message .

**Comment by ashvayka** [comment]
Closing due to inactivity.
