### ISSUE TITLE
On Raspberry Pi 3 connection MQTT Ok but Data not commit

### ISSUE THREAD

**Issue by delattreb** [thingsboard/thingsboard#283]
After installation on Raspberry Pi 3 connection with MQTT ok, but telemetry topic don't take values.
Work on your demo server with the same code.
Installation on Raspberry Pi 3 with Postgres Database.

**Application log:**
2017-09-10 20:40:21,701 [http-nio-0.0.0.0-8080-exec-3] ERROR o.a.coyote.http11.Http11NioProtocol - Error reading request, ignored
2017-09-10 20:40:23,929 [http-nio-0.0.0.0-8080-exec-7] ERROR o.a.coyote.http11.Http11NioProtocol - Error reading request, ignored
2017-09-10 20:40:26,242 [http-nio-0.0.0.0-8080-exec-4] ERROR o.a.coyote.http11.Http11NioProtocol - Error reading request, ignored

**Comment by ashvayka** [comment]
The error you are logging is clearly related to http and not mqtt. Something is definitely not write but this is probably not mqtt based staff. please enable trace logging and attach the log.

**Comment by delattreb** [comment]
Thanks for your response Ashvayka !
This is an extract of Thingsboard.log:

2017-09-14 12:06:11,261 [http-nio-0.0.0.0-8080-exec-5] INFO  o.t.s.c.p.PluginWebSocketHandler - [0007d08d-d58b-4d7e-bdb9-5edf83c43cec][3] Session is started
2017-09-14 12:06:11,265 [http-nio-0.0.0.0-8080-exec-5] INFO  o.t.s.c.p.PluginWebSocketHandler - [3] Processing TextMessage payload=[{"tsSubCmd..], byteCount=156, last=true]
2017-09-14 12:06:11,272 [http-nio-0.0.0.0-8080-exec-5] INFO  o.t.s.c.p.PluginWebSocketHandler - [3] Processing TextMessage payload=[{"tsSubCmd..], byteCount=160, last=true]
2017-09-14 12:06:11,289 [http-nio-0.0.0.0-8080-exec-5] INFO  o.t.s.c.p.PluginWebSocketHandler - [3] Session is closed
2017-09-14 12:06:11,301 [Akka-system-plugin-dispatcher-42] WARN  o.t.s.c.p.PluginWebSocketHandler - [0007d08d-d58b-4d7e-bdb9-5edf83c43cec] Failed to find session by external id
2017-09-14 12:06:11,310 [Akka-system-plugin-dispatcher-42] WARN  o.t.s.c.p.PluginWebSocketHandler - [0007d08d-d58b-4d7e-bdb9-5edf83c43cec] Failed to find session by external id
2017-09-14 12:06:11,315 [http-nio-0.0.0.0-8080-exec-5] WARN  o.t.s.c.p.PluginWebSocketHandler - IO error
java.io.IOException: java.io.IOException: Relais brisé (pipe)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:315)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197)
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:102)
        at org.thingsboard.server.controller.plugin.PluginWebSocketHandler.handleTextMessage(PluginWebSocketHandler.java:80)
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:110)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:78)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:106)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:69)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Relais brisé (pipe)
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221)
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451)
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441)
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:97)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:494)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
        ... 30 common frames omitted
2017-09-14 12:06:11,317 [http-nio-0.0.0.0-8080-exec-5] WARN  o.t.s.c.p.PluginWebSocketHandler - [3] Failed to find session
2017-09-14 12:06:13,326 [http-nio-0.0.0.0-8080-exec-3] INFO  o.t.s.c.p.PluginWebSocketHandler - [cb31ab4d-60c1-45af-a208-823e9b85d225][4] Session is started
2017-09-14 12:06:13,329 [http-nio-0.0.0.0-8080-exec-10] INFO  o.t.s.c.p.PluginWebSocketHandler - [4] Processing TextMessage payload=[{"tsSubCmd..], byteCount=156, last=true]
2017-09-14 12:06:13,336 [http-nio-0.0.0.0-8080-exec-7] INFO  o.t.s.c.p.PluginWebSocketHandler - [4] Processing TextMessage payload=[{"tsSubCmd..], byteCount=160, last=true]
2017-09-14 12:06:13,346 [http-nio-0.0.0.0-8080-exec-7] INFO  o.t.s.c.p.PluginWebSocketHandler - [4] Session is closed
2017-09-14 12:06:13,348 [http-nio-0.0.0.0-8080-exec-7] WARN  o.t.s.c.p.PluginWebSocketHandler - IO error
java.io.IOException: java.io.IOException: Relais brisé (pipe)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:315)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197)
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:102)
        at org.thingsboard.server.controller.plugin.PluginWebSocketHandler.handleTextMessage(PluginWebSocketHandler.java:80)
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:110)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:78)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:106)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:69)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Relais brisé (pipe)
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221)
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451)
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441)
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:97)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:494)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
        ... 30 common frames omitted
2017-09-14 12:06:13,349 [http-nio-0.0.0.0-8080-exec-7] WARN  o.t.s.c.p.PluginWebSocketHandler - [4] Failed to find session
2017-09-14 12:06:13,366 [Akka-system-plugin-dispatcher-42] WARN  o.t.s.c.p.PluginWebSocketHandler - [cb31ab4d-60c1-45af-a208-823e9b85d225] Failed to find session by external id
2017-09-14 12:06:13,367 [Akka-system-plugin-dispatcher-42] WARN  o.t.s.c.p.PluginWebSocketHandler - [cb31ab4d-60c1-45af-a208-823e9b85d225] Failed to find session by external id
2017-09-14 12:06:15,434 [http-nio-0.0.0.0-8080-exec-6] INFO  o.t.s.c.p.PluginWebSocketHandler - [14f1a232-4691-4396-8bf7-b58c350d8c7d][5] Session is started
2017-09-14 12:06:15,438 [http-nio-0.0.0.0-8080-exec-6] INFO  o.t.s.c.p.PluginWebSocketHandler - [5] Processing TextMessage payload=[{"tsSubCmd..], byteCount=156, last=true]
2017-09-14 12:06:15,451 [http-nio-0.0.0.0-8080-exec-6] INFO  o.t.s.c.p.PluginWebSocketHandler - [5] Processing TextMessage payload=[{"tsSubCmd..], byteCount=160, last=true]
2017-09-14 12:06:15,460 [http-nio-0.0.0.0-8080-exec-6] INFO  o.t.s.c.p.PluginWebSocketHandler - [5] Session is closed

**Comment by ashvayka** [comment]
The websocket handler error may mean that you just closed the browser. We don't support MQTT over WS. Only MQTT over 1883 port (or secure one)

**Comment by delattreb** [comment]
Understand but my code work on your live demo server, but not on my raspberry...

**Comment by delattreb** [comment]
This is my code take on your website:
#include <PubSubClient.h>
#include <ESP8266WiFi.h>

#define WIFI_AP "XXX"
#define WIFI_PASSWORD "XXX"

#define TOKEN "8GxgPwehBShardbcmElk"

char thingsboardServer[] = "192.168.1.22";

WiFiClient wifiClient;

PubSubClient client(wifiClient);

int status = WL_IDLE_STATUS;
unsigned long lastSend;

void setup()
{
  Serial.begin(115200);
  delay(10);
  InitWiFi();
  client.setServer( thingsboardServer, 1883 );
  lastSend = 0;
}

void loop()
{
  if ( !client.connected() ) {
    reconnect();
  }

  if ( millis() - lastSend > 3000 ) { // Update and send only after 1 seconds
    getAndSendTemperatureAndHumidityData();
    lastSend = millis();
  }

  client.loop();
}

void getAndSendTemperatureAndHumidityData()
{

float t = 25.5;
float h = 23.1;

  String temperature = String(t);
  String humidity = String(h);

  // Prepare a JSON payload string
  String payload = "{";
  payload += "\"temperature\":"; payload += temperature; payload += ",";
  payload += "\"humidity\":"; payload += humidity;
  payload += "}";

  // Send payload
  char attributes[100];
  payload.toCharArray( attributes, 100 );
  client.publish( "v1/devices/me/telemetry", attributes );
  Serial.println( attributes );
}

void InitWiFi()
{
  Serial.println("Connecting to AP ...");
  // attempt to connect to WiFi network

  WiFi.begin(WIFI_AP, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("Connected to AP");
}


void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    status = WiFi.status();
    if ( status != WL_CONNECTED) {
      WiFi.begin(WIFI_AP, WIFI_PASSWORD);
      while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
      }
      Serial.println("Connected to AP");
    }
    Serial.print("Connecting to ThingsBoard node ...");
    // Attempt to connect (clientId, username, password)
    if ( client.connect("testdevice", TOKEN, NULL) ) {
      Serial.println( "[DONE]" );
    } else {
      Serial.print( "[FAILED] [ rc = " );
      Serial.print( client.state() );
      Serial.println( " : retrying in 5 seconds]" );
      // Wait 5 seconds before retrying
      delay( 5000 );
    }
  }
}

**Comment by delattreb** [comment]
After a new installation of ThingsBoard on Raspberry Pi 3b+ it work fine with the default database.
It is not the case with Postgres.

**Comment by ashvayka** [comment]
We can't reproduce this. Probably a local issue during installation
