### ISSUE TITLE
the command of  “mvn clean install -DskipTests“   does not work well

### ISSUE THREAD

**Issue by mybaby1** [thingsboard/thingsboard#284]
Hi，when I  execute the Command of  "mvn clean install -DskipTests"  at {TB_WORK_DIR},it do not  response at the step of "[WARNING] npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url".
Can anybody help me?
Thanks.

**Comment by volodymyr-babak** [comment]
how long it doesn't respond? 
have you tried manually execute command **git -c core.longpaths=true config --get remote.origin.url** ?

**Comment by mybaby1** [comment]
About three hours。
I manually execute command “git -c core.longpaths=true config --get remote.origin.url“，It returns "https://github.com/thingsboard/thingsboard.git"

**Comment by volodymyr-babak** [comment]
what is your PC hardware specification and OS?

**Comment by volodymyr-babak** [comment]
try execute with debug option. maybe this could provide you some ideas what is wrong:
**mvn clean install -DskipTests -X**

**Comment by mybaby1** [comment]
I do it as you  say, it returns the information as following:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:c
lean (default-clean) on project ui: Failed to clean project: Failed to delete D:
\Program Files\Git\bin\thingsboard\ui\target\node\node.exe -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project
ui: Failed to clean project: Failed to delete D:\Program Files\Git\bin\thingsboa
rd\ui\target\node\node.exe
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to clean proje
ct: Failed to delete D:\Program Files\Git\bin\thingsboard\ui\target\node\node.ex
e
        at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:215)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 20 more
Caused by: java.io.IOException: Failed to delete D:\Program Files\Git\bin\things
board\ui\target\node\node.exe
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:249)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:191)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:158)
        at org.apache.maven.plugin.clean.Cleaner.delete(Cleaner.java:117)
        at org.apache.maven.plugin.clean.CleanMojo.execute(CleanMojo.java:193)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]

**Comment by mybaby1** [comment]
Can I manually delete "D:
\Program Files\Git\bin\thingsboard\ui\target\node\node.exe"?
what is the cause of the error?

**Comment by mybaby1** [comment]
I  manually delete "D:
\Program Files\Git\bin\thingsboard\ui\target\node\node.exe"，then   execute “mvn clean install -DskipTests -X”，it has no response  at "[INFO] Running 'npm install' in D:\Program Files\Git\bin\thingsboard\ui".
Is it normal？or is there any problem?

**Comment by volodymyr-babak** [comment]
on my PC with 16GB RAM and Ubuntu OS it takes 5 minutes to compile UI. (npm install)
How long did  you wait ?

**Comment by mybaby1** [comment]
I wait about ten minutes,but it has some error as followsing :
[INFO] Running 'npm install' in D:\Program Files\Git\bin\thingsboard\ui
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_
modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
 fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})
[ERROR] npm ERR! Windows_NT 6.1.7601
[ERROR] npm ERR! argv "D:\\Program Files\\Git\\bin\\thingsboard\\ui\\target\\nod
e\\node.exe" "D:\\Program Files\\Git\\bin\\thingsboard\\ui\\target\\node\\node_m
odules\\npm\\bin\\npm-cli.js" "install"
[ERROR] npm ERR! node v6.9.1
[ERROR] npm ERR! npm  v3.10.8
[ERROR]
[ERROR] npm ERR! shasum check failed for C:\Users\lenovo\AppData\Local\Temp\npm-
2612-776851de\registry.npmjs.org\caniuse-db\-\caniuse-db-1.0.30000727.tgz
[ERROR] npm ERR! Expected: 4e22593089b0f35c1b2adcfc28234493a21a4b2e
[ERROR] npm ERR! Actual:   bbd5e22db52d689806218d34cd213d842d6709f3
[ERROR] npm ERR! From:     https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.
0.30000727.tgz
[ERROR] npm ERR!
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     D:\Program Files\Git\bin\thingsboard\ui\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  1.329 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.146 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  4.565 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  1.468 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  0.810 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [  9.205 s]
[INFO] Thingsboard Server Extensions API .................. SUCCESS [  1.696 s]
[INFO] Thingsboard Server Core Extensions ................. SUCCESS [  4.936 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.075 s]
[INFO] Thingsboard Server RabbitMQ Extension .............. SUCCESS [  3.175 s]
[INFO] Thingsboard Server REST API Call Extension ......... SUCCESS [  1.173 s]
[INFO] Thingsboard Server Kafka Extension ................. SUCCESS [  4.342 s]
[INFO] Thingsboard Server MQTT Extension .................. SUCCESS [  0.797 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.078 s]
[INFO] Thingsboard HTTP Transport ......................... SUCCESS [  0.819 s]
[INFO] Thingsboard COAP Transport ......................... SUCCESS [  1.507 s]
[INFO] Thingsboard MQTT Transport ......................... SUCCESS [  1.204 s]
[INFO] Thingsboard Server UI .............................. FAILURE [12:14 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:52 min
[INFO] Finished at: 2017-09-11T16:05:11+08:00
[INFO] Final Memory: 87M/763M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm
 (npm install) on project ui: Failed to run task: 'npm install' failed. (error c
ode 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.eirslett:frontend-maven-plugin:1.0:npm (npm install) on project ui: Fa
iled to run task
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:95)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: '
npm install' failed. (error code 1)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execu
te(NodeTaskExecutor.java:60)
        at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMo
jo.java:62)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:89)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :ui.

I do not know how to do now?

**Comment by volodymyr-babak** [comment]
run **npm install** manually and see resolve errors that this command produces

**Comment by mybaby1** [comment]
how  to run "npm install"? After I run it,it  Prompts  "npm is not an internal or external command, nor is it a program to run Batch file."

**Comment by volodymyr-babak** [comment]
I don't use windows and can't answer this question.
According to maven output you have issues while running **'npm install'**.
This should be fixed first, before running again maven build.
How to fix this in your case I don't know. 
Probably some windows expect is able to answer your question or google.

**Comment by mybaby1** [comment]
Thank u .Can u give me your contact way,like QQ or Weixin?Then I can ask u conveniently when meeting problems.My QQ number is 1405107585.

**Comment by alonsillo88** [comment]
Got the same issue and still can't fix it.

**Comment by mahmed14** [comment]
i got the same issue , so i run this on git bash terminal on windows. can you try to run it via git bash
