### ISSUE TITLE
the command of “mvn clean install -DskipTests -X“ does not work well

### ISSUE THREAD

**Issue by mybaby1** [thingsboard/thingsboard#285]
Hi,
When run it in command,it has some error as following:
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
.[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
[DEBUG] waiting....
.
[INFO] Build
Unzipping C:\Users\lenovo\.gradle\wrapper\dists\gradle-2.13-bin\4xsgxlfjcxvrea7a
kf941nvc7\gradle-2.13-bin.zip to C:\Users\lenovo\.gradle\wrapper\dists\gradle-2.
13-bin\4xsgxlfjcxvrea7akf941nvc7
[INFO]
[DEBUG] waiting....
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [ 10.184 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.144 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  5.555 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  1.550 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.068 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [  9.819 s]
[INFO] Thingsboard Server Extensions API .................. SUCCESS [  1.811 s]
[INFO] Thingsboard Server Core Extensions ................. SUCCESS [  5.294 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.118 s]
[INFO] Thingsboard Server RabbitMQ Extension .............. SUCCESS [  3.392 s]
[INFO] Thingsboard Server REST API Call Extension ......... SUCCESS [  1.401 s]
[INFO] Thingsboard Server Kafka Extension ................. SUCCESS [  5.933 s]
[INFO] Thingsboard Server MQTT Extension .................. SUCCESS [  1.028 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.168 s]
[INFO] Thingsboard HTTP Transport ......................... SUCCESS [  1.176 s]
[INFO] Thingsboard COAP Transport ......................... SUCCESS [  2.032 s]
[INFO] Thingsboard MQTT Transport ......................... SUCCESS [  1.509 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [04:53 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  0.943 s]
[INFO] ThingsBoard Server Application ..................... FAILURE [22:05 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27:52 min
[INFO] Finished at: 2017-09-11T17:24:37+08:00
[INFO] Final Memory: 92M/754M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (d
efault) on project application: org.gradle.tooling.GradleConnectionException: Co
uld not install Gradle distribution from 'https://services.gradle.org/distributi
ons/gradle-2.13-bin.zip'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project application:
org.gradle.tooling.GradleConnectionException: Could not install Gradle distribut
ion from 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: org.gradle.tooling.Grad
leConnectionException: Could not install Gradle distribution from 'https://servi
ces.gradle.org/distributions/gradle-2.13-bin.zip'.
        at org.fortasoft.maven.plugin.gradle.GradleMojo.execute(GradleMojo.java:
270)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :application

Can anybody help me?

**Comment by Hailing-Feng** [comment]
Had you solved this problem?

**Comment by caozhejun** [comment]
how to fix it ?

**Comment by imbaq123** [comment]
how to fix it?
