### ISSUE TITLE
[Question] How to use proxy in 'rest api call' node?

### ISSUE THREAD

**Issue by helguson** [thingsboard/thingsboard#2855]
**Component**
 * Rule Engine

**Context**
 * We tried to follow the [tutorial for reading a rest api](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/get-weather-using-rest-api-call/ ) to use a 'rest api call' node for calling a rest API.

**Environment**
- We use an [official docker image consisting of Thingsboard CE 2.4.3 and cassandra](https://hub.docker.com/r/thingsboard/tb-cassandra). 
- Our system is behind a proxy, i.e., we need to use that proxy when accessing external ressources like rest APIs.

**Description**
When we tried to use the 'rest api call' node, the connection was unsuccessful delivering a 'connection timed out' exception:

> io.netty.channel.ConnectTimeoutException: connection timed out: api.openweathermap.org/188.166.16.132:80
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

So we tried to setup a proxy configuration which was also unsuccessful leading us to the same 'connection timed out' exception:
- We tried by setting the environment variables _http_proxy_ and _https_proxy_.
- We tried by adding proxy settings via the _JAVA_OPTS_ variable which is used in  _/usr/bin/start-tb.sh_ to start Thingsboard.

> JAVA_OPTS=-Dhttp.nonProxyHosts=<...> -Dhttp.proxyHost=<...> -Dhttp.proxyPort=<...> -Dhttps.proxyHost=<...> -Dhttps.proxyPort=<...>

as well as

> JAVA_OPTS=-Dtb.proxy.system=true -Dtb.proxy.host=<...> -Dtb.proxy.port=<...>

as seen [here](https://youtu.be/2khu3RP0TGE?t=241).

**Question**
Is it possible to use the 'rest api call' node in combination with a proxy? If yes, how can we set it up?

**Comment by YevhenBondarenko** [comment]
Hello @helguson 
Thanks for your question. Now "rest api call" node can't use proxy, but we are planning to add it in the next release.

**Comment by YevhenBondarenko** [comment]
Hi @helguson 
We created a test build with proxy settings in "rest api call" node, you can test this build using the [link](https://drive.google.com/file/d/1cyVRwImmL2Tu-0ZbHWkxDX_J5PcFwkSQ/view?usp=sharing).
Please let us know if it helps you.

**Comment by eckbert** [comment]
Hi,
what I did for testing: 
- took the existing Dockerimage (thingsboard/tb with embedded HSQLDB) as Baseimage
- added followinf steps in the dockerfile:
   COPY thingsboard.deb /
   ARG DEBIAN_FRONTEND=noninteractive
   RUN apt-get install -y /thingsboard.deb  
So with the new image, I saw Ver 2.5.2 starting...
But saw no new settings inside "rest"-node nor changes in the behaviour... still getting the error
Perhabs the way I installed the build is wrong.  As I understand you right, there should occure proxy settings inside the nodes settings(detals) tab, Global/environment settings are not respected in backgrund

**Comment by eckbert** [comment]
Ok... I need to check the "Use simple client HTTP factory"
- but still getting the timeout
- I'll look into it a bit more, but the first attempts still fail

**Comment by eckbert** [comment]
After saving the rule chain (what I forgot in my previous attemt) I got a diffenrent Exception:

java.lang.IllegalStateException: Asynchronous execution requires TaskExecutor to be set
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createAsyncRequest(SimpleClientHttpRequestFactory.java:162)
	at org.springframework.http.client.support.AsyncHttpAccessor.createAsyncRequest(AsyncHttpAccessor.java:85)
	at org.springframework.web.client.AsyncRestTemplate.doExecute(AsyncRestTemplate.java:536)
	at org.springframework.web.client.AsyncRestTemplate.execute(AsyncRestTemplate.java:497)
	at org.springframework.web.client.AsyncRestTemplate.exchange(AsyncRestTemplate.java:434)
	at org.thingsboard.rule.engine.rest.TbHttpClient.processMessage(TbHttpClient.java:102)
	at org.thingsboard.rule.engine.rest.TbRestApiCallNode.onMsg(TbRestApiCallNode.java:61)

**Comment by YevhenBondarenko** [comment]
Hi @eckbert 
Thank you for testing. Now we fixed it and updated the [build](https://drive.google.com/file/d/1cyVRwImmL2Tu-0ZbHWkxDX_J5PcFwkSQ/view?usp=sharing).
Please let us know if it helps you.

**Comment by eckbert** [comment]
Hi Yevhen,
this looks good! Getting the expected response via proxy :) .  So far, so good, thank you.
If I have many Rest-Api-Nodes in my setup, it will be difficult to handle the proxy setting node by node, would it no be a good/better solution to respect a general/global setting or environment setting...
But for now, its fine.
Well done ;-)

**Comment by YevhenBondarenko** [comment]
Hi @eckbert ,
thank you, it is a good idea, I think we will add it in the next release.
