### ISSUE TITLE
[Bug]  Parser of translation not behaving correctly

### ISSUE THREAD

**Issue by gsouleres** [thingsboard/thingsboard#2911]
**Describe the bug**
After updating to Thingsboard 3.0PE, everything seems to work (except some custom widgets, as expected), except for parsing errors in translations, for example :
"Failed to parse source: {count, plural, 1 {1 alarme} other {# alarmes}} sélectionnées"
​
message: "Expected \"{\" but end of input found."
name: "SyntaxError"

The errors disappear if I just select the English language for my user.

I have another error that could be linked in thingsboard.log
2020-06-04 15:58:22,824 [ForkJoinPool-2-worker-51] ERROR o.h.hql.internal.ast.ErrorTracker - <AST>:0:0: unexpected AST node: {vector}
2020-06-04 15:58:22,826 [ForkJoinPool-2-worker-51] ERROR o.h.hql.internal.ast.ErrorTracker - <AST>:0:0: unexpected AST node: {vector}
2020-06-04 16:00:22,351 [ForkJoinPool-2-worker-58] ERROR o.h.hql.internal.ast.ErrorTracker - <AST>:0:0: unexpected AST node: {vector}
2020-06-04 16:00:22,353 [ForkJoinPool-2-worker-58] ERROR o.h.hql.internal.ast.ErrorTracker - <AST>:0:0: unexpected AST node: {vector}

I'll post full Stack Trace in next post

**Your Server Environment**
Server running Ubuntu 20.04 LTS
Thingsboard 3.0PE

**Your Client Environment**
Desktop
Windows 10
Firefox 76.0.1 

![TB_Translation_Issue](https://user-images.githubusercontent.com/25827381/83768258-d7830700-a67e-11ea-9bc9-a7b108b271d7.PNG)

**Comment by gsouleres** [comment]
2020-06-04 00:00:44,941 [ForkJoinPool-2-worker-21] ERROR o.h.hql.internal.ast.ErrorTracker - <AST>:0:0: unexpected AST node: {vector}
antlr.NoViableAltException: unexpected AST node: {vector}
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2155)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2075)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2072)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.logicalExpr(HqlSqlBaseWalker.java:2072)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.whereClause(HqlSqlBaseWalker.java:819)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.query(HqlSqlBaseWalker.java:613)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.selectStatement(HqlSqlBaseWalker.java:317)
        at org.hibernate.hql.internal.antlr.HqlSqlBaseWalker.statement(HqlSqlBaseWalker.java:265)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:272)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:192)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:144)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:113)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:73)
        at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:155)
        at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:604)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1394)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1562)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1530)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1578)
        at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:409)
        at com.sun.proxy.$Proxy292.getSingleResult(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:196)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:618)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy194.findAlarmCount(Unknown Source)
        at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao.findAlarmCount(JpaAlarmDao.java:138)
        at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao$$FastClassBySpringCGLIB$$fedeae2f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
        at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao$$EnhancerBySpringCGLIB$$7b16629a.findAlarmCount(<generated>)
        at org.thingsboard.server.dao.alarm.BaseAlarmService.findAlarmCounts(BaseAlarmService.java:322)
        at org.thingsboard.rule.engine.analytics.latest.alarm.TbAlarmsCountNode.countAlarms(TbAlarmsCountNode.java:135)
        at org.thingsboard.rule.engine.analytics.latest.alarm.TbAlarmsCountNode.lambda$doParentAggregations$0(TbAlarmsCountNode.java:105)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.thingsboard.rule.engine.analytics.latest.alarm.TbAlarmsCountNode.doParentAggregations(TbAlarmsCountNode.java:103)
        at org.thingsboard.rule.engine.analytics.latest.TbAbstractLatestNode.lambda$null$6(TbAbstractLatestNode.java:101)
        at java.util.Collections$SingletonList.forEach(Collections.java:4824)
        at org.thingsboard.rule.engine.analytics.latest.TbAbstractLatestNode.lambda$aggregate$7(TbAbstractLatestNode.java:100)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:1091)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by xalt7x** [comment]
I believe that this issue was solved several years ago.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
