### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sourabhkumarjha** [thingsboard/thingsboard#2947]
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: syntax error at or near "PROCEDURE"
Position: 21
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:68)
at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:175)
at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Unexpected error during ThingsBoard installation!
ThingsBoard DB installation failed!

why i get this msg can any one resolve this?

**Comment by Barnabe22** [comment]
Hi
i have the same problem. hoping someone to help us.

**Comment by yefimov-andrey** [comment]
Which version of ThingsBoard are you trying to install?

**Comment by sourabhkumarjha** [comment]
i'm using 2.5 version

**Comment by sourabhkumarjha** [comment]
Hello Barnabe, i got the solution. you need to have postgresql 12 on you machine.

**Comment by Barnabe22** [comment]
i'm still having the same error even with postgresql 12 on my machine.
How did you proceed sourabhkumarjha.
the version that i'm installing is 3.0.1

**Comment by sourabhkumarjha** [comment]
Hello Barnabe, first you need to uninstall postgresql. and than go with website and see how thay install : https://computingforgeeks.com/install-postgresql-12-on-ubuntu/

**Comment by Barnabe22** [comment]
Hello sourabhkumarjha.
this is what I did when you told to install postgresql-12:
- i uninstall postgresql
- i install postgresql-12
- and i proceed to the remaining steps of the thingsboard's installation
i'm still having the same error. therefore:
- I uninstall all packages I have installed for thingsboard's installation including postgresql-12.
Curiously, when I type the command below, 
psql -U postgres -d postgres -h 127.0.0.1 -W 
it works without any problem. I can see all dabases I've created.

I was wordering that when I would have postgresql and postgresql-12 uninstalled the command above shouldn't work. Am I right ?
can you clarify this point to me please?

**Comment by sourabhkumarjha** [comment]
[sudo] password for sourabh: 
postgres@sourabh-VirtualBox:~$ psql
psql (12.3 (Ubuntu 12.3-1.pgdg16.04+1))
Type "help" for help.

postgres=# 

did you get this?

**Comment by Barnabe22** [comment]
> [sudo] password for sourabh:
> postgres@sourabh-VirtualBox:~$ psql
> psql (12.3 (Ubuntu 12.3-1.pgdg16.04+1))
> Type "help" for help.
> 
> postgres=#
> 
> did you get this?

yes

**Comment by sourabhkumarjha** [comment]
and also you need to change postgres default password

**Comment by Barnabe22** [comment]
> and also you need to change postgres default password as postgres

yes I change it with \password

**Comment by Barnabe22** [comment]
I think that I have some thing different comparing to your display

[sudo] password for Barn: 
postgres@Barn:~$ psql
psql (12.3 (Ubuntu 12.3-1.pgdg18.04+1), server 10.13 (Ubuntu 10.13-1.pgdg18.04+1))
Type "help" for help.

postgres=#

**Comment by Barnabe22** [comment]
> I think that I have some thing different comparing to your display
> 
> [sudo] password for Barn:
> postgres@Barn:~$ psql
> psql (12.3 (Ubuntu 12.3-1.pgdg18.04+1), server 10.13 (Ubuntu 10.13-1.pgdg18.04+1))
> Type "help" for help.
> 
> postgres=#

server 10.13 (Ubuntu 10.13-1.pgdg18.04+1)

**Comment by CooL16** [comment]
To perform the installation/upgrade for thingsboard 2.5+ you have to have postgresql 11+.
To perform the upgrade of postgresql please follow this guide:
https://gist.github.com/ShvaykaD/1f0e6c1321a0a2b4b9f3b9ea9ab3e8d3

**Comment by Barnabe22** [comment]
sourabhkumarjha and CooL16 thank to both of you
I got thingsboard installed successfully. It was a postgresql's version problem as CooL16 has explained. this link https://gist.github.com/ShvaykaD/1f0e6c1321a0a2b4b9f3b9ea9ab3e8d3 was helpful
