### ISSUE TITLE
Error During AWS IoT Integration - Creating TLS factory failed!

### ISSUE THREAD

**Issue by TheoreticallyNick** [thingsboard/thingsboard#2982]
Hello, 

I recently was upgrade from version 2.4.3 to version 3.0.1

Before the upgrade, I had successfully integrated between my AWS IoT account and my Thingsboard PE with no issues, following the integration guide provided by thingsboard.

After the upgrade however, I received the following error. I tried to reset the certificates on the AWS side and create a new TB integrator, however, I am still unable to send mqtt messages between the two platforms.

`java.io.IOException: overrun, bytes = 924
        at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:92)
        at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.getKeySpec(CertPemClientCredentials.java:186)
        at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.readPrivateKeyFile(CertPemClientCredentials.java:173)
        at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.createAndInitKeyManagerFactory(CertPemClientCredentials.java:104)
        at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.initSslContext(CertPemClientCredentials.java:87)
        at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initSslContext(AbstractMqttIntegration.java:193)
        at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initClient(AbstractMqttIntegration.java:161)
        at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.init(BasicMqttIntegration.java:74)
        at org.thingsboard.integration.mqtt.aws.AwsIotIntegration.init(AwsIotIntegration.java:46)
        at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.getOrCreateThingsboardPlatformIntegration(DefaultPlatformIntegrationService.java:930)
        at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.lambda$createIntegration$1(DefaultPlatformIntegrationService.java:338)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

**Comment by TheoreticallyNick** [comment]
After looking through the log, 
I think this is related to the update made on May 8th, 2020. This update is linked below:
[https://github.com/thingsboard/thingsboard/commit/7e66fd269332482b8f53597ddca23e4e1197606e]

It looks like TB is trying to decrypt a private.key file that is already decrypted. In the UI, the Private Key password is empty (null).

Here's a snapshot of the UI
![image](https://user-images.githubusercontent.com/28991711/85207215-3b4f3600-b2f5-11ea-8e67-51bafb1c981e.png)

**Comment by Karabiy** [comment]
those is fixed for the next version already, wait for release

**Comment by Emerrv** [comment]
Having the same issue, could you find any solution or alternative to sending data?
I'm trying iot rules with a lambda, may be kinesis or sqs could work too.

**Comment by Karabiy** [comment]
for those reasons, you may set those and also use any kind of an external rule nodes. That should work with the kinesis. The fix will be for the next version, so that, please, stay in touch on for the new release.

**Comment by povi2946** [comment]
this is a critical issue. when can we expect the next release?
