### ISSUE TITLE
[Bug] Script Node - No compiled script found for scriptId

### ISSUE THREAD

**Issue by netvandal** [thingsboard/thingsboard#2994]
**Describe the bug**
Script node in Rule Chain fail with "No compiled script found for scriptId".

**Your Server Environment**
* demo.thingsboard.io
Working as expected

* own setup
  * Local install on debian server.
  * ThingsBoard 3.0.0
  * Debian 10
Fail with the the title error

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Ubuntu 20.04
* Browser Firefox
* Version 71.0.1

**To Reproduce**

1. Follow the turorial at https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms/
2. Enable debug on Script Node
3. Send some data

**Expected behavior**
Script run as expected and alarm is set or cleared

**Additional context**
I just followed the linked tutorial and no Alarm is triggered. So I started debugging and found the filter node failing and giving error when the Event type is "OUT"

The full error is this:
```
Java.lang.RuntimeException: No compiled script found for scriptId: [bdc4b1da-ecce-4b22-ae7d-58080cc386b6]!
	at org.ThingsBoard.server.service.script.AbstractJsInvokeService.invokeFunction(AbstractJsInvokeService.java:64)
	at org.ThingsBoard.server.service.script.RuleNodeJsScriptEngine.executeScriptAsync(RuleNodeJsScriptEngine.java:223)
	at org.ThingsBoard.server.service.script.RuleNodeJsScriptEngine.executeFilterAsync(RuleNodeJsScriptEngine.java:170)
	at org.ThingsBoard.rule.engine.filter.TbJsFilterNode.onMsg(TbJsFilterNode.java:55)
	at org.ThingsBoard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:107)
	at org.ThingsBoard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:85)
	at org.ThingsBoard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:48)
	at org.ThingsBoard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:46)
	at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

Same thing on demo.thingsboard.io work as expected. I'm missing something?
Thankyou

**Comment by netvandal** [comment]
Checkin lifecycle events i found this error too:

`
	java.lang.ClassNotFoundException: org.thingsboard.rule.engine.filter.TbJsFilterNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:121)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:53)
	at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:54)
	at akka.actor.Actor.aroundPreStart(Actor.scala:545)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:545)
	at akka.actor.AbstractActor.aroundPreStart(AbstractActor.scala:220)
	at akka.actor.ActorCell.create(ActorCell.scala:637)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

**Comment by netvandal** [comment]
I found that the proxy in front of thingsboard for some reason rename "thingsboard" to "ThingsBoard" and this 'cause the missing class error. creating rules without the proxy in front of TB make everything work as expected.

**Comment by amizer12** [comment]
Bumping this one and re-opening - i have exatcly the same issue running behind nginx.
All my functions are starting to fail due to this, everything works fine withot the proxy.
Anyone have a fix for this ?
Concidering how many instances re being run behind reverse proxy i think the app cod eshouls also hande this exception as well.
