### ISSUE TITLE
[Bug] Exception on RestClient.login 3.0.1PE

### ISSUE THREAD

**Issue by ignacioperezmoreno** [thingsboard/thingsboard#3021]
**Describe the bug**
When trying to login RestClient produces a exception

**Your Server Environment**
Thingsboard 3.0.1 PE, deployed on Amazon
  * Ubuntu 18

**Your Client Environment**

**Smartphone (please complete the following information):**
* Device: Huawei P20
* OS: Android 10
* Browser N/A
* Version N/A

**To Reproduce**
1. Create a blank Android App and Include repositories {
        maven {
            url "https://repo.thingsboard.io/artifactory/libs-release-public"
        } 
in Graddle project module
2. Include implementation('org.thingsboard:rest-client:3.0.1PE') on App module
3. Inside the onCreate method of the MainActivity:
Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try  {

                    restClient = new RestClient("http://zzzzzzzzzzzz:8080");

                    String loginResult = null;

                   try {
                        restClient.login("yyyyyyy@gmail.com", "xxxxxx");
                        Log.d(TAG,"restClient "+restClient.getUser().toString());
                    } catch (Exception e) {
                        loginResult = e.getMessage();
                    }

                } catch (Exception e) {
                    //TODO tratar el fallo de conexión
                    e.printStackTrace();
                }
            }
        });
        thread.start();

6-29 16:51:26.752 14341 14458 I QarthLog: [PatchStore] create disable file for com.fs.android.myapplication uid is 10165
06-29 16:51:26.753 14341 14458 E AndroidRuntime: FATAL EXCEPTION: Thread-2
06-29 16:51:26.753 14341 14458 E AndroidRuntime: Process: com.fs.android.myapplication, PID: 14341
06-29 16:51:26.753 14341 14458 E AndroidRuntime: java.lang.ExceptionInInitializerError
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.util.UriComponentsBuilder.fromUriString(UriComponentsBuilder.java:213)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.util.DefaultUriBuilderFactory$DefaultUriBuilder.initUriComponentsBuilder(DefaultUriBuilderFactory.java:243)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.util.DefaultUriBuilderFactory$DefaultUriBuilder.<init>(DefaultUriBuilderFactory.java:229)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.util.DefaultUriBuilderFactory.uriString(DefaultUriBuilderFactory.java:212)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.util.DefaultUriBuilderFactory.expand(DefaultUriBuilderFactory.java:205)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:673)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:449)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.thingsboard.rest.client.RestClient.login(RestClient.java:217)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at com.fs.android.myapplication.MainActivity$1.run(MainActivity.java:31)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:929)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 96
06-29 16:51:26.753 14341 14458 E AndroidRuntime: ^(([^:/?#]+):)?(//(([^@\[/?#]*)@)?(\[[\p{XDigit}:.]*[%\p{Alnum}]*]|[^\[/?#:]*)(:(\d*(?:\{[^/]+?})?))?)?([^?#]*)(\?([^#]*))?(#(.*))?
06-29 16:51:26.753 14341 14458 E AndroidRuntime:                                                                                                 ^
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at java.util.regex.Pattern.compileImpl(Native Method)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at java.util.regex.Pattern.compile(Pattern.java:1433)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at java.util.regex.Pattern.<init>(Pattern.java:1408)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at java.util.regex.Pattern.compile(Pattern.java:966)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	at org.springframework.web.util.UriComponentsBuilder.<clinit>(UriComponentsBuilder.java:92)
06-29 16:51:26.753 14341 14458 E AndroidRuntime: 	... 10 more
06-29 16:51:26.754  1205  2500 W ActivityTaskManager:   finishTopCrashedActivityLocked Force finishing activity com.fs.android.myapplication/.MainActivity
06-29 16:51:26.755  1205  2500 V ActivityTaskManager: positionChild stackId=0 to top.
06-29 16:51:26.755  1205 14483 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2

**Expected behavior**
The RestClient should login (or give an error if credentials are not correct).

**Additional context**
The same worked perfectly on v2.5.0

**Comment by StarostinVlad** [comment]
Faced the same problem in version 3.3.3. Were you able to solve it?And for some reason it gives an error if you add the maven repository to the project file, it builds only if you add the repository to settings.gradle.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
