### ISSUE TITLE
[Bug] TbActorMailbox can't start after TB3.0.1 upgrade. 

### ISSUE THREAD

**Issue by faithware** [thingsboard/thingsboard#3022]
Hello,
My thingsboard cluster installation is not working properly.
Here is the error logged.

020-06-29 15:47:04,060 [ForkJoinPool-12-worker-1] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 1, going to retry in attempts in 5000ms
2020-06-29 15:47:09,109 [ForkJoinPool-12-worker-2] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 2, going to retry in attempts in 10000ms
2020-06-29 15:47:19,147 [ForkJoinPool-12-worker-0] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 3, going to retry in attempts in 15000ms
2020-06-29 15:47:34,206 [ForkJoinPool-12-worker-1] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 4, going to retry in attempts in 20000ms
2020-06-29 15:47:54,279 [ForkJoinPool-12-worker-2] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 5, going to retry in attempts in 25000ms
2020-06-29 15:48:19,325 [ForkJoinPool-12-worker-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 6, going to retry in attempts in 30000ms
2020-06-29 15:48:49,366 [ForkJoinPool-12-worker-0] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 7, going to retry in attempts in 35000ms
2020-06-29 15:49:24,419 [ForkJoinPool-12-worker-1] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 8, going to retry in attempts in 40000ms
2020-06-29 15:50:04,463 [ForkJoinPool-12-worker-2] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 9, going to retry in attempts in 45000ms
2020-06-29 15:50:49,538 [ForkJoinPool-12-worker-3] INFO  o.t.server.actors.TbActorMailbox - [RULE_NODE|ac8ae4f0-8055-11e9-bece-776775873d25] Failed to init actor, attempt 10, going to stop attempts.
org.thingsboard.server.actors.TbActorException: Failed to init actor
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:71)
        at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:56)
        at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:61)
        at org.thingsboard.server.actors.TbActorMailbox.lambda$null$1(TbActorMailbox.java:77)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.thingsboard.rule.engine.metadata.TbGetSumIntoMetadata
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:121)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:53)
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:62)
        ... 8 common frames omitted

**Comment by Ultrazombie** [comment]
Closed due to inactive
