### ISSUE TITLE
Copy to view node not working [Bug] 

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#3050]
Hy,

I use thingsboard community 3.0.1, when I use the copy to view rule node, I get following exception:
Could you tell me what is the wrong?

java.lang.NullPointerException
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.attributeContainsInEntityView(TbCopyAttributesToEntityViewNode.java:145)
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.lambda$null$0(TbCopyAttributesToEntityViewNode.java:95)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.lambda$onMsg$2(TbCopyAttributesToEntityViewNode.java:95)
	at org.thingsboard.common.util.DonAsynchron$1.onSuccess(DonAsynchron.java:39)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1078)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:47)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1045)
	at org.thingsboard.common.util.DonAsynchron.withCallback(DonAsynchron.java:53)
	at org.thingsboard.common.util.DonAsynchron.withCallback(DonAsynchron.java:30)
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.onMsg(TbCopyAttributesToEntityViewNode.java:84)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:107)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:45)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:121)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Karabiy** [comment]
which is the exact input for the rule node? can you provide the screenshots of the debug events on those?

**Comment by JozsefGuyas** [comment]
I made my solution based on this example: 
https://thingsboard.io/docs/user-guide/entity-views/

this is my solution:
![rule](https://user-images.githubusercontent.com/40265672/86577043-ec9ece80-bf79-11ea-9553-c00fb9dfd6b5.PNG)
![rule1](https://user-images.githubusercontent.com/40265672/86577051-f1fc1900-bf79-11ea-8a48-8b3ef3f3306d.PNG)
![rule2](https://user-images.githubusercontent.com/40265672/86577062-f45e7300-bf79-11ea-8ae7-24393f7fb914.PNG)

**Comment by NicoWii4** [comment]
Hello, 
I am facing the same issue on version 3.3.1PE.
Is there any news about this issue ?

best regards

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
