### ISSUE TITLE
How to upgrade thingsboard from 3.0.0 to 3.0.1

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#3125]
Hi, I want to upgrade my thingsboard from 3.0.0 to 3.0.1 on windows.
I downloaded the thingsboard-windows-3.0.1.zip, and execute "upgrade.bat --fromVersion=3.0.0".But I failed.
The logs are below:
E:\IOT\thingsboard\install_package\thingsboard-3.0.1>upgrade.bat --fromVersion=3
.0.0
Upgrading thingsboard ...
 ===================================================
 :: ThingsBoard ::       (v3.0.1)
 ===================================================

Starting ThingsBoard Upgrade from version 3.0.0 ...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersi
on: 3.0.0
        at org.thingsboard.server.install.ThingsboardInstallService.performInsta
ll(ThingsboardInstallService.java:163)
        at org.thingsboard.server.ThingsboardInstallApplication.main(Thingsboard
InstallApplication.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLau
ncher.java:597)
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!

I don't know how to upgrade from 3.0.0 to 3.0.1.

**Comment by vvlladd28** [comment]
Hi @qwyinxiang 
You need to use the key in the command `--fromVersion=2.5.0`

**Comment by qwyinxiang** [comment]
I use `upgrade.bat --fromVersion=2.5.1`，but the logs seems I upgraded from 2.5.1 to 3.0.0, not 3.0.1.
and I can't start thingsboard service using "net start thingsboard".

E:\IOT\thingsboard\install_package\thingsboard-3.0.1>upgrade.bat --fromVersion=2.5.1
Upgrading thingsboard ...
 ===================================================
 :: ThingsBoard ::       (v3.0.1)
 ===================================================

Starting ThingsBoard Upgrade from version 2.5.1 ...
Upgrading ThingsBoard from version 2.5.1 to 3.0.0 ...
Updating system data...
Upgrade finished successfully!
ThingsBoard upgraded successfully!

E:\IOT\thingsboard\install_package\thingsboard-3.0.1>net start thingsboard
服务名无效。

请键入 NET HELPMSG 2185 以获得更多的帮助.


E:\IOT\thingsboard\install_package\thingsboard-3.0.1>

The install.log is below:
`2020-07-22 16:00:54,695 [main] INFO  o.s.d.r.c.RepositoryConfigurationExtensionSupport - Spring Data Redis - Could not safely identify store assignment for repository candidate interface org.thingsboard.server.dao.sql.device.DeviceRepository. If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository.
2020-07-22 16:00:54,696 [main] INFO  o.s.d.r.c.RepositoryConfigurationExtensionSupport - Spring Data Redis - Could not safely identify store assignment for repository candidate interface org.thingsboard.server.dao.sql.relation.RelationRepository. If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository.
2020-07-22 16:00:54,696 [main] INFO  o.s.d.r.c.RepositoryConfigurationExtensionSupport - Spring Data Redis - Could not safely identify store assignment for repository candidate interface org.thingsboard.server.dao.sql.rule.RuleNodeRepository. If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository.
2020-07-22 16:00:54,696 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 54ms. Found 0 Redis repository interfaces.
2020-07-22 16:00:55,037 [main] INFO  o.s.cloud.context.scope.GenericScope - BeanFactory id=40bef4b1-d308-384b-8c8e-ea28c33e6a8b
2020-07-22 16:00:55,509 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$dacd82b9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-22 16:00:55,995 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
2020-07-22 16:00:56,010 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-0.0.0.0-8080"]
2020-07-22 16:00:56,010 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2020-07-22 16:00:56,010 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.33]
2020-07-22 16:00:56,012 [main] INFO  o.a.c.core.AprLifecycleListener - Loaded APR based Apache Tomcat Native library [1.2.24] using APR version [1.7.0].
2020-07-22 16:00:56,012 [main] INFO  o.a.c.core.AprLifecycleListener - APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2020-07-22 16:00:56,012 [main] INFO  o.a.c.core.AprLifecycleListener - APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2020-07-22 16:00:56,015 [main] INFO  o.a.c.core.AprLifecycleListener - OpenSSL successfully initialized [OpenSSL 1.1.1g  21 Apr 2020]
2020-07-22 16:00:56,107 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2020-07-22 16:00:56,107 [main] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 3401 ms
2020-07-22 16:00:57,283 [main] INFO  o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [name: default]
2020-07-22 16:00:57,421 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.4.12.Final
2020-07-22 16:00:57,733 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-07-22 16:00:57,917 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2020-07-22 16:00:58,212 [main] INFO  com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (这个 org.postgresql.jdbc.PgConnection.getNetworkTimeout() 方法尚未被实作。)
2020-07-22 16:00:58,229 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2020-07-22 16:00:58,257 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2020-07-22 16:00:59,730 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2020-07-22 16:00:59,759 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
2020-07-22 16:01:01,590 [main] INFO  c.d.oss.driver.api.core.uuid.Uuids - PID obtained through native call to getpid(): 8844
2020-07-22 16:01:01,824 [main] WARN  o.s.b.a.j.JacksonAutoConfiguration$JodaDateTimeJacksonConfiguration - Auto-configuration of Jackson's Joda-Time integration is deprecated in favor of using java.time (JSR-310).
2020-07-22 16:01:01,999 [main] INFO  o.s.b.a.w.s.WelcomePageHandlerMapping - Adding welcome page: class path resource [public/index.html]
2020-07-22 16:01:02,483 [main] INFO  o.s.b.a.s.s.UserDetailsServiceAutoConfiguration - 

Using generated security password: a6baa86a-e234-4c49-a337-3765272771ab

2020-07-22 16:01:02,655 [main] INFO  o.s.s.web.DefaultSecurityFilterChain - Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@6cfbbff7, org.springframework.security.web.context.SecurityContextPersistenceFilter@3a401749, org.springframework.security.web.header.HeaderWriterFilter@50b0afd7, org.springframework.security.web.csrf.CsrfFilter@67d32a54, org.springframework.security.web.authentication.logout.LogoutFilter@2c829dbc, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@6f5e16cf, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@7f323b3a, org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter@30db5536, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@56846330, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@27e2287c, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@4640195a, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@45b32dfe, org.springframework.security.web.session.SessionManagementFilter@62765aec, org.springframework.security.web.access.ExceptionTranslationFilter@164642a4, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@17229821]
2020-07-22 16:01:03,159 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 2 endpoint(s) beneath base path '/actuator'
2020-07-22 16:01:03,203 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-0.0.0.0-8080"]
2020-07-22 16:01:03,229 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 8080 (http) with context path ''
2020-07-22 16:01:03,257 [main] INFO  o.t.s.i.ThingsboardInstallService - Starting ThingsBoard Upgrade from version 2.5.1 ...
2020-07-22 16:01:03,258 [main] INFO  o.t.s.i.ThingsboardInstallService - Upgrading ThingsBoard from version 2.5.1 to 3.0.0 ...
2020-07-22 16:01:03,258 [main] INFO  o.t.s.i.ThingsboardInstallService - Updating system data...
2020-07-22 16:01:04,850 [main] INFO  o.t.s.i.ThingsboardInstallService - Upgrade finished successfully!
2020-07-22 16:01:04,865 [sql-queue-ts-5-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2020-07-22 16:01:04,867 [sql-queue-attributes-3-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] Queue polling was interrupted
2020-07-22 16:01:04,867 [sql-queue-ts latest-4-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2020-07-22 16:01:04,869 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2020-07-22 16:01:04,883 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2020-07-22 16:01:04,892 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2020-07-22 16:01:04,894 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Pausing ProtocolHandler ["http-nio-0.0.0.0-8080"]
2020-07-22 16:01:04,989 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2020-07-22 16:01:04,993 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Stopping ProtocolHandler ["http-nio-0.0.0.0-8080"]
2020-07-22 16:01:04,996 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Destroying ProtocolHandler ["http-nio-0.0.0.0-8080"]
`

**Comment by qwyinxiang** [comment]
Should I have to execute install.bat first, then upgrade.bat?
I unzip the thingsboard-windows-3.0.1.zip, but not execute the install.bat.

**Comment by vvlladd28** [comment]
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#windows-301

**Comment by qwyinxiang** [comment]
My upgrade is success, Thank you very much.
