### ISSUE TITLE
Build issue with gradle-maven-plugin

### ISSUE THREAD

**Issue by obiwantotobi** [thingsboard/thingsboard#314]
I´ve tried to build version 1.3 from sources in Ubuntu 16.04 LTS and the build fails with the following error: 

> [INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [ 22.649 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.208 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [ 11.763 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.735 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.469 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 23.511 s]
[INFO] Thingsboard Server Extensions API .................. SUCCESS [  4.050 s]
[INFO] Thingsboard Server Core Extensions ................. SUCCESS [ 11.994 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.259 s]
[INFO] Thingsboard Server RabbitMQ Extension .............. SUCCESS [ 10.605 s]
[INFO] Thingsboard Server REST API Call Extension ......... SUCCESS [  3.941 s]
[INFO] Thingsboard Server Kafka Extension ................. SUCCESS [ 18.632 s]
[INFO] Thingsboard Server MQTT Extension .................. SUCCESS [  2.912 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.184 s]
[INFO] Thingsboard HTTP Transport ......................... SUCCESS [  2.646 s]
[INFO] Thingsboard COAP Transport ......................... SUCCESS [  4.815 s]
[INFO] Thingsboard MQTT Transport ......................... SUCCESS [  3.254 s]
[INFO] Thingsboard Server UI .............................. SUCCESS [05:19 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  1.573 s]
[INFO] ThingsBoard Server Application ..................... FAILURE [16:51 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24:20 min
[INFO] Finished at: 2017-09-28T23:25:54-03:00
[INFO] Final Memory: 88M/1979M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project application: org.gradle.tooling.GradleConnectionException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.8:invoke (default) on project application: org.gradle.tooling.GradleConnectionException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: org.gradle.tooling.GradleConnectionException: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'.
        at org.fortasoft.maven.plugin.gradle.GradleMojo.execute(GradleMojo.java:270)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :application
<

Tried rmoving the .gradle reference but the issue persisted.

Any idea would help.

**Comment by ikulikov** [comment]
Closing due to an inactivity.
