### ISSUE TITLE
Creating TLS factory failed![Bug] 

### ISSUE THREAD

**Issue by Emerrv** [thingsboard/thingsboard#3159]
After upgrade to versión 3.0.1 aws iot integration stopped working.

I have thingsboard PE 3.0.1 installed in ubuntu server 18.04 LTS

Error:

java.lang.RuntimeException: Creating TLS factory failed!
	at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.initSslContext(CertPemClientCredentials.java:93)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initSslContext(AbstractMqttIntegration.java:193)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initClient(AbstractMqttIntegration.java:161)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.init(BasicMqttIntegration.java:74)
	at org.thingsboard.integration.mqtt.aws.AwsIotIntegration.init(AwsIotIntegration.java:46)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.getOrCreateThingsboardPlatformIntegration(DefaultPlatformIntegrationService.java:930)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.lambda$createIntegration$1(DefaultPlatformIntegrationService.java:338)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.IOException: overrun, bytes = 924
	at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:92)
	at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.getKeySpec(CertPemClientCredentials.java:186)
	at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.readPrivateKeyFile(CertPemClientCredentials.java:173)
	at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.createAndInitKeyManagerFactory(CertPemClientCredentials.java:104)
	at org.thingsboard.integration.mqtt.credentials.CertPemClientCredentials.initSslContext(CertPemClientCredentials.java:87)
	... 14 more

**Comment by CooL16** [comment]
This issue is being in our backlog. 
We are planning to make the new release during the first week of August

**Comment by Heavenclone** [comment]
> This issue is being in our backlog.
> We are planning to make the new release during the first week of August

Hello, can we get an update on this upcoming release??? 
This is a significant bug, we haven't been able to get data in from our AWS services in over two weeks because of this. At this point, we're even reconsidering using thingsboard PE to display data to customers...
