### ISSUE TITLE
How to run unit test? thingsboard2.4.3

### ISSUE THREAD

**Issue by waytai** [thingsboard/thingsboard#3177]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
How to run unit test for thingsboard2.4.3

**Environment**

 * OS:  name and version
 * ThingsBoard: 2.4.3
 * Java 1.8.0_251
* Idea

when run unit test

2020-07-28 13:37:54,704 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
java.sql.SQLInvalidAuthorizationSpecException: invalid authorization specification - not found: SA
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)

**Comment by Ultrazombie** [comment]
closed, due to inactivity
