### ISSUE TITLE
Exceptions - Error

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3194]
Hi, 

What is "Deque full" error related to? What is the direct cause? 

Thanks

**Comment by fjpa121197** [comment]
Looking at the logs, I see the following error in TB logs:

```
2020-08-01 01:17:06,946 [ForkJoinPool-12-worker-0] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
java.lang.IllegalStateException: Deque full
	at java.util.concurrent.LinkedBlockingDeque.addLast(LinkedBlockingDeque.java:335)
	at java.util.concurrent.LinkedBlockingDeque.add(LinkedBlockingDeque.java:633)
	at org.thingsboard.server.dao.util.AbstractBufferedRateExecutor.submit(AbstractBufferedRateExecutor.java:109)
	at org.thingsboard.server.dao.nosql.CassandraAbstractDao.executeAsync(CassandraAbstractDao.java:93)
	at org.thingsboard.server.dao.nosql.CassandraAbstractDao.executeAsyncWrite(CassandraAbstractDao.java:76)
	at org.thingsboard.server.dao.timeseries.CassandraBaseTimeseriesDao.savePartition(CassandraBaseTimeseriesDao.java:434)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.saveAndRegisterFutures(BaseTimeseriesService.java:153)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.save(BaseTimeseriesService.java:144)
	at org.thingsboard.server.service.telemetry.DefaultTelemetrySubscriptionService.saveAndNotify(DefaultTelemetrySubscriptionService.java:124)
	at org.thingsboard.rule.engine.telemetry.TbMsgTimeseriesNode.onMsg(TbMsgTimeseriesNode.java:89)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:107)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:45)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:121)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Karabiy** [comment]
for those reasons you can refer to this thread
#1515

**Comment by fjpa121197** [comment]
I have a monitoring tool that checks the availability of the database and it doesn't show any time that the node was down. Also, how can I increase this queue size? Is there a parameters in a configuration file or is related to a resource?

**Comment by fjpa121197** [comment]
@ashvayka @Karabiy any comments on what parameter to change to overcome this error?

**Comment by Ultrazombie** [comment]
Deque full error has been encountered in versions before 3.3.x if I'm not mistaken.
It was solved by raising cassandra.query.concurrent_limit. This error has not occurred for a long time on recent versions of ThingsBoard.
