### ISSUE TITLE
[Bug] Changing TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_QUEUE_PER_WS_SESSION to "0"

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3212]
**Describe the bug**
Hi, while changing parameters of the conf file, I change TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_QUEUE_PER_WS_SESSION to "0", as the description says that setting to 0 disables that limitation. 

I then try in the TB UI to see the latest telemetry from a device (even from the ones loaded from demo) and I got the following error in the UI: WebSocket Error: error code - 1011. I checked in TB log files and I got the following error:

```
2020-08-03 08:17:31,335 [http-nio-0.0.0.0-8080-exec-1] ERROR o.s.w.s.h.ExceptionWebSocketHandlerDecorator - Closing session due to exception for StandardWebSocketSession[id=6f6c695b-30c9-1e98-09c3-72f012888576, uri=ws://cseetprj04.essex.ac.uk:8080/api/ws/plugins/telemetry?token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiJjNjhhMWQ0MC1kNTU4LTExZWEtYmRkNy1kOWZkOTZhNDM3NjAiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiYzYxODQ4YTAtZDU1OC0xMWVhLWJkZDctZDlmZDk2YTQzNzYwIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNTk2NDM5MDA1LCJleHAiOjE1OTY0NDgwMDV9.6MP7MEHjYy_Y_Fi79qM-izPo-n2lcIlmpWMto4CTFcHMHrnz975rNX4XIiD39SwlPnNYg5jMTtLiEFeOH3UC9w]
java.lang.IllegalArgumentException: Reason must not be empty
	at org.springframework.util.Assert.hasText(Assert.java:284)
	at org.springframework.web.socket.CloseStatus.withReason(CloseStatus.java:193)
	at org.thingsboard.server.controller.plugin.TbWebSocketHandler.afterConnectionEstablished(TbWebSocketHandler.java:131)
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionEstablished(WebSocketHandlerDecorator.java:70)
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionEstablished(LoggingWebSocketHandlerDecorator.java:48)
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.afterConnectionEstablished(ExceptionWebSocketHandlerDecorator.java:48)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onOpen(StandardWebSocketHandlerAdapter.java:104)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:133)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:914)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
However, when I change the value (instead of putting a 0, I up this limit to another number), everything went normal and I didnt get the error anymore.

**Your Server Environment**
* own setup
  * ThingsBoard Version: thingsboard-3.0.1
  * OS Name and Version: Ubuntu 20.04 LTS

**To Reproduce**
1. Install Thingsboard locally (Using Hybrd PostgreSQL + Cassandra) 
2. Before starting, change TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_QUEUE_PER_WS_SESSION to "0"
3. Start TB service and go to devices and check their latest telemetry section.
4. See error WebSocket Error: error code - 1011 appear in red box

**Comment by trypzz** [comment]
Hello, @fjpa121197 
confused with `TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_QUEUE_PER_WS_SESSION `parameter with and `TB_SERVER_WS_TENANT_RATE_LIMITS_MAX_SESSIONS_PER_PUBLIC_USER`

Please check configuration documentation: https://thingsboard.io/docs/user-guide/install/config/
