### ISSUE TITLE
[Question] WARNING Record value is out of bounds

### ISSUE THREAD

**Issue by fjpa121197** [thingsboard/thingsboard#3299]
Im having the following warning after a period of time of sending constant data (7.5k devices sending data every 10 seconds). Here is the log section:
```
2020-08-13 09:40:03,762 [Thingsboard-io-3] WARN  c.d.o.d.i.core.metrics.HdrReservoir - [Thingsboard.cql-requests] Recorded value (19163326012) is out of bounds, discarding
```
Followed by this error:

```
2020-08-13 09:40:08,202 [cassandra-callback-10-thread-425] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT20S
	at com.datastax.oss.driver.internal.core.cql.CqlRequestHandler.lambda$scheduleTimeout$1(CqlRequestHandler.java:224)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

What is this warning related to?

**Comment by Ultrazombie** [comment]
Closed, as not active.
