### ISSUE TITLE
Build error in the ui module

### ISSUE THREAD

**Issue by hguomin** [thingsboard/thingsboard#331]
Hi team,

Today I pull the latest code from tb repo and build with command "mvn clean install", it tell me that BUILD SUCCESS and then I run TB and visit http://localhost:8080 but get follow result in the browser:
""""""""""""
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Oct 07 00:54:02 CST 2017
There was an unexpected error (type=Not Found, status=404).
No message available
"""""""""""""""

I check TB log, it says:
"""""""""""""""""
2017-10-07 00:54:01.073 ERROR 696 --- [0.0-8080-exec-4] org.apache.velocity                      : ResourceManager : unable to find resource 'error.vm' in any resource loader.
2017-10-07 00:54:01.085 ERROR 696 --- [0.0-8080-exec-4] org.apache.velocity                      : ResourceManager : unable to find resource 'error.html.vm' in any resource loader.
"""""""""""""""

Then I review the build process and found following error message when building the ui module
""""""""""""""""""""""""""""""""""""""""
[INFO] ERROR in ./src/scss/main.scss
[INFO] Module build failed: Error: dlopen(/Documents/Projects/thingsboard/ui/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
[INFO] 	/Documents/Projects/thingsboard/ui/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1458176 which is past end of file 173616
[INFO] 	/Documents/Projects/thingsboard/ui/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1458176 which is past end of file 173616
[INFO]     at Error (native)
[INFO]     at Object.Module._extensions..node (module.js:597:18)
[INFO]     at Module.load (module.js:487:32)
[INFO]     at tryModuleLoad (module.js:446:12)
[INFO]     at Function.Module._load (module.js:438:3)
[INFO]     at Module.require (module.js:497:17)
[INFO]     at require (internal/module.js:20:19)
[INFO]     at module.exports (/Documents/Projects/thingsboard/ui/node_modules/node-sass/lib/binding.js:19:10)
[INFO]     at Object.<anonymous> (/Documents/Projects/thingsboard/ui/node_modules/node-sass/lib/index.js:14:35)
[INFO]     at Module._compile (module.js:570:32)
"""""""""""""""""""""""""""""""

Any idea to help me solve this issue? thanks

**Comment by hguomin** [comment]
Run the following command in ui module to rebuild the node-sass module fixed the issue:
nom rebuild node-sass

refer to: https://github.com/sass/node-sass/issues/1387
