### ISSUE TITLE
[Bug] Java rest client can't parse json

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard#3320]
Hi!

I use thingsboard 3.1 CE and java rest client 2.5.0. When I getSharedAttributes I get following error:

Exception in thread "pool-3-thread-1" java.lang.RuntimeException: Can't parse value: {"zoneIndex":1,"saturday":true,"enabled":true,"monday":true,"thuesday":true,"wednesday":true,"thursday":true,"friday":true,"sunday":true,"mondayStartTime":"10:10","thuesdayStartTime":"10:10","wednesdayStartTime":"10:10","thursdayStartTime":"10:10","fridayStartTime":"10:10","saturdayStartTime":"10:10","sundayStartTime":"10:10","timeoutThuesday":5,"timeoutWednesday":5,"timeoutThursday":5,"timeoutFriday":5,"timeoutMonday":5,"timeoutSaturday":5,"timeoutSunday":5}
	at org.thingsboard.rest.client.utils.RestJsonConverter.parseValue(RestJsonConverter.java:84)
	at org.thingsboard.rest.client.utils.RestJsonConverter.lambda$toAttributes$0(RestJsonConverter.java:47)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.thingsboard.rest.client.utils.RestJsonConverter.toAttributes(RestJsonConverter.java:50)
	at org.thingsboard.rest.client.RestClient.getAttributesByScope(RestClient.java:1601)
	at com.gj.manual.Thingsboard$AttributesGetterTask.lambda$run$0(Thingsboard.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at com.gj.manual.Thingsboard$AttributesGetterTask.run(Thingsboard.java:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

The java rest client can handle the json format? How Can I solve this problem? Could you help me?

**Comment by Karabiy** [comment]
the JSON seems to be an okay. can you describe the exact request you are being executing for the REST API, or please specify the exact way you are sending those

**Comment by JozsefGuyas** [comment]
So I would like to get a json type device share attribute with java rest client. 
This method throw the mentioned exception.
client.getAttributesByScope(tbDevice.getCredentials().getDeviceID(), DataConstants.SHARED_SCOPE, key)

Can i get a json object from device attribute with java rest client?

**Comment by sumin-denys** [comment]
Hi @JozsefGuyas,

Thank you for your report! 
This was an issue in our Java Rest client 2.5.0. in the latest version of the Rest client, this issue was resolved.  
I am closing this issue.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).
If you have any further questions, please feel free to create a new issue or reopen this one.
