### ISSUE TITLE
[Bug] update error

### ISSUE THREAD

**Issue by Alentus** [thingsboard/thingsboard#3322]
I have emty field on table device_credentials and i have this log
```bash
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromV                                                                    ersion=3.0.1
 ===================================================
 :: ThingsBoard ::       (v3.1.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.0.1 ...
Upgrading ThingsBoard from version 3.0.1 to 3.1.0 ...
Updating schema ...
Optimizing alarm relations...
Alarm relations optimized.
Updating table admin_settings.
Table admin_settings column id updated!
Table admin_settings updated.
Updating table alarm.
Table alarm column id updated!
Table alarm column originator_id updated!
Table alarm column tenant_id updated!
Table alarm updated.
Updating table asset.
Table asset column id updated!
Table asset column customer_id updated!
Table asset column tenant_id updated!
Table asset updated.
Updating table audit_log.
Table audit_log column id updated!
Table audit_log column customer_id updated!
Table audit_log column tenant_id updated!
Table audit_log column entity_id updated!
Table audit_log column user_id updated!
Table audit_log updated.
Updating table attribute_kv.
Table attribute_kv column entity_id updated!
Table attribute_kv updated.
Updating table component_descriptor.
Table component_descriptor column id updated!
Table component_descriptor updated.
Updating table customer.
Table customer column id updated!
Table customer column tenant_id updated!
Table customer updated.
Updating table dashboard.
Table dashboard column id updated!
Table dashboard column tenant_id updated!
Table dashboard updated.
Updating table device.
Table device column id updated!
Table device column customer_id updated!
Table device column tenant_id updated!
Table device updated.
Updating table device_credentials.
Failed updating schema!!!
org.postgresql.util.PSQLException: ОШИБКА: неверный синтаксис для типа uuid: "--                                                                    1--"
  Где: функция PL/pgSQL to_uuid(character varying), строка 3, оператор присваива                                                                    ние
SQL-оператор: "UPDATE device_credentials SET device_id = to_uuid(old_device_id)                                                                     WHERE old_device_id is not null;"
функция PL/pgSQL column_type_to_uuid(character varying,character varying), строк                                                                    а 5, оператор EXECUTE
SQL-оператор: "SELECT column_type_to_uuid(table_name, column_device_id)"
функция PL/pgSQL update_device_credentials(), строка 23, оператор PERFORM
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryEx                                                                    ecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutor                                                                    Impl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.ja                                                                    va:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303                                                                    )
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289                                                                    )
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266                                                                    )
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgr                                                                    adeDatabase(SqlDatabaseUpgradeService.java:264)
        at org.thingsboard.server.install.ThingsboardInstallService.performInsta                                                                    ll(ThingsboardInstallService.java:173)
        at org.thingsboard.server.ThingsboardInstallApplication.main(Thingsboard                                                                    InstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                    java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                    sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner                                                                    .java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLau                                                                    ncher.java:597)
Updating data from version 3.0.1 to 3.1.0 ...
Unexpected error during ThingsBoard installation!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extra                                                                    ct ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarE                                                                    xception: could not extract ResultSet
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHiberna                                                                    teAccessException(HibernateJpaDialect.java:281)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExcep                                                                    tionIfPossible(HibernateJpaDialect.java:255)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translat                                                                    eExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator                                                                    .translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(                                                                    DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterc                                                                    eptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(                                                                    ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPos                                                                    tProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetada                                                                    taPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(                                                                    ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invok                                                                    e(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(                                                                    ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynami                                                                    cAopProxy.java:212)
        at com.sun.proxy.$Proxy153.findByRegionNextPage(Unknown Source)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantDao.findTenantsByRegio                                                                    n(JpaTenantDao.java:56)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$FastClassBySpring                                                                    CGLIB$$bb4581c1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:2                                                                    18)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterce                                                                    ptor.intercept(CglibAopProxy.java:687)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$EnhancerBySpringC                                                                    GLIB$$8830d7bc.findTenantsByRegion(<generated>)
        at org.thingsboard.server.dao.tenant.TenantServiceImpl.findTenants(Tenan                                                                    tServiceImpl.java:120)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateServic                                                                    e$2.findEntities(DefaultDataUpdateService.java:115)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateServic                                                                    e$2.findEntities(DefaultDataUpdateService.java:111)
        at org.thingsboard.server.service.install.update.PaginatedUpdater.update                                                                    Entities(PaginatedUpdater.java:31)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateServic                                                                    e.updateData(DefaultDataUpdateService.java:82)
        at org.thingsboard.server.install.ThingsboardInstallService.performInsta                                                                    ll(ThingsboardInstallService.java:174)
        at org.thingsboard.server.ThingsboardInstallApplication.main(Thingsboard                                                                    InstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                    java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                    sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner                                                                    .java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLau                                                                    ncher.java:597)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract Result                                                                    Set
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(S                                                                    QLStateConversionDelegate.java:103)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.conver                                                                    t(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlException                                                                    Helper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlException                                                                    Helper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(Result                                                                    SetReturnImpl.java:67)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2292)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
        at org.hibernate.loader.Loader.doQuery(Loader.java:953)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Lo                                                                    ader.java:354)
        at org.hibernate.loader.Loader.doList(Loader.java:2838)
        at org.hibernate.loader.Loader.doList(Loader.java:2820)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2652)
        at org.hibernate.loader.Loader.list(Loader.java:2647)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslat                                                                    orImpl.java:396)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.                                                                    java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1404)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractPro                                                                    ducedQuery.java:1562)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProdu                                                                    cedQuery.java:1530)
        at org.hibernate.query.Query.getResultList(Query.java:165)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                    java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                    sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryI                                                                    nvocationHandler.invoke(SharedEntityManagerCreator.java:409)
        at com.sun.proxy.$Proxy210.getResultList(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$Paged                                                                    Execution.doExecute(JpaQueryExecution.java:177)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execu                                                                    te(JpaQueryExecution.java:88)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExec                                                                    ute(AbstractJpaQuery.java:154)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execut                                                                    e(AbstractJpaQuery.java:142)
        at org.springframework.data.repository.core.support.RepositoryFactorySup                                                                    port$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:618)
        at org.springframework.data.repository.core.support.RepositoryFactorySup                                                                    port$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(                                                                    ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.                                                                    invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.in                                                                    voke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(                                                                    ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterc                                                                    eptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        ... 27 common frames omitted
Caused by: org.postgresql.util.PSQLException: ОШИБКА: столбец tenantenti0_.creat                                                                    ed_time не существует
  Позиция: 36
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryEx                                                                    ecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutor                                                                    Impl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.ja                                                                    va:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedSt                                                                    atement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatem                                                                    ent.java:116)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPrepa                                                                    redStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(Hika                                                                    riProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(Result                                                                    SetReturnImpl.java:57)
        ... 60 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!

```
i fixed table
when i try start update scrip again i have
```
sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.0.1                                                         ===================================================
 :: ThingsBoard ::       (v3.1.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.0.1 ...
Upgrading ThingsBoard from version 3.0.1 to 3.1.0 ...
Updating schema ...
Optimizing alarm relations...
Failed updating schema!!!
org.postgresql.util.PSQLException: ОШИБКА: оператор не существует: uuid = character varying
  Подсказка: Оператор с данными именем и типами аргументов не найден. Возможно, вам следует добавить                                                 явные приведения типов.
  Позиция: 136
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455                                                )
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatab                                                aseUpgradeService.java:257)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstal                                                lService.java:173)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.j                                                ava:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Updating data from version 3.0.1 to 3.1.0 ...
Unexpected error during ThingsBoard installation!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n                                                /a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(Hi                                                bernateJpaDialect.java:281)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(Hiber                                                nateJpaDialect.java:255)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible                                                (AbstractEntityManagerFactoryBean.java:528)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionI                                                fPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java                                                :242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(Persist                                                enceExceptionTranslationInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvo                                                cation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMetho                                                dMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvo                                                cation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationIn                                                terceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvo                                                cation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy153.findByRegionNextPage(Unknown Source)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantDao.findTenantsByRegion(JpaTenantDao.java:                                                56)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$FastClassBySpringCGLIB$$bb4581c1.invo                                                ke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(Cglib                                                AopProxy.java:687)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$EnhancerBySpringCGLIB$$fde38fb8.findT                                                enantsByRegion(<generated>)
        at org.thingsboard.server.dao.tenant.TenantServiceImpl.findTenants(TenantServiceImpl.java:12                                                0)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService$2.findEntities(Def                                                aultDataUpdateService.java:115)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService$2.findEntities(Def                                                aultDataUpdateService.java:111)
        at org.thingsboard.server.service.install.update.PaginatedUpdater.updateEntities(PaginatedUp                                                dater.java:31)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(Default                                                DataUpdateService.java:82)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstal                                                lService.java:174)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.j                                                ava:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDel                                                egate.java:103)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExcepti                                                onConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:6                                                7)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2292)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
        at org.hibernate.loader.Loader.doQuery(Loader.java:953)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
        at org.hibernate.loader.Loader.doList(Loader.java:2838)
        at org.hibernate.loader.Loader.doList(Loader.java:2820)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2652)
        at org.hibernate.loader.Loader.list(Loader.java:2647)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1404)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1562                                                )
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1530)
        at org.hibernate.query.Query.getResultList(Query.java:165)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.inv                                                oke(SharedEntityManagerCreator.java:409)
        at com.sun.proxy.$Proxy210.getResultList(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(                                                JpaQueryExecution.java:177)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution                                                .java:88)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery                                                .java:154)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.j                                                ava:142)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMe                                                thodInterceptor.doInvoke(RepositoryFactorySupport.java:618)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMe                                                thodInterceptor.invoke(RepositoryFactorySupport.java:605)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvo                                                cation.java:186)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransact                                                ion(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInte                                                rceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvo                                                cation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(Persist                                                enceExceptionTranslationInterceptor.java:139)
        ... 27 common frames omitted
Caused by: org.postgresql.util.PSQLException: ОШИБКА: столбец tenantenti0_.created_time не существуе                                                т
  Позиция: 36
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455                                                )
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52                                                )
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedState                                                ment.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:5                                                7)
        ... 60 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
```
I think this is because the uuid have already  been created.
can you add a check of the passed installation steps?
I'll apply the backups tomorrow morning and try again.

**Comment by trypzz** [comment]
Hello, @Alentus 

We are sorry for the delayed reply. Can I help you now or I can close this issue?

**Comment by Alentus** [comment]
> Hello, @Alentus
> 
> We are sorry for the delayed reply. Can I help you now or I can close this issue?
