### ISSUE TITLE
[Question] win10 compile error

### ISSUE THREAD

**Issue by waytai** [thingsboard/thingsboard#3330]
**Component**

 * win10 idea
 * thingsboard release-3.1
* nodeVersion: v12.14.0 npmVersion:6.13.4 

**Description**
Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project ui-ngx: Failed to clean project: Failed to delete D:\test\ThingsBoard\ui-ngx\target\node\nod
e.exe

**Environment**

 * OS:  win10
 * thingsboard release-3.1

**Comment by yefimov-andrey** [comment]
Did you try deleting the file manually and trying again?

**Comment by waytai** [comment]
Yes, I try to remode node_modules and compiled again, but also ui error

[ERROR] The build command requires to be run in an Angular project, but a project definition could not be found.
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! thingsboard@3.1.0 build:prod: `ng build --prod --vendor-chunk`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the thingsboard@3.1.0 build:prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\zhiweiliu\AppData\Roaming\npm-cache\_logs\2020-08-27T09_04_18_435Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ThingsBoard Server UI 3.1.0:
[INFO]
[INFO] ThingsBoard Server UI .............................. FAILURE [11:18 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:20 min
[INFO] Finished at: 2020-08-27T17:04:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:npm (npm build) on project ui-ngx: Failed to run task: 'npm run build:prod' failed. org.apache.commons.exec.ExecuteException: P
rocess exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following ar

**Comment by waytai** [comment]
OR] npm notice created a lockfile as package-lock.json. You should commit this file.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\rollup\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.14.0","npm":"6.13.4"})
[INFO] added 1636 packages from 1460 contributors in 606.157s
[WARNING] npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN @flowjs/ngx-flow@0.4.4 requires a peer of @angular/common@^6.0.0 || ^7.0.0|| ^8.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @flowjs/ngx-flow@0.4.4 requires a peer of @angular/core@^6.0.0 || ^7.0.0|| ^8.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @material-ui/pickers@3.2.10 requires a peer of @date-io/core@^1.3.6 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none is installed. You must install peer dependencies yourself.
[ERROR]
[INFO]
[INFO] 63 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO]
[INFO]
[INFO] --- frontend-maven-plugin:1.7.5:npm (npm build) @ ui-ngx ---
[INFO] Running 'npm run build:prod' in D:\test\ThingsBoard\ui-ngx
[INFO]
[INFO] > thingsboard@3.1.0 build:prod D:\test\ThingsBoard\ui-ngx
[INFO] > ng build --prod --vendor-chunk
[INFO]
[ERROR] The build command requires to be run in an Angular project, but a project definition could not be found.
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! thingsboard@3.1.0 build:prod: `ng build --prod --vendor-chunk`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the thingsboard@3.1.0 build:prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\zhiweiliu\AppData\Roaming\npm-cache\_logs\2020-08-27T09_04_18_435Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ThingsBoard Server UI 3.1.0:
[INFO]
[INFO] ThingsBoard Server UI .............................. FAILURE [11:18 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:20 min
[INFO] Finished at: 2020-08-27T17:04:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:npm (npm build) on project ui-ngx: Failed to run task: 'npm run build:prod' failed. org.apache.commons.exec.ExecuteException: P
rocess exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by waytai** [comment]
INFO] --- frontend-maven-plugin:1.7.5:npm (npm build) @ ui-ngx ---
[INFO] Running 'npm run build:prod' in D:\test\ThingsBoard\ui-ngx
[INFO]
[INFO] > thingsboard@3.1.0 build:prod D:\test\ThingsBoard\ui-ngx
[INFO] > ng build --prod --vendor-chunk
[ERROR]
[ERROR] Compiling ngx-flowchart : module as esm5
[INFO]
[INFO] chunk {} runtime.6feb887df07fce63b89a.js (runtime) 1.46 kB [entry] [rendered]
[INFO] chunk {1} main.e29f4efbe71b2e527978.js (main) 128 bytes [initial] [rendered]
[INFO] chunk {2} polyfills.58a5fd1dd6d7d916bda4.js (polyfills) 25.1 kB [initial] [rendered]
[ERROR]
[INFO] chunk {3} polyfills-es5.bdfc16373bb872b3c64f.js (polyfills-es5) 86.8 kB [initial] [rendered]
[ERROR] WARNING in Invalid constructor parameter decorator in D:/test/ThingsBoard/ui-ngx/node_modules/ngx-flowchart/dist/ngx-flowchart/fesm2015/ngx-flowchart.js:
[INFO] chunk {4} styles.20c4f3d1a8621a2288d1.css (styles) 300 kB [initial] [rendered]
[INFO] chunk {scripts} scripts.5bafdae4331650149d6f.js (scripts) 1.29 MB [entry] [rendered]
[ERROR]  () => []
[INFO] Date: 2020-08-27T10:21:13.868Z - Hash: 931342f8057430ee1f0c - Time: 40766ms
[ERROR]
[ERROR] ERROR in getInternalNameOfClass() called on a non-ES5 class: expected FcModelValidationService to have an inner class declaration
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! thingsboard@3.1.0 build:prod: `ng build --prod --vendor-chunk`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the thingsboard@3.1.0 build:prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\zhiweiliu\AppData\Roaming\npm-cache\_logs\2020-08-27T10_21_14_015Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 3.1.0:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [  2.699 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  4.750 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.041 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  5.333 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.515 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  2.135 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  0.951 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  0.834 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [ 36.291 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.101 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  1.714 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.626 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.828 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  1.025 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  1.909 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.057 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  1.170 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [ 10.908 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  6.894 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.047 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 44.731 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 14.772 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 14.891 s]
[INFO] ThingsBoard Server UI .............................. FAILURE [03:34 min]
[INFO] Thingsboard Server Tools ........................... SKIPPED
[INFO] Thingsboard Rest Client ............................ SKIPPED
[INFO] ThingsBoard Server Application ..................... SKIPPED
[INFO] ThingsBoard Microservices .......................... SKIPPED
[INFO] ThingsBoard Docker Images .......................... SKIPPED
[INFO] ThingsBoard JavaScript Executor Microservice ....... SKIPPED
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:09 min
[INFO] Finished at: 2020-08-27T18:21:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:npm (npm build) on project ui-ngx: Failed to run task: 'npm run build:prod' failed. org.apache.commons.exec.ExecuteException: P
rocess exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ui-ngx

**Comment by waytai** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\test\\ThingsBoard\\ui-ngx\\target\\node\\node.exe',
1 verbose cli   'D:\\test\\ThingsBoard\\ui-ngx\\target\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:prod'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle thingsboard@3.1.0~prebuild:prod: thingsboard@3.1.0
6 info lifecycle thingsboard@3.1.0~build:prod: thingsboard@3.1.0
7 verbose lifecycle thingsboard@3.1.0~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle thingsboard@3.1.0~build:prod: PATH: D:\test\ThingsBoard\ui-ngx\target\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\test\ThingsBoard\ui-ngx\node_modules\.bin;D:\test\ThingsBoard\ui-ngx\target\node;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\software\python;D:\software\python\Scripts;D:\software\Git\cmd;D:\software\go\bin;D:\software\Vim\vim82;D:\software\nodejs\;D:\software\mingw64\bin;C:\Users\zhiweiliu\AppData\Roaming\npm\node_modules;%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;C:\Program Files\Java\jdk1.8.0_231\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;D:\software\redis\;C:\Users\zhiweiliu\AppData\Local\Microsoft\WindowsApps;C:\Users\zhiweiliu\go\bin;C:\Users\zhiweiliu\AppData\Roaming\npm;D:\software\apache-maven-3.6.3\bin;;D:\software\vscode\bin;
9 verbose lifecycle thingsboard@3.1.0~build:prod: CWD: D:\test\ThingsBoard\ui-ngx
10 silly lifecycle thingsboard@3.1.0~build:prod: Args: [ '/d /s /c', 'ng build --prod --vendor-chunk' ]
11 silly lifecycle thingsboard@3.1.0~build:prod: Returned: code: 1  signal: null
12 info lifecycle thingsboard@3.1.0~build:prod: Failed to exec build:prod script
13 verbose stack Error: thingsboard@3.1.0 build:prod: `ng build --prod --vendor-chunk`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\test\ThingsBoard\ui-ngx\target\node\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (D:\test\ThingsBoard\ui-ngx\target\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid thingsboard@3.1.0
15 verbose cwd D:\test\ThingsBoard\ui-ngx
16 verbose Windows_NT 10.0.18362
17 verbose argv "D:\\test\\ThingsBoard\\ui-ngx\\target\\node\\node.exe" "D:\\test\\ThingsBoard\\ui-ngx\\target\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error thingsboard@3.1.0 build:prod: `ng build --prod --vendor-chunk`
22 error Exit status 1
23 error Failed at the thingsboard@3.1.0 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by waytai** [comment]
> Did you try deleting the file manually and trying again?

I have try remove node_modules and compiled again, also the error

**Comment by vvlladd28** [comment]
Hi 
Change package.json line "`ngx-flowchart": "git://github.com/thingsboard/ngx-flowchart.git#master",` to "ngx-flowchart": "git://github.com/thingsboard/ngx-flowchart.git#9caae13da1b95fa8aaa7938f57537b229b207e4a",

**Comment by zacky131** [comment]
> Hi
> Change package.json line "`ngx-flowchart": "git://github.com/thingsboard/ngx-flowchart.git#master",` to "ngx-flowchart": "git://github.com/thingsboard/ngx-flowchart.git#9caae13da1b95fa8aaa7938f57537b229b207e4a",

( I'm using Thingsboard 3.2)
Thanks its help me out..However, on the next step during building js-executor it give me another error...
But, I found the solution for it by changing: ( also update node, yarn and npm to the latest version)
change package.json inside js-executor and web-ui folder to
"scripts": {
    "install": "pkg -t **node14-linux-x64,node14-win-x64** --out-path ./target . && node install.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "WEB_FOLDER=./target/web nodemon server.js",
    "start-prod": "NODE_ENV=production nodemon server.js"
  },

**Comment by resyon** [comment]
> > Hi
> > Change package.json line "`ngx-flowchart": "git://github.com/thingsboard/ngx-flowchart.git#master",` to "ngx-flowchart": "git://github.com/thingsboard/ngx-flowchart.git#9caae13da1b95fa8aaa7938f57537b229b207e4a",
> 
> ( I'm using Thingsboard 3.2)
> Thanks its help me out..However, on the next step during building js-executor it give me another error...
> But, I found the solution for it by changing: ( also update node, yarn and npm to the latest version)
> change package.json inside js-executor and web-ui folder to
> "scripts": {
> "install": "pkg -t **node14-linux-x64,node14-win-x64** --out-path ./target . && node install.js",
> "test": "echo "Error: no test specified" && exit 1",
> "start": "WEB_FOLDER=./target/web nodemon server.js",
> "start-prod": "NODE_ENV=production nodemon server.js"
> },
thanks, this sloved my problem.  
thingsboard v3.2.2
ubuntu 20.04
