### ISSUE TITLE
[Bug] Error when upgrading from Thingsboard PE 2.4.3 using Docker-Cassandra

### ISSUE THREAD

**Issue by DejonckheereWard** [thingsboard/thingsboard#3345]
**Describe the bug**
When executing the upgrade script given with the docker compose scripts the script tries to upgrade from version "2.4.3" to "2.4.3PE" then the script hangs at "updating schema..." and after a while the script crashes with this error:
```
Starting ThingsBoard Upgrade from version 2.4.3 ...
Upgrading ThingsBoard from version 2.4.3 to 2.4.3PE ...
Updating schema ...
Unexpected error during ThingsBoard installation!
java.lang.NullPointerException: null
        at org.thingsboard.server.service.install.CassandraDatabaseUpgradeService.lambda$loadCql$0(CassandraDatabaseUpgradeService.java:393)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.thingsboard.server.service.install.CassandraDatabaseUpgradeService.loadCql(CassandraDatabaseUpgradeService.java:392)
        at org.thingsboard.server.service.install.CassandraDatabaseUpgradeService.upgradeDatabase(CassandraDatabaseUpgradeService.java:315)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:148)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Unexpected error during ThingsBoard installation!
```

**My Server Environment**
* Own setup
  * Docker Deployment with Cassandra
  * 2.4.3
  * Photon OS 3.0 (build: 11dd065)

**Comment by trypzz** [comment]
Hello, @DejonckheereWard 

Tell me, please, your problem is actual or not?
