### ISSUE TITLE
[Bug] Transformation Node "script" cannot handle "for" loop.

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#3348]
**Describe the bug**
When I use the "script" node to handle for loop, there is an error eccured.
My script node is like below:
`alarmRule = JSON.parse(metadata.alarmRule);
if(metadata.cs_设备位置 ==  "1号仓库"){
     for(let i=0; i<alarmRule.length;i++){
         alarmJson = alarmRule[i];
     }
}
return {msg: msg, metadata: metadata, msgType: msgType};`
![image](https://user-images.githubusercontent.com/31084798/90849412-be4a4680-e3a1-11ea-91d9-abda55f022fb.png)

But, if I use a if, there is no error.
`alarmRule = JSON.parse(metadata.alarmRule);
if(metadata.cs_设备位置 ==  "1号仓库"){
    if(alarmRule.length > 0){
        alarmJson = alarmRule[0];
    }
}
return {msg: msg, metadata: metadata, msgType: msgType};`

The error message is like below:
`java.lang.RuntimeException: No compiled script found for scriptId: [8fad0cbb-3f9c-420f-a81c-551254705f7c]!
	at org.thingsboard.server.service.script.AbstractJsInvokeService.invokeFunction(AbstractJsInvokeService.java:64)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeScriptAsync(RuleNodeJsScriptEngine.java:223)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeUpdateAsync(RuleNodeJsScriptEngine.java:117)
	at org.thingsboard.rule.engine.transform.TbTransformMsgNode.transform(TbTransformMsgNode.java:56)
	at org.thingsboard.rule.engine.transform.TbAbstractTransformNode.onMsg(TbAbstractTransformNode.java:46)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:107)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:45)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:121)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`
![image](https://user-images.githubusercontent.com/31084798/90849323-9bb82d80-e3a1-11ea-8173-cf564d34306d.png)

**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard Version:3.0.1
  * OS Name and Version:Ubuntu:18.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows7
* Browser:chrome, 
* Version :84

**Comment by ChantsovaEkaterina** [comment]
Hello,
Could you replace _let_ on _var_ and test if this will make it work?

**Comment by qwyinxiang** [comment]
I have just replcaed let on var, and there is no error occurs.
Thank you very much for your answer.
