### ISSUE TITLE
Running development environment

### ISSUE THREAD

**Issue by kimoudev** [thingsboard/thingsboard#336]
I can't login in development environment after this command in UI
`mvn clean install -P npm-start`
I have the same problem on mac as on ubuntu.
```
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 3.36 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/components/plugin-select.scss 1.86 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]                                    Asset     Size  Chunks             Chunk Names
[ERROR]     7a764201c0fa39a9802df062c009ba7e.svg  15.7 kB          [emitted]  
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 5.2 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/widget/lib/rpc/knob.scss 3.61 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR]         [2] ./src/app/widget/lib/rpc/svg/knob.svg 82 bytes {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 29 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/widget/lib/rpc/switch.scss 3.14 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR]         [2] ./src/app/widget/lib/rpc/svg/thumb-bar-checked.svg 6.79 kB {0} [built]
[ERROR]         [3] ./src/app/widget/lib/rpc/svg/thumb-bar.svg 5.87 kB {0} [built]
[ERROR]         [4] ./src/app/widget/lib/rpc/svg/thumb-checked.svg 6.26 kB {0} [built]
[ERROR]         [5] ./src/app/widget/lib/rpc/svg/thumb.svg 5.39 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 4.61 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/components/react/json-form.scss 3.1 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 2.61 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/dashboard/states/entity-state-controller.scss 1.11 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 2.97 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/components/react/json-form-color.scss 1.47 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 3.45 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/components/react/json-form-image.scss 1.94 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 2.63 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/components/material-icons-dialog.scss 1.13 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 3.05 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/components/react/json-form-ace-editor.scss 1.54 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 4.43 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/widget/lib/rpc/led-indicator.scss 2.92 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] Child extract-text-webpack-plugin:
[ERROR]     chunk    {0} extract-text-webpack-plugin-output-filename 12.7 kB [rendered]
[ERROR]         [0] ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/widget/lib/rpc/round-switch.scss 11.2 kB {0} [built]
[ERROR]         [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
[ERROR] API proxy error: Error: connect ECONNREFUSED 127.0.0.1:8080
[ERROR] API proxy error: Error: connect ECONNREFUSED 127.0.0.1:8080
```

**Comment by mp-loki** [comment]
I think you need the backend running in order to be able to log in.
Please check out the [Contribution Guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/)

**Comment by kimoudev** [comment]
please error from spring boot...

`2017-10-10 16:05:26.538  INFO 15460 --- [           main] o.t.server.ThingsboardServerApplication  : Starting ThingsboardServerApplication v1.3.1-SNAPSHOT on UbuntuJC with PID 15460 (/var/www/ikozer/thingsboard/application/target/thingsboard-1.3.1-SNAPSHOT-boot.jar started by jnguesan in /var/www/ikozer/thingsboard)
2017-10-10 16:05:26.691  INFO 15460 --- [           main] o.t.server.ThingsboardServerApplication  : No active profile set, falling back to default profiles: default
2017-10-10 16:05:27.338  INFO 15460 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@29ee9faa: startup date [Tue Oct 10 16:05:27 CEST 2017]; root of context hierarchy
2017-10-10 16:05:54.203  INFO 15460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$e1e36244] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-10-10 16:05:54.356  INFO 15460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [class org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$7a912a7e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-10-10 16:05:54.387  INFO 15460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'objectPostProcessor' of type [class org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-10-10 16:05:54.392  INFO 15460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@d2de489' of type [class org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-10-10 16:05:54.433  INFO 15460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [class org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$9f65cd30] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-10-10 16:05:54.472  INFO 15460 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [class org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-10-10 16:05:56.351  INFO 15460 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-10-10 16:05:56.436  INFO 15460 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2017-10-10 16:05:56.438  INFO 15460 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.6
2017-10-10 16:05:56.743  INFO 15460 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-10-10 16:05:56.744  INFO 15460 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 29410 ms
2017-10-10 16:05:59.449  INFO 15460 --- [ost-startStop-1] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2017-10-10 16:05:59.513  INFO 15460 --- [ost-startStop-1] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2017-10-10 16:06:00.235  INFO 15460 --- [ost-startStop-1] org.hibernate.Version                    : HHH000412: Hibernate Core {5.0.11.Final}
2017-10-10 16:06:00.239  INFO 15460 --- [ost-startStop-1] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2017-10-10 16:06:00.245  INFO 15460 --- [ost-startStop-1] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
2017-10-10 16:06:00.487  INFO 15460 --- [ost-startStop-1] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB5F06952BD7.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2017-10-10 16:06:02.929  INFO 15460 --- [ost-startStop-1] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
2017-10-10 16:06:04.238  INFO 15460 --- [ost-startStop-1] o.h.tool.hbm2ddl.SchemaValidator         : HHH000229: Running schema validator
2017-10-10 16:06:04.278  INFO 15460 --- [ost-startStop-1] rmationExtractorJdbcDatabaseMetaDataImpl : HHH000262: Table not found: admin_settings
2017-10-10 16:06:04.280  INFO 15460 --- [ost-startStop-1] rmationExtractorJdbcDatabaseMetaDataImpl : HHH000262: Table not found: admin_settings
2017-10-10 16:06:04.289 ERROR 15460 --- [ost-startStop-1] o.s.b.c.embedded.tomcat.TomcatStarter    : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'restAuthenticationProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restAuthenticationProvider' defined in URL [jar:file:/var/www/ikozer/thingsboard/application/target/thingsboard-1.3.1-SNAPSHOT-boot.jar!/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'relationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRelationService': Unsatisfied dependency expressed through field 'relationDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaRelationDao': Unsatisfied dependency expressed through field 'relationRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'relationRepository': Cannot create inner bean '(inner bean)#2661cdb7' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#2661cdb7': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
2017-10-10 16:06:04.348  WARN 15460 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
2017-10-10 16:06:04.503 ERROR 15460 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:36) [classes!/:1.3.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [thingsboard-1.3.1-SNAPSHOT-boot.jar:1.3.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [thingsboard-1.3.1-SNAPSHOT-boot.jar:1.3.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [thingsboard-1.3.1-SNAPSHOT-boot.jar:1.3.1-SNAPSHOT]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521) [thingsboard-1.3.1-SNAPSHOT-boot.jar:1.3.1-SNAPSHOT]
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:115) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:82) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:535) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:177) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	... 16 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'restAuthenticationProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'restAuthenticationProvider' defined in URL [jar:file:/var/www/ikozer/thingsboard/application/target/thingsboard-1.3.1-SNAPSHOT-boot.jar!/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/rest/RestAuthenticationProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'relationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseRelationService': Unsatisfied dependency expressed through field 'relationDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jpaRelationDao': Unsatisfied dependency expressed through field 'relationRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'relationRepository': Cannot create inner bean '(inner bean)#2661cdb7' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#2661cdb7': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
`  @mp-loki  @ashvayka

**Comment by sonersoysal** [comment]
Hi,
I'm having the same issue. Would you please help me fixing it.
Thanks!

**Comment by derklauer** [comment]
Also having this issue
