### ISSUE TITLE
[Bug] Script is blacklisted due to maximum error count 3

### ISSUE THREAD

**Issue by destr1ke** [thingsboard/thingsboard#3372]
**Script is blacklisted due to maximum error count 3**
Hello! I have a couple of scripts in rule chains and it breaks 2 times in a month. Although before that everything worked without problems for a long time. Here is the error that first appears before the script breaks:
```javax.script.ScriptException: java.lang.RuntimeException: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.NashornSandboxImpl$1.invokeFunction(NashornSandboxImpl.java:353)
	at org.thingsboard.server.service.script.AbstractNashornJsInvokeService.doInvokeFunction(AbstractNashornJsInvokeService.java:91)
	at org.thingsboard.server.service.script.AbstractJsInvokeService.invokeFunction(AbstractJsInvokeService.java:51)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeScript(RuleNodeJsScriptEngine.java:172)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeUpdate(RuleNodeJsScriptEngine.java:104)
	at org.thingsboard.rule.engine.transform.TbTransformMsgNode.lambda$transform$0(TbTransformMsgNode.java:52)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.ThreadMonitor.run(ThreadMonitor.java:130)
	at delight.nashornsandbox.internal.JsEvaluator.runMonitor(JsEvaluator.java:47)
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:161)
	at delight.nashornsandbox.internal.NashornSandboxImpl.access$000(NashornSandboxImpl.java:36)
	at delight.nashornsandbox.internal.NashornSandboxImpl$1.invokeFunction(NashornSandboxImpl.java:349)
	... 11 more
Caused by: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.ThreadMonitor.run(ThreadMonitor.java:91)
	... 15 more```

Tell me what could be the problem?

* own setup
  * ThingsBoard Version 2.2.0
  * linux

**Comment by Karabiy** [comment]
The script you're using is blacklisted. In order to get it out from a blacklist you have to:

Delete one symbol and save it, get that symbol back and save it again.Then your script will get out from a blacklist.The blacklisting happens in 2 cases:
1)The script is too heavy.
2)The system is loaded by something else.
The script is blacklisted when its execution is longer than 100 ms.
The main solution involves changing thingsboard.yml parameter:changing js.local.max_cpu_time in the thingsboard.yml to a value more than 100 in order to increase the time before the script is blacklisted by the rule engine.
In order to exclude something already blacklisted you need to re-save the script (delete one symbol and type it back and save, for example).
Also, the script blacklisting can happen in case the script receives messages which can not be proceeded ( Javascript code-related errors ). 
For those reasons, you can proceed with the combination of filtering being applied before those (in case the script uses some particular message included body or metadata)
Please, refer to this link regarding the Filter nodes: [](https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/)

There were some enhancements in the Rule Engine 2.5 version so that now the queue processing strategy can be configured to handle those. Please, refer to this link regarding the queue processing strategies options: [](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#queue-processing-strategy)

Also, you can create the rule chain for emailing you and have those being connected with the script nodes, so that in the case of a failure, you will receive the email on those.
Please, refer to this link regarding how to proceed with the email notifications: [](https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/send-email/)
