### ISSUE TITLE
[Bug] REST Connector example not working

### ISSUE THREAD

**Issue by thucar** [thingsboard/thingsboard#3408]
**Describe the bug**
After configuring the REST connector according to the example on thingsboard.io website, I'm getting an Internal Server Error (error 500) At the same time I'm seeing a Keyerror: 'HTTPMethods' in syslog

**Your Server Environment**
* own setup
  * Cloud VPS
  * ThingsBoard 3.1.1
  * Debian 10

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Windows 7 x64
* Browser: Chrome

**Your Device**

* Connectivity
  * Gateway with REST Connector

**To Reproduce**
1. Configure REST connector for IoT Gateway
2. Make a POST request to the configured endpoint
3. see error message in syslog

**Expected behavior**
Incoming REST requests should be handled according to the connectors configuration.

**Additional context**
tb_gateway.yaml
```
thingsboard:
  host: 127.0.0.1
  port: 1883
  remoteConfiguration: false
  security:
    accessToken: xxXXxxxXXXXXXxXx
storage:
  type: file
  data_folder_path: /tmp/tbgw-data/
  max_file_count: 10
  max_read_records_count: 10
  max_records_per_file: 10000
connectors:

  -
    name: REST Connector
    type: rest
    configuration: rest.json

```

rest.json
```
{
  "host": "0.0.0.0",
  "port": "5000",
  "mapping":[
    {
      "endpoint": "/test",
      "HTTPMethod": [
        "POST"
      ],
      "security": {
        "type": "basic",
        "username": "user",
        "password": "passwd"
      },
      "converter": {
        "type": "json",
        "deviceNameExpression": "Device ${name}",
        "deviceTypeExpression": "default",
        "attributes": [
          {
            "type": "string",
            "key": "model",
            "value": "${sensorModel}"
          }
        ],
        "timeseries": [
          {
            "type": "double",
            "key": "temperature",
            "value": "${temp}"
          },
          {
            "type": "double",
            "key": "humidity",
            "value": "${hum}"
          }
        ]
      }
    }
  ]
}
```

Error message from syslog:
```
Sep  2 09:21:29 vmi440474 python3[28174]: ""2020-09-02 09:21:29" - ERROR - [app.py] - app - 1892 - Exception on /test [POST]"
Sep  2 09:21:29 vmi440474 python3[28174]: Traceback (most recent call last):
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/var/lib/thingsboard_gateway/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Sep  2 09:21:29 vmi440474 python3[28174]:     rv = self.dispatch_request()
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/var/lib/thingsboard_gateway/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Sep  2 09:21:29 vmi440474 python3[28174]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/var/lib/thingsboard_gateway/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
Sep  2 09:21:29 vmi440474 python3[28174]:     resp = resource(*args, **kwargs)
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/var/lib/thingsboard_gateway/.local/lib/python3.7/site-packages/flask/views.py", line 89, in view
Sep  2 09:21:29 vmi440474 python3[28174]:     return self.dispatch_request(*args, **kwargs)
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/var/lib/thingsboard_gateway/.local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
Sep  2 09:21:29 vmi440474 python3[28174]:     resp = meth(*args, **kwargs)
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/var/lib/thingsboard_gateway/.local/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
Sep  2 09:21:29 vmi440474 python3[28174]:     return f(*args, **kwargs)
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/rest/rest_connector.py", line 362, in post
Sep  2 09:21:29 vmi440474 python3[28174]:     return self.process_data(request)
Sep  2 09:21:29 vmi440474 python3[28174]:   File "/usr/lib/python3/dist-packages/thingsboard_gateway/connectors/rest/rest_connector.py", line 343, in process_data
Sep  2 09:21:29 vmi440474 python3[28174]:     if request.method.upper() not in [method.upper() for method in endpoint_config['HTTPMethods']]:
Sep  2 09:21:29 vmi440474 python3[28174]: KeyError: 'HTTPMethods'
```

**Comment by Karabiy** [comment]
please, refer for this file in order to have a fix for the issue of yours 
https://github.com/thingsboard/thingsboard-gateway/blob/master/thingsboard_gateway/config/rest.json

**Comment by thucar** [comment]
@Karabiy thank you! Found the bug - in the example config file on the website https://thingsboard.io/docs/iot-gateway/config/rest/

HTTP Method sections are defined as "HTTPMethod" but should be "HTTPMethods"
```
"mapping":[
    {
      "endpoint": "/test_device",
      "HTTPMethod": [
        "POST"
      ],
...
{
      "endpoint": "/test",
      "HTTPMethod": [
        "GET",
        "POST"
      ],
```

Changing that fixed my issue.
