### ISSUE TITLE
[Bug] Docker Update procedure does not work

### ISSUE THREAD

**Issue by pieromacaluso** [thingsboard/thingsboard#3439]
## Describe the bug
The procedure proposed to upgrade the Docker ThingsBoard version from one to another (provided below) does not work as expected.

```
docker pull thingsboard/tb-postgres
docker-compose stop
docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres upgrade-tb.sh
docker-compose rm mytb
docker-compose up
```

## Your Server Environment

- Docker Deployment (`thingsboard/tb-postgres`)
- **TB Version**: v3.0.0
- **TB Upgrading Version**: latest (v3.1.1)
- **OS**: Ubuntu 20.04

### Initial `docker-compose.yaml`
```
version: '2.2'
services:
  linksboard:
    restart: always
    image: "thingsboard/tb-postgres:3.0.0"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
```
### Steps to reproduce the behaviour
1. Create volumes dir:
```
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs
```
2. Install v3.0.0 via Docker Compose with `docker-compose up`
3. Follows this [guide](https://thingsboard.io/docs/user-guide/install/docker/#upgrading)
```
docker pull thingsboard/tb-postgres
docker-compose stop
docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres upgrade-tb.sh
```

### Error Log
```
Starting ThingsBoard upgrade ...
 ===================================================
 :: ThingsBoard ::       (v3.1.1)
 ===================================================

Starting ThingsBoard Upgrade from version 2.4.2 ...
Upgrading ThingsBoard from version 2.4.2 to 2.4.3 ...
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:208)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:155)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
	... 17 common frames omitted
Unexpected error during ThingsBoard installation!
/usr/bin/upgrade-tb.sh: line 45: /data/.upgradeversion: Permission denied
pg_ctl: could not open PID file "/data/db/postmaster.pid": Permission denied

```

## Expected behavior

Complete the update and conclude the upgrade by using the remaining commands:
```
docker-compose rm mytb
docker-compose up
```

**Comment by pieromacaluso** [comment]
I noticed that it was necessary to run another time the following script after the first installation:
```
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs
```
Furthermore, when upgrading from 3.0.1 to 3.1.0, I had to modify manually the file `~/.my-tbdata/.upgradeversion` from `2.4.5` to `3.0.1`.

However I was still unable to update Thingsboard and I receive this log:

```
Starting ThingsBoard upgrade ...
 ===================================================
 :: ThingsBoard ::       (v3.1.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.0.1 ...
Upgrading ThingsBoard from version 3.0.1 to 3.1.0 ...
Failed updating schema!!!
org.postgresql.util.PSQLException: FATAL: role "thingsboard" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2586)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:113)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:243)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:173)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Updating data from version 3.0.1 to 3.1.0 ...
Unexpected error during ThingsBoard installation!
org.springframework.orm.jpa.JpaSystemException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy152.findByRegionNextPage(Unknown Source)
	at org.thingsboard.server.dao.sql.tenant.JpaTenantDao.findTenantsByRegion(JpaTenantDao.java:56)
	at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$FastClassBySpringCGLIB$$bb4581c1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$EnhancerBySpringCGLIB$$6a3741c8.findTenantsByRegion(<generated>)
	at org.thingsboard.server.dao.tenant.TenantServiceImpl.findTenants(TenantServiceImpl.java:120)
	at org.thingsboard.server.service.install.update.DefaultDataUpdateService$2.findEntities(DefaultDataUpdateService.java:115)
	at org.thingsboard.server.service.install.update.DefaultDataUpdateService$2.findEntities(DefaultDataUpdateService.java:111)
	at org.thingsboard.server.service.install.update.PaginatedUpdater.updateEntities(PaginatedUpdater.java:31)
	at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:82)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:174)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2104)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2034)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
	at org.hibernate.loader.Loader.doQuery(Loader.java:953)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2838)
	at org.hibernate.loader.Loader.doList(Loader.java:2820)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2652)
	at org.hibernate.loader.Loader.list(Loader.java:2647)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:396)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1404)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1562)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1530)
	at org.hibernate.query.Query.getResultList(Query.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:409)
	at com.sun.proxy.$Proxy209.getResultList(Unknown Source)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:177)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:618)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	... 27 common frames omitted
Caused by: org.postgresql.util.PSQLException: FATAL: role "thingsboard" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2586)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:113)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at com.zaxxer.hikari.HikariDataSource$$FastClassBySpringCGLIB$$eeb1ae86.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$a63f3fa.getConnection(<generated>)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)
	... 65 common frames omitted
Unexpected error during ThingsBoard installation!
waiting for server to shut down.... done
server stopped
```

**Comment by kurtrenauer** [comment]
... we have exactly the same bug experience ...

**Comment by CooL16** [comment]
Please try to use this docker-compose.yml for initializing in case of ThingsBoard 3.1+:

```
version: '2.2'
services:
  mytbpe:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
  postgres:
    restart: always
    image: "postgres:11.6"
    ports:
    - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/.mytb-data/db:/var/lib/postgresql/data
```
Here also steps for performing an upgrade:

Make a backup of existing data:
```
cp ~/.mytb-data/.firstlaunch ~/backup/
```

start new version of TB with following command:
```
docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres bash
```

Then please follow these steps:
```
apt update

apt install sudo

chown -R postgres. /data/db/

chmod 750 -R /data/db/

sudo -i -u postgres

cd /usr/lib/postgresql/11/

./bin/pg_ctl -D /data/db start

logout

/usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.1

exit

```

**Comment by michalfapso** [comment]
@pieromacaluso, you've just saved my day! :) I had the same issue with a clean install of the current version 3.1.1. The first `docker-compose up` went well, but then when I stopped the container and ran it the second time, I got the error:
```
org.postgresql.util.PSQLException: Connection to localhost:5432 refused
```
It was fixed by setting file permissions again, as you wrote in your post:
> mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
> mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs

Thanks!

**Comment by saemy** [comment]
This is how I was able to fix the `FATAL: role "thingsboard" does not exist` issue:

Switch to an interactive shell within the container:
```
$ docker stop thingsboard
$ docker run --tty --interactive --rm \
      --volume /mnt/data/thingsboard/data:/data \
      --volume /mnt/data/thingsboard/logs:/var/log \
      thingsboard/tb-postgres bash
thingsboard:/$ 
```

Launch the postgres server:
```
thingsboard:/$ postgres &
```

Login as the existing "postgres" user and add a temporary "admin" user:
```
thingsboard:/$ psql -U postgres
postgres=# CREATE ROLE admin WITH SUPERUSER LOGIN;
postgres=# exit
```

Login as the temporary "admin" user and rename the existing "postgres" user to "thingsboard":
```
thingsboard:/$ psql -U admin -d thingsboard
thingsboard=# ALTER ROLE postgres RENAME TO thingsboard;
thingsboard=# exit
```

Login as the "thingsboard" user and remove the temporary "admin" user:
```
thingsboard:/$ psql -U thingsboard
thingsboard=# DROP ROLE admin;
thingsboard=# exit
```

Then logout from the container and re-run `upgrade-tb.sh`.

Hope this helps.

**Comment by pieromacaluso** [comment]
Thanks @saemy for your kind answer.
Unfortunately, I can not try anymore this fix on the same problem I had two months ago. I managed to "solve" the problem by following the indication of issue #3347 and this [related one](https://github.com/thingsboard/thingsboard.github.io/issues/428). I will leave it there if it could be useful for future adventurers.
Thanks to all! :smile:

**Comment by hallard** [comment]
Hi There,

Sorry to open back but as today upgrade (yes I say upgrade) still not works.
Today I spent 4H trying to update CE docker compose from 3.0.1 to 3.1.0 (as stated the documentation one version up each time) tried around all things here without any success

first things I've done is to change the file content of file `.upgradeversion` to `3.0.1` then


```
docker pull thingsboard/tb-postgres:3.1.0
docker-compose stop
docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres:3.1.0 upgrade-tb.sh
```
of course got the error 

```
Starting ThingsBoard upgrade ...
 ===================================================
 :: ThingsBoard ::       (v3.1.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.0.1 ...
Upgrading ThingsBoard from version 3.0.1 to 3.1.0 ...
Failed updating schema!!!
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.connect(Driver.java:272)
bla 
bla 
bla
``` 

The classic `chown` **does not works** in case of upgrade it is for first install/run so container install thingsboard and database

```
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs
```

On my case because the folder exists (yes it's an upgrade) and the folder '~/.mytb-data/db` should be related to postgres user of the container so in case it changed 
```
sudo chown -R 102:105 ~/.mytb-data/db
```

Content of container `/etc/passwd` as you can see postgreSQL ID
```
thingsboard:x:799:799:Thingsboard application,,,:/home/thingsboard:/bin/false
postgres:x:102:105:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash

```

But anyway, I succeeded to get things back up and running with version 3.0.1 but there is no full working procedure for upgrading, so If someone has some experience on this upgrade it will really be appreciated
