### ISSUE TITLE
[Bug]  Subscribe to Device Alarm caused server exception, 

### ISSUE THREAD

**Issue by wy6688** [thingsboard/thingsboard#3495]
**Describe the bug**
when I subscribed to the device alarm, the backend
 "org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository.findAlarmDataByQueryForEntities" produced wrong SQL statement and caused TB server exception.

**Your Server Environment**

* own setup
  * local Thingboard + Postrgres
  * ThingsBoard develop/3.2
  * OS: Windows 10 pro.

**Your Client Environment**
* OS: Windows 10
* Browser chrome
* Version [85.0.4183]

**Your Device**

* Connectivity
  * Local MQTT client
  
1. Run attached Typescript code to subscribe to any device alarm.
2. Check Thingsboard server log, you will find the log similiar as attached log file.

**Expected behavior**
Subscribe to Device alarm shouldn't cause the thingsboard exception
=============================================================

---------------------------------------------------------------------------
client side typescript code:

public getAlarmObservable(deviceId: EntityId): Observable<any> {

      const alarmSubscriber = new TelemetrySubscriber(this.telemetryWsService);
      const alarmDataCmd = new AlarmDataCmd();
      alarmDataCmd.query = {entityFilter: { type: AliasFilterType.singleEntity, singleEntity: { entityType: EntityType.DEVICE, id: deviceId.id}}, pageLink: {pageSize: 100, page: 0}};

      alarmSubscriber.subscriptionCommands.push(alarmDataCmd);
      alarmSubscriber.subscribe();

      return alarmSubscriber.alarmData$.pipe(catchError(err => {
          console.log('error:', err); return of([]);}), tap((data) => console.log(data)));
 }

TthingsBoard  devlop/3.2 exception log 

===========================================================================
2020-09-18 06:32:10,718 [http-nio-0.0.0.0-8080-exec-8] ERROR o.s.w.s.h.ExceptionWebSocketHandlerDecorator - Closing session due to exception for StandardWebSocketSession[id=486462fa-ec34-e2ae-a21a-cebd3dd6ec9a, uri=ws://localhost:4200/api/ws/plugins/telemetry?token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJ1c2VySWQiOiIwMWM5NmEzMC1mOGNlLTExZWEtOGMxNy0zZGFiMGNhZGJjNzMiLCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMDE2NTUxMzAtZjhjZS0xMWVhLThjMTctM2RhYjBjYWRiYzczIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCIsImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNjAwNDI3NTg4LCJleHAiOjE2MDA0MzY1ODh9.06Yd0g7FATHED1h_sDazVwLNbmwpr6KAHKta1m5uZWRtbFQuWFRYLZfYkAnx2HbfMtcJgBA3wbQfwcWY__GmzQ]
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select count(*) from (select a.id as id, a.created_time as created_time, a.ack_ts as ack_ts, a.clear_ts as clear_ts, a.additional_info as additional_info, a.end_ts as end_ts, a.originator_id as originator_id, a.originator_type as originator_type, a.propagate as propagate, a.severity as severity, a.start_ts as start_ts, a.status as status,  a.tenant_id as tenant_id,  a.propagate_relation_types as propagate_relation_types,  a.type as type, CASE WHEN a.originator_type = 0 THEN (select title from tenant where id = a.originator_id) WHEN a.originator_type = 2 THEN (select title from customer where id = a.originator_id) WHEN a.originator_type = 3 THEN (select email from tb_user where id = a.originator_id) WHEN a.originator_type = 4 THEN (select title from dashboard where id = a.originator_id) WHEN a.originator_type = 5 THEN (select name from asset where id = a.originator_id) WHEN a.originator_type = 6 THEN (select name from device where id = a.originator_id) WHEN a.originator_type = 11 THEN (select name from entity_view where id = a.originator_id) END as originator_name,  a.originator_id as entity_id  from alarm a  left join (select * from (VALUES(uuid('026fbc50-f8ce-11ea-8c17-3dab0cadbc73'), 0)) as e(id, priority)) e on a.originator_id = e.id where ) result]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 1264
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:235)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:748)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:236)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:253)
	at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository.lambda$findAlarmDataByQueryForEntities$0(DefaultAlarmQueryRepository.java:238)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository.findAlarmDataByQueryForEntities(DefaultAlarmQueryRepository.java:129)
	at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository$$FastClassBySpringCGLIB$$a1c7ad2c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository$$EnhancerBySpringCGLIB$$fb6b0a8a.findAlarmDataByQueryForEntities(<generated>)
	at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao.findAlarmDataByQueryForEntities(JpaAlarmDao.java:121)
	at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao$$FastClassBySpringCGLIB$$fedeae2f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao$$EnhancerBySpringCGLIB$$3087a37e.findAlarmDataByQueryForEntities(<generated>)
	at org.thingsboard.server.dao.alarm.BaseAlarmService.findAlarmDataByQueryForEntities(BaseAlarmService.java:139)
	at org.thingsboard.server.service.subscription.TbAlarmDataSubCtx.fetchAlarms(TbAlarmDataSubCtx.java:93)
	at org.thingsboard.server.service.subscription.DefaultTbEntityDataSubscriptionService.handleCmd(DefaultTbEntityDataSubscriptionService.java:259)
	at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.handleWsAlarmDataCmd(DefaultTelemetryWebSocketService.java:248)
	at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.lambda$handleWebSocketMsg$4(DefaultTelemetryWebSocketService.java:217)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.handleWebSocketMsg(DefaultTelemetryWebSocketService.java:217)
	at org.thingsboard.server.controller.plugin.TbWebSocketHandler.handleTextMessage(TbWebSocketHandler.java:96)
	at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:395)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
	
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 1264
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:678)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 57 common frames omitted
2020-09-18 06:32:10,719 [http-nio-0.0.0.0-8080-exec-8] INFO  o.t.s.c.plugin.TbWebSocketHandler - [486462fa-ec34-e2ae-a21a-cebd3dd6ec9a] Session is closed
2020-09-18 06:32:16,047 [TB-Scheduling-4] INFO  o.t.s.s.s.DefaultTbEntityDataSubscriptionService - Stats: regularQueryInvocationCnt = [2], regularQueryInvocationTime = [14], dynamicQueryCnt = [0] dynamicQueryInvocationCnt = [0], dynamicQueryInvocationTime = [0], alarmQueryInvocationCnt = [0], alarmQueryInvocationTime = [0]

**Comment by shaphiro** [comment]
Same error for me using thingsboard client for flutter. Standard thingsboard 3.4.1 with postgresql installation.

`AlarmDataQuery adq = new AlarmDataQuery(
        entityFilter: EntityTypeFilter(entityType: EntityType.DEVICE),
        //entityFields: deviceFields,
        //alarmFields: alarmFields,
        //keyFilters: [alarmStatusKeyFilter],
        //latestValues: latestValues,
        pageLink: new AlarmDataPageLink(pageSize: 100, page: 0));
    var cmd = AlarmDataCmd(query: adq);
    var telemetryService = tbClient.getTelemetryService();
    subscription = TelemetrySubscriber(telemetryService, [cmd]);
    subscription.entityDataStream.listen((alarmDataUpdate) {
      print('Received entity data update: $alarmDataUpdate');
    });
    subscription.subscribe();`

The error is:

`ERROR o.s.w.s.h.ExceptionWebSocketHandlerDecorator - Closing session due to exception for StandardWebSocketSession[id=bf29a9ab-56a8-6840-b2a7-35fc03ac75e1, uri=ws://dataservice.tk/api/ws/plugins/telemetry?token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBpbnNpY28uaXQiLCJ1c2VySWQiOiIxY2IxNzU5MC0zNGY0LTExZWQtYjFiNi00YmFkNGUyMTRmZTgiLCJzY29wZXMiOlsiVEVOQU5UX0FETUlOIl0sImlzcyI6InRoaW5nc2JvYXJkLmlvIiwiaWF0IjoxNjYzMjQ3ODg1LCJleHAiOjE2NjMyNTY4ODUsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiIwNDZkOWIzMC0zNGY0LTExZWQtYjFiNi00YmFkNGUyMTRmZTgiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIn0.3nxaI7ZRIP7J1550FKvmjMsOoIOOA0_5GiozNVbxyinZBIK9j7l8l_Fw6HFIw7GnRhyXIttY-a89Cn51DLQYhA]
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select count(*) from (select a.id as id, a.created_time as created_time, a.ack_ts as ack_ts, a.clear_ts as clear_ts, a.additional_info as additional_info, a.end_ts as end_ts, a.originator_id as originator_id, a.originator_type as originator_type, a.propagate as propagate, a.propagate_to_owner as propagate_to_owner, a.propagate_to_tenant as propagate_to_tenant, a.severity as severity, a.start_ts as start_ts, a.status as status,  a.tenant_id as tenant_id,  a.customer_id as customer_id,  a.propagate_relation_types as propagate_relation_types,  a.type as type, COALESCE(CASE WHEN a.originator_type = 0 THEN (select title from tenant where id = a.originator_id) WHEN a.originator_type = 1 THEN (select title from customer where id = a.originator_id) WHEN a.originator_type = 2 THEN (select email from tb_user where id = a.originator_id) WHEN a.originator_type = 3 THEN (select title from dashboard where id = a.originator_id) WHEN a.originator_type = 4 THEN (select name from asset where id = a.originator_id) WHEN a.originator_type = 5 THEN (select name from device where id = a.originator_id) WHEN a.originator_type = 9 THEN (select name from entity_view where id = a.originator_id) END, 'Deleted') as originator_name,  a.originator_id as entity_id  from alarm a  inner join (select * from (VALUES(uuid('7a6d03b0-34f5-11ed-b1b6-4bad4e214fe8'), 0),(uuid('7eb079c0-34f5-11ed-b1b6-4bad4e214fe8'), 1),(uuid('82a53390-34f5-11ed-b1b6-4bad4e214fe8'), 2)) as e(id, priority)) e on a.originator_id = e.id where ) result]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 1506
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:738)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:794)
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:243)
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:260)
        at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository.lambda$findAlarmDataByQueryForEntities$0(DefaultAlarmQueryRepository.java:245)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository.findAlarmDataByQueryForEntities(DefaultAlarmQueryRepository.java:124)
        at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository$$FastClassBySpringCGLIB$$a1c7ad2c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at org.thingsboard.server.dao.sql.query.DefaultAlarmQueryRepository$$EnhancerBySpringCGLIB$$5c6e955c.findAlarmDataByQueryForEntities(<generated>)
        at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao.findAlarmDataByQueryForEntities(JpaAlarmDao.java:161)
        at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao$$FastClassBySpringCGLIB$$fedeae2f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at org.thingsboard.server.dao.sql.alarm.JpaAlarmDao$$EnhancerBySpringCGLIB$$e503306d.findAlarmDataByQueryForEntities(<generated>)
        at org.thingsboard.server.dao.alarm.BaseAlarmService.findAlarmDataByQueryForEntities(BaseAlarmService.java:141)
        at org.thingsboard.server.service.subscription.TbAlarmDataSubCtx.doFetchAlarms(TbAlarmDataSubCtx.java:111)
        at org.thingsboard.server.service.subscription.TbAlarmDataSubCtx.fetchAlarms(TbAlarmDataSubCtx.java:101)
        at org.thingsboard.server.service.subscription.DefaultTbEntityDataSubscriptionService.handleCmd(DefaultTbEntityDataSubscriptionService.java:293)
        at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.handleWsAlarmDataCmd(DefaultTelemetryWebSocketService.java:276)
        at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.lambda$handleWebSocketMsg$4(DefaultTelemetryWebSocketService.java:229)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.handleWebSocketMsg(DefaultTelemetryWebSocketService.java:229)
        at org.thingsboard.server.controller.plugin.TbWebSocketHandler.handleTextMessage(TbWebSocketHandler.java:96)
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 1506
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
        ... 60 common frames omitted`

thingsboard.conf

`export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/data"
export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard/gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError"
export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
export LOG_FILENAME=thingsboard.out
export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql

# DB Configuration 
export DATABASE_TS_TYPE=sql
export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/thingsboard
export SPRING_DATASOURCE_USERNAME=postgres
export SPRING_DATASOURCE_PASSWORD=password
# Specify partitioning size for timestamp key-value storage. Allowed values: DAYS, MONTHS, YEARS, INDEFINITE.
export SQL_POSTGRES_TS_KV_PARTITIONING=MONTHS

# Update ThingsBoard memory usage and restrict it to 256MB in /etc/thingsboard/conf/thingsboard.conf
export JAVA_OPTS="$JAVA_OPTS -Xms256M -Xmx256M"`

thingsboard.yml untouched

Thanks in advance
