### ISSUE TITLE
Include timestamp variable in data converter function?

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#3528]
How can I include timestamp in the data converter function? I am using MQTT integration with QoS1, so if thingsboard is down, when it re-connects it will receive pending messages. The messages have timestamps and sensor data.

I would like to make sure data is inserted with the correct timestamp when the data is pulled via the integration.

Not sure how to include timestamp in the data converter decode function

`
```
// Decode an uplink message from a buffer
// payload - array of bytes
// metadata - key/value object

/** Decoder **/

// decode payload to string

var payloadStr = decodeToString(payload);

// decode payload to JSON
var data = decodeToJson(payload);

var deviceType = 'SCCLORA';


//var customerName = 'customer';
//var groupName = 'thermostat devices';
// var assetName = 'Asset A';
// var assetType = 'building';


// Result object with device/asset attributes/telemetry data
var result = {
   deviceName: data.deveui,
   deviceType: deviceType,
   groupName: "SCCLORA",
   attributes: {
    //   applicationName:data.applicationName,
       adr:data.adr,
       integrationName: metadata['integrationName'],
       networkServer:"chirpstack"
   },
   telemetry: {
       rssi: data.rssi,
       snr: data.snr,
       sf: data.sf,
       data_Datahex:data.payload_hex,
       gwId: data.gwId,
       analog1: data.analog1,
       analog2: data.analog2,
       int_temp: data.int_temp,
       int_light: data.int_light,
       voltage: data.voltage,

       //digital1: data.digital1
       //digital2: data.digital2
       valve1: data.valve1,
       valve2: data.valve2,
       valve3: data.valve3
      
   }
};

/** Helper functions **/

function decodeToString(payload) {
   return String.fromCharCode.apply(String, payload);
}

function decodeToJson(payload) {
   // covert payload to string.
   var str = decodeToString(payload);

   // parse string to JSON
   var data = JSON.parse(str);
   return data;
}

return result;`
```

**Comment by ashvayka** [comment]
To add a timestamp you should change your data converter logic to return 'result' in the following format:

```json
    {
        "deviceName":"SN-111",
        "deviceType":"thermostat",
        "attributes":{
            "model":"Model A"
        },
        "telemetry":[
            {
                "ts":1527863043000,
                "values":{
                    "battery":3.99,
                    "temperature":27.05
                }
            }
        ]
    }
```

Please attach the input of your data converter and I will be able to provide more accurate answer.

**Comment by t0mmyz7** [comment]
great thanks!
```
{
    "deviceName": "008000000400E61B",
    "deviceType": "SCCLORA",
    "groupName": "SCCLORA",
    "attributes": {
        "adr": false,
        "integrationName": "AWS IOT - ChirpStack",
        "networkServer": "chirpstack"
    },
    "telemetry": {
        "ts": 1601551108946,
        "values": {
            "rssi": -81,
            "snr": 12,
            "sf": 10,
            "data_Datahex": "33000000000000"
        }
    }
}
```

**Comment by t0mmyz7** [comment]
@ashvayka I guess it doesn't work for Attributes after all?

```
   attributes: [{
    ts:data.timestamp,
       values:{
       adr:data.adr,
       integrationName: metadata['integrationName'],
       networkServer:"chirpstack"
       }
   }],
```

gives me this:
```

com.google.gson.JsonSyntaxException: Can't parse value: [{"ts":1602018185114,"values":{"adr":false,"integrationName":"AWS IOT - ChirpStack","networkServer":"chirpstack"}}]
	at org.thingsboard.server.common.adaptor.JsonConverter.convertToAttributesProto(JsonConverter.java:158)
	at org.thingsboard.integration.api.converter.AbstractUplinkDataConverter.parseAttributesUpdate(AbstractUplinkDataConverter.java:154)
	at org.thingsboard.integration.api.converter.AbstractUplinkDataConverter.parseUplinkData(AbstractUplinkDataConverter.java:118)
	at org.thingsboard.integration.api.converter.AbstractUplinkDataConverter.convertUplink(AbstractUplinkDataConverter.java:75)
	at org.thingsboard.integration.api.AbstractIntegration.convertToUplinkDataList(AbstractIntegration.java:241)


```

**Comment by bamarek** [comment]
@t0mmyz7 Have you managed to find a solution? I tried adding a 13-char timestamp as integer and text and it is definitely not being picked up by dashboards.

**Comment by t0mmyz7** [comment]
It works for time series data but not for attribute data.

**Comment by yeduy** [comment]
Hi @t0mmyz7 ,

It is not working, because attributes have not timestamps. You can see only last massage time which is come to Thingsboards for attributes.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
