### ISSUE TITLE
[Bug] js-executor: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by janschumann** [thingsboard/thingsboard#3564]
**Describe the bug**

The js-executor pod constantly restarts (CrashLoopBackOff) with the following error:

```
2020-10-08T12:49:48.049888328Z Producer: AwsSqsProducer { send: [AsyncFunction] }
2020-10-08T12:56:10.898522333Z (node:6) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
2020-10-08T12:56:10.898561833Z     at Printf.transform (/snapshot/js-executor/node_modules/logform/printf.js:11:26)
2020-10-08T12:56:10.898566928Z     at Format.transform (/snapshot/js-executor/node_modules/logform/combine.js:20:24)
2020-10-08T12:56:10.898570841Z     at DerivedLogger._transform (/snapshot/js-executor/node_modules/winston/lib/winston/logger.js:235:29)
2020-10-08T12:56:10.898574597Z     at DerivedLogger._read (/snapshot/js-executor/node_modules/readable-stream/lib/_stream_transform.js:184:10)
2020-10-08T12:56:10.89857881Z     at DerivedLogger._write (/snapshot/js-executor/node_modules/readable-stream/lib/_stream_transform.js:172:83)
2020-10-08T12:56:10.898582769Z     at doWrite (/snapshot/js-executor/node_modules/readable-stream/lib/_stream_writable.js:428:64)
2020-10-08T12:56:10.898586047Z     at writeOrBuffer (/snapshot/js-executor/node_modules/readable-stream/lib/_stream_writable.js:417:5)
2020-10-08T12:56:10.898589289Z     at DerivedLogger.write (/snapshot/js-executor/node_modules/readable-stream/lib/_stream_writable.js:334:11)
2020-10-08T12:56:10.898592727Z     at DerivedLogger.log (/snapshot/js-executor/node_modules/winston/lib/winston/logger.js:181:12)
2020-10-08T12:56:10.898596094Z     at DerivedLogger.error (/snapshot/js-executor/node_modules/winston/lib/winston/create-logger.js:62:21)
```

**Your Server Environment**

* k8s msa deployment
* ThingsBoard Version: 3.1.1
* OS Name and Version: Kubernetes 1.17
* AWS SQS Queue

**To Reproduce**

After deploying the js-executor pod connected to AWS SQS the pod constantly restarts (CrashLoopBackOff)

**Comment by ashvayka** [comment]
Does this JS executor work with the other Queues? I am trying to figure out where this is an issue with specific queue implementation or with the user defined function that is causing the loop. I suspect the first one..
@YevhenBondarenko  please check.

**Comment by YevhenBondarenko** [comment]
Hi,
this bug has already fixed for the next release.

**Comment by janschumann** [comment]
Hi @YevhenBondarenko, the only change I have found is the upgrade of the kafkajs package. Does that fix the issue?

**Comment by Karabiy** [comment]
> Hi @YevhenBondarenko, the only change I have found is the upgrade of the kafkajs package. Does that fix the issue?

Yes, those should be an okay after the package change.

**Comment by janschumann** [comment]
Great. Will close this issue.
