### ISSUE TITLE
[Bug] no String-argument constructor/factory method to deserialize from String value ('')

### ISSUE THREAD

**Issue by quocnh** [thingsboard/thingsboard#3586]
**Describe the bug**
Based on this [tutorial](https://thingsboard.io/docs/samples/analytics/kafka-streams/), I want to use an Integration to read Kafka topic data. But I got the bellow bug after upgrading Thingsboard 3.1.1
I did search kafka [document](https://kafka.apache.org/23/documentation/streams/quickstart#quickstart_streams_download), the issue caused by the kafka integration which does not implemented with "--property key.deserializer=org.apache.kafka.common.serialization.StringDeserializer \". 
 
**Your Server Environment**
* own setup
  * my cloud vm
  * ThingsBoard Version: 3.1.1
  * Ubuntu 18.04
**Your Client Environment**=
**Desktop (please complete the following information):**
MacOS

  * Integration: Kafka

**To Reproduce**
1. Go to 'Integration'
2. Click on 'integration/event'
3. Choose "Lifecycle event type"

`com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('')
 at [Source: (String)"{"groupId":"group_id_6238ulbcnz","clientId":"client_id_cl15o71g1y","topics":"solar-module-anomalies","bootstrapServers":"134.129.97.131:9092","pollInterval":5000,"autoCreateTopics":false,"otherProperties":""}"; line: 1, column: 206] (through reference chain: org.thingsboard.integration.kafka.KafkaConsumerConfiguration["otherProperties"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1429)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1059)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromString(ValueInstantiator.java:258)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:357)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at org.thingsboard.integration.kafka.AbstractKafkaIntegration.init(AbstractKafkaIntegration.java:61)
	at org.thingsboard.integration.kafka.basic.BasicKafkaIntegration.init(BasicKafkaIntegration.java:52)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.getOrCreateThingsboardPlatformIntegration(DefaultPlatformIntegrationService.java:938)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.lambda$createIntegration$1(DefaultPlatformIntegrationService.java:346)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
`
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by YevhenBondarenko** [comment]
Hi @quocnh,

we have fixed this bug in the 3.2.0 release.

This bug is related to the empty param "Other properties" in ThingsBoard Version 3+ and you can add any data to  "Other properties" and integration will work.

**Comment by quocnh** [comment]
> Hi @quocnh,
> 
> we have fixed this bug in the 3.2.0 release.
> 
> This bug is related to the empty param "Other properties" in ThingsBoard Version 3+ and you can add any data to "Other properties" and integration will work.

Thank you for the response. So that, my thingsboard will automatically be updated to the 3.2.0 version? or I need to re-install thingsboard from beginning?

**Comment by YevhenBondarenko** [comment]
When Thingsboard 3.2.0 version will be released you can upgrade your old version using [the instruction](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/).

**Comment by quocnh** [comment]
> When Thingsboard 3.2.0 version will be released you can upgrade your old version using [the instruction](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/).

Great! Could you please tell me about the release time so that we can arrange our work better?

**Comment by YevhenBondarenko** [comment]
I believe by the end of this month.
