### ISSUE TITLE
Thingsboard Installation Error

### ISSUE THREAD

**Issue by cjkini** [thingsboard/thingsboard#360]
Guys,

I am trying ton install Thingsboard on Window 7 as per the instruction (https://thingsboard.io/docs/user-guide/install/windows/)
However, my installation failed with below error : 

```
C:\thingsboard>install.bat -loadDemo
Detecting Java version installed.
Detecting if it is 64 bit machine
CurrentVersion
Detecting if it is 32 bit machine
CurrentVersion 1.8
Java 1.8 found!
Installing thingsboard ...
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLau
ncher.java:521)
Caused by: while parsing a block mapping
 in 'reader', line 17, column 1:
    server:
    ^
expected <block end>, but found BlockMappingStart
 in 'reader', line 231, column 3:
      data:
      ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(Par
serImpl.java:570)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java
:230)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:12
2)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructo
r.java:104)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:502)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlPr
ocessor.java:160)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlPr
ocessor.java:138)
        at org.springframework.boot.env.YamlPropertySourceLoader$Processor.proce
ss(YamlPropertySourceLoader.java:101)
        at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlProper
tySourceLoader.java:58)
        at org.springframework.boot.env.PropertySourcesLoader.load(PropertySourc
esLoader.java:127)
        at org.springframework.boot.context.config.ConfigFileApplicationListener
$Loader.loadIntoGroup(ConfigFileApplicationListener.java:466)
        at org.springframework.boot.context.config.ConfigFileApplicationListener
$Loader.load(ConfigFileApplicationListener.java:453)
        at org.springframework.boot.context.config.ConfigFileApplicationListener
$Loader.load(ConfigFileApplicationListener.java:377)
        at org.springframework.boot.context.config.ConfigFileApplicationListener
.addPropertySources(ConfigFileApplicationListener.java:212)
        at org.springframework.boot.context.config.ConfigFileApplicationListener
.postProcessEnvironment(ConfigFileApplicationListener.java:181)
        at org.springframework.boot.context.config.ConfigFileApplicationListener
.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:168)
        at org.springframework.boot.context.config.ConfigFileApplicationListener
.onApplicationEvent(ConfigFileApplicationListener.java:154)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.i
nvokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.m
ulticastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.m
ulticastEvent(SimpleApplicationEventMulticaster.java:121)
        at org.springframework.boot.context.event.EventPublishingRunListener.env
ironmentPrepared(EventPublishingRunListener.java:68)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPre
pared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringA
pplication.java:337)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:308)
        at org.thingsboard.server.ThingsboardInstallApplication.main(Thingsboard
InstallApplication.java:40)
        ... 8 more
ThingsBoard installation failed!
```
Can anyone help me out, pse. Thanks

**Comment by BIT-masterpy** [comment]
thingsboard.yml.  The problem should be in the yml file, and you can check the configuration information.
