### ISSUE TITLE
[Bug] OPC UA integration is not working

### ISSUE THREAD

**Issue by SuneethaYamani** [thingsboard/thingsboard#3621]
**Describe the bug**
I followed OPC UA integration YouTube video created it as per steps ,but it is not working

**Your Server Environment**

* own setup
  * cloud 
  * ThingsBoard PE 2.2.0 AMI with Cassandra-bad88275-3518-466b-8063-69eb1105cfec-ami-02aac36bf8bd57ce0.4

**Your Client Environment**

**windows VM on Azure for OPC UA server

**To Reproduce**
1. Go to 'OPC-UA integration'
2. Click on 'Events'
3. Scroll down to 'Life cycle events'

**Expected behavior**
Expected to create device group after OPC integration

**Screenshots**
![image](https://user-images.githubusercontent.com/37862040/96958870-44a71400-151c-11eb-9f2e-c33bdf5f0412.png)

![image](https://user-images.githubusercontent.com/37862040/96958709-dbbf9c00-151b-11eb-8de7-93cf1c40f36c.png)

**Additional context**
```
java.lang.RuntimeException: Failed to connect to OPC-UA server. Reason: Failed to connect to provided endpoint: opc.tcp://xxx.xxx.xxx.xxx:48010
	at org.thingsboard.server.service.integration.opcua.OpcUaIntegration.initClient(OpcUaIntegration.java:254)
	at org.thingsboard.server.service.integration.opcua.OpcUaIntegration.init(OpcUaIntegration.java:114)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.initIntegration(DefaultPlatformIntegrationService.java:577)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.getOrCreateThingsboardPlatformIntegration(DefaultPlatformIntegrationService.java:559)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.lambda$createIntegration$0(DefaultPlatformIntegrationService.java:225)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


```

**Comment by Ultrazombie** [comment]
Closed, as not active.
