### ISSUE TITLE
[Bug] Docker tb-cassandra : PSQL database thingsboard creation

### ISSUE THREAD

**Issue by mire22** [thingsboard/thingsboard#3662]
**Describe the bug**
I'm trying to run ThingsBoard Docker with Hybrid PostgreSQL and Cassandra database [thingsboard/tb-cassandra](https://hub.docker.com/r/thingsboard/tb-cassandra) but during the database creation, the following error occurs:
```Starting ThingsBoard installation ...
 ===================================================
 :: ThingsBoard ::       (v3.1.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: FATAL: database "thingsboard" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2586)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:113)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:222)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
        at org.postgresql.Driver.makeConnection(Driver.java:404)
        at org.postgresql.Driver.connect(Driver.java:272)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:66)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:194)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Unexpected error during ThingsBoard installation!
```

**Your Server Environment**
Host: Debian 9 stretch
Docker: Docker version 19.03.13, build 4484c46d9d
Thingsboard image: thingsboard/tb-cassandra:latest, id 58873b6cd186

**To Reproduce**
Execute:
```
docker run -it -p 9090:9090 -p 1883:1883 -p 5683:5683/udp --name mytb --restart always thingsboard/tb-cassandra
```
I choose not to mount volumes in order to avoid the problems with UID/GID.

**Expected behavior**
ThingsBoard should initialize databases and start.

**Additional context**
I have the same issue with Docker image thingsboard/tb-postgres.
I saw [here](https://github.com/thingsboard/thingsboard/issues/2223) and in the file ```start-db.sh``` [here](https://github.com/thingsboard/thingsboard/blob/master/msa/tb/docker-cassandra/start-db.sh) that it might be related to the existence of the file ```/data/.firstlaunch``` but I can't figure out how to solve the issue.

Thank you for your help!

**Comment by mire22** [comment]
Hi,
Looks like a basic `sudo reboot` solved my issue.
