### ISSUE TITLE
Client Disconnects on Publishing large json packet

### ISSUE THREAD

**Issue by sonychoudhary** [thingsboard/thingsboard#3677]
When trying to publish large telemetry data the clients gets disconnected 
* **demo.thingsboard.io**
sample json packet which contains array of data it publishes small packets like this one but for large packets with around 628 values and ts fields
{'data1': [{'values': {'a': '0', 'b': '1.6970', 'c': '1604487310330', 'd': 1604487310532, 'e': 'efgw', 'f': '1.1060', 'id': '0'}, 'ts': 1604487310532},{'values': {'a': '0', 'b': '1.6970', 'c': '1604487310330', 'd': 1604487310532, 'e': 'efgw', 'f': '1.1060', 'id': '0'}, 'ts': 1604487310532}]}

* Connectivity
  * **MQTT**
  
It will close the connection of the client and the message is also not published 
2020-11-04 16:27:46,216  INFO --- PublishController              : publish
2020-11-04 16:27:46,382 ERROR --- MqttFX ClientModel             : Error publishing to topic: v1/gateway/telemetry
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsSender.handleRunException(CommsSender.java:182) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsSender.run(CommsSender.java:163) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_181]
	at java.net.SocketOutputStream.socketWrite(Unknown Source) ~[?:1.8.0_181]
	at java.net.SocketOutputStream.write(Unknown Source) ~[?:1.8.0_181]
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source) ~[?:1.8.0_181]
	at java.io.BufferedOutputStream.write(Unknown Source) ~[?:1.8.0_181]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttOutputStream.write(MqttOutputStream.java:85) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	at org.eclipse.paho.client.mqttv3.internal.CommsSender.run(CommsSender.java:140) ~[org.eclipse.paho.client.mqttv3-1.2.0.jar:?]
	... 7 more
2020-11-04 16:27:46,395  INFO --- MqttFX ClientModel             : Broker connection lost: Resetting client.

**Comment by Karabiy** [comment]
In case if you are using the MQTT device API, as it seems, you can increase the       max_payload_size: "${NETTY_MAX_PAYLOAD_SIZE:65536}"
value, it is located in the netty subtopic for the mqtt topic.
