### ISSUE TITLE
Remote TCP Integration - Trying to Reconnect due to error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#3713]
**Description**
I am getting the following error at tb-tcp-udp-integration.log at my remote tcp integration server.

2020-11-12 15:31:23,377 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!
2020-11-12 15:31:26,376 [pool-3-thread-1] INFO  o.t.i.s.RemoteIntegrationManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!
2020-11-12 15:31:26,377 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!
2020-11-12 15:31:29,376 [pool-3-thread-1] INFO  o.t.i.s.RemoteIntegrationManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!
2020-11-12 15:31:29,377 [pool-3-thread-1] ERROR i.g.i.ManagedChannelOrphanWrapper - *~*~*~ Channel ManagedChannelImpl{logId=8133, target=35.235.XX.XX:9090} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:512)
        at org.thingsboard.integration.rpc.IntegrationGrpcClient.connect(IntegrationGrpcClient.java:101)
        at org.thingsboard.integration.service.RemoteIntegrationManagerService.lambda$scheduleReconnect$0(RemoteIntegrationManagerService.java:332)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-11-12 15:31:29,377 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!
2020-11-12 15:31:32,376 [pool-3-thread-1] INFO  o.t.i.s.RemoteIntegrationManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!
2020-11-12 15:31:32,386 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!
2020-11-12 15:31:35,376 [pool-3-thread-1] INFO  o.t.i.s.RemoteIntegrationManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!
2020-11-12 15:31:35,377 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!
2020-11-12 15:31:38,376 [pool-3-thread-1] INFO  o.t.i.s.RemoteIntegrationManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!
2020-11-12 15:31:38,390 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!
2020-11-12 15:31:41,376 [pool-3-thread-1] INFO  o.t.i.s.RemoteIntegrationManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!
2020-11-12 15:31:41,377 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!
2020-11-12 15:31:44,376 [pool-3-thread-1] INFO  o.t.i.s.RemoteIntegrationManagerService - Trying to reconnect due to the error: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception!
2020-11-12 15:31:44,387 [pool-3-thread-1] INFO  o.t.i.rpc.IntegrationGrpcClient - [5b426222-bfe8-8b7b-1e65-2ec18342ad67] Sending a connect request to the TB!

I setup server A (IP 34.71.XX.XX) to be my remote tcp integration server, where I installed tb-tcp-udp-thingsboard service. At conf file of this server I setup the following:

export PRC_HOST=35.235.XX.XX
export RPC_PORT=9090
export INTEGRATION_ROUTING_KEY=5b42xxxxxxxxxxxxxxxxxxxxxxxxxxxx67
export INTEGRATION_SECRET=oelxxxxxxxxxxxxxxxxxxxxxxxx3z

The server B (IP35.235.XX.XX) is where I have installed Thingsboard service which today I already receive some http integrations payloads. The TCP integration created was:

![tcp integration](https://user-images.githubusercontent.com/61842529/98962233-362d9600-24e5-11eb-93c0-cd7c8bed988c.png)

I already open port 9983 at server A, and both servers are being able to ping to each other.

Thanks for comments, suggestion and orientations.

**Environment**

 * OS:  Ubuntu 18.04.5 
 * ThingsBoard: 3.1.1 PE
 * Browser: Chrome
* Instances: Google Cloud Instances

**Comment by NN01010101** [comment]
Hi Freddy, how did you solve your problem?
