### ISSUE TITLE
[Bug] Handle non-JSON responses from REST API call node in rule chains

### ISSUE THREAD

**Issue by mojabyte** [thingsboard/thingsboard#3742]
If the response of the *REST API Call* node in the rule chain isn't in JSON format, the script node can't parse the inbound `msg` as it expected to be only in JSON format and it fails to execute the script.

The error message of the script node debug:
```
java.lang.RuntimeException: SyntaxError: Unexpected token < in JSON at position 0 in at line number 1
	at org.thingsboard.server.service.script.RemoteJsInvokeService.lambda$doInvokeFunction$1(RemoteJsInvokeService.java:205)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:242)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:232)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1164)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:789)
	at com.google.common.util.concurrent.TimeoutFuture$Fire.run(TimeoutFuture.java:116)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1164)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:727)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$null$0(DefaultTbQueueRequestTemplate.java:110)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$init$2(DefaultTbQueueRequestTemplate.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Your Server Environment**

* demo.thingsboard.io

**Your Client Environment**

**Desktop:**

* OS: macOS
* Browser chrome
* Version 86.0.4240.198 (Official Build) (x86_64)

**To Reproduce**
1. Go to Rule Chains
2. Create a new rule chain
3. Add a generator node and a rest API call node and connect it to the generator node to produce REST API calls
4. Add the URL of an API that its response isn't JSON, e.g. `http://demo.thingsboard.io/ruleChains`
5. Add a script node connected to the API call node

**Expected behavior**
The script node should execute its script without failure.

**Screenshots**
![image](https://user-images.githubusercontent.com/29512354/99381509-7b383a80-28e0-11eb-8e33-3b404c78b2b1.png)

**Additional context**
I think the *REST API call* node should check for the response body type and if it isn't in JSON, then it should add it to a JSON: `{ body: ${responseBody} }`, so it could be handled by other rule chain nodes.

**Comment by Ultrazombie** [comment]
ThingsBoard support only JSON messages.
