### ISSUE TITLE
Installationerror: authentication type 10 - trouble shooting

### ISSUE THREAD

**Issue by Centurio-Macro** [thingsboard/thingsboard#3788]
**Component**

 * Installation
 

**Description**
I get the following error message during installation of thingsboard
```
C:\Program Files (x86)\thingsboard>install.bat --loadDemo
Detecting Java version installed.
CurrentVersion 18
Java 1.8 found!
Installing thingsboard ...
 ===================================================
 :: ThingsBoard ::       (v3.1.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: Der Authentifizierungstyp 10 wird nicht unterst³tzt. Stellen Sie sicher, dass die Datei 'pg_hba.conf' die IP-Adresse oder das Subnetz des Clients enthõlt und dass der Client ein Authentifizierungsschema nutzt, das vom Treiber unterst³tzt wird.
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:634)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:217)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:52)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:216)
        at org.postgresql.Driver.makeConnection(Driver.java:404)
        at org.postgresql.Driver.connect(Driver.java:272)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:66)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:194)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

```
It tells:
authentication type 10 isnt supported
make sure that pg_hba.conf contains clients IP-address or subnet
make sure that client uses an authentication scheme that is supported by the driver

I´ve verified that Java is correctly installed. 
I´ve installed PostgreSQL 13.1 and the JDBC 42.2.18 42 driver
I´ve also succesfully started pgAdmin and created a new Database thingsboard.
As the thingsboard installation guide suggests, I created a new inbound rule for the windows firewall.

In other online discussions there were questions regarding these files. Thats how my files look like:
[pg_hab.conf](https://1drv.ms/u/s!Au1bXNOlBiy8y3RsIklx7kyzzCk9?e=j8cPgY)
[postgresql.conf](https://1drv.ms/u/s!Au1bXNOlBiy8y3aUMehgBLPg-kaZ?e=CWWbpU)
[thingsboard.yml](https://1drv.ms/u/s!Au1bXNOlBiy8y3ftSnHG7x3zu12t?e=PISwiw)
I can´t detect any errors.

I took a look into the thingsboard log file. There is this error logged, right before the above mentioned `org.postgresql.util.PSQLException` notification.

```
2020-11-30 12:19:34,535 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2020-11-30 12:19:35,621 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
org.postgresql.util.PSQLException: Der Authentifizierungstyp 10 wird nicht unterstützt. Stellen Sie sicher, dass die Datei 'pg_hba.conf' die IP-Adresse oder das Subnetz des Clients enthält und dass der Client ein Authentifizierungsschema nutzt, das vom Treiber unterstützt wird.
```

### Questions:
Any suggestions for further trouble shooting?
After installing, where should I save the `postgresql-42.2.18.jar` driver file?

**Environment**

 * OS:  Windows 10 1909
 * ThingsBoard: 3.1.1
 * Browser: Firefox 83
 * JDK 8
 * PostgreSQL 13.1
 * Driver: 42.2.18 JDBC 42

**Comment by Backdraft007** [comment]
Hi,
maybe it helps if you change password encryption to md5.
https://stackoverflow.com/questions/64210167/unable-to-connect-to-postgress-db-due-to-the-authentication-type-10-is-not-suppo

**Comment by Centurio-Macro** [comment]
> 
> 
> Hi,
> maybe it helps if you change password encryption to md5.
> https://stackoverflow.com/questions/64210167/unable-to-connect-to-postgress-db-due-to-the-authentication-type-10-is-not-suppo

Thx for your quick reaction!

I tried, however got the **same error message.** 

I edited: postgresql.conf
```
# - Authentication -

#authentication_timeout = 1min		# 1s-600s
password_encryption = md5		# md5 or scram-sha-256
#db_user_namespace = off

# GSSAPI using Kerberos
#krb_server_keyfile = ''
#krb_caseins_users = off

# - SSL -
```

and: pg_hba.conf
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     md5
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

```

**Comment by Backdraft007** [comment]
You changed also your password?

**Comment by Centurio-Macro** [comment]
> 
> 
> You changed also your password?

No I left that untouched.

What did solve it in the end was this kind [advice](https://github.com/thingsboard/thingsboard/issues/3667).
After installment via PostgreSQL Stackbuilder, I needed to put the `postgresql-42.2.18.jar` driver file into the **JDK directory**, i.e. C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\jre\lib\ext

Instead I put it into thingsboard and PostgreSQL directory.

**Comment by kevinunger** [comment]
Thanks @Centurio-Macro that fixed the issue for me as well.

**Comment by studyy-yy** [comment]
Hello, I also have this problem now. Do you remember how to solve it?
