### ISSUE TITLE
[Question] Which fromVersion to use when upgrading from 2.5.1 to 2.5.2

### ISSUE THREAD

**Issue by mfalkvidd** [thingsboard/thingsboard#3820]
**Component**

 * Installation

**Description**

I tried to upgrade from 2.5.1 to 2.5.2 on Ubuntu using the instructions at
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-252

The database used is Cassandra.

The instructions state:
```
# Finally, execute upgrade script and specify your previous ThingsBoard version. 
$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.3
```
I don't understand why --fromVersion=2.4.3 is used here. The install page says
> NOTE: These upgrade steps are applicable for ThingsBoard version 2.5.1. In order to upgrade to 2.5.2 you need to upgrade to 2.5.1 first.

Since I am upgrading from 2.5.1 I tried `$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.5.1` but got this result:
```
 ===================================================
 :: ThingsBoard ::       (v2.5.2)
 ===================================================

Starting ThingsBoard Upgrade from version 2.5.1 ...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 2.5.1
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:169)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Unexpected error during ThingsBoard installation!
```

Therefore, I tried fromVersion=2.4.3 as the installation instructions say. But that didn't work either:
```
thingsboard@thingsboard-1:~$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.3
 ===================================================
 :: ThingsBoard ::       (v2.5.2)
 ===================================================

Starting ThingsBoard Upgrade from version 2.4.3 ...
Upgrading ThingsBoard from version 2.4.3 to 2.5.0 ...
Updating schema ...
Updating ts ...
Schema updated.
Updating schema ...
Updating attributes ...
Updating tenant...
Schema updated.
Upgrading ThingsBoard from version 2.5.0 to 2.5.1 ...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade Cassandra database, unsupported fromVersion: 2.5.0
        at org.thingsboard.server.service.install.CassandraTsDatabaseUpgradeService.upgradeDatabase(CassandraTsDatabaseUpgradeService.java:52)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:146)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed
```

**Environment**

 * OS:  Ubuntu 18.04 LTS
 * ThingsBoard: 2.5.1 / 2.5.2
 * Browser: Not applicable

**Comment by trikimiki** [comment]
Upgrade script is not required here. Try:

```
$ sudo systemctl daemon-reload 
$ sudo service thingsboard restart
```

And then service status should show something like this:

```
$ sudo service thingsboard status
● thingsboard.service - thingsboard
     Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-12-09 12:32:26 EET; 5s ago
   Main PID: 17560 (thingsboard.jar)
      Tasks: 17 (limit: 4656)
     Memory: 157.2M
     CGroup: /system.slice/thingsboard.service
             ├─17560 /bin/bash /usr/share/thingsboard/bin/thingsboard.jar
             └─17593 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/data -Xloggc:/var/log/thingsboard/gc.log -XX:+IgnoreUnrecognizedVMOpti>

гру 09 12:32:26 tbtest-VirtualBox systemd[1]: Started thingsboard.
гру 09 12:32:28 tbtest-VirtualBox thingsboard.jar[17593]:  ===================================================
гру 09 12:32:28 tbtest-VirtualBox thingsboard.jar[17593]:  :: ThingsBoard ::       (v2.5.2)
гру 09 12:32:28 tbtest-VirtualBox thingsboard.jar[17593]:  ===================================================

```

**Comment by mfalkvidd** [comment]
Great, thanks! How do we know when the upgrade script is required and when it isn't required?

**Comment by trikimiki** [comment]
We're working on fixing/updating docs, so it will be specified there ASAP - check for updates.
