### ISSUE TITLE
[Bug] Upgrade CE from 3.1.1 to 3.2.0

### ISSUE THREAD

**Issue by brunoVanDame** [thingsboard/thingsboard#3841]
**Describe the bug**
When following the upgrade instuctions at [https://thingsboard.io/docs/user-guide/install/upgrade-instructions/](url) I get the below error : 

>  ===================================================
 :: ThingsBoard ::       (v3.2.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.1.1 ...
Upgrading ThingsBoard from version 3.1.1 to 3.2.0 ...
Load TTL functions ...
Functions successfully loaded!
Load Drop Partitions functions ...
Functions successfully loaded!
Updating schema ...
Creating default tenant profiles...
Failed updating schema!!!
**java.lang.NullPointerException: null**
	**at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl.saveTenantProfile(TenantProfileServiceImpl.java:90)**
	at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl$$FastClassBySpringCGLIB$$67564a4a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl$$EnhancerBySpringCGLIB$$894e945b.saveTenantProfile(<generated>)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createDefaultTenantProfiles(DefaultSystemDataLoaderService.java:160)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:381)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:183)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Updating data from version 3.1.1 to 3.2.0 ...
Updating system data...
Upgrade finished successfully!
ThingsBoard upgraded successfully!

Thingsboard does not start anymore.

**Your Server Environment**
The CE 3.1.1 is an installation on a **Cent OS 8**, release (`rpm -q centos_release`) **centos-release-8.2-2.2004.0.2.el8.x86_64.** in a VirtualBox virutal machine.

**Kafka** : kafka_2.13-2.6.0

**Apache** : (`httpd -version`) Server version: Apache/2.4.37 (centos), Server built:   Sep 15 2020 15:41:16.

**Database** : (`psql -v`) psql (PostgreSQL) 12.5

**Additional context**
It is a very basic installation of Thingboard CE v3.1.1.
Not many things have been done in the interface.
Was learning how to use the application guided by : [https://thingsboard.io/docs/getting-started-guides/helloworld/](url)
Arrived at step 4 which needs version 3.2 to create device profiles.
Did upgrade resulting in error and unusable system.

I took a look at the code, I guess it is the line causing problems : `TenantProfileServiceImpl` -> `cache.evict(Collections.singletonList(savedTenantProfile.getId().getId()));`
The id is missing ?
For this reason I tried to add some info in the one and only default tenant profile but to no avail.

**Reproduce**

Do a basic installation of CE v 3.1.1 with kafka and progress.
Follow the helloworld steps till step 4.
Upgrade to v 3.2

**Comment by trikimiki** [comment]
Hello!

Tenant profile tables are usually added when upgrading to 3.1.1 (while running "update.sh --FromVersion=x.x.x").

I suggest trying using "--FromVersion=3.0.1" when executing "upgrade.sh".

**Comment by brunoVanDame** [comment]
Hi There !
Thanks for your reaction.

I tried your suggestion but, unfortunately, to no avail.
This is the output I get, quiet the same : 

 ===================================================
 :: ThingsBoard ::       (v3.2.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.0.1 ...
Upgrading ThingsBoard from version 3.0.1 to 3.1.0 ...
Updating schema ...
Schema updated.
Updating data from version 3.0.1 to 3.1.0 ...
Upgrading ThingsBoard from version 3.1.0 to 3.1.1 ...
Updating schema ...
Schema updated.
Upgrading ThingsBoard from version 3.1.1 to 3.2.0 ...
Load TTL functions ...
Functions successfully loaded!
Load Drop Partitions functions ...
Functions successfully loaded!
Updating schema ...
Creating default tenant profiles...
Failed updating schema!!!
**java.lang.NullPointerException: null
	at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl.saveTenantProfile(TenantProfileServiceImpl.java:90)**
	at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl$$FastClassBySpringCGLIB$$67564a4a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl$$EnhancerBySpringCGLIB$$1b47ad4a.saveTenantProfile(<generated>)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createDefaultTenantProfiles(DefaultSystemDataLoaderService.java:160)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:381)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:183)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Updating data from version 3.1.1 to 3.2.0 ...
Updating system data...
Upgrade finished successfully!
ThingsBoard upgraded successfully!

Anything I can do ?

**Comment by trikimiki** [comment]
Tried clean install on VM, everything went OK. Here's my history 
```
$ history
    1  sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    2  sudo yum install java-1.8.0-openjdk
    3  java -version
    #...
    5  wget https://github.com/thingsboard/thingsboard/releases/download/v3.1.1/thingsboard-3.1.1.rpm
    6  sudo rpm -Uvh thingsboard-3.1.1.rpm
    7  sudo yum update
    8  sudo yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    9  sudo dnf -qy module disable postgresql
   #...
   13  sudo dnf -y install postgresql12-12.5-1PGDG.rhel8.x86_64
   #...
   15  sudo dnf -y install postgresql12-server-12.5-1PGDG.rhel8.x86_64
   #...
   17  sudo /usr/pgsql-12/bin/postgresql-12-setup initdb
   18  sudo systemctl start postgresql-12
   19  sudo systemctl enable --now postgresql-12
   20  sudo su - postgres
   # set postgres user password
   21  sudo nano /var/lib/pgsql/12/data/pg_hba.conf
   22  sudo systemctl restart postgresql-12.service
   23  psql -U postgres -d postgres -h 127.0.0.1 -W
   # create DB
   24  sudo nano /etc/thingsboard/conf/thingsboard.conf
   25  sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
   26  sudo chmod +x /usr/local/bin/docker-compose
   27  docker-compose --version
   #...
   29  sudo yum install -y yum-utils
   30  sudo yum-config-manager     --add-repo     https://download.docker.com/linux/centos/docker-ce.repo
   #...
   33  sudo yum install docker-ce docker-ce-cli containerd.io
   34  sudo systemctl start docker
   #...
   36  sudo systemctl enable --now docker
   37  sudo docker run hello-world
   38  sudo chmod 666 /var/run/docker.sock
   #...
   43  sudo yum install git
   #...
   45  git clone https://github.com/wurstmeister/kafka-docker.git
   #...
   47  cd kafka-docker/
   48  docker-compose up -d
   49  sudo nano /etc/thingsboard/conf/thingsboard.conf
   #...
   55  cd ..
   #...
   57  sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
   58  docker ps
   59  sudo firewall-cmd --zone=public --add-port=8080/tcp --permanent
   60  sudo firewall-cmd --reload
   61  sudo service thingsboard start
   #...
   # upgrade
   64  wget https://github.com/thingsboard/thingsboard/releases/download/v3.2/thingsboard-3.2.rpm
   65  sudo rpm -Uvh thingsboard-3.2.rpm
   66  sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.1.1
   67  sudo service thingsboard start
   #...
```
Do you see anything you did differently?

**Comment by brunoVanDame** [comment]
There are differences.
I use Cent OS 8 and I did some steps following
[https://thingsboard.io/docs/getting-started-guides/helloworld/](url).

Till step 4 where I needed version 3.2.0.

So my database content is not exactly the same with yours.
Yours is still the demo database.

I guess the problem is situated somewhere in the data contained in the DB.

**Comment by justsomeguyontheinternet** [comment]
i have the same/similar problem. i installed 3.1.1 docker based on instructions here:
https://thingsboard.io/docs/user-guide/install/docker/

running the upgrade instructions here:
https://thingsboard.io/docs/user-guide/install/docker/#upgrading

my upgrade has same issue. i ran without --fromVersion (since instructions didn't mention it)
i didn't save the output, but it looks like it starts with some very early version and then does piecemeal upgrades e.g. 2.0 -> 2.1, then 2.1 -> 2.2. all of these basically conclude with "already up to date". it is the 3.1.1 -> 3.2.0 portion of the script that fails with a similar message here, some stack dump, though i didn't notice exactly what caused the error.

**Comment by justsomeguyontheinternet** [comment]
i ran it again, and it generated another error, but this time in the 3.0.1 to 3.1.0 upgrade section

![image](https://user-images.githubusercontent.com/34630628/102695811-b7203180-41f7-11eb-99cd-479496fc3823.png)

--fromVersion=3.1.1 had no effect. it seemed to ignore the parameter and start upgrading from an earlier 2.x.x version.

**Comment by brunoVanDame** [comment]
I can provide someone with my database content to help ?

**Comment by brunoVanDame** [comment]
Or even my virtual machine  (virtual box) ?

**Comment by justsomeguyontheinternet** [comment]
tried again, hoping newer releases fixed this issue, but... nope. issue persists. took a closer look at upgrade instructions, but nothing came up. someone suggested merging operation, but this seems to not apply to postgres install.

so... still stuck.

**Comment by justsomeguyontheinternet** [comment]
i took a look at some unrelated upgrade bugs. i was able to upgrade my install by changing the /data/.upgradeversion file contents to 3.1.1, they were 2.4.2 by default. i also dropped the --fromVersion argument to the upgrade script that seemed to have no effect. after that everything seemed to work. the issue i saw may have been limited to docker installations.
