### ISSUE TITLE
[Bug] Rule chain will have errors after a few days of execution.

### ISSUE THREAD

**Issue by Krong1997** [thingsboard/thingsboard#3845]
Hello, I have a trouble. I create three rule chains as follow.
1.Root Rule Chain
![Screenshot from 2020-12-14 10-39-20](https://user-images.githubusercontent.com/71483852/102034461-ffef7900-3df8-11eb-937b-da09630f579a.png)
2.Threshold entry
![Screenshot from 2020-12-14 10-41-40](https://user-images.githubusercontent.com/71483852/102034445-f9610180-3df8-11eb-8023-79a50a5cd2ec.png)
**3.mem-loading**
This rule chain based on "upsert threshold settings" node settings to do something.
Finally, compare it to something and decide whether to create an alarm.
The system was working normally, but **after a few days or several hours** it will start to show errors. 
![Screenshot from 2020-12-14 09-32-53](https://user-images.githubusercontent.com/71483852/102031252-5c01cf80-3df0-11eb-9fd5-4344adc0ab25.png)

**Describe the bug**
Originally TB rule chain executed normally as follows:
![Screenshot from 2020-12-14 09-29-55](https://user-images.githubusercontent.com/71483852/102030782-f9f49a80-3dee-11eb-8320-85822a4cbb3d.png)

After a few days or several hours of system execution , it will start to show errors as follows:
![Screenshot from 2020-12-14 09-31-14](https://user-images.githubusercontent.com/71483852/102030837-27414880-3def-11eb-966a-6f34d5cfa541.png)

Error details as follow:

```
com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out: com.google.common.util.concurrent.SettableFuture@4a2d6f72[status=PENDING]
```

```
java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at org.thingsboard.server.service.script.AbstractJsInvokeService.invokeFunction(AbstractJsInvokeService.java:70)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeScriptAsync(RuleNodeJsScriptEngine.java:223)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeUpdateAsync(RuleNodeJsScriptEngine.java:117)
	at org.thingsboard.rule.engine.transform.TbTransformMsgNode.transform(TbTransformMsgNode.java:56)
	at org.thingsboard.rule.engine.transform.TbAbstractTransformNode.onMsg(TbAbstractTransformNode.java:46)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:112)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:45)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:121)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I can only restart TB container to solve this trouble. Although it can temporarily solve the problem, it will appear again after a while. 

**My settings as follows**:
Asset : 1 
Device : 1
Post data frequency : 1/5s
2020-12-07 16:31:46 starting upload data every 5s
2020-12-11 about 07:00:00 starting show errors 

**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard Version 3.1.1
  * Docker version 19.03.13
  * OS Version LINUX 20.04 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: LINUX 20.04 LTS
* Browser chrome
* Version 86.0.4240.111 (Official Build) (64-bit)

**Your Device**

* Connectivity
  * HTTP 
* Content-Type: application/json (JSON Object)

**To Reproduce**

1. Create a device name as "device1"
2. Create an asset name as "group"
3. Add "device1" device to "group" asset outbound relations
4. Create a rule chain name as "Threshold entry"
5. Create a rule chain name as "mem-loading"
6. Add "group" asset to "mem-loading" rule chain outbound relations
7. Upload "device1" device client attribute at first time  
8. Upload "device1" device telemetry data every 5s 

Rule chain settings

"upsert threshold settings" rule chain node jsScript as follow:
```js
    const newMetadata = {
      ...metadata,
      "alermMsg": "Memory used is greater then 60"",
      "condition": "0",
      "dataSource": "MEM.memUsed",
      "denominator": "MEM.Cap",
      "isRatio": "true",
      "isSendEmail": "true",
      "thresholdName": "mem-loading",
      "thresholdValue": "60",
      "toEmail": "xxx@gmail.com"
    };
    return {
      msg: msg,
      metadata: newMetadata,
      msgType: msgType
    };
```
"upsert threshold settings" rule chain node **input metadata** as follow:
```js
{
    "deviceName": "rule-test1",
    "deviceType": "device",
    "ts": "1607619783587"
}
```

"upsert threshold settings" rule chain node **output metadata** as follow:
```js
{
    "alermMsg": "Memory used is greater then 60",
    "condition": "0",
    "dataSource": "MEM.memUsed",
    "denominator": "MEM.Cap",
    "deviceName": "rule-test1",
    "deviceType": "device",
    "isRatio": "true",
    "isSendEmail": "true",
    "thresholdName": "mem-loading",
    "thresholdValue": "60",
    "toEmail": "xxx@gmail.com",
    "ts": "1607619783587"
}
```
"upsert threshold settings" rule chain node **input message** as follow (Same as output message):
```js
{
    "Dev": "Device1",
    "CPU": {
        ...omit
    },
    "MEM": {
        "memUsed": 5280787.469970813,
        "temp": 85.7706152474597
    },
    ...omit
    "time": 1599806557
}
```

Device settings as follow:
device client attribute
```
MEM:{
  "Cap": 20971520,
  "Slot":
  {
    "0":
      {memory1 infos},
    "1": 
      {memory2 infos}
  }
}
```

**Expected behavior**
Every time the device uploads data, it will enter the rule chain for inspection. If the threshold is exceeded, an alarm will be created.

**Screenshots**
"group" asset relations
![Screenshot from 2020-12-14 10-52-15](https://user-images.githubusercontent.com/71483852/102035066-7f317c80-3dfa-11eb-9ebd-b23d60d2a461.png)
"mem-loading" rule chain relations
![Screenshot from 2020-12-14 10-53-04](https://user-images.githubusercontent.com/71483852/102035112-996b5a80-3dfa-11eb-9920-06ba46ed30a6.png)

**Comment by ipa-hanna** [comment]
I have also encountered similar problems.

**Comment by ashvayka** [comment]
Hi @Krong1997, most likely, one of the messages that arrived causes an error in your custom JS function and this is something that causes the script to fail. It should automatically recover after 1 minute. Then, subsequent messages may cause the error again. Please try to find the first Failure. This will provide you a hint of how to fix it.

**Comment by Krong1997** [comment]
Hi @ashvayka, thanks for your reply !
So this is related to the data uploaded by the device?

**Comment by Krong1997** [comment]
Hi, I have a new trouble. I checked the log of the rule chain container. I found the ERROR log as follow :

```
2020-12-18 01:20:24,215 [tb-rule-engine-consumer-23-thread-3] ERROR o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=re-Main-consumer-tb-rule-engine1, groupId=re-Main-consumer-tb-rule-engine1] Offset commit with offsets {tb_rule_engine.main.8-0=OffsetAndMetadata{offset=484408, leaderEpoch=0, metadata=''}, tb_rule_engine.main.0-0=OffsetAndMetadata{offset=233492, leaderEpoch=0, metadata=''}, tb_rule_engine.main.6-0=OffsetAndMetadata{offset=379, leaderEpoch=0, metadata=''}, tb_rule_engine.main.4-0=OffsetAndMetadata{offset=320, leaderEpoch=0, metadata=''}, tb_rule_engine.main.2-0=OffsetAndMetadata{offset=646, leaderEpoch=0, metadata=''}} failed
org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.sendOffsetCommitRequest(ConsumerCoordinator.java:820)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.doCommitOffsetsAsync(ConsumerCoordinator.java:645)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsAsync(ConsumerCoordinator.java:612)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitAsync(KafkaConsumer.java:1524)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitAsync(KafkaConsumer.java:1493)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitAsync(KafkaConsumer.java:1470)
	at org.thingsboard.server.queue.kafka.TbKafkaConsumerTemplate.doCommit(TbKafkaConsumerTemplate.java:101)
	at org.thingsboard.server.queue.common.AbstractTbQueueConsumerTemplate.commit(AbstractTbQueueConsumerTemplate.java:130)
	at org.thingsboard.server.service.queue.DefaultTbRuleEngineConsumerService.lambda$launchConsumer$5(DefaultTbRuleEngineConsumerService.java:189)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Whenever this error appears. All rule chains will failure at the same time. 
Can I solve this by modifying kafka.env or other .env file ?
![image](https://user-images.githubusercontent.com/71483852/102564739-05113880-4117-11eb-8e6f-34db93d533ae.png)

**Comment by Krong1997** [comment]
We update thingsboard to 3.2.0 to resolve this bug.

**Comment by xiddjp** [comment]
> We update thingsboard to 3.2.0 to resolve this bug.

We still encountered this issue on version 3.3.4.1. How did you solve it?

**Comment by Vishalbuu** [comment]
Hi, I am also encountering this problem on Version 
![Screenshot from 2024-03-08 13-17-27](https://github.com/thingsboard/thingsboard/assets/114239141/cc821aa8-3039-4e9c-8175-bcf6475dc3bc)
