### ISSUE TITLE
Fetching Historical Timeseries Data using Agg SUM Problem

### ISSUE THREAD

**Issue by chunyeow** [thingsboard/thingsboard#391]
My TB facing the following problem and become unresponsive if I fetch one day historical data using agg - SUM:

2017-11-01 20:57:51,121 [https-jsse-nio-0.0.0.0-8083-exec-7] INFO  o.a.t.w.s.WsRemoteEndpointImplServer - Failed to close the ServletOutputStream connection cleanly
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.apache.tomcat.util.net.SecureNioChannel.flush(SecureNioChannel.java:143)
        at org.apache.tomcat.util.net.SecureNioChannel.close(SecureNioChannel.java:494)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.close(NioEndpoint.java:1165)
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doClose(WsRemoteEndpointImplServer.java:171)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.close(WsRemoteEndpointImplBase.java:710)
        at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:613)
        at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:526)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.close(WsHttpUpgradeHandler.java:233)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:155)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2017-11-01 20:57:51,121 [https-jsse-nio-0.0.0.0-8083-exec-7] INFO  o.t.s.c.p.PluginWebSocketHandler - [2] Session is closed

**Comment by vparomskiy** [comment]
Please update to the latest version. Issue should be already resolved.

**Comment by vparomskiy** [comment]
Few issues with web sockets were fixed in Thingsboard 2.1.3 . Bit I recommend to update to the latest version 2.2 (Note that v2.3 will be available in few weeks)

**Comment by LeoMorgan113** [comment]
Hi @chunyeow,
All issues with WebSockets were fixed in v.3.2.2
Please, refer to https://thingsboard.io/docs/reference/releases/
