### ISSUE TITLE
Mqtt Publish error from  ESP8266

### ISSUE THREAD

**Issue by sijokwork** [thingsboard/thingsboard#392]
Hi,

i am unable to track down the error with mqtt publish error ,where i am currently sending message from esp8266 which running esp-open-rtos with paho mqtt client ,the below are the log from thingboard log folder

2017-11-02 12:20:54,537 [nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt1253] Processing connect msg for client: ESP-600194803E7D!
2017-11-02 12:21:10,774 [nioEventLoopGroup-5-5] WARN  o.t.s.t.mqtt.MqttTransportHandler - [mqtt1253] Failed to process publish msg [v1/devices/me/telemetry][-1]
org.thingsboard.server.common.transport.adaptor.AdaptorException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 53 path $
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToTelemetryUploadRequest(JsonMqttAdaptor.java:236)
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToActorMsg(JsonMqttAdaptor.java:60)
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToActorMsg(JsonMqttAdaptor.java:47)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processDevicePublish(MqttTransportHandler.java:178)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processPublish(MqttTransportHandler.java:150)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processMqttMsg(MqttTransportHandler.java:112)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.channelRead(MqttTransportHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 53 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToTelemetryUploadRequest(JsonMqttAdaptor.java:234)
	... 26 common frames omitted
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 53 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1416)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 28 common frames omitted
2017-11-02 12:21:10,776 [nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt1253] Closing current session due to invalid publish msg [v1/devices/me/telemetry][-1]

any ideas what causes the error 
sijo k

**Comment by nmenoni** [comment]
How is the message you are trying to publish?

2017-11-02 9:54 GMT-03:00 sijokwork <notifications@github.com>:

**Comment by xjz** [comment]
I think "com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException" tells the reason,The Message you published probably is invalid json string

**Comment by sijokwork** [comment]
sorry for late reply because of holidays

**Comment by sijokwork** [comment]
im able to upload data via external mqtt with Gateway configuration
