### ISSUE TITLE
[Bug] Rule Engine can't load originator fields from Entity Views

### ISSUE THREAD

**Issue by robertoenr** [thingsboard/thingsboard#3928]
I have a Device, an EntityView linked to Device, and a Relation from EntityView to Device. Also have a Generator rule node to push fake data to system.

When I post a simple telemetry from Device to Thingsboard, I do the following steps after "Save Timeseries" node:

- I change the originator to an Entity View related to the Device originator. I've check that the Entity View is loaded OK.
- After that, I try to use the "originator fields" node, in order to load the start and end dates from the Entity View (also tried to load the name and type fields, but same issue), but it throws the following exception: 

`org.thingsboard.rule.engine.api.TbNodeException: Unexpected original EntityType 0028cf80-51e4-11eb-87e8-917f5d0d502a
	at org.thingsboard.rule.engine.util.EntitiesFieldsAsyncLoader.findAsync(EntitiesFieldsAsyncLoader.java:62)
	at org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsNode.putEntityFields(TbGetOriginatorFieldsNode.java:70)
	at org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsNode.onMsg(TbGetOriginatorFieldsNode.java:59)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:132)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:45)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:121)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)`

Note: the timeseries from device are stored and saved OK on Device and Entity View.

**Your Server Environment**
* own setup
  * local server on a SBC
  * ThingsBoard Version 3.2.0
  * Armbian ARM64 with 5.9.0 kernel based on Ubuntu Focal

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: MacOS 10.13.6 High Sierra
* Browser chrome
* Version 87

**Your Device**

Generator node in rule engine

**To Reproduce**
1. Create a device.
2. In Rule Engine create a Generator node for device.
3. Create an EntityView associated to Device. And create a relation from EntityView to Device.
4. In Rule Engine, after "Save timeseries" node, put a "change originator" node, to the related Entity View.
4. In Rule Engine, after "change originator" node, put a "originator fields" node, with fields "name" and "type". Enable debug, and see the errors over this node.

**Expected behavior**
The expected behaviour is that the "originator fields" node could load the fields without errors.

**Comment by vvlladd28** [comment]
Hi @robertoenr,
Thank you for the report. Fix will be added in the new version.

**Comment by ashvayka** [comment]
Fix for this item is in the master branch now.

**Comment by Shedaim** [comment]
Same happens for type "ENTITY_GROUP"

**Comment by Shedaim** [comment]
> 
> 
> Fix for this item is in the master branch now.
Same happens for type "ENTITY_GROUP"

**Comment by robertoenr** [comment]
Hi, thank you for you fast fix!
Any way to add the Start/End dates of an ENTITY_VIEW with the "Originator Fields" node?
