### ISSUE TITLE
[Question] navigate from main dashboard to dashboard state depending on the device attribute

### ISSUE THREAD

**Issue by Amith828** [thingsboard/thingsboard#3976]
Hi Guys,

I'm trying to setting up a Custom Action in the Table widget to navigate from main dashboard to dashboard state, depending on the device attribute.

I got the code from here : https://github.com/thingsboard/thingsboard/issues/1655
```
var $injector = widgetContext.$scope.$injector;
var attributeService = $injector.get('AttributeService');
var types=$injector.get('types');
$injector.get('deviceService').getDevice(entityId.id).then(function(device){
    attributeService.getEntityAttributesValues(entityId.entityType,entityId.id,types.attributesScope.client.value,'Model',{
        ignoreLoading: true
    }
    ).then((attributes) =>{
        var newParams = {};
        newParams.entityId = entityId;
        newParams.entityName = entityName;
        if( attribute[0].value == 'RN'){
            widgetContext.stateController.openState('RN', newParams, true);
        }else if( attributes[0].value == 'DF'){
            widgetContext.stateController.openState('DF', newParams, true);
        }else if( attributes[0].value == 'FR'){
            widgetContext.stateController.openState('FR', newParams, true);
        }else{
            widgetContext.stateController.openState('unknown', newParams, true);
        }
    });
});

function openDashboardState(stateId, device) {
    var params = {
        entityId: entityId,
        entityName: device.name,
        entityLabel: device.label
    }

    widgetContext.stateController.openState(stateId, params, false);
}
```

**This is the error that I get:**
```
1.bf36d0884e8a014bfcaf.js:1 NullInjectorError: R3InjectorError(e)[getEntityAttributesValues -> getEntityAttributesValues -> getEntityAttributesValues -> getEntityAttributesValues]: 
  NullInjectorError: No provider for getEntityAttributesValues!
    at e.value (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:769481)
    at e.value (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:830565)
    at e.value (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:830565)
    at e.value (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:830565)
    at e.value (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:830565)
    at n.value (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:926098)
    at Object.get (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:909718)
    at vr (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:783883)
    at e.value (https://my.sol-chip.com/polyfills.594effbea12271e731a5.js:1:785663)
    at eval (eval at e.handleWidgetAction (https://my.sol-chip.com/1.bf36d0884e8a014bfcaf.js:1:2169937), <anonymous>:4:34)
e.handleWidgetAction @ 1.bf36d0884e8a014bfcaf.js:1
e.onRowClick @ 1.bf36d0884e8a014bfcaf.js:1
e_mat_row_25_Template_mat_row_click_0_listener @ template.html:103
Jl @ polyfills.594effbea12271e731a5.js:1
i @ polyfills.594effbea12271e731a5.js:1
(anonymous) @ polyfills.594effbea12271e731a5.js:1
e.invokeTask @ polyfills.594effbea12271e731a5.js:1
t.runTask @ polyfills.594effbea12271e731a5.js:1
t.invokeTask @ polyfills.594effbea12271e731a5.js:1
v @ polyfills.594effbea12271e731a5.js:1
y @ polyfills.594effbea12271e731a5.js:1

```
**Using Thingsboard**: 3.2.0 v

Someone did it before and can help?

**Comment by vvlladd28** [comment]
Hi @Amith828,
In the new version of TB 3.0, we update the Angular version, and some features need to be updated to work correctly on the new version. Examples are available in Custom action (with HTML template).
To make your code work, you need to change:
```
$injector.get('deviceService').getDevice(entityId.id).then(function(device){
    attributeService.getEntityAttributesValues(entityId.entityType,entityId.id,types.attributesScope.client.value,'Model',{
        ignoreLoading: true
    }
    ).then((attributes) =>{
```
=> 
```
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => {
    $injector.get(widgetContext.servicesMap.get('attributeService')).getEntityAttributes(device, 'CLIENT_SCOPE', ['Model'], {
        ignoreLoading: true
    }).subscribe((attributes) =>
```

**Comment by t0mmyz7** [comment]
Hi @vvlladd28 
We are trying to make this same behavior but it is not working. I did look in the custom action with HTML for example but couldn't put it together.

Any chance you can provide a full code example for custom action that will, based on attribute "model" or device profile (type), Navigate to a different dashboard state?

That would be very helpful and useful thank you!

**Comment by t0mmyz7** [comment]
@vvlladd28 this is my code adaption and error, any advice?

```
var $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => {
    $injector.get(widgetContext.servicesMap.get('attributeService')).getEntityAttributes(device, 'CLIENT_SCOPE', ['active'], {
        ignoreLoading: true
    }).subscribe((attributes) =>{
        var newParams = {};
        newParams.entityId = entityId;
        newParams.entityName = entityName;
        if( attribute[0].value == 'true'){
            widgetContext.stateController.openState('test', newParams, true);
        }else if( attributes[0].value == 'DF'){
            widgetContext.stateController.openState('DF', newParams, true);
        }else if( attributes[0].value == 'FR'){
            widgetContext.stateController.openState('FR', newParams, true);
        }else{
            widgetContext.stateController.openState('test', newParams, true);
        }
    });
});

function openDashboardState(stateId, device) {
    var params = {
        entityId: entityId,
        entityName: device.name,
        entityLabel: device.label
    }

    widgetContext.stateController.openState(stateId, params, false);
}
```

this is the error:
```

error: "<!doctype html><html lang=\"en\"><head><title>HTTP Status 400 – Bad Request</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>"
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit()
 }
​
message: "Http failure response for https://my.sol-chip.com/api/plugins/telemetry/undefined/[object%20Object]/values/attributes/CLIENT_SCOPE?keys=active: 400 OK"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 400
​
statusText: "OK"
​
url: "https://my.sol-chip.com/api/plugins/telemetry/undefined/[object%20Object]/values/attributes/CLIENT_SCOPE?keys=active"
​
<prototype>: Object { … }
polyfills.060276757d6eacd2fd6e.js:1:41585
```

**Comment by vvlladd28** [comment]
Hi @t0mmyz7,

Full code example used custom action for navigate dashboard state:
```
var $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => {
    $injector.get(widgetContext.servicesMap.get('attributeService')).getEntityAttributes(device.id, 'SERVER_SCOPE', ['active'], {
        ignoreLoading: true
    }).subscribe((attributes) =>{
        var newParams = {};
        newParams.entityId = entityId;
        newParams.entityName = entityName;
        if( attributes[0].value === true){
            widgetContext.stateController.openState('test', newParams, true);
        }else if( attributes[0].value === 'DF'){
            widgetContext.stateController.openState('DF', newParams, true);
        }else if( attributes[0].value === 'FR'){
            widgetContext.stateController.openState('FR', newParams, true);
        }else{
            widgetContext.stateController.openState('test', newParams, true);
        }
    });
});

function openDashboardState(stateId, device) {
    var params = {
        entityId: entityId,
        entityName: device.name,
        entityLabel: device.label
    }

    widgetContext.stateController.openState(stateId, params, false);
}
```
or example used device type to navigate from dashboard state:
```
var $injector = widgetContext.$scope.$injector;
let attributeService = $injector.get(widgetContext.servicesMap.get('attributeService'));
$injector.get(widgetContext.servicesMap.get('deviceService')).getDevice(entityId.id).subscribe((device) => {
        var newParams = {};
        newParams.entityId = entityId;
        newParams.entityName = entityName;
        if(device.type == "Gateway") {
            widgetContext.stateController.openState(‘gateway', newParams, true);
        }else if(device.type == "Termostat") {
            widgetContext.stateController.openState('termostat', newParams, true);
        }else if(device.type == "Water meter") {
            widgetContext.stateController.openState('water', newParams, true);
        }else{
            widgetContext.stateController.openState('info', newParams, true);
        }
    }
);

function openDashboardState(stateId, device) {
    var params = {
        entityId: entityId,
        entityName: device.name,
        entityLabel: device.label
    }

    widgetContext.stateController.openState(stateId, params, false);
}
```
