### ISSUE TITLE
[Question] Installation problem v3.2.0 on OpenSUSE with RPM built from source 

### ISSUE THREAD

**Issue by frozznight** [thingsboard/thingsboard#3979]
**Component**
 * Installation

**Description**
I am trying to install thingsboard v3.2.0 by building from source.
I have successfully built the rpm and modified necessarily the rpm package because I don't have sudo permission in the machine.
Now I tried to install the service by running the following command
```sh
usr/share/thingsboard/bin/install/install.sh --loadDemo
```
However, I received the following error message:
```sh
 ===================================================
 :: ThingsBoard ::       (v3.2.0)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Unable to load oauth2 config templates from json: [usr/share/thingsboard/data/json/system/oauth2_config_templates/google_config.json]
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to load oauth2 config templates from json
        at org.thingsboard.server.service.install.InstallScripts.lambda$createOAuth2Templates$8(InstallScripts.java:238)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.thingsboard.server.service.install.InstallScripts.createOAuth2Templates(InstallScripts.java:225)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createOAuth2Templates(DefaultSystemDataLoaderService.java:223)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:220)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.thingsboard.server.common.data.oauth2.OAuth2MapperConfig` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.thingsboard.server.common.data.oauth2.OAuth2ClientRegistrationTemplate["mapperConfig"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4497)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2730)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3183)
        at org.thingsboard.server.service.install.InstallScripts.lambda$createOAuth2Templates$8(InstallScripts.java:229)
        ... 13 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!
```
I checked the config file exists:
```sh
:~> ll usr/share/thingsboard/data/json/system/oauth2_config_templates/
total 12
-rwxr-xr-- 1 xxxxx xxxxxx 806 Jan 21 14:56 facebook_config.json
-rwxr-xr-- 1 xxxxx xxxxxx 943 Jan 21 14:56 github_config.json
-rwxr-xr-- 1 xxxxx xxxxxx 835 Jan 21 14:56 google_config.json
```
Which parts should I look at to fix this issue?
Thanks in advance

**Environment**

 * OS:  OpenSUSE 42.3
 * ThingsBoard: 3.2.0

**Comment by frozznight** [comment]
Apparently, using the rpm downloaded from github works well.
```sh
wget https://github.com/thingsboard/thingsboard/releases/download/v3.2/thingsboard-3.2.rpm
```

**Comment by ashvayka** [comment]
Please close the ticket if the official image works fine. It is built from source on Ubuntu machine.
