### ISSUE TITLE
[Bug] tb-cassandra load demo data error

### ISSUE THREAD

**Issue by amir-hg** [thingsboard/thingsboard#4029]
**Describe the bug**
i got this error when i run tb-cassandra:3.2.1 
this error apears only in v 3.2.1 not in 3.2.0 
`
2021-01-30 07:48:01,970 [main] INFO  o.t.s.i.ThingsboardInstallService - Loading demo data...
2021-01-30 07:48:02,228 [main] ERROR o.t.s.i.ThingsboardInstallService - Unexpected error during ThingsBoard installation!
java.lang.NullPointerException: null
        at org.thingsboard.server.dao.timeseries.CassandraBaseTimeseriesDao.isFixedPartitioning(CassandraBaseTimeseriesDao.java:420)
        at org.thingsboard.server.dao.timeseries.CassandraBaseTimeseriesDao.savePartition(CassandraBaseTimeseriesDao.java:181)
        at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.saveAndRegisterFutures(BaseTimeseriesService.java:168)
        at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.save(BaseTimeseriesService.java:147)
        at org.thingsboard.server.dao.usagerecord.ApiUsageStateServiceImpl.createDefaultApiUsageState(ApiUsageStateServiceImpl.java:103)
        at org.thingsboard.server.dao.tenant.TenantServiceImpl.saveTenant(TenantServiceImpl.java:124)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.loadDemoData(DefaultSystemDataLoaderService.java:231)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:228)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)`

**Your Server Environment**
my docker-compose file is simple as it documented on website

> version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-cassandra"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard

**Comment by sjupas** [comment]
Install thingsboard-3.2.0 and then use upgrade instructions. This error will not appear. Cheers.
