### ISSUE TITLE
[Bug] WebSocket NullPointerException

### ISSUE THREAD

**Issue by Hopperpop** [thingsboard/thingsboard#4042]
**Describe the bug**
After a dashboard is open for a long time and we switch to another dashboard we sometimes see websocket error -1011. The web socket continually tries to reconnect, but always returns the same error. Refreshing the page solves the issue. The logs show a NullPointerException.

**Your Server Environment**

* own setup
  * Azure deployment from marketspace
  * ThingsBoard v3.2.0 PE
  * Operating System: Ubuntu 18.04.5 LTS

**Your Client Environment**

**Desktop:**

* OS: Win10
* Browser Firefox
* Version 85.0 (64-bits)

**Screenshots**
![image](https://user-images.githubusercontent.com/11853634/106591503-a4b34a80-654e-11eb-9749-2df2b5bb274d.png)

**Logs**

`
2021-02-02 11:38:33,729 [http-nio-0.0.0.0-8080-exec-7] ERROR o.s.w.s.h.ExceptionWebSocketHandlerDecorator - Closing session due to exception for StandardWebSocketSession[id=c186bc3b-3692-797b-5035-abd3414291cb, uri=ws://<redacted>/api/ws/plugins/telemetry?token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicmFtZ0BjdHJsZW5naW5lZXJpbmcuZXUiLCJzY29wZXMiOlsiVEVOQU5UX0FETUlOIl0sInVzZXJJZCI6ImU1NGY0YWYwLTI4YjYtMTFlYi1hMmFlLWQzY2JlNzgwYzliMSIsImZpcnN0TmFtZSI6IkJyYW0iLCJsYXN0TmFtZSI6Ikd1cmRlYmVrZSIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiJiOWMwOGI4MC0yOGI0LTExZWItYTJhZS1kM2NiZTc4MGM5YjEiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIiwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE2MTIyNjAzMzksImV4cCI6MTYxMjI2OTMzOX0.jJ18qu22mwPRYsfRhNRb8EtcW9cTGpqs3HxEd4h4LtCB97vSS0ei8RUxGbjUnWvfvPK4Fhg4FKZVcGIBxjElGg]
java.lang.NullPointerException: null
        at org.thingsboard.server.service.subscription.TbAbstractDataSubCtx.setAndResolveQuery(TbAbstractDataSubCtx.java:127)
        at org.thingsboard.server.service.subscription.DefaultTbEntityDataSubscriptionService.createSubCtx(DefaultTbEntityDataSubscriptionService.java:320)
        at org.thingsboard.server.service.subscription.DefaultTbEntityDataSubscriptionService.handleCmd(DefaultTbEntityDataSubscriptionService.java:189)
        at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.handleWsEntityDataCmd(DefaultTelemetryWebSocketService.java:252)
        at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.lambda$handleWebSocketMsg$3(DefaultTelemetryWebSocketService.java:228)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.thingsboard.server.service.telemetry.DefaultTelemetryWebSocketService.handleWebSocketMsg(DefaultTelemetryWebSocketService.java:228)
        at org.thingsboard.server.controller.plugin.TbWebSocketHandler.handleTextMessage(TbWebSocketHandler.java:114)
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:402)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:502)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by vvlladd28** [comment]
Hi @Hopperpop, 
We will fix this problem in the new version, TB 3.2.2. Wait for the release of the new version or do build from source code.

**Comment by shaphiro** [comment]
I have currently the 3.3.0 thingsboard community version and this kind of error is just appeared this morning. After closing the dashbaords window on the browser the issue is disappeared.
