### ISSUE TITLE
 json convert is error in rest api call node

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#4158]
when I run application,it occurs in the rule  node: rest api call。

java.lang.NullPointerException
	at org.thingsboard.rule.engine.rest.TbHttpClient.<init>(TbHttpClient.java:145)
	at org.thingsboard.rule.engine.rest.TbRestApiCallNode.init(TbRestApiCallNode.java:54)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:151)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:63)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:62)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:56)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:61)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$null$1(TbActorMailbox.java:77)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

and in the database,my data is here:
INSERT INTO "public"."rule_node"("id", "created_time", "rule_chain_id", "additional_info", "configuration", "type", "name", "debug_mode", "search_text") VALUES ('b93eab30-3b95-11eb-a0d6-a9a4f14cd82b', 0, 'b8e8ea10-3b95-11eb-a0d6-a9a4f14cd82b', '{"description":null,"layoutX":292,"layoutY":304}', '{"restEndpointUrlPattern":"http://localhost:8081/api/handleRpc","requestMethod":"POST","useSimpleClientHttpFactory":true,"enableProxy":null,"useSystemProxyProperties":null,"proxyScheme":null,"proxyHost":null,"proxyPort":null,"proxyUser":null,"proxyPassword":null,"readTimeoutMs":0,"maxParallelRequestsCount":0,"headers":{},"useRedisQueueForMsgPersistence":false,"trimQueue":false,"maxQueueSize":0,"credentials":{"type":"anonymous"}}', 'org.thingsboard.rule.engine.rest.TbRestApiCallNode', '将RPC转发到第三方API', 't', '将rpc转发到第三方api');

when I debug the server,I find the code:
the config object is null.I think the json convert is error.
nettyFactory.setSslContext(config.getCredentials().initSslContext());

**Comment by vvlladd28** [comment]
Hi @zth390872451,
Thank you for your report. This problem was fixed in the master branch. 
To fix on your server, you need to go to the setting **Rest API call** node and set setting **Credentials type - Anonymous**.
