### ISSUE TITLE
MQTT Plugin causes Rule to not work anymore

### ISSUE THREAD

**Issue by Be-P** [thingsboard/thingsboard#423]
If I configure a wrong Velocity Template under Template Body the system will hang writing in the log always the same error [ even with plugin and rule stopped and after service restart ] :

```
2017-11-16 16:05:26,177 [nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt413] Processing connect msg for client: custom!

2017-11-16 16:05:26,183 [nioEventLoopGroup-5-5] WARN  o.t.s.t.mqtt.MqttTransportHandler - [mqtt413] Failed to process publish msg [v1/devices/me/telemetry][27]
org.thingsboard.server.common.transport.adaptor.AdaptorException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 53 path $.longitude
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToTelemetryUploadRequest(JsonMqttAdaptor.java:236)
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToActorMsg(JsonMqttAdaptor.java:60)
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToActorMsg(JsonMqttAdaptor.java:47)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processDevicePublish(MqttTransportHandler.java:178)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processPublish(MqttTransportHandler.java:150)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processMqttMsg(MqttTransportHandler.java:112)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.channelRead(MqttTransportHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 53 path $.longitude
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.thingsboard.server.transport.mqtt.adaptors.JsonMqttAdaptor.convertToTelemetryUploadRequest(JsonMqttAdaptor.java:234)
	... 26 common frames omitted
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 53 path $.longitude
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:495)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:742)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 30 common frames omitted
2017-11-16 16:05:26,183 [nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt413] Closing current session due to invalid publish msg [v1/devices/me/telemetry][27]
2017-11-16 16:05:26,183 [MQTT Rec: custom] WARN  o.t.s.e.mqtt.plugin.MqttMsgHandler - Failed to deliver message [AbstractRuleToPluginMsg [uid=282235c1-0514-46ee-966d-a6938b4a7798, tenantId=b5fe0da0-cad5-11e7-b695-552c6207e186, customerId=13814000-1dd2-11b2-8080-808080808080, deviceId=1d7a0ec0-cad6-11e7-b695-552c6207e186, payload=MqttActionPayload(sync=false, topic=v1/devices/me/telemetry, msgBody={ "temperature" : 12 , "longitude" : BasicTsKvEntry{ts=1510844309671, kv=DoubleDataEntry{value=43.354} BasicKvEntry{key='longitude'}} , "humidity" : 38 }, requestId=0, msgType=POST_TELEMETRY_REQUEST)]] to topic [v1/devices/me/telemetry]!
```

**Comment by vparomskiy** [comment]
Not actual anymore since ThingsBoard architecture was modified since version 2.0 and plugins where removed.
