### ISSUE TITLE
[Question] A challenge on building ThingsBoard JavaScript Executor Microservice 3.2.1

### ISSUE THREAD

**Issue by scutcz** [thingsboard/thingsboard#4256]
**Component**
I have a challenge on building ThingsBoard JavaScript Executor Microservice 3.2.1  as following details. Did someone encounter the same issue? Please let me know your comments, thanks.

**Description**
[INFO] ------------------< org.thingsboard.msa:js-executor >-------------------
[INFO] Building ThingsBoard JavaScript Executor Microservice 3.2.1      [30/37]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ js-executor ---
[INFO] Deleting /Users/******/thingsboard-3.2.1/msa/js-executor/target
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy (copy-protoc) @ js-executor ---
[INFO] Configured Artifact: com.google.protobuf:protoc:osx-x86_64:3.11.4:exe
[INFO] Copying protoc-3.11.4-osx-x86_64.exe to /Users/******/thingsboard-3.2.1/msa/js-executor/target/protoc-3.11.4-osx-x86_64.exe
[INFO]
[INFO] --- frontend-maven-plugin:1.7.5:install-node-and-yarn (install node and yarn) @ js-executor ---
[INFO] Installing node version v12.16.1
[INFO] Unpacking /Users/******/.m2/repository/com/github/eirslett/node/12.16.1/node-12.16.1-darwin-x64.tar.gz into /Users/******/thingsboard-3.2.1/msa/js-executor/target/node/tmp
[INFO] Copying node binary from /Users/******/thingsboard-3.2.1/msa/js-executor/target/node/tmp/node-v12.16.1-darwin-x64/bin/node to /Users/******/thingsboard-3.2.1/msa/js-executor/target/node/node
[INFO] Installed node locally.
[INFO] Installing Yarn version v1.22.4
[INFO] Unpacking /Users/******/.m2/repository/com/github/eirslett/yarn/1.22.4/yarn-1.22.4.tar.gz into /Users/******/thingsboard-3.2.1/msa/js-executor/target/node/yarn
[INFO] Installed Yarn locally.
[INFO]
[INFO] --- frontend-maven-plugin:1.7.5:yarn (yarn install) @ js-executor ---
[INFO] Running 'yarn install' in /Users/******/thingsboard-3.2.1/msa/js-executor
[INFO] yarn install v1.22.4
[INFO] [1/5] Validating package.json...
[INFO] [2/5] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ pkg -t node12-linux-x64,node12-win-x64 --out-path ./target . && node install.js
[INFO] > pkg@4.4.9
[INFO] > Warning Failed to make bytecode node12-x64 for file /snapshot/js-executor/node_modules/@opencensus/web-types/build/src/index.js
[ERROR] assert.js:385
[ERROR]     throw err;
[ERROR]     ^
[ERROR]
[ERROR] AssertionError [ERR_ASSERTION]: Placeholder for not found
[ERROR]     at injectPlaceholder (/Users/******/thingsboard-3.2.1/msa/js-executor/node_modules/pkg/lib-es5/producer.js:46:37)
[ERROR]     at injectPlaceholders (/Users/******/thingsboard-3.2.1/msa/js-executor/node_modules/pkg/lib-es5/producer.js:66:3)
[ERROR]     at /Users/******/thingsboard-3.2.1/msa/js-executor/node_modules/pkg/lib-es5/producer.js:224:9
[ERROR]     at FSReqCallback.oncomplete (fs.js:154:23) {
[ERROR]   generatedMessage: false,
[ERROR]   code: 'ERR_ASSERTION',
[ERROR]   actual: false,
[ERROR]   expected: true,
[ERROR]   operator: '=='
[ERROR] }
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Thingsboard 3.2.1:
[INFO]
[INFO] Thingsboard ........................................ SUCCESS [ 12.780 s]
[INFO] Netty MQTT Client .................................. SUCCESS [  1.741 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.148 s]
[INFO] Thingsboard Server Common Data ..................... SUCCESS [  4.069 s]
[INFO] Thingsboard Server Common Utils .................... SUCCESS [  0.303 s]
[INFO] Thingsboard Server Common Messages ................. SUCCESS [  3.103 s]
[INFO] Thingsboard Actor system ........................... SUCCESS [  0.677 s]
[INFO] Thingsboard Server Stats ........................... SUCCESS [  0.264 s]
[INFO] Thingsboard Server Queue components ................ SUCCESS [  7.771 s]
[INFO] Thingsboard Server Commons ......................... SUCCESS [  0.038 s]
[INFO] Thingsboard Server Common Transport components ..... SUCCESS [  2.703 s]
[INFO] Thingsboard MQTT Transport Common .................. SUCCESS [  1.028 s]
[INFO] Thingsboard HTTP Transport Common .................. SUCCESS [  0.384 s]
[INFO] Thingsboard CoAP Transport Common .................. SUCCESS [  0.491 s]
[INFO] Thingsboard Server Common DAO API .................. SUCCESS [  0.873 s]
[INFO] Thingsboard Extensions ............................. SUCCESS [  0.055 s]
[INFO] Thingsboard Rule Engine API ........................ SUCCESS [  0.681 s]
[INFO] Thingsboard Server DAO Layer ....................... SUCCESS [  5.944 s]
[INFO] Thingsboard Rule Engine Components ................. SUCCESS [  3.218 s]
[INFO] Thingsboard Server Transport Modules ............... SUCCESS [  0.027 s]
[INFO] Thingsboard HTTP Transport Service ................. SUCCESS [ 12.779 s]
[INFO] Thingsboard MQTT Transport Service ................. SUCCESS [ 11.692 s]
[INFO] Thingsboard CoAP Transport Service ................. SUCCESS [ 11.637 s]
[INFO] ThingsBoard Server UI .............................. SUCCESS [01:34 min]
[INFO] Thingsboard Server Tools ........................... SUCCESS [  0.557 s]
[INFO] Thingsboard Rest Client ............................ SUCCESS [  0.554 s]
[INFO] ThingsBoard Server Application ..................... SUCCESS [ 29.777 s]
[INFO] ThingsBoard Microservices .......................... SUCCESS [  1.309 s]
[INFO] ThingsBoard Docker Images .......................... SUCCESS [  0.860 s]
[INFO] ThingsBoard JavaScript Executor Microservice ....... FAILURE [ 20.398 s]
[INFO] ThingsBoard Web UI Microservice .................... SKIPPED
[INFO] ThingsBoard Node Microservice ...................... SKIPPED
[INFO] ThingsBoard Transport Microservices ................ SKIPPED
[INFO] ThingsBoard MQTT Transport Microservice ............ SKIPPED
[INFO] ThingsBoard HTTP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard COAP Transport Microservice ............ SKIPPED
[INFO] ThingsBoard Black Box Tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:50 min
[INFO] Finished at: 2021-03-17T16:47:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.5:yarn (yarn install) on project js-executor: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :js-executor

**Environment**
 * OS:  macOS Big Sur
 * ThingsBoard: 3.2.1

**Comment by scutcz** [comment]
Just removed the pkg cache "~/.pkg/v2.6" then download again, problem resolved.
