### ISSUE TITLE
[Bug] integration aws kinesis connect to AWS China (Unable to connect to endpoint)

### ISSUE THREAD

**Issue by ksbneo** [thingsboard/thingsboard#4279]
**Describe the bug**
I am able to make the [sample](https://thingsboard.io/docs/user-guide/integrations/aws-kinesis/) work if using the AWS **Global** instance. However, it cannot work against the AWS **China** instance.
The error message from thingsboard.log:
2021-03-22 03:37:15,807 [kpl-daemon-0003] INFO  c.a.s.k.p.LogInputStreamReader - [2021-03-22 03:37:15.807739] [0x00004da9][0x00007f9235de47c0] [info] [shard_map.cc:81] Updating shard map for stream "tb-test-downlink"
2021-03-22 03:37:15,812 [kpl-daemon-0003] ERROR c.a.s.k.p.LogInputStreamReader - [2021-03-22 03:37:15.812233] [0x00004da9][0x00007f9213fff700] [error] [AWS Log: ERROR](CurlHttpClient)Curl returned error code 6
2021-03-22 03:37:15,812 [kpl-daemon-0003] ERROR c.a.s.k.p.LogInputStreamReader - [2021-03-22 03:37:15.812283] [0x00004da9][0x00007f9213fff700] [error] [shard_map.cc:152] Shard map update for stream "tb-test-downlink" failed. Code:  Message: **Unable to connect to endpoint**; retrying in 30000 ms

I doubt it probably related to aws arn issue. one is arn:aws, another is arn:aws-cn
For example:
in Global, arn: arn:aws:kinesis:us-east-1:111122223333:stream/tb-test-downlink
in China, the arn: arn:aws-cn:kinesis:cn-northwest-1:111122223333:stream/tb-test-downlink

**Your Server Environment**

* own setup
  * ThingsBoard Version: ThingsBoard 3.2.1PE
  * OS Name and Version: Amazon Linux 2

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Windows 10
* Browser [e.g. chrome, safari] Chrome

**Your Device**

* Connectivity
  * Integration: AWS Kinesis
* Device vendor and model

**To Reproduce**
1. Go to 'device' atrribute
2. Add a new attribute: version: v.0.11
3. Go to integration -> kinesis_integration (Note: create it follow the guide) -> Event
4. See error:
java.lang.Exception: com.amazonaws.services.kinesis.producer.UserRecordFailedException
	at org.thingsboard.integration.aws.kinesis.AwsKinesisIntegration$1.onFailure(AwsKinesisIntegration.java:384)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1064)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1164)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:53)
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler.onPutRecordResult(KinesisProducer.java:197)
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler.access$000(KinesisProducer.java:131)
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler$1.run(KinesisProducer.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.kinesis.producer.UserRecordFailedException
	... 6 more

**Expected behavior**
integrate with AWS China kinesis without issue.

**Screenshots**

**Additional context**

**Comment by ashvayka** [comment]
Hi @ksbneo , unfortunately, we don't have a presence in China and can't create or connect to AWS resources in China to test. Please share the credentials to connect to your Kinesis instance if possible (please send the email to support@thingsboard.io).

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
