### ISSUE TITLE
MQTT with QoS=0 results in akka.actor error

### ISSUE THREAD

**Issue by mripv6** [thingsboard/thingsboard#429]
When sending device or attribute data to the Thingsboard gateway device using MQTT, Thingsboard updates the values (attributes or telemetry), but throws an error in the Thingsboard log file.  For example, sending these MQTT messages results in the error. This happens in both 1.3.1 and the current 1.4.0 SNAPSHOT.

v1/gateway/attributes
{"Exchanger":{"model":"Temp Trend"}}

v1/gateway/telemetry
{"Exchanger":[{"ts":1511103113127,"values":{"ReturnTemperature":51.3,"SupplyTemperature":48.9}}]}

Here's the error.

2017-11-19 15:11:48,937 [Akka-akka.actor.default-dispatcher-207] ERROR akka.actor.OneForOneStrategy - messageId: -1 (expected: 1 ~ 65535)
java.lang.IllegalArgumentException: messageId: -1 (expected: 1 ~ 65535)
	at io.netty.handler.codec.mqtt.MqttMessageIdVariableHeader.from(MqttMessageIdVariableHeader.java:31)
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.createMqttPubAckMsg(MqttTransportHandler.java:375)
	at org.thingsboard.server.transport.mqtt.session.GatewayDeviceSessionCtx.getToDeviceMsg(GatewayDeviceSessionCtx.java:87)
	at org.thingsboard.server.transport.mqtt.session.GatewayDeviceSessionCtx.onMsg(GatewayDeviceSessionCtx.java:74)
	at org.thingsboard.server.actors.session.ASyncMsgProcessor.processToDeviceMsg(ASyncMsgProcessor.java:102)
	at org.thingsboard.server.actors.session.SessionActor.processToDeviceMsg(SessionActor.java:91)
	at org.thingsboard.server.actors.session.SessionActor.onReceive(SessionActor.java:69)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mripv6** [comment]
I found more info. The error only happens when QoS = 0 in the MQTT publish message. If the QoS is 1 in the publish message, no error in log file. With QoS 1, TB sends out a PUB ACK packet.

So... I think this is a bug in Thingsboard. There should be no error with QoS = 1 in a MQTT PUB.

**Comment by ashvayka** [comment]
Yes, this is probably a bug. @mp-loki please take a look.

**Comment by ashvayka** [comment]
@mp-loki please add link to PR and close this

**Comment by mp-loki** [comment]
Fixed in main branch
https://github.com/thingsboard/thingsboard/pull/455
