### ISSUE TITLE
[Bug] RestClient getLatestTimeseries Can't parse value: null

### ISSUE THREAD

**Issue by mislayming** [thingsboard/thingsboard#4324]
**Describe the bug**
When calling getLatestTimeseries by java sdk [version 3.2.0], if the telemetry value obtained is null, it will throw an exception.

**To Reproduce**
```
public static void main(String[] args) {
        RestClient rest = new RestClient("http://localhost:8090");
        rest.login("tenant@thingsboard.org", "tenant");

        DeviceId did = new DeviceId(UUID.fromString("c2a136a0-8e5d-11eb-9604-4b0c329f88c8"));
        List<TsKvEntry> t = rest.getLatestTimeseries(did, Arrays.asList("ABC", "BCD"));
    }
```

run it and throw exception
```
Exception in thread "main" java.lang.RuntimeException: Can't parse value: null
	at org.thingsboard.rest.client.utils.RestJsonConverter.parseValue(RestJsonConverter.java:82)
	at org.thingsboard.rest.client.utils.RestJsonConverter.lambda$null$1(RestJsonConverter.java:62)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.thingsboard.rest.client.utils.RestJsonConverter.lambda$toTimeseries$2(RestJsonConverter.java:65)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.thingsboard.rest.client.utils.RestJsonConverter.toTimeseries(RestJsonConverter.java:60)
	at org.thingsboard.rest.client.RestClient.getLatestTimeseries(RestClient.java:1924)
	at org.thingsboard.rest.client.RestClient.getLatestTimeseries(RestClient.java:1909)
	at com.augesmart.health.api.things.ThingsGeneralAPIImpl.main(ThingsGeneralAPIImpl.java:165)
```

**Expected behavior**
I think if the equipment has just been online, it is impossible for all the telemetry points to be reported at the same time.
So get null value is correct.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
