### ISSUE TITLE
Multiple MQTT PUB ACKs for a single PUB

### ISSUE THREAD

**Issue by mripv6** [thingsboard/thingsboard#433]
Thingsboard sends out three MQTT Publish Ack packets for this JSON publish message, which contain time series and values for three devices. I think there should only be a single ACK per MQTT PUB message, not one for each device.

This means, you have to send a MQTT message for each device in separate messages. So the gateway really doesn't function as designed. 

I believe this is a bug.

Topic: v1/gateway/telemetry

{"Exchanger": [{"ts": 1511196547,"values": {"TempSupply": 49.8,"TempReturn": 53.6}}],"Chiller": [{"ts": 1511196547,"values": {"TempSupply": 45.86,"TempReturn": 50.72}}],"Tank": [{"ts": 1511196547,"values": {"TempSupply": 52.5,"TempReturn": 70.2}}]}

If I send this MQTT message using mqtt-spy, mqtt-spy throws an error and sends a RST packet. Probably because it's not expecting unsolicited ACKs. Thingsboard registers the error in the log file as an Unexpected Exception.

2017-11-20 17:10:16,051 [nioEventLoopGroup-5-9] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt25] Unexpected Exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:349)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Karabiy** [comment]
the new ThingsBord IoT Gateway written in python does solve this problem. you need to configure the converter for the use case of yours. 
here's the link for the python gateway: https://thingsboard.io/docs/iot-gateway/what-is-iot-gateway/
