### ISSUE TITLE
[Bug] Rule node switch don`t worck

### ISSUE THREAD

**Issue by Alentus** [thingsboard/thingsboard#4335]
**Describe the bug**
After update from 3.2.1 to 3.2.2 rule node switch don't execute my code.
**Your Server Environment**

* own setup
  * local infrastructure 
  * ThingsBoard Version 3.2.2
  * Ubuntu server 20.04

**To Reproduce**
1. open root rule chain and add node generator and switch 
2. use this code
```javascript
switch (metadata.deviceType) {
    case 'FSL_Telemetry':
        return ['Asset'];
    case 'FSL_Speed':
        return ['Asset'];
    case 'FSL_air':
        return ['Asset'];
    case 'PresureTel':
        return ['Asset'];
    case 'ECOUNTER':
        return ['ECOUNTER'];
    case 'FSL-Metrocounter':
        return ['Metrocounter'];

    default:
        return ['Asset'];
}
```
in version 3.2.1 this code work fine but in 3.2.2 i have this log: 

```
java.lang.IllegalArgumentException: Can't compile script: javax.script.ScriptException: <eval>:8:32 Expected case but found __if
  switch (metadata.deviceType) {__if();
                                ^ in <eval> at line number 8 at column number 32
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.<init>(RuleNodeJsScriptEngine.java:63)
	at org.thingsboard.server.actors.ruleChain.DefaultTbContext.createJsScriptEngine(DefaultTbContext.java:381)
	at org.thingsboard.rule.engine.filter.TbJsSwitchNode.init(TbJsSwitchNode.java:51)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:154)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:62)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:64)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$tryInit$1(TbActorMailbox.java:81)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.concurrent.ExecutionException: javax.script.ScriptException: <eval>:8:32 Expected case but found __if
  switch (metadata.deviceType) {__if();
                                ^ in <eval> at line number 8 at column number 32
	at org.thingsboard.server.service.script.AbstractNashornJsInvokeService.lambda$doEval$0(AbstractNashornJsInvokeService.java:141)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	... 6 more
Caused by: javax.script.ScriptException: <eval>:8:32 Expected case but found __if
  switch (metadata.deviceType) {__if();
                                ^ in <eval> at line number 8 at column number 32
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:544)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:531)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
	at delight.nashornsandbox.internal.JsEvaluator.run(JsEvaluator.java:55)
	... 6 more
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:8:32 Expected case but found __if
  switch (metadata.deviceType) {__if();
                                ^
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:297)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:282)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:353)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:340)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.switchStatement(Parser.java:2505)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1072)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.functionBody(Parser.java:4206)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.functionExpression(Parser.java:3831)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1099)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.functionBody(Parser.java:4206)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.functionExpression(Parser.java:3831)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.statement(Parser.java:1099)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:909)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.program(Parser.java:844)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:325)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compile(Context.java:1500)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1467)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.compileScript(Context.java:750)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:542)
	... 12 more
```

**Comment by ashvayka** [comment]
Hi @Alentus , preliminary investigation shows that this is a bug related to the Nashorn JS Sandbox [library](https://github.com/javadelight/delight-nashorn-sandbox) that we use. We are investigating the issue and will prepare a bugfix. As a workaround, please disable the sandbox JS execution using USE_LOCAL_JS_SANDBOX env variable (set to "false") or via thingsboard.yml.
