### ISSUE TITLE
[Bug] even with the latest version 3.2.2, the upgrade-tb.sh in all-in-one postgres docker image resets .upgradeversion file to 2.4.2

### ISSUE THREAD

**Issue by tozhangkai** [thingsboard/thingsboard#4386]
**Describe the bug**
We recently upgraded tb running with all-in-one postgres docker from 2.5.1 all the way to the latest 3.2.2. During the process, we ran upgrade-tb.sh in the images from 2.5.2, 3.0, 3.1, 3.2, and eventually to 3.2.2. Each time we ran the script. it resets the `.upgradeversion` file to 2.4.2. We had to manually fix the file to the correct version so the next upgrade starts from the correct point. It seems the version hasn't been updated for a while: https://github.com/thingsboard/thingsboard/blob/a98499354b3401a2eeb2282283301958dda32c05/msa/tb/pom.xml#L42

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version 3.2.2
  * OS Name and Version Ubunbu 20.0.4

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows
* Browser Chrome
* Version 89

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
1. Run an older version of Thingsboard postgres all-in-one docker image (for example 2.5.1), and let it create the database.
2. Pull a newer version (for example 3.0), and run the `upgrade-tb.sh` from the newer image as in the instructions
3. Check the `.upgradeversion` file in the data folder, you'll see it has `2.4.2`.
4. Pull a newer version again (for example 3.1), and run its `upgrade-tb.sh`, you'll see it applies upgrades from 2.4.2. When completes, the `.upgradeversion` remains 2.4.2.
5. Manually change the `.upgradeversion` to `3.1.0` and run the `upgrade-tb.sh` again, you'll see the `.upgradeversion` is set back to `2.4.2`

**Expected behavior**
`.upgradeversion` should reflect the latest successful upgraded version, so when we upgrade for the next version, it only applies the DB changes from the last successful upgrade, but not all the way from 2.4.2.

**Screenshots**

**Additional context**

**Comment by AngeLinuX99** [comment]
Same problem to me... upgrading from 3.2.1 to 3.2.2, 

root@docker2:/home/ubuntu# docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres upgrade-tb.sh
Starting ThingsBoard upgrade ...
 ===================================================
 :: ThingsBoard ::       (v3.2.2)
 ===================================================

Starting ThingsBoard Upgrade from version 2.4.2 ...
Upgrading ThingsBoard from version 2.4.2 to 2.4.3 ...
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.connect(Driver.java:264)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:233)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:154)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
	at org.postgresql.core.PGStream.<init>(PGStream.java:95)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	... 17 common frames omitted
Unexpected error during ThingsBoard installation!
pg_ctl: could not send stop signal (PID: 11): No such process

**Comment by vvlladd28** [comment]
Hi @tozhangkai,
Thank you for your report. We fixed the issue at master branch, and a fix will add a new release.
