### ISSUE TITLE
[Bug] Can not install on Raspberry Pi

### ISSUE THREAD

**Issue by IAmTheNail** [thingsboard/thingsboard#4442]
**Describe the bug**
Following the instructions on "https://thingsboard.io/docs/user-guide/install/rpi/" at Step 6, the installer script throws an exception.

**Your Server Environment**

* own setup
  * local infrastructure
  * ThingsBoard Version 3.2.2
  * Raspberry Pi OS 10 (buster)
  * Raspberry Pi 4

**Your Client Environment**
n/a

**Smartphone (please complete the following information):**
n/a

**Your Device**
n/a

**To Reproduce**
1. Follow the install instructions at https://thingsboard.io/docs/user-guide/install/rpi/.
2. Run successfully the first 5 steps.
3. At Step 6, Run installation script, run "sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo". This triggers the exception shown below:

```
$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalArgumentException: Invalid source directory /srv/dev-disk-by-id-md-name-nas-0/home/pi
	at org.springframework.boot.loader.PropertiesLauncher.<init>(PropertiesLauncher.java:158)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:465)
Caused by: java.lang.IllegalArgumentException: Invalid source directory /srv/dev-disk-by-id-md-name-nas-0/home/pi
	at org.springframework.boot.loader.archive.ExplodedArchive.<init>(ExplodedArchive.java:73)
	at org.springframework.boot.loader.PropertiesLauncher.getProperty(PropertiesLauncher.java:426)
	at org.springframework.boot.loader.PropertiesLauncher.getProperty(PropertiesLauncher.java:395)
	at org.springframework.boot.loader.PropertiesLauncher.initializeProperties(PropertiesLauncher.java:173)
	at org.springframework.boot.loader.PropertiesLauncher.<init>(PropertiesLauncher.java:153)
	... 1 more
ThingsBoard installation failed!
```

**Expected behavior**
The command to run successfully & the error to give a hint about what is going wrong.

**Screenshots**
n/a

**Additional context**

**Comment by IAmTheNail** [comment]
Same happens with Postgres 11

**Comment by IAmTheNail** [comment]
Apparently the current directory has something to do with it. Because the installer *does* work when setting first the current directory to /tmp.

**Comment by xalt7x** [comment]
Yes, there's an issue in the installation script on Linux (PR #9548 should handle it)
Currently it's recommended to go either to the user's $HOME directory (e.g. /home/user) or to the Thingsboard installation directory (e.g. /usr/share/thingsboard).

**Comment by myroslav-tb** [comment]
Hello @IAmTheNail,

Has the answer of xalt7x helped to resolve your issue? 
Please let us know if you require any additional help.

Best regards,
Myroslav
