### ISSUE TITLE
Thingsboard installation failed

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#445]
After builded Things-board source. 
I have trying to install things-board from following directory binary Thingsboard{DIR-}/application/target/ install.sh, but I have some problem on Ubuntu. please help me to fix it. have attached my logs. Thanks

./install.sh: 18: ./install.sh: [[: not found
./install.sh: 34: [: unexpected operator
./install.sh: 45: ./install.sh: source: not found
 ===================================================
 :: ThingsBoard ::       (v1.4.0-SNAPSHOT)
> 
> ===================================================

log4j:WARN No appenders could be found for logger (hsqldb.db.HSQLDB5FE8B507AD.ENGINE).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Unable to create initial connections of pool.
java.sql.SQLException: file input/output error: /tmp/thingsboardDb.log
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:718)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:650)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:468)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:143)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:254)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:228)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:207)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:207)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:847)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:874)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:340)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.hsqldb.HsqlException: file input/output error: /tmp/thingsboardDb.log
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.Log.openLog(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	... 55 common frames omitted
Starting ThingsBoard Installation...
Installing DataBase schema...
Installing SQL DataBase schema...
Unexpected error during ThingsBoard installation!
java.sql.SQLException: file input/output error: /tmp/thingsboardDb.log
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.thingsboard.server.service.install.SqlDatabaseSchemaService.createDatabaseSchema(SqlDatabaseSchemaService.java:60)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:118)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.hsqldb.HsqlException: file input/output error: /tmp/thingsboardDb.log
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.persist.Log.openLog(Unknown Source)
	at org.hsqldb.persist.Log.open(Unknown Source)
	at org.hsqldb.persist.Logger.open(Unknown Source)
	at org.hsqldb.Database.reopen(Unknown Source)
	at org.hsqldb.Database.open(Unknown Source)
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source)
	at org.hsqldb.DatabaseManager.newSession(Unknown Source)
	... 16 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

**Comment by mp-loki** [comment]
You are not supposed to run install.sh from the target dir. Once you have thingsboard.deb built, you can pick it up and follow the [Installation Instructions](https://thingsboard.io/docs/user-guide/install/linux/).

**Comment by ethicstechOSS** [comment]
@mp-loki I am also facing the same problem when I install the demo data,

Exception in thread "main" java.lang.IllegalArgumentException: Invalid source folder /root/thingsboard
	at org.springframework.boot.loader.archive.ExplodedArchive.<init>(ExplodedArchive.java:73)
	at org.springframework.boot.loader.PropertiesLauncher.getProperty(PropertiesLauncher.java:379)
	at org.springframework.boot.loader.PropertiesLauncher.getProperty(PropertiesLauncher.java:357)
	at org.springframework.boot.loader.PropertiesLauncher.getArgs(PropertiesLauncher.java:301)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:520)
ThingsBoard installation failed!

I could not find anything on the installation page about from where we want to execute this command. Please clarify.

**Comment by ashvayka** [comment]
Hi @srimathselva There is https://pastebin.com/ or other similar websites to avoid pushing tons of log to github issues. They also make browsing of the logs easier. Please review the https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/ for more information. I think it will cover all the questions.

**Comment by 18616505009** [comment]
I have come through this problem and my coworker helped to get over it.In my case the problem occured because I was using a member account instead of the root account on my mac.Follow these steps:
1.Terminal -->cd /tmp
2.ls -l (check your thingsboardDb.log, is it only accessible with root account?)
3.sudo chown {your account name} thingsboardDb.log (change this file owner to your accout)
4.ls -l (again,make sure thingsboardDb.log is accessible with your account
run your project again,hope it helps and sorry for my chinglish

**Comment by pushkar31** [comment]
@mp-loki,
Where did we get thingsboard.deb.
attached is the screenshot of my target directory. 
![target](https://user-images.githubusercontent.com/30723922/34994906-f14961de-fafa-11e7-9b5c-67b04af9c7f5.png)

**Comment by vparomskiy** [comment]
deb package is generated during build procedure
https://thingsboard.io/docs/user-guide/install/building-from-source/

just run 'mvn clean install' is the root directory of the project. After that you will see deb package in ./application/target/ directory

Otherwise you can download debian package directly using this url:
wget https://github.com/thingsboard/thingsboard/releases/download/v1.3.1/thingsboard-1.3.1.deb

**Comment by pushkar31** [comment]
deb package is generated during build procedure, but for me its not generated during the build procedure.
./apllication/target is there but deb package is not there. (you can see in above screenshot which i shared in last post)

Also you mention that i can download package with url. 
wget https://github.com/thingsboard/thingsboard/releases/download/v1.3.1/thingsboard-1.3.1.deb

If i use this deb package will it be the source installation OR package installation. 
Please it will be helpful if you explain me.
Because my developer required that it should be source installation.

Thanks

**Comment by pushkar31** [comment]
Today I again tried "mvn clean install" and in output its giving error massage of npm installtion.
please find attached screenshot.
![error of npm](https://user-images.githubusercontent.com/30723922/35027213-77dde466-fb75-11e7-8f31-dc5565601fa4.png)

Guide me if there is solution on this.

**Comment by srimathselva** [comment]
Hi @pushkar31  
          can you try the following command on terminal,
       sudo  npm install -g cross-env 
       sudo npm install -g webpack

**Comment by pushkar31** [comment]
Hi,
Thanks for response. I tried both the command and below is the out put of each 
*  sudo npm install -g cross-env -:
root@ip-172-31-17-12:/opt/thingsboard# sudo npm install -g cross-env
/usr/local/bin/cross-env -> /usr/local/lib/node_modules/cross-env/dist/bin/cross-env.js
/usr/local/bin/cross-env-shell -> /usr/local/lib/node_modules/cross-env/dist/bin/cross-env-shell.js
/usr/local/lib
└─┬ cross-env@5.1.3
  ├─┬ cross-spawn@5.1.0
  │ ├─┬ lru-cache@4.1.1
  │ │ ├── pseudomap@1.0.2
  │ │ └── yallist@2.1.2
  │ ├─┬ shebang-command@1.2.0
  │ │ └── shebang-regex@1.0.0
  │ └─┬ which@1.3.0
  │   └── isexe@2.0.0
  └── is-windows@1.0.1

* sudo npm install -g webpack -:

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

sh: 1: node: not found
/usr/local/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.4.0-1047-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "webpack"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/thingsboard/npm-debug.log
npm ERR! code 1


Thanks
Pushkar

**Comment by srimathselva** [comment]
you have to install the npm-webpack.  have a look on this repo : https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/117  may this help you to fix

**Comment by pushkar31** [comment]
Hi,
I did the following changes -:
I fixed the issue by using the least version of npm & node as per the advise from @datthanhvu98
But I am not sure why the main source still uses older version of node & npm in pom.xml file.

Solution :
Modify the file https://github.com/thingsboard/thingsboard/blob/master/ui/pom.xml and edit the node & npm version as like the below.

v8.9.3
5.5.1

And its showed me that its successfully Build. (attached screenshot)
![build_success](https://user-images.githubusercontent.com/30723922/35031489-38759684-fb89-11e7-9067-4d2afebad6dc.png)

Then i found deb package in target directory, which i installed with thingsboard.deb
installed it using  - apt install ./thingsboard.deb  ( Screenshot attached)
![thingsboard_install](https://user-images.githubusercontent.com/30723922/35031635-d11cb93a-fb89-11e7-960b-c2b93f6b494b.png)

I am not sure how to start using it now, Please let me know if you have idea on this.

**Comment by pushkar31** [comment]
Hi,
I did the database import and things board started on port 8080.
but on browser it says-: http://13.127.98.67:8080/

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jan 17 08:30:06 UTC 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by srimathselva** [comment]
Check whether thingsboard service is running or not using this command,
sudo servie thingsboard status 
sudo service thingsboard start

and paste the following url on browser
http://locallhost:3000

**Comment by pushkar31** [comment]
Yes its running and active. (screenshot attached) but on http://13.127.98.67:3000 its not opening any page.

I have installed thingsboard using source file on AWS ec2 instance.
OS - Ubuntu 16.04

**Comment by m0rt3nlund** [comment]
Same issue here.

**Comment by ethicstechOSS** [comment]
@pushkar31 Check the same issue posted, https://github.com/thingsboard/thingsboard/issues/484 (many other already posted for while) and @mp-loki pointed out that it is an known issue with no proper solution yet and you have to try with other combination of OS, NODE & NPM. But it is a mystery that which is the right combination to get it successfully working. I tried many combination, but not yet successful.
