### ISSUE TITLE
[Bug] Kinesis Shard is not closed

### ISSUE THREAD

**Issue by ksbneo** [thingsboard/thingsboard#4498]
**Describe the bug**
It worked perfect when I followed the [guide ](https://thingsboard.io/docs/user-guide/integrations/aws-kinesis)to integration with aws-kinesis. I did clean up when done the practice, such as remove integration in thingsboard, delete AWS Kinesis data streams. 
A few weeks later, I met a problem when I followed the same guide, error message:
2021-04-23 02:23:08,559 [Thread-199] ERROR s.a.kinesis.leases.ShardSyncTask - Caught exception while sync'ing Kinesis shards and leases
software.amazon.kinesis.exceptions.internal.KinesisClientLibIOException: **Shard [shardId-000000000000] is not closed. This can happen if we constructed the list of shards  while a reshard operation was in progress**.
  at software.amazon.kinesis.leases.HierarchicalShardSyncer.assertClosedShardsAreCoveredOrAbsent(HierarchicalShardSyncer.java:172)
  at software.amazon.kinesis.leases.HierarchicalShardSyncer.cleanupLeasesOfFinishedShards(HierarchicalShardSyncer.java:599)
  at software.amazon.kinesis.leases.HierarchicalShardSyncer.checkAndCreateLeaseForNewShards(HierarchicalShardSyncer.java:112)
  at software.amazon.kinesis.leases.ShardSyncTask.call(ShardSyncTask.java:67)
  at software.amazon.kinesis.metrics.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:53)
  at software.amazon.kinesis.coordinator.Scheduler.initialize(Scheduler.java:271)
  at software.amazon.kinesis.coordinator.Scheduler.run(Scheduler.java:235)
  at java.base/java.lang.Thread.run(Thread.java:834)

I had tried several ways such as reboot instances but it worked until I changed the Kinesis stream name.
I doubt whether there is a backend service not cleared even I had already removed the integration, and the backend service continued to consume non-exist data streams.

**Your Server Environment**

* own setup
  * Binary installed on standalone instance
  * ThingsBoard Version PE V3.2.2
  * OS Name and Version AWS EC2 Ubuntu 16.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] Windows

**Expected behavior**
I could repeat to make the [guide ](https://thingsboard.io/docs/user-guide/integrations/aws-kinesis/)work even if I already made it worked before.

**Screenshots**

**Additional context**

**Comment by AndrewVolosytnykhThingsboard** [comment]
@ksbneo hi! can you pls specify more details about this problems? it will very help me. I followed your steps but can't reproduce same exception.
