### ISSUE TITLE
[Bug] MQTT Channel closed

### ISSUE THREAD

**Issue by tatianagasser** [thingsboard/thingsboard#4533]
**Describe the bug**
Hello, 

I have a problem when I want to send a message from the cloud dashboard to my device. In the rule engine after having post telemetry, I add a mqtt node to send the message to my device. Except that 2 times out of 3 I get the channel closed error. Would you have a clue about the problem? Is there a configuration to do? I use a public broker between my device and my dashboard. 

org.thingsboard.mqtt.ChannelClosedException: Channel is closed!
	at org.thingsboard.mqtt.MqttClientImpl.sendAndFlushPacket(MqttClientImpl.java:446)
	at org.thingsboard.mqtt.MqttClientImpl.publish(MqttClientImpl.java:381)
	at org.thingsboard.mqtt.MqttClientImpl.publish(MqttClientImpl.java:348)
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.onMsg(TbMqttNode.java:95)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:150)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:109)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:75)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:60)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:156)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Your Server Environment**
* cloud.thingsboard.io

** Connectivity **
  * MQTT

**To Reproduce**
1.  Add a mqtt node on the rule engine after save Timeseries
2.  Active debug mode
3.  Send a mqtt msg on a topic which the cloud is sub
4. See error in Event type OUT

**Expected behavior**
I just want to send a message on a topic after we received a data and saved it

**Comment by sabrectw** [comment]
I have the same problem and i am using a private broker running on Mosquitto.

**Comment by baigod** [comment]
As we all know, when using an MQTT node to connect to an external Borker, only one MQTT connection can be established with the same credentials. Therefore, in the thingsboard cluster environment, you cannot use the same credentials to create an MQTT connection in each node of the cluster. As a result, the MQTT rule node in all nodes except one fails to create a connection, and an error is reported on the onMsg: "Channel closed!"
I think the cluster tool class should be used to keep the MQTT rule node single in the cluster

**Comment by baigod** [comment]
@ikulikov Please read

**Comment by trikimiki** [comment]
A new feature allows avoiding this issue by using a singleton mode. See https://github.com/thingsboard/thingsboard/issues/7633
