### ISSUE TITLE
Bug on Server Side RPC Call Action

### ISSUE THREAD

**Issue by stieuquy** [thingsboard/thingsboard#454]
https://github.com/thingsboard/thingsboard/blob/5607d9a78ac28b1ef58a66a15765bbf70a137311/extensions-core/src/main/java/org/thingsboard/server/extensions/core/plugin/rpc/handlers/RpcRuleMsgHandler.java#L69

Hi,

when I config Server Side RPC Call Action of System RPC Plugin. I figured out that I can not config for "To Device Relation template" field. It means when running the rule it can not get the "to device relation". And I think the line of code above could be a cause. 

The exception will be like this:
`2017-11-28 13:08:03,480 [Akka-system-plugin-dispatcher-21] INFO  o.t.s.e.c.p.r.h.RpcRuleMsgHandler - Failed to process RPC Call Action msg
org.thingsboard.server.dao.exception.DataValidationException: Relation type should be specified!
	at org.thingsboard.server.dao.relation.BaseRelationService.validateType(BaseRelationService.java:324)
	at org.thingsboard.server.dao.relation.BaseRelationService.findByToAndType(BaseRelationService.java:243)
	at org.thingsboard.server.actors.plugin.PluginProcessingContext.findByToAndType(PluginProcessingContext.java:436)
	at org.thingsboard.server.extensions.core.plugin.rpc.handlers.RpcRuleMsgHandler$1.onSuccess(RpcRuleMsgHandler.java:69)
	at org.thingsboard.server.extensions.core.plugin.rpc.handlers.RpcRuleMsgHandler$1.onSuccess(RpcRuleMsgHandler.java:1)
	at org.thingsboard.server.actors.plugin.PluginProcessingContext.lambda$12(PluginProcessingContext.java:271)
	at org.thingsboard.server.actors.plugin.ValidationCallback.onSuccess(ValidationCallback.java:43)
	at org.thingsboard.server.actors.plugin.PluginProcessingContext.validate(PluginProcessingContext.java:301)
	at org.thingsboard.server.actors.plugin.PluginProcessingContext.checkAccess(PluginProcessingContext.java:271)
	at org.thingsboard.server.extensions.core.plugin.rpc.handlers.RpcRuleMsgHandler.handle(RpcRuleMsgHandler.java:58)
	at org.thingsboard.server.extensions.core.plugin.rpc.handlers.RpcRuleMsgHandler.process(RpcRuleMsgHandler.java:50)
	at org.thingsboard.server.extensions.api.plugins.AbstractPlugin.process(AbstractPlugin.java:47)
	at org.thingsboard.server.actors.plugin.PluginActorMessageProcessor.onRuleToPluginMsg(PluginActorMessageProcessor.java:101)
	at org.thingsboard.server.actors.plugin.PluginActor.onRuleToPluginMsg(PluginActor.java:93)
	at org.thingsboard.server.actors.plugin.PluginActor.onReceive(PluginActor.java:52)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by vparomskiy** [comment]
This issue not valid anymore, it was resolved during refactoring of the transport layer in ThingsBoard v 2.0
