### ISSUE TITLE
License Error: ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104) - Active instances capacity exceeded!

### ISSUE THREAD

**Issue by BaerSy** [thingsboard/thingsboard#4709]
**Component**

 * Installation
 
**Description**
I purchased PE 3.2.2 and tried to install it under Ubuntu 18.04.  Failed with following errors: (**_License Error: ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104) - Active instances capacity exceeded!_**)

mytbpe_1    | 2021-06-08 15:09:07,004 [main] INFO  o.t.license.client.TbLicenseClient - Initializing ThingsBoard License Client, Release Date [2021-03-24]
mytbpe_1    | 2021-06-08 15:09:08,358 [main] ERROR o.t.license.client.TbLicenseClient - License Error: ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104) - Active instances capacity exceeded!
mytbpe_1    | 2021-06-08 15:09:08,359 [main] ERROR o.t.license.client.TbLicenseClient - Failed to initialize ThingsBoard License Client!
mytbpe_1    | 2021-06-08 15:09:08,363 [main] ERROR o.t.s.d.s.BasicSubscriptionService - Failed to init license client
mytbpe_1    | org.thingsboard.license.shared.exception.LicenseException: Active instances capacity exceeded!
mytbpe_1    | 	at org.thingsboard.license.shared.exception.LicenseErrorResponse.toLicenseException(LicenseErrorResponse.java:69)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.toLicenseException(TbLicenseClient.java:393)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.activateInstance(TbLicenseClient.java:331)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.readInstanceDataOrActivate(TbLicenseClient.java:316)
mytbpe_1    | 	at org.thingsboard.license.client.TbLicenseClient.init(TbLicenseClient.java:171)
mytbpe_1    | 	at org.thingsboard.server.dao.subscription.BasicSubscriptionService.init(BasicSubscriptionService.java:100)
mytbpe_1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mytbpe_1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
mytbpe_1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
mytbpe_1    | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
mytbpe_1    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
mytbpe_1    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
mytbpe_1    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
mytbpe_1    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
mytbpe_1    | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
mytbpe_1    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
mytbpe_1    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
mytbpe_1    | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
mytbpe_1    | 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
mytbpe_1    | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
mytbpe_1    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
mytbpe_1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
mytbpe_1    | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
mytbpe_1    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
mytbpe_1    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
mytbpe_1    | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)

**Environment**

 * OS:  Ubuntu 18.04
 * ThingsBoard: PE 3.2.2
 * Browser: Chrome and Edge

**Comment by BaerSy** [comment]
Fixed. thanks
