### ISSUE TITLE
No enum constant org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryFeature.ATTRİBUTES

### ISSUE THREAD

**Issue by rubycik** [thingsboard/thingsboard#478]
hello
I get an error below when I run it on a local computer

```

> 2017-12-13 11:28:01.595 ERROR 23051 --- [0.0-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: No enum constant org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryFeature.ATTRİBUTES] with root cause
> 
> java.lang.IllegalArgumentException: No enum constant org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryFeature.ATTRİBUTES
>         at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_151]
>         at org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryFeature.valueOf(TelemetryFeature.java:21) ~[extensions-core-1.4.0-SNAPSHOT.jar!/:na]
>         at org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryFeature.forName(TelemetryFeature.java:26) ~[extensions-core-1.4.0-SNAPSHOT.jar!/:na]
>         at org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryRestMsgHandler.handleHttpGetRequest(TelemetryRestMsgHandler.java:72) ~[extensions-core-1.4.0-SNAPSHOT.jar!/:na]
>         at org.thingsboard.server.extensions.api.plugins.handlers.DefaultRestMsgHandler.process(DefaultRestMsgHandler.java:42) ~[extensions-api-1.4.0-SNAPSHOT.jar!/:na]
>         at org.thingsboard.server.extensions.api.plugins.AbstractPlugin.process(AbstractPlugin.java:42) ~[extensions-api-1.4.0-SNAPSHOT.jar!/:na]
>         at org.thingsboard.server.actors.plugin.PluginActorMessageProcessor.onRestMsg(PluginActorMessageProcessor.java:117) ~[classes!/:1.4.0-SNAPSHOT]
>         at org.thingsboard.server.actors.plugin.PluginActor.onRestMsg(PluginActor.java:113) ~[classes!/:1.4.0-SNAPSHOT]
>         at org.thingsboard.server.actors.plugin.PluginActor.onReceive(PluginActor.java:48) ~[classes!/:1.4.0-SNAPSHOT]
>         at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.4.2.jar!/:na]
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.7.jar!/:na]
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.7.jar!/:na]
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.7.jar!/:na]
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.7.jar!/:na]

```

**Comment by demirizZz** [comment]
Is there any solution for this?
I got the same error
java.lang.IllegalArgumentException: No enum constant org.thingsboard.server.common.data.EntityType.RULE_CHAİN

**Comment by hoffi085** [comment]
Hi, I have the same situation. Is there any hint? I tried to upgrade, but that did not solve the problem.
No enum constant org.thingsboard.server.common.data.plugin.ComponentType.FLOW; nested exception is java.lang.IllegalArgumentException: No enum constant org.thingsboard.server.common.data.plugin.ComponentType.FLOW

**Comment by wsdt** [comment]
Having the same issue

**Comment by kakasiji** [comment]
> Hi, I have the same situation. Is there any hint? I tried to upgrade, but that did not solve the problem. No enum constant org.thingsboard.server.common.data.plugin.ComponentType.FLOW; nested exception is java.lang.IllegalArgumentException: No enum constant org.thingsboard.server.common.data.plugin.ComponentType.FLOW

I have the same    how?

**Comment by ouertani** [comment]
New flow node has been add part of this commit from current:
https://github.com/thingsboard/thingsboard/commit/d6e18d05cd46d1ad407979878009446b66d42696#diff-402503245b2c634e6d57d49b9040495b1de35b5839c6a072f2a896dfcb598c07 

To fix for older version execute the below: 

`DELETE FROM public.component_descriptor WHERE type = 'FLOW';`

**Comment by Ultrazombie** [comment]
@demirizZz @kakasiji @hoffi085 @wsdt @rubycik 
Did the last comment help you?
