### ISSUE TITLE
[resolved] Error on 1.3.1 upgrage with postgre

### ISSUE THREAD

**Issue by xmas3** [thingsboard/thingsboard#491]
Hi, Im getting following error on upgrade. Any ideas?

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd c:/thingsboard

c:\thingsboard>upgrade.bat --fromVersion=1.3.0
Upgrading thingsboard ...
 ===================================================
 :: ThingsBoard ::       (v1.3.1)
 ===================================================

Starting ThingsBoard Upgrade from version 1.3.0 ...
Upgrading ThingsBoard from version 1.3.0 to 1.3.1 ...
Updating schema ...
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: syntax error at or near "varchar" Position: 659
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.jva:291)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:30)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:29)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:26)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:265)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgadeDatabase(SqlDatabaseUpgradeService.java:60)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstll(ThingsboardInstallService.java:89)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboarInstallApplication.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunne.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLancher.java:521)
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
```

**Comment by xmas3** [comment]
resolved here
https://groups.google.com/forum/#!topic/thingsboard/zFOg9zdmA7M
