### ISSUE TITLE
Unexpected error during ThingsBoard installation! org.postgresql.util.PSQLException: ERROR: syntax error at or near "PROCEDURE"

### ISSUE THREAD

**Issue by TERRYX95** [thingsboard/thingsboard#4987]
unable to install thingsboard, situation as follows:
$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
 ===================================================
 :: ThingsBoard ::       (v3.2.2)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: syntax error at or near "PROCEDURE"
  Position: 21
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:68)
	at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:210)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!
PostgreSQL version:
$ psql --version
psql (PostgreSQL) 12.7 (Ubuntu 12.7-1.pgdg16.04+1)

**Comment by trypzz** [comment]
Hi,

Provide /var/log/thingsboard/install.log file. In this file we can found more information about installation and clarify on which step installation failed.

**Comment by shimniok** [comment]
@trypzz -- I'm having the same problem. Here's my [install.log](https://github.com/thingsboard/thingsboard/files/7576656/install.log) file. Thanks.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
