### ISSUE TITLE
[Question] LwM2M bootstrap / register errors

### ISSUE THREAD

**Issue by JavierNR** [thingsboard/thingsboard#5108]
**Component**

 * Generic

**Description**
Hello, I'm testing the new 3.3 feature LwM2M with a Telit dev board to check how it works and I'm finding problems connecting it with/without bootstrap server.

At the moment I'm trying with PSK with 'coaps://' address because Telit doesn't allow 'coap://' address type.

On thingsboard side I've setup a device profile with more or less default setups and set security mode as Pre-Shared key on both Bootstrap and LwM2M server.
I've created a device that uses this profile and set their credentials as following:
Endpoint Client Name: [Module IMEI]
Security Config Mode: Pre-Shared Key
Client identity: [Module IMEI]
Client key: 12312312312312312312312312312312 (just random numbers for testing till 32 required characters)

In bootstrap client side (Bootstrap Server) I've set Pre-Shared key with:
Client public key: [Module IMEI]
Client Secret Key: 12312312312312312312312312312312

As soon as I activate the Telit module LwM2M client I've got the following in console:
```tail -f /var/log/thingsboard/thingsboard.log | grep 'DTLS\|lwm2m\|ERROR'
2021-08-18 18:01:41,008 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#10] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 4, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-08-18 18:01:41,009 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#10] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-08-18 18:01:42,011 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 4, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-08-18 18:01:42,011 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-08-18 18:01:44,012 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#6] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 4, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-08-18 18:01:44,013 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#6] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-08-18 18:01:44,377 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#9] WARN  o.e.c.scandium.dtls.ServerHandshaker - Cannot process handshake message from peer [/195.226.133.55:6002] due to [null]
org.thingsboard.server.transport.lwm2m.server.client.LwM2MAuthException: null
        at org.thingsboard.server.transport.lwm2m.secure.LwM2mCredentialsSecurityInfoValidator.getEndpointSecurityInfoByCredentialsId(LwM2mCredentialsSecurityInfoValidator.java:92)
        at org.thingsboard.server.transport.lwm2m.bootstrap.secure.LwM2MBootstrapSecurityStore.getByIdentity(LwM2MBootstrapSecurityStore.java:95)
        at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:1811)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1509)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1365)
```

Under transportLog key, I have the following message: `info: getParametersBootstrap: [Module IMEI] Access connect client with bootstrap server.`

If I avoid the bootstrap process and set the keys manually on the device, the console throws me this error:
```2021-08-18 18:34:59,281 [CoapServer(main)#1] ERROR o.e.l.core.response.SendableResponse - Exception while calling the reponse sent callback```

I will edit this issue or add more information while I keep testing why it fails.

**Environment**
 * OS:  Debian 10 / openjdk 11.0.12 2021-07-20
 * ThingsBoard: 3.3.0
 * Browser: Chrome 92

**Comment by JavierNR** [comment]
Just for updating the issue, I've tried to connect the same end device to leshan sandbox and it connects successfully both bootstrap and server.
I'm leaving here my procedures in order to help other people begining with LwM2M. I'm using Telit ME910C-WW via AT Commands.

- **Procedure in leshan sandbox [WORKING]**
1. Create a client configuration in leshan bootstrap [https://leshan.eclipseprojects.io/bs](url) with following credentials:
  - Endpoint: 353081091430838
  - LwM2M Server:
    - Server URL: default 
    - Security Mode: PSK
    - Identity: 353081091430838
    - Key: 12312312312312312312312312312312
  - LwM2M Bootstrap Server:
    - Server URL: default 
    - Security Mode: PSK
    - Identity: 353081091430838
    - Key: 12312312312312312312312312312312
2. Add security information in leshan server [https://leshan.eclipseprojects.io/](url) with following credentials:
  - Endpoint: 353081091430838
  - Security Mode: PSK
  - Identity: 353081091430838
  - Key: 12312312312312312312312312312312
3. Telit ME910C Module AT Commands:
  - Set LwM2M Keys
    - AT#LWM2MINJKEYS=0,1,"353081091430838","353081091430838","12312312312312312312312312312312"
  - Set LwM2M Bootstrap Server
    - AT#LWM2MSTS=0,999,"coaps://leshan.eclipseprojects.io:5784",1
  - Enable LwM2M
    - AT#LWM2MENA=1

- **Procedure in Thingsboard Server [NOT WORKING]**
1. Create Device Profile and set security mode with PSK:
   ![image](https://user-images.githubusercontent.com/1872120/132845603-d2bb2d2e-86a9-47b7-8f6e-aa9cab7efc7a.png)
2. Add some objects to LwM2M Device Profile:
   ![image](https://user-images.githubusercontent.com/1872120/132845895-e10ea899-ed91-4262-9a9f-cde9bb5b3fa9.png)
3. Add device that uses LwM2M Profile:
   ![image](https://user-images.githubusercontent.com/1872120/132846045-5a14cbf6-d677-4f3b-8f61-a91530a9c263.png)
4. Device credentials (Client Security Config):
   ![image](https://user-images.githubusercontent.com/1872120/132846136-b64502a5-ca93-4772-9019-1afae405584e.png)
5. Device credentials (Bootstrap Client):
   ![image](https://user-images.githubusercontent.com/1872120/132846327-35d90872-9dc8-475c-982e-0892402b3109.png)
6. Telit ME910C Module AT Commands:
   - Set LwM2M Bootstrap Server
    - AT#LWM2MSTS=0,999,"coaps://THINGSBOARDSERVERURL:5788",1
7. Logs and screenshots:
tail -f /var/log/thingsboard/thingsboard.log | grep 'DTLS\|lwm2m\|ERROR\|Coap'
```2021-09-10 13:30:10,901 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#10] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 4, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-09-10 13:30:10,904 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#10] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-09-10 13:30:11,583 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#4] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 6, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-09-10 13:30:11,585 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#4] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-09-10 13:30:15,109 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - Bootstrap session started securityInfos: [java.util.Collections$1@6cd5e8ae]
2021-09-10 13:30:15,110 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - Bootstrap session started : DefaultBootstrapSession [id=j9oKkZyKJH, endpoint=353081091430838, identity=Identity /195.226.133.57:6002[psk=353081091430838], authorized=true, contentFormat=ContentFormat [name=TLV, code=11542], creationTime=1631273415110, request=org.eclipse.leshan.core.request.BootstrapRequest@3c84c5a3, cancelled=false]```

Device has created server attributes and a telemetry key, but no LwM2M objects as attributes. The device doesn't conclude the bootstrap process.
![image](https://user-images.githubusercontent.com/1872120/132847457-81421d14-edad-4e4b-91aa-222add224244.png)
![image](https://user-images.githubusercontent.com/1872120/132847506-2de1ad42-8d0a-42fe-8317-c0aa9cde5053.png)

**Comment by JavierNR** [comment]
Hello @ashvayka 

I've installed 3.3.2 version, and still doesn't work. As my device under test doesn't output logs about the connection, I've decided to try Lwm2m client with node-red and enable all lwm2m messages.

I think, the client sends the bootstrap messages to TB server correctly and is getting bad endpoint IP address.
I've attached to this message the file of the client side, but I think that the problem is that the server sends the ip to register to, as 127.0.0.1 (check last lines of the attached log)

``done:cmd=>[read], resp=>[/resp], base64=>[AgFFAAABAAEAAgAGAQAw], base64Len=>[20], expectedPayloadLen=>[20]
prv_generic_read:(lwm2m_data_new):numData=>1
prv_generic_read:result=>0x45
Sending 67 bytes to [127.0.0.1]:0
16 FE FD 00  00 00 00 00  00 00 00 00  36 01 00 00   ............6...
2A 00 00 00  00 00 00 00  2A FE FD 00  00 00 0D 21   *.......*......!
F5 B7 E4 78  F3 63 BD 59  07 6F 7B BC  C9 51 94 09   ...x.c.Y.o{..Q..
81 E0 22 8E  90 A4 20 3C  6F F6 75 00  00 00 02 C0   .."... <o.u.....
A8 01 00                                             ...
#> failed sending 98 bytes``

I've tried to change servers IP on LwM2M Device profile, and change LWM2M_BIND_ADDRESS, LWM2M_SECURITY_BIND_ADDRESS and BS address on yml but lwm2m still gets 127.0.0.1 as response.

Do you have some advice, or maybe a way to check lwm2m logs on thingsboard side in order to get around this problem?

Will try on another machine on my side and keep this question opened.

Regards
[Lwm2m log with bootstrap.txt](https://github.com/thingsboard/thingsboard/files/7527167/Lwm2m.log.with.bootstrap.txt)

**Comment by AlexDoanTB** [comment]
Hi @JavierNR , this is a known issue. 
We are working on a newer version of the Bootstrap server implementation. So far it looks to LwM2M v1.0 while now we are using LwM2M v1.1 specification. Although the update is under development, your testing can help us to make a bugless release  

Update of Bootstrap in this branch — https://github.com/thingsboard/thingsboard/tree/develop/3.3.3

**Comment by JavierNR** [comment]
Hi @AlexDoanTB ,

Will checkout the 3.3.3 branch and keep this issue updated with my findings.

Currently I've tested 3.3.2 release with my end device doing the bootstrap with leshan demo server and pointing my tb server as the final LwM2M server, the device bootstraps correctly and I can see under transportLog:
 
![image](https://user-images.githubusercontent.com/1872120/142625051-a01d9da5-0621-4cb8-a999-bd214f1b83ab.png)

Thingsboard sends read requests to the device but at the end, the device only answers to a few, the rest of responses ends with timeouts. And also the end device feels unresponsive for a while.

![image](https://user-images.githubusercontent.com/1872120/142625436-3673f35e-a0d6-4e30-945f-c4a01d6f176b.png)

Note that this same device bootstraps and registers correctly under leshan demo servers.
Will keep you updated.

Best regards

**Comment by AlexDoanTB** [comment]
@JavierNR What would the RPC request timeout be configured within RPC terminal widget (Advanced setting). The default value of 500 ms might be insufficient for your network

**Comment by JavierNR** [comment]
> @JavierNR What would the RPC request timeout be configured within RPC terminal widget (Advanced setting). The default value of 500 ms might be insufficient for your network

Hello @AlexDoanTB at the moment don't use this device in any dashboard nor widget, these messages comes at device registration cycle.

Today I've compiled and clean install of develop/3.3.3 branch commit 2a54196f82f72e5745829eca484bcb25779b5e18

The device still doesn't bootstrap, but will continue to test and check new commits as soon as "see" commits regarding lwm2m process.

Here is my last log:
```2021-11-24 17:25:31,845 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#8] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 4, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-11-24 17:25:31,845 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#8] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverId = [123]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - publicKeyOrId  [353081091430838]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - secretKey [12312312312312312312312312312312]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverSecurity.uri = [coaps://tbaddress.com:5686]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - server []
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverId = [111]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - publicKeyOrId  [353081091430838]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - secretKey [12312312312312312312312312312312]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverSecurity.uri = [coaps://tbaddress.com:5688]
2021-11-24 17:25:32,398 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - server []
2021-11-24 17:25:32,399 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#3] ERROR o.t.s.t.l.b.s.LwM2MBootstrapSecurityStore - Invalid Bootstrap Configuration
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MInMemoryBootstrapConfigStore.addToStore(LwM2MInMemoryBootstrapConfigStore.java:76)
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MInMemoryBootstrapConfigStore.add(LwM2MInMemoryBootstrapConfigStore.java:59)
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MBootstrapSecurityStore.getByIdentity(LwM2MBootstrapSecurityStore.java:107)
        at org.eclipse.californium.scandium.DTLSConnector.processHandshakeRecord(DTLSConnector.java:1811)
        at org.eclipse.californium.scandium.DTLSConnector.processRecord(DTLSConnector.java:1509)
        at org.eclipse.californium.scandium.DTLSConnector$12.run(DTLSConnector.java:1365)
2021-11-24 17:25:32,503 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#1] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 6, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-11-24 17:25:32,503 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#1] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverId = [123]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - publicKeyOrId  [353081091430838]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - secretKey [12312312312312312312312312312312]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverSecurity.uri = [coaps://tbaddress.com:5686]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - server []
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverId = [111]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - publicKeyOrId  [353081091430838]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - secretKey [12312312312312312312312312312312]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverSecurity.uri = [coaps://tbaddress.com:5688]
2021-11-24 17:25:36,888 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - server []
2021-11-24 17:25:36,888 [CoapServer(main)#1] ERROR o.t.s.t.l.b.s.LwM2MBootstrapSecurityStore - Invalid Bootstrap Configuration
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MInMemoryBootstrapConfigStore.addToStore(LwM2MInMemoryBootstrapConfigStore.java:76)
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MInMemoryBootstrapConfigStore.add(LwM2MInMemoryBootstrapConfigStore.java:59)
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MBootstrapSecurityStore.getAllByEndpoint(LwM2MBootstrapSecurityStore.java:83)
        at org.thingsboard.server.transport.lwm2m.bootstrap.secure.LwM2mDefaultBootstrapSessionManager.begin(LwM2mDefaultBootstrapSessionManager.java:90)
        at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:227)
        at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:204)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:137)
        at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:309)
2021-11-24 17:25:36,889 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - info: Bootstrap session started...
2021-11-24 17:25:36,890 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - error: Bootstrap session failed because of NO_BOOTSTRAP_CONFIG

**Comment by nickAS21** [comment]
1. You need to upgrade to version 3.3.3
To do this, run
ThingsboardInstallApplication
in config: with VM options: 
-Dinstall.upgrade=true
-Dinstall.upgrade.from_version=3.3.2
2. After that, in the profile configuration, delete the bootstrap section

**Comment by JavierNR** [comment]
Hello @nickAS21 

Just an update of the issue, I've run a clean Thingsboard installation from develop/3.3.3 commit https://github.com/thingsboard/thingsboard/commit/774f175f7fdc98f5807bb6659b4e28329949bbf8 
I've deleted database and installed fresh compiled .deb. Upload LWM2M xml files from 0 to 14 object, created LwM2M device profile and a test device with PSK.
Also enabled subscribing a few lwm2m objects as attributes

![image](https://user-images.githubusercontent.com/1872120/143867023-adbbd7a8-702e-4897-a1fa-4045c7b285b0.png)

**Test results**
- My telit board ends bootstrap with INTERNAL_SERVER_ERROR as seen on tb logs
- Node red with node-red-contrib-lwm2m ends bootstrap with INTERNAL_SERVER_ERROR
- leshan-client-demo.jar bootstraps and registers successfully but I can't see lwm2m attributes on device

I'm attaching thingsboard side logs of failed device bootstrap (in this case with node-red-contrib-lwm2m) but telit device does the same.

 ````
2021-11-29 12:57:28,612 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#11] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 4, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-11-29 12:57:28,612 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#11] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-11-29 12:57:28,689 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#7] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverId = [123]
2021-11-29 12:57:28,689 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#7] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - publicKeyOrId  [454545452345657488]
2021-11-29 12:57:28,689 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#7] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - secretKey [45454545234565748857575757575757]
2021-11-29 12:57:28,689 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#7] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverSecurity.uri = [coaps://tbserver.com:5686]
2021-11-29 12:57:28,689 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#7] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - server []
2021-11-29 12:57:28,691 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#7] INFO  o.e.c.scandium.dtls.DTLSFlight - Prepare flight 6, using max. datagram size 1436, max. fragment size 16384 [mhm=false, mr=true]
2021-11-29 12:57:28,691 [DTLS-Worker-0.0.0.0/0.0.0.0:5688#7] INFO  o.e.c.scandium.dtls.DTLSFlight - Effective max. datagram size 1436
2021-11-29 12:57:30,781 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverId = [123]
2021-11-29 12:57:30,782 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - publicKeyOrId  [454545452345657488]
2021-11-29 12:57:30,782 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - secretKey [45454545234565748857575757575757]
2021-11-29 12:57:30,783 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - serverSecurity.uri = [coaps://tbserver.com:5686]
2021-11-29 12:57:30,783 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfig - server []
2021-11-29 12:57:30,783 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - info: Bootstrap session started...
2021-11-29 12:57:30,786 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - tasks.requestsToSend = [[DiscoverRequest [/]]]
2021-11-29 12:57:30,832 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - info: BootstrapDiscoverRequest / receives error response DiscoverResponse [code=BAD_REQUEST(400), errormessage=]
2021-11-29 12:57:30,834 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2MBootstrapConfigStoreTaskProvider - Bootstrap Discover return error DiscoverResponse [code=BAD_REQUEST(400), errormessage=] : to continue bootstrap session without autoIdForSecurityObject mode. DefaultBootstrapSession [id=11qgwcJqhL, endpoint=454545452345657488, identity=Identity /88.16.255.43:56839[psk=454545452345657488], authorized=true, contentFormat=TLV(11542), creationTime=1638187050783, request=org.eclipse.leshan.core.request.BootstrapRequest@8157343d, cancelled=false]
2021-11-29 12:57:30,834 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - tasks.requestsToSend = [[BootstrapReadRequest [path=/1 format=null]]]
2021-11-29 12:57:30,878 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - info: BootstrapReadRequest /1 receives error response BootstrapReadResponse [code=BAD_REQUEST(400), errormessage=]
2021-11-29 12:57:30,881 [CoapServer(main)#1] WARN  o.e.l.s.b.DefaultBootstrapHandler - Unexpected error on response callback for DefaultBootstrapSession [id=11qgwcJqhL, endpoint=454545452345657488, identity=Identity /88.16.255.43:56839[psk=454545452345657488], authorized=true, contentFormat=TLV(11542), creationTime=1638187050783, request=org.eclipse.leshan.core.request.BootstrapRequest@8157343d, cancelled=false]
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MBootstrapConfigStoreTaskProvider.findServerInstanceId(LwM2MBootstrapConfigStoreTaskProvider.java:155)
        at org.thingsboard.server.transport.lwm2m.bootstrap.store.LwM2MBootstrapConfigStoreTaskProvider.getTasks(LwM2MBootstrapConfigStoreTaskProvider.java:103)
        at org.thingsboard.server.transport.lwm2m.bootstrap.secure.LwM2mDefaultBootstrapSessionManager.nextRequest(LwM2mDefaultBootstrapSessionManager.java:146)
        at org.thingsboard.server.transport.lwm2m.bootstrap.secure.LwM2mDefaultBootstrapSessionManager.onResponseError(LwM2mDefaultBootstrapSessionManager.java:193)
        at org.eclipse.leshan.core.californium.CoapAsyncRequestObserver.onResponse(CoapAsyncRequestObserver.java:99)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveResponse(BaseCoapStack.java:214)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveResponse(BaseCoapStack.java:143)
        at org.eclipse.californium.core.network.CoapEndpoint$1.receiveResponse(CoapEndpoint.java:321)
2021-11-29 12:57:30,883 [CoapServer(main)#1] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - error: Bootstrap session failed because of INTERNAL_SERVER_ERROR
````

**Comment by KKoovalsky** [comment]
@JavierNR from the logs it is clear that your client responds with 404 to Bootstrap Interface commands (Bootstrap Discover, Bootstrap Read Request). I had similar issue - my LWM2M client expected that basic LWM2M bootstrap scenario will be run ("send me LwM2M server URI").

I wonder whether there is a way for the Bootstrap Server, within Thingsboard, to not use the Bootstrap Interface commands?

**Comment by AlexDoanTB** [comment]
@JavierNR @KKoovalsky omitting Bootstrap commands is not recommended (not possible) as this breaches the device indexation that eventually will cause a boot loop of the device.  
With BootstrapDiscover TB checks existing objects and indexes. 
Upon result we read data from available objects — BootstrapReadRequest. 
Afterward, data update comes with WriteRequest.

Without the default approach, one configures LwM2M server on TB, and either the same setting applies towards Bootstrap or the device will have 2 configurations with the same index (Id for connection). As a result, the device will stuck on a fence, choosing between bootstrap port: 5687 and lwm2m port: 5685

**Comment by KKoovalsky** [comment]
@AlexDoanTB well, after applying the patch, I have tried that with the Wakaama client, according to the [guide here](https://thingsboard.io/docs/reference/lwm2m-api/#step-4-connect-the-device), and it worked. The client finds no problem connecting to the LwM2M Server over 5685 port.

**Comment by ban2derlog** [comment]
Hi, @JavierNR 
Do you try to update to latest version already?
Is this resolve your issue?

**Comment by JavierNR** [comment]
Hello,

I've installed thingsboard latest version 3.4.1 and did a quick test with my end devices (Quectel BG77)
At bootstrap phase I can see the following error:
````
2022-09-03 17:32:55,143 [CoapServer(main)#5] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - Endpoint: [urn:imei:866349041113576] [info: Bootstrap session started...]
2022-09-03 17:32:55,151 [CoapServer(main)#5] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - tasks.requestsToSend = [[DiscoverRequest [/]]]
2022-09-03 17:32:55,444 [CoapServer(main)#8] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - Endpoint: [urn:imei:866349041113576] [error: BootstrapDiscoverRequest / failed because of org.eclipse.leshan.core.link.LinkParseException: Invalid Links [lwm2m="1.0",</0/0>,</1/0>;ssid=111,</2>,</3/0>,</4/0>,</5/0>,</6/0>,</7/0>,</9/0>,</10/0>,</11/0>,</15/0>,</16/0>,</16/1>,</19/0>,</19/1>,</10308/0>] : URI-Reference [lwm2m="1.0"] should begin with "<" and ends with ">"]
2022-09-03 17:32:55,450 [CoapServer(main)#8] INFO  o.t.s.t.l.b.s.LwM2mDefaultBootstrapSessionManager - Endpoint: [urn:imei:866349041113576] [error: Bootstrap session failed because of REQUEST_FAILED]
````
I've tested leshan sandbox, and I see that recently they added the option Auto ID for security Object under bootstrap:
![image](https://user-images.githubusercontent.com/1872120/188420446-419d9396-8282-464e-ab8b-6e00de92282e.png)

My device fails if I leave that switch to true, so I gave a try with @KKoovalsky suggestion and compiled 3.4.1 with autoIdForSecurityObject = false and the end device bootstraps and registers successfully.

I'm not an LwM2M expert here, but I think the end device doesn't support autoID, so at the moment will stick to custom compiled thingsboard with this flag to false.

But, maybe tb team could add this feature selectable on device profile?

Thanks again

**Comment by ban2derlog** [comment]
Hi,
I don't have a valid LWM2M device for testing, but I assume that you can try this workarounds:
Set this environment and change default `111` to `0` in this parameter:
[`LWM2M_SERVER_ID_BS`](https://thingsboard.io/docs/pe/user-guide/install/config/#local-lwm2m-transport-parameters)

About `autoID` setting - I need to check.

**Comment by ban2derlog** [comment]
@JavierNR 
Hi, do you try to set on default ThingsBoard package environment from comment above?

Additionally, about AutoID - this is feature in ThingsBoard, because this function is best recommendation for BootStrap server for LWM2M.
As BootStrap server main purpose of setting new security policies and parameters for next restart of device - this is required function for security purposes.
I assume is that using [LWM2M_SERVER_ID_BS](https://thingsboard.io/docs/pe/user-guide/install/config/#local-lwm2m-transport-parameters) parameter can resolve issue with your devices without disabling AutoID and rebuilding a package.
