### ISSUE TITLE
[Bug] Sometimes telemetry data is not sent. 

### ISSUE THREAD

**Issue by kumiizoo** [thingsboard/thingsboard#5109]
**Describe the bug**
Although all pods in k8s are running, sometimes telemetry data is not sent. We use PE 3.0.0 on k8s bellow https://github.com/thingsboard/thingsboard-pe-k8s. We always resolve the issue to restart all pods. But we would like to know why the issue happens.

**Your Server Environment**

* own setup
  * cloud or local infrastructure or docker deployment:Kubernetes 1.18.8-aliyun.1 
  * ThingsBoard Version:Professional Edtion 3.0.0
  * OS Name and Version:N/A

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser:chrome
* Version:92.0.4515.131

**Your Device**

* Connectivity
  * HTTP
* Device vendor and model
  * obnizOS and obniz.js
  * https://obniz.com/ja/doc/reference/common/

**Expected behavior**
telemetry data is always sent.

**Comment by kumiizoo** [comment]
tb-node pod outputted the log bellow in the issue.

```
2021-08-19 07:08:54,582 [tb-core-consumer-17-thread-1] WARN  o.t.s.s.q.DefaultTbCoreConsumerService - [cde4b129-77d9-4f53-829d-6ad4ef37bdfe] Timeout to process message: toDeviceActorMsg {
  sessionInfo {
    nodeId: "tb-http-transport-969964c54-46ssq"
    sessionIdMSB: 7518168410659440409
    sessionIdLSB: -9084015275832282196
    tenantIdMSB: 2666820583280415211
    tenantIdLSB: -5654313485976093397
    deviceIdMSB: -2224511030667308565
    deviceIdLSB: -5654313485976093397
    deviceName: "\343\202\253xxx"
    deviceType: "Refrigerator"
  }
  subscriptionInfo {
    lastActivityTime: 1629356932577
  }
}
```

**Comment by kumiizoo** [comment]
Also both tb-http-transport pods always output the log bellow in the issue.

```
2021-08-19 06:27:52,960 [ForkJoinPool-1-worker-6] WARN  o.t.s.t.http.DeviceApiController - Failed to process request
java.util.concurrent.TimeoutException: null
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$null$1(DefaultTbQueueRequestTemplate.java:138)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$init$2(DefaultTbQueueRequestTemplate.java:133)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ban2derlog** [comment]
Hi.
First, try this deployment on latest versions of  ThingsBoard - from 3.0.0 there was a magnificent quantity of improvement and fixes.
Second, ThingsBoard main services are coded on Java, so you can change Logger level from INFO to DEBUG\TRACE and have much more output for investigating your internal problem\problems in your deployment.
Third, it's a small chance, but - check your internal\external network (ISP issue) - there can be a filter\firewall that will block connection after some X connections for Y period of time. It can be an AntiDDOS system or something like that.
