### ISSUE TITLE
[Bug]  Update from 3.2.2 to 3.3.0, got rule chain error

### ISSUE THREAD

**Issue by zxy54** [thingsboard/thingsboard#5172]
**Describe the bug**
Update from 3.2.2 to 3.3.0, applied schema_update.sql, got error finding rule chain with backtrace like:

**Your Server Environment**

* own setup
  * local docker
  * ThingsBoard 3.2.2 to 3.3.0
  * ubuntu 20.04

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: windows10
* Browser firefox
* Version 91.0.2

**To Reproduce**
1. Upgrade from ver 3.2.2 to 3.3.0, applied sql upgrade
2. Login and click RuleChain
3. See error

**Expected behavior**
Rule chains found with ease

**Screenshots**
![图片](https://user-images.githubusercontent.com/5396350/131477953-c8c73189-a276-4484-80a7-e7bf7e1fb273.png)

**Correction**
Add these two lines in sql:

ALTER TABLE rule_chain ADD COLUMN IF NOT EXISTS type varchar(255);

UPDATE rule_chain SET type = 'CORE';

Hope that helps.

**Comment by Strauteka** [comment]
Maybe similar problem with Docker thingsboard/tb-postgres upgrade 3.1.1 to 3.3.0
```
Failed updating schema!!!
org.postgresql.util.PSQLException: ERROR: column "device_profile_id" contains null values
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.loadSql(SqlDatabaseUpgradeService.java:479)
        at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:415)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:182)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```
From PG logs
```
CREATE TABLE IF NOT EXISTS device_profile (
postgres_1   |      id uuid NOT NULL CONSTRAINT device_profile_pkey PRIMARY KEY,
postgres_1   |      created_time bigint NOT NULL,
postgres_1   |      name varchar(255),
postgres_1   |      type varchar(255),
postgres_1   |      transport_type varchar(255),
postgres_1   |      provision_type varchar(255),
postgres_1   |      profile_data jsonb,
postgres_1   |      description varchar,
postgres_1   |      search_text varchar(255),
postgres_1   |      is_default boolean,
postgres_1   |      tenant_id uuid,
postgres_1   |      default_rule_chain_id uuid,
postgres_1   |      default_queue_name varchar(255),
postgres_1   |      provision_device_key varchar,
postgres_1   |      CONSTRAINT device_profile_name_unq_key UNIQUE (tenant_id, name),
postgres_1   |      CONSTRAINT device_provision_key_unq_key UNIQUE (provision_device_key),
postgres_1   |      CONSTRAINT fk_default_rule_chain_device_profile FOREIGN KEY (default_rule_chain_id) REFERENCES rule_chain(id)
```
```
 CREATE OR REPLACE PROCEDURE update_device_profiles()
postgres_1   |      LANGUAGE plpgsql AS
postgres_1   |  $$
postgres_1   |  BEGIN
postgres_1   |      UPDATE device as d SET device_profile_id = p.id, device_data = '{"configuration":{"type":"DEFAULT"}, "transportConfiguration":{"type":"DEFAULT"}}'
postgres_1   |          FROM
postgres_1   |             (SELECT id, tenant_id, name from device_profile) as p
postgres_1   |                  WHERE d.device_profile_id IS NULL AND p.tenant_id = d.tenant_id AND d.type = p.name;
postgres_1   |  END;
```
selecting from empty table(shortly before created) device_profile. (if I'm not mistaken). Table does not exists in 3.1.1

And 
```
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:281)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:531)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:154)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy180.findByTenantIdAndTypeAndRootIsTrue(Unknown Source)
        at org.thingsboard.server.dao.sql.rule.JpaRuleChainDao.findRootRuleChainByTenantIdAndType(JpaRuleChainDao.java:76)
        at org.thingsboard.server.dao.sql.rule.JpaRuleChainDao$$FastClassBySpringCGLIB$$837e70a6.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
...
```
**Successful** migration from 3.1.1 to 3.3.0 can be achieved using Docker thingsboard/tb-postgres:3.2.1 and then Docker thingsboard/tb-postgres:latest/3.3.0
First schema migration from 3.1.1 to 3.2.1 and then from 3.2.1 to 3.3.0

~Example: from [docker](https://hub.docker.com/r/thingsboard/tb-postgres) run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgress upgrade-tb.sh

**Comment by volodymyr-babak** [comment]
@zxy54 
Please provide steps that you did to upgrade your database.

SQL database schema modified from Java and it must be updated if upgrade script executed like this:
docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres upgrade-tb.sh

**Comment by zxy54** [comment]
Previously, the upgrade was only done by package update and importing sql under appplication/src/main/upgrade , not via using upgrade commands in install service. So the issue seems only caused by invalid operation, I'll close this issue, thanks for reply.
