### ISSUE TITLE
[Bug] Upgrade from dockerized Thingsboard 3.2.1 to 3.2.2 fails due to Cassandra configuration error

### ISSUE THREAD

**Issue by jonrot1906** [thingsboard/thingsboard#5214]
**Describe the bug**
When I was trying to do a release-by-release upgrade from dockerized Thingsboard-Cassandra 3.2.0 to 3.3.1, the upgrade fails every time at the upgrade step 3.2.1 to 3.2.2. The error presents itself by an endless waiting loop until Cassandra starts. I opened a bash shell in the upgrade docker container because of this and tried to start Cassandra manually. Here the following configuration error causes a shutdown of Cassandra:

```Cannot change the number of tokens from 256 to 16
Fatal configuration error; unable to start server.  See log for stacktrace.
ERROR [main] 2021-09-08 18:37:49,734 CassandraDaemon.java:822 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Cannot change the number of tokens from 256 to 16
        at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1045)
        at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:994)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:793)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:723)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:400)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:676)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:800)
```

**Your Server Environment**

* own setup
  * docker deployment
  * ThingsBoard Version: 3.2.1
  * OS Name and Version: Ubuntu 20.04.3 LTS

**To Reproduce**
1. Follow steps for installing Thingsboard-Cassandra 3.2.1 on [Installing ThingsBoard using Docker (Linux or Mac OS)](https://thingsboard.io/docs/user-guide/install/docker/)
2. Set current Thingsboard version in `$(DATA_FOLDER)/.upgradeversion` (in this case 3.2.1)
3. Try to do an upgrade from Thingsboard-Cassandra 3.2.1 to 3.2.2, following same instructions

Is this behaviour related to the Cassandra 4.0 update? How can I fix it?

**Comment by jonrot1906** [comment]
I'm starting to get a workaround on this. For anyone who struggles as well, here is how I went:

1. Changing num_tokens parameter in docker-cassandra by adding `RUN sed -i 's/num_tokens: 16/num_tokens: 256/g' /etc/cassandra/cassandra.yaml` on line 31 to the Dockerfiles of version 3.2.2, 3.3.0 and 3.3.1.
2. Build docker images. Note that version 3.2.2 uses deprecated postgresql repo, so replace `RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ sid-pgdg main' | tee --append /etc/apt/sources.list.d/pgdg.list > /dev/null` with `RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' | tee --append /etc/apt/sources.list.d/pgdg.list > /dev/null` in both docker-cassandra and docker-postgres (otherwise build will fail).
3. Do docker upgrade according to the [Thingsboard Guide](https://thingsboard.io/docs/user-guide/install/docker/), going from version 3.2.0 to 3.2.1 (using thingsboard/tb-cassandra:3.2.1), afterwards use your own docker images. Don't forget to edit .upgradeversion between each step!
4. Stop at step 3.2.2 -> 3.3.0. Thingsboard now uses Postgresql 12 instead of version 11, so we need to migrate our data. Thanks to @tianon [(look here)](https://github.com/tianon/docker-postgres-upgrade) we can use specific update containers: `docker run --rm -v ~/.mytb-src/db:/var/lib/postgresql/11/data -v ~/.mytb-dst/db:/var/lib/postgresql/12/data -e PGUSER="thingsboard" -e POSTGRES_INITDB_ARGS="-U thingsboard --local=C.UTF-8" -e POSTGRES_PASSWORD="postgres" tianon/postgres-upgrade:11-to-12` . 

- Note that we used specific Postgresql user and local settings.
- ~/.mytb-src/db is where the original data is coming from. ~/.mytb-dst/db ist where it will be migrated to.
- We need to copy cassandra database data (`cp ~/.mytb-data/cassandra ~/.mytb-dst`) as well as our .upgradversion file `(cp ~/.mytb-data/.upgradeversion ~/.mytb-dst)`

5. Edit .upgradeversion in your new .mytb-dst folder to "3.2.2".
6. Set rights right: `chown -R 799:799 ~/.mytb-dst`
7. Run your docker-cassandra 3.3.0 image: `docker run -it -v ~/.mytb-dst:/data --rm ${dockeruser}/${dockerimagename}:3.3.0 upgrade-tb.sh`
