### ISSUE TITLE
Error: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1

### ISSUE THREAD

**Issue by anbha** [thingsboard/thingsboard#524]
Hi,

I tried to creating Alarm and sending email. There is an error occurred in plugin>events>error>
Failed to send email.
Error is
"org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1; message exception details (1) are:
Failed message 1:
javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1694)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:525)
	at javax.mail.Service.connect(Service.java:291)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:501)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:421)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:340)
	at org.thingsboard.server.extensions.core.plugin.mail.MailPlugin.sendMail(MailPlugin.java:120)
	at org.thingsboard.server.extensions.core.plugin.mail.MailPlugin.lambda$process$1(MailPlugin.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)"

Am using token SMTP, host smtp.gmail.com, port 465 and authentication and TLS are enable true.

So, help me how to solve this issue. Your quick answer is so helpful for me. 

Thanks and regards.

**Comment by anbha** [comment]
Hi,

I solved this issue.
Solution is i changed port 465 to 587. Because am setting in mail properties TLS(Transport security layer) Enable is true .
So i changed port to 587.
Now its working. Email was send.

**Comment by ravisyam09** [comment]
Need solution

**Comment by Mwamba30** [comment]
not work for @anbha

**Comment by Mwamba30** [comment]
error i get 
Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 501 <JEMATECH@[192.168.1.82]>: domain literals not allowed

**Comment by Wanderzhd** [comment]
Need solution:
https://github.com/thingsboard/thingsboard/issues/2728

**Comment by simaltpl** [comment]
thanks
