### ISSUE TITLE
[Bug] can not install Thingboard CE on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by gilbertoe** [thingsboard/thingsboard#5244]
Hi

I am trying to install thingsboard ce on Ubuntu 20.04.3 LTS computer.
I use the procedure described here https://thingsboard.io/docs/user-guide/install/ubuntu/
Everything is fine until step 6. It seems there  a user already present in database. The console log is below:
gilberto@kerberos:~$ sudo gedit /etc/thingsboard/conf/thingsboard.conf

(gedit:9938): Tepl-WARNING **: 19:39:55.876: GVfs metadata is not supported. Fallback to TeplMetadataManager. Either GVfs is not correctly installed or GVfs metadata are not supported on this platform. In the latter case, you should configure Tepl with --disable-gvfs-metadata.
gilberto@kerberos:~$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard ::       (v3.3.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!
	at org.thingsboard.server.dao.user.UserServiceImpl$2.validateDataImpl(UserServiceImpl.java:447)
	at org.thingsboard.server.dao.user.UserServiceImpl$2.validateDataImpl(UserServiceImpl.java:387)
	at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:67)
	at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:130)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createUser(DefaultSystemDataLoaderService.java:494)
	at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createSysAdmin(DefaultSystemDataLoaderService.java:179)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:235)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

Could someone provide some advise?

BR
Gilberto

**Comment by jonrot1906** [comment]
Try to drop your thingsboard database in postgresql and try again.

**Comment by trypzz** [comment]
Hi,

This is looking like you trying install thingsboard not the first time. 

This error, means, that some data in database already present. If you need clear installation, just drop the database and recreate again.

# sudo su -l postgres -c "psql"
# drop database thingsboard;
# create database thingsboard;

After this rerun install script.
