### ISSUE TITLE
[Bug] CoAP observation drops

### ISSUE THREAD

**Issue by jairohg** [thingsboard/thingsboard#5263]
**Bug**
CoAP observation relationship is "lost" ~1min after being established. While trying to Observe coap://host/api/v1/$ACCESS_TOKEN/rpc

**Server**
Confirmed on 
* demo.thingsboard.io
and 
* ThingsBoard PE 3.3.0 running on Ubuntu 20.04.3 (Docker monolith) 

**Your Device**

* Connectivity
  * CoAP 
Reproducible with "coap-client" from libcoap 4.3.0 running on linux (Ubuntu 20.04.3)

**To Reproduce**
1. Using the sample widget "send rpc" on a dashboard. Attempt to send an RPC command to coap-client, which is subscribed by launching the process with the following syntax:
`./coap-client -m get coap://demo.thingsboard.io/api/v1/$ACCESS_TOKEN/rpc -s 720`
2. Click on "send rpc". Which should result in the following output being printed (stdout) by the coap-client process:
`{"id":1,"method":"rpcCommand","params":{}}`
3. Wait ~1min or longer and click "send rpc". This command will never reach the coap-client. 

**Expected behavior**
CoAP observation should not be dropped without notifying the observer.

**Relevant logs**
`2021-09-21 13:37:38,274 [DefaultTransportService-22-6] INFO  o.e.californium.core.CoapResource - successfully established observe relation between 172.19.0.1:36342#BEEFFEED and resource /api/v1 (Exchange[R1132], size 33)`

after failing to send RPC to device

`2021-09-21 13:45:06,488 [CoapServer(main)#2] INFO  o.e.c.c.network.stack.ObserveLayer - notification for token [Token=BEEFFEED] timed out. Canceling all relations with source [/172.19.0.1:36342]
2021-09-21 13:45:06,489 [CoapServer(main)#2] INFO  o.e.californium.core.CoapResource - remove observe relation between 172.19.0.1:36342#BEEFFEED and resource /api/v1 (Exchange[R1132, complete], size 32)
2021-09-21 13:45:06,489 [CoapServer(main)#2] ERROR o.e.c.c.n.stack.ReliabilityLayer - Exception for Exchange[R1132, complete] in MessageObserver: null
java.lang.NullPointerException: null
	at org.thingsboard.server.transport.coap.client.DefaultCoapClientContext.cancelRpcSubscription(DefaultCoapClientContext.java:741)
	at org.thingsboard.server.transport.coap.client.DefaultCoapClientContext.deregisterObserveRelation(DefaultCoapClientContext.java:176)
	at org.thingsboard.server.transport.coap.CoapTransportResource$CoapResourceObserver.removedObserveRelation(CoapTransportResource.java:504)
	at org.eclipse.californium.core.CoapResource.removeObserveRelation(CoapResource.java:778)
	at org.eclipse.californium.core.observe.ObserveRelation.cancel(ObserveRelation.java:151)
	at org.eclipse.californium.core.observe.ObservingEndpoint.cancelAll(ObservingEndpoint.java:74)
	at org.eclipse.californium.core.observe.ObserveRelation.cancelAll(ObserveRelation.java:162)
	at org.eclipse.californium.core.network.stack.ObserveLayer$NotificationController.onTimeout(ObserveLayer.java:233)
	at org.eclipse.californium.core.coap.Message.setTimedOut(Message.java:954)
	at org.eclipse.californium.core.network.Exchange.setTimedOut(Exchange.java:707)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.retry(ReliabilityLayer.java:524)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.access$200(ReliabilityLayer.java:430)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask$1.run(ReliabilityLayer.java:467)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:289)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Additional context**
Somewhat noteworthy is the fact that monitoring the packets in/out we could not observe any outgoing packets for the failed RPC to device. Additionally, this interaction is on IPv6, and yet the log shows the observation being mapped to IPv4.

**Comment by WillNilges** [comment]
https://github.com/thingsboard/thingsboard-udp-loadbalancer/pull/6

**Comment by WillNilges** [comment]
I suppose it's worth mentioning the setup that I see my issues on. I'm running an RKE v1.21.5 cluster on Fedora Server 34, virtualized on self-hosted Proxmox. I'm using a modified version of the minikube scripts located [here](github.com/thingsboard/thingsboard-ce-k8s) to do so. With a Calico networking addon, and the ThingsBoard COAP transport patched through a NodePort, I'm seeing the same behavior. 

@ashvayka do you think you can share any documentation or test results you have from this project? As far as we know, we've seen this issue in all environments and all deployments. I'd love to work with you in trying to get this LB working on Kube, but I'm confused as to where exactly this LB is supposed to run. What exactly are the issues posed by running this containerized? Is it supposed to be installed on a services VM like a typical HAProxy deployment does?

It sounds like it's supposed to be installed on a host system and then run as a daemon or something, but the presence of Dockerfiles and the implication that this can run in conjunction with a microservices deployment is confusing me.

**Comment by WillNilges** [comment]
I have an update: @jairohg and I tried using CoAP with and without DTLS on a K8s Thingsboard deployment (same specs as above: RKE v1.21.5 cluster on Fedora Server 34, virtualized on self-hosted Proxmox) using MetalLB. The agent we're using connected OK, but RPC still dies about 2 minutes in. So MetalLB also doesn't seem to fit the bill.

I don't quite understand why we're seeing this issue even when a baremetal deployment is using a NodePort to pass traffic to the CoAP transport. We're sure that it's Docker? How exactly does the Thingsboard UDP LB address the issue if it's not required to run in a docker container, instead running on the host as a `.deb` package?

**Comment by WillNilges** [comment]
Got an update: I actually managed to pass traffic from the LB to my cluster using this. I have my cluster on one Fedora VM, and my LB is on a separate Ubuntu VM. However, I dont think this is the correct configuration, because while we can pass traffic, we're still seeing this CoAP Observation dropping issue. Do I need to... somehow... install the lb _on_ the cluster and point it at the CoAP service ClusterIP?

**Comment by galenguyer** [comment]
Hey, I want to raise this issue again. I've taken over from @WillNilges and am still seeing the issue with traffic dropping using release 1.0.0 of the tb-udp-lb

**Comment by thedevleon** [comment]
Hi, I realize this is a relatively old issue, however, I'm seeing the exact same behavior on a monolithic instance of Thingsboard v3.4.4-1.

In the first minute, RPCs work fine, however, at some point after that, a packet seems to be dropped (nothing arrives at my board), which triggers the timeout and the deregistering of the observer.

```
2023-03-14 14:17:25,427 [CoapServer(main)#1] INFO  o.e.c.c.network.stack.ObserveLayer - notification for token [Token=06AFF92A7EF36E79] timed out. Canceling all relations with source [46.244.106.52:3568]
2023-03-14 14:17:25,427 [CoapServer(main)#1] INFO  o.e.californium.core.CoapResource - remove observe relation between 46.244.106.52:3568#06AFF92A7EF36E79 and resource /api/v1 (Exchange[R430084, complete], size 201)
2023-03-14 14:17:25,430 [CoapServer(main)#1] WARN  o.e.c.c.network.stack.BaseCoapStack - error send response CON-2.02   MID=   -1, Token=06AFF92A7EF36E79, OptionSet={}, <empty data>
org.eclipse.californium.core.network.ExchangeCompleteException: Exchange[R430084, complete] is already complete! CON-2.02   MID=   -1, Token=06AFF92A7EF36E79, OptionSet={}, <empty data>
        at org.eclipse.californium.core.network.Exchange.assertIncomplete(Exchange.java:1314)
        at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerWithMessageId(InMemoryMessageExchangeStore.java:240)
        at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerOutboundResponse(InMemoryMessageExchangeStore.java:411)
        at org.eclipse.californium.core.network.UdpMatcher.sendResponse(UdpMatcher.java:161)
        at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendResponse(CoapEndpoint.java:879)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendResponse(BaseCoapStack.java:239)
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendResponse(ReliabilityLayer.java:150)
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendResponse(BlockwiseLayer.java:688)
        at org.eclipse.californium.core.network.stack.ObserveLayer.sendResponse(ObserveLayer.java:125)
        at org.eclipse.californium.core.network.stack.AbstractLayer.sendResponse(AbstractLayer.java:74)
        at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendResponse(ExchangeCleanupLayer.java:95)
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendResponse(BaseCoapStack.java:197)
        at org.eclipse.californium.core.network.stack.BaseCoapStack.sendResponse(BaseCoapStack.java:113)
        at org.eclipse.californium.core.network.CoapEndpoint$4.run(CoapEndpoint.java:684)
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
        at org.eclipse.californium.core.network.CoapEndpoint$6.run(CoapEndpoint.java:1311)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Is there maybe a way to disable to instant de-registering after a single timeout?

**Comment by thedevleon** [comment]
Quick update from my side, the issue was due to a missing ACK to the RPC CON message from the server, which ultimately caused the timeout.

Still, I wonder what this behavior will mean if a packet from the observation doesn't reach the client (i.e. because a packet has been dropped) - immediately removing the observation seems a bit drastic.

Where could I make an adjustment so that it takes a bigger number of un-acknowledged messages (for example, 5 successive messages) before the observer relation is removed?

**Comment by matiasmelendez** [comment]
> Quick update from my side, the issue was due to a missing ACK to the RPC CON message from the server, which ultimately caused the timeout.
> 
> Still, I wonder what this behavior will mean if a packet from the observation doesn't reach the client (i.e. because a packet has been dropped) - immediately removing the observation seems a bit drastic.
> 
> Where could I make an adjustment so that it takes a bigger number of un-acknowledged messages (for example, 5 successive messages) before the observer relation is removed?
> 
> Edit:
> 
> From further digging, it seems the configuration flags `NOTIFICATION_CHECK_INTERVAL` and `NOTIFICATION_CHECK_INTERVAL_COUNT` from californium might be relevant.
> 
> https://github.com/thingsboard/thingsboard/blob/1be933622db1157f79a2d790e5547984344c7387/common/coap-server/src/main/java/org/thingsboard/server/coapserver/DefaultCoapServerService.java#L97

@thedevleon I am getting crazy with this issue. Do you have any updates? Thanks a lot!

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
