### ISSUE TITLE
[Bug] Rule Node fails randomly with similar input

### ISSUE THREAD

**Issue by mcpicoli** [thingsboard/thingsboard#5270]
Rule chain receives all POST_TELEMETRY messages, and its first node, of type Filter - Switch checks if the telemetry body has one or more keys. Depending on the result, it is forwarded to one of several other nodes that do further processing.

This node is failing randomly a few seconds after it is added to the Rule Chain (after saving of course), even if the data received is the same (similar key, similar value, or even exact same keys, exact same values if you look back a few seconds), and since there is quite a few devices connected (several hundred), it immediately starts failing with "Script invocation is blocked due to maximum error count 3".

Out TB version is PE, latest (3.3.1), self-hosted. 

_Before anyone says "use your paid support", yes, I already contacted them. However, I'd say this bug would affect the CE version as well, since it does not depend on any PE feature._ I have no way to test this assertion.

Please note that the server is busy, but not overloaded. CPU usage hovers around 30%. The database server is also busy and has similar CPU load. We have several hundred devices conected at once (mostly via MQTT), and telemetry message count is "several per second" (via guesstimation).

More details:

The initial error message is:

`TypeError: Cannot read property "substring" from undefined in <eval> at line number 14`

The code contained in the "Filter - Switch" node is:
```javascript
var keys = Object.keys(msg);

if (!Array.isArray(keys))
{
    return ["Outros"];
}

for (k = 0; k < keys.length; k++)
{
    var key = keys[k].toString();
    if (key && key.substring(0, 6) == "pulso_")
    {
        // Is Pulse Counter
        return ["Contador Pulsos"];
    }
}

return ["Outros"];
```

The data that causes the initial error (copied from the "debug" in Events of the Rule Node) is:
```
{
    "po_1": 241
}
```

The previous invocation of the code executes fine with this data:
```
{
    "pa_1": 1626
}
```

This is the full error as reported by the "Error" column of the "Event" tab:

```
java.util.concurrent.ExecutionException: javax.script.ScriptException: TypeError: Cannot read property "substring" from undefined in <eval> at line number 14
	at org.thingsboard.js.api.AbstractNashornJsInvokeService.lambda$doInvokeFunction$1(AbstractNashornJsInvokeService.java:186)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: javax.script.ScriptException: TypeError: Cannot read property "substring" from undefined in <eval> at line number 14
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:399)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:197)
	at delight.nashornsandbox.internal.InvokeOperation.executeScriptEngineOperation(InvokeOperation.java:21)
	at delight.nashornsandbox.internal.JsEvaluator.run(JsEvaluator.java:55)
	... 6 more
Caused by: <eval>:14 TypeError: Cannot read property "substring" from undefined
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Undefined.get(Undefined.java:161)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$2362$448AAA$\^eval\_.invokeInternal_f83447a7_b106_4268_bf13_48ccb7eb8da2#ruleNodeFunc(<eval>:14)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$2366$219AAA$\^eval\_.invokeInternal_f83447a7_b106_4268_bf13_48ccb7eb8da2(<eval>:5)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:661)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
	... 9 more
```

If I use the "Test Filter" button on the Rule Node, the result is the expected (no error), and correct, for both sets of data (and others).

My educated guess is that there is some race condition in the Rule Engine, or some resource/buffer is exhausted, since it takes a random time (around 15-30 seconds, never the same) for the first failure to occur.

Thanks

**Comment by JacksonBowe** [comment]
@mcpicoli What if you try using 
```
if (key && key.indexOf("polso_") > -1) {
    // work
```

The substring method seems to be exculsive to strings, but the indexOf method might get around that. I think it would still not work correctly, but maybe it wont shut down your rule node?

Also, I've just now noticed what the issue probably is. In your for loop you have 
``` for (k = 0; k < keys.length; k++) {}```

This is thingsboard kryptonite. What you should have is
``` for (var k = 0; k < keys.length; k++) {}```

Or 
``` 
Object.keys(msg).forEach(function (key) {
    //work
}
```

The reason is that in your version, you are declaring k=0 at the start of the loop. This isn't a local declaration, you're setting the variable k=0 globally across your whole instance. That means if two messages reach this node at slightly different times and are looping through the process will be like this:

Loop A sets k=0  > does work
Loop A does it's work
Loop B sets k=0
Loop A finishes work and sets k=1
Loop B starts doing work, but instead of using k=0 it's using k=1, but that's not possible
So Loop B gets something like ``` var key = keys[1] // But keys doesn't have an index 1 > returns undefined```

To verify what I'm saying here, add in an empty Tansformation-script node and have the following, nothing else in the node
``` return {msg: {"test":k}, metadata: metadata, msgType: msgType}```

Don't open the node with "Test transformer function" button, just write in the box and save it.

Good luck

**Comment by ashvayka** [comment]
Hi @mcpicoli , I totally agree with @JacksonBowe. Please let us know if adding "var" or "let" will fix the issue.

**Comment by mcpicoli** [comment]
Hi, thanks for the feedback. I tried the following changes, with the following results:

a) Adding ```var``` to declare ```k``` locally *does not solve the problem*. It now reads:

```javascript
var keys = Object.keys(msg);

if (!Array.isArray(keys))
{
    return ["Outros"];
}

for (var k = 0; k < keys.length; k++)
{
    var key = keys[k].toString();
    if (key && key.substring(0, 6) == "pulso_")
    {
        // Trata-se de um contador de pulsos
        return ["Contador Pulsos"];
    }
}

return ["Outros"];
```

Replacing ```substring()``` with ```indexOf()```. it *solves the problem*. The relevant lines now read:

```javascript
for (var k = 0; k < keys.length; k++)
{
    var key = keys[k].toString();
    if (key && key.indexOf("pulso_") == 0)                                      // HAS to be at the first position
    {
        // Is a pulse counter
        return ["Contador Pulsos"];
    }
}
```

Using more elegant code, with ```substring()``` (sure, I'm just _old fashioned_) that now reads as follows *solves the problem*:

```javascript
var flag = false;

Object.keys(msg).forEach(function (key)
{
    if (key && key.substring(0, 6) == "pulso_")
    {
        // Is a pulse counter
        flag = true;
        return;
    }
});

if (flag)
{
    return ["Contador Pulsos"];
}

return ["Outros"];
```

Using the same code above, but with ```indexOf()``` also *solves the problem*.

In the end I cannot conclude what is the root cause of the problem. ```substring()``` misbehaves, but not in the code suggested before. Local declaration of variables seems to not matter.

I still believe that there is something deeper in the way the code is parsed/evaluated that sometimes causes problems and sometimes do not, since even with the original code it takes several seconds for the problem to manifest.

If any of you has further suggestions for investigating the issue, I'll be happy to try them, but _for now_ I'll stick with the more elegant version suggested.

**Comment by mcpicoli** [comment]
I updated the previous comment to ammend the information. Local declaration of variables SOLVE the problem as well as the other suggestions.

**Comment by ashvayka** [comment]
the debug events will automatically cleanup due to ttl if you enable it.
