### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sandaruwanbandara** [thingsboard/thingsboard#5387]
After start thingsboar it authomatically shutdown and I found following issue

2021-10-17 15:19:45,016 [tb-queue-request-template-tb_transport.api.responses.localhost-13-thread-1] WARN  o.t.s.q.c.DefaultTbQueueRequestTemplate - Request timeout detected, currentNs [14700604422375], ResponseMetaData{submitTime=14687757602887, calculatedExpTime=14697757602887, deltaMs=10000000000, expTime=14697757602887, future=com.google.common.util.concurrent.SettableFuture@508b98bc[status=PENDING]}, key [be4bd797-d11f-4473-b64a-e3d476d861b0]
2021-10-17 15:19:45,145 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at org.thingsboard.server.common.transport.service.DefaultTransportService.getSnmpDevicesIds(DefaultTransportService.java:303)
	at org.thingsboard.server.transport.snmp.service.ProtoTransportEntityService.getSnmpDevicesIds(ProtoTransportEntityService.java:89)
	at org.thingsboard.server.transport.snmp.SnmpTransportContext.fetchDevicesAndEstablishSessions(SnmpTransportContext.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:108)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:553)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:534)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:91)
	at org.thingsboard.server.common.transport.service.DefaultTransportService.getSnmpDevicesIds(DefaultTransportService.java:300)
	... 28 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.setTimeoutException(DefaultTbQueueRequestTemplate.java:163)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$tryCleanStaleRequests$0(DefaultTbQueueRequestTemplate.java:132)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.tryCleanStaleRequests(DefaultTbQueueRequestTemplate.java:128)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:117)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

* own setup
  *  local infrastructure
  * ThingsBoard 3.3.1
  * linux ubuntu server 18.04

**Comment by sandaruwanbandara** [comment]
This error was occurred after upgrading form 3.2.2 to 3.3.0.then remove all files and databases install it again now it works well
