### ISSUE TITLE
[Bug] REOPEN #4877 System SMTP Settings: Email Failure.

### ISSUE THREAD

**Issue by Curtis-K** [thingsboard/thingsboard#5446]
**Describe the bug**
System SMTP settings fail with error "Unable to send mail: 535 5.7.3 Authentication unsuccessful" when no authentication is required. When "Use system mail settings" is disabled in a send mail rule, the identical mail server settings are able to send mail successfully.

This is a new development since Thingsboard 3.1.

**Your Server Environment**
Thingsboard CE 3.3.1 (Docker thingsboard-postgres)

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Chrome, Edge
* Version [e.g. 22]

**To Reproduce**
1. Log in as system administrator.
2. Select 'System Settings/Mail Server'
3. Enter settings: SMTP, local SMTP host, Port of local host, no TLS, no proxy, no username, no password.
4. Click 'Send Test Email'
5. Error: Unable to send mail: 535 5.7.3 Authentication unsuccessful.
6. Add Send Mail Rule.
7. Uncheck 'Use system SMTP settings'.
8. Enter identical settings to system SMTP settings.
9. Rule successfully sends email.

**Expected behavior**
Email using System SMTP settings successfully sends email.
**Screenshots**
Configure and Test System Email:
![image](https://user-images.githubusercontent.com/85591539/138993475-4fde1fa6-a00b-43ee-870f-8642513c6732.png)

Configure Send Email Rule with System SMTP Settings:
![image](https://user-images.githubusercontent.com/85591539/138993780-592134ab-1b10-4692-b465-2f1f017cf3a9.png)

Result:
`org.thingsboard.server.common.data.exception.ThingsboardException: Unable to send mail: 535 5.7.3 Authentication unsuccessful

	at org.thingsboard.server.service.mail.DefaultMailService.handleException(DefaultMailService.java:467)
	at org.thingsboard.server.service.mail.DefaultMailService.sendMail(DefaultMailService.java:293)
	at org.thingsboard.server.service.mail.DefaultMailService.send(DefaultMailService.java:255)
	at org.thingsboard.rule.engine.mail.TbSendEmailNode.sendEmail(TbSendEmailNode.java:89)
	at org.thingsboard.rule.engine.mail.TbSendEmailNode.lambda$onMsg$0(TbSendEmailNode.java:77)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

Configure Send Email Rule with identical Settings:
![image](https://user-images.githubusercontent.com/85591539/138993956-e5d64bb0-7b9a-49b2-8b22-84846012d000.png)

Result:
Mail sent successfully.
**Additional context**
As noted above, this is new since Thingsboard 3.1.

**Comment by Curtis-K** [comment]
...bump...
Anyone else experiencing this failure?

**Comment by DanielWi92** [comment]
I realized this bug also in the version 3.3.3.

It is only working for me in the rule chain when I open the settings menue and clear the username and password and save this:

When I open the settings menue after the save operation, the username and password is automatically filled:
![image](https://user-images.githubusercontent.com/89963757/159924590-4278982d-4a8f-4ac4-910f-42299ab2dd18.png)

When I now save again the error from Curtis-K is comming again!

The only possibility to send mails without authentication is:
- send via Rule chain
- open mail settings there
- set email-server and delete username and password
- save this settings and doesn't save it again with the automatically filled username/password

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
