### ISSUE TITLE
[Bug] custom rule node issue

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#5685]
**Describe the bug**
custom rule node can not working.
tb-node log show "java.lang.ClassNotFoundException" 

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard 3.3
  * Ubuntu Server 20.04 LTS
  * 8 Core & 16G Ram

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Win7
* Browser: chrome
* Version [92]

**Your Device**

* Connectivity
  * MQTT

**To Reproduce**
1. build custom rule node
2. copy rule node jar to extensions directory.
sudo cp rule-engine-1.0.0-custom-nodes.jar /usr/share/thingsboard/extensions/
3. change rule node jar owner to thingsboard
sudo chown thingsboard:thingsboard /usr/share/thingsboard/extensions/*
4. restart docker image
5. ClassNotFoundException occur, but the jar in the directory, and ower is correct.
6. this rule node can not run in rule chain page.

**Expected behavior**
custom rule node can run success

**Screenshots**

**Additional context**
Caused by: java.lang.ClassNotFoundException: org.thingsboard.rule.engine.node.action.TbCreateDeviceNode
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:152)
        at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:62)
        at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)

**Comment by xiddjp** [comment]
@ashvayka How can I add a custom rule node into docker image?

**Comment by ashvayka** [comment]
please attach your docker-compose file or your docker run command.

**Comment by Raven888888** [comment]
@xiddjp have you managed to create a usable custom rule node and integrate into docker thingsboard?

**Comment by xiddjp** [comment]
@ashvayka @Raven888888 After i clean the chrome cache, it works now, thanks.
