### ISSUE TITLE
Browser keeps on restarting - latest master (11 Fb 2018)

### ISSUE THREAD

**Issue by azrin1972** [thingsboard/thingsboard#580]
Hi my previous TB works fine for months. Today I compiled the latest master and I my browser keeps on reloading. here is my log.

```
2018-02-11 23:37:54.901 ERROR 1208 --- [t-dispatcher-25] akka.actor.OneForOneStrategy             : messageId: -1 (expected: 1 ~ 65535)

java.lang.IllegalArgumentException: messageId: -1 (expected: 1 ~ 65535)
	at io.netty.handler.codec.mqtt.MqttMessageIdVariableHeader.from(MqttMessageIdVariableHeader.java:31) ~[netty-all-4.1.3.Final.jar!/:4.1.3.Final]
	at org.thingsboard.server.transport.mqtt.MqttTransportHandler.createMqttPubAckMsg(MqttTransportHandler.java:377) ~[mqtt-1.4.0-SNAPSHOT.jar!/:na]
	at org.thingsboard.server.transport.mqtt.session.GatewayDeviceSessionCtx.getToDeviceMsg(GatewayDeviceSessionCtx.java:90) ~[mqtt-1.4.0-SNAPSHOT.jar!/:na]
	at org.thingsboard.server.transport.mqtt.session.GatewayDeviceSessionCtx.onMsg(GatewayDeviceSessionCtx.java:77) ~[mqtt-1.4.0-SNAPSHOT.jar!/:na]
	at org.thingsboard.server.actors.session.ASyncMsgProcessor.processToDeviceMsg(ASyncMsgProcessor.java:102) ~[classes!/:1.4.0-SNAPSHOT]
	at org.thingsboard.server.actors.session.SessionActor.processToDeviceMsg(SessionActor.java:91) ~[classes!/:1.4.0-SNAPSHOT]
	at org.thingsboard.server.actors.session.SessionActor.onReceive(SessionActor.java:69) ~[classes!/:1.4.0-SNAPSHOT]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) ~[akka-actor_2.11-2.4.2.jar!/:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.2.jar!/:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) ~[akka-actor_2.11-2.4.2.jar!/:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.2.jar!/:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.2.jar!/:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.2.jar!/:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.2.jar!/:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.2.jar!/:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar!/:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar!/:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar!/:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar!/:na]

2018-02-11 23:37:54.902 ERROR 1208 --- [t-dispatcher-25] akka.actor.OneForOneStrategy             : null

java.lang.NullPointerException: null


```

**Comment by vparomskiy** [comment]
Do you still have same problem on latest master?

**Comment by azrin1972** [comment]
I’ve compile the 7 March release still having it in Safari but not under Chrome 

Was trying to upgrade to 1.4.1 but the database structure has changed and there no upgrade module form 1.4.0 to 1.4.1 yet. 

But I saw there is already 1.4.0 to 1.5.0

**Comment by Karabiy** [comment]
those seems to be fixed for the ThingsBoard latest version.
