### ISSUE TITLE
[Question] How can I load a resource as a module and use @NgModule without 'decorators-legacy' related error messages?

### ISSUE THREAD

**Issue by technorabilia** [thingsboard/thingsboard#5838]
**Component**
 * UI (custom widget development)

**Description**
For a widget I'm trying to load an Angular module. For this I have checked "Is module" when adding the resource.

I get the following error message when trying to load the module:
```
main.4eb0765d2ad316efc805.js:1 Unable to load module from url: http://localhost:8888/ang.ts SyntaxError: /http:/localhost:8888/ang.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (1:1):

> 1 | @NgModule({
    | ^
  2 | })
  3 | 
    at De._raise (scripts.62812db253892871a94b.js:7:170590)
    at De.raiseWithData (scripts.62812db253892871a94b.js:7:170529)
    at De.expectOnePlugin (scripts.62812db253892871a94b.js:7:190314)
    at De.parseDecorator (scripts.62812db253892871a94b.js:7:233422)
    at De.parseDecorators (scripts.62812db253892871a94b.js:7:233079)
    at De.parseStatement (scripts.62812db253892871a94b.js:7:230252)
    at De.parseBlockOrModuleBlockBody (scripts.62812db253892871a94b.js:7:240501)
    at De.parseBlockBody (scripts.62812db253892871a94b.js:7:240259)
    at De.parseTopLevel (scripts.62812db253892871a94b.js:7:228957)
    at De.parse (scripts.62812db253892871a94b.js:7:260516)
```
The module I am trying to load is very basic:
```
@NgModule({
})
```
When I look at [ui-ngx/ts.config](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/tsconfig.json#L11) I see that ```experimentalDecorators``` is set to ```true```.

How come I still het the "Support for the experimental syntax 'decorators-legacy' isn't currently enabled" error message? How can I make this work?

**Environment**

 * OS:  Docker 20.10.12 on Ubuntu 20.04
 * ThingsBoard: CE v3.3.3-SNAPSHOT
 * Browser: Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by Nathan-ma** [comment]
Great Question. Subscribing to this. I'm also trying to create my own component and add it to a widget.

if anyone knows how to do this, please give me some instructions! thank you!

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.

**Comment by zelms** [comment]
For anyone hoping to create their own component, check out the related [thingsboard-extensions](https://github.com/thingsboard/thingsboard-extensions/tree/release-3.8).
