### ISSUE TITLE
[Bug] Custom integration - remote-integration-example is out of date or unusable in PE 3.3.2.

### ISSUE THREAD

**Issue by soyoeml** [thingsboard/thingsboard#5964]
**Component**

 *  [remote-integration-example](https://github.com/thingsboard/remote-integration-example)
 *  custom integration

**Environment**

 * OS:  Ubuntu 20.04 focal
 * ThingsBoard: thingsboard-3.3.2pe
 * Browser: Firefox 95.0 64bit
 
**Description**
The project remote-integration-example is out of date and has runtime exception. I compiled this project and configured it properly. But I got rumtime exception: java.lang.ClassNotFoundException: org.thingsboard.server.coapserver.CoapServerService. I found there is no coap-server-3.3.2PE.jar indeed. Please fix it.

**Steps to reproduce**

  * Git clone remote-integration-example project and use master branch;
  * mvn spring-boot:run
     You’ll see this runtime error. You can also use mvn clean package and dpkg install and service start it. 

**Exception log**

`2022-01-24 21:29:26,883 [main] INFO  o.t.i.ThingsboardRemoteIntegrationApplication - Starting ThingsboardRemoteIntegrationApplication v2.0.0 on ip-172-31-18-220 with PID 345726 (/usr/share/tb-remote-integration-example/bin/tb-remote-integration-example.jar started by thingsboard in /usr/share/tb-remote-integration-example/bin)
2022-01-24 21:29:26,890 [main] INFO  o.t.i.ThingsboardRemoteIntegrationApplication - No active profile set, falling back to default profiles: default
2022-01-24 21:29:27,094 [background-preinit] WARN  o.s.h.c.j.Jackson2ObjectMapperBuilder - For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2022-01-24 21:29:28,598 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2022-01-24 21:29:28,605 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2022-01-24 21:29:28,676 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 42 ms. Found 0 Redis repository interfaces.
2022-01-24 21:29:29,347 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 16000 (http)
2022-01-24 21:29:29,364 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-0.0.0.0-16000"]
2022-01-24 21:29:29,366 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2022-01-24 21:29:29,367 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.46]
2022-01-24 21:29:29,480 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2022-01-24 21:29:29,480 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 2457 ms
2022-01-24 21:29:29,838 [main] INFO  o.t.s.c.adaptor.JsonConverterConfig - JSON max string value length = 0
2022-01-24 21:29:29,841 [main] INFO  o.t.s.c.adaptor.JsonConverterConfig - JSON type cast enabled = true
2022-01-24 21:29:29,866 [main] INFO  o.t.i.storage.EventStorageReader - Initializing from state file: [/usr/share/tb-remote-integration-example/bin/./data_1643058363782.txt:0]
2022-01-24 21:29:29,883 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RemoteIntegrationManagerService': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.thingsboard.integration.service.RemoteIntegrationManagerService] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5a2e4553]
2022-01-24 21:29:29,888 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2022-01-24 21:29:29,911 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-01-24 21:29:29,938 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'RemoteIntegrationManagerService': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.thingsboard.integration.service.RemoteIntegrationManagerService] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5a2e4553]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:289)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1290)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1205)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at org.thingsboard.integration.ThingsboardRemoteIntegrationApplication.main(ThingsboardRemoteIntegrationApplication.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.thingsboard.integration.service.RemoteIntegrationManagerService] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@5a2e4553]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267)
	... 27 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/thingsboard/server/coapserver/CoapServerService
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
	... 29 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.thingsboard.server.coapserver.CoapServerService
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 33 common frames omitted`

**Comment by soyoeml** [comment]
In class [org.thingsboard.integration.service.RemoteIntegrationManagerService], there is a CoapServerService declaration with @Autowired(required = false), but excluding coap-sever package artifacts. The problem is here. Please fix it.

**Comment by ashvayka** [comment]
@ShvaykaD please fix this.

**Comment by soyoeml** [comment]
Hi @ShvaykaD,

Steps to reproduce:
1. Git clone remote-integration-example project and use master branch;
2. mvn spring-boot:run
You’ll see this runtime error. Thanks

**Comment by ShvaykaD** [comment]
Hi @soyoeml,

I have added a temporary fix to the master branch to exclude the CoapServerService.class and CoapServerContext.class using @ComponentScan.Filter annotation.

In addition, I have updated the project to use the latest version of ThingsBoard - 3.3.3PE

Could you please verify the update? Thanks!

**Comment by soyoeml** [comment]
Hi @ShvaykaD,

I verified and confirm that's fixed in this [commit](https://github.com/thingsboard/remote-integration-example/commit/27f6000eac7c49b9d1b4935f73ca728b86afca47) . Thank you!
