### ISSUE TITLE
OTA image assigned to device profile does not populate device shared properties

### ISSUE THREAD

**Issue by flagline** [thingsboard/thingsboard#6008]
First off, I'm completely new to thingsboard, so forgive me if I'm missing something obvious.

I have ARM-based devices running busy-box linux to which I'm trying to deliver OTA software updates.  I have gotten it to work by assigning a software OTA update to the device profile and then assigning that profile to the devices that I want to update.   This results in the device shared attributes being populated with the OTA properties: sw_title, sw_version, sw_size, and sw_checksum.  Once my device has that, it can successfully download and install the OTA update if it is different from what is already installed.

However, when I then assign a new OTA package to the device profile, the OTA properties are not propagated to the devices assigned to that profile.  Instead, the device shared attributes are just deleted.  I can work around this by going into each device and assigning the "default" device profile and then reassigning my device profile with the OTA package, but that defeats the point of the device profile.

We're running thingsboard 3.3.3 on a virtual linux server. 

I'm wondering if anyone has seen this behavior before and found a workaround or fix.

**Comment by flagline** [comment]
The problem is confined to the "assigned software" slot.   When I modified my firmware to use the "assigned firmware" slot for OTA updates, everything works as expected.   Now when I assign a new OTA update package to the device profile's "assigned firmware", all devices assigned to that profile have their shared attributes updated to match the new OTA package.

**Comment by marcocastellani** [comment]
Any news on this topic?
Still there with 3.4.1 version

**Comment by peterchen5** [comment]
The same issue occurred on 3.3.4. Not sure if it is a configuration/setting up issue or bug.

**Comment by ashvayka** [comment]
The fix will be released in v3.4.2

**Comment by marcocastellani** [comment]
Hello, 
I've just tested v3.4.4 and now seems that both firmware and software stopped working.
**What I did:**
- create a new instance of TB 3.4.4 CE using docker compose in documentation, with only one client
- create a tenant
- create a device profile
- create a device and assign it to the profile
- assigned firmware and software to the device (I also try assigning fw and sw to profile above)

**Expected:**
device shared attribute is populated with fw_title and sw_title shared attribute taken from assigned OTA version
also
in device telemetry  a value fw_state = INITIATED

**Results**
no fw_* attribute is populated in device
in device telemetry  we found a value fw_state = QUEUED that, according to documentation means that the update not yet delivered to device

Additional info,
inside tb log we found
`
2023-03-28 08:45:51,235 [tb-core-usage-stats-consumer-52-thread-1] ERROR o.t.server.dao.service.DataValidator - ApiUsageState object is invalid: [ApiUsageState is referencing to non-existent tenant!]
2023-03-28 08:45:51,235 [tb-core-usage-stats-consumer-52-thread-1] WARN  o.t.s.s.q.DefaultTbCoreConsumerService - [23f3bf98-b9e6-4052-8a36-9652e390ccbd] Failed to process usage stats: TbProtoQueueMsg(key=1f938c4d-91b9-492a-bd26-0f3c0133ac5b, value=tenantIdMSB: 652947044566766061
tenantIdLSB: -6523233674833915927
values {
  key: "RE_EXEC_COUNT"
  value: 2
}
, headers=org.thingsboard.server.queue.common.DefaultTbQueueMsgHeaders@18c5b8a1)
java.lang.NullPointerException: null
	at org.thingsboard.server.service.apiusage.TenantApiUsageState.<init>(TenantApiUsageState.java:46)
	at org.thingsboard.server.service.apiusage.DefaultTbApiUsageStateService.getOrFetchState(DefaultTbApiUsageStateService.java:453)
	at org.thingsboard.server.service.apiusage.DefaultTbApiUsageStateService.processEntityUsageStats(DefaultTbApiUsageStateService.java:195)
	at org.thingsboard.server.service.apiusage.DefaultTbApiUsageStateService.process(DefaultTbApiUsageStateService.java:182)
	at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.handleUsageStats(DefaultTbCoreConsumerService.java:433)
	at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.lambda$launchUsageStatsConsumer$8(DefaultTbCoreConsumerService.java:361)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.lambda$launchUsageStatsConsumer$11(DefaultTbCoreConsumerService.java:357)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

Any suggestion?

**Comment by BelegCuthalion** [comment]
I have the same problem.
The devices' fw_ attributes do not change after assigning new firmware to their profile. While the [docs](https://thingsboard.io/docs/user-guide/ota-updates) clearly say that the expected behavior is otherwise:

> For example, let’s assume you have Devices D1 and D2 that has Profile P1:
> If you assign package F1 to Profile P1 [...] Devices D1 and D2 will be updated to F1.

Can anyone confirms if this is a known bug? And if it is going to be fixed?

**Comment by FelixKikleo** [comment]
Since upgrading 3.5.1 to 3.7, we have the same issue. Devices shared attributes don't update when changing the assigned OTA (framework or software) in the Profile. But if change the profile of the device, changes are made accordingly in the device shared attributes. 
Anyone working on this ? We have many devices, doing this manually for each device would be too time consuming

**Comment by mykhailokornieiev** [comment]
Hi. This bug should have been fixed in the v3.8 release. I close this ticket due to inactivity. Feel free to create a new ticket with full steps to reproduce in case it is still relevant on the latest releases
