### ISSUE TITLE
[Bug] [3.4] FindAllTenants uses hard-coded Global region.

### ISSUE THREAD

**Issue by ashvayka** [thingsboard/thingsboard#6057]
**Describe the bug**
See stack trace:
tb-core1_1            | 	at org.thingsboard.server.dao.sql.tenant.JpaTenantDao.findTenantsByRegion(JpaTenantDao.java:63)
tb-core1_1            | 	at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$FastClassBySpringCGLIB$$bb4581c1.invoke(<generated>)
tb-core1_1            | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
tb-core1_1            | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
tb-core1_1            | 	at org.thingsboard.server.dao.sql.tenant.JpaTenantDao$$EnhancerBySpringCGLIB$$217df218.findTenantsByRegion(<generated>)
tb-core1_1            | 	at org.thingsboard.server.dao.tenant.TenantServiceImpl.findTenants(TenantServiceImpl.java:171)

The findTenantsByRegion is redundant. Please correct the implementation of TenantServiceImpl.findTenants

**Comment by mykhailokornieiev** [comment]
The respective ticket was added to the backlog for developers
