### ISSUE TITLE
Gateway Error

### ISSUE THREAD

**Issue by arunnediyasala** [thingsboard/thingsboard#611]
@mp-loki  
I am getting the following error from the gateway log. It was running perfectly before suddenly I got this error . Please help me to understand this  ,I have seen that Now in my gate way telemetry field I am getting 2 days old data

```
2018-02-26 10:33:28,215 [MQTT Rec: 3AF5Cd4DsI/IG3T4MKkr8bjhH3uuWHrNiKSob56HcBc=] WARN  o.t.g.service.MqttGatewayService - [FF63DB76][2] Failed to report device connection!
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)

```

**Comment by arunnediyasala** [comment]
@mp-loki 
I found solution from https://github.com/thingsboard/thingsboard-gateway/issues/16 figued the storage folder under /usr/share/tb-gateway/bin/storage/ on Ubuntu 16.04

Delete the folder having alpha-numeric name(auto generated) inside storage folder by sudo rm -r <folder_name>
Restart the thingsboard gateway service by sudo service tb-gateway restart.
The attribute and telemetry upload will start.
