### ISSUE TITLE
[Bug] HTTP Integration not working with PEM SSL config - javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#6228]
**Describe the bug**
We configured SSL using PEM via documentation guide:
https://thingsboard.io/docs/pe/user-guide/ssl/http-over-ssl/

This works fine and the web front-end is available with https. When trying to send data from rulechain to HTTP integration an error occurs due to SSL problems.
Is there anything missing which needs to be added to the config?

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version 3.3.3
  * Ubuntu

* Connectivity
  * Integration: (HTTP) 

**To Reproduce**
1. Apply Config for SSL https://thingsboard.io/docs/pe/user-guide/ssl/http-over-ssl/
2. Create a new HTTP Integration and Copy the URL
3. Create a rulechain with generator node
4. Add rest api call node using the Integration URL
5. Inspect Debug logs of rest api call node

**Expected behavior**
Request to the HTTP Integration should be successful without any SSL issues.

**Additional context**
Error Message printed in debug logs:

_io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1883)
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:806)
                at java.base/javax.net.ssl.SSLEngine.wrap(SSLEngine.java:522)
                at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1041)
                at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:927)
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1409)
                at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
                at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
                ... 17 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
                at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
                at java.base/sun.security.validator.Validator.validate(Validator.java:264)
                at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
                at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
                at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
                at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:234)
                at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:740)
                at io.netty.internal.tcnative.CertificateVerifierTask.runTask(CertificateVerifierTask.java:36)
                at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:48)
                at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:42)
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine$TaskDecorator.run(ReferenceCountedOpenSslEngine.java:1446)
                at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1549)
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1395)
                ... 21 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
                at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
                at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
                at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
                ... 34 more_

**Comment by mde2017** [comment]
Any update on this?

**Comment by torres-sonia** [comment]
Possibly related to https://github.com/thingsboard/thingsboard/issues/1499

**Comment by Ultrazombie** [comment]
Closed due to inactivity
