### ISSUE TITLE
[Bug] TB 3.3.4 not starting after fresh Windows install (on-premises community)

### ISSUE THREAD

**Issue by gr-hayduk** [thingsboard/thingsboard#6250]
I've installed Thingsboard according to https://thingsboard.io/docs/user-guide/install/windows/
Up to point 6 (Run installation script) everything went OK. I have tables filled with data in PostgreSQL db.
But then the Thingsboard service doesn't start, it terminates with an error 1067: Process exited unexpectedly. 
I have looked into log files in the C:/Program Files (x86)/Thingsboard/logs folder:

thingsboard.err:
```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: -Xlog:gc*,heap*,age*,safepoint=debug:file=C:\Program Files (x86)\thingsboard\logs\gc.log:time,uptime,level,tags:filecount=10,filesize=10M
```

thingsboard.wrapper.log:
```
2022-03-14 10:13:27,872 INFO  - Starting ServiceWrapper in the service mode
2022-03-14 10:13:27,903 INFO  - Starting java  -Dplatform=windows "-Dinstall.data_dir=C:\Program Files (x86)\thingsboard\data" "-Xlog:gc*,heap*,age*,safepoint=debug:file=C:\Program Files (x86)\thingsboard\logs\gc.log:time,uptime,level,tags:filecount=10,filesize=10M" -XX:+HeapDumpOnOutOfMemoryError -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10 -Xms256m -Xmx256m -jar "C:\Program Files (x86)\thingsboard\lib\thingsboard.jar" 
2022-03-14 10:13:27,903 INFO  - Starting java  -Dplatform=windows "-Dinstall.data_dir=C:\Program Files (x86)\thingsboard\data" "-Xlog:gc*,heap*,age*,safepoint=debug:file=C:\Program Files (x86)\thingsboard\logs\gc.log:time,uptime,level,tags:filecount=10,filesize=10M" -XX:+HeapDumpOnOutOfMemoryError -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10 -Xms256m -Xmx256m -jar "C:\Program Files (x86)\thingsboard\lib\thingsboard.jar" 
2022-03-14 10:13:28,153 INFO  - Started 5976
```

So I tried so start the java commandline (java -Dplatform=windows -Dinstall.data_dir-...) from admin-elevated command prompt with "C:\Program Files (x86)\thingsboard" as working directory, but then I get:
```
C:\Program Files (x86)\thingsboard>java  -Dplatform=windows "-Dinstall.data_dir=C:\Program Files (x86)\thingsboard\data" "-Xlog:gc*,heap*,age*,safepoint=debug:file=C:\Program Files (x86)\thingsboar
09:59:37.737 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/C:/Program%20Files%20(x86)/thingsboard...
(cut)
09:59:37.753 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to load property source from 'file:./thingsboard.xml' (file:./thingsboard.xml)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:564)
(cut)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.util.InvalidPropertiesFormatException: jdk.internal.org.xml.sax.SAXParseException; An XML properties document must contain the DOCTYPE declaration as defined by java.util.Properties
.
        at java.base/jdk.internal.util.xml.PropertiesDefaultHandler.load(PropertiesDefaultHandler.java:85)
(cut)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:534)
        ... 33 common frames omitted
Caused by: jdk.internal.org.xml.sax.SAXParseException: An XML properties document must contain the DOCTYPE declaration as defined by java.util.Properties.
        at java.base/jdk.internal.util.xml.PropertiesDefaultHandler.startElement(PropertiesDefaultHandler.java:162)
(cut)
        at java.base/jdk.internal.util.xml.PropertiesDefaultHandler.load(PropertiesDefaultHandler.java:83)
        ... 40 common frames omitted
```

Is there anything I can do to start the Thingsboard on Windows? Even without using service method (just start it from commandline)?

I'm running latest LTS Java:
OpenJDK11U-jdk_x64_windows_hotspot_11.0.14.1_1.msi
I don't have any other Java VM, above JDK is in the PATH, the CLASSPATH ENV has postgresql-4.23.jar added:
```
CLASSPATH=.;C:\Program Files\OpenJDK-11.0.14.101-hotspot\jre\lib\ext\postgresql-42.3.3.jar
JAVA_HOME=C:\Program Files\OpenJDK-11.0.14.101-hotspot\
Path=C:\Program Files\OpenJDK-11.0.14.101-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System
32\WindowsPowerShell\v1.0\;...
```
and downloaded Thingsboard release:
thingsboard-windows-3.3.4.zip

My OS is Windows Server 2016.

**To Reproduce**
1. Go to https://thingsboard.io/docs/user-guide/install/windows/
2. Proceed with the description, install Thingsboard (steps 1 to 6), install service with install.bat -loadDemo
3. Run Thingsboard service (step 7)
4. See the error that the service cannot start, check thingsboard.log file

**Expected behavior**
Thingsboard running.

**Comment by topwebguru** [comment]
Same issue happened to me also, thanks for providing details, @gr-hayduk , my case is correctly same to you, but my OS is Windows 10 Pro 1903

**Comment by topwebguru** [comment]
On my case, there was process which is running on 7070 port, after I killed that process, thingsboard service started successfully

**Comment by wenjinchao** [comment]
I'm experiencing the same issue, any solutions?
And I imported codes to eclipse,  is there any way to run thingsboard from eclipse or from cmd line?
Thanks a lot!

**Comment by ZhouJianzj** [comment]
How to solve this problem

thingsboard.err:
````
Unrecognized option: -Xlog:gc*,heap*,age*,safepoint=debug:file=E:\workspace\thingsboard\thingsboard\logs\gc.log:time,uptime,level,tags:filecount=10,filesize=10M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: -Xlog:gc*,heap*,age*,safepoint=debug:file=E:\workspace\thingsboard\thingsboard\logs\gc.log:time,uptime,level,tags:filecount=10,filesize=10M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/PropertiesLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:641)
```
