### ISSUE TITLE
[Question] data converter fails to insert new data for multiple devices 

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#6281]
Hi

we are using batch syntax to insert multiple device data points in one return

problem is, if one of the devices in the batch payload does not exist in the system, and integration is set NOT to allow creation of new devices and assets

the whole payload fails and no new data is inserted

example payload, assume the first device does not exist in the platform, and the other 2 do exist. This will result in error and no data will be inserted by the data converter.

any workaround for this?

```
[{
    "deviceName": "249F895384C0",
    "deviceType": "DefaultSensor",
    "groupName": "Refrigerations",
    "attributes": {
        "integrationName": "Refrigerations-DefaultSensor",
        "gatewayId": "A8032AF8D008",
        "active": true,
        "excessiveMsg": 1
    },
    "telemetry": [{
        "ts": 1647524001268,
        "values": {
            "battery": 3.01,
            "temperature": 19.87,
            "rssi": -81
        }
    }]
}, {
    "deviceName": "D02EABBD91B7",
    "deviceType": "DefaultSensor",
    "groupName": "Refrigerations",
    "attributes": {
        "integrationName": "Refrigerations-DefaultSensor",
        "gatewayId": "A8032AF8D008",
        "active": true,
        "excessiveMsg": 1
    },
    "telemetry": [{
        "ts": 1647524006569,
        "values": {
            "battery": 3,
            "temperature": 19.37,
            "temperature-int": 19.23,
            "rssi": -81
        }
    }]
}, {
    "deviceName": "D02EABBD93CB",
    "deviceType": "DefaultSensor",
    "groupName": "Refrigerations",
    "attributes": {
        "integrationName": "Refrigerations-DefaultSensor",
        "gatewayId": "A8032AF8D008",
        "active": true,
        "excessiveMsg": 1
    },
    "telemetry": [{
        "ts": 1647524011309,
        "values": {
            "battery": 3.09,
            "temperature": 19.81,
            "temperature-int": 19.93,
            "rssi": -76
        }
    }]
}]
```

**Comment by t0mZ4** [comment]
```
2022-03-17 19:57:39,883 [nioEventLoopGroup-4-3] WARN  o.t.i.api.util.ExceptionUtil - [005b3b20-a213-11ec-9df9-93fb802473db] Unknown error during message processing
org.thingsboard.server.exception.ThingsboardRuntimeException: Creating devices is forbidden!
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.processGetOrCreateDevice(DefaultPlatformIntegrationService.java:714)
	at org.thingsboard.server.service.integration.DefaultPlatformIntegrationService.getOrCreateDevice(DefaultPlatformIntegrationService.java:638)
	at jdk.internal.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy281.getOrCreateDevice(Unknown Source)

```

**Comment by JacksonBowe** [comment]
There's probably no way you can get around this cleanly. If you only want to allow certain devices then you need to put a lookup table in the decoder and filter out devices that aren't in the lookup. But it's not scalable.

**Comment by t0mZ4** [comment]
@JacksonBowe I know I was thinking the same thing and really am trying to avoid that lookup table i'll have to manually handle.

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
