### ISSUE TITLE
Error when installing Thingsboard CE on Ubuntu OS

### ISSUE THREAD

**Issue by nhp14** [thingsboard/thingsboard#6292]
Hi everyone!
I'm installing Thingsboard CE following the installation guides for ubuntu os. When i executed this command: "sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo"
and this error appeared: "rg.postgresql.util.PSQLException: ERROR: constraint "fk_device_profile_ota_package" for relation "ota_package" already exists".

Here is my full log report:

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: ERROR: constraint "fk_device_profile_ota_package" for relation "ota_package" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.executeQueryFromFile(SqlAbstractDatabaseSchemaService.java:82)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:63)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:239)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

Anybody please help me! Thank you all!

**Comment by mde2017** [comment]
Hi @nhp14,

is this a clean installation? Or did you use previous tb versions?

If it's a fresh installation, try to delete the thingsboard database in postgres and create it again afterwards. Then start the installation script.

**Comment by nhp14** [comment]
Hi @mde2017,

I did a clean installation and came into this error. I'll try your advice to see whether it works or not. Thank you!

**Comment by gonzalomartinezg** [comment]
Did you solve it? I have the same error.

**Comment by watson8544** [comment]
@nhp14 @gonzalomartinezg  I meet this issue too. But after I delect database "postgres" and create, this bug was fixed

**Comment by enesekin** [comment]
Hi @gonzalomartinezg,
I did installation by following the thingsboard documentation and I had created a database before. I deleted the database that was I created earlier and the problem solved

**Comment by KhanhTea** [comment]
Drop database thingsboard in your postgres and reinstall

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
