### ISSUE TITLE
[Bug] Alarm is duplicated when any device attribute is deleted

### ISSUE THREAD

**Issue by nowherex** [thingsboard/thingsboard#6393]
I ended up discovering a "serious" bug by chance.
Whenever a device attribute is deleted, the last alarm generated by the device (cleared alarm) is generated again.

Tested it on a clean tenant account, to ensure that no rule chain changes were interfering with this bug, I also tested it on a clean account at demo.thingsboard.io, so it's an active bug for PE and CE.

In my tests, an alarm generated on September 20, 2021 was created again when deleting a device attribute.

**Your Server Environment**
* demo.thingsboard.io and Self-managed PE version
* own setup
  * ThingsBoard Version CE 3.3.4 (demo.thingsboard.io) and ThingsBoard PE 3.3.4.1
  * OS Ubuntu

**To Reproduce**
1. Create a device and generate an alarm using Alarm Rules in the device profile.
or get any device with an alarm generated and cleared (If it is an alarm generated for this purpose, remember to clear it).
2. Add any attribute to the device.
3. Delete the attribute.
4. See previously created alarm being duplicated.

**Expected behavior**

**Comment by nowherex** [comment]
Trying to create a temporary solution, I found another bug related to the alarms api, when a non-cleared and active alarm (ACTIVE_UNACK) is deleted through the API (route: DELETE /api/alarm/{alarmId}), new alarms are not generated, even if the telemetry meets the rules in the device profile or rule chain.

Looking at the Debug events in the Device Profile node of the root rules chain, after deleting an active and not cleared alarm and trying to repeat the "To Reproduce", an event with error is generated for the message type "ATTRIBUTES_DELETED".

Error (Failure) : 
```
java.lang.NullPointerException at org.thingsboard.server.service.telemetry.DefaultAlarmSubscriptionService.createOrUpdateAlarm(DefaultAlarmSubscriptionService.java:111)
	at org.thingsboard.rule.engine.profile.AlarmState.calculateAlarmResult(AlarmState.java:264)
	at org.thingsboard.rule.engine.profile.AlarmState.createOrClearAlarms(AlarmState.java:129)
	at org.thingsboard.rule.engine.profile.AlarmState.process(AlarmState.java:95)
	at org.thingsboard.rule.engine.profile.DeviceState.processAttributesDeleteNotification(DeviceState.java:241)
	at org.thingsboard.rule.engine.profile.DeviceState.process(DeviceState.java:163)
	at org.thingsboard.rule.engine.profile.TbDeviceProfileNode.onMsg(TbDeviceProfileNode.java:150)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:150)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:117)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:76)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:60)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

It might give you a good idea of the bug reported above.

**Comment by nowherex** [comment]
Hello thingsboard team, I found another bug related to alarms, when I delete an alarm using the api (route: DELETE /api/alarm/{alarmId}) the audit logs query (UI /auditLogs) crashes because of the related logs to these deleted alarms, the 

Following error is displayed in console log repeatedly (causes browser to crash):

```
vendor.335f194322e137716b38.js:1 ERROR Error: Parameter "key" required
    at Ie.instant (vendor.335f194322e137716b38.js:1:1909464)
    at q.cellContentFunction (3928.52a000229c47393013b3.js:1:607114)
    at Vt.cellContent (3928.52a000229c47393013b3.js:1:919746)
    at wt (3928.52a000229c47393013b3.js:1:900773)
    at Fh (vendor.335f194322e137716b38.js:1:295674)
    at Rc (vendor.335f194322e137716b38.js:1:294279)
    at vendor.335f194322e137716b38.js:1:294712
    at Rc (vendor.335f194322e137716b38.js:1:294737)
    at or (vendor.335f194322e137716b38.js:1:301775)
    at vendor.335f194322e137716b38.js:1:295153
```

the logs are not displayed on the screen (UI):

![](https://uploaddeimagens.com.br/images/003/829/515/full/auditLog.png?1649945326)
