### ISSUE TITLE
MQTT Connect issue

### ISSUE THREAD

**Issue by esculca** [thingsboard/thingsboard#640]
I've just installed TB 1.4.0
I noticed now that, when ading a new device, we need to populate "Name" and "Device Type"
I am using a device based around an arduino + esp8266 and the authentication method was based on the access token, I am sending a dummy "Device Id". Not sure what that "Name" and "Device Type" are for.
For some reason I am not able to connect for more than a few seconds and then I get:

2018-03-09 13:15:45,550 [nioEventLoopGroup-5-2] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt1106] Processing connect msg for client: nuno!
2018-03-09 13:16:22,530 [nioEventLoopGroup-5-3] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt1107] Processing connect msg for client: nuno!
2018-03-09 13:16:59,513 [nioEventLoopGroup-5-4] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt1108] Processing connect msg for client: nuno!
2018-03-09 13:17:36,492 [nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt1109] Processing connect msg for client: nuno!
2018-03-09 13:18:04,907 [nioEventLoopGroup-5-10] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt754] Unexpected Exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
2018-03-09 13:18:41,883 [nioEventLoopGroup-5-7] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt1063] Unexpected Exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

Please advise

**Comment by DIYGuy01** [comment]
Having the same, due to some code nuances started getting Java exception from devices. The first my guess was die to use of PlatformIO. But tired to compile/upload using ArduinoIDE started getting the same. 

> 2018-03-19 20:45:38,323 [nioEventLoopGroup-5-12] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt6840] Unexpected Exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by DIYGuy01** [comment]
**I think i found the problem, reproduced multiple times**.
I work with ESP8266 different boards- ESP-01, Wemos D1 mini, NodeMCU...
If I use in my sketch ESP.deepSleep() function, Mosquitto is crashing but if I replace the function with ordinary delay() then all is ok.
@esculca could you check, might be similar to my finding?

**Comment by Ultrazombie** [comment]
Hello @esculca,
Is your problem still relevant on the latest ThingsBoard version?
