### ISSUE TITLE
[Bug] copy attributes to view node nullPointerExeption

### ISSUE THREAD

**Issue by NicoWii4** [thingsboard/thingsboard#6421]
**Describe the bug**
Hello,
I am trying to duplicate my devices attributes to my entities views with the methodology described here : [https://thingsboard.io/docs/user-guide/entity-views/](https://thingsboard.io/docs/user-guide/entity-views). Unfortunately, I have the same problem described in an old issue : [https://github.com/thingsboard/thingsboard/issues/3050](https://github.com/thingsboard/thingsboard/issues/3050). I use the "copy attributes to view" node after a "Message Type Switch" node (see screenshot 1) and I have the following error: 
```js
java.lang.NullPointerException
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.attributeContainsInEntityView(TbCopyAttributesToEntityViewNode.java:160)
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.lambda$onMsg$0(TbCopyAttributesToEntityViewNode.java:110)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.lambda$onMsg$2(TbCopyAttributesToEntityViewNode.java:110)
	at org.thingsboard.common.util.DonAsynchron$1.onSuccess(DonAsynchron.java:55)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1080)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:47)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1047)
	at org.thingsboard.common.util.DonAsynchron.withCallback(DonAsynchron.java:69)
	at org.thingsboard.common.util.DonAsynchron.withCallback(DonAsynchron.java:46)
	at org.thingsboard.rule.engine.action.TbCopyAttributesToEntityViewNode.onMsg(TbCopyAttributesToEntityViewNode.java:99)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:150)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:117)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:76)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:60)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Your Server Environment**

* own setup
  * Cloud docker deployment with official Thingsboard PE images
  * ThingsBoard Version 3.3.3PE
  * Docker host is debian buster, Docker version 20.10.12

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Ubuntu 20.04 / Windows 10
* Chrome / Firefox 97.0

**Expected behavior**
I hope I have no errors and that the copy of my attributes is successful.

**Screenshots**
Screenshot 1 :
![screenshot 1](https://user-images.githubusercontent.com/80882254/163553185-ca8ed10d-09f9-4998-bfc5-4446a19ea597.png)

Best regards.

**Comment by yang-zhou** [comment]
i find this bug too. it happens when i created an EntityView with no cs/sc/sh.
so i fllowed the resource code, it seems that EntityView's default cs/sc/sh field has gone.

FILE_PATH:
thingsboardrule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbCopyAttributesToEntityViewNode.java

![image](https://user-images.githubusercontent.com/21171589/165665966-bb9f5eba-d49d-4456-9f18-dddd7f1356f2.png)

**Comment by Widnio** [comment]
Hey,

I am also experiencing this issue in Version 3.4.0.

If I add "metadata.scope = "SERVER_SCOPE";" in a script before the "copy to view" node it solves the problem. 

The exception only happend for devices without an EtityView related to them.

I hope this helps.

Regards,
Roman

**Comment by Ultrazombie** [comment]
Closed do to inactivity
