### ISSUE TITLE
java.util.concurrent.TimeoutException: null[Bug] 

### ISSUE THREAD

**Issue by 1-point** [thingsboard/thingsboard#6541]
**Describe the bug**
I am using thingsboard/tb-postgres:3.3.2 docker image, and I upload device data by MQTT gateway topic v1/gateway/telemetry, then I figure out that one device cannot upload successfully, I cought the error as following:

```
2022-05-12 02:17:51,599 [tb-queue-request-template-tb_transport.api.responses.604da33c4fb4-13-thread-1] WARN  o.t.s.q.c.DefaultTbQueueRequestTemplate - Request timeout detected, currentNs [2382850858702220], ResponseMetaData{submitTime=2382831607024612, calculatedExpTime=2382841607024612, deltaMs=10000000000, expTime=2382841607024612, future=SettableFuture@4464abe0[status=PENDING]}, key [b7812293-872b-4dde-b0ee-d77dd26bccf4]
2022-05-12 02:17:51,600 [DefaultTransportService-8-8] WARN  o.t.s.t.m.s.GatewaySessionHandler - [ce5dd187-c680-4610-a287-1b4ec2e6c86c] Failed to process device connect command: 孔隙水压计
java.util.concurrent.TimeoutException: null
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.setTimeoutException(DefaultTbQueueRequestTemplate.java:163)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$tryCleanStaleRequests$0(DefaultTbQueueRequestTemplate.java:132)
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.tryCleanStaleRequests(DefaultTbQueueRequestTemplate.java:128)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:117)
        at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:101)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

My gateway upload message format is 
```
{
	"液位计": [
		{
			"values": {
				"key-cm": 13.0
			},
			"ts": 1652320706000
		}
	],
	"孔隙水压计": [
		{
			"values": {
				"key-mpa": 0.1
			},
			"ts": 1652320706000
		}
	],
	"测斜仪": [
		{
			"values": {
				"key-du": 72.47
			},
			"ts": 1652320706000
		}
	]
}
```

* OS: centos7
* Browser chrome

I wonder why it's happend and how can i solve this problem, can anyone hele me.
thanks

**Comment by 1-point** [comment]
I found and solved the problem.
the key point is that i changed the default device_profile name, `default ` to another word
when new device upload, the program will automatically create. when set device_profile_id, it will use keyword 'default' to match the field name of device_profile table, because I change the name of default device_profile, so none of record matched.
and then creating a new default device_profile record. but default record is already exist, so .......
I think if we query the default device profile not by filed name, but is_default would be better.
