### ISSUE TITLE
[Bug] Invalid Redis connection when downloading software package

### ISSUE THREAD

**Issue by shoskensMagics** [thingsboard/thingsboard#6542]
**Describe the bug**
I'm getting an internal server error (status 500) when I try to call the `/api/v1/{deviceToken}/software` endpoint.

**Your Server Environment**
* Own setup
  * Helm deployment on GCP cluster
  * ThingsBoard Version 3.3.4.1

**Your Client Environment**
**Desktop (please complete the following information):**
* OS: Windows
* Browser: Chrome

**Your Device**
HTTP connectivity, through the swagger-ui

**To Reproduce**
1. Make sure you have a valid software package configured
1. Go to 'http(s)://host:port/swagger-ui/#/device-api-controller/getSoftwareUsingGET'
2. Fill in the device / software package details
3. Make the request

**Expected behavior**
A download of the software package is made possible

**Workaround**
I can fiddle with the helm deployment and add the following environment variables to the http-transport StatefulSet.
```yaml
- name: REDIS_HOST
  value: "{{ .Release.Name }}-redis-master"
- name: REDIS_PASSWORD
  value: "{{ .Values.redis.auth.password }}"
```
Is this expected? Should the http-transport service interface with the Redis cache?

**Additional context**
Stacktrace found on the http-transport pod:
```
2022-05-12 09:38:16,750 [DefaultTransportService-25-1] WARN  o.t.s.t.http.DeviceApiController - Failed to process request
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:283)
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:485)
        at org.thingsboard.server.cache.ota.RedisOtaPackageDataCache.get(RedisOtaPackageDataCache.java:41)
        at org.thingsboard.server.transport.http.DeviceApiController$GetOtaPackageCallback.onSuccess(DeviceApiController.java:513)
        at org.thingsboard.server.transport.http.DeviceApiController$GetOtaPackageCallback.onSuccess(DeviceApiController.java:492)
        at org.thingsboard.server.common.transport.service.DefaultTransportService.lambda$process$10(DefaultTransportService.java:704)
        at org.thingsboard.server.queue.common.AsyncCallbackTemplate$1.onSuccess(AsyncCallbackTemplate.java:49)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1080)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:15)
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:273)
        ... 13 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to localhost:6379
        at redis.clients.jedis.Connection.connect(Connection.java:165)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:109)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1904)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:130)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
        ... 16 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:53)
        at redis.clients.jedis.Connection.connect(Connection.java:158)
        ... 23 common frames omitted
```

**Comment by ban2derlog** [comment]
Hi, your WORKAROUND is a solution.
OTA updates (SOTA\FOTA) in MSA structure use Redis to send firmware\software to Devices.
So you need to add REDIS endpoint environment to Transport where OTA is configured.
