### ISSUE TITLE
SSL_CREDENTIALS_TYPE: PEM with Docker Compose throwing Error "Could not load key store 'null'" [Bug] 

### ISSUE THREAD

**Issue by kellergoech** [thingsboard/thingsboard#6732]
When trying to start the Docker compose yml with SL_CREDENTIALS_TYPE: PEM the container fails starting with the error Message "Could not load key store 'null'"

I use the actual Docker Image with thingsboard v3.3.4.1.
Here the yml file:
```
version: '2.2'
#upgrade:
#docker pull thingsboard/tb-cassandra
#docker-compose stop
#docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres upgrade-tb.sh
#docker-compose rm mytb
#docker-compose up
services:
  zookeeper:
    restart: unless-stopped
    image: "zookeeper:3.5"
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
  kafka:
    restart: unless-stopped
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  pitb:
    restart: unless-stopped
    image: "thingsboard/tb-cassandra"
    depends_on:
      - kafka
    ports:
      - "8080:9090"
      - "1883:1883"
      - "8883:8883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
      SSL_ENABLED: 1
      SSL_CREDENTIALS_TYPE: PEM
      SSL_PEM_CERT: /config/HTTP/HTTPserver.pem
      SSL_PEM_KEY: /config/HTTP/HTTPserver_key.pem
      MQTT_SSL_ENABLED: 0
      MQTT_SSL_CREDENTIALS_TYPE: PEM
      MQTT_SSL_PEM_CERT: /config/MQTT/MQTTserver.pem
      MQTT_SSL_PEM_KEY: /config/MQTT/MQTTserver_key.pem
      MQTT_BIND_PORT: 1883
      MQTT_BIND_ADDRESS: 0.0.0.0
        #8883 tls - 1883 ohne
    volumes:
      - /home/elias/Python/Dash/thingsboard/data:/data
      - /home/elias/Python/Dash/thingsboard/logs:/var/log/thingsboard
      - /home/elias/Python/Dash/thingsboard/certificates:/config
```

and the log:

```
2022-06-16 10:14:30,459 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId: ebb1d6e21cc92130
2022-06-16 10:14:30,459 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1655374470459
2022-06-16 10:14:30,460 [main] INFO  o.a.k.c.consumer.ConsumerConfig - ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [kafka:9092]
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
	client.id = transport-api-notifications-cf42b0bed28e
	client.rack = 
	connections.max.idle.ms = 540000
	default.api.timeout.ms = 60000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 134217728
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = transport-node-cf42b0bed28e
	group.instance.id = null
	heartbeat.interval.ms = 3000
	interceptor.classes = []
	internal.leave.group.on.close = true
	internal.throw.on.fetch.stable.offset.unsupported = false
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 16777216
	max.poll.interval.ms = 300000
	max.poll.records = 8192
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer

2022-06-16 10:14:30,462 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka version: 2.8.0
2022-06-16 10:14:30,462 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId: ebb1d6e21cc92130
2022-06-16 10:14:30,462 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1655374470462
2022-06-16 10:14:30,464 [main] INFO  o.t.s.q.c.AbstractTbQueueConsumerTemplate - enqueue topics subscribe [TopicPartitionInfo(topic=tb_transport.notifications.cf42b0bed28e, tenantId=Optional.empty, partition=Optional.empty, fullTopicName=tb_transport.notifications.cf42b0bed28e, myPartition=false)] 
2022-06-16 10:14:30,514 [main] INFO  o.t.s.q.c.AbstractTbQueueConsumerTemplate - enqueue topic subscribe tb_transport.api.responses.cf42b0bed28e 
2022-06-16 10:14:30,515 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.t.s.q.k.TbKafkaConsumerTemplate - subscribe topics [tb_transport.api.responses.cf42b0bed28e]
2022-06-16 10:14:30,516 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.clients.consumer.KafkaConsumer - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Subscribed to topic(s): tb_transport.api.responses.cf42b0bed28e
2022-06-16 10:14:30,522 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  org.apache.kafka.clients.Metadata - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Cluster ID: M5ySetviRZyynkwt4_TI3w
2022-06-16 10:14:30,522 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Discovered group coordinator kafka:9092 (id: 2147482641 rack: null)
2022-06-16 10:14:30,525 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] (Re-)joining group
2022-06-16 10:14:30,533 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] (Re-)joining group
2022-06-16 10:14:30,535 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Successfully joined group with generation Generation{generationId=1, memberId='transport-api-response-cf42b0bed28e-fa4ea28f-eb40-4bea-b5e7-30261fd8616d', protocol='range'}
2022-06-16 10:14:30,536 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Finished assignment for group at generation 1: {transport-api-response-cf42b0bed28e-fa4ea28f-eb40-4bea-b5e7-30261fd8616d=Assignment(partitions=[tb_transport.api.responses.cf42b0bed28e-0])}
2022-06-16 10:14:30,540 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Successfully synced group in generation Generation{generationId=1, memberId='transport-api-response-cf42b0bed28e-fa4ea28f-eb40-4bea-b5e7-30261fd8616d', protocol='range'}
2022-06-16 10:14:30,540 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Notifying assignor about the new Assignment(partitions=[tb_transport.api.responses.cf42b0bed28e-0])
2022-06-16 10:14:30,543 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Adding newly assigned partitions: tb_transport.api.responses.cf42b0bed28e-0
2022-06-16 10:14:30,549 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Found no committed offset for partition tb_transport.api.responses.cf42b0bed28e-0
2022-06-16 10:14:30,559 [tb-queue-request-template-tb_transport.api.responses.cf42b0bed28e-17-thread-1] INFO  o.a.k.c.c.i.SubscriptionState - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Resetting offset for partition tb_transport.api.responses.cf42b0bed28e-0 to position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[kafka:9092 (id: 1006 rack: null)], epoch=0}}.
2022-06-16 10:14:30,724 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Could not load key store 'null'
2022-06-16 10:14:30,724 [main] INFO  o.t.s.q.c.AbstractTbQueueConsumerTemplate - unsubscribe topic and stop consumer tb_transport.notifications.cf42b0bed28e
2022-06-16 10:14:30,724 [main] INFO  o.t.s.q.k.TbKafkaConsumerTemplate - unsubscribe topic and close consumer for topic tb_transport.notifications.cf42b0bed28e
2022-06-16 10:14:30,725 [main] INFO  o.a.k.clients.consumer.KafkaConsumer - [Consumer clientId=transport-api-notifications-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Unsubscribed all topics or patterns and assigned partitions
2022-06-16 10:14:30,725 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,725 [main] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,725 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,727 [main] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.consumer for transport-api-notifications-cf42b0bed28e unregistered
2022-06-16 10:14:30,727 [main] INFO  o.t.s.q.c.AbstractTbQueueConsumerTemplate - unsubscribe topic and stop consumer tb_transport.api.responses.cf42b0bed28e
2022-06-16 10:14:30,735 [main] INFO  o.t.s.q.k.TbKafkaConsumerTemplate - unsubscribe topic and close consumer for topic tb_transport.api.responses.cf42b0bed28e
2022-06-16 10:14:30,735 [main] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Revoke previously assigned partitions tb_transport.api.responses.cf42b0bed28e-0
2022-06-16 10:14:30,735 [main] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Member transport-api-response-cf42b0bed28e-fa4ea28f-eb40-4bea-b5e7-30261fd8616d sending LeaveGroup request to coordinator kafka:9092 (id: 2147482641 rack: null) due to the consumer unsubscribed from all topics
2022-06-16 10:14:30,736 [main] INFO  o.a.k.clients.consumer.KafkaConsumer - [Consumer clientId=transport-api-response-cf42b0bed28e, groupId=transport-node-cf42b0bed28e] Unsubscribed all topics or patterns and assigned partitions
2022-06-16 10:14:30,739 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,739 [main] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,740 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,741 [main] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.consumer for transport-api-response-cf42b0bed28e unregistered
2022-06-16 10:14:30,742 [main] INFO  o.a.k.clients.producer.KafkaProducer - [Producer clientId=transport-api-request-cf42b0bed28e] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2022-06-16 10:14:30,743 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,743 [main] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,743 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,743 [main] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.producer for transport-api-request-cf42b0bed28e unregistered
2022-06-16 10:14:30,744 [kafka-admin-client-thread | adminclient-6] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-6 unregistered
2022-06-16 10:14:30,745 [kafka-admin-client-thread | adminclient-6] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,745 [kafka-admin-client-thread | adminclient-6] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,745 [kafka-admin-client-thread | adminclient-6] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,746 [kafka-admin-client-thread | adminclient-7] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-7 unregistered
2022-06-16 10:14:30,747 [kafka-admin-client-thread | adminclient-7] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,747 [kafka-admin-client-thread | adminclient-7] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,747 [kafka-admin-client-thread | adminclient-7] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,747 [kafka-admin-client-thread | adminclient-8] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-8 unregistered
2022-06-16 10:14:30,748 [kafka-admin-client-thread | adminclient-8] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,748 [kafka-admin-client-thread | adminclient-8] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,748 [kafka-admin-client-thread | adminclient-8] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,749 [kafka-admin-client-thread | adminclient-9] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-9 unregistered
2022-06-16 10:14:30,750 [kafka-admin-client-thread | adminclient-9] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,750 [kafka-admin-client-thread | adminclient-9] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,750 [kafka-admin-client-thread | adminclient-9] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,750 [kafka-admin-client-thread | adminclient-10] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-10 unregistered
2022-06-16 10:14:30,751 [kafka-admin-client-thread | adminclient-10] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,751 [kafka-admin-client-thread | adminclient-10] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,751 [kafka-admin-client-thread | adminclient-10] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,751 [kafka-admin-client-thread | adminclient-11] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-11 unregistered
2022-06-16 10:14:30,752 [kafka-admin-client-thread | adminclient-11] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,752 [kafka-admin-client-thread | adminclient-11] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,752 [kafka-admin-client-thread | adminclient-11] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,753 [kafka-admin-client-thread | adminclient-2] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-2 unregistered
2022-06-16 10:14:30,753 [kafka-admin-client-thread | adminclient-2] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,753 [kafka-admin-client-thread | adminclient-2] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,754 [kafka-admin-client-thread | adminclient-2] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,754 [kafka-admin-client-thread | adminclient-3] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-3 unregistered
2022-06-16 10:14:30,754 [kafka-admin-client-thread | adminclient-3] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,755 [kafka-admin-client-thread | adminclient-3] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,755 [kafka-admin-client-thread | adminclient-3] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,755 [kafka-admin-client-thread | adminclient-4] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-4 unregistered
2022-06-16 10:14:30,756 [kafka-admin-client-thread | adminclient-4] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,756 [kafka-admin-client-thread | adminclient-4] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,756 [kafka-admin-client-thread | adminclient-4] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,757 [kafka-admin-client-thread | adminclient-5] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-5 unregistered
2022-06-16 10:14:30,757 [kafka-admin-client-thread | adminclient-5] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,757 [kafka-admin-client-thread | adminclient-5] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,757 [kafka-admin-client-thread | adminclient-5] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,758 [kafka-admin-client-thread | adminclient-1] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.admin.client for adminclient-1 unregistered
2022-06-16 10:14:30,758 [kafka-admin-client-thread | adminclient-1] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,758 [kafka-admin-client-thread | adminclient-1] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,759 [kafka-admin-client-thread | adminclient-1] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,759 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
2022-06-16 10:14:30,759 [main] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-16 10:14:30,759 [main] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
2022-06-16 10:14:30,759 [main] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.consumer for consumer-stats-loader-client unregistered
2022-06-16 10:14:30,761 [nosql-Read-dispatcher-5-thread-1] INFO  o.t.s.d.u.AbstractBufferedRateExecutor - Buffered rate executor thread stopped
2022-06-16 10:14:30,761 [nosql-Write-dispatcher-7-thread-1] INFO  o.t.s.d.u.AbstractBufferedRateExecutor - Buffered rate executor thread stopped
2022-06-16 10:14:30,761 [nosql-Write-dispatcher-7-thread-2] INFO  o.t.s.d.u.AbstractBufferedRateExecutor - Buffered rate executor thread stopped
2022-06-16 10:14:30,761 [nosql-Read-dispatcher-5-thread-2] INFO  o.t.s.d.u.AbstractBufferedRateExecutor - Buffered rate executor thread stopped
2022-06-16 10:14:30,761 [sql-queue-2-ts latest-13-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2022-06-16 10:14:30,761 [sql-queue-1-ts latest-12-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2022-06-16 10:14:30,761 [sql-queue-0-ts latest-11-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2022-06-16 10:14:32,778 [sql-queue-0-events-2-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2022-06-16 10:14:32,778 [sql-queue-1-events-3-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2022-06-16 10:14:32,778 [sql-queue-2-events-4-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2022-06-16 10:14:32,784 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2022-06-16 10:14:32,785 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-06-16 10:14:32,788 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2022-06-16 10:14:32,813 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-06-16 10:14:32,840 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Could not load key store 'null'
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.boot.web.server.WebServerException: Could not load key store 'null'
	at org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.configureSslKeyStore(SslConnectorCustomizer.java:132)
	at org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.configureSsl(SslConnectorCustomizer.java:92)
	at org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.customize(SslConnectorCustomizer.java:57)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.customizeSsl(TomcatServletWebServerFactory.java:341)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.customizeConnector(TomcatServletWebServerFactory.java:319)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:185)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158)
	... 17 common frames omitted
Caused by: java.lang.IllegalArgumentException: Resource location must not be null
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.util.ResourceUtils.getURL(ResourceUtils.java:130)
	at org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.configureSslKeyStore(SslConnectorCustomizer.java:129)
	... 24 common frames omitted 
```
The certificates are existend in the docker container, which I checked:
```
thingsboard@fc369b1fc438:/config/MQTT$ ls
MQTTserver.pem  MQTTserver_key.pem
thingsboard@fc369b1fc438:/config/MQTT$ cd /config/HTTP
thingsboard@fc369b1fc438:/config/HTTP$ ls
HTTPserver.pem  HTTPserver_key.pem
```

**Comment by kellergoech** [comment]
I also tried to use the old PKCS12 KEYSTORE but it gets the same error message. Is there any special Owner/rights which I have to set on the certificates?

**Comment by trikimiki** [comment]
`MQTT_SSL_ENABLED: 0` - your SSL option for MQTT is actually disabled

You might also need to rewrite it so instead of `0` or `1` there would be `"false"` or `"true"`

About permissions - the owner is correct, but permissions should be `-rw-r--r--`

If this does not help - you could try using the default location for SSL keys/certs, which is configuration folder:
1. Go to `/usr/share/thingsboard/conf` inside the container, copy configs file.
2. Create a new volume for configs, e.g. `- /home/elias/Python/Dash/thingsboard/config:/usr/share/thingsboard/conf`
3. Copy files to the new volume, apply required permissions (as per installation guide).
4. In the compose file, change keys/certs location so it is only file name, e.g. `SSL_PEM_CERT:"HTTPserver.pem"`
