### ISSUE TITLE
mail service

### ISSUE THREAD

**Issue by AvishekHardin** [thingsboard/thingsboard#689]
Hello Team,

Good day,
am actually getting below issue while sending email in case of any alarms that have been triggered by. following the guides from https://thingsboard.io/docs/samples/alarms/basic-rules/
Note: I have created a gmail account and associated this with TB-plugins, snapshot below.. 

![image](https://user-images.githubusercontent.com/7479253/38024107-0c665194-3295-11e8-9d5b-e296d39c0712.png)

can you please help.

org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbui
534-5.7.14 FXmQvhs6YRR-sX9dKT2B-ldNK8m29PP-FdYKso5QWXfeXt5Lyju_u5fVt7cKiTw8DGkc5h
534-5.7.14 uruoPQZFzwIG0mTj7ivIhbVxZVkTOHGgXEZkqs3CTnmCuyWzPJcsbetD1absbG3D9duJiN
534-5.7.14 0KfwwKEjbTyabV7oGORsZGS7ZwLyZoeZrwJgiIcJWy0hu3zRngubLsV_alvtSZMPTb7Im_
534-5.7.14 y1ve3QM-jvn4t3XksXmyCOXhme4b0> Please log in via your web browser and
534-5.7.14 then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 o88sm938597pfk.91 - gsmtp

	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:424)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:340)
	at org.thingsboard.server.extensions.core.plugin.mail.MailPlugin.sendMail(MailPlugin.java:120)
	at org.thingsboard.server.extensions.core.plugin.mail.MailPlugin.lambda$process$1(MailPlugin.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbui
534-5.7.14 FXmQvhs6YRR-sX9dKT2B-ldNK8m29PP-FdYKso5QWXfeXt5Lyju_u5fVt7cKiTw8DGkc5h
534-5.7.14 uruoPQZFzwIG0mTj7ivIhbVxZVkTOHGgXEZkqs3CTnmCuyWzPJcsbetD1absbG3D9duJiN
534-5.7.14 0KfwwKEjbTyabV7oGORsZGS7ZwLyZoeZrwJgiIcJWy0hu3zRngubLsV_alvtSZMPTb7Im_
534-5.7.14 y1ve3QM-jvn4t3XksXmyCOXhme4b0> Please log in via your web browser and
534-5.7.14 then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 o88sm938597pfk.91 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:648)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:583)
	at javax.mail.Service.connect(Service.java:291)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:501)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:421)
	... 9 more

Thanks,
Best Regards,

**Comment by Karabiy** [comment]
are you sure you have used the up to date credentials for those? we also recommend following the next guide for the mail server configuration reasons: https://thingsboard.io/docs/user-guide/ui/mail-settings/
