### ISSUE TITLE
[Bug] Upgrade from 3.3.4.1 to 3.4 failed

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#6971]
**Your Server Environment**
* own setup
  * local infrastructure
  * 3.3.4.1 CE
  * Debian Buster (10.12)
Upgrading to 3.4 failed.

2022-07-20 08:08:13,838 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2022-07-20 08:08:13,866 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-07-20 08:08:14,607 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 667 ms. Found 1 JPA repository interfaces.
2022-07-20 08:08:14,624 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2022-07-20 08:08:14,625 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-07-20 08:08:14,718 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 92 ms. Found 1 JPA repository interfaces.
2022-07-20 08:08:14,725 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2022-07-20 08:08:14,726 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-07-20 08:08:14,782 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 55 ms. Found 1 JPA repository interfaces.
2022-07-20 08:08:14,788 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2022-07-20 08:08:14,788 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-07-20 08:08:15,611 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 822 ms. Found 40 JPA repository interfaces.
2022-07-20 08:08:17,978 [main] INFO  o.s.i.c.DefaultConfiguringBeanFactoryPostProcessor - No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2022-07-20 08:08:18,052 [main] INFO  o.s.i.c.DefaultConfiguringBeanFactoryPostProcessor - No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2022-07-20 08:08:19,407 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-07-20 08:08:19,447 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-07-20 08:08:20,793 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
2022-07-20 08:08:20,824 [main] INFO  o.a.coyote.http11.Http11NioProtocol - The ["http-nio-0.0.0.0-8080"] connector has been configured to support HTTP upgrade to [h2c]
2022-07-20 08:08:20,824 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-0.0.0.0-8080"]
2022-07-20 08:08:20,825 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2022-07-20 08:08:20,826 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.63]
2022-07-20 08:08:21,142 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2022-07-20 08:08:21,142 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 13340 ms
2022-07-20 08:08:23,788 [main] INFO  o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [name: default]
2022-07-20 08:08:24,040 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.6.9.Final
2022-07-20 08:08:25,054 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-07-20 08:08:25,546 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2022-07-20 08:08:26,366 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2022-07-20 08:08:26,446 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2022-07-20 08:08:28,231 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.20.Final
2022-07-20 08:08:32,753 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-07-20 08:08:32,818 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-07-20 08:08:40,772 [main] INFO  o.t.s.d.a.CachedAttributesService - Going to use directExecutor for the local cache type caffeine
2022-07-20 08:08:45,024 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 1 endpoint(s) beneath base path '/actuator'
2022-07-20 08:08:46,335 [main] INFO  o.s.b.a.w.s.WelcomePageHandlerMapping - Adding welcome page: class path resource [public/index.html]
2022-07-20 08:08:48,400 [main] INFO  o.s.s.web.DefaultSecurityFilterChain - Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@2e6f1f48, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@5ed88e31, org.springframework.security.web.context.SecurityContextPersistenceFilter@6ac0fd1d, org.springframework.security.web.header.HeaderWriterFilter@2ba4b32b, org.springframework.security.web.csrf.CsrfFilter@21539796, org.springframework.security.web.authentication.logout.LogoutFilter@2e096ac0, org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter@74267ece, org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter@55a07f97, org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter@3e265811, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@58189132, org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter@574413bd, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@6ce8bf64, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@6413eeb7, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@3ad9fea, org.springframework.security.oauth2.client.web.OAuth2AuthorizationCodeGrantFilter@748fa354, org.springframework.security.web.session.SessionManagementFilter@47ab3688, org.springframework.security.web.access.ExceptionTranslationFilter@623ed5ed, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@7827cdfc]
2022-07-20 08:08:49,554 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2022-07-20 08:08:49,555 [main] INFO  o.s.i.c.PublishSubscribeChannel - Channel 'application.errorChannel' has 1 subscriber(s).
2022-07-20 08:08:49,555 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - started bean '_org.springframework.integration.errorLogger'
2022-07-20 08:08:49,556 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-0.0.0.0-8080"]
2022-07-20 08:08:49,616 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 8080 (http) with context path ''
2022-07-20 08:08:50,387 [main] INFO  o.t.s.i.ThingsboardInstallService - Starting ThingsBoard Upgrade from version 3.3.4 ...
2022-07-20 08:08:50,392 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clear cache to upgrade from version 3.3.4 to 3.4.0 ...
2022-07-20 08:08:50,393 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [relations]
2022-07-20 08:08:50,394 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [deviceCredentials]
2022-07-20 08:08:50,395 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [devices]
2022-07-20 08:08:50,400 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [sessions]
2022-07-20 08:08:50,400 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [assets]
2022-07-20 08:08:50,400 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [entityViews]
2022-07-20 08:08:50,400 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [claimDevices]
2022-07-20 08:08:50,400 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [securitySettings]
2022-07-20 08:08:50,400 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [tenantProfiles]
2022-07-20 08:08:50,400 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [tenants]
2022-07-20 08:08:50,401 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [tenantsExist]
2022-07-20 08:08:50,401 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [deviceProfiles]
2022-07-20 08:08:50,401 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [attributes]
2022-07-20 08:08:50,401 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [usersUpdateTime]
2022-07-20 08:08:50,402 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [otaPackages]
2022-07-20 08:08:50,402 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [otaPackagesData]
2022-07-20 08:08:50,402 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [edges]
2022-07-20 08:08:50,402 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [repositorySettings]
2022-07-20 08:08:50,402 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [autoCommitSettings]
2022-07-20 08:08:50,402 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [twoFaVerificationCodes]
2022-07-20 08:08:50,402 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [versionControlTask]
2022-07-20 08:08:50,403 [main] INFO  o.t.s.i.ThingsboardInstallService - Upgrading ThingsBoard from version 3.3.4 to 3.4.0 ...
2022-07-20 08:08:50,476 [main] INFO  o.t.s.s.i.SqlDatabaseUpgradeService - Updating schema ...
2022-07-20 08:08:55,569 [main] INFO  o.t.s.s.i.SqlDatabaseUpgradeService - Loading queues...
2022-07-20 08:08:56,164 [main] INFO  org.owasp.validator.html.Policy - Attempting to load AntiSamy policy from an input stream.
2022-07-20 08:08:56,632 [main] WARN  org.owasp.validator.html.Policy - The directive "noopenerAndNoreferrerAnchors" is not enabled by default. It is recommended to enable it to prevent reverse tabnabbing attacks.
2022-07-20 08:08:57,086 [main] INFO  c.d.oss.driver.api.core.uuid.Uuids - PID obtained through JMX: 11503
2022-07-20 08:08:57,571 [main] INFO  o.t.s.s.i.SqlDatabaseUpgradeService - Updating schema settings...
2022-07-20 08:08:57,579 [main] INFO  o.t.s.s.i.SqlDatabaseUpgradeService - Schema updated.
2022-07-20 08:08:57,581 [main] INFO  o.t.s.s.i.u.DefaultDataUpdateService - Updating data from version 3.3.4 to 3.4.0 ...
2022-07-20 08:08:58,001 [main] ERROR o.t.server.dao.service.DataValidator - Data object is invalid: [Tenant profile data queue configuration should be specified!]
2022-07-20 08:08:58,005 [main] ERROR o.t.s.i.ThingsboardInstallService - Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: Tenant profile data queue configuration should be specified!
	at org.thingsboard.server.dao.service.validator.TenantProfileDataValidator.validateDataImpl(TenantProfileDataValidator.java:69)
	at org.thingsboard.server.dao.service.validator.TenantProfileDataValidator.validateDataImpl(TenantProfileDataValidator.java:38)
	at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:55)
	at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl.saveTenantProfile(TenantProfileServiceImpl.java:87)
	at org.thingsboard.server.service.install.update.RateLimitsUpdater.updateEntity(RateLimitsUpdater.java:112)
	at org.thingsboard.server.service.install.update.RateLimitsUpdater.updateEntity(RateLimitsUpdater.java:28)
	at org.thingsboard.server.service.install.update.PaginatedUpdater.updateEntities(PaginatedUpdater.java:37)
	at org.thingsboard.server.service.install.update.PaginatedUpdater.updateEntities(PaginatedUpdater.java:53)
	at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:159)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:223)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)

**Comment by YevhenBondarenko** [comment]
HI @Backdraft007,

Thanks for the issue.

We investigated your logs and found a bug with upgrade script.
This bug related to the "isolated" tenant profiles and for resolving we have a workaround.
Please connect to the DB `psql -U postgres -d postgres -h 127.0.0.1 -W` 
and execute `UPDATE tenant_profile SET isolated_tb_rule_engine = false WHERE isolated_tb_rule_engine = true;`

**Comment by Backdraft007** [comment]
Hi @YevhenBondarenko,

when I execute the command, I get the following:
postgres=# UPDATE tenant_profile SET isolated_tb_rule_engine = false WHERE isolated_tb_rule_engine = true;
ERROR:  relation "tenant_profile" does not exist
LINE 1: UPDATE tenant_profile SET isolated_tb_rule_engine = false WH...

**Comment by YevhenBondarenko** [comment]
- `psql -U postgres -d postgres -h 127.0.0.1 -W `
- `\c thingsboard`
- `UPDATE tenant_profile SET isolated_tb_rule_engine = false WHERE isolated_tb_rule_engine = true;`

**Comment by Backdraft007** [comment]
Thank you @YevhenBondarenko .
It is working now. So I wait to upgrade my PE environment till the bug is corrected?

**Comment by Backdraft007** [comment]
Perfect. Thanks.
