### ISSUE TITLE
[Bug] Thingsboard extension - Error: inject() must be called from an injection context

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6977]
**Thingsboard v3.3.4.1**

This error I got when adding `thingsboard-extension-widgets.js` as module to my custom widget. There is no code modification. Only difference is I don't deploy `thingsboard-extension-widgets-1.0.0-SNAPSHOT.jar` as described [here](https://github.com/thingsboard/thingsboard-extensions#deploy-project-to-customer-server) but use JSDelivr CDN to get direct access to built [thingsboard-extension-widgets.js](https://cdn.jsdelivr.net/gh/devaskim/my-cdn/thingsboard-extension-widgets.js)

Also I [added into Thingsboard UI](https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/services/resources.service.ts#L157) additional log message `console.log('Module init error: ', e);` to see the following error:

Log without `map` file
```
Module init error:  Error: inject() must be called from an injection context
    at Ua (thingsboard-extension-widgets.js:347:172)
    at Ya (thingsboard-extension-widgets.js:347:349)
    at Object.cX_Factory [as factory] (ɵfac.js? [sm]:1:1)
    at R3Injector.hydrate (core.js:11457:1)
    at R3Injector.get (core.js:11276:1)
    at core.js:11314:1
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (core.js:11314:1)
    at new NgModuleRef$1 (core.js:25345:1)
    at NgModuleFactory$1.create (core.js:25399:1)
```
Log with `map` file, the file is [also added](https://cdn.jsdelivr.net/gh/devaskim/my-cdn/thingsboard-extension-widgets.js.map) to JSDelivr.
```
Module init error:  Error: inject() must be called from an injection context
    at Ua (injector_compatibility.ts:61:11)
    at Ya (injector_compatibility.ts:85:40)
    at vX.ɵfac [as factory] (thingsboard-extension-widgets.ts:3:4)
    at R3Injector.hydrate (core.js:11457:1)
    at R3Injector.get (core.js:11276:1)
    at core.js:11314:1
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (core.js:11314:1)
    at new NgModuleRef$1 (core.js:25345:1)
    at NgModuleFactory$1.create (core.js:25399:1)
```
Here is content of `at vX.ɵfac [as factory] (thingsboard-extension-widgets.ts:3:4)`

![Скриншот 21-07-2022 141038](https://user-images.githubusercontent.com/86909129/180176711-b5202e47-f64a-4159-9069-b757986eebff.jpg)

**Comment by UsmanAzam** [comment]
Have you fixed it? What was your fix?

I also want to use jsdelivr cdn instead of my own server

**Comment by devaskim** [comment]
Unfortunately, no

**Comment by UsmanAzam** [comment]
Im assuming you kept the Is module option ON?

**Comment by devaskim** [comment]
Yes
