### ISSUE TITLE
java.io.IOException: java.io.IOException，Invalid message received

### ISSUE THREAD

**Issue by BIT-masterpy** [thingsboard/thingsboard#701]
2018-04-03 13:28:03,303 [nioEventLoopGroup-5-5] INFO  o.t.s.t.mqtt.MqttTransportHandler - [127.0.0.1:60680] Invalid message received
2018-04-03 13:28:04,993 [http-nio-0.0.0.0-8080-exec-4] INFO  o.t.s.c.p.PluginWebSocketHandler - [fe8142c6-d4cb-4d8e-a80c-5dcca99fc0f3][30] Session is started
2018-04-03 13:28:05,005 [http-nio-0.0.0.0-8080-exec-6] INFO  o.t.s.c.p.PluginWebSocketHandler - [30] Processing TextMessage payload=[{"tsSubCmd..], byteCount=156, last=true]
2018-04-03 13:28:05,014 [http-nio-0.0.0.0-8080-exec-7] INFO  o.t.s.c.p.PluginWebSocketHandler - [30] Processing TextMessage payload=[{"tsSubCmd..], byteCount=160, last=true]
2018-04-03 13:28:05,024 [Akka-system-plugin-dispatcher-12] INFO  o.t.s.c.p.PluginWebSocketHandler - [30] Session is closed
2018-04-03 13:28:05,025 [Akka-system-plugin-dispatcher-12] WARN  o.t.s.e.c.p.t.h.TelemetryWebsocketMsgHandler - [fe8142c6-d4cb-4d8e-a80c-5dcca99fc0f3] Failed to send reply: SubscriptionUpdate [subscriptionId=2, errorCode=0, errorMsg=null, data={key1=[[Ljava.lang.Object;@592fa545], key2=[[Ljava.lang.Object;@37715b08]}]
java.io.IOException: java.io.IOException: źք׷ܺאքɭݾאֹһٶӑݨbքlޓc
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:315)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197)
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:102)
	at org.thingsboard.server.controller.plugin.PluginWebSocketHandler.send(PluginWebSocketHandler.java:189)
	at org.thingsboard.server.actors.plugin.PluginProcessingContext.send(PluginProcessingContext.java:86)
	at org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryWebsocketMsgHandler.sendWsMsg(TelemetryWebsocketMsgHandler.java:369)
	at org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryWebsocketMsgHandler.access$000(TelemetryWebsocketMsgHandler.java:49)
	at org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryWebsocketMsgHandler$3.onSuccess(TelemetryWebsocketMsgHandler.java:234)
	at org.thingsboard.server.extensions.core.plugin.telemetry.handlers.TelemetryWebsocketMsgHandler$3.onSuccess(TelemetryWebsocketMsgHandler.java:231)
	at org.thingsboard.server.actors.plugin.PluginActorMessageProcessor.onPluginCallbackMsg(PluginActorMessageProcessor.java:132)
	at org.thingsboard.server.actors.plugin.PluginActor.onPluginCallback(PluginActor.java:76)
	at org.thingsboard.server.actors.plugin.PluginActor.onReceive(PluginActor.java:50)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: źք׷ܺאքɭݾאֹһٶӑݨbքlޓc
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.write(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221)
	at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451)
	at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441)
	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doWrite(WsRemoteEndpointImplServer.java:97)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:494)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	... 26 common frames omitted

**Comment by vparomskiy** [comment]
could you please write what value is sent over websocket?

**Comment by BIT-masterpy** [comment]
@vparomskiy 
I use tb-gateway to receive data sent by opc server.  tb-gateway:1.4 ,thingsboard:1.4 version

**tb-gateway.yml:**
![tb-gateway](https://user-images.githubusercontent.com/30205233/39103028-f2f3e794-46da-11e8-95d6-4d939e136c9b.png)

**opc-config.json**
![opc-config](https://user-images.githubusercontent.com/30205233/39103040-05c5522c-46db-11e8-9102-260b98b3eb4a.png)

**opcua  server:**
![server](https://user-images.githubusercontent.com/30205233/39103086-4e976f62-46db-11e8-8f26-428c8ba2c141.png)

![opc](https://user-images.githubusercontent.com/30205233/39103087-559c9cec-46db-11e8-81d3-959cb99f387a.png)

**Comment by mp-loki** [comment]
ThingsBoard says "Invalid message received" but it's not clear right now what's wrong with payload.
Can you please go to tb-gateway/conf/logback.xml, set 

```xml
<logger name="org.thingsboard" level="TRACE" />
```
Then re-run your case and post your logs?

**Comment by vparomskiy** [comment]
@BIT-masterpy sory for a long delay, os this issue still valid for you?
