### ISSUE TITLE
[Bug] TimeoutException when thingsboard-node is scaled by more than +1 replica at a time on kubernetes install

### ISSUE THREAD

**Issue by joe-pulse** [thingsboard/thingsboard#7067]
**Describe the bug**
* When scaling the `thingsboard-node` stateful set created by the `thingsboard-ce-k8s` helm charts, a `TimeoutException` occurs in `DefaultTransportService.getSnmpDevicesIds` if more than one replica is added at a time.
* This results in a crash loop and eventually one or more nodes ends up in Crash Loop Backoff state.
* Is this a regression of https://github.com/thingsboard/thingsboard/issues/6025 ?

**Your Server Environment**
* own setup
  * Managed K8s
  * Latest everything, stock everything, i.e.
    * Helm charts from https://github.com/thingsboard/thingsboard-ce-k8s master branch commit https://github.com/thingsboard/thingsboard-ce-k8s/commit/7e8887d180e4c18a04240c3a461e74d84d539e53
    * which pull Thingsboard 3.4.0

**Your Client Environment**
* kubectl client v1.24.3
* helm v3.9.2

**To Reproduce**
```
~/tmp1234$ git clone https://github.com/thingsboard/thingsboard-ce-k8s.git
Cloning into 'thingsboard-ce-k8s'...
remote: Enumerating objects: 1421, done.
remote: Counting objects: 100% (430/430), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 1421 (delta 344), reused 288 (delta 278), pack-reused 991
Receiving objects: 100% (1421/1421), 261.46 KiB | 507.00 KiB/s, done.
Resolving deltas: 100% (1012/1012), done.
~/tmp1234$ 

~/tmp1234$ helm dependency build thingsboard-ce-k8s/helm/thingsboard/
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "haproxy-ingress" chart repository
...Successfully got an update from the "haproxytech" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 4 charts
Downloading postgresql-ha from repo https://charts.bitnami.com/bitnami
Downloading cassandra from repo https://charts.bitnami.com/bitnami
Downloading kafka from repo https://charts.bitnami.com/bitnami
Downloading redis from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
~/tmp1234$ 

~/tmp1234$ kubectl create namespace reproduce3
namespace/reproduce3 created
~/tmp1234$ 

~/tmp1234$ helm install --set cassandra.enabled=true --namespace reproduce3 thingsboard  thingsboard-ce-k8s/helm/thingsboard/
NAME: thingsboard
LAST DEPLOYED: Wed Aug 10 16:58:38 2022
NAMESPACE: reproduce3
STATUS: deployed
REVISION: 1
NOTES:
1. Get node URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace reproduce3 -l "app.kubernetes.io/instance=thingsboard-node" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace reproduce3 port-forward $POD_NAME 8080:80
~/tmp1234$ 
```
* (Note there is no need here to go through the full setup process with load balancer etc as the issue relates to internal `thingsboard-node` startup.)
* Wait for the `thingsboard-init-tb-db-<uuid>` installer to complete.
* Wait for the single `thingsboard-node-0` node to startup and show `READY=1/1`
* Scale up the thingsboard-node stateful set to 3 replicas:
```
~/tmp1234$ 
~/tmp1234$ kubectl scale --replicas=3 sts/thingsboard-node -n reproduce3
statefulset.apps/thingsboard-node scaled
~/tmp1234$ 
```
* Result: The error is observed from the third node, i.e.
```
~/tmp1234$ kubectl logs --follow  -n reproduce3 thingsboard-node-2 | grep -B 2 -A 2 TimeoutException
2022-08-10 16:07:08,840 [vc-consumer-58-thread-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=monolith-vc-consumer-tb-node, groupId=monolith-vc-node] Setting offset for partition tb_version_control.1-8 to the committed offset FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[thingsboard-kafka-0.thingsboard-kafka-headless.reproduce3.svc.cluster.local:9092 (id: 0 rack: null)], epoch=0}}
2022-08-10 16:07:18,169 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at org.thingsboard.server.common.transport.service.DefaultTransportService.getSnmpDevicesIds(DefaultTransportService.java:348)
	at org.thingsboard.server.transport.snmp.service.ProtoTransportEntityService.getSnmpDevicesIds(ProtoTransportEntityService.java:86)
<etc...>
~/tmp1234$ 
```
and eventually the 3rd node ends up in "Crash loop backoff" state:
```
~/tmp1234$ kubectl get pods  -n reproduce3 | grep node
thingsboard-node-0                          1/1     Running            3 (22m ago)     24m
thingsboard-node-1                          1/1     Running            0               20m
thingsboard-node-2                          0/1     CrashLoopBackOff   7 (2m39s ago)   20m
```

**Workaround**
If only one replica is added at a time, the error does not occur:
```
$ kubectl scale --replicas=2 sts/thingsboard-node -n reproduce3
statefulset.apps/thingsboard-node scaled

$ kubectl get pods  -n reproduce3 | grep node
thingsboard-node-0                          1/1     Running   3 (29m ago)     31m
thingsboard-node-1                          1/1     Running   0               38s

$ kubectl scale --replicas=3 sts/thingsboard-node -n reproduce3
statefulset.apps/thingsboard-node scaled

$ kubectl get pods  -n reproduce3 | grep node
thingsboard-node-0                          1/1     Running   3 (31m ago)   33m
thingsboard-node-1                          1/1     Running   0             2m50s
thingsboard-node-2                          1/1     Running   0             54s
```
etc.

An alternative workaround would presumably be to disable the SNMP transport as per https://github.com/thingsboard/thingsboard/issues/6025

**Expected behavior**
`thingsboard-node` can be scaled with any additional number of replicas at the same time, subject to resource constraints.

**Comment by sumin-denys** [comment]
Hi @joe-pulse,

Since there hasn’t been any activity, I’m going to close this ticket for now. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.
