### ISSUE TITLE
UPDATE IoT data analytics tutorial & Samples

### ISSUE THREAD

**Issue by untilbit** [thingsboard/thingsboard#711]
Some users have issues with "IoT data analytics using Apache Spark, Kafka and ThingsBoard" tutorial and it's samples and need to be updated so it can work with ThingsBoard 1.4.

**Comment by cjkini** [comment]
Hi there,
 
i am facing the same issue here 

https://github.com/thingsboard/thingsboard/issues/722

**Comment by cjkini** [comment]
Error also poped up when we want to configure Telemetry Forwarding Rule.
https://thingsboard.io/docs/samples/analytics/resources/windspeed_telemetry_rule.json

The error is : 
"Unable to import plugin: Invalid plugin data structure"

**Comment by mp-loki** [comment]
Looks like you are trying to import Rule on Plugins screen. Go to Rules screen instead

**Comment by mp-loki** [comment]
@untilbit the tutorial was tested with ThingsBoard 1.4. The documentation was updated to remove the odds. Can you please describe the specific problems that you are facing with the tutorial?

**Comment by untilbit** [comment]
When I try to build the TB I get these errors.

> user@laptop:~/Projects/spark Integration/thingsboard$ mvn clean install -DskipTests
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] 'dependencies.dependency. org.thingsboard.extensions:extension-kafka:1.4.1-SNAPSHOT' for org.thingsboard.extensions:extension-kafka:1.4.1-SNAPSHOT is referencing itself. @ org.thingsboard:thingsboard:1.4.1-SNAPSHOT, /home/user/Projects/spark Integration/thingsboard/pom.xml, line 319, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.thingsboard.extensions:extension-kafka:1.4.1-SNAPSHOT (/home/ibina/Projects/spark Integration/thingsboard/extensions/extension-kafka/pom.xml) has 1 error
[ERROR]     'dependencies.dependency. org.thingsboard.extensions:extension-kafka:1.4.1-SNAPSHOT' for org.thingsboard.extensions:extension-kafka:1.4.1-SNAPSHOT is referencing itself. @ org.thingsboard:thingsboard:1.4.1-SNAPSHOT, /home/user/Projects/spark Integration/thingsboard/pom.xml, line 319, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by untilbit** [comment]
I still have issues.

The method **getWindSpeed()** doesn't exist in class **AvgWindSpeedData**.
**WindSpeedAndGeoZoneData** class does not have **getGeoZone()** method.

**Comment by untilbit** [comment]
I still have issues.

The method getWindSpeed() doesn't exist in class AvgWindSpeedData.
WindSpeedAndGeoZoneData class does not have getGeoZone() method.

**Comment by untilbit** [comment]
I've added it and still the same. The IDE cannot fins some methods because don't exist in the sample classes.

**Comment by mp-loki** [comment]
Which IDE are you using? Try building from Maven and then update maven project. Lombok library generates getters and setters for the fields, so it means that your IDE does not grab the binaries. Do **Maven -> Reimport** in Idea or **Project -> Clean + Maven -> Update Project** in Eclipse

**Comment by untilbit** [comment]
I use Idea, and have done Maven -> Re-import and also Regenerate Sources but still the same.
I'm missing something or some component has some issue..

**Comment by mp-loki** [comment]
Please check that Lombok plugin is installed and works properly in your IDE. This is piece of software is responsible for that. You can try to do some basic Lombok tutorial in a sample project to verify that.

**Comment by untilbit** [comment]
I am using IntelliJ IDEA as my IDE on Ubuntu 16.04.

I have done the following:

0. Wiped all data in **.m2/repository**
1. I have reinstalled Lombok plugin and then tested it with a sample project and is working.
2. Reimport TB server, built TB with **mvn clean install** and checked that thingsboard exists in **.m2/repository/org**
3. Reimport sample example and run it from IDE and I get 2 errors.

- Asset does not exist (org.thingsboard.server.common.data.asset.Asset)
- IDE cannot resolve symbol '**server**'

Checked **.m2/repository/org/thingsboard** and did not found the folder **server** so i created it and copied to it the folder **common** but did not solve the problem.

**Comment by mp-loki** [comment]
1) Which version of ThingsBoard have you built? 
2) what are the contents of  .m2/repository/org/thingsboard?
3) What is the value of `<thingsboard.version>` in `samples/pom.xml` ?

**Comment by untilbit** [comment]
1. I've built TB 1.4.0 Release

2. These are the contents of that folder
> .m2/repository/org/thingsboard
├── application
│   ├── 1.4.0
│   │   ├── application-1.4.0-boot.jar
│   │   ├── application-1.4.0.jar
│   │   ├── application-1.4.0.pom
│   │   ├── application-1.4.0-windows.zip
│   │   └── _remote.repositories
│   └── maven-metadata-local.xml
├── common
│   ├── 1.4.0
│   │   ├── common-1.4.0.pom
│   │   └── _remote.repositories
│   ├── data
│   │   ├── 1.3.1-SNAPSHOT
│   │   │   ├── data-1.3.1-SNAPSHOT.jar.lastUpdated
│   │   │   ├── data-1.3.1-SNAPSHOT.pom.lastUpdated
│   │   │   ├── data-1.3.1-SNAPSHOT-sources.jar.lastUpdated
│   │   │   └── resolver-status.properties
│   │   ├── 1.4.0
│   │   │   ├── data-1.4.0.jar
│   │   │   ├── data-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── maven-metadata-local.xml
│   ├── message
│   │   ├── 1.4.0
│   │   │   ├── message-1.4.0.jar
│   │   │   ├── message-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   └── transport
│       ├── 1.4.0
│       │   ├── _remote.repositories
│       │   ├── transport-1.4.0.jar
│       │   └── transport-1.4.0.pom
│       └── maven-metadata-local.xml
├── dao
│   ├── 1.4.0
│   │   ├── dao-1.4.0.jar
│   │   ├── dao-1.4.0.pom
│   │   ├── dao-1.4.0-tests.jar
│   │   └── _remote.repositories
│   └── maven-metadata-local.xml
├── extensions
│   ├── 1.4.0
│   │   ├── extensions-1.4.0.pom
│   │   └── _remote.repositories
│   ├── extension-kafka
│   │   ├── 1.0.0
│   │   │   ├── extension-kafka-1.0.0.jar.lastUpdated
│   │   │   └── extension-kafka-1.0.0.pom.lastUpdated
│   │   ├── 1.4.0
│   │   │   ├── extension-kafka-1.4.0-extension.jar
│   │   │   ├── extension-kafka-1.4.0.jar
│   │   │   ├── extension-kafka-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── extension-mqtt
│   │   ├── 1.4.0
│   │   │   ├── extension-mqtt-1.4.0-extension.jar
│   │   │   ├── extension-mqtt-1.4.0.jar
│   │   │   ├── extension-mqtt-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── extension-rabbitmq
│   │   ├── 1.4.0
│   │   │   ├── extension-rabbitmq-1.4.0-extension.jar
│   │   │   ├── extension-rabbitmq-1.4.0.jar
│   │   │   ├── extension-rabbitmq-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── extension-rest-api-call
│   │   ├── 1.4.0
│   │   │   ├── extension-rest-api-call-1.4.0-extension.jar
│   │   │   ├── extension-rest-api-call-1.4.0.jar
│   │   │   ├── extension-rest-api-call-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── extension-sns
│   │   ├── 1.4.0
│   │   │   ├── extension-sns-1.4.0-extension.jar
│   │   │   ├── extension-sns-1.4.0.jar
│   │   │   ├── extension-sns-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── extension-sqs
│   │   ├── 1.4.0
│   │   │   ├── extension-sqs-1.4.0-extension.jar
│   │   │   ├── extension-sqs-1.4.0.jar
│   │   │   ├── extension-sqs-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   └── maven-metadata-local.xml
├── extensions-api
│   ├── 1.4.0
│   │   ├── extensions-api-1.4.0.jar
│   │   ├── extensions-api-1.4.0.pom
│   │   └── _remote.repositories
│   └── maven-metadata-local.xml
├── extensions-core
│   ├── 1.4.0
│   │   ├── extensions-core-1.4.0.jar
│   │   ├── extensions-core-1.4.0.pom
│   │   └── _remote.repositories
│   └── maven-metadata-local.xml
├── samples
│   └── 1.4.0
│       └── samples-1.4.0.pom.lastUpdated
├── thingsboard
│   ├── 1.4.0
│   │   ├── _remote.repositories
│   │   └── thingsboard-1.4.0.pom
│   └── maven-metadata-local.xml
├── tools
│   ├── 1.4.0
│   │   ├── _remote.repositories
│   │   ├── tools-1.4.0.jar
│   │   └── tools-1.4.0.pom
│   └── maven-metadata-local.xml
├── transport
│   ├── 1.4.0
│   │   ├── _remote.repositories
│   │   └── transport-1.4.0.pom
│   ├── coap
│   │   ├── 1.4.0
│   │   │   ├── coap-1.4.0.jar
│   │   │   ├── coap-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── http
│   │   ├── 1.4.0
│   │   │   ├── http-1.4.0.jar
│   │   │   ├── http-1.4.0.pom
│   │   │   └── _remote.repositories
│   │   └── maven-metadata-local.xml
│   ├── maven-metadata-local.xml
│   └── mqtt
│       ├── 1.4.0
│       │   ├── mqtt-1.4.0.jar
│       │   ├── mqtt-1.4.0.pom
│       │   └── _remote.repositories
│       └── maven-metadata-local.xml
└── ui
    ├── 1.4.0
    │   ├── _remote.repositories
    │   ├── ui-1.4.0.jar
    │   └── ui-1.4.0.pom
    └── maven-metadata-local.xml

48 directories, 100 files

3. **<thingsboard.version>**  does not exist in my **samples/pom.xml**

I tried changing to version 1.4.0 for samples artifact but did not notice any effect
```
<parent>
        <groupId>org.thingsboard</groupId>
        <artifactId>samples</artifactId>
        <version>1.4.0</version>
    </parent>
```

**Comment by mp-loki** [comment]
Seems like you are trying to build **samples/spark-kafka-streaming-integration**.
You have to build parent **samples** project instead.

**Comment by untilbit** [comment]
- You are right. Lastly I was running it from **samples/spark-kafka-streaming-integration**, not from **samples** project.

- I changed version to 1.4.0 in **<thingsboard.version>1.4.0</thingsboard.version>**
- When I built the **samples** project I got this error:
> [ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project spark-kafka-streaming-integration: Some files do not have the expected license header -> [Help 1]

- Removed the plug-in and now I can build **samples** project without errors.

- Then I run in IDE Spark Kafka Streaming, I have TB docker running, Kafka running, Script to send random data running and when I check Asset "**Zone A**" and Device "**Analytics Gateway**" but no telemetry data. Also Asset "**Zone B**" isn't created.

- So I debugged the main class and IDE shows the following:
> t._1 = Cannot find local variable 't'
t._2 = Cannot find local variable 't'

- Also the aggregated data variable "**aggData**" is always equal to zero "**0**"

**Comment by untilbit** [comment]
Also tried doing the following:

- Executing the jar files **java -jar spark-kafka-streaming-integration-1.0.0.jar** and **java -jar original-spark-kafka-streaming-integration-1.0.0.jar** and i got same message as #722:
> no main manifest attribute, in spark-kafka-streaming-integration-1.0.0.jar

- Spark Submit:
```
spark-submit --class spark-kafka-streaming-integration-1.0.0.jar 
Exception in thread "main" java.lang.IllegalArgumentException: Missing application resource.
        at org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:241)
        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitArgs(SparkSubmitCommandBuilder.java:160)
        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitCommand(SparkSubmitCommandBuilder.java:274)
        at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildCommand(SparkSubmitCommandBuilder.java:151)
```

**Comment by untilbit** [comment]
Thanks for the answers @mp-loki. I'm near to resolving this. Any help is welcome.

**Comment by cjkini** [comment]
If we can solve this, coffee on me guys :grin: :grin: :grin:

**Comment by untilbit** [comment]
@cjkini    :smiley: :smiley:
If I solve this I'll would create a new turoial.

**Comment by mp-loki** [comment]
@untilbit That is appreciated

**Comment by untilbit** [comment]
Finally I was able to finish the Windmills tutorial last week, one of the issues was with Kafka installed locally. What I did was to use a Kafka broker hosted in the cloud.

**Comment by mp-loki** [comment]
I assume this can be closed now

**Comment by cjkini** [comment]
Hi guys, 
I am redoing this example. Please help me to solve this 

Will update my finding soon.

Thanks ya...

**Comment by untilbit** [comment]
Clone repository
    Import project in Intellij Idea
    Open terminal in IDE
    Compile with mvn clean install -DskipTests.

**Comment by cjkini** [comment]
Hi guys, 
I manage to get this thing done. Thanks to @mp-loki  @untilbit  for your support on this activity.

But, here i have 2 issues to be discussed : 
1. The SparkKafkaStreamingDemoMain code only runs for 15 minutes. The Spark Streaming context stop after that with this error : 

`Exception in thread "main" org.springframework.web.client.HttpServerErrorException: 500 null`

2. Zone B Asset did not pop up automatically after the Wind Turbine 3 data is launched

Appreciate your guys feedback on this.

Thanks.

**Comment by untilbit** [comment]
You are welcome @cjkini

**Comment by cjkini** [comment]
Thanks @untilbit.
I manage to solve no 2 already.

Any view on no 1 issue?

Regards

**Comment by untilbit** [comment]
@cjkini  What was the problem and how did you solve it.

**Comment by cjkini** [comment]
Hi @untilbit ,
The no 2, is mainly due to my mistake in publishing attribute and keys pair. :)

But, the program still stuck with error no 1. :+1: 


1.The SparkKafkaStreamingDemoMain code only runs for 15 minutes. The Spark Streaming context stop after that with this error :

Exception in thread "main" org.springframework.web.client.HttpServerErrorException: 401 null


Do u face the same problem?

Thanks

**Comment by cjkini** [comment]
This is the whole error Stack Trace


```
org.springframework.web.client.HttpClientErrorException: 401 null
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
	at org.thingsboard.samples.spark.RestClient.sendTelemetryToAsset(RestClient.java:111)
	at org.thingsboard.samples.spark.SparkKafkaStreamingDemoMain$StreamRunner.lambda$start$e3b46054$1(SparkKafkaStreamingDemoMain.java:99)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:254)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:254)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:254)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-06-11 10:45:00,666 [dispatcher-event-loop-0] INFO  o.a.spark.storage.BlockManagerInfo - Removed broadcast_5_piece0 on 192.168.1.109:46419 in memory (size: 2.5 KB, free: 347.1 MB)
2018-06-11 10:45:00,675 [main] INFO  o.a.s.s.scheduler.ReceiverTracker - ReceiverTracker stopped
2018-06-11 10:45:00,696 [main] INFO  o.a.s.s.scheduler.JobGenerator - Stopping JobGenerator immediately
2018-06-11 10:45:00,707 [Spark Context Cleaner] INFO  org.apache.spark.ContextCleaner - Cleaned shuffle 3
2018-06-11 10:45:00,711 [dispatcher-event-loop-3] INFO  o.a.spark.storage.BlockManagerInfo - Removed broadcast_6_piece0 on 192.168.1.109:46419 in memory (size: 3.2 KB, free: 347.1 MB)
2018-06-11 10:45:00,713 [main] INFO  o.a.s.streaming.util.RecurringTimer - Stopped timer for JobGenerator after time 1528685100000
2018-06-11 10:45:00,715 [dispatcher-event-loop-1] INFO  o.a.spark.storage.BlockManagerInfo - Removed broadcast_7_piece0 on 192.168.1.109:46419 in memory (size: 2.5 KB, free: 347.1 MB)
2018-06-11 10:45:00,724 [Spark Context Cleaner] INFO  org.apache.spark.ContextCleaner - Cleaned shuffle 1
2018-06-11 10:45:00,735 [dispatcher-event-loop-3] INFO  o.a.spark.storage.BlockManagerInfo - Removed broadcast_2_piece0 on 192.168.1.109:46419 in memory (size: 3.2 KB, free: 347.1 MB)
2018-06-11 10:45:00,748 [main] INFO  o.a.s.s.scheduler.JobGenerator - Stopped JobGenerator
2018-06-11 10:45:00,749 [dispatcher-event-loop-1] INFO  o.a.spark.storage.BlockManagerInfo - Removed broadcast_3_piece0 on 192.168.1.109:46419 in memory (size: 2.5 KB, free: 347.1 MB)
2018-06-11 10:45:00,751 [Spark Context Cleaner] INFO  org.apache.spark.ContextCleaner - Cleaned shuffle 2
2018-06-11 10:45:00,753 [dispatcher-event-loop-0] INFO  o.a.spark.storage.BlockManagerInfo - Removed broadcast_4_piece0 on 192.168.1.109:46419 in memory (size: 3.2 KB, free: 347.1 MB)
2018-06-11 10:45:00,757 [dispatcher-event-loop-1] INFO  o.a.spark.storage.BlockManagerInfo - Removed broadcast_1_piece0 on 192.168.1.109:46419 in memory (size: 2.5 KB, free: 347.1 MB)
2018-06-11 10:45:00,887 [main] INFO  o.a.s.s.scheduler.JobScheduler - Stopped JobScheduler
2018-06-11 10:45:00,956 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@66c83fc8{/streaming,null,UNAVAILABLE}
2018-06-11 10:45:00,957 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@40368a46{/streaming/batch,null,UNAVAILABLE}
2018-06-11 10:45:00,967 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@35ff8fc9{/static/streaming,null,UNAVAILABLE}
2018-06-11 10:45:00,977 [main] INFO  o.a.spark.streaming.StreamingContext - StreamingContext stopped successfully
2018-06-11 10:45:01,104 [main] INFO  o.s.jetty.server.ServerConnector - Stopped ServerConnector@7607263{HTTP/1.1}{0.0.0.0:4040}
2018-06-11 10:45:01,104 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@3e792ce3{/stages/stage/kill,null,UNAVAILABLE}
2018-06-11 10:45:01,105 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@7bfc3126{/jobs/job/kill,null,UNAVAILABLE}
2018-06-11 10:45:01,105 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@22ee2d0{/api,null,UNAVAILABLE}
2018-06-11 10:45:01,105 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@2c282004{/,null,UNAVAILABLE}
2018-06-11 10:45:01,106 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@7dd712e8{/static,null,UNAVAILABLE}
2018-06-11 10:45:01,106 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@10ad20cb{/executors/threadDump/json,null,UNAVAILABLE}
2018-06-11 10:45:01,106 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@26d10f2e{/executors/threadDump,null,UNAVAILABLE}
2018-06-11 10:45:01,106 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@70f43b45{/executors/json,null,UNAVAILABLE}
2018-06-11 10:45:01,106 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@106faf11{/executors,null,UNAVAILABLE}
2018-06-11 10:45:01,107 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@32c0915e{/environment/json,null,UNAVAILABLE}
2018-06-11 10:45:01,107 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@33aa93c{/environment,null,UNAVAILABLE}
2018-06-11 10:45:01,107 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@7692cd34{/storage/rdd/json,null,UNAVAILABLE}
2018-06-11 10:45:01,107 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@27a0a5a2{/storage/rdd,null,UNAVAILABLE}
2018-06-11 10:45:01,108 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@33d05366{/storage/json,null,UNAVAILABLE}
2018-06-11 10:45:01,108 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@47a64f7d{/storage,null,UNAVAILABLE}
2018-06-11 10:45:01,108 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@36dce7ed{/stages/pool/json,null,UNAVAILABLE}
2018-06-11 10:45:01,108 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@3a45c42a{/stages/pool,null,UNAVAILABLE}
2018-06-11 10:45:01,109 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@5af5def9{/stages/stage/json,null,UNAVAILABLE}
2018-06-11 10:45:01,109 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@57a4d5ee{/stages/stage,null,UNAVAILABLE}
2018-06-11 10:45:01,109 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@6e9c413e{/stages/json,null,UNAVAILABLE}
2018-06-11 10:45:01,109 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@15deb1dc{/stages,null,UNAVAILABLE}
2018-06-11 10:45:01,110 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@24b52d3e{/jobs/job/json,null,UNAVAILABLE}
2018-06-11 10:45:01,110 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@3301500b{/jobs/job,null,UNAVAILABLE}
2018-06-11 10:45:01,110 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@7561db12{/jobs/json,null,UNAVAILABLE}
2018-06-11 10:45:01,111 [main] INFO  o.s.j.server.handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@4acf72b6{/jobs,null,UNAVAILABLE}
2018-06-11 10:45:01,126 [main] INFO  org.apache.spark.ui.SparkUI - Stopped Spark web UI at http://192.168.1.109:4040
2018-06-11 10:45:02,207 [dispatcher-event-loop-2] INFO  o.a.s.MapOutputTrackerMasterEndpoint - MapOutputTrackerMasterEndpoint stopped!
2018-06-11 10:45:02,329 [main] INFO  o.a.spark.storage.memory.MemoryStore - MemoryStore cleared
2018-06-11 10:45:02,331 [main] INFO  o.apache.spark.storage.BlockManager - BlockManager stopped
2018-06-11 10:45:02,332 [main] INFO  o.a.spark.storage.BlockManagerMaster - BlockManagerMaster stopped
2018-06-11 10:45:02,344 [dispatcher-event-loop-2] INFO  o.a.s.s.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint - OutputCommitCoordinator stopped!
Exception in thread "main" org.springframework.web.client.HttpClientErrorException: 401 null
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:407)
2018-06-11 10:45:02,354 [main] INFO  org.apache.spark.SparkContext - Successfully stopped SparkContext
	at org.thingsboard.samples.spark.RestClient.sendTelemetryToAsset(RestClient.java:111)
	at org.thingsboard.samples.spark.SparkKafkaStreamingDemoMain$StreamRunner.lambda$start$e3b46054$1(SparkKafkaStreamingDemoMain.java:99)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:254)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:254)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:254)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-06-11 10:45:02,843 [Thread-1] INFO  o.a.spark.util.ShutdownHookManager - Shutdown hook called
2018-06-11 10:45:02,857 [Thread-1] INFO  o.a.spark.util.ShutdownHookManager - Deleting directory /tmp/spark-fb305b49-1a17-4def-860e-eb35e9fa12c8
```

**Comment by mp-loki** [comment]
401 means authentication error.
do you mean you start getting this error after 15 minutes of normal operation?

**Comment by untilbit** [comment]
I guess that it's not working in the first 15 mins.

**Comment by mp-loki** [comment]
Is the Username/Password set in RestClient correct? Can you log in to ThingsBoard GUI using those credentials?

**Comment by cjkini** [comment]
Yes @mp-loki
The spark program runs only for 15 minutes, then it will stop on it's own. 
We have to rerun again to get the data streaming

**Comment by mp-loki** [comment]
@cjkini I think there is a bug in the application when the token expires after 15 minutes. I'll try to fix it when I have time. In the meantime you can try to fix it on your side - just re-do login when you catch 401 error.
This application was developed as an example only, that's why I think we did not hit this error before.

**Comment by cjkini** [comment]
Hi @mp-loki.

Noted with thanks.

Your help is appreciated. Regards
