### ISSUE TITLE
[Bug] Things Board installation error

### ISSUE THREAD

**Issue by khandavally** [thingsboard/thingsboard#7113]
[gc.log](https://github.com/thingsboard/thingsboard/files/9371872/gc.log)
[install.log](https://github.com/thingsboard/thingsboard/files/9371873/install.log)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/9371874/thingsboard.log)

OS : Ubuntu 20.04
Database: Postgres SQL
Stand alone server setup 
Showing the error as per below 
sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard ::       (v3.3.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: java.lang.NullPointerException
        at org.thingsboard.server.service.component.AnnotationComponentDiscoveryService.registerRuleNodeComponents(AnnotationComponentDiscoveryService.java:113)
        at org.thingsboard.server.service.component.AnnotationComponentDiscoveryService.discoverComponents(AnnotationComponentDiscoveryService.java:235)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:233)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.NullPointerException: null
        at org.thingsboard.server.dao.sql.component.JpaBaseComponentDescriptorDao.saveIfNotExist(JpaBaseComponentDescriptorDao.java:72)
        at org.thingsboard.server.dao.sql.component.JpaBaseComponentDescriptorDao$$FastClassBySpringCGLIB$$fb0aa4b1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.thingsboard.server.dao.sql.component.JpaBaseComponentDescriptorDao$$EnhancerBySpringCGLIB$$ce5d11f9.saveIfNotExist(<generated>)
        at org.thingsboard.server.dao.component.BaseComponentDescriptorService.saveComponent(BaseComponentDescriptorService.java:55)
        at org.thingsboard.server.service.component.AnnotationComponentDiscoveryService.scanAndPersistComponent(AnnotationComponentDiscoveryService.java:182)
        at org.thingsboard.server.service.component.AnnotationComponentDiscoveryService.registerRuleNodeComponents(AnnotationComponentDiscoveryService.java:96)
        ... 11 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

Please help to advise.

**Comment by trikimiki** [comment]
From logs it seems like there is an encoding issue.

Can you run these commands and post the results?

```
psql -U postgres -h localhost -c "\l"

psql -U postgres -h localhost -d thingsboard -c "show server_encoding;"

psql -U postgres -h localhost -d thingsboard -c "show client_encoding;"
```

**Comment by khandavally** [comment]
psql -U postgres -h localhost -c "\l"
Password for user postgres:
                              List of databases
    Name     |  Owner   | Encoding | Collate | Ctype |   Access privileges
-------------+----------+----------+---------+-------+-----------------------
 postgres    | postgres | LATIN1   | en_US   | en_US |
 template0   | postgres | LATIN1   | en_US   | en_US | =c/postgres          +
             |          |          |         |       | postgres=CTc/postgres
 template1   | postgres | LATIN1   | en_US   | en_US | =c/postgres          +
             |          |          |         |       | postgres=CTc/postgres
 thingsboard | postgres | LATIN1   | en_US   | en_US |
(4 rows)

psql -U postgres -h localhost -d thingsboard -c "show server_encoding;"
Password for user postgres:
 server_encoding
-----------------
 LATIN1
(1 row)

psql -U postgres -h localhost -d thingsboard -c "show client_encoding;"
Password for user postgres:
 client_encoding
-----------------
 UTF8
(1 row)

**Comment by trikimiki** [comment]
You need to recreate a DB using UTF8 encoding. If you don't have anything important running on your Postgres, you can do the following:

1. Run `pg_lsclusters` and check what Postgres version you are running. In this example, the version is `12`:
```
Ver Cluster Port Status Owner    Data directory              Log file
12  main    5432 online postgres /var/lib/postgresql/12/main /var/log/postgresql/postgresql-12-main.log
```
2. Drop your current DB (don't forget to change `12` to your version):
```
pg_dropcluster --stop 12 main
```
3. Create a DB with UTF8 encoding (don't forget to change `12` to your version):
```
pg_createcluster --start -e UTF-8 12 main
```
4. Repeat those installation steps:

> Once PostgreSQL is installed you may want to create a new user or set the password for the the main user. The instructions below will help to set the password for main postgresql user
```
