### ISSUE TITLE
Thingsboard 3.4.0 to 3.4.1 upgrade error

### ISSUE THREAD

**Issue by MCPule** [thingsboard/thingsboard#7147]
**Component**

 * Installation

**Description**
Installation error when upgrading from version 3.4.0 to 3.4.1

**Environment**

 * OS:  Ubuntu 22.04.1 LTS
 * ThingsBoard: 3.4.0
 * Browser: Chrome

-----------------------------------------------------------------------------------------------------------------------------------------------
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: no partition of relation "error_event" found for row
  Detail: Partition key of the failing row contains (ts) = (1589794897763).
  Where: SQL statement "INSERT INTO error_event
    SELECT id,
           tenant_id,
           ts,
           entity_id,
           body ->> 'server',
           body ->> 'method',
           body ->> 'error'
    FROM
    (select id, tenant_id, ts, entity_id, to_safe_json(body) as body
     FROM event WHERE ts >= start_ts_in_ms and ts < end_ts_in_ms AND event_type = 'ERROR' AND to_safe_json(body) ->> 'server' IS NOT NULL
    ) safe_event
    ON CONFLICT DO NOTHING"
PL/pgSQL function migrate_regular_events(bigint,bigint,integer) line 51 at SQL statement
        at org.thingsboard.server.dao.sql.event.SqlEventCleanupRepository.callMigrateFunction(SqlEventCleanupRepository.java:106)
        at org.thingsboard.server.dao.sql.event.SqlEventCleanupRepository.callMigrateFunctionByPartitions(SqlEventCleanupRepository.java:90)
        at org.thingsboard.server.dao.sql.event.SqlEventCleanupRepository.migrateEvents(SqlEventCleanupRepository.java:59)
        at org.thingsboard.server.dao.sql.event.SqlEventCleanupRepository$$FastClassBySpringCGLIB$$c5eb007e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at org.thingsboard.server.dao.sql.event.SqlEventCleanupRepository$$EnhancerBySpringCGLIB$$1ce8a57f.migrateEvents(<generated>)
        at org.thingsboard.server.dao.sql.event.JpaBaseEventDao.migrateEvents(JpaBaseEventDao.java:266)
        at org.thingsboard.server.dao.event.BaseEventService.migrateEvents(BaseEventService.java:139)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:176)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:227)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.postgresql.util.PSQLException: ERROR: no partition of relation "error_event" found for row
  Detail: Partition key of the failing row contains (ts) = (1589794897763).
  Where: SQL statement "INSERT INTO error_event
    SELECT id,
           tenant_id,
           ts,
           entity_id,
           body ->> 'server',
           body ->> 'method',
           body ->> 'error'
    FROM
    (select id, tenant_id, ts, entity_id, to_safe_json(body) as body
     FROM event WHERE ts >= start_ts_in_ms and ts < end_ts_in_ms AND event_type = 'ERROR' AND to_safe_json(body) ->> 'server' IS NOT NULL
    ) safe_event
    ON CONFLICT DO NOTHING"
PL/pgSQL function migrate_regular_events(bigint,bigint,integer) line 51 at SQL statement
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.thingsboard.server.dao.sql.event.SqlEventCleanupRepository.callMigrateFunction(SqlEventCleanupRepository.java:102)
        ... 25 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!

**Comment by trikimiki** [comment]
It seems like the timestamp for some specific error event is out of bounds of migrating procedure. It is either a bug or invalid data on this particular event.

You can workaround this issue by truncating the table "event" before the upgrade. You will only lose your debug data as it only stores statistics, lifecycle, and debug events.

**Comment by MCPule** [comment]
@trikimiki, thanks for your response.

However, I get the following error when I try to truncate the tables "event" or "error_event":

---------------------------------------------------------------------------------------------------------------------------------

postgres=# TRUNCATE TABLE event;
ERROR:  relation "event" does not exist
postgres=# TRUNCATE TABLE error_event;
ERROR:  relation "error_event" does not exist
postgres=#

**Comment by trikimiki** [comment]
I think you are connected to the wrong DB: `postgres=#`
Try connecting to "thingsboard" before executing the query:
```
\c thingsboard
```

**Comment by MCPule** [comment]
@trikimiki, thanks for your support. We managed to upgrade with success.
