### ISSUE TITLE
Running java jar file getting exception in thingsboard

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#726]
Hi,
       Whenever i'm running this java -jar thingsboard-1.4.0-SNAPSHOT-boot.jar from thingsboard/application/target/ directory  getting the following error . 

**ERROR :** 

Error while storing properties to /homefolder/thingsboard/application/target/Californium.properties

java.io.FileNotFoundException: Californium.properties (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_151]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_151]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_151]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_151]
	at java.io.FileWriter.<init>(FileWriter.java:90) ~[na:1.8.0_151]
	at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:218) [californium-core-1.0.2.jar!/:na]
	at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:205) [californium-core-1.0.2.jar!/:na]
	at org.eclipse.californium.core.network.config.NetworkConfig.createStandardWithFile(NetworkConfig.java:170) [californium-core-1.0.2.jar!/:na]
	at org.eclipse.californium.core.network.config.NetworkConfig.getStandard(NetworkConfig.java:125) [californium-core-1.0.2.jar!/:na]
	at org.eclipse.californium.core.CoapServer.<init>(CoapServer.java:115) [californium-core-1.0.2.jar!/:na]
	at org.thingsboard.server.transport.coap.CoapTransportService.init(CoapTransportService.java:75) [coap-1.4.0-SNAPSHOT.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) [spring-beans-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.3.RELEASE.jar!/:1.4.3.RELEASE]
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:36) [classes!/:1.4.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [thingsboard-1.4.0-SNAPSHOT-boot.jar:1.4.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [thingsboard-1.4.0-SNAPSHOT-boot.jar:1.4.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [thingsboard-1.4.0-SNAPSHOT-boot.jar:1.4.0-SNAPSHOT]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521) [thingsboard-1.4.0-SNAPSHOT-boot.jar:1.4.0-SNAPSHOT]

**Comment by Strauteka** [comment]
Similar problem running Docker Image thingsboard/tb-postgres:3.1.1

```
2020-10-07 05:04:27,837 [main] INFO  o.e.c.c.network.config.NetworkConfig - Storing standard properties in file Californium.properties  
tb_1        | 2020-10-07 05:04:27,837 [main] WARN  o.e.c.c.network.config.NetworkConfig - Error while storing properties to /Californium.properties  
tb_1        | java.io.FileNotFoundException: Californium.properties (Permission denied)  
tb_1        |   at java.io.FileOutputStream.open0(Native Method)  
tb_1        |   at java.io.FileOutputStream.open(FileOutputStream.java:270)  
tb_1        |   at java.io.FileOutputStream.<init>(FileOutputStream.java:213)  
tb_1        |   at java.io.FileOutputStream.<init>(FileOutputStream.java:162)  
tb_1        |   at java.io.FileWriter.<init>(FileWriter.java:90)  
tb_1        |   at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:218)  
tb_1        |   at org.eclipse.californium.core.network.config.NetworkConfig.store(NetworkConfig.java:205)  
tb_1        |   at org.eclipse.californium.core.network.config.NetworkConfig.createStandardWithFile(NetworkConfig.java:170)  
tb_1        |   at org.eclipse.californium.core.network.config.NetworkConfig.getStandard(NetworkConfig.java:125)  
tb_1        |   at org.eclipse.californium.core.CoapServer.<init>(CoapServer.java:115)  
tb_1        |   at org.thingsboard.server.transport.coap.CoapTransportService.init(CoapTransportService.java:49)  
tb_1        |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
tb_1        |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  
tb_1        |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
tb_1        |   at java.lang.reflect.Method.invoke(Method.java:498)  
tb_1        |   at  
org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)  
tb_1        |   at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.jav  
```

Directory `./` dont have premissions to store files for user `thingsboard` owned by `root`

**fix:** Create my own docker file with content:
```Dockerfile
# Removing error [main] WARN  o.e.c.c.network.config.NetworkConfig - Error while storing properties to /Californium.properties
FROM thingsboard/tb-postgres:3.1.1
USER root
RUN touch Californium.properties
RUN chmod 777 ./Californium.properties
USER  thingsboard
```

**Comment by Ultrazombie** [comment]
Hello @srimathselva
Is your problem still relevant to the latest ThignsBoard version?
