### ISSUE TITLE
[Bug] Sometimes telemetry data pushed via Rest /api/v1/token/telemetry is not treated by backend in a micro-service deployment

### ISSUE THREAD

**Issue by bilelkhedira** [thingsboard/thingsboard#7274]
Hello,

**Bug description**
we are encountering a random behavior, 500 HTTP status while pushing data via Rest API /api/v1/token/telemetry is not treated by tb-node

**Your Server Environment**
* Oracle cloud, K8 platform as a service
* OS: Linux 7.9
* ThingsBoard Version 3.3.2
* micro-service deployment

* Connectivity
  * HTTP

**Exception log trace in the transport microservice **
```
ard.server.queue.common.DefaultTbQueueMsgHeaders@776ca9dc)
2022-09-07 08:24:38,049 [queue-scheduler-2-thread-1] INFO  o.t.s.q.u.DefaultTbApiUsageClient - Report statistics for: 1 tenants
2022-09-07 08:24:38,897 [tb-queue-request-template-tb_transport.api.responses.tb-http-transport-7c9bb9c6cd-bzcq8-3-thread-1] WARN  o.t.s.q.c.DefaultTbQueueRequestTemplate - Request timeout detected, currentNs [1871871251413059], ResponseMetaData{submitTime=1871856928915156, calculatedExpTime=1871866928915156, deltaMs=10000000000, expTime=1871866928915156, future=SettableFuture@594644ef[status=PENDING]}, key [64d297a5-e4a6-4299-abeb-66b08cb7f0d5]
2022-09-07 08:24:38,897 [DefaultTransportService-26-10] WARN  o.t.s.t.http.DeviceApiController - Failed to process request
java.util.concurrent.TimeoutException: null
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.setTimeoutException(DefaultTbQueueRequestTemplate.java:163)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.lambda$tryCleanStaleRequests$0(DefaultTbQueueRequestTemplate.java:132)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.tryCleanStaleRequests(DefaultTbQueueRequestTemplate.java:128)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:117)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Thanks in advance

**Comment by bilelkhedira** [comment]
For more details we are receiving ~ 1000 messages/minute

**Comment by Ultrazombie** [comment]
This is similar to the Kafka problem, but it's too hard to say for sure - we need more information. the ticket is probably no longer relevant and I will close it. please create new ticket - with more details (describe node's/pods/configfiles)
