### ISSUE TITLE
[Bug] Kafka producer node doesn't accept metadata attributes in bootstrap servers and other properties fields

### ISSUE THREAD

**Issue by thirstyfish** [thingsboard/thingsboard#7301]
**Describe the bug**

We're trying to parameterise the kafka producer rule chain node so the target kafka servers and the api key is not hardcoded in the rule node. We're using confluent cloud as the target, so sasl.jaas.config is being used.

We're storing the required parameters in server-side attributes on the tenant that the rule chain loads into metadata before the kafka producer node is reached.

However, it seems that only the topic pattern input is able to use metadata attributes.

When metadata attributes are used in either the Bootstrap servers or Other properties inputs (where the sasl.jaas.config resides), the rule chain fails to start with the below error messages.

This functionality would be needed to prevent exposing sensitive data to tenants and to be able to use the git sync feature to promote rule chains in between environments without having to manually change hardcoded values.

Error related to metadata key in Kafka Bootstrap servers input:

```
org.thingsboard.server.actors.TbRuleNodeUpdateException: Failed to update rule node
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onUpdate(RuleNodeActorMessageProcessor.java:83)
	at org.thingsboard.server.actors.service.ComponentActor.onComponentLifecycleMsg(ComponentActor.java:108)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:58)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:45)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:142)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.thingsboard.rule.engine.api.TbNodeException: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.thingsboard.rule.engine.kafka.TbKafkaNode.init(TbKafkaNode.java:111)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:154)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:62)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onUpdate(RuleNodeActorMessageProcessor.java:81)
	... 10 more
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:439)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:289)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:316)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:301)
	at org.thingsboard.rule.engine.kafka.TbKafkaNode.init(TbKafkaNode.java:102)
	... 13 more
Caused by: org.apache.kafka.common.config.ConfigException: Invalid url in bootstrap.servers: ${kafkaBootstrapServers}
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:59)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:413)
	... 17 more
```

Error related to metadata key in sasl.jaas.config:

```
org.thingsboard.rule.engine.api.TbNodeException: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.thingsboard.rule.engine.kafka.TbKafkaNode.init(TbKafkaNode.java:111)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:154)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:62)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:65)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$tryInit$1(TbActorMailbox.java:82)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:439)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:289)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:316)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:301)
	at org.thingsboard.rule.engine.kafka.TbKafkaNode.init(TbKafkaNode.java:102)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Login module control flag is not available in the JAAS config
	at org.apache.kafka.common.security.JaasConfig.loginModuleControlFlag(JaasConfig.java:85)
	at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:111)
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:88)
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:82)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:167)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:484)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:428)
	... 16 more

```

**Your Server Environment**
TB 3.4.1 running in self-hosted k8s

**Expected behavior**
The kafka producer rule chain node should accept metadata attributes as values in the bootstrap servers and Other properties inputs

**Screenshots**
<img width="952" alt="Screen Shot 2022-09-20 at 15 59 18" src="https://user-images.githubusercontent.com/6710477/191178928-04558c12-5808-4012-8523-aa5488378852.png">

**Comment by Raven888888** [comment]
I think this is more like a improvement rather than bug. I am also looking for similar thing.

**Comment by thirstyfish** [comment]
Yeah, you are right. Also when looking at the source, the bootstrap servers and the sasl.jaas.config are needed to instantiate the Kafka producer, so can't extract that from metadata.

In contrast to this, the topic can be extracted from each incoming message:
https://github.com/thingsboard/thingsboard/blob/da4c74287216fc6962c74f084c2eedebf06e1a64/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNode.java#L99

So I'd revise this to a feature request and instead it'd be great if an environment variable could be given as value. This way the value is readily available when the producer is created, but will nicely work with the version control across environments.

Happy to contribute to a PR to get this in if anyone can point me to an example?
Thanks

**Comment by sudhirbits** [comment]
Would be useful improvement to have. Watching on this.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion https://github.com/thingsboard/thingsboard/discussions/15951 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
