### ISSUE TITLE
Runtime error when trying to retrieve previous telemetry value in rule chain

### ISSUE THREAD

**Issue by merrittholmes7** [thingsboard/thingsboard#7314]
Using TB Cloud: 
<img width="1680" alt="Screenshot 2022-09-21 at 17 53 04" src="https://user-images.githubusercontent.com/58036630/191565293-83c1c9d2-1d43-4aa4-adde-88965ff92d95.png">
<img width="1680" alt="Screenshot 2022-09-21 at 17 52 51" src="https://user-images.githubusercontent.com/58036630/191565307-04660e89-5960-4971-b35d-68e3d3db8977.png">
When using the Enrichment - originator attributes node, to retrieve the previous value I am getting this error:

java.lang.RuntimeException: The following attribute/telemetry keys is not present in the DB: 
	[LATEST_TS]:[1]

	at org.thingsboard.rule.engine.metadata.TbAbstractGetAttributesNode.reportFailures(TbAbstractGetAttributesNode.java:226)
	at org.thingsboard.rule.engine.metadata.TbAbstractGetAttributesNode.lambda$safePutAttributes$2(TbAbstractGetAttributesNode.java:117)
	at org.thingsboard.common.util.DonAsynchron$1.onSuccess(DonAsynchron.java:55)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1080)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by OzyOzk** [comment]
You don't need to use template literals in the originator attributes node. It should be motion_detected, not ${motion_detected}.

**Comment by merrittholmes7** [comment]
Thanks. I should have updated the message as I came to realise this. The hint can be interpreted in a few ways so might need to tighten up the language to stop people like me misinterpreting them. On 22 Sep 2022 17:13, Ozyoz ***@***.***> wrote:
You don't need to use template literals in the originator attributes node. It should be motion_detected, not ${motion_detected}.
