### ISSUE TITLE
[Question] Upgrade from 3.1.1 to 3.4.1 problems

### ISSUE THREAD

**Issue by ljubomirsinadinovski** [thingsboard/thingsboard#7374]
**Component**

 * Installation

**Description**
Our company server had 3.1.1 version installed with previous setup and config (by previous employees), I am using first time Thingsboard. The problem was that our UI will drop in a week and restart was required, as I read through the other Git Issues I was supposed to upgrade. First I upgraded the openJDK version and then I started upgrading version by version (download and install as you recommend on your website). On the end the installation was not working and I couldn't access Thingsboard. We also have purchased licenses as well. The database is still populated with the old data (PSQL), but it seems I am missing some columns. If you can please tell me exactly which tables to alter. I am confused because in terminal output gives external_id and in log file its adminseei0_.tenant_id

Terminal Output:
```
 sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo -debug
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard ::       (v3.4.1)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Unexpected error during ThingsBoard installation!
org.postgresql.util.PSQLException: FEHLER: Spalte »external_id« existiert nicht
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.executeQueryFromFile(SqlAbstractDatabaseSchemaService.java:82)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseIndexes(SqlAbstractDatabaseSchemaService.java:74)
        at org.thingsboard.server.service.install.SqlEntityDatabaseSchemaService.createDatabaseIndexes(SqlEntityDatabaseSchemaService.java:37)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:66)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:247)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!
ketag@srvketag40:~$  sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo -debug
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.executeQueryFromFile(SqlAbstractDatabaseSchemaService.java:82)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseIndexes(SqlAbstractDatabaseSchemaService.java:74)
        at org.thingsboard.server.service.install.SqlEntityDatabaseSchemaService.createDatabaseIndexes(SqlEntityDatabaseSchemaService.java:37)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:66)
        at org.thingsboard.server.service.install.SqlAbstractDatabaseSchemaService.createDatabaseSchema(SqlAbstractDatabaseSchemaService.java:57)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:247)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!
```

**Environment**

 * OS:   Ubuntu 18.04.5 LTS
 * ThingsBoard: 3.4.1
 * java -version output:
```
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu118.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu118.04, mixed mode, sharing)
```

Config file /etc/thingsboard/conf/thingsboard.conf:
```

export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/data"
export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/thingsboard/gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError"
export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
export LOG_FILENAME=thingsboard.out
export LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions
export SQL_DATA_FOLDER=/usr/share/thingsboard/data/sql

# DB Configuration
export DATABASE_TS_TYPE=sql
export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/thingsboard
export SPRING_DATASOURCE_USERNAME=postgres
export SPRING_DATASOURCE_PASSWORD=xxxxxxx
export SPRING_DATASOURCE_MAXIMUM_POOL_SIZE=5
# Specify partitioning size for timestamp key-value storage. Allowed values: DAYS, MONTHS, YEARS, INDEFINITE.
export SQL_POSTGRES_TS_KV_PARTITIONING=MONTHS
```

Result from: cat /var/log/thingsboard/thingsboard.log | grep ERROR
```
 ERROR o.h.e.jdbc.spi.SqlExceptionHelper - FEHLER: Spalte adminsetti0_.tenant_id existiert nicht
2022-10-04 13:54:18,316 [main] ERROR o.s.b.w.e.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'thingsboardSecurityConfiguration': Unsatisfied dependency expressed through field 'oauth2AuthenticationSuccessHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'oauth2AuthenticationSuccessHandler' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-INF/classes!/org/thingsboard/server/service/security/auth/oauth2/Oauth2AuthenticationSuccessHandler.class]: Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultSystemSecurityService': Unsatisfied dependency expressed through field 'mailService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultMailService': Invocation of init method failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
2022-10-04 13:54:18,447 [main] ERROR o.s.boot.SpringApplication - Application run failed
```

Thank you, and if you require any further info please don't hesitate to ask for it.

**Comment by ljubomirsinadinovski** [comment]
> As I understand you try to directly upgrade from 3.1 to 3.4, right? You should upgrade from version to version without skipping

nope, i upgraded version by version. My upgrade step (for every version were):
1.  would download the newest version with wget, e.g. wget `https://github.com/thingsboard/thingsboard/releases/download/v3.4.1/thingsboard-3.4.1.deb`
2. run the install command `sudo dpkg -i thingsboard-3.4.1.deb`

i did the same for all version listed here `https://thingsboard.io/docs/user-guide/install/upgrade-instructions/` that are bigger than 3.1.1 one by one with the 2 commands for each version i explained above without testing in between 

```
and then I started upgrading version by version (download and install as you recommend on your website)
```

**Comment by mde2017** [comment]
As the error messages states, the column _external_id_ is missing. This column is used in multiple tables and was introduced with the Version control feature. Probably there were issues while updating the Postgresql tables during installation process.

To fix the issue, try running the sql script located in the installation directory at \thingsboard\data\upgrade\3.3.4

**Comment by ljubomirsinadinovski** [comment]
I re-opened this because my colleague detected that thingsboard isn't working as previously with trying to login into customer account flow. In addition I am including the images and the logs files as you requested before. Please do not hesitate to ask for further information or logs.


![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/24614182/194562352-878e6647-017d-4fb6-9bc0-cb309460fb32.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/24614182/194562359-9f875138-dc00-479b-b17e-608f3c93d2b6.png)

The install log and the schema:
[install.log](https://github.com/thingsboard/thingsboard/files/9734173/install.log)
[my-schema.sql.txt](https://github.com/thingsboard/thingsboard/files/9734201/my-schema.sql.txt)

**Comment by trikimiki** [comment]
I see a few errors in your install log - they mean that some specific tables were not updated, and thus "SQLGrammarError" appears on the UI.
While I am checking the schema, please reproduce this error (multiple times with different "scenarios" if possible) and send your log file: `/var/log/thingsboard/thingsboard.log`. It should point a specific table(s) with issues.

**Comment by ljubomirsinadinovski** [comment]
> I see a few errors in your install log - they mean that some specific tables were not updated, and thus "SQLGrammarError" appears on the UI. While I am checking the schema, please reproduce this error (multiple times with different "scenarios" if possible) and send your log file: `/var/log/thingsboard/thingsboard.log`. It should point a specific table(s) with issues.

Other than the 2 it seems OAuth2 related errors
[thingsboardLog.txt](https://github.com/thingsboard/thingsboard/files/9753817/thingsboardLog.txt)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/24614182/195058288-aa982481-7bcb-4892-9e1c-803101e846bd.png)

**Comment by trikimiki** [comment]
I see a number of differences, and I suspect that you have used Professional Edition (as I can see data converters table, entity groups, schedulers, etc). Note that you have updated as if you were using Community Edition.

If you were indeed using Professional Edition before, I recommend contacting our managers via [this form](https://thingsboard.io/docs/contact-us/), as your license key might have expired (and you cannot upgrade in this case).

**Comment by ljubomirsinadinovski** [comment]
> I see a number of differences, and I suspect that you have used Professional Edition (as I can see data converters table, entity groups, schedulers, etc). Note that you have updated as if you were using Community Edition.
> 
> If you were indeed using Professional Edition before, I recommend contacting our managers via [this form](https://thingsboard.io/docs/contact-us/), as your license key might have expired (and you cannot upgrade in this case).

Thank you for your kind answer. I think we had PE version, but when I started the upgrade process I wasn't sure. Therefore I did the upgrade from the Community Editions (starting from 3.1.1 and above) and when I reached the latest version, I just downloaded the latest PE additionally and installed it.

Yes, I did use the contact from with link reference to this thread, but nobody has replied yet

**Comment by trikimiki** [comment]
If you have a DB backup of v3.1.1, you should re-run all upgrades using Professional Edition packages.
Still, as I mentioned before, your license might be outdated and don't support newer version, so please wait until you get contacted.

**Comment by ljubomirsinadinovski** [comment]
> If you have a DB backup of v3.1.1, you should re-run all upgrades using Professional Edition packages. Still, as I mentioned before, your license might be outdated and don't support newer version, so please wait until you get contacted.

I do have the backup thanks, I will wait little bit to get contacted first. Thank you for your devotion, will post an update here when I get to a solution

**Comment by ljubomirsinadinovski** [comment]
> If you have a DB backup of v3.1.1, you should re-run all upgrades using Professional Edition packages. Still, as I mentioned before, your license might be outdated and don't support newer version, so please wait until you get contacted.

Hey, so I didn't get contacted back by your managers, however I reverted the backup (which was fully functional) and started again with the step-by-step upgrades using PE... i got stuck when upgrading from version `3.3.0pe.deb` to `3.3.1pe.deb`
This is what I get

```sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.3.0
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard Professional Edition ::       (v3.3.1PE)
 ===================================================

Warning: Nashorn engine is planned to be removed from a future JDK release
Starting ThingsBoard Upgrade from version 3.3.0 ...
Upgrading ThingsBoard from version 3.3.0 to 3.3.1 ...
Upgrading ThingsBoard from version 3.3.1 to 3.3.1PE ...
Updating schema ...
Schema updated.
Updating data from version 3.3.1 to 3.3.1PE ...
Unexpected error during ThingsBoard installation!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:281)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:531)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:154)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy152.findByTenantId(Unknown Source)
        at org.thingsboard.server.dao.sql.edge.JpaEdgeDao.findEdgesByTenantId(JpaEdgeDao.java:78)
        at org.thingsboard.server.dao.sql.edge.JpaEdgeDao$$FastClassBySpringCGLIB$$d3fa571b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.thingsboard.server.dao.sql.edge.JpaEdgeDao$$EnhancerBySpringCGLIB$$b6e89b33.findEdgesByTenantId(<generated>)
        at org.thingsboard.server.dao.edge.EdgeServiceImpl.findEdgesByTenantId(EdgeServiceImpl.java:214)
        at org.thingsboard.server.dao.edge.EdgeServiceImpl$$FastClassBySpringCGLIB$$c596e17.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.thingsboard.server.dao.edge.EdgeServiceImpl$$EnhancerBySpringCGLIB$$8b81dfe3.findEdgesByTenantId(<generated>)
        at org.thingsboard.server.service.install.update.EntityGroupAllPaginatedUpdater.findEntities(EntityGroupAllPaginatedUpdater.java:95)
        at org.thingsboard.server.service.install.update.EntityGroupAllPaginatedUpdater.findEntities(EntityGroupAllPaginatedUpdater.java:60)
        at org.thingsboard.server.service.install.update.PaginatedUpdater.updateEntities(PaginatedUpdater.java:50)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService$7.updateEntity(DefaultDataUpdateService.java:550)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService$7.updateEntity(DefaultDataUpdateService.java:501)
        at org.thingsboard.server.service.install.update.PaginatedUpdater.updateEntities(PaginatedUpdater.java:52)
        at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:252)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:229)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2297)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
        at org.hibernate.loader.Loader.doQuery(Loader.java:948)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
        at org.hibernate.loader.Loader.doList(Loader.java:2843)
        at org.hibernate.loader.Loader.doList(Loader.java:2825)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2657)
        at org.hibernate.loader.Loader.list(Loader.java:2652)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1414)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1636)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1604)
        at org.hibernate.query.Query.getResultList(Query.java:165)
        at jdk.internal.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:409)
        at com.sun.proxy.$Proxy229.getResultList(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:177)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        ... 34 common frames omitted
Caused by: org.postgresql.util.PSQLException: FEHLER: Spalte edgeentity0_.cloud_endpoint existiert nicht
  Position: 127
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
        ... 67 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
```

**Comment by trikimiki** [comment]
The `could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet` error is generic, and you always should look for more specifics in your `thingsboard.log file`

If this is still relevant - please feel free to reopen with logs attached.
