### ISSUE TITLE
ThingsBoard Build error at UI

### ISSUE THREAD

**Issue by Hecky30** [thingsboard/thingsboard#7513]
**Component**

 * UI

**Description**
While Building ThinbsBoard, getting error while compiling the UI module as follows:
[error] HookWebpackError: EIO
    at makeWebpackError (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:2515:12
    at eval (eval at create (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:98:1)
-- inner error --
Error: EIO
    at new Worker (node:internal/worker:259:19)
    at ThreadPool._addNewWorker (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\piscina\dist\src\index.js:395:24)
    at ThreadPool._ensureMinimumWorkers (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\piscina\dist\src\index.js:390:18)
    at new ThreadPool (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\piscina\dist\src\index.js:385:14)
    at new Piscina (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\piscina\dist\src\index.js:722:45)
    at C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\@angular-devkit\build-angular\src\webpack\plugins\javascript-optimizer-plugin.js:118:36
    at fn (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:508:19)
    at _next3 (eval at create (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:89:17)
    at eval (eval at create (C:\Users\Administrator\OneDrive\Desktop\Thingsboard\ui-ngx\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:111:1)

**Environment**

 * OS:  Windows 10 64 bit
 * ThingsBoard: 3.4.2
 * Cloned from GitHub

**Comment by trikimiki** [comment]
If the problem described in this issue can be reproduced in the latest version, please create a new ticket with a concise description of the problem.
