### ISSUE TITLE
Multiple queue errors while using OCI streaming

### ISSUE THREAD

**Issue by guidin360** [thingsboard/thingsboard#7516]
Although OCI Streaming is not natively implemented in thingsboard, i'm using the Confluent cloud options in thingsboard.conf, the streams are created and i can see them in OCI, but i get the following errors:

`2022-11-01 07:46:38,520 [tb-rule-engine-notifications-consumer-39-thread-1] WARN  o.t.s.s.q.p.AbstractConsumerService - Failed to obtain notifications from queue.
java.lang.IllegalStateException: Unexpected error code 4 while fetching at offset 0 from topic-partition tb_rule_engine.notifications.thingsboard1-0
	at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1379)
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:658)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1215)
	at org.thingsboard.server.queue.kafka.TbKafkaConsumerTemplate.doPoll(TbKafkaConsumerTemplate.java:91)
	at org.thingsboard.server.queue.common.AbstractTbQueueConsumerTemplate.poll(AbstractTbQueueConsumerTemplate.java:101)
	at org.thingsboard.server.service.queue.processing.AbstractConsumerService.lambda$launchNotificationsConsumer$4(AbstractConsumerService.java:118)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

`2022-11-01 07:37:08,660 [tb-queue-request-template-tb_transport.api.responses.thingsboard1-7-thread-1] WARN  o.t.s.q.c.DefaultTbQueueRequestTemplate - Failed to obtain and process responses from queue. Going to sleep 23262582ns
java.lang.IllegalStateException: Unexpected error code 4 while fetching at offset 0 from topic-partition tb_transport.api.responses.thingsboard1-0
	at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1379)
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:658)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1242)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1215)
	at org.thingsboard.server.queue.kafka.TbKafkaConsumerTemplate.doPoll(TbKafkaConsumerTemplate.java:91)
	at org.thingsboard.server.queue.common.AbstractTbQueueConsumerTemplate.poll(AbstractTbQueueConsumerTemplate.java:101)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.doPoll(DefaultTbQueueRequestTemplate.java:152)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:115)
	at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:103)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

thingsboard.conf:

`export TB_QUEUE_TYPE=kafka
export TB_QUEUE_KAFKA_USE_CONFLUENT_CLOUD=true
export TB_KAFKA_SERVERS=cell-1.streaming.eu-frankfurt-1.oci.oraclecloud.com:9092
export TB_QUEUE_KAFKA_CONFLUENT_SASL_MECHANISM=PLAIN
export TB_QUEUE_KAFKA_CONFLUENT_SASL_JAAS_CONFIG="org.apache.kafka.common.security.plain.PlainLoginModule required username='<<username>>' password='<<token>>"
export TB_QUEUE_KAFKA_CONFLUENT_SECURITY_PROTOCOL=SASL_SSL`

Thanks!!

**Comment by trikimiki** [comment]
I assume that these parameters were not correctly implemented at the time (2022ish releases)
```
TB_QUEUE_KAFKA_CONFLUENT_SASL_MECHANISM
TB_QUEUE_KAFKA_CONFLUENT_SASL_JAAS_CONFIG
TB_QUEUE_KAFKA_CONFLUENT_SECURITY_PROTOCOL
```
We did not test OCI Streaming with ThingsBoard, but according to the docs, it is Kafka-compatible. I think newer releases should work with the `thingsboard.conf` described in the issue.
If you are experiencing a similar problem with the recent version(s), please feel free to create a new issue.
