### ISSUE TITLE
[Question] how can i specify PEM file for Cassandra Connexion

### ISSUE THREAD

**Issue by ysimonx** [thingsboard/thingsboard#7574]
**Thingsboard 3.4.1**

 * Installation

**Description**
I am trying to connect a CE thingsboard instance to a remote cassandra database
this remote database can be accessed only with a .pem certfile

I managed to connect this cassandra database thanks to cqlsh command line
my .cassandra/cqlshrc file contains

```
[authentication]
username = ***
password = *** 

[connection]
hostname = cassandra-....net
port = 2...4 
factory = cqlshlib.ssl.ssl_transport_factory

[ssl]
certfile = /etc/thingsboard/conf/ca-cassandra-ovh-eurevia.pem
validate = true

```

i tried to specify the same configuration in thingsboard.conf

```
export CASSANDRA_CLUSTER_NAME=Thingsboard Cluster
export CASSANDRA_KEYSPACE_NAME=***
export CASSANDRA_URL=cassandra-....net:2...4
export CASSANDRA_USE_CREDENTIALS=true
export CASSANDRA_USERNAME=***
export CASSANDRA_PASSWORD=***
export CASSANDRA_USE_SSL=true
export CASSANDRA_SSL_KEY_STORE=/etc/thingsboard/conf/ca-cassandra-ovh-eurevia.pem

```

but when trying to load the demo data, i have an error

I think I have to convert the pem file to both key_store and trust_store
 
 or 
 
how can i specify this PEM file for this cassandra connexion please ?

```
Unexpected error during ThingsBoard installation!
java.lang.IllegalArgumentException: Error instantiating class DefaultSslEngineFactory (specified by advanced.ssl-engine-factory.class): Cannot initialize SSL Context
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:253)
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslEngineFactory(DefaultDriverContext.java:417)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.lambda$new$4(DefaultDriverContext.java:285)
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslEngineFactory(DefaultDriverContext.java:783)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildSslHandlerFactory(DefaultDriverContext.java:472)
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getSslHandlerFactory(DefaultDriverContext.java:849)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.init(DefaultSession.java:348)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.access$1100(DefaultSession.java:300)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.lambda$init$0(DefaultSession.java:146)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Cannot initialize SSL Context
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:74)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246)
	... 18 common frames omitted
Caused by: java.io.IOException: Invalid keystore format
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:670)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.buildContext(DefaultSslEngineFactory.java:143)
	at com.datastax.oss.driver.internal.core.ssl.DefaultSslEngineFactory.<init>(DefaultSslEngineFactory.java:72)
	... 23 common frames omitted
Unexpected error during ThingsBoard installation!
```

**Comment by ysimonx** [comment]
I managed to convert ca.pem to truststore.jks with this command

`keytool -importcert -file ca.pem -keystore truststore.jks -storepass [truststore_password] -deststoretype jks `

i had to search for the CASSANDRA_LOCAL_DATACENTER
with https://stackoverflow.com/questions/19489498/getting-cassandra-datacenter-name-in-cqlsh

my working thingsboard.conf is now : 


```


export CASSANDRA_CLUSTER_NAME="Thingsboard Cluster" 
export CASSANDRA_LOCAL_DATACENTER=[local_data_center]
export CASSANDRA_KEYSPACE_NAME=[keyspace]
export CASSANDRA_URL=[hostname]:[port]
export CASSANDRA_USE_CREDENTIALS=true
export CASSANDRA_USERNAME=[user_login]
export CASSANDRA_PASSWORD=[user_password]
export CASSANDRA_USE_SSL=true
export CASSANDRA_SSL_TRUST_STORE=/etc/thingsboard/conf/truststore.jks
export CASSANDRA_SSL_TRUST_STORE_PASSWORD=[truststore_password]
```
