### ISSUE TITLE
[Question] Disable some log messages in thingsboard.log

### ISSUE THREAD

**Issue by freebooterish** [thingsboard/thingsboard#7605]
Hi,

I am using ThingsBoard 3.4.1, OS is Linux 20.04.
I found many many same messages  in thingsboard.log, like this:

`java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar!/:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.72.Final.jar!/:4.1.72.Final]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2022-11-14 11:30:39.324 ERROR 1 --- [ntLoopGroup-4-8] o.t.s.t.mqtt.MqttTransportHandler        : [62823e0d-7c46-420d-a4e3-cfabe6c4833a] Unexpected Exception`

what does that mean？ Is there a way to disable this message? 

Regards

**Comment by den1jkee** [comment]
Hi,
This means that some device is not properly disconnected from the ThingsBoard and the ThingsBoard gives a warning.
Check the properties of devices to resolve this issue.
Also, you can disable logging in **logback.xml**
Read this article about logs
[Enable/Disable logging](https://thingsboard.io/docs/pe/user-guide/troubleshooting/#enable-certain-logs)
