### ISSUE TITLE
[Question] Rule Engine - Rest API Call - Post Parameters

### ISSUE THREAD

**Issue by kandrianatos** [thingsboard/thingsboard#7638]
**Component**
 * Rule Engine

**Description**
Am trying to make a POST request to a REST API, but I can't find where can I pass the body parameters, only the headers. Any ideas?
![image](https://user-images.githubusercontent.com/22050314/202474416-b241a0b7-fb09-4859-a459-2028a5fdd8f6.png)

**Environment**
OS: Windows 11 Pro Local Installation

**Comment by kandrianatos** [comment]
Hi [mde2017](https://github.com/mde2017) and thank you for your reply,

I still cannot find where can i pass my request parameters, and I can't find any examples either,  I apologize but I am quite new to thingsboard.

Let say that I want to call  **https://test.com/api/getData** with request body
```
{
    "parameterOne": "valueOne",
    "parameterTwo": "valueTwo"
}
```
In the screenshot below you can see a postman sample of exactly what i want to do. 
![image](https://user-images.githubusercontent.com/22050314/202556636-3315f626-2a1a-499d-97dd-8747d70674cb.png)

**Comment by espring** [comment]
> Rule Engine is an easy to use framework for building event-based workflows. There are 3 main components:
>
> Message - any incoming event. It can be an incoming data from devices, device life-cycle event, REST API event, RPC request, etc.
> ...

The request body should be defined into msg object in the previous node which is the generator in your case.

https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#generator-node

**Comment by mde2017** [comment]
Hi @kandrianatos,

you have to define the following msg object in your case (within generator node):

```
var msg = {
    "parameterOne": "valueOne",
    "parameterTwo": "valueTwo"};
var metadata = {};
var msgType = "POST_TELEMETRY_REQUEST";

return { msg: msg, metadata: metadata, msgType: msgType };
```

**Comment by kandrianatos** [comment]
It works! I also added -> "content-type": "application/json" in headers.

Thanks!

**Comment by escalanterj** [comment]
Hello, I want to make an API call to flespi and have no idea, can anybody help me? thanks!!

**Comment by Jayanth-TR** [comment]
the post method is not working for me. i want to send data to my express backend. 
and this this the error im getting. 
org.springframework.web.reactive.function.client.WebClientRequestException: Connection refused: localhost/127.0.0.1:7000
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to POST http://localhost:7000/api/OFF/alarmStatus [DefaultWebClient]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4496)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222)
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204)
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:225)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:274)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxConcatMapNoPrefetch.java:326)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:211)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:471)
		at reactor.core.publisher.SinkManyEmitterProcessor$EmitterInner.drainParent(SinkManyEmitterProcessor.java:615)
		at reactor.core.publisher.FluxPublish$PubSubInner.request(FluxPublish.java:873)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.Operators$DeferredSubscription.request(Operators.java:1717)
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:192)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:311)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:172)
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:488)
		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:436)
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186)
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:201)
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:583)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(Fl...[truncated 3472 symbols]
