### ISSUE TITLE
MqttTransport unexpected exception

### ISSUE THREAD

**Issue by pavellzubkov** [thingsboard/thingsboard#776]
Hi.
I use eclipse paho mqtt client. When my device change wi fi network - thingsboard server stopping display any device data with errors in logs. (device id 87a87850-5162-11e8-ac0d-178594aeaa55) 

> 2018-05-12 18:06:55,620 [nioEventLoopGroup-5-8] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt8] Processing connect msg for client: 87a87850-5162-11e8-ac0d-178594aeaa55!
2018-05-12 18:07:16,512 [nioEventLoopGroup-5-9] INFO  o.t.s.t.mqtt.MqttTransportHandler - [mqtt9] Processing connect msg for client: 87a87850-5162-11e8-ac0d-178594aeaa55!
2018-05-12 18:07:21,224 [nioEventLoopGroup-5-8] ERROR o.t.s.t.mqtt.MqttTransportHandler - [mqtt8] Unexpected Exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
root@srv41857:~#

**Comment by pavellzubkov** [comment]
sorry) all ok. in paho mqtt reconnection time grow up if reconnection failed. after reconnection all works fine. Issue should be closed.

**Comment by mp-loki** [comment]
@pavellzubkov you can close it yourself as well
