### ISSUE TITLE
Opening Thingsboard on browser under proxy

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7843]
**Component**

 * Generic

**Description**
I am using Thingsboard installing in AWS EC2, with OS linix 20.04. 
I can open the Thingsboard page on browser from outside by using EC2 provided domain-address and then the Thingsboard port (8080). But in our office environment as it is under proxy, it is not possible to access Thingboard. Is there any way to make TB accessible under proxy? 

Best regards,
Debasish

**Environment**

 * OS:  Linux 20.04 (under AWS EC2)
 * ThingsBoard: Community Edition 3.4.1
 * Browser: chrome, edge, firefox

**Comment by devaskim** [comment]
You can run your TB instance on 80 or 443 port directly or use, for example, HAproxy (here is [TB guide](https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/) ), to redirect traffic to 8080 port

**Comment by debacs83** [comment]
Thank you for your reply. 

I have just tried the first and simpler options. Edit the /etc/thingsboard/conf/thingsboard.yml file. 
port* "${HTTP_BIND_PORT:443}" 

but thingsboard could not start (>service thingsboard start) 

------------- error msg --------------
● thingsboard.service - thingsboard
     Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-12-26 09:27:43 UTC; 34s ago
    Process: 127373 ExecStart=/usr/share/thingsboard/bin/thingsboard.jar (code=exited, status=1/FAILURE)
   Main PID: 127373 (code=exited, status=1/FAILURE)

Dec 26 09:27:41 ip-172-31-34-110 systemd[1]: Started thingsboard.
Dec 26 09:27:41 ip-172-31-34-110 thingsboard.jar[127382]: /usr/share/thingsboard/conf/thingsboard.conf: line 19: xport: comma>
Dec 26 09:27:43 ip-172-31-34-110 systemd[1]: thingsboard.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 09:27:43 ip-172-31-34-110 systemd[1]: thingsboard.service: Failed with result 'exit-code'.

--------------------------------------------------------

With PORT:80, it could start, but then could not open TB on browser. 
I tried with <http://ec2-12-234-5-67.us-west-2.compute.amazonaws.com:80> 

I am using self-signed certificate and https, using the following explanation.
https://thingsboard.io/docs/user-guide/ssl/http-over-ssl/

openssl ecparam -out server_key.pem -name secp256r1 -genkey
openssl req -new -key server_key.pem -x509 -nodes -days 365 -out server.pem 

I haven't tried the HAProxy yet. 

Thanks.

**Comment by debacs83** [comment]
A very critical situation raised. After editing the thingsboard.yml file and trying to start-stop it a few times, suddenly the service 'thingsboard' is not appearing anymore. I used to start-stop it with 'service' command. 
service thingsboard start  
But now the 'thingsboard' itself is not appearing! What might be the cause? Any way to recover? If I reinstall it does all my setting, dashboards, widget all will go? It will be really scary then.

Please help.

Debasish

**Comment by devaskim** [comment]
Just make backup of `data` folder and try to reinstall

**Comment by debacs83** [comment]
Thanks for getting back. 

Do you mean the files under /etc/thingsboard/conf or the postgresql database or some other folder?

**Comment by debacs83** [comment]
Are you talking about this folder? 
/usr/share/thingsboard/data

**Comment by debacs83** [comment]
ubuntu@ip-172-31-34-110:~$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
/usr/share/thingsboard/conf/thingsboard.conf: line 19: xport: command not found

This is the error msg when I tried to reinstall. It is the same error msg appeared before. This is the entire error msg.

---
ubuntu@ip-172-31-34-110:~$ sudo /usr/share/thingsboard/bin/install/install.sh --loadDemo
/usr/share/thingsboard/conf/thingsboard.conf: line 19: xport: command not found
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard ::       (v3.4.2)
 ===================================================

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!
        at org.thingsboard.server.dao.service.validator.UserDataValidator.validateDataImpl(UserDataValidator.java:137)
        at org.thingsboard.server.dao.service.validator.UserDataValidator.validateDataImpl(UserDataValidator.java:39)
        at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:55)
        at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:115)
        at org.thingsboard.server.dao.user.UserServiceImpl$$FastClassBySpringCGLIB$$83a3dd57.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at org.thingsboard.server.dao.user.UserServiceImpl$$EnhancerBySpringCGLIB$$ba384c7c.saveUser(<generated>)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createUser(DefaultSystemDataLoaderService.java:515)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createSysAdmin(DefaultSystemDataLoaderService.java:195)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:273)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

**Comment by debacs83** [comment]
Though the same error msg shown in the beginning but could upgrade to 3.4.2 

Updating data from version 3.4.1 to 3.4.2 ...
Starting audit logs migration. Can be skipped with TB_SKIP_AUDIT_LOGS_MIGRATION env variable set to true
Starting edge events migration. Can be skipped with TB_SKIP_EDGE_EVENTS_MIGRATION env variable set to true
Updating system data...
Upgrade finished successfully!
ThingsBoard upgraded successfully!
----
But the original problem remains. Thinsboard service could not found.

ubuntu@ip-172-31-34-110:/etc/thingsboard/conf$ sudo service thingisboard status
Unit thingisboard.service could not be found.

But could solve it!

Warning: The unit file, source configuration file or drop-ins of thingsboard.service changed on disk. Run 'systemctl daemon-reload' to reload units.
ubuntu@ip-172-31-34-110:/etc/thingsboard/conf$ systemctl daemon-reload

So as per instruction in the above, it is working as before. And instead of installing, as I have already unpack the 3.4.2 package, I upgraded it with the following command.

sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=3.4.1

Thank you for helping. One thing would like to confirm. I had faced this problem long before while installing Thingsboard on docker. What this 'systemctl daemon-reload' is doing and how it is recovered? And what could be this sudden problem? Because it was working fine for months. I have another TB running for more than a year in local server and it is fine too. 

Regards,
Debasish

**Comment by devaskim** [comment]
> Are you talking about this folder?
/usr/share/thingsboard/data

Yes

> User with email '[sysadmin@thingsboard.org](mailto:sysadmin@thingsboard.org)' already present in database!

You ran installation script with `--loadDemo` option that try to create default sysadmin and tenant account, but your Postgres database already has those account from previous, i.e. broken, installation

> What this 'systemctl daemon-reload' is doing 

Once you add new service file where are instructions how to start/stop your service, you need to notify OS about it.

> And what could be this sudden problem? 

I never face with such issue. I guest you make some syntax mistake in TB configuration files.

**Comment by debacs83** [comment]
Thank you for the detailed explanation.  Yes, it could be thingsboard.conf file, as in the error msg it is mentioning line 19 of that file. I will later check with my other TB config file.

**Comment by debacs83** [comment]
The config files seems fine. One mistake I probably done yesterday was editing the 'thingsboard.yml' file (for changing the PORT number from 8080 to 443 or 80) I should have stopped the Thingsboard first. Also after editing it might be better to exit the editing mode (it was running in the background). Does these things, especially the first, could have caused the problem of 'thingsboard' service gone missing? Then I should note it down in RED color.

**Comment by devaskim** [comment]
It is not a problem to edit configurarion files while service is running, but starting again all of them must be at least be saved.

To find more details about issue you can recheck thingsboard.log file

**Comment by debacs83** [comment]
It was saved of course. But the text editor was running in bg. That should not be a problem I think. Will check the log. 
Thank you.

**Comment by debacs83** [comment]
@devaskim 
I have tried the HAProxy. Installation went well without problem. At the very end, 
sudo certbot-certonly --domain your_domain --email your_email

I tried with the AWS EC2 instance's 'Public IPv4 DNS' and with '$dnsdomainname' command on Linux EC2 instance. 
Both of them gave the following error:
The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy.

Seems I need to create a domain name with the EC2 instance's Elastic IP, either by going to a Domain name provider or create it at AWS Route 53. 

checked with the following command if the HAProxy is active or not.
$sudo systemctl status haproxy.service -l --no-pager

It gave the following results:
haproxy.service - HAProxy Load Balancer
     Loaded: loaded (/lib/systemd/system/haproxy.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-01-10 07:08:17 UTC; 7min ago
...
...
Health check for server tb-backend/tb1 succeeded, reason: Layer4 check passed, check duration: 0ms, status: 3/3 UP.

If I run 'sudo haproxy-refresh' it says that there is no 'live' file or folder

 '/usr/share/tb-haproxy/letsencrypt/live': No such file or directory

And there is no 'live' file or folder as the error msg says. 

Any other thing should I try or test?

**Comment by devaskim** [comment]
> sudo certbot-certonly --domain your_domain --email your_email

Try to google `certbot aws`

**Comment by debacs83** [comment]
Thanks. I have got related pages and explanation. Before that I would like to one related question. 
Earlier you had suggested to change the port number from 8080 to 80 or 443 directly. The thing is, after editing, when I start TB, it started normally. But within a couple of minutes its stopped. But if I use any other port number, say 8989, 108080 whatever and add that to the EC2 Inbound port list, it works fine. 
Here is a part of log:

       ....  ....
        Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:238)
        at     org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
        ... 24 common frames omitted
        Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1075)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:234)
        ... 26 common frames omitted
       Caused by: java.net.SocketException: Permission denied
       ....   ....
         
ps. I had installed apache2 server following instruction for AWS certbot related pages. As apache is also using port 80, so I stopped it when assigning port 80 to TB.

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with a full description of your request.
