### ISSUE TITLE
docker images web-ui error

### ISSUE THREAD

**Issue by struggle3** [thingsboard/thingsboard#7852]
**Component**

 * UI

**Description**
After building local Docker images web ui, using Docker Run, the following error occurs:

[root@localhost ~]# docker logs web-ui
Starting 'ThingsBoard Web UI Microservice' ...
/usr/share/tb-web-ui/conf/tb-web-ui.conf: line 16: $'\r': command not found
' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/usr/share/tb-web-ui/conf
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/usr/share/tb-web-ui/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "logger.level" is not defined
    at Config.get (/usr/share/tb-web-ui/node_modules/config/lib/config.js:182:11)
    at _logger (/usr/share/tb-web-ui/config/logger.js:54:33)
    at Object.<anonymous> (/usr/share/tb-web-ui/server.js:61:37)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

![image](https://user-images.githubusercontent.com/19941827/209593697-79f6d878-1909-4365-b73c-617940ddc741.png)

**Environment**

 * OS:  centos & docker
 * ThingsBoard: 3.4.2
 * Browser: none

**Comment by pon0marev** [comment]
You have probably mounted the `/usr/share/tb-web-ui/conf` directory to the docker container but have not included the default configuration files.
Attach your docker deployment file and the contents of `/usr/share/tb-web-ui/conf`

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
