### ISSUE TITLE
[Bug] Update from 3.4.1 to 3.4.2 or 3.4.3 docker-compose

### ISSUE THREAD

**Issue by TS-Steff** [thingsboard/thingsboard#7882]
**Describe the bug**
```
Starting ThingsBoard upgrade ...

 :: ThingsBoard ::       (v3.4.3)

Starting ThingsBoard Upgrade from version 3.4.1 ...
Clear cache to upgrade from version 3.4.1 to 3.4.2 ...
Clearing cache [assets]
Clearing cache [repositorySettings]
Upgrading ThingsBoard from version 3.4.1 to 3.4.2 ...
Updating schema ...
2023-01-01 21:44:32.229 UTC [107] ERROR:  relation "old_blob_entity" does not exist
2023-01-01 21:44:32.229 UTC [107] CONTEXT:  SQL statement "CREATE INDEX IF NOT EXISTS idx_old_blob_entity_created_time_tmp ON old_blob_entity(created_time)"
	PL/pgSQL function inline_code_block line 7 at SQL statement
2023-01-01 21:44:32.229 UTC [107] STATEMENT:  
	-- AUDIT LOGS MIGRATION END
	
	
	-- EDGE EVENTS MIGRATION START
	DO
	$$
	    DECLARE table_partition RECORD;
	    BEGIN
	    -- in case of running the upgrade script a second time:
	        IF NOT (SELECT exists(SELECT FROM pg_tables WHERE tablename = 'old_edge_event')) THEN
	            ALTER TABLE edge_event RENAME TO old_edge_event;
	            CREATE INDEX IF NOT EXISTS idx_old_blob_entity_created_time_tmp ON old_blob_entity(created_time);
	            ALTER INDEX IF EXISTS idx_edge_event_tenant_id_and_created_time RENAME TO idx_old_edge_event_tenant_id_and_created_time;
	
	            FOR table_partition IN SELECT tablename AS name, split_part(tablename, '_', 3) AS partition_ts
	            FROM pg_tables WHERE tablename LIKE 'edge_event_%'
	            LOOP
	                EXECUTE format('ALTER TABLE %s RENAME TO old_edge_event_%s', table_partition.name, table_partition.partition_ts);
	            END LOOP;
	        ELSE
	            RAISE NOTICE 'Table old_edge_event already exists, leaving as is';
	        END IF;
	END;
	$$
Failed updating schema!!!
org.postgresql.util.PSQLException: ERROR: relation "old_blob_entity" does not exist
  Where: SQL statement "CREATE INDEX IF NOT EXISTS idx_old_blob_entity_created_time_tmp ON old_blob_entity(created_time)"
PL/pgSQL function inline_code_block line 7 at SQL statement
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.loadSql(SqlDatabaseUpgradeService.java:694)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.runSchemaUpdateScript(SqlDatabaseUpgradeService.java:687)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:617)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:234)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Updating data from version 3.4.1 to 3.4.2 ...
Starting audit logs migration. Can be skipped with TB_SKIP_AUDIT_LOGS_MIGRATION env variable set to true
2023-01-01 21:44:32.622 UTC [57] ERROR:  procedure migrate_audit_logs(bigint, bigint, bigint) does not exist at character 6
2023-01-01 21:44:32.622 UTC [57] HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.
2023-01-01 21:44:32.622 UTC [57] STATEMENT:  CALL migrate_audit_logs($1, $2, $3)
Unexpected error during ThingsBoard installation!
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [CALL migrate_audit_logs(?, ?, ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: procedure migrate_audit_logs(bigint, bigint, bigint) does not exist
  Hint: No procedure matches the given name and argument types. You might need to add explicit type casts.
  Position: 6
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1025)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao.callMigrationFunction(JpaAuditLogDao.java:182)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao.migrateAuditLogs(JpaAuditLogDao.java:173)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao$$FastClassBySpringCGLIB$$86741131.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.thingsboard.server.dao.aspect.SqlDaoCallsAspect.handleSqlCall(SqlDaoCallsAspect.java:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao$$EnhancerBySpringCGLIB$$69c07465.migrateAuditLogs(<generated>)
	at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:193)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:235)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.postgresql.util.PSQLException: ERROR: procedure migrate_audit_logs(bigint, bigint, bigint) does not exist
  Hint: No procedure matches the given name and argument types. You might need to add explicit type casts.
  Position: 6
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
	... 37 common frames omitted
Unexpected error during ThingsBoard installation!
waiting for server to shut down....2023-01-01 21:44:32.961 UTC [13] LOG:  received fast shutdown request
2023-01-01 21:44:32.963 UTC [13] LOG:  aborting any active transactions
2023-01-01 21:44:32.970 UTC [13] LOG:  background worker "logical replication launcher" (PID 20) exited with exit code 1
2023-01-01 21:44:32.970 UTC [15] LOG:  shutting down
2023-01-01 21:44:33.012 UTC [13] LOG:  database system is shut down
 done
server stopped
```

**Server Environment**
* own setup
  * docker-compose with traefik reverse-proxy
  * ThingsBoard 3.4.1
  * Ubuntu 22.04.1 LTS 
  * Docker version 20.10.12, build e91ed57
  * docker-compose version 1.21.2, build a133471

I couldn't find a way to upgrade.

**Comment by pon0marev** [comment]
It is important to upgrade version by version. First, set the 3.4.2 image and upgrade from version 3.4.1. Then set the 3.4.3 image.

**Comment by TS-Steff** [comment]
I've just deleted docker images 3.4.3 and 3.4.2.
Changed docker-compose to use thingsboard/tb-postgres:3.4.2
edited .upgradeversion to 3.4.1

```
docker-compose pull
docker run -it -v /home/docker_user/thingsboard/data:/data --rm thingsboard/tb-postgres:3.4.2 upgrade-tb.sh
docker-compose up
```

This upgraded sucessfully to 3.4.2. The Problem seems to be the docker run command without the container version. This because docker dose not look in the docker-compose file for the version.

After this i changed the docker-compose.yaml to use 3.4.3 and ran the update for 3.4.3. This failed with
```
Starting ThingsBoard Upgrade from version 3.4.2 ...
Clearing cache to upgrade from version 3.4.2 to 3.4.3 ...
Clearing cache [repositorySettings]
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 3.4.2
```

I then deleted the .upgradeversion file and tried again which gave me of course
```
Starting ThingsBoard upgrade ...
FROM_VERSION variable is invalid or unspecified!
```
after recreating and running upgrade-tb.sh again i ended up with the previous error again, Unable to upgrade ThingsBoard, unsupported fromVersion: 3.4.2.

Ignoring this error and starting the container seems to work.

Is there even a database update from 3.4.2 to 3.4.3?

**Comment by pon0marev** [comment]
As noted in the upgrade instructions [https://thingsboard.io/docs/user-guide/install/upgrade-instructions/](url) , to upgrade from 3.4.2 to 3.4.3 there is no need to run the upgrade script. In 3.4.3 there were no changes to the database, so you only need to update the image.

**Comment by TS-Steff** [comment]
Thanks @pon0marev 
I should really better RTFM

**Comment by HardwayLinka** [comment]
Hi @pon0marev, I wonder why it is important to upgrade version by version. The version of my current database is 3.4.1, and the version of my thingsboard is 3.4.3, then I want to upgrade the version of database directly from 3.4.1 to 3.4.2 by building from source. So i changed the value of `isUpgrade` and `upgradeFromVersion` in [ThingsboardInstallService.java](https://github.com/thingsboard/thingsboard/blob/e9be91d9e1ee3373f365342d8f7f8d43af36f1ce/application/src/main/java/org/thingsboard/server/install/ThingsboardInstallService.java) like this: 
```
@Value("${install.upgrade:true}")
private Boolean isUpgrade;

@Value("${install.upgrade.from_version:3.4.1}")
private String upgradeFromVersion;
```
then run [ThingsboardInstallApplication.java](https://github.com/thingsboard/thingsboard/blob/e9be91d9e1ee3373f365342d8f7f8d43af36f1ce/application/src/main/java/org/thingsboard/server/ThingsboardInstallApplication.java), but the problem as below happened:

> 2023-02-02 12:10:02,740 [main] INFO  o.t.s.i.ThingsboardInstallService - Starting ThingsBoard Upgrade from version 3.4.1 ...
2023-02-02 12:10:02,741 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clear cache to upgrade from version 3.4.1 to 3.4.2 ...
2023-02-02 12:10:02,741 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [assets]
2023-02-02 12:10:02,743 [main] INFO  o.t.s.s.i.u.DefaultCacheCleanupService - Clearing cache [repositorySettings]
2023-02-02 12:10:02,744 [main] INFO  o.t.s.i.ThingsboardInstallService - Upgrading ThingsBoard from version 3.4.1 to 3.4.2 ...
2023-02-02 12:10:02,772 [main] INFO  o.t.s.s.i.SqlDatabaseUpgradeService - Updating schema ...
2023-02-02 12:10:02,810 [main] ERROR o.t.s.s.i.SqlDatabaseUpgradeService - Failed updating schema!!!
org.postgresql.util.PSQLException: ERROR: relation "old_blob_entity" does not exist
  Where: SQL statement "CREATE INDEX IF NOT EXISTS idx_old_blob_entity_created_time_tmp ON old_blob_entity(created_time)"
PL/pgSQL function inline_code_block line 7 at SQL statement
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.loadSql(SqlDatabaseUpgradeService.java:694)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.runSchemaUpdateScript(SqlDatabaseUpgradeService.java:687)
	at org.thingsboard.server.service.install.SqlDatabaseUpgradeService.upgradeDatabase(SqlDatabaseUpgradeService.java:617)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:234)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
2023-02-02 12:10:02,811 [main] INFO  o.t.s.s.i.u.DefaultDataUpdateService - Updating data from version 3.4.1 to 3.4.2 ...
2023-02-02 12:10:02,811 [main] INFO  o.t.s.s.s.a.j.s.DefaultJwtSettingsService - Saving legacy JWT admin settings from YML...
2023-02-02 12:10:03,033 [main] INFO  o.t.s.s.i.u.DefaultDataUpdateService - Starting audit logs migration. Can be skipped with TB_SKIP_AUDIT_LOGS_MIGRATION env variable set to true
2023-02-02 12:10:03,039 [main] INFO  o.t.s.dao.sql.audit.JpaAuditLogDao - Migrating audit logs for time period: 1480982400000 - 1481587200000
2023-02-02 12:10:03,140 [main] ERROR o.t.s.i.ThingsboardInstallService - Unexpected error during ThingsBoard installation!
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [CALL migrate_audit_logs(?, ?, ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: procedure migrate_audit_logs(bigint, bigint, bigint) does not exist
  Hint: No procedure matches the given name and argument types. You might need to add explicit type casts.
  Position: 6
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1025)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao.callMigrationFunction(JpaAuditLogDao.java:182)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao.migrateAuditLogs(JpaAuditLogDao.java:173)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao$$FastClassBySpringCGLIB$$86741131.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.thingsboard.server.dao.aspect.SqlDaoCallsAspect.handleSqlCall(SqlDaoCallsAspect.java:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.thingsboard.server.dao.sql.audit.JpaAuditLogDao$$EnhancerBySpringCGLIB$$f4a7dbd1.migrateAuditLogs(<generated>)
	at org.thingsboard.server.service.install.update.DefaultDataUpdateService.updateData(DefaultDataUpdateService.java:193)
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:235)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
Caused by: org.postgresql.util.PSQLException: ERROR: procedure migrate_audit_logs(bigint, bigint, bigint) does not exist
  Hint: No procedure matches the given name and argument types. You might need to add explicit type casts.
  Position: 6
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
	... 29 common frames omitted
2023-02-02 12:10:03,165 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2023-02-02 12:10:03,165 [main] INFO  o.s.i.c.PublishSubscribeChannel - Channel 'application.errorChannel' has 0 subscriber(s).
2023-02-02 12:10:03,166 [main] INFO  o.s.i.endpoint.EventDrivenConsumer - stopped bean '_org.springframework.integration.errorLogger'
2023-02-02 12:10:03,192 [sql-queue-0-edge events-17-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Edge Events] Queue polling was interrupted
2023-02-02 12:10:03,194 [sql-queue-0-ts latest-11-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2023-02-02 12:10:03,194 [sql-queue-1-ts latest-12-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2023-02-02 12:10:03,194 [sql-queue-2-ts latest-13-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2023-02-02 12:10:03,194 [sql-queue-0-ts-8-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2023-02-02 12:10:03,194 [sql-queue-1-ts-9-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2023-02-02 12:10:03,195 [sql-queue-2-ts-10-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2023-02-02 12:10:03,195 [sql-queue-2-attributes-7-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] Queue polling was interrupted
2023-02-02 12:10:03,195 [sql-queue-0-attributes-5-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] Queue polling was interrupted
2023-02-02 12:10:03,196 [sql-queue-1-attributes-6-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] Queue polling was interrupted
2023-02-02 12:10:03,199 [sql-queue-0-events-2-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2023-02-02 12:10:03,199 [sql-queue-2-events-4-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2023-02-02 12:10:03,199 [sql-queue-1-events-3-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2023-02-02 12:10:03,203 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2023-02-02 12:10:03,206 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-02-02 12:10:03,294 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2023-02-02 12:10:03,296 [main] ERROR o.t.s.ThingsboardInstallApplication - Unexpected error during ThingsBoard installation!
>
>Process finished with exit code 1

**Comment by HardwayLinka** [comment]
This issue has nothing to do with version-by-version upgrades. It's a bug which fixed [here](https://github.com/thingsboard/thingsboard/commit/f04753d3f970272e3a4ff9ad92451dcce4ffb35a)

**Comment by thhart** [comment]
I have the same problem. The fix mentioned above does not solve the original problem of old_blob_entity non existing. At which version was this relation introduced? Is it possible to share a valid schema of this relation, I can not find it anywhere in the source.
