### ISSUE TITLE
develop/1.5 alarm error

### ISSUE THREAD

**Issue by untilbit** [thingsboard/thingsboard#793]
I created an alarm an i'm getting these errors:

I'm using Thingsboard 1.5, compiled from last commit " fix lincense headers ".

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 1 failed)
	at org.thingsboard.server.dao.alarm.BaseAlarmService.createOrUpdateAlarm(BaseAlarmService.java:108)
	at org.thingsboard.rule.engine.action.TbCreateAlarmNode.lambda$updateAlarm$4(TbCreateAlarmNode.java:85)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 1 failed)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.dao.alarm.BaseAlarmService.createOrUpdateAlarm(BaseAlarmService.java:105)
	... 8 more
Caused by: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 1 failed)
	at com.datastax.driver.core.exceptions.WriteFailureException.copy(WriteFailureException.java:125)
	at com.datastax.driver.core.exceptions.WriteFailureException.copy(WriteFailureException.java:31)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.getUninterruptibly(RateLimitedResultSetFuture.java:52)
	at org.thingsboard.server.dao.nosql.CassandraAbstractDao.execute(CassandraAbstractDao.java:94)
	at org.thingsboard.server.dao.nosql.CassandraAbstractDao.executeWrite(CassandraAbstractDao.java:79)
	at org.thingsboard.server.dao.nosql.CassandraAbstractModelDao.saveWithResult(CassandraAbstractModelDao.java:143)
	at org.thingsboard.server.dao.nosql.CassandraAbstractModelDao.save(CassandraAbstractModelDao.java:162)
	at org.thingsboard.server.dao.alarm.CassandraAlarmDao.save(CassandraAlarmDao.java:75)
	at org.thingsboard.server.dao.alarm.BaseAlarmService.updateAlarm(BaseAlarmService.java:155)
	at org.thingsboard.server.dao.alarm.BaseAlarmService.access$000(BaseAlarmService.java:60)
	at org.thingsboard.server.dao.alarm.BaseAlarmService$1.apply(BaseAlarmService.java:144)
	at org.thingsboard.server.dao.alarm.BaseAlarmService$1.apply(BaseAlarmService.java:137)
	... 7 more
Caused by: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 1 failed)
	at com.datastax.driver.core.exceptions.WriteFailureException.copy(WriteFailureException.java:136)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:137)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:198)
	at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:50)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:852)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:686)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1087)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1010)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:806)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 1 failed)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:84)
	at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:37)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:289)
	at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:269)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 23 more

```

**Comment by ashvayka** [comment]
Are you sure your Cassandra is ok? Is it 3.11.2?

**Comment by untilbit** [comment]
Yes, in docker-compose i have version 3.11.2.
When I send timeseries data it appears in thingboard.

**Comment by ashvayka** [comment]
Please move to develop/2.0. develop/1.5 is now develop/2.0

**Comment by untilbit** [comment]
Ok. I'll try again

**Comment by untilbit** [comment]
Can't build develop/2.0.
I have a question: How I can save data from telemetry attribute to 2 other telemetry attributes or server attributes.

**Comment by ashvayka** [comment]
We are writing the tutorials now. Stay tuned.

**Comment by untilbit** [comment]
Great!

**Comment by untilbit** [comment]
I got another error. I created alarm following the tutorial and in the **Create alarm** node I have the following.

```
javax.script.ScriptException: Failed to execute js script: java.lang.RuntimeException: Script is blacklisted due to maximum error count 3!
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeScript(RuleNodeJsScriptEngine.java:171)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.executeJson(RuleNodeJsScriptEngine.java:117)
	at org.thingsboard.rule.engine.action.TbAbstractAlarmNode.lambda$buildAlarmDetails$2(TbAbstractAlarmNode.java:78)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Tutorial: https://github.com/thingsboard/thingsboard.github.io/blob/9de495b8d140b373e4629ea48806bdda308a43e8/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms.md#step-2-clear-alarm

**Comment by vparomskiy** [comment]
If a configured script was failed internally because of error more then 3 times it is added into the blacklist. If you see this error, then please review your script code and fix the issue. Blacklist is cleared after Rule Chain is changed and saved.

**Comment by aderbas** [comment]
I sometimes receive this error and my script is very short. `return metadata.deviceType === 'zipbx';` All circle of rule is stopped before this error. I do not understand why this happens. Version 2.1.0.
