### ISSUE TITLE
Unable to start service thingsboard

### ISSUE THREAD

**Issue by Vishalbuu** [thingsboard/thingsboard#7939]
I am using Ubuntu 18.04 server
I started to follow procedure to download thinksboard V3.4.3 in  Installation > On premise > Ubuntu Server 

I followed all steps there were no error  
After I tried to start the service and checked its status it showed running or active after few minutes I checked http://(my ip):8080/ it is not running.
Below I will attach log
ethics@ethics-desktop:~$ sudo service thingsboard start
ethics@ethics-desktop:~$ sudo service thingsboard status
● thingsboard.service - thingsboard
   Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2023-01-13 17:01:38 IST; 2s ago
 Main PID: 19895 (thingsboard.jar)
    Tasks: 21 (limit: 4647)
   CGroup: /system.slice/thingsboard.service
           ├─19895 /bin/bash /usr/share/thingsboard/bin/thingsboard.jar
           └─19923 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=deb -Dinstall.data_dir=/usr/share/thingsboard/data -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/lo

Jan 13 17:01:38 ethics-desktop systemd[1]: Started thingsboard.

ethics@ethics-desktop:~$ sudo service thingsboard status
● thingsboard.service - thingsboard
   Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2023-01-13 17:02:28 IST; 2min 38s ago
  Process: 19895 ExecStart=/usr/share/thingsboard/bin/thingsboard.jar (code=exited, status=1/FAILURE)
 Main PID: 19895 (code=exited, status=1/FAILURE)

Jan 13 17:01:42 ethics-desktop thingsboard.jar[19895]:  :: ThingsBoard ::       (v3.4.3)
Jan 13 17:01:42 ethics-desktop thingsboard.jar[19895]:  ===================================================
Jan 13 17:02:15 ethics-desktop thingsboard.jar[19895]: WARNING: An illegal reflective access operation has occurred
Jan 13 17:02:15 ethics-desktop thingsboard.jar[19895]: WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (jar:file:/usr/share/thingsboard/bin/thingsboard.jar!/BOOT-IN
Jan 13 17:02:15 ethics-desktop thingsboard.jar[19895]: WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
Jan 13 17:02:15 ethics-desktop thingsboard.jar[19895]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Jan 13 17:02:15 ethics-desktop thingsboard.jar[19895]: WARNING: All illegal access operations will be denied in a future release
Jan 13 17:02:24 ethics-desktop thingsboard.jar[19895]: Warning: Nashorn engine is planned to be removed from a future JDK release
Jan 13 17:02:28 ethics-desktop systemd[1]: thingsboard.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 17:02:28 ethics-desktop systemd[1]: thingsboard.service: Failed with result 'exit-code'.
lines 1-16/16 (END)

This same thing happens while I am trying to do the same using  Installation > On premise > Building from sources  procedure.

Please help me how I can solve this issue

**Comment by Vishalbuu** [comment]
2023-01-18 10:22:32,877 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.20.Final
2023-01-18 10:22:34,349 [main] INFO  o.t.s.ThingsboardServerApplication - Starting ThingsboardServerApplication v3.4.3 using Java 11.0.17 on ethics-desktop with PID 936 (/usr/share/thingsboard/bin/thingsboard.jar started by thingsboard in /usr/share/thingsboard/bin)
2023-01-18 10:22:34,351 [main] INFO  o.t.s.ThingsboardServerApplication - No active profile set, falling back to 1 default profile: "default"
2023-01-18 10:23:01,148 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2023-01-18 10:23:01,148 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-01-18 10:23:03,757 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 2561 ms. Found 45 JPA repository interfaces.
2023-01-18 10:23:03,765 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2023-01-18 10:23:03,766 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-01-18 10:23:03,824 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 58 ms. Found 1 JPA repository interfaces.
2023-01-18 10:23:03,833 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2023-01-18 10:23:03,833 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-01-18 10:23:03,921 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 87 ms. Found 1 JPA repository interfaces.
2023-01-18 10:23:03,940 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2023-01-18 10:23:03,940 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-01-18 10:23:04,015 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 75 ms. Found 1 JPA repository interfaces.
2023-01-18 10:23:07,282 [main] INFO  o.s.i.c.DefaultConfiguringBeanFactoryPostProcessor - No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2023-01-18 10:23:07,376 [main] INFO  o.s.i.c.DefaultConfiguringBeanFactoryPostProcessor - No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2023-01-18 10:23:16,086 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-18 10:23:16,272 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-01-18 10:23:17,930 [main] INFO  o.t.s.q.d.DefaultTbServiceInfoProvider - Current Service ID: ethics-desktop
2023-01-18 10:23:22,547 [main] INFO  o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [name: default]
2023-01-18 10:23:25,465 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.6.9.Final
2023-01-18 10:23:33,053 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2023-01-18 10:23:35,053 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-01-18 10:23:41,121 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-01-18 10:23:42,889 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
2023-01-18 10:23:57,494 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2023-01-18 10:23:57,734 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-01-18 10:24:16,277 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
2023-01-18 10:24:16,331 [main] INFO  o.a.coyote.http11.Http11NioProtocol - The ["http-nio-0.0.0.0-8080"] connector has been configured to support HTTP upgrade to [h2c]
2023-01-18 10:24:16,331 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-0.0.0.0-8080"]
2023-01-18 10:24:16,333 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
2023-01-18 10:24:16,334 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.63]
2023-01-18 10:24:16,830 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
2023-01-18 10:24:16,838 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 101243 ms
2023-01-18 10:24:23,053 [main] INFO  o.t.s.s.a.DefaultTbApiUsageStateService - Starting api usage service.
2023-01-18 10:24:23,203 [main] INFO  o.t.s.s.a.DefaultTbApiUsageStateService - Started api usage service.
2023-01-18 10:24:23,498 [main] INFO  o.t.s.d.a.CachedAttributesService - Going to use directExecutor for the local cache type caffeine
2023-01-18 10:24:30,686 [main] INFO  d.n.internal.NashornDetection - Delight-nashorn-sandbox detected that JDK Nashorn is present and standalone Nashorn is absent, and will use JDK Nashorn
2023-01-18 10:24:33,978 [main] INFO  o.t.s.c.t.c.ssl.SslCredentialsConfig - LWM2M Server DTLS Credentials: Skipping initialization of disabled SSL credentials.
2023-01-18 10:24:33,995 [main] INFO  o.t.s.c.t.c.ssl.SslCredentialsConfig - LWM2M Trust Credentials: Skipping initialization of disabled SSL credentials.
2023-01-18 10:24:34,023 [main] INFO  o.t.s.c.t.c.ssl.SslCredentialsConfig - LWM2M Bootstrap DTLS Credentials: Skipping initialization of disabled SSL credentials.
2023-01-18 10:24:34,377 [main] INFO  o.t.s.s.edge.rpc.EdgeGrpcService - Initializing Edge RPC service!
2023-01-18 10:24:36,126 [main] INFO  o.t.s.s.edge.rpc.EdgeGrpcService - Going to start Edge RPC server using port: 7070
2023-01-18 10:24:36,718 [main] INFO  o.t.s.s.edge.rpc.EdgeGrpcService - Edge RPC service initialized!
2023-01-18 10:24:37,767 [main] INFO  o.t.s.a.service.DefaultActorService - Initializing actor system.
2023-01-18 10:24:37,837 [main] INFO  o.t.s.a.service.DefaultActorService - Actor system initialized.
2023-01-18 10:24:39,294 [main] INFO  o.t.s.c.SystemInfoController - System build info: {"version":"3.4.3","artifact":"application","name":"ThingsBoard Server Application"}
2023-01-18 10:24:39,754 [main] INFO  o.t.s.c.t.a.JsonConverterConfig - JSON type cast enabled = true
2023-01-18 10:24:39,755 [main] INFO  o.t.s.c.t.a.JsonConverterConfig - JSON max string value length = 0
2023-01-18 10:24:39,942 [main] INFO  o.t.s.t.mqtt.MqttTransportService - Setting resource leak detector level to DISABLED
2023-01-18 10:24:39,942 [main] INFO  o.t.s.t.mqtt.MqttTransportService - Starting MQTT transport...
2023-01-18 10:24:40,424 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'MqttTransportService': Invocation of init method failed; nested exception is java.net.BindException: Address already in use
2023-01-18 10:24:40,428 [main] INFO  o.t.s.a.service.DefaultActorService - Stopping actor system.
2023-01-18 10:24:40,430 [main] INFO  o.t.s.a.service.DefaultActorService - Actor system stopped.
2023-01-18 10:24:40,606 [sql-queue-0-edge events-26-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Edge Events] Queue polling was interrupted
2023-01-18 10:24:40,613 [sql-queue-0-attributes-18-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] Queue polling was interrupted
2023-01-18 10:24:40,613 [sql-queue-2-attributes-20-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] Queue polling was interrupted
2023-01-18 10:24:40,619 [sql-queue-0-ts latest-13-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2023-01-18 10:24:40,620 [sql-queue-1-ts latest-14-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2023-01-18 10:24:40,620 [sql-queue-2-ts latest-15-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS Latest] Queue polling was interrupted
2023-01-18 10:24:40,621 [sql-queue-0-ts-10-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2023-01-18 10:24:40,621 [sql-queue-1-ts-11-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2023-01-18 10:24:40,622 [sql-queue-2-ts-12-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [TS] Queue polling was interrupted
2023-01-18 10:24:40,624 [sql-queue-1-attributes-19-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Attributes] Queue polling was interrupted
2023-01-18 10:24:40,638 [sql-queue-0-events-2-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2023-01-18 10:24:40,638 [sql-queue-2-events-4-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2023-01-18 10:24:40,637 [sql-queue-1-events-3-thread-1] INFO  o.t.s.dao.sql.TbSqlBlockingQueue - [Events] Queue polling was interrupted
2023-01-18 10:24:40,646 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2023-01-18 10:24:40,650 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-01-18 10:24:40,722 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2023-01-18 10:24:40,726 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2023-01-18 10:24:40,807 [main] INFO  o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-01-18 10:24:41,007 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'MqttTransportService': Invocation of init method failed; nested exception is java.net.BindException: Address already in use
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:459)
	at java.base/sun.nio.ch.Net.bind(Net.java:448)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)


I have attached thinksboard.log

**Comment by Vishalbuu** [comment]
Ok sir, Thank You I have cleared the issue by killing the mqtt broker port

**Comment by Stergios96Tousoulis** [comment]
Hello, i tried to install on Debian Raspberry pi but i got the following error:


Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email 'sysadmin@thingsboard.org'  already present in database!
        at org.thingsboard.server.dao.service.validator.UserDataValidator.validateDataImpl(UserDataValidator.java:137)
        at org.thingsboard.server.dao.service.validator.UserDataValidator.validateDataImpl(UserDataValidator.java:39)
        at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:55)
        at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:115)
        at org.thingsboard.server.dao.user.UserServiceImpl$$FastClassBySpringCGLIB$$83a3dd57.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at org.thingsboard.server.dao.user.UserServiceImpl$$EnhancerBySpringCGLIB$$dff8f79b.saveUser(<generated>)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createUser(DefaultSystemDataLoaderService.java:515)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createSysAdmin(DefaultSystemDataLoaderService.java:195)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:273)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!


Below is attached the log file
[install.log](https://github.com/thingsboard/thingsboard/files/10609905/install.log)

Thanks!

**Comment by ban2derlog** [comment]
@StergiosT0 drop and create or simply use a new database .
ThingsBoard install script can't create entities that is already exist.
