### ISSUE TITLE
Anybody could give me a packaged ui-1.4.0.jar

### ISSUE THREAD

**Issue by rokily** [thingsboard/thingsboard#795]
I tried to rebuild thingsboard-release-1.4.0,  but I failed to build the ui project, through I work around by manually executing  update some scripts -> "npm install"->"npm run build" -> "mvn clean package -DskipTests" I got ui-1.4.0.jar, but it doesn't work when deploy to server, the server launched but the web page is empty, I can see nothing in browser, but lots of error in browser console.
So, I do nothing change for ui component, anyone could give me a correctly build package of ui-1.4.0.jar? thanks.

if possible, I still want to fix my issue of ui component, 
1. update scripts
   a. comment "//import 'flot.curvedlines/curvedLines';" in ui/src/app/widget/lib/flot-widget.js
   b. vi package.json removed "-p" in this line  "build": "cross-env NODE_ENV=production webpack"
        or, I see error like   """ERROR in bundle.ccb8b62a927e70d9965d.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/bufferutil/fallback.js:19,0]
Child extract-text-webpack-plugin:"""

2. "npm install":
at last, I still see below message
'''
[!] 26 vulnerabilities found [16182 packages audited]
    Severity: 24 Moderate | 2 Critical
    Run `npm audit` for more detail
'''

3. "npm run build", ui-1.4.0.jar was produced, but still some warnings in console:
a. 
WARNING in ./~/bindings/bindings.js
Critical dependencies:
81:22-40 the request of a dependency is an expression
81:43-53 the request of a dependency is an expression
 @ ./~/bindings/bindings.js 81:22-40 81:43-53

b. 
WARNING in ./~/bindings/package.json
Module parse failed: /thingsboard-release-1.4-bak/ui/node_modules/bindings/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (/thingsboard-release-1.4-bak/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/thingsboard-release-1.4-bak/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
...

c. 
WARNING in ./~/bindings/README.md
Module parse failed: /thingsboard-release-1.4-bak/ui/node_modules/bindings/README.md Unexpected token (2:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:3)
    at Parser.pp$4.raise (/thingsboard-release-1.4-bak/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/thingsboard-release-1.4-bak/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/thingsboard-release-1.4-bak/ui/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
.....
    at /thingsboard-release-1.4-bak/ui/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:408:3)
 @ ./~/bindings ^\.\/.*$

**Comment by rokily** [comment]
Some error message: 

After executed "npm install" ----> 
up to date in 15.532s
[!] 26 vulnerabilities found [16023 packages audited]
    Severity: 24 Moderate | 2 Critical
    Run `npm audit` for more detail

$ npm audit
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Missing: flot-curvedlines@git://github.com/MichaelZinsmaier/CurvedLines.git#master

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-05-19T15_04_32_000Z-debug.log


The error message in "Users/mac/.npm/_logs/2018-05-19T15_04_32_000Z-debug.log"

7 verbose Darwin 17.4.0
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "audit"
9 verbose node v10.0.0
10 verbose npm  v6.0.1
11 error code ELOCKVERIFY
12 error Errors were found in your package-lock.json, run  npm install  to fix them.
12 error     Missing: flot-curvedlines@git://github.com/MichaelZinsmaier/CurvedLines.git#master
13 verbose exit [ 1, true ]

**Comment by rokily** [comment]
I passed the build of UI project, but, after deploying, its empty in Browser, I see the error message in console below:

javascript.js:3 Uncaught TypeError: ace.require is not a function
    at javascript.js:3
    at Object.<anonymous> (javascript.js:5)
    at Object.<anonymous> (bundle.b432d66ba5d11ba67dfb.js:149461)
    at e (bootstrap b432d66ba5d11ba67dfb:73)
    at Object.<anonymous> (widget-editor.controller.js:23)
    at e (bootstrap b432d66ba5d11ba67dfb:73)
    at Object.<anonymous> (index.js:34)
    at e (bootstrap b432d66ba5d11ba67dfb:73)
    at Object.<anonymous> (index.js:48)
    at e (bootstrap b432d66ba5d11ba67dfb:73)
(anonymous) @ javascript.js:3
(anonymous) @ javascript.js:5
(anonymous) @ bundle.b432d66ba5d11ba67dfb.js:149461
e @ bootstrap b432d66ba5d11ba67dfb:73
(anonymous) @ widget-editor.controller.js:23
e @ bootstrap b432d66ba5d11ba67dfb:73
(anonymous) @ index.js:34
e @ bootstrap b432d66ba5d11ba67dfb:73
(anonymous) @ index.js:48
e @ bootstrap b432d66ba5d11ba67dfb:73
(anonymous) @ app.js:66
e @ bootstrap b432d66ba5d11ba67dfb:73
(anonymous) @ bundle.b432d66ba5d11ba67dfb.js:5
e @ bootstrap b432d66ba5d11ba67dfb:73
window.webpackJsonp @ bootstrap b432d66ba5d11ba67dfb:44
(anonymous) @ bundle.b432d66ba5d11ba67dfb.js:1
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module thingsboard due to:
Error: [$injector:nomod] Module 'thingsboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=thingsboard
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:377
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:10525
    at t (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:9998)
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:10310
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:19658
    at r (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:825)
    at h (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:19506)
    at rt (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:21433)
    at a (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:8075)
    at oe (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:8385)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=thingsboard&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'thingsboard'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dthingsboard%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A377%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A10525%0A%20%20%20%20at%20t%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A9998)%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A10310%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A19658%0A%20%20%20%20at%20r%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A825)%0A%20%20%20%20at%20h%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A19506)%0A%20%20%20%20at%20rt%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A21433)%0A%20%20%20%20at%20a%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A8075)%0A%20%20%20%20at%20oe%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A8385)
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:377
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:10525
    at t (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:9998)
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:10310
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:19658
    at r (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:825)
    at h (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:19506)
    at rt (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:21433)
    at a (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:8075)
    at oe (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:8385)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=thingsboard&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'thingsboard'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dthingsboard%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A377%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A10525%0A%20%20%20%20at%20t%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A9998)%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A10310%0A%20%20%20%20at%20http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A19658%0A%20%20%20%20at%20r%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A825)%0A%20%20%20%20at%20h%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A19506)%0A%20%20%20%20at%20rt%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A21433)%0A%20%20%20%20at%20a%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A8075)%0A%20%20%20%20at%20oe%20(http%3A%2F%2Fosvm%3A8080%2Fstatic%2Fbundle.b432d66ba5d11ba67dfb.js%3A519%3A8385)
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:377
    at http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:19934
    at r (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:825)
    at h (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:19506)
    at rt (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:21433)
    at a (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:8075)
    at oe (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:8385)
    at re (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:519:7624)
    at HTMLDocument.<anonymous> (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:524:8284)
    at c (http://osvm:8080/static/bundle.b432d66ba5d11ba67dfb.js:25:25165)

**Comment by untilbit** [comment]
I have issues with UI and cannt build it.

**Comment by vparomskiy** [comment]
please update to the latest version. an issue with ace package was already fixed
