### ISSUE TITLE
[Bug]  originator attributes is broken after upgrade to 3.4.3 from 3.3.4.1

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#7998]
Hello
after upgrading from 3.3.4.1 to 3.4.3 this node is broken if "Tell Failure" option is checked.

the issue is, it will report a failure with the missing data keys, but it will also not populate the existing fields into msg or metadata.

so if device has key1 and key2, and you are fetching key1, key2, and key3. and Tell Failure is checked, 

you will get error message that key3 is  not present in the DB, but key1 and key2 are not populated into OUT message as expected.

expected behavior:

TB reports fails message and reports error with missing datakeys, and existing datakeys are populated into msg or metadata.

actual behavior:

TB reports fails message and reports error, BUT existing keys are not populated into msg or metadata.

![image](https://user-images.githubusercontent.com/31729091/214854050-53555045-9348-4fb4-893f-fa6c358f2224.png)

java.lang.RuntimeException: The following attribute/telemetry keys is not present in the DB: 
	[SERVER_SCOPE]:[voice_tempAlertLocation]
	[LATEST_TS]:[door]

	at org.thingsboard.rule.engine.metadata.TbAbstractGetAttributesNode.reportFailures(TbAbstractGetAttributesNode.java:241)
	at org.thingsboard.rule.engine.metadata.TbAbstractGetAttributesNode.lambda$safePutAttributes$5(TbAbstractGetAttributesNode.java:129)
	at org.thingsboard.common.util.DonAsynchron$1.onSuccess(DonAsynchron.java:55)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1080)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by t0mZ4** [comment]
workaround: disable Tell Failure

**Comment by ashvayka** [comment]
I will let @YevhenBondarenko comment on this.

**Comment by YevhenBondarenko** [comment]
Hi @t0mZ4
