### ISSUE TITLE
Failed to instantiate module thingsboard due to: Error: [$injector:nomod] Module 'thingsboard' is not available! 

### ISSUE THREAD

**Issue by zhangwonderful** [thingsboard/thingsboard#803]
I downloaded the latest stable version 1.4, and started the project successfully. But I visited the address: 127.0.0.1:8080 in browser, the browser console output the errors as below:

javascript.js:3 Uncaught TypeError: ace.require is not a function
    at javascript.js:3
    at Object.<anonymous> (javascript.js:5)
    at Object.<anonymous> (bundle.8be2b43c2aa1cabcf7fb.js:149461)
    at e (bootstrap 8be2b43c2aa1cabcf7fb:73)
    at Object.<anonymous> (widget-editor.controller.js?6b0f:23)
    at e (bootstrap 8be2b43c2aa1cabcf7fb:73)
    at Object.<anonymous> (index.js?829b:34)
    at e (bootstrap 8be2b43c2aa1cabcf7fb:73)
    at Object.<anonymous> (index.js?7280:48)
    at e (bootstrap 8be2b43c2aa1cabcf7fb:73)
(anonymous) @ javascript.js:3
(anonymous) @ javascript.js:5
(anonymous) @ bundle.8be2b43c2aa1cabcf7fb.js:149461
e @ bootstrap 8be2b43c2aa1cabcf7fb:73
(anonymous) @ widget-editor.controller.js?6b0f:23
e @ bootstrap 8be2b43c2aa1cabcf7fb:73
(anonymous) @ index.js?829b:34
e @ bootstrap 8be2b43c2aa1cabcf7fb:73
(anonymous) @ index.js?7280:48
e @ bootstrap 8be2b43c2aa1cabcf7fb:73
(anonymous) @ app.js?ea9a:66
e @ bootstrap 8be2b43c2aa1cabcf7fb:73
(anonymous) @ bundle.8be2b43c2aa1cabcf7fb.js:5
e @ bootstrap 8be2b43c2aa1cabcf7fb:73
window.webpackJsonp @ bootstrap 8be2b43c2aa1cabcf7fb:44
(anonymous) @ bundle.8be2b43c2aa1cabcf7fb.js:1
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module thingsboard due to:
Error: [$injector:nomod] Module 'thingsboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=thingsboard
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:377
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:10525
    at t (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:9998)
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:10310
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:19658
    at r (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:825)
    at h (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:19506)
    at rt (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:21433)
    at a (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:8075)
    at oe (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:8385)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=thingsboard&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'thingsboard'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dthingsboard%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A377%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A10525%0A%20%20%20%20at%20t%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A9998)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A10310%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A19658%0A%20%20%20%20at%20r%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A825)%0A%20%20%20%20at%20h%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A19506)%0A%20%20%20%20at%20rt%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A21433)%0A%20%20%20%20at%20a%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A8075)%0A%20%20%20%20at%20oe%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A8385)
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:377
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:10525
    at t (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:9998)
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:10310
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:19658
    at r (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:825)
    at h (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:19506)
    at rt (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:21433)
    at a (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:8075)
    at oe (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:8385)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=thingsboard&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'thingsboard'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dthingsboard%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A377%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A10525%0A%20%20%20%20at%20t%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A9998)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A10310%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A19658%0A%20%20%20%20at%20r%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A825)%0A%20%20%20%20at%20h%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A19506)%0A%20%20%20%20at%20rt%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A21433)%0A%20%20%20%20at%20a%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A8075)%0A%20%20%20%20at%20oe%20(http%3A%2F%2F127.0.0.1%3A8080%2Fstatic%2Fbundle.8be2b43c2aa1cabcf7fb.js%3A519%3A8385)
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:377
    at http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:19934
    at r (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:825)
    at h (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:19506)
    at rt (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:21433)
    at a (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:8075)
    at oe (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:8385)
    at re (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:519:7624)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:524:8284)
    at c (http://127.0.0.1:8080/static/bundle.8be2b43c2aa1cabcf7fb.js:25:25165)
(anonymous) @ angular.js:68
(anonymous) @ angular.js:4640
r @ angular.js:321
h @ angular.js:4601
rt @ angular.js:4523
a @ angular.js:1758
oe @ angular.js:1779
re @ angular.js:1664
(anonymous) @ angular.js:31763
c @ jquery.js:3534
u @ jquery.js:3602
setTimeout (async)
Ee.readyException @ jquery.js:3826
(anonymous) @ jquery.js:3846
c @ jquery.js:3534
u @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
c @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
c @ jquery.js:3268
fireWith @ jquery.js:3398
u @ jquery.js:3622
setTimeout (async)
(anonymous) @ jquery.js:3640
c @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
c @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
g @ jquery.js:3888
jquery.js:510 [Violation] 'setTimeout' handler took 61ms

**Comment by zhangwonderful** [comment]
perform the command "npm run start", some warns were output to the console as followings:
WARNING in ./~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in D:\workspace\IoT\thingsboard-1.4\ui\node_modules\ws\lib
 @ ./~/ws/lib/BufferUtil.js 12:15-36

WARNING in ./~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in D:\workspace\IoT\thingsboard-1.4\ui\node_modules\ws\lib
 @ ./~/ws/lib/Validation.js 12:16-41
Child html-webpack-plugin for "index.html":

**Comment by vparomskiy** [comment]
It is a known problem that will be fixed in the next release.
Right now you can change ace-builds version to the 1.3.1 in the package.json file.
`"ace-builds": "1.3.1",`

**Comment by jacklicn** [comment]
download thingsboard mater branche code. see [https://github.com/thingsboard/thingsboard/pull/783](https://github.com/thingsboard/thingsboard/pull/783)
