### ISSUE TITLE
Error installing Thingsboard on Rpi4  "ThingsBoard installation failed!"

### ISSUE THREAD

**Issue by StergiosT0** [thingsboard/thingsboard#8041]
Hello, i tried to install on Debian Raspberry pi but i got the following error:

Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing SQL DataBase schema PostgreSQL specific indexes part: schema-entities-idx-psql-addon.sql
Installing DataBase schema for timeseries...
Installing SQL DataBase schema part: schema-ts-psql.sql
Successfully executed query: CREATE TABLE IF NOT EXISTS ts_kv_indefinite PARTITION OF ts_kv DEFAULT;
Loading system data...
Unexpected error during ThingsBoard installation!
org.thingsboard.server.dao.exception.DataValidationException: User with email '[sysadmin@thingsboard.org](mailto:sysadmin@thingsboard.org)' already present in database!
at org.thingsboard.server.dao.service.validator.UserDataValidator.validateDataImpl(UserDataValidator.java:137)
at org.thingsboard.server.dao.service.validator.UserDataValidator.validateDataImpl(UserDataValidator.java:39)
at org.thingsboard.server.dao.service.DataValidator.validate(DataValidator.java:55)
at org.thingsboard.server.dao.user.UserServiceImpl.saveUser(UserServiceImpl.java:115)
at org.thingsboard.server.dao.user.UserServiceImpl$$FastClassBySpringCGLIB$$83a3dd57.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
at org.thingsboard.server.dao.user.UserServiceImpl$$EnhancerBySpringCGLIB$$dff8f79b.saveUser()
at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createUser(DefaultSystemDataLoaderService.java:515)
at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createSysAdmin(DefaultSystemDataLoaderService.java:195)
at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:273)
at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
ThingsBoard installation failed!

Below i have attached the log file
[install.log](https://github.com/thingsboard/thingsboard/files/10609905/install.log)

Thanks!

**Comment by Backdraft007** [comment]
Is it a fresh installation? Which documentation do you follow?
Which steps do you have executed?
Seems that you you have calles a step twice or it is not a fresh installation.

**Comment by Stergios96Tousoulis** [comment]
https://thingsboard.io/docs/user-guide/install/rpi/?ubuntuThingsboardQueue=inmemory
Using the above guide

**Comment by Backdraft007** [comment]
Sure that you execute step 6 only once?
What happen when you start the service in step 7?

**Comment by StergiosT0** [comment]
I am not sure, maybe twice.

After service started nothing happend..

**Comment by Backdraft007** [comment]
Can you upload /var/log/thingsboard/thingsboard.log
You cannot open the WebUI on http://IP_of_Rpi4:8080? On a Raspberry it can be very slowly till the webserice started completely.

**Comment by StergiosT0** [comment]
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/10668953/thingsboard.log)

i have attached the log file

**Comment by Backdraft007** [comment]
For the fast way to investigate. Please reboot your raspberry, wait some minutes and try to open the WebUI with http://IP_of_RPi:8080
When you can't open the WebUI attach an actual log here.

Do you have other install other services on the Rpi? Maybe the port 8080 is blocked.
Please provide the ouput of `netstat -tulpn`

**Comment by StergiosT0** [comment]
I tried to open WebUi using http://ipofRpi:port but nothing.

By the way tried to change the port 8080 to 8082 by add the following in conf file: export HTTP_BIND_PORT=8082

![netstat1](https://user-images.githubusercontent.com/26569006/217186825-e5d64bd5-88e5-44c5-8689-fea187f1f203.jpg)

**Comment by StergiosT0** [comment]
is there any way to purge completly Thingsboard previous installation also postgresql then start to install again?

**Comment by Backdraft007** [comment]
Do you have running an mqtt broker on the pi?
Try to start thingsboard `sudo service start thingsboard` and upload thingsboard.log please.

**Comment by Backdraft007** [comment]
I don't think that an reinstallation will help.

**Comment by StergiosT0** [comment]
Is there any way to Drop thingsboard Db?

**Comment by Backdraft007** [comment]
Try to start Thingsboard and upload thingsboard.log

**Comment by StergiosT0** [comment]
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/10673453/thingsboard.log)

**Comment by StergiosT0** [comment]
Also installtion steps output

[terminal installation output steps.txt](https://github.com/thingsboard/thingsboard/files/10673502/terminal.installation.output.steps.txt)

**Comment by Backdraft007** [comment]
There is already a service running on port 1883. This is MQTT.
Post the output of `sudo service status thingsboard` and of `ps aux`

**Comment by StergiosT0** [comment]
[ps aux.txt](https://github.com/thingsboard/thingsboard/files/10673756/ps.aux.txt)
[thingsboard status.txt](https://github.com/thingsboard/thingsboard/files/10673757/thingsboard.status.txt)

**Comment by Backdraft007** [comment]
It is running.
Do you made this changes?
```
# Update ThingsBoard memory usage and restrict it to 256MB in /etc/thingsboard/conf/thingsboard.conf
export JAVA_OPTS="$JAVA_OPTS -Xms256M -Xmx256M"
```

**Comment by StergiosT0** [comment]
yes

**Comment by Backdraft007** [comment]
Ah I see a runnning mosquitto. Please stop mosquitto server and restart thingsboard.

**Comment by StergiosT0** [comment]
i did but nothing, i also change port to 8083 but same problem

Below is the output of thingsboard status:

thingsboard.service - thingsboard
     Loaded: loaded (/lib/systemd/system/thingsboard.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-02-07 10:21:35 CET; 2 days ago
   Main PID: 677 (thingsboard.jar)
      Tasks: 32 (limit: 4915)
        CPU: 9min 28.957s
     CGroup: /system.slice/thingsboard.service
             ├─677 /bin/bash /usr/share/thingsboard/bin/thingsboard.jar
             └─696 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Dplatform=deb -Dinsta>

Warning: journal has been rotated since unit was started, output may be incomplete.

**Comment by Backdraft007** [comment]
No problem. You are welcome. Close this issue please. :)
