### ISSUE TITLE
Azure Active Directory SSO implementation 

### ISSUE THREAD

**Issue by Zangetu121345** [thingsboard/thingsboard#8156]
I am trying to integrate azure ad sso for my thingsboard. I followed the documentation and made changes as required in my <b>thingsboard.yml</b> file and after restarting the login button does not appear.
Then i tried using my sysadmin account oAuth2 and created a custom login provider and after configuring it with my credentials provided my azure I am getting the button and it is also redirecting me to microsoft login page but after filling the details in that login section I am getting :
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Mar 01 12:08:01 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).
```
When i check my  thingsboard log it says:
```
2023-03-01 12:08:01,182 [http-nio-0.0.0.0-8080-exec-6] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.IllegalArgumentException: Missing attribute 'email' in attributes
        at org.springframework.security.oauth2.core.user.DefaultOAuth2User.<init>(DefaultOAuth2User.java:72)
        at org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.loadUser(DefaultOAuth2UserService.java:116)
        at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:109)
        at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:66)
        at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.authenticate(OidcAuthorizationCodeAuthenticationProvider.java:156)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
        at org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter.attemptAuthentication(OAuth2LoginAuthenticationFilter.java:195)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:178)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        
```
And the details i filled:
- Acess Token URI: https://login.microsoftonline.com/xx_azure_tenant_id_xx/oauth2/v2.0/token
- Authorization URI: https://login.microsoftonline.com/xx_azure_tenant_id_xx/oauth2/v2.0/authorize
- JWK URI: https://login.microsoftonline.com/xx_azure_tenant_id_xx/discovery/keys
- User info URI : https://graph.microsoft.com/v1.0/me

Mapper configuration:
- User name attribute Key: email
- Mapper Type : BASIC
- Email attribute key : email
- Tenant name Strategy: DOMAIN

I checked if there is any  issue with azure sso using postman and it is giving me id_token and when i am decoding that token it has email attribute in it .
Can anyone help me with what might be wrong in my case.

**Comment by ban2derlog** [comment]
hi, first - restore configuration in _**thingsboard.yml**_.
this was require previously, and now you can make all via Web UI.
second, try to use in User name attribute Key and Email attribute key - **_preferred_username_**
third, set scope to **_openid_** , **_profile_**
and check that this application in AD has right in API permissions for Graph API - **_openid_**

**Comment by Pankaj9410557422** [comment]
```
2023-03-02 16:56:00,785 [http-nio-0.0.0.0-8080-exec-3] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.IllegalArgumentException: Missing attribute 'preferred_username' in attributes
        at org.springframework.security.oauth2.core.user.DefaultOAuth2User.<init>(DefaultOAuth2User.java:72)
        at org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.loadUser(DefaultOAuth2UserService.java:116)
        at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:109)
        at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:66)
        at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.authenticate(OidcAuthorizationCodeAuthenticationProvider.java:156)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
        at org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter.attemptAuthentication(OAuth2LoginAuthenticationFilter.java:195)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:178)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
 ```
 I followed the steps you mentioned but it is still showing same error.Can you tell me what should be the value of JWK URI and User info URI value.

**Comment by ban2derlog** [comment]
you can find all endpoints in Azure AD in Endpoints - open link `OpenID Connect metadata document`
![image](https://user-images.githubusercontent.com/33271053/222699104-97b9694d-5e9f-4025-b72b-4971c76983de.png)
here is reference from OpenID page: ThingsBoard key - link\value from OpenID:
Access token URI - `token_endpoint`
Authoriation URI - `authorization_endpoint`
JSON Web Key - `jwks_uri`
User info URI is optional.

and check that you have this:
![image](https://user-images.githubusercontent.com/33271053/222700144-700b5425-d410-466c-9890-b6881dab7537.png)

**Comment by Zangetu121345** [comment]
I have provided all these values and also in my <b>API Permisions</b> i have ```openid email profile```.
After adding more logs in my log i added :
```
    <logger name="org.springframework.security" level="DEBUG"/>
    <logger name="org.springframework.security.oauth2" level="DEBUG"/>
```
I am getting 
```
2023-03-03 12:13:52,375 [http-nio-0.0.0.0-8080-exec-6] DEBUG o.s.security.web.FilterChainProxy - Securing GET /login/oauth2/code/?code=0.AWQAZcYwFGiqokaWTJIdQVhWuCVJzfWIAlVOsq4cFyGoM6dlAAA.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wUA9P-eluOE8ZOdrsqtgKLbyR-leMIULrRMCsG6KQjsNHqldfGTVOaSZH6LF8Lz6JhJmOtIKK58xkI-hWKkQ2ndcAUmbN3faQrkSdIMlJymKOId6BEgUuuzcfQi5NDECG-Hq84NOPtkAmKuLCqGmgdhhAEQhiG8eSJbWFzcv6VLgCFlN5C-vNLVZPg9AOW2DHXuYmbKlTIK88ma-tgWXCpM_s8hZTgv6X3e_LiOsbiJHjCml4mFHclE_CfY8H3t4f4UXFtLSVEJGxC5QWik2mAn1WAWH8NbMAJdRP643Ay0t6BQRBRCZvqVYBlSSZGzlysu49sXz5p5c3I0tkJrhrHcsaV9Boy-G1Ij9j1c1lx8_C3dkfqARyPbbVypzdQ2wQ6edHvJ18-aw9tdHP8J1G9Epg1XX_8R99JPrJlrBIxRjG3dxdA6kBph6TgxKPdD6zCMpLb5sDr82ZPvT4kQgpAyHn02KhrOUklKeBZmfxOq_RglBjzAwG_8vOfUch8zIdMS-n0oeyKSM-ZpgPAXfT6qWN-AxHNylS6UfQFnW-YfN8l_j2-iXCIs5HesxeqynxaFxCkfrTA99kfR2HE_cibVREKim98ammxv0edG21zXuMNo-73nuUo5O1kKSPNtb_y-dcWcEk3Zd355rkqEEyNXxTkfShGKy5mwSO-EJr3aMSBFZlRF0Xf5qNrEMboYQzceB9DWFJEOMqpT8kw3NFk0cDt35RRzEM555IXykxa9W9kPi26iWPAYveNWkJGhbl_qkDIzBmhSffJLMI41dMwGZ5zhx6jO4C9-c0TfotXFRxXTcxCCUMQm6Vx43QJ-wZPQ54RRiwNo4W_XinMaVRixi8vhy3M7ShOHGO_WFBPFcgMY8ByyemAM5cNdpT0BzHeHBtxBb9nED7qUE2U2iy3L8iOFfHTBRwxx4NwHI4DuygkIRUFhBt1wDRtth0eVGyV0Z-Dla8tTX0VhI8gqHWqhvw3UWY5kqS6kf73jX89b_3IxdireGNaNP3W4X6cyE6ytUDa0DIOUI2YndY77MJmOG5vcsEPwcpPOc1h5CVSHKf04AfNvW2a7Vv90jzaw99T9E7GL_ayv2tIwF9pweSxoJeERbUqXrtaGQjHJg3W2QqJkEfpUCovtc9EcM8mNHSTjcVW7ygaZnYjI765_PJjXpprzVTY-j4tOCKuv2xeYMLK_s2jziTxHtDLFrIq0_xE9FhGCc8233Z1GgAvjsNN9PIFOFAXL-2vj_JrevFsnfXt6sQW5xfxkSOBZD3jHzTR05FMIIJld6yc0s-1q9fz1EA&state=mZSIvbKDOLX3UTjjsRJZXX-Ve825kCp58YTbbsjJyLQ%3d&session_state=0406bff2-425b-49c6-a495-2d59a2da758c
2023-03-03 12:13:52,375 [http-nio-0.0.0.0-8080-exec-6] DEBUG o.s.s.w.c.SecurityContextPersistenceFilter - Set SecurityContextHolder to empty SecurityContext
2023-03-03 12:13:52,376 [http-nio-0.0.0.0-8080-exec-6] INFO  o.t.s.c.CustomOAuth2AuthorizationRequestResolver - This is apptoken:null
2023-03-03 12:13:53,007 [http-nio-0.0.0.0-8080-exec-6] DEBUG o.s.s.w.c.SecurityContextPersistenceFilter - Cleared SecurityContextHolder to complete request
2023-03-03 12:13:53,008 [http-nio-0.0.0.0-8080-exec-6] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.IllegalArgumentException: Missing attribute 'email' in attributes
        at org.springframework.security.oauth2.core.user.DefaultOAuth2User.<init>(DefaultOAuth2User.java:72)
        at org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.loadUser(DefaultOAuth2UserService.java:116)
        at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:109)
        at org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService.loadUser(OidcUserService.java:66)
        at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.authenticate(OidcAuthorizationCodeAuthenticationProvider.java:156)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
        at org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter.attemptAuthentication(OAuth2LoginAuthenticationFilter.java:195)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
```
Is the problem in my azure end or thingsboard end?

**Comment by ban2derlog** [comment]
this error means that ThingsBoard can't find `attribute` key in JWT that comes from Azure AD.
please look carefully on API permissions, there can be issue that to apply them you need approve from Global Administrator\Higher Authority.
additionally, check that in Azure: Authorization - Implicit grant and hybrid flows - enabled Access Token for this application.
