### ISSUE TITLE
Downlink to ChirpStack Doesn‘t Work

### ISSUE THREAD

**Issue by xiaoyu4122** [thingsboard/thingsboard#8196]
I applied the PE Thingsboard. Also, I tested the uplink(from chirpstack to thingsboard) function and it worked well. However, the downlink (from thingsboard to chirpstack) does not work. I followed the guides and set up the rule chain but it does not work. Can anyone figure this out?

**Comment by mullerch** [comment]
I was not able to make it work with both ChirpStack v3 and v4.

There is a lack of documentation and debug features to help diagnose the issue.

**Comment by mullerch** [comment]
I was able to make it work for v3, but not v4.

**Comment by danialothman** [comment]
Hi @mullerch, I am experiencing the same issue, although I have **not** tested downlink with ChirpStack v3, do you by any luck have gotten downlink to v4 work?

my setup:
chirpstack version 4.6.0
thingsboard version 3.6.2PAAS

**Comment by mullerch** [comment]
Hi @danialothman, I did not give it a try. However, this is what I got from TB support :

> About ChirpStack v4 - ThingsBoard doesn’t have issues with Uplinks and Downlinks with ChirpStack v4.
I additionally tested this, and all work as expected if you set it up correctly.
ChirpStack v4 installed on clean server or Docker Compose can send Uplink messages and receive Downlink messages.
In tested situation - ThingsBoard sends Downlink on every new message that sends device data:

So it should work. Using this config:

> From ThingsBoard side - ChirpStack Integration.
> From ChirpStack side - HTTP integration, as described in guide.
> ![image](https://github.com/thingsboard/thingsboard/assets/1092115/f3a8f127-8fae-494f-b465-6e722bc1b9e9)
> Keep in mind, that in Integration there is ChirpStack API endpoint.
> About downlink - it is almost same as in example.
> ![image](https://github.com/thingsboard/thingsboard/assets/1092115/e09e0df3-2a45-4bba-ae6c-1ae89a99ae24)
> There is only change that DevEUI and fPort used not from Client Attributes but from Shared, but this is only because it was easier to use on my DEV environment.
> Main logic for Downlink is used same as [here](https://thingsboard.io/docs/user-guide/integrations/chirpstack/) (Rule Chains, Converters).

Hope this helps.

**Comment by niho06** [comment]
hello,

I have followed all your steps but nothing runs downlink:
![image](https://github.com/thingsboard/thingsboard/assets/122945130/41c8b5c8-ab9b-40b4-87b9-6a3dd2023dd8)


![image](https://github.com/thingsboard/thingsboard/assets/122945130/fdac00c3-7a0f-454d-a05d-9de4bd843263)
that is the error of this image

`org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://127.0.0.0:8090/api/devices/4b7709bb66035c29/queue": Network is unreachable (connect failed); nested exception is java.net.SocketException: Network is unreachable (connect failed)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:474)
	at org.thingsboard.integration.http.chirpstack.ChirpStackIntegration.processDownLinkMsg(ChirpStackIntegration.java:163)
	at org.thingsboard.integration.http.chirpstack.ChirpStackIntegration.onDownlinkMsg(ChirpStackIntegration.java:137)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.lambda$handleDownlink$2(DefaultIntegrationManagerService.java:251)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.net.SocketException: Network is unreachable (connect failed)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:277)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:376)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:397)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782)
	... 11 more
`

![image](https://github.com/thingsboard/thingsboard/assets/122945130/102d5eeb-4f79-4e70-a139-6ec89d827e7e)

Can you help me see what I'm doing wrong?

about metadata.shared_DevEui: metadata.cs_DevEui must be changed so that it can obtain the data because shared client only has the sending data

Best Resgard

**Comment by danialothman** [comment]
> Hi @danialothman, I did not give it a try. However, this is what I got from TB support :
> 
> > About ChirpStack v4 - ThingsBoard doesn’t have issues with Uplinks and Downlinks with ChirpStack v4.
> > I additionally tested this, and all work as expected if you set it up correctly.
> > ChirpStack v4 installed on clean server or Docker Compose can send Uplink messages and receive Downlink messages.
> > In tested situation - ThingsBoard sends Downlink on every new message that sends device data:
> 
> So it should work. Using this config:
> 
> > From ThingsBoard side - ChirpStack Integration.
> > From ChirpStack side - HTTP integration, as described in guide.
> > ![image](https://private-user-images.githubusercontent.com/1092115/306297809-f3a8f127-8fae-494f-b465-6e722bc1b9e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTAzNzEsIm5iZiI6MTcwOTExMDA3MSwicGF0aCI6Ii8xMDkyMTE1LzMwNjI5NzgwOS1mM2E4ZjEyNy04ZmFlLTQ5NGYtYjQ2NS02ZTcyMmJjMWI5ZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDg0NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZjODI0ZGY1OGE3MDYwZTMyNzYxNTZjZDRmYjIzZGZjYzBjMjRmOWI3M2E2ZjQwYzcyODg5ODZkMjkxOTEzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mjW91sRtSdQ35SUl33TTEfUOIAtmMlY_Gj72isPwI24)
> > Keep in mind, that in Integration there is ChirpStack API endpoint.
> > About downlink - it is almost same as in example.
> > ![image](https://private-user-images.githubusercontent.com/1092115/306297366-e09e0df3-2a45-4bba-ae6c-1ae89a99ae24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTAzNzEsIm5iZiI6MTcwOTExMDA3MSwicGF0aCI6Ii8xMDkyMTE1LzMwNjI5NzM2Ni1lMDllMGRmMy0yYTQ1LTRiYmEtYWU2Yy0xYWU4OWE5OWFlMjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDg0NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRmMGM5OWE4YjgyMjhmNGYzMGM0NjA2NGE4YTcwMTcxZmY3ZjNmNWU4OTBlMzBiMDNkMDhiNjVmMmU5ZWU0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.njsaQuDcOSa7y9ELJtLTf_t8rTPtr4uTcPr_KEZ6xbU)
> > There is only change that DevEUI and fPort used not from Client Attributes but from Shared, but this is only because it was easier to use on my DEV environment.
> > Main logic for Downlink is used same as [here](https://thingsboard.io/docs/user-guide/integrations/chirpstack/) (Rule Chains, Converters).
> 
> Hope this helps.

Thanks so much! Pointing my application url to 8090 solved it for me!

**Comment by niho06** [comment]
Hello everyone, 

what I understand about my situation is that I am using ThingsBoard cloud. so when it tries to send downlink it doesn't find my Chirpstack V4 server because I don't have public NAT or port forwarding.

Can you confirm that you are working on ThingsBoard PE on-premise?

Greetings

**Comment by danialothman** [comment]
> Hello everyone,
> 
> what I understand about my situation is that I am using ThingsBoard cloud. so when it tries to send downlink it doesn't find my Chirpstack V4 server because I don't have public NAT or port forwarding.
> 
> Can you confirm that you are working on ThingsBoard PE on-premise?
> 
> Greetings

Hey @niho06 I am on ThingsBoard Cloud. You can use a service like ngrok, run it on a machine which is hosting your ChirpStack instance. I am using ChirpStack-Docker for tests. 

start ngrok on terminal `ngrok http http://localhost:8090`. 
My issue was I was pointing it to 8080, the downlink from ThingsBoard Cloud requires ChirpStack API since I noticed below was the response:
`INFO gRPC{uri=/api/devices/0000000000000000/queue}: chirpstack::api: Finished processing request status="400"`

Use the public link generated by ngrok on the integration detail for the 'application url' in ThingsBoard Cloud integration.

everything else are from the ChirpStack integration [doc](https://thingsboard.io/docs/paas/user-guide/integrations/chirpstack/)

Note: 
Make sure the Device/s on ThingsBoard relations, 'Outbound relations' have an entry 
Type: 'ManagedByIntegration'
To entity type: 'Integration'
To entity name: '_integration name_'

**Comment by xTwigx** [comment]
Hi has anyone managed to do this?

I have a chirpstack http integration sending to thingsboard and im trying to send a downlink to create queues.

This is my downlink data convertor:
![image](https://github.com/user-attachments/assets/f6079084-c866-4781-9c07-bd1039853dec)


But then the integration gets a Downlink: ATTRIBUTES_UPDATED type. With the following message:

![image](https://github.com/user-attachments/assets/a095a602-da05-4708-adbb-d1a07c05b226)
