### ISSUE TITLE
[Bug] Baltimore CyberTrust Root Certificate interpreted as Empty input for SAS credential in Azure IoT Hub integration

### ISSUE THREAD

**Issue by Kiwikisser** [thingsboard/thingsboard#8198]
**Describe the bug**
When trying to integrate Azure IoT Hub in ThingsBoard Cloud, it is not clear which certificate is required as SAS credential or how it should be formatted. All documentation points to the Baltimore CyberTrust Root certificate, however importing it in various ways results in either TLS factory creation or SAS token build errors.

The documentation I follow:
https://thingsboard.io/docs/paas/user-guide/integrations/azure-iot-hub/
> If Shared Access Signature credentials type is selected, the following configuration should be provided:
> * SAS Key - it is key from your device in [Azure IoT Hub](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-authenticate-downstream-device#symmetric-key-authentication)
> * CA certificate file, by default used Baltimore certificate. More about certificates [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#tlsssl-configuration)

Where SAS Key is the device key provided by Azure IoT Hub and CA certificate file `BaltimoreCyberTrustRoot.crt`.

The last bullet points to Azure documentation on which certificate is used for clients and how to configure TLS/SSL over MQTT using the certificate. It also links to the Baltimore CyberTrust Root certificate, but written out in the `certs.c` file ([certs.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/certs/certs.c)). 
> * \<local path to digicert.cer\> is the path to a local file that contains the DigiCert Baltimore Root certificate. You can create this file by copying the certificate information from [certs.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/certs/certs.c) in the Azure IoT SDK for C. Include the lines -----BEGIN CERTIFICATE----- and -----END CERTIFICATE-----, remove the " marks at the beginning and end of every line, and remove the \r\n characters at the end of every line.

The string copied into a separate `.cer` file, removing the quotations `"` and `\r\n`'s results in a different input exception, occurring from the SAS token build attempt.

**Your Server Environment**
* cloud.thingsboard.io

**Your Client Environment**
* OS: Windows 10 
* Browser: Edge

**Your Device**
* Connectivity
  * MQTT
  * Integration: Azure IoT Hub
* Device vendor and model
* Device simulation from: https://learn.microsoft.com/en-us/azure/iot-develop/quickstart-send-telemetry-iot-hub?pivots=programming-language-ansi-c

**To Reproduce**
https://thingsboard.io/docs/paas/user-guide/integrations/azure-iot-hub/
Set up Azure IoT Hub
Set up device and generate SAS token
Set up ThingsBoard Cloud trial environment
Set up decoder in ThingsBoard
Make new Integration item of Azure IoT Hub type
Fill in Hostname, Device ID, SAS credentials with Baltimore CyberTrust Root Certificate, set up topic filter
Receive error on Creating TLS factory

**Expected behavior**
Accept the certificate required from the provided documentation

**Additional context**
Stacktrace for providing the `BaltimoreCyberTrustRoot.crt`:
```
java.lang.RuntimeException: Creating TLS factory failed!
	at org.thingsboard.integration.mqtt.azure.AzureIotHubSasCredentials.initSslContext(AzureIotHubSasCredentials.java:72)
	at org.thingsboard.integration.mqtt.azure.AzureIotHubIntegration$1.initSslContext(AzureIotHubIntegration.java:73)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initSslContext(AbstractMqttIntegration.java:245)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initClient(AbstractMqttIntegration.java:209)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.init(BasicMqttIntegration.java:75)
	at org.thingsboard.integration.mqtt.azure.AzureIotHubIntegration.init(AzureIotHubIntegration.java:51)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.update(AbstractMqttIntegration.java:107)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.processUpdateEvent(DefaultIntegrationManagerService.java:581)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.update(DefaultIntegrationManagerService.java:528)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.tryUpdate(DefaultIntegrationManagerService.java:494)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.lambda$scheduleIntegrationEvent$9(DefaultIntegrationManagerService.java:662)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:115)
	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
	at org.thingsboard.integration.mqtt.azure.AzureIotHubSasCredentials.readCertFile(AzureIotHubSasCredentials.java:101)
	at org.thingsboard.integration.mqtt.azure.AzureIotHubSasCredentials.createAndInitTrustManagerFactory(AzureIotHubSasCredentials.java:82)
	at org.thingsboard.integration.mqtt.azure.AzureIotHubSasCredentials.initSslContext(AzureIotHubSasCredentials.java:67)
	... 16 more
Caused by: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:111)
	... 20 more

```

Stacktrace for providing the manually created `.cer` certificate in [certs.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/certs/certs.c):
```
java.lang.RuntimeException: Failed to build SAS token!!!
	at org.thingsboard.common.util.AzureIotHubUtil.buildSasToken(AzureIotHubUtil.java:95)
	at org.thingsboard.integration.mqtt.azure.AzureIotHubIntegration$1.configure(AzureIotHubIntegration.java:82)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.initClient(AbstractMqttIntegration.java:221)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.init(BasicMqttIntegration.java:75)
	at org.thingsboard.integration.mqtt.azure.AzureIotHubIntegration.init(AzureIotHubIntegration.java:51)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.update(AbstractMqttIntegration.java:107)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.processUpdateEvent(DefaultIntegrationManagerService.java:581)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.lambda$reInitIntegrations$10(DefaultIntegrationManagerService.java:673)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
	at org.thingsboard.server.service.integration.DefaultIntegrationManagerService.reInitIntegrations(DefaultIntegrationManagerService.java:669)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:736)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
	at org.thingsboard.common.util.AzureIotHubUtil.buildSasToken(AzureIotHubUtil.java:87)
	... 15 more
```

**Comment by Kiwikisser** [comment]
After a lot of trial and error with combining variations of SAS tokens and certificates, finally a connection resulted in success.

The required certificate was: `DigiCertGlobalRootG2.crt.pem`, downloaded from: https://www.digicert.com/kb/digicert-root-certificates.htm

The SAS token required to be pasted into the SAS key credential field was the Base64 string in the latter part of the primary connection string, found under the device identity in IoT Hub:

```
HostName=thingsboard-integration-################.azure-devices.net;DeviceId=MyFirstDevice;SharedAccessKey=<BASE64_STRING_################>
```

Hostname is already a field in the IoT Hub integration in ThingsBoard, so that's not necessary to be copied. Device ID also has it own field, thus doesn't have to be included either. Most importantly, inserting anything that is not a Base64 value in the SAS key field will result in a failure to build the SAS token, originating from the java decode function as seen in the 2nd stack trace in the original post. This leaves the Base64 string as only option to put into the SAS key field.

In hindsight I discovered the primary key from the device in Azure IoT Hub is the one used at the end of the SAS connection string. So this primary key is supposed to be copied and used for the SAS key field in ThingsBoard.

![image](https://user-images.githubusercontent.com/25525622/224722807-d38e5445-0523-4d6a-95f5-aa29c9bfbd99.png)

I'm incredibly disappointed with the lack of guidance in ThingsBoard documentation for setting up an integration. The steps:

> SAS Key - it is key from your device in [Azure IoT Hub](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-authenticate-downstream-device#symmetric-key-authentication)

and

> CA certificate file, by default used Baltimore certificate. More about certificates [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#tlsssl-configuration)

do no provide, in any way, concrete enough information to reliably set up an Azure IoT Hub integration with ThingsBoard.


I have created a separate issue for this lack of documentation as I will close this one now. 

#8209

**Comment by Kiwikisser** [comment]
IoT Hub connection status reverted back to Failed soon after the first Sucess. Changing CA certificate to the `BaltimoreCyberTrustRoot.crt.pem` resulted in Sucess again. For now.
