### ISSUE TITLE
[Question] When I upgraded the version, ts_kv_indefinite reported an error

### ISSUE THREAD

**Issue by znnspace** [thingsboard/thingsboard#8347]
**Description**

2023-04-12 13:58:02,636 [tb-core-usage-stats-consumer-47-thread-1] WARN  o.t.s.s.q.DefaultTbCoreConsumerService - [a3fecd8a-7bec-4e36-9f3e-6fb1eff768c1] Failed to process usage stats: TbProtoQueueMsg(key=99a0eb08-190d-43e1-9dd4-5f6bb627dfcd, value=tenantIdMSB: 1405474927960789426
tenantIdLSB: -9187201950435737472
values {
  key: "RE_EXEC_COUNT"
  value: 2
}
, headers=org.thingsboard.server.queue.common.DefaultTbQueueMsgHeaders@262f0f7e)
java.lang.RuntimeException: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [CREATE TABLE IF NOT EXISTS ts_kv_2023_04 PARTITION OF ts_kv FOR VALUES FROM (1680307200000) TO (1682899200000)]; ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row; nested exception is org.postgresql.util.PSQLException: ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row
	at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.savePartition(JpaSqlTimeseriesDao.java:154)
	at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.savePartitionIfNotExist(JpaSqlTimeseriesDao.java:135)
	at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.save(JpaSqlTimeseriesDao.java:84)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.doSaveAndRegisterFuturesFor(BaseTimeseriesService.java:219)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.saveAndRegisterFutures(BaseTimeseriesService.java:206)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.doSave(BaseTimeseriesService.java:185)
	at org.thingsboard.server.dao.timeseries.BaseTimeseriesService.save(BaseTimeseriesService.java:169)
	at org.thingsboard.server.service.telemetry.DefaultTelemetrySubscriptionService.saveAndNotifyInternal(DefaultTelemetrySubscriptionService.java:179)
	at org.thingsboard.server.service.telemetry.DefaultTelemetrySubscriptionService.saveAndNotifyInternal(DefaultTelemetrySubscriptionService.java:174)
	at jdk.internal.reflect.GeneratedMethodAccessor232.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy295.saveAndNotifyInternal(Unknown Source)
	at org.thingsboard.server.service.apiusage.DefaultTbApiUsageStateService.processEntityUsageStats(DefaultTbApiUsageStateService.java:220)
	at org.thingsboard.server.service.apiusage.DefaultTbApiUsageStateService.process(DefaultTbApiUsageStateService.java:182)
	at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.handleUsageStats(DefaultTbCoreConsumerService.java:433)
	at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.lambda$launchUsageStatsConsumer$8(DefaultTbCoreConsumerService.java:361)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.thingsboard.server.service.queue.DefaultTbCoreConsumerService.lambda$launchUsageStatsConsumer$11(DefaultTbCoreConsumerService.java:357)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [CREATE TABLE IF NOT EXISTS ts_kv_2023_04 PARTITION OF ts_kv FOR VALUES FROM (1680307200000) TO (1682899200000)]; ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row; nested exception is org.postgresql.util.PSQLException: ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:393)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:431)
	at org.thingsboard.server.dao.sqlts.insert.sql.SqlPartitioningRepository.save(SqlPartitioningRepository.java:52)
	at org.thingsboard.server.dao.sqlts.insert.sql.SqlPartitioningRepository$$FastClassBySpringCGLIB$$7d66494c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.thingsboard.server.dao.sqlts.insert.sql.SqlPartitioningRepository$$EnhancerBySpringCGLIB$$562a161f.save(<generated>)
	at org.thingsboard.server.dao.sqlts.sql.JpaSqlTimeseriesDao.savePartition(JpaSqlTimeseriesDao.java:145)
	... 26 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: updated partition constraint for default partition "ts_kv_indefinite" would be violated by some row
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:422)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)
	... 44 common frames omitted

**Environment**
 * OS:  win10
 * ThingsBoard: 3.4.3

**Comment by Ultrazombie** [comment]
Hello @znnspace 
Is your problem still relevant?

**Comment by trikimiki** [comment]
closed due to inactivity
