### ISSUE TITLE
MqttGatewayService - Error getting attributes

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard#835]
After connecting a device through Mqtt, following error messages occur:

```
2018-06-04 17:23:40,059 [MQTT Call: e7055fe1-e48b-4d6c-bd7b-340c5a59b0db] INFO  o.t.g.s.gateway.MqttGatewayService - [WeatherStation] Device Connected!
2018-06-04 17:23:40,061 [MQTT Call: e7055fe1-e48b-4d6c-bd7b-340c5a59b0db] TRACE o.t.g.s.gateway.MqttGatewayService - [WeatherStation][4] Updating device telemetry: [BasicTsKvEntry{ts=1528125819958, kv=DoubleDataEntry{value=54.1} BasicKvEntry{key='temperature'}}]
2018-06-04 17:23:40,068 [MQTT Call: e7055fe1-e48b-4d6c-bd7b-340c5a59b0db] DEBUG o.t.g.e.m.client.MqttBrokerMonitor - Scheduling keep alive timer for device WeatherStation with timeout = 60000
2018-06-04 17:23:40,069 [MQTT Call: e7055fe1-e48b-4d6c-bd7b-340c5a59b0db] DEBUG o.e.p.c.m.internal.CommsCallback - e7055fe1-e48b-4d6c-bd7b-340c5a59b0db: notify spaceAvailable
2018-06-04 17:23:40,069 [MQTT Call: e7055fe1-e48b-4d6c-bd7b-340c5a59b0db] DEBUG o.e.p.c.m.internal.CommsCallback - e7055fe1-e48b-4d6c-bd7b-340c5a59b0db: wait for workAvailable
2018-06-04 17:23:40,540 [http-nio-0.0.0.0-9090-ClientPoller-1] DEBUG o.apache.tomcat.util.net.NioEndpoint - timeout completed: keys processed=0; now=1528125820540; nextExpiration=1528125820539; keyCount=0; hasEvents=false; eval=false
2018-06-04 17:23:40,540 [http-nio-0.0.0.0-9090-ClientPoller-0] DEBUG o.apache.tomcat.util.net.NioEndpoint - timeout completed: keys processed=0; now=1528125820540; nextExpiration=1528125820539; keyCount=0; hasEvents=false; eval=false
2018-06-04 17:23:41,198 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - Sending message [MqttPersistentMessage(id=a5d80810-5e15-4946-8493-fa5d415e6332, timestamp=0, deviceId=null, messageId=1, topic=v1/devices/me/attributes/request/1, payload=[123, 34, 115, 104, 97, 114, 101, 100, 34, 58, 34, 99, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 34, 125])]
2018-06-04 17:23:41,198 [pool-3-thread-1] INFO  o.t.g.service.MqttMessageSender - ThingsBoard MQTT connection failed. Reconnecting in [3000] milliseconds
2018-06-04 17:23:41,199 [pool-4-thread-1] WARN  o.t.g.s.gateway.MqttGatewayService - Error getiing attributes
nl.jk5.mqtt.ChannelClosedException: Channel is closed
	at nl.jk5.mqtt.MqttClientImpl.sendAndFlushPacket(MqttClientImpl.java:347)
	at nl.jk5.mqtt.MqttClientImpl.publish(MqttClientImpl.java:295)
	at nl.jk5.mqtt.MqttClientImpl.publish(MqttClientImpl.java:263)
	at org.thingsboard.gateway.service.MqttMessageSender.publishMqttMessage(MqttMessageSender.java:105)
	at org.thingsboard.gateway.service.MqttMessageSender.run(MqttMessageSender.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2018-06-04 17:23:41,199 [pool-4-thread-1] WARN  o.t.g.service.MqttMessageReceiver - Failed to send message [MqttPersistentMessage(id=a5d80810-5e15-4946-8493-fa5d415e6332, timestamp=0, deviceId=null, messageId=1, topic=v1/devices/me/attributes/request/1, payload=[123, 34, 115, 104, 97, 114, 101, 100, 34, 58, 34, 99, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 34, 125])] due to [{}]
nl.jk5.mqtt.ChannelClosedException: Channel is closed
```
Although the Mqtt device (with the name "WeatherStation") is connected through the tb-gateway, there is no automatically provisioned device on my dashboard. Also the "latest telemetry" for the gateway device is empty.
Why does the tb-gateway send a mqtt message with the topic "v1/devices/me/attributes/request/1" to the mosquitto broker that I am using ? For what purpose are required the device attributes?
In the mqtt-json file there are no attributes defined:

```
{
  "brokers": [
    {
      "host": "127.0.0.1",
      "port": 22000,
      "ssl": false,
      "retryInterval": 3000,
      "credentials": {
        "type": "anonymous"
      },
      "mapping": [
    {
          "topicFilter": "WeatherStation",
          "converter": {
            "type": "json",
            "filterExpression": "",
            "deviceNameTopicExpression": "^(.*)$",
            "timeout": 60000,
            "timeseries": [
              {
                "type": "double",
                "key": "temperature",
                "value": "${$.value}"
              }
            ]
          }
    }
]
}
]
}
```

**Comment by mp-loki** [comment]
please provide your tb-gateway.yml as well

**Comment by abrasat** [comment]
Problem was related to wrong access token, thx for support.
