### ISSUE TITLE
[Bug] Update broke my MQTT integration?

### ISSUE THREAD

**Issue by SpieringsAE** [thingsboard/thingsboard#8607]
**Describe the bug**
This morning after 10:25:08 (GMT+2) my MQTT integration broke and the links on my homepage to my various dashboards suddenly broke. I managed to fix this last one, but I'm no longer getting any telemetry/attributes from my devices.

This error shows up in my uplink converter: 

```
java.lang.RuntimeException: No compiled script found for scriptId: [61f0d28d-c41a-4453-8944-ab644cff4269]!
	at org.thingsboard.script.api.AbstractScriptInvokeService.error(AbstractScriptInvokeService.java:301)
	at org.thingsboard.script.api.AbstractScriptInvokeService.invokeScript(AbstractScriptInvokeService.java:158)
	at org.thingsboard.integration.api.converter.ScriptUplinkEvaluator.execute(ScriptUplinkEvaluator.java:61)
	at org.thingsboard.integration.api.converter.ScriptUplinkDataConverter.doConvertUplink(ScriptUplinkDataConverter.java:79)
	at org.thingsboard.integration.api.converter.AbstractUplinkDataConverter.convertUplink(AbstractUplinkDataConverter.java:79)
	at org.thingsboard.integration.api.AbstractIntegration.convertToUplinkDataListAsync(AbstractIntegration.java:273)
	at org.thingsboard.integration.api.AbstractIntegration.convertToUplinkDataList(AbstractIntegration.java:283)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.doProcess(BasicMqttIntegration.java:137)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.doProcess(BasicMqttIntegration.java:65)
	at org.thingsboard.integration.mqtt.AbstractMqttIntegration.process(AbstractMqttIntegration.java:161)
	at org.thingsboard.integration.mqtt.basic.BasicMqttIntegration.lambda$subscribeToTopics$2(BasicMqttIntegration.java:118)
	at org.thingsboard.mqtt.MqttChannelHandler.invokeHandlersForIncomingPublish(MqttChannelHandler.java:124)
	at org.thingsboard.mqtt.MqttChannelHandler.handlePublish(MqttChannelHandler.java:198)
	at org.thingsboard.mqtt.MqttChannelHandler.channelRead0(MqttChannelHandler.java:61)
	at org.thingsboard.mqtt.MqttChannelHandler.channelRead0(MqttChannelHandler.java:41)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.thingsboard.mqtt.MqttPingHandler.channelRead(MqttPingHandler.java:71)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOp...[truncated 494 symbols]
```

after 10:25:13 it shows no more events in my uplink converter.

I noticed that the website had changed aswell, the interface for example. So I think some update has happened.

**Your Server Environment**

* cloud.thingsboard.io (I think its this? everything is in the browser)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS] 
Ubuntu 20.04
* Browser [e.g. chrome, safari] 
Firefox
* Version [e.g. 22]
113.0.1

**Your Device**

* Connectivity
MQTT (broker is still functioning properly)
* Device vendor and model
Many affected types and models but they are all embedded Linux systems, but they are operating as usual

**To Reproduce**
No idea how to reproduce this

**Expected behavior**

My dashboards continuing to function when I don't touch them.
Uplink converter receives messages from our MQTT broker and then passes them along to our dashboards.
MQTT broker is functioning btw I have checked it.

**Screenshots**

![Screenshot from 2023-05-23 12-48-52](https://github.com/thingsboard/thingsboard/assets/91117176/94819a8c-2629-4fbd-ba46-270d36eb1cd2)

event log of the uplink converter

![Screenshot from 2023-05-23 12-50-35](https://github.com/thingsboard/thingsboard/assets/91117176/52695705-b90b-4508-8ca5-f8650504db88)

shows devices becoming "inactive" around 10:25

**Comment by SpieringsAE** [comment]
Awesome thank you!
