### ISSUE TITLE
[Bug] TBEL runtime doesnt recognize decodeToJson

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [thingsboard/thingsboard#8780]
**Describe the bug**

**Your Server Environment**

* own setup
  * cloud deployment
  * ThingsBoard Version
 * OS:  Linux (ubuntu 20.04)

**Your Device**

* Connectivity
  * Integration: TCP 
* Teltonika FMC003

**To Reproduce**
1. Create a TBEL script
2. Add binary input
3. convert to text, then manipulate the text
4. Add `decodeToJson(stringToBytes(yourString))` to the TBEL code
5. Wait for messages to arrive

**Expected behavior**
This problem seems to be rather weird. Using the exact same payload that errors out during normal workflows, manual testing passes without any issue. This is also the right behaviour. The problem is that when it's parsing normal message, it constantly fails. It's weird to me, but there is nothing I can do, as manual testing again works.

**Stacktrace**
```java
java.util.concurrent.ExecutionException: org.thingsboard.script.api.TbScriptException: [Error: Invalid statement: decodeToJson(stringToBytes(test))]
[Near : {... var json = decodeToJson(stringToBytes(tes ....}]
                        ^
[Line: 38, Column: 12]
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at org.thingsboard.integration.api.AbstractIntegration.convertToUplinkDataList(AbstractIntegration.java:279)
	at org.thingsboard.integration.tcpip.AbstractIpIntegration.getUplinkDataList(AbstractIpIntegration.java:301)
	at org.thingsboard.integration.tcpip.AbstractIpIntegration.process(AbstractIpIntegration.java:179)
	at org.thingsboard.integration.tcpip.AbstractIpIntegration$AbstractChannelHandler.channelRead0(AbstractIpIntegration.java:339)
	at org.thingsboard.integration.tcpip.AbstractIpIntegration$AbstractChannelHandler.channelRead0(AbstractIpIntegration.java:321)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.thingsboard.script.api.TbScriptException: [Error: Invalid statement: decodeToJson(stringToBytes(test))]
[Near : {... var json = decodeToJson(stringToBytes(tes ....}]
                        ^
[Line: 38, Column: 12]
	at org.thingsboard.script.api.tbel.DefaultTbelInvokeService.lambda$doInvokeFun...[truncated 5461 symbols]
```

**Comment by Ultrazombie** [comment]
decodeToJson already implemented.
https://thingsboard.io/docs/user-guide/tbel/#decodetojson. 
Please upgrade your thingsboard service to the latest version
