### ISSUE TITLE
[Bug] 3.5.1 PE - New tenants fails to receive telemetry data

### ISSUE THREAD

**Issue by olheimerspg** [thingsboard/thingsboard#8794]
**Describe the bug**
After upgrade from 3.4.4 to 3.5.1 PE we face the following problem.

When we add a new tenant and add a device to it and send data via http to the device we get a 500 Server error.
For existing tenants - which we had added in 3.4.4 PE the data can still be received. Even if we add a new device to an pre 3.5.1 tenant the data is received as expected.

**Your Server Environment**
* own setup
  * Kubernetes cloud deployment
  * ThingsBoard 3.5.1 PE

**To Reproduce**
1. Go to sysadmin console.
2. Add a new tenant with default profile
3. Add a new tenant administrator
4. Login as the new tenant administrator
5. Add device with default profile
6. Copy access token and send http request to https://your-thingsboard-url/api/v1/ACCESS-TOKEN/telemetry
7. Result is a response code http 500 (internal server error) and no telemetry is written
8. See logs below

**Expected behavior**
Telemetry data should be received and response would be HTTP Code 200

**Logs**
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
    at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
    at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
    at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1158)
    at org.thingsboard.server.common.data.FSTUtils.decode(FSTUtils.java:43)
    at org.thingsboard.server.queue.util.ProtoWithFSTService.decode(ProtoWithFSTService.java:49)
    at org.thingsboard.server.common.transport.service.DefaultTransportDeviceProfileCache.getOrCreate(DefaultTransportDeviceProfileCache.java:78)
    at org.thingsboard.server.common.transport.service.DefaultTransportService.lambda$doProcess$4(DefaultTransportService.java:469)
    at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:250)
    at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:240)
    at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
    at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
    at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
    at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.processResponse(DefaultTbQueueRequestTemplate.java:195)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:132)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:118)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
unable to decode:�0org.thingsboard.server.common.data.DeviceProfileºgØ��ÿÿú=org.thingsboard.server.common.data
2023-06-20 11:41:22,983 [DefaultTransportService-18-2] WARN  o.t.s.t.http.DeviceApiController - Failed to process request
java.io.IOException: java.io.IOException: <id of IdBased>:Failed to instantiate 'org.thingsboard.server.common.data.id.UUIDBased'. Register a custom serializer implementing instantiate or define empty constructor.
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:247)
    at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1158)
    at org.thingsboard.server.common.data.FSTUtils.decode(FSTUtils.java:43)
    at org.thingsboard.server.queue.util.ProtoWithFSTService.decode(ProtoWithFSTService.java:49)
    at org.thingsboard.server.common.transport.service.DefaultTransportDeviceProfileCache.getOrCreate(DefaultTransportDeviceProfileCache.java:78)
    at org.thingsboard.server.common.transport.service.DefaultTransportService.lambda$doProcess$4(DefaultTransportService.java:469)
    at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:250)
    at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:240)
    at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
    at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
    at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
    at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.processResponse(DefaultTbQueueRequestTemplate.java:195)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:132)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:118)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: <id of IdBased>:Failed to instantiate 'org.thingsboard.server.common.data.id.UUIDBased'. Register a custom serializer implementing instantiate or define empty constructor.
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:533)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
    at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
    at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
    ... 22 common frames omitted
java.lang.InstantiationException: org.thingsboard.server.common.data.id.UUIDBased
    at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
    at jdk.unsupported/sun.misc.Unsafe.allocateInstance(Unsafe.java:840)
    at org.nustaq.serialization.FSTDefaultClassInstantiator.newInstance(FSTDefaultClassInstantiator.java:43)
    at org.nustaq.serialization.FSTClazzInfo.newInstance(FSTClazzInfo.java:231)
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:531)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
    at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:713)
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:566)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:374)
    at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:331)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:311)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:245)
    at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1167)
    at org.thingsboard.server.common.data.FSTUtils.decode(FSTUtils.java:43)
    at org.thingsboard.server.queue.util.ProtoWithFSTService.decode(ProtoWithFSTService.java:49)
    at org.thingsboard.server.common.transport.service.DefaultTransportDeviceProfileCache.getOrCreate(DefaultTransportDeviceProfileCache.java:78)
    at org.thingsboard.server.common.transport.service.DefaultTransportService.lambda$doProcess$4(DefaultTransportService.java:469)
    at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:250)
    at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:240)
    at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
    at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
    at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
    at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.processResponse(DefaultTbQueueRequestTemplate.java:195)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.fetchAndProcessResponses(DefaultTbQueueRequestTemplate.java:132)
    at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.mainLoop(DefaultTbQueueRequestTemplate.java:118)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ban2derlog** [comment]
Hello,
During update there were errors?
Check log folder, by default pod that runs upgrate must mount logs folder for ThingsBoard nodes.
https://github.com/thingsboard/thingsboard-pe-k8s/blob/fec90eafcf5e6226250c7aa96a93a4f05266a3d1/aws/microservices/database-setup.yml#L49
Check that during upgrade there wasn't any errors in install.log file.

Additionally, test this with new Device Profile on new Tenant and old one.

**Comment by olheimerspg** [comment]
@ban2derlog, thanks! In the meanwhile I found the problem. It was a missconfigured http transport container.
