### ISSUE TITLE
I can create an alarm but i can't send email 

### ISSUE THREAD

**Issue by davidsa81** [thingsboard/thingsboard#8829]
I have created several devices inside thingsboard linked with flespi. From the thingsboard I see the telemetry for each device but I am having problems trying to send an email when a value of this telemetry is exceeded. it could be that the name of the temperature variable does not match. I have read the documentation to create alarms and send e-mail but I can't do it. The alarms are created fine but the email is not sent. Can you help me?

**Environment**

 * OS:  windows 11
 * ThingsBoard: Live Demo
 * Browser: Chrome 114.0.5735.134

**Comment by devaskim** [comment]
If you use Rule Engine and its alarm/email nodes, you can enable debug mode for each rule node and look at Event tab is there any errors

**Comment by davidsa81** [comment]
first, i have a rule to create and send email with this script:

return msg.bms.temp > 25;

the data that device sends is "bms.temp": 0,
and i have an error on debug:
"org.thingsboard.script.api.TbScriptException: java.lang.RuntimeException: TypeError: Cannot read properties of undefined (reading 'temp') in at line number 1
	at org.thingsboard.server.service.script.RemoteJsInvokeService.handleInvokeError(RemoteJsInvokeService.java:237)
	at org.thingsboard.server.service.script.RemoteJsInvokeService.lambda$doInvokeFunction$1(RemoteJsInvokeService.java:188)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: TypeError: Cannot read properties of undefined (reading 'temp') in at line number 1
	at org.thingsboard.server.service.script.RemoteJsInvokeService.handleInvokeError(RemoteJsInvokeService.java:215)
	... 7 more
"
any help?

**Comment by davidsa81** [comment]
hi, i have another problem...
please see the files

https://ibb.co/0D2snFD
https://ibb.co/F7hbkSx
https://ibb.co/r4NhYXh

thanks

**Comment by devaskim** [comment]
`Use message alarm data` option means that all alarm specific fields including `severity` (see error description of on the last screenshot) should be in incoming message.

**Comment by davidsa81** [comment]
ok...
how can i access to a device tag?    ${deviceTag}  does not work....

**Comment by davidsa81** [comment]
https://ibb.co/gSpHqmv

**Comment by devaskim** [comment]
> https://ibb.co/gSpHqmv

Just drag and drop screenshot to the comment's content

> how can i access to a device label? ${deviceLabel} does not work....
You can use data only from message and metadata. As I know there is `deviceName` key in metadata, not label

**Comment by davidsa81** [comment]
ok, great! thank you

**Comment by sudhirbits** [comment]
> Use message alarm data option means that all alarm specific fields including severity (see error description of on the last screenshot) should be in incoming message.

This needs to be updated into the documentation.
