### ISSUE TITLE
[Bug] NullPointerException in HashPartitionService

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#8835]
**Describe the bug**
This is TB CE 3.5.1, [cluster setup in Docker](https://thingsboard.io/docs/user-guide/install/cluster/docker-compose-setup/) with HTTP and MQTT transports. All services are on the same Ubuntu machine (2 CPU, 8GB): one core node, one JS executor. From time to time I faced with the following exception during cluster start (`./docker-start-services.sh`). After some time MQTT transport and other part of cluster finally establish connection between each other.

Stacktrace in MQTT transport service.
```
java.lang.NullPointerException: null
        at org.thingsboard.server.queue.discovery.HashPartitionService.resolve(HashPartitionService.java:207)
        at org.thingsboard.server.queue.discovery.HashPartitionService.resolve(HashPartitionService.java:188)
        at org.thingsboard.server.common.transport.service.DefaultTransportService.sendToRuleEngine(DefaultTransportService.java:1113)
        at org.thingsboard.server.common.transport.service.DefaultTransportService.sendToRuleEngine(DefaultTransportService.java:1142)
        at org.thingsboard.server.common.transport.service.DefaultTransportService.process(DefaultTransportService.java:581)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processDevicePublish(MqttTransportHandler.java:440)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processPublish(MqttTransportHandler.java:350)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processRegularSessionMsg(MqttTransportHandler.java:304)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.lambda$processMsgQueue$0(MqttTransportHandler.java:298)
        at org.thingsboard.server.transport.mqtt.session.DeviceSessionCtx.tryProcessQueuedMsgs(DeviceSessionCtx.java:239)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processMsgQueue(MqttTransportHandler.java:298)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.enqueueRegularSessionMsg(MqttTransportHandler.java:290)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.processMqttMsg(MqttTransportHandler.java:233)
        at org.thingsboard.server.transport.mqtt.MqttTransportHandler.channelRead(MqttTransportHandler.java:194)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:349)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by trikimiki** [comment]
Most likely, some service(s) did not start "completely," but Docker considered it started (sent "I am up and running" to Docker daemon while still loading some resources). Transports depend on TB-Cores and Zoo, I believe.

Can you share your compose file(s) so I could try to reproduce it?

**Comment by devaskim** [comment]
Thanks
```
version: '2.2'

services:
  zookeeper:
    restart: always
    image: "zookeeper:3.8.0"
    ports:
      - "2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
      ZOO_ADMINSERVER_ENABLED: "false"
  tb-js-executor:
    restart: always
    image: "${DOCKER_REPO}/${JS_EXECUTOR_DOCKER_NAME}:${TB_VERSION}"
    env_file:
      - tb-js-executor.env
  tb-core1:
    restart: always
    image: "${DOCKER_REPO}/tb-node:${TB_VERSION}"
    container_name: tb-node
    hostname: tb-node
    ports:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-core1
      TB_SERVICE_TYPE: tb-core
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-node/log:/var/log/thingsboard
    depends_on:
      - zookeeper
      - tb-js-executor
      - tb-rule-engine1
  tb-rule-engine1:
    restart: always
    image: "${DOCKER_REPO}/${TB_NODE_DOCKER_NAME}:${TB_VERSION}"
    ports:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-rule-engine1
      TB_SERVICE_TYPE: tb-rule-engine
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-node/log:/var/log/thingsboard
    depends_on:
      - zookeeper
      - tb-js-executor
  tb-mqtt-transport1:
    restart: always
    image: "${DOCKER_REPO}/${MQTT_TRANSPORT_DOCKER_NAME}:${TB_VERSION}"
    ports:
      - "1883"
    environment:
      TB_SERVICE_ID: tb-mqtt-transport1
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-mqtt-transport.env
    volumes:
      - ./tb-transports/mqtt/conf:/config
      - ./tb-transports/mqtt/log:/var/log/tb-mqtt-transport
    depends_on:
      - zookeeper
      - tb-core1
  tb-http-transport1:
    restart: always
    image: "${DOCKER_REPO}/${HTTP_TRANSPORT_DOCKER_NAME}:${TB_VERSION}"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-http-transport1
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-http-transport.env
    volumes:
      - ./tb-transports/http/conf:/config
      - ./tb-transports/http/log:/var/log/tb-http-transport
    depends_on:
      - zookeeper
      - tb-core1
  tb-web-ui1:
    restart: always
    image: "${DOCKER_REPO}/tb-web-ui:${TB_VERSION}"
    container_name: tb-web-ui
    hostname: tb-web-ui
    ports:
      - "8080"
    env_file:
      - tb-web-ui.env
  tb-vc-executor1:
    restart: always
    image: "${DOCKER_REPO}/${TB_VC_EXECUTOR_DOCKER_NAME}:${TB_VERSION}"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-vc-executor1
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-vc-executor.env
    volumes:
      - ./tb-vc-executor/conf:/config
      - ./tb-vc-executor/log:/var/log/tb-vc-executor
    depends_on:
      - zookeeper
      - tb-core1
  haproxy:
    restart: always
    container_name: "${LOAD_BALANCER_NAME}"
    image: thingsboard/haproxy-certbot:1.3.0
    volumes:
     - ./haproxy/config:/config
     - ./haproxy/letsencrypt:/etc/letsencrypt
     - ./haproxy/certs.d:/usr/local/etc/haproxy/certs.d
    ports:
     - "80:80"
     - "443:443"
     - "1883:1883"
     - "9999:9999"
    cap_add:
     - NET_ADMIN
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      MQTT_PORT: 1883
      FORCE_HTTPS_REDIRECT: "true"
    links:
        - tb-core1
        - tb-web-ui1
        - tb-mqtt-transport1
        - tb-http-transport1
```

**Comment by trikimiki** [comment]
This deploy file LGTM, although - are you using any other services? I assume, similar to the official deployment files, you are using additional "yaml" files with additional services like Redis, Kafka, etc. Let me know if there are any changes (from default) to those.

AFAIK HashPartitionService is used to find topics in queue service (Kafka) - for some reason, there is a NULL returned. If this is resolved after some time after startup, it seems like Kafka/Redis did not startup completely when transport was already looking for topics?

I think the best way is to check Kafka/Redis/transport logs on startup. Also, check if there are any changes to other config files.

**Comment by devaskim** [comment]
> If this is resolved after some time after startup
Yes, in most cases the NullPointer stachtrace disappear, but sometimes the tb-core or mqtt transport (don't know exactly) doesn't receive any incoming from devices at all, until rebooting all services. 

> are you using any other services? 
Yes, there is Kafka and Redis. The only change to default deployment is adding password to Redis because of security reasons.

**Comment by trikimiki** [comment]
Could you check Kafka and Redis logs after (and the short time before) getting the error?
Most likely, if it is indeed a topic discovery issue, the problem is with queue service (e.g. topic cannot be recovered) or cache (e.g. cache is pointing to the wrong or unexisting topic).

**Comment by devaskim** [comment]
Sorry, we should get back to monolith because lack of time, so no logs.  At least cleaning Redis cache didn't help

**Comment by xianglinghui** [comment]
I have encountered the same problem, and the reason is that HashPartitionService.partitionsInit is anotated by AfterStartUp，then this function will be executed after the MqttTransportService.init，which will let the netty start to work。
