### ISSUE TITLE
[Bug] Kafka PolicyViolationException Thingsboard PE EKS

### ISSUE THREAD

**Issue by dantjackson** [thingsboard/thingsboard#8861]
**Describe the bug**
Unable to start a tb-integration-executor-0 pod on Thingsboard PE.  
Looks like Kafka consumer definition is incompatible with topic.

Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
 at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
 at org.thingsboard.server.queue.kafka.TbKafkaAdmin.createTopicIfNotExists(TbKafkaAdmin.java:86)

Topics are created in Confluent by TB and config looks correct, I am guessing the segment bytes is set when defining a consumer.

I've peppered segment.bytes:52428800 wherever I could, in an attempt to override.

**Your Server Environment**
* AWS EKS .. following > https://thingsboard.io/docs/user-guide/install/pe/cluster/aws-microservices-setup/#step-42-cassandra-optional
  * ThingsBoard PE 

**Kafka Config for config map**
  TB_KAFKA_CREATE_TOPICS: js.eval.requests:120:1:delete --config=retention.ms=600000 --config=segment.bytes=26214400 --config=retention.bytes=5368709120,tb.transport.api.requests:30:1:delete --config=retention.ms=600000 --config=segment.bytes=26214400 --config=retention.bytes=5368709120,tb.rule-engine:30:1:delete --config=retention.ms=600000 --config=segment.bytes=26214400 --config=retention.bytes=5368709120
  KAFKA_CREATE_TOPICS: js.eval.requests:120:1:delete --config=retention.ms=600000 --config=segment.bytes=26214400 --config=retention.bytes=5368709120,tb.transport.api.requests:30:1:delete --config=retention.ms=600000 --config=segment.bytes=26214400 --config=retention.bytes=5368709120,tb.rule-engine:30:1:delete --config=retention.ms=600000 --config=segment.bytes=26214400 --config=retention.bytes=5368709120
  TB_QUEUE_KAFKA_OTHER_PROPERTIES: retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000
  TB_QUEUE_KAFKA_REPLICATION_FACTOR: '3'
  TB_QUEUE_KAFKA_USE_CONFLUENT_CLOUD: 'true'
  TB_QUEUE_KAFKA_CONFLUENT_SSL_ALGORITHM: https
  TB_QUEUE_KAFKA_CONFLUENT_SASL_MECHANISM: PLAIN
  TB_QUEUE_KAFKA_CONFLUENT_SECURITY_PROTOCOL: SASL_SSL
  TB_QUEUE_KAFKA_RE_TOPIC_PROPERTIES: retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000
  TB_QUEUE_KAFKA_CORE_TOPIC_PROPERTIES: retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000
  TB_QUEUE_KAFKA_TA_TOPIC_PROPERTIES: retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000
  TB_QUEUE_KAFKA_NOTIFICATIONS_TOPIC_PROPERTIES: retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000
  TB_QUEUE_KAFKA_JE_TOPIC_PROPERTIES: retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000
  TB_QUEUE_KAFKA_OTA_TOPIC_PROPERTIES: retention.ms:604800000;segment.bytes:52428800;retention.bytes:1048576000
  TB_QUEUE_CORE_POLL_INTERVAL_MS : '1000'
  TB_QUEUE_CORE_PARTITIONS : '2'  
  TB_QUEUE_RULE_ENGINE_POLL_INTERVAL_MS : '1000'
  TB_QUEUE_TRANSPORT_REQUEST_POLL_INTERVAL_MS : '1000'
  TB_QUEUE_TRANSPORT_RESPONSE_POLL_INTERVAL_MS : '1000'
  TB_QUEUE_TRANSPORT_NOTIFICATIONS_POLL_INTERVAL_MS : '1000'
  TB_QUEUE_VC_INTERVAL_MS : '1000'
  TB_QUEUE_VC_PARTITIONS: '1'

Full stack

2023-07-03 11:11:00,526 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultClusterIntegrationControllerApi': Unsatisfied dependency expressed through field 'integrationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultIntegrationManagerService' defined in URL [jar:file:/usr/share/tb-integration-executor/bin/tb-integration-executor.jar!/BOOT-INF/lib/cluster-integration-api-3.5.1PE.jar!/org/thingsboard/server/service/integration/DefaultIntegrationManagerService.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tbIntegrationExecutorIntegrationConfigurationService': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.
 at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
 at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
 at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
 at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
 at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
 at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
 at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
 at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
 at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
 at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
 at org.thingsboard.integration.ThingsboardIntegrationExecutorApplication.main(ThingsboardIntegrationExecutorApplication.java:49)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
 at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultIntegrationManagerService' defined in URL [jar:file:/usr/share/tb-integration-executor/bin/tb-integration-executor.jar!/BOOT-INF/lib/cluster-integration-api-3.5.1PE.jar!/org/thingsboard/server/service/integration/DefaultIntegrationManagerService.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tbIntegrationExecutorIntegrationConfigurationService': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.
 at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
 at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
 at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
 at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
 at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
 ... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tbIntegrationExecutorIntegrationConfigurationService': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.
 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
 at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
 at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
 at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
 at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
 ... 41 common frames omitted
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.
 at org.thingsboard.server.queue.kafka.TbKafkaAdmin.createTopicIfNotExists(TbKafkaAdmin.java:93)
 at org.thingsboard.server.queue.common.DefaultTbQueueRequestTemplate.init(DefaultTbQueueRequestTemplate.java:108)
 at org.thingsboard.integration.service.api.TbIntegrationExecutorIntegrationConfigurationService.init(TbIntegrationExecutorIntegrationConfigurationService.java:78)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
 ... 54 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
 at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
 at org.thingsboard.server.queue.kafka.TbKafkaAdmin.createTopicIfNotExists(TbKafkaAdmin.java:86)
 ... 63 common frames omitted
Caused by: org.apache.kafka.common.errors.PolicyViolationException: Config property 'segment.bytes' with value '26214400' is lower than the minimum allowed value of 52428800.

**Comment by pon0marev** [comment]
The issue has been closed due to inactivity. If you have additional questions or comments, you can reopen it.
