### ISSUE TITLE
[Bug] "Entities Table" widget stuck on 'Loading..."

### ISSUE THREAD

**Issue by LukaszDuss** [thingsboard/thingsboard#8870]
**Additional context**
I'am using Entities Table in seperate dashboard state to list inactive Entities (Entity Views), based on that im generating reports (to PDF) with inactive devices for one of our clients. Reports are scheduled once a day through Scheduler.

Once a week we were reciving report that have not been loaded correctly - instead of entities on list it would say "Loading...".

I have established that root of the problem is not the lack of time to load the list but rather there is an error that prevents the list to load.

**Describe the bug**
From time to time when loading Entities Table occures an error that make the widget stuck on "Loading..." (fig.1)

the error (fig.2) :
`Uncaught TypeError: Cannot read properties of undefined (reading '7ed47920-5430-11ec-aec0-479313e883ed')`

**Expected behavior**
Loaded list (fig.3)

**Your Server Environment**
* Docker Microservices architecture 
  * ThingsBoard PE 3.4.0

**Your Client Environment**
* OS: 
* Windows 10 Pro 22H2 (19045.3086)
* Browser: 
* Chrome 114.0.5735.199
* Firefox 114.0.2 

**Screenshots**

![image](https://github.com/thingsboard/thingsboard/assets/42135726/bbbe3b5f-d0c6-46cd-8ccb-1882cdc8c630)
[fig.1]

![image](https://github.com/thingsboard/thingsboard/assets/42135726/975d7862-7a4f-4f6c-9a52-d0a3dac44e1e)
[fig.2]

![image](https://github.com/thingsboard/thingsboard/assets/42135726/a0c56e20-4a12-42f3-adac-645abb203096)
[fig.3]

**Comment by LukaszDuss** [comment]
`polyfills.6d09cdca7f8342e3da77.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '8a146650-971a-11ed-a9ad-f9619e4281bf')
    at G.onDataUpdate (5920.526e4cf06fe3c6bad81e.js:1:231227)
    at O._next (5920.526e4cf06fe3c6bad81e.js:1:222760)
    at O.__tryOrUnsub (vendor.a874a1c6b75cffcc819b.js:1:2772210)
    at O.next (vendor.a874a1c6b75cffcc819b.js:1:2771439)
    at m._next (vendor.a874a1c6b75cffcc819b.js:1:2770608)
    at m.next (vendor.a874a1c6b75cffcc819b.js:1:2770382)
    at m.next (vendor.a874a1c6b75cffcc819b.js:1:2768112)
    at m.nextInfiniteTimeWindow (vendor.a874a1c6b75cffcc819b.js:1:2766434)
    at A.onEntityData (main.e7c861b24fc85e14f0fa.js:1:1153268)
    at d.onMessage (5920.526e4cf06fe3c6bad81e.js:1:306471)
onDataUpdate @ 5920.526e4cf06fe3c6bad81e.js:1
(anonymous) @ 5920.526e4cf06fe3c6bad81e.js:1
__tryOrUnsub @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
_next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
nextInfiniteTimeWindow @ vendor.a874a1c6b75cffcc819b.js:1
onEntityData @ main.e7c861b24fc85e14f0fa.js:1
onMessage @ 5920.526e4cf06fe3c6bad81e.js:1
(anonymous) @ 5920.526e4cf06fe3c6bad81e.js:1
invoke @ polyfills.6d09cdca7f8342e3da77.js:1
run @ polyfills.6d09cdca7f8342e3da77.js:1
runOutsideAngular @ vendor.a874a1c6b75cffcc819b.js:1
(anonymous) @ 5920.526e4cf06fe3c6bad81e.js:1
__tryOrUnsub @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
_next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
j.onmessage @ 5920.526e4cf06fe3c6bad81e.js:1
V @ polyfills.6d09cdca7f8342e3da77.js:1
invokeTask @ polyfills.6d09cdca7f8342e3da77.js:1
onInvokeTask @ vendor.a874a1c6b75cffcc819b.js:1
invokeTask @ polyfills.6d09cdca7f8342e3da77.js:1
runTask @ polyfills.6d09cdca7f8342e3da77.js:1
invokeTask @ polyfills.6d09cdca7f8342e3da77.js:1
at @ polyfills.6d09cdca7f8342e3da77.js:1
it @ polyfills.6d09cdca7f8342e3da77.js:1
mt @ polyfills.6d09cdca7f8342e3da77.js:1
setTimeout (async)
w @ polyfills.6d09cdca7f8342e3da77.js:1
scheduleTask @ polyfills.6d09cdca7f8342e3da77.js:1
scheduleTask @ polyfills.6d09cdca7f8342e3da77.js:1
scheduleMacroTask @ polyfills.6d09cdca7f8342e3da77.js:1
h @ polyfills.6d09cdca7f8342e3da77.js:1
(anonymous) @ polyfills.6d09cdca7f8342e3da77.js:1
O.<computed> @ polyfills.6d09cdca7f8342e3da77.js:1
e @ vendor.a874a1c6b75cffcc819b.js:1
__tryOrUnsub @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
_next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
nextInfiniteTimeWindow @ vendor.a874a1c6b75cffcc819b.js:1
onEntityData @ main.e7c861b24fc85e14f0fa.js:1
onMessage @ 5920.526e4cf06fe3c6bad81e.js:1
(anonymous) @ 5920.526e4cf06fe3c6bad81e.js:1
invoke @ polyfills.6d09cdca7f8342e3da77.js:1
run @ polyfills.6d09cdca7f8342e3da77.js:1
runOutsideAngular @ vendor.a874a1c6b75cffcc819b.js:1
(anonymous) @ 5920.526e4cf06fe3c6bad81e.js:1
__tryOrUnsub @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
_next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
next @ vendor.a874a1c6b75cffcc819b.js:1
j.onmessage @ 5920.526e4cf06fe3c6bad81e.js:1
V @ polyfills.6d09cdca7f8342e3da77.js:1
invokeTask @ polyfills.6d09cdca7f8342e3da77.js:1
onInvokeTask @ vendor.a874a1c6b75cffcc819b.js:1
invokeTask @ polyfills.6d09cdca7f8342e3da77.js:1
runTask @ polyfills.6d09cdca7f8342e3da77.js:1
invokeTask @ polyfills.6d09cdca7f8342e3da77.js:1
at @ polyfills.6d09cdca7f8342e3da77.js:1
it @ polyfills.6d09cdca7f8342e3da77.js:1
mt @ polyfills.6d09cdca7f8342e3da77.js:1
`

**Comment by LukaszDuss** [comment]
Please let me know what kind of information do i need to provide about the issue for You to better understand it.

**Comment by LukaszDuss** [comment]
@vvlladd28 @ashvayka

**Comment by ashaforost** [comment]
@LukaszDuss 

It's apparent that you have some custom action/post-processing/cell content function or a custom widget based on the thingsboard entities table -  this code is blocking widget loading. 
I would advise you to debug your code; feel free to share your widget's custom components so the community may pinpoint the issue,

**Comment by ashaforost** [comment]
I'm closing this issue due to inactivity. Feel free to reopen if you still require assistance from the community.

**Comment by LukaszDuss** [comment]
> @LukaszDuss
> 
> It's apparent that you have some custom action/post-processing/cell content function or a custom widget based on the thingsboard entities table - this code is blocking widget loading. I would advise you to debug your code; feel free to share your widget's custom components so the community may pinpoint the issue,

You were right, additional CSS in "row style" was the issue, Thanks 🍺
