### ISSUE TITLE
[Bug] TbDate toISOString() method is not thread-safe (runtime error)

### ISSUE THREAD

**Issue by smatvienko-tb** [thingsboard/thingsboard#8872]
# TbDate toISOString() method is not thread-safe (runtime error)

```
public class TbDate extends Date {
...
 private static final DateFormat isoDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
...
 public String toISOString() {
        return isoDateFormat.format(this);
 }
```

According to `SimpleDateFormat` documentation, this implementation must be synchronized.
![image](https://github.com/thingsboard/thingsboard/assets/79898499/0e1831ee-3c6d-4772-be5b-d8eefe0db603)

In run-time, during uplink data conversion, a runtime error appeared.

The error is not reproducible with UI test function.

```
org.thingsboard.script.api.TbScriptException: [Error: Invalid statement: payload.metaData.certificate_expiration_date != null]
[Near : {... if(payload.metaData.certificate_e ....}]
                ^
[Line: 55, Column: 8]
	at org.thingsboard.script.api.tbel.DefaultTbelInvokeService.lambda$doInvokeFunction$7(DefaultTbelInvokeService.java:219)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.mvel2.CompileException: [Error: Invalid statement: payload.metaData.certificate_expiration_date != null]
[Near : {... if(payload.metaData.certificate_e ....}]
                ^
[Line: 55, Column: 8]
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:184)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:98)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:74)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:96)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.MVEL.executeExpression(MVEL.java:939)
	at org.mvel2.MVEL.executeTbExpression(MVEL.java:952)
	at org.thingsboard.script.api.tbel.DefaultTbelInvokeService.lambda$doInvokeFunction$7(DefaultTbelInvokeService.java:215)
	... 9 common frames omitted
Caused by: java.lang.RuntimeException: cannot construct object
	at org.mvel2.optimizers.impl.refl.nodes.ConstructorAccessor.getValue(ConstructorAccessor.java:57)
	at org.mvel2.ast.NewObjectNode.getReducedValueAccelerated(NewObjectNode.java:242)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.DeepAssignmentNode.getReducedValueAccelerated(DeepAssignmentNode.java:90)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:74)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:96)
	... 19 common frames omitted
Caused by: java.lang.RuntimeException: cannot invoke method: toISOString
	at org.mvel2.optimizers.impl.refl.nodes.MethodAccessor.getValue(MethodAccessor.java:63)
	at org.mvel2.optimizers.impl.refl.nodes.ConstructorAccessor.getValue(ConstructorAccessor.java:34)
	... 25 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mvel2.optimizers.impl.refl.nodes.MethodAccessor.getValue(MethodAccessor.java:44)
	... 26 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 13
	at java.base/sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:457)
	at java.base/java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2394)
	at java.base/java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2309)
	at java.base/java.util.Calendar.setTimeInMillis(Calendar.java:1834)
	at java.base/java.util.Calendar.setTime(Calendar.java:1800)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:974)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:967)
	at java.base/java.text.DateFormat.format(DateFormat.java:374)
	at org.thingsboard.script.api.tbel.TbDate.toISOString(TbDate.java:91)
	... 30 common frames omitted

```

**Comment by smatvienko-tb** [comment]
released in 3.6
