### ISSUE TITLE
An error occurred every time the TB service was restarted

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#889]
2018-06-22 17:40:59,455 [Akka-rule-dispatcher-9] WARN  o.t.s.s.s.AbstractNashornJsSandboxService - Failed to compile JS script: java.lang.IllegalStateException: Executor thread not set after 100 ms
java.lang.RuntimeException: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.ThreadMonitor.run(ThreadMonitor.java:130)
	at delight.nashornsandbox.internal.JsEvaluator.runMonitor(JsEvaluator.java:47)
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:161)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:146)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:127)
	at org.thingsboard.server.service.script.AbstractNashornJsSandboxService.eval(AbstractNashornJsSandboxService.java:86)
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.<init>(RuleNodeJsScriptEngine.java:46)
	at org.thingsboard.server.actors.ruleChain.DefaultTbContext.createJsScriptEngine(DefaultTbContext.java:157)
	at org.thingsboard.rule.engine.action.TbLogNode.init(TbLogNode.java:49)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:117)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:58)
	at org.thingsboard.server.actors.service.ComponentActor.preStart(ComponentActor.java:57)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
	at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalStateException: Executor thread not set after 100 ms
	at delight.nashornsandbox.internal.ThreadMonitor.run(ThreadMonitor.java:91)
	... 23 common frames omitted

**Comment by vparomskiy** [comment]
All JS scripts inside Rule Engine are limited to execute in 100 ms. If execution time is bigger - this error is thrown.
There are 2 properties in the thingsboard.yml file
actors.rule.js_sandbox.use_js_sandbox - enable/disable sandbox
actors.rule.js_sandbox.monitor_thread_pool_size - number of monitor threads for the sandbox
actors.rule.js_sandbox.max_cpu_time - max time in millis for script execution
actors.rule.js_sandbox.max_errors - number of errors when script is blacklisted.

You can tune those properties for your use cases or validate JS script and verify, why its execution time is so long.
