### ISSUE TITLE
[Question] Troubles saving an array using 'Saving to custom table' node.

### ISSUE THREAD

**Issue by Andmac12** [thingsboard/thingsboard#8943]
**Component**

 * Rule Engine

**Description**

I have a rule node for saving data into a Cassandra cluster setted up. The entire rule chain works properly unless when trying to save arrays into a table list<any> field. I get the following error when trying to do so:

```
java.lang.IllegalStateException: Message data key: 'groupsList' with value: 'groups_list' is not a JSON Object or JSON Primitive!
	at org.thingsboard.rule.engine.action.TbSaveToCustomCassandraTableNode.lambda$save$2(TbSaveToCustomCassandraTableNode.java:216)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.thingsboard.rule.engine.action.TbSaveToCustomCassandraTableNode.save(TbSaveToCustomCassandraTableNode.java:193)
	at org.thingsboard.rule.engine.action.TbSaveToCustomCassandraTableNode.onMsg(TbSaveToCustomCassandraTableNode.java:115)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:150)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:117)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:76)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:60)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:157)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

``` 

I went for a quick search in Thingsboard CE codebase and found out that in the [Node Object](https://github.com/thingsboard/thingsboard/blob/master/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/action/TbSaveToCustomCassandraTableNode.java) what seems to be an intentional leave out array elements: 

```java
 private ListenableFuture<Void> save(TbMsg msg, TbContext ctx) {
        JsonElement data = parser.parse(msg.getData());
        if (!data.isJsonObject()) {
            throw new IllegalStateException("Invalid message structure, it is not a JSON Object:" + data);
        } else {
            JsonObject dataAsObject = data.getAsJsonObject();
            BoundStatementBuilder stmtBuilder = new BoundStatementBuilder(saveStmt.bind());
            AtomicInteger i = new AtomicInteger(0);
            fieldsMap.forEach((key, value) -> {
                if (key.equals(ENTITY_ID)) {
                    stmtBuilder.setUuid(i.get(), msg.getOriginator().getId());
                } else if (dataAsObject.has(key)) {
                    JsonElement dataKeyElement = dataAsObject.get(key);
                    if (dataKeyElement.isJsonPrimitive()) {
                        JsonPrimitive primitive = dataKeyElement.getAsJsonPrimitive();
                        if (primitive.isNumber()) {
                            if (primitive.getAsString().contains(".")) {
                                stmtBuilder.setDouble(i.get(), primitive.getAsDouble());
                            } else {
                                stmtBuilder.setLong(i.get(), primitive.getAsLong());
                            }
                        } else if (primitive.isBoolean()) {
                            stmtBuilder.setBoolean(i.get(), primitive.getAsBoolean());
                        } else if (primitive.isString()) {
                            stmtBuilder.setString(i.get(), primitive.getAsString());
                        } else {
                            stmtBuilder.setToNull(i.get());
                        }
                    } else if (dataKeyElement.isJsonObject()) {
                        stmtBuilder.setString(i.get(), dataKeyElement.getAsJsonObject().toString());
                    } else {
                        throw new IllegalStateException("Message data key: '" + key + "' with value: '" + value + "' is not a JSON Object or JSON Primitive!");
                    }
                } else {
                    throw new RuntimeException("Message data doesn't contain key: " + "'" + key + "'!");
                }
                i.getAndIncrement();
            });
            return getFuture(executeAsyncWrite(ctx, stmtBuilder.build()), rs -> null);
        }
    }
``` 

Is there any reason behind this?

**Environment**

 * OS:  Ubuntu 21.04
 * ThingsBoard: v.3.4.4PE
 * Browser: *

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
