### ISSUE TITLE
[Bug] rest-client 3.5.1PE. DoubleDataEntry NoClassDefFoundError when calling getAttributeKvEntries

### ISSUE THREAD

**Issue by pcoutin** [thingsboard/thingsboard#9077]
**Describe the bug**

The class is in the JAR, I don't know why it's not being loaded.

I can provide a minimal project to reproduce the issue if necessary.

```
Aug 14 20:48:22 thingsboard java[76489]: java.lang.NoClassDefFoundError: org/thingsboard/server/common/data/kv/DoubleDataEntry
Aug 14 20:48:22 thingsboard java[76489]:         at org.thingsboard.rest.client.utils.RestJsonConverter.parseNumericValue(RestJsonConverter.java:106)
Aug 14 20:48:22 thingsboard java[76489]:         at org.thingsboard.rest.client.utils.RestJsonConverter.parseValue(RestJsonConverter.java:93)
Aug 14 20:48:22 thingsboard java[76489]:         at org.thingsboard.rest.client.utils.RestJsonConverter.lambda$toAttributes$1(RestJsonConverter.java:63)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Aug 14 20:48:22 thingsboard java[76489]:         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
Aug 14 20:48:22 thingsboard java[76489]:         at org.thingsboard.rest.client.utils.RestJsonConverter.toAttributes(RestJsonConverter.java:66)
Aug 14 20:48:22 thingsboard java[76489]:         at org.thingsboard.rest.client.RestClient.getAttributeKvEntries(RestClient.java:1924)
...
Aug 14 20:48:20 thingsboard java[76489]: Caused by: java.lang.ClassNotFoundException: org.thingsboard.server.common.data.kv.DoubleDataEntry
Aug 14 20:48:20 thingsboard java[76489]:         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
Aug 14 20:48:20 thingsboard java[76489]:         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
Aug 14 20:48:20 thingsboard java[76489]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
Aug 14 20:48:20 thingsboard java[76489]:         ... 53 more
```

**Your Server Environment**
3.5.1PE, Ubuntu 22.04 amd64, OpenJDK JRE 17

My pom.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>attributeQueryService</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.release>11</maven.compiler.release>
    </properties>

    <repositories>
        <repository>
            <id>thingsboard</id>
            <url>https://repo.thingsboard.io/artifactory/libs-release-public</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.thingsboard</groupId>
            <artifactId>rest-client</artifactId>
            <version>3.5.1PE</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.7</version>
        </dependency>
        <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin-bundle</artifactId>
            <version>5.6.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>Main</mainClass>
                                </transformer>
                            </transformers>
                            <minimizeJar>false</minimizeJar>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by pcoutin** [comment]
I'm having trouble reproducing this. I wonder if it was being caused by the load average of the server being over 30, somehow
