### ISSUE TITLE
Looping exception

### ISSUE THREAD

**Issue by stanurkov** [thingsboard/thingsboard#909]
Last week, my TB server started generating extensive logs filled with exception logs. In most cases, server dies, but sometimes it manages to recover, I didn't find a matching pattern yet. However, the exception loop stays the same all the time.
It looks like this:

`2018-07-02 10:42:02,312 [pool-17-thread-1] ERROR o.t.s.s.t.DefaultTelemetryWebSocketService - Failed to fetch data!
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:131)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.isDone(RateLimitedResultSetFuture.java:95)
	at com.google.common.util.concurrent.AggregateFuture$RunningState.handleOneInputDone(AggregateFuture.java:204)
	at com.google.common.util.concurrent.AggregateFuture$RunningState.access$200(AggregateFuture.java:78)
	at com.google.common.util.concurrent.AggregateFuture$RunningState$1.run(AggregateFuture.java:133)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:636)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:100)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.lambda$addListener$2(RateLimitedResultSetFuture.java:122)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:677)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:112)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:713)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:185)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.setResult(AbstractCatchingFuture.java:162)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:138)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:553)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.cancel(AbstractFuture.java:106)
	at org.thingsboard.server.dao.util.BufferedRateLimiter$LockedFuture.cancelFuture(BufferedRateLimiter.java:171)
	at org.thingsboard.server.dao.util.BufferedRateLimiter.printStats(BufferedRateLimiter.java:148)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:129)
	... 40 common frames omitted
Caused by: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1114)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1174)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:110)
	... 19 common frames omitted
2018-07-02 10:42:02,313 [pool-13-thread-170289] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:131)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.isDone(RateLimitedResultSetFuture.java:95)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1173)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:103)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:129)
	... 7 common frames omitted
Caused by: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1114)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1174)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:110)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:553)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.cancel(AbstractFuture.java:106)
	at org.thingsboard.server.dao.util.BufferedRateLimiter$LockedFuture.cancelFuture(BufferedRateLimiter.java:171)
	at org.thingsboard.server.dao.util.BufferedRateLimiter.printStats(BufferedRateLimiter.java:148)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	... 3 common frames omitted
2018-07-02 10:42:02,323 [pool-13-thread-170310] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:131)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.isDone(RateLimitedResultSetFuture.java:95)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1173)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:103)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:129)
	... 7 common frames omitted
Caused by: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1114)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1174)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:110)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:553)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.cancel(AbstractFuture.java:106)
	at org.thingsboard.server.dao.util.BufferedRateLimiter$LockedFuture.cancelFuture(BufferedRateLimiter.java:171)
	at org.thingsboard.server.dao.util.BufferedRateLimiter.printStats(BufferedRateLimiter.java:148)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	... 3 common frames omitted
2018-07-02 10:42:02,323 [pool-13-thread-170429] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:131)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.isDone(RateLimitedResultSetFuture.java:95)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1173)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:103)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:129)
	... 7 common frames omitted
Caused by: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1114)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1174)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:110)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.cancel(AbstractFuture.java:553)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.cancel(AbstractFuture.java:106)
	at org.thingsboard.server.dao.util.BufferedRateLimiter$LockedFuture.cancelFuture(BufferedRateLimiter.java:171)
	at org.thingsboard.server.dao.util.BufferedRateLimiter.printStats(BufferedRateLimiter.java:148)
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	... 3 common frames omitted
2018-07-02 10:42:02,324 [pool-13-thread-170355] ERROR c.g.c.u.concurrent.AggregateFuture - Got more than one input Future failure. Logging failures after the first
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:131)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.isDone(RateLimitedResultSetFuture.java:95)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1173)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:103)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.dao.nosql.RateLimitedResultSetFuture.safeGet(RateLimitedResultSetFuture.java:129)
	... 7 common frames omitted
`

**Comment by vparomskiy** [comment]
It looks like to many requests where generated to the Cassandra and they are rejected. In the log file I want to find a message with this pattern:

> Permits maxBuffer [{}] maxPermits [{}] expired [{}] currPermits [{}] currBuffer [{}] totalPermits [{}] totalRequests [{}] totalReleased [{}]"

It will show how many Cassandra queries where executed during last 30 seconds. 
The default limit is 200,000 queries, all other will be rejected. But the system should recover correctly from such states.

In any case, I need to look at your log file, please share it.

**Comment by stanurkov** [comment]
Here is a line with limits:
2018-07-04 00:02:54,207 [SockJS-1] INFO  o.t.s.dao.util.BufferedRateLimiter - Permits maxBuffer [16609] maxPermits [1000] expired [0] currPermits [1000] currBuffer [14817] totalPermits [45407] totalRequests [60224] totalReleased [44407]
I will give you a log example tomorrow as it's on my office machine

**Comment by stanurkov** [comment]
OK, here is a link to download the entire log - https://drive.google.com/open?id=1FZ9DNwqSST05Xcj3xWfO1FEwSxbhyujU

**Comment by vparomskiy** [comment]
According to this:

> 2018-07-02 10:40:31,406 [SockJS-1] INFO  o.t.s.dao.util.BufferedRateLimiter - Permits maxBuffer [16656] maxPermits [0] expired [0] currPermits [1000] currBuffer [16657] totalPermits [0] totalRequests [621] totalReleased [0]
> 2018-07-02 10:41:01,411 [SockJS-1] INFO  o.t.s.dao.util.BufferedRateLimiter - Permits maxBuffer [16978] maxPermits [0] expired [0] currPermits [1000] currBuffer [16979] totalPermits [0] totalRequests [322] totalReleased [0]
> 2018-07-02 10:41:31,413 [SockJS-1] INFO  o.t.s.dao.util.BufferedRateLimiter - Permits maxBuffer [17709] maxPermits [0] expired [0] currPermits [1000] currBuffer [17710] totalPermits [0] totalRequests [731] totalReleased [0]
> 2018-07-02 10:42:09,587 [SockJS-1] INFO  o.t.s.dao.util.BufferedRateLimiter - Permits maxBuffer [18042] maxPermits [1000] expired [8124] currPermits [1000] currBuffer [9719] totalPermits [16377] totalRequests [8386] totalReleased [16377]
> 

at 10:40:01 N Cassandra queries were submitted to Cassandra and those queries were not finished during 120 seconds (we can see it form this log message - **totalReleased [0]**)

After 120 seconds, those queries are canceled and that is the reason for the error you see in the log file.
In total, 8124 queries ( **expired [8124]** ) were canceled at 10:42:09

After that, the system returned to the normal operation state and process.
At 10:51:09 problem was repeated and at 10:52:49 11220 queries were canceled.

You need to identify queries that were executed at this time and find the reason why they were not finished in 120 seconds. You can make it by enabling debug or trace logging.

**Comment by stanurkov** [comment]
OK, thanks. Where do I set the log level?  Is it logback.xml (which node then?) or somewhere else?

I also have cassandra logs, I see many messages being stopped there, but I have no idea what they mean and what to do. Something like
`2018-07-04T10:41:53.682+0300: 3608892.686: Total time for which application threads were stopped: 0.0475437 seconds, Stopping threads took: 0.0023996 seconds
{Heap before GC invocations=156271 (full 352):
 par new generation   total 46080K, used 41103K [0x00000000ed400000, 0x00000000f0600000, 0x00000000f0600000)
  eden space 40960K, 100% used [0x00000000ed400000, 0x00000000efc00000, 0x00000000efc00000)
  from space 5120K,   2% used [0x00000000efc00000, 0x00000000efc23e30, 0x00000000f0100000)
  to   space 5120K,   0% used [0x00000000f0100000, 0x00000000f0100000, 0x00000000f0600000)
 concurrent mark-sweep generation total 256000K, used 180133K [0x00000000f0600000, 0x0000000100000000, 0x0000000100000000)
 Metaspace       used 43791K, capacity 45080K, committed 45280K, reserved 1089536K
  class space    used 5548K, capacity 5838K, committed 5912K, reserved 1048576K
2018-07-04T10:41:54.098+0300: 3608893.102: [GC (Allocation Failure) 2018-07-04T10:41:54.098+0300: 3608893.102: [ParNew
Desired survivor size 2621440 bytes, new threshold 1 (max 1)
- age   1:     296296 bytes,     296296 total
: 41103K->294K(46080K), 0.0604519 secs] 221237K->180432K(302080K), 0.0607417 secs] [Times: user=0.01 sys=0.00, real=0.06 secs] 
Heap after GC invocations=156272 (full 352):
 par new generation   total 46080K, used 294K [0x00000000ed400000, 0x00000000f0600000, 0x00000000f0600000)
  eden space 40960K,   0% used [0x00000000ed400000, 0x00000000ed400000, 0x00000000efc00000)
  from space 5120K,   5% used [0x00000000f0100000, 0x00000000f0149a10, 0x00000000f0600000)
  to   space 5120K,   0% used [0x00000000efc00000, 0x00000000efc00000, 0x00000000f0100000)
 concurrent mark-sweep generation total 256000K, used 180137K [0x00000000f0600000, 0x0000000100000000, 0x0000000100000000)
 Metaspace       used 43791K, capacity 45080K, committed 45280K, reserved 1089536K
  class space    used 5548K, capacity 5838K, committed 5912K, reserved 1048576K
}
2018-07-04T10:41:54.158+0300: 3608893.163: Total time for which application threads were stopped: 0.0658992 seconds, Stopping threads took: 0.0043573 seconds
{Heap before GC invocations=156272 (full 352):
 par new generation   total 46080K, used 41254K [0x00000000ed400000, 0x00000000f0600000, 0x00000000f0600000)
  eden space 40960K, 100% used [0x00000000ed400000, 0x00000000efc00000, 0x00000000efc00000)
  from space 5120K,   5% used [0x00000000f0100000, 0x00000000f0149a10, 0x00000000f0600000)
  to   space 5120K,   0% used [0x00000000efc00000, 0x00000000efc00000, 0x00000000f0100000)
 concurrent mark-sweep generation total 256000K, used 180137K [0x00000000f0600000, 0x0000000100000000, 0x0000000100000000)
 Metaspace       used 43791K, capacity 45080K, committed 45280K, reserved 1089536K
  class space    used 5548K, capacity 5838K, committed 5912K, reserved 1048576K`

**Comment by vparomskiy** [comment]
1. In the logback.xml (in /etc/thingsboard/conf/logback.xml) enable debug:

 `<logger name="org.thingsboard.server" level="DEBUG" />`

2. Are the Thignsboard and Cassandra installed on the same instance?
3. What is instance type used (CPU/RAM)?
4. If Cassandra on the separate instance, then what is instance type for it?
5. Provide please Cassandra statistic using this command - nodetool cfstats

> nodetool cfstats > stats.txt

**Comment by stanurkov** [comment]
OK, the problem with debug logging is that the volume of logged data is excessive and it eats available disk space quickly (we are reaching the quota limit now, upgrade to new quota will take some time), so it could be that this factor also applies.

1. Here are the parts with errors: https://drive.google.com/open?id=1p4cXaW8OlGKUQkDD-xuN-icGk5dT1Mxl
1a. And these are the logs from the start (in case you need them) - https://drive.google.com/open?id=1CHSOY7i6h9FLQFsjZct9NHfZmMHU4qDQ
2. Yes, they are
3. 1 Xeon CPU, 2 Gb of RAM.
5.  https://drive.google.com/open?id=1u-02bsW_UdMJdRrOCoP89OW0Xrr9SdoZ

**Comment by vparomskiy** [comment]
1. I do not see the problem with some specific Cassandra queries. I think the root cause is the total number of 'SELECT' queries, that are generated during fetching data for the Dashboard widgets. In peak, you have 600 read request per second. In general, it is not a big number, but we need to take in account your instance type.

2. If Thingsboard and Cassandra are both executed on the same instance with 2 GB of RAM, then it is a problem. Cassandra was designed as a big data storage and it requires memory and CPU resources for normal operation. At least you need to have 2 GB RAM and 1 dedicated CPU for the Cassandra process. But in your case you share those resources between OS, Thingsboard and Cassandra - it is not enough for production systems.

What to do - you have a few options:
1. Increase instance type and give more resources for the Cassandra.
2. Review your dashboard and find out why it generates so many requests. General idea is that you need to carefully configure dashboard time window and aggregation interval. For example, if you have 1 chart widget that shows 1 telemetry value for the last month with aggregation interval 2 hours than total number or read quires is:
1*1*(30*24)/2=360

Again, 360 requests or even 1000 requests per second is not a problem for the Thingsboard and Cassandra, but you need to provide a meaningful number of resources for making it stable.

**Comment by stanurkov** [comment]
@vparomskiy thank you so much for your insights! We'll make changes to the system and see what happens.

**Comment by stanurkov** [comment]
One thing should be noted, though - I suspect the looping from the OP is caused by non-processing exception that happens in an exception handler, so it may worth to check the code there...

**Comment by vparomskiy** [comment]
Those exceptions are thrown by Guava library when Future task is cancelled. It is hard to mute it.
