### ISSUE TITLE
Login Error: Can't get or create security user from oauth2 user

### ISSUE THREAD

**Issue by jason-hulkman** [thingsboard/thingsboard#9128]
I deploy the TB PE and config the OAuth2.0  custom login button with Auth0.

When I click the login button(Auth0), there is a meesage that login error: Can't get or create security user from oauth2 user.

And TB create the user, but do not assign the user group.

Someone met these?

**In TB CE + Auth0, the login process is fine. What is wrong with TB PE OAuth2.0?**

![image](https://github.com/thingsboard/thingsboard/assets/133846760/b236ce8d-5eac-4092-834e-5108744cc9c8)
![image](https://github.com/thingsboard/thingsboard/assets/133846760/84bfa2fa-adae-490f-a26e-9735b251aa0e)
![image](https://github.com/thingsboard/thingsboard/assets/133846760/9b7912b2-09eb-4753-a905-7d1fe88cc193)

My Auth0 Rule is like:
`function (user, context, callback) {
  const thingsboardClientID = 'xxxxxxxxYYYYYYYYYzzzzzzzz'; // Add your Discourse client ID here
  // Only run this rule for the Discourse application
  if(context.clientID !== thingsboardClientID) {
    return callback(null, user, context);
  }
  const namespace = 'http://customclaims/';
  
  // Set the tenantId for ThingsBoard in the ID token.
  const testTenantName = 'Tenant';
  const testCustomerName = "Customer C";
  const testDashboardName = "Gateways";
  const testGroupName = "Customer Users";
  const testParentCustomerName = "Customer A";
  
  context.idToken[namespace + 'tenantName'] = testTenantName;
  context.idToken[namespace + 'customerName'] = testCustomerName;
  context.idToken[namespace + 'parentCustomerName'] = testParentCustomerName;
	context.idToken[namespace + 'dashboardName'] = testDashboardName;
  context.idToken[namespace + 'gourpName'] = testGroupName;
	console.log(namespace + 'tenantName');
  return callback(null, user, context);
}`

the error log:
`2023-08-24 17:23:59,852 [http-nio-0.0.0.0-8080-exec-21] ERROR o.t.s.s.s.a.o.AbstractOAuth2ClientMapper - Can't get or create security user from oauth2 user
java.lang.NullPointerException: null
	at org.thingsboard.server.service.entitiy.user.DefaultUserService.save(DefaultUserService.java:92)
	at org.thingsboard.server.service.entitiy.user.DefaultUserService.save(DefaultUserService.java:72)
	at org.thingsboard.server.service.security.auth.oauth2.AbstractOAuth2ClientMapper.getOrCreateSecurityUserFromOAuth2User(AbstractOAuth2ClientMapper.java:183)
	at org.thingsboard.server.service.security.auth.oauth2.BasicOAuth2ClientMapper.getOrCreateUserByClientPrincipal(BasicOAuth2ClientMapper.java:56)
	at org.thingsboard.server.service.security.auth.oauth2.Oauth2AuthenticationSuccessHandler.onAuthenticationSuccess(Oauth2AuthenticationSuccessHandler.java:120)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.successfulAuthentication(AbstractAuthenticationProcessingFilter.java:329)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:237)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:178)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by EinarArnason** [comment]
As a workaround you can create the user first and activate, then on the password creation page, go back to the login and use oauth2.

**Comment by ViacheslavKlimov** [comment]
The fix for this is already implemented and will be a part of the upcoming 3.5.2 release

**Comment by liangzhu2008** [comment]
I deploy the TB PE 3.5.1 and config the OAuth2.0 custom login button with Google.

I follow this document: https://thingsboard.io/docs/pe/user-guide/oauth-2-support/#login-with-google

When I click the login button(Google), there is a meesage that login error: Can't get or create security user from oauth2 user.

And TB create the user, but do not assign the user group.

**Comment by rusko-hypros** [comment]
> The fix for this is already implemented and will be a part of the upcoming 3.5.2 release

I use TB version 3.5.1 and can confirm the behaviour described. I have already tested TB version 3.6.0 locally with my custom mapper and get the same result. I could not find anything about this bug in the changelogs of version 3.6.0 either.

When can a fix be expected?

**Comment by Ultrazombie** [comment]
Hello @liangzhu2008,
I assume your request is a little different from the topic-starter request; please make a new ticket with your problem to investigate.
