### ISSUE TITLE
[Bug] Upgrade to thingsboard 3.6 failed

### ISSUE THREAD

**Issue by shaphiro** [thingsboard/thingsboard#9304]
During thingsboard upgrade from 3.5.1 to 3.6.0 I encountered the following error:

`2023-09-21 11:39:06,055 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'refreshTokenExpCheckService' defined in URL [jar:file:/usr/share/thingsboard/bin/thingsboa>
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at org.thingsboard.server.ThingsboardServerApplication.main(ThingsboardServerApplication.java:36)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

It seems that the option is not specified in the thingsboard.yml file. This file is the same as version 3.5.1, it has not been overwritten by the new version.

**Server Environment**
debian linux

**To Reproduce**
Standard thingsboard upgrade procedure

**Comment by shaphiro** [comment]
I think that the option is the following:

mail:
  oauth2:
    refreshTokenCheckingInterval: "${REFRESH_TOKEN_EXPIRATION_CHECKING_INTERVAL:86400}" # Number of seconds (1 day).

In my case how can I upgrade thingsboard in order to have this option in the configuration file without lose my settings? I did not see any "merge" during the installation process. Thanks

**Comment by trikimiki** [comment]
Hi!

You should check your /etc/thingsboard/conf directory. If you've chosen "keep old yml file" option during package installation, there should be file labeled "thingsboard.yml.dpkg-new" (or similar, depending on your installation type).

Merge your old yml into that file, and rename it to just "thingsboard.yml"

**Comment by shaphiro** [comment]
Thank you, it works!
