### ISSUE TITLE
Error creating bean with name 'defaultTbMailConfigTemplateService'

### ISSUE THREAD

**Issue by ShukeshAiotel** [thingsboard/thingsboard#9324]
**Component**

 * Installation

**Description**

Hi everyone, 

I am facing issue while running boot-jar file in application/target, receiving following error. 

ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultTbMailConfigTemplateService': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [templates/mail_config_templates.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/thingspad/Documents/thingsboard/application/target/thingsboard-3.6.1-SNAPSHOT-boot.jar!/BOOT-INF/classes!/templates/mail_config_templates.json

@ashvayka @imbeacon @Ultrazombie @Karabiy @smatvienko-tb @pinkevmladchy, could you kindly assist with this issue?
 
Best regards,

**Environment**
 * OS:  ubuntu 20.04
 * ThingsBoard: CE 3.6

**Comment by digitalhero-m** [comment]
I have the same problem when updating ThingsBoard v3.5.1 to v3.6 with docker-compose.

**Enviroment**
OS: ubuntu 20.04.6 LTS 
Thingsboard: PE 3.6
Container: Docker version 23.0.4, build f480fb1

**Comment by ShukeshAiotel** [comment]
Hello @digitalhero-m 

Have you found a solution to the issue we are facing? 

Thanks in Advance.

**Comment by jortega11** [comment]
I am having the same problem using W10.

While looking for a solution I encountered #9311 where ThingsBoard stops after starting it. They ask for the [thingsboard.log](https://github.com/thingsboard/thingsboard/files/12791351/thingsboard.log) and [install.log](https://github.com/thingsboard/thingsboard/files/12791358/install.log)

**Comment by jortega11** [comment]
I have found that my error was caused because, while substituting the conf folder while doing the upgrade, I was not including a new file from version 3.6 whose name was `mail_config_templates.json`.
Now I am getting just one error in my [thingsboard.log](https://github.com/thingsboard/thingsboard/files/12791447/thingsboard.log) saying that `Error creating bean with name 'refreshTokenExpCheckService'`

**Comment by ShukeshAiotel** [comment]
Hello @jortega11 

I have fixed the issue by replacing getFile() with getInputStream() in DefaultTbMailConfigTemplateService.java. 

[refereed  sollution](https://stackoverflow.com/questions/25869428/classpath-resource-not-found-when-running-as-jar)

**Comment by ShukeshAiotel** [comment]
Hello @leitinhakk 

please find the attachment of  DefaultTbMailConfigTemplateService.java
 
`package org.thingsboard.server.service.mail;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;
import org.thingsboard.common.util.JacksonUtil;

import org.apache.commons.io.IOUtils;
import javax.annotation.PostConstruct;
import java.io.IOException;
import java.io.InputStream;
@Service
@Slf4j
public class DefaultTbMailConfigTemplateService implements TbMailConfigTemplateService {

    private JsonNode mailConfigTemplates;

    @PostConstruct
    private void postConstruct() throws IOException {
        try (InputStream inputStream = new ClassPathResource("/templates/mail_config_templates.json").getInputStream()) {
            String jsonContent = IOUtils.toString(inputStream, "UTF-8"); 
            mailConfigTemplates = JacksonUtil.toJsonNode(jsonContent); 
        } catch (IOException e) {
            log.error("Error loading mail config templates.", e);
            throw e;
        }
    }

    @Override
    public JsonNode findAllMailConfigTemplates() {
        return mailConfigTemplates;
    }
}`

**Comment by leitinhakk** [comment]
> Hello @leitinhakk
> 
> please find the attachment of DefaultTbMailConfigTemplateService.java
> 
> `package org.thingsboard.server.service.mail;
> 
> import com.fasterxml.jackson.databind.JsonNode; import lombok.extern.slf4j.Slf4j; import org.springframework.core.io.ClassPathResource; import org.springframework.stereotype.Service; import org.thingsboard.common.util.JacksonUtil;
> 
> import org.apache.commons.io.IOUtils; import javax.annotation.PostConstruct; import java.io.IOException; import java.io.InputStream; @service @slf4j public class DefaultTbMailConfigTemplateService implements TbMailConfigTemplateService {
> 
> ```
> private JsonNode mailConfigTemplates;
> 
> @PostConstruct
> private void postConstruct() throws IOException {
>     try (InputStream inputStream = new ClassPathResource("/templates/mail_config_templates.json").getInputStream()) {
>         String jsonContent = IOUtils.toString(inputStream, "UTF-8"); 
>         mailConfigTemplates = JacksonUtil.toJsonNode(jsonContent); 
>     } catch (IOException e) {
>         log.error("Error loading mail config templates.", e);
>         throw e;
>     }
> }
> 
> @Override
> public JsonNode findAllMailConfigTemplates() {
>     return mailConfigTemplates;
> }
> ```
> 
> }`

just to be sure, it's the file on "/thingsboard/application/src/main/java/org/thingsboard/server/service/mail" right?

**Comment by ShukeshAiotel** [comment]
Hello @leitinhakk 

yes, your on the right path.

**Comment by trikimiki** [comment]
Excluding building from sources case, this might happen due to one of the following:
- in configuration folder (`/usr/share/thingsboard/conf`), there is no `templates` folder present with the `mail_config_templates.json` file; in case of MSA installation, you might want to check your volumes if they are set up
- in config variables (environment and/or `/usr/share/thingsboard/conf/thingsboard.conf`), the value `LOADER_PATH=/usr/share/thingsboard/conf,/usr/share/thingsboard/extensions` is not present; in case of MSA installation, you might want to check your volumes/configmaps

**Comment by mixo3891** [comment]
I have problem.


Starting ThingsBoard Upgrade from version 3.6.1 ...
Clearing cache to upgrade from version 3.6.1 to 3.6.2
Clearing cache [securitySettings]
Clearing cache [resourceInfo]
Upgrading ThingsBoard from version 3.6.1 to 3.6.2 ...
Updating schema ...
Skip schema re-update to version 3.6.2. Use env flag 'SKIP_SCHEMA_VERSION_CHECK' to force the re-update.
Installing SQL DataBase schema views and functions: schema-views-and-functions.sql
Successfully executed query: DROP VIEW IF EXISTS device_info_view CASCADE;
Successfully executed query: CREATE OR REPLACE VIEW device_info_view AS SELECT * FROM device_info_active_attribute_view;
Updating system data...
Starting rule nodes upgrade ...
Finished rule nodes upgrade. Upgraded rule nodes count: 0
Loading system widgets
Unable to load widget type from json: [/usr/share/thingsboard/data/json/system/widget_types/update_server_location_attribute.json]
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to load widget type from json
at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:249)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.thingsboard.server.service.install.InstallScripts.loadSystemWidgets(InstallScripts.java:241)
at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.loadSystemWidgets(DefaultSystemDataLoaderService.java:538)
at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:288)
at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:752)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
at org.thingsboard.server.dao.resource.BaseImageService$$EnhancerBySpringCGLIB$$2298e34d.replaceBase64WithImageUrl()
at org.thingsboard.server.dao.widget.WidgetTypeServiceImpl.saveWidgetType(WidgetTypeServiceImpl.java:97)
at org.thingsboard.server.service.install.InstallScripts.lambda$loadSystemWidgets$5(InstallScripts.java:246)
... 13 common frames omitted
Unexpected error during ThingsBoard installation!
ThingsBoard upgrade failed!
