### ISSUE TITLE
License check fails and loses track of instance ID in the presence of zero disk space.

### ISSUE THREAD

**Issue by ianso-msf** [thingsboard/thingsboard#9357]
**Describe the bug**

This bug report linked to your license check for the PE edition.

When the disk that Thingsboard is running on is temporarily out of space during the license check, or has another process aggressively consuming all available space, the following sequence occurs:

1/ TB deletes it's license file

2/ Makes a rest call to your license server

3/ Another process uses all the space --> 0 bytes disk space free

4/ rest call to the license server returns

5/ TB attempts to write the new license file and fails

6/ On the next license check, even with disk space free, TB assumes it's a new instance, and TB shuts down with "license capacity exceeded".

This has been an unfortunate side-effect of other problems we've been having that are obviously not your fault :-)

However, your license instance checking process would be more robust if you, instead of deleting and rewriting the license file, zeroed it out / replaced the contents with NULs in step 1 above. Then, TB can be confident that nobody else will take the space it's been using. (I would also pad the file to a fixed size rounded up to the nearest 10KB above your normal license file size so that you can write more bytes if needed)

**Your Server Environment**

Docker container running on a server with many other applications, with the log an data volumes bound to directories on a shared disk.

**Your Client Environment**
N/A

**To Reproduce**
1. create a very small volume and mount TB PE docker volumes inside the volume
2. write a bash script or something that writes to the volume until 0 bytes are free, and then blocks until 1 bytes is free, consumes it, waits...
3. run the license check in TB PE
4. See error in the log files

**Expected behavior**
Even if no disk space is free, TB license check should still work. 

**Screenshots**
Logs:

````
2023-10-04 20:56:51,726 [pool-2-thread-1] INFO  o.t.license.client.TbLicenseClient - planData: {                                                                                                    [0/159]
  "maxassets" : {
    "value" : -1,
    "description" : "Assets amount limitation"
  },
  "maxdevices" : {
    "value" : -1,
    "description" : "Devices amount limitation"
  },
  "plan" : {
    "value" : "Perpetual",
    "description" : "Plan name"
  },
  "whitelabeling" : {
    "value" : true,
    "description" : "White-labeling feature"
  }
}
2023-10-04 21:56:51,868 [pool-2-thread-1] ERROR o.t.license.client.TbLicenseClient - License Error: GENERAL_ERROR(300) - Failed to persist instance data into: "/data/license.data"!
2023-10-04 21:56:51,912 [pool-2-thread-1] ERROR o.t.license.client.TbLicenseClient - General Error occurred!
org.thingsboard.license.shared.exception.LicenseException: Failed to persist instance data into: "/data/license.data"!
        at org.thingsboard.license.client.TbLicenseClient.persistInstanceData(TbLicenseClient.java:407)
        at org.thingsboard.license.client.TbLicenseClient.persistInstanceData(TbLicenseClient.java:397)
        at org.thingsboard.license.client.TbLicenseClient.checkInstance(TbLicenseClient.java:380)
        at org.thingsboard.license.client.TbLicenseClient.checkInstanceTask(TbLicenseClient.java:358)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: No space left on device
        at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at java.base/sun.nio.ch.FileDis2023-10-04 22:05:34,039 [main] INFO  o.t.license.client.TbLicenseClient - Initializing ThingsBoard License Client, Release Date [2023-02-07]
2023-10-04 22:05:34,868 [main] ERROR o.t.license.client.TbLicenseClient - License Error: ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104) - Active instances capacity exceeded!
2023-10-04 22:05:34,869 [main] ERROR o.t.license.client.TbLicenseClient - Failed to initialize ThingsBoard License Client!
2023-10-04 22:05:34,872 [main] ERROR o.t.s.d.s.BasicSubscriptionService - Failed to init license client
````

**Additional context**

**Comment by ianso-msf** [comment]
Hi everyone, just to query if this is something that is on your radar?

**Comment by Ultrazombie** [comment]
There are no plans to change this behavior.
This is normal behavior because the license server is trying to update the instance-license.data file, and there is not enough space. Please read how the license server works: https://thingsboard.io/products/license-server/ and please keep free space on your disk.
