### ISSUE TITLE
Critical error on rulechain save: Incorrect parameter name in enrichment nodes:

### ISSUE THREAD

**Issue by curt-k** [thingsboard/thingsboard#9377]
**Describe the bug**
Error starting rule chane when Enrichment rules are added or edited in a rule chain..
Seems like a refactoring-related error where "fieldsMapping" was updated to "dataMapping"
This is replicatable in both my development and production environments.

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version: 3.6.0 (recently upgraded from 3.5.1)
  * Docker on windows

**Your Client Environment**
Web browser (Edge)

* OS: Windows
* Browser Edge
* Version --

**To Reproduce**
1. Add an enrichment node and configure.
2. Save the ruleset.
3. See error / Alert "Start failure in Rule Chain..."
4.  Error text: 'Unrecognized field "fieldsMapping" (class org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsConfiguration), not marked as ignorable (3 known properties: "ignoreNullStrings", "dataMapping", "fetchTo"])'

**Expected behavior**
The rule should work.

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/119271415/59397ca8-1cc0-4f76-b2e9-4b896ff0ac2d)

**Additional context**
Just upgraded from 3.5.1 to 3.6.0

Full error text from node:
org.thingsboard.rule.engine.api.TbNodeException: java.lang.IllegalArgumentException: Can't convert value: {"fieldsMapping":{"additionalInfo.description":"Description"},"ignoreNullStrings":true}
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:47)
	at org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsNode.loadNodeConfiguration(TbGetOriginatorFieldsNode.java:55)
	at org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsNode.loadNodeConfiguration(TbGetOriginatorFieldsNode.java:37)
	at org.thingsboard.rule.engine.metadata.TbAbstractNodeWithFetchTo.init(TbAbstractNodeWithFetchTo.java:47)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:173)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:64)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:68)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$initActor$0(TbActorMailbox.java:61)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalArgumentException: Can't convert value: {"fieldsMapping":{"additionalInfo.description":"Description"},"ignoreNullStrings":true}
	at org.thingsboard.common.util.JacksonUtil.treeToValue(JacksonUtil.java:153)
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:45)
	... 15 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "fieldsMapping" (class org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsConfiguration), not marked as ignorable (3 known properties: "ignoreNullStrings", "dataMapping", "fetchTo"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsConfiguration["fieldsMapping"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2036)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3295)
	at org.thingsboard.common.util.JacksonUtil.treeToValue(JacksonUtil.java:151)
	... 16 more

**Comment by curt-k** [comment]
EDIT:: I can confirm that this applies strictly to newly added rule nodes. Old nodes from the previous (3.5.1) version of thingsboard may be edited and rulechains saved without the error. As soon as a new enrichment node is added, however, the save action causes the error.

EDIT2:: Not All Enrichment nodes are affected. Based on my testing:
- Calculate data: Success (no error)
- customer attributes FAIL
- customer details FAIL
- originator attributes SUCCESS
- originator Fields FAIL

**Comment by curt-k** [comment]
Further INFO:
Old rules continue to function if unedited. When an offending rule is opened, it does not display the configured attributes.
![image](https://github.com/thingsboard/thingsboard/assets/119271415/ccf8ec82-68cc-4b89-86a6-f98d8fa3ba64)

If i add an attribute to the rule and save, however, then I receive the error above.

**Comment by loicHercogener** [comment]
same error and conclusion https://github.com/thingsboard/thingsboard/issues/9392

**Comment by den1jkee** [comment]
Greetings,

Could you please provide install.log and thingsboard.log when this issue occurs?
Also, please provide a JSON file of the Rule Chain with the Originator fields node.

Best regards,
Denys

**Comment by curt-k** [comment]
[enrichment_node_bug.json](https://github.com/thingsboard/thingsboard/files/12875862/enrichment_node_bug.json)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/12875864/thingsboard.log)
[install.log](https://github.com/thingsboard/thingsboard/files/12875865/install.log)

**Comment by curt-k** [comment]
Shared to the issue.

**Comment by den1jkee** [comment]
Hi @curt-k ,
You need to clear all cache&cookies. 
After it try to create a new enrichment nodes and test it. 
If it doens't help you, please follow the answer I've linked https://github.com/thingsboard/thingsboard/issues/9392#issuecomment-1757543974


Best regards,
Denys

**Comment by curt-k** [comment]
Clearing cache and cookies resolved the issue. I can now add and configure enrichment nodes that were previously throwing the error.
