### ISSUE TITLE
[Bug] Impossible to configure rule node Enrichment - originator fields

### ISSUE THREAD

**Issue by loicHercogener** [thingsboard/thingsboard#9392]
**Describe the bug**
I just update  to 3.6.0PE and now its impossible to configure the rule node "Enrichment - originator fields"
I have an error on start describe just after. And my old rule node configure show no configuration. 
error onStart: 
```
org.thingsboard.rule.engine.api.TbNodeException: java.lang.IllegalArgumentException: Can't convert value: {"fieldsMapping":{"name":"name"},"ignoreNullStrings":false}
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:62)
	at org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsNode.loadNodeConfiguration(TbGetOriginatorFieldsNode.java:70)
	at org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsNode.loadNodeConfiguration(TbGetOriginatorFieldsNode.java:52)
	at org.thingsboard.rule.engine.metadata.TbAbstractNodeWithFetchTo.init(TbAbstractNodeWithFetchTo.java:62)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:188)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:79)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:78)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:72)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:83)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$initActor$0(TbActorMailbox.java:76)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalArgumentException: Can't convert value: {"fieldsMapping":{"name":"name"},"ignoreNullStrings":false}
	at org.thingsboard.common.util.JacksonUtil.treeToValue(JacksonUtil.java:188)
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:60)
	... 15 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "fieldsMapping" (class org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsConfiguration), not marked as ignorable (3 known properties: "ignoreNullStrings", "dataMapping", "fetchTo"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.thingsboard.rule.engine.metadata.TbGetOriginatorFieldsConfiguration["fieldsMapping"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2036)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3295)
	at org.thingsboard.common.util.JacksonUtil.treeToValue(JacksonUtil.java:186)
	... 16 more

```

**Your Server Environment**
* docker deploymenent with 3.6.0 PE

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: windows
* Browser all

**To Reproduce**
1. create a rule node Enrichment - originator fields
2. try to configure
3. save
4. See error in the debug menu of the node

**Screenshots**
![image](https://github.com/thingsboard/thingsboard/assets/124673070/621b7a01-b995-41a9-b7ba-71e940e1a3ec)

**Comment by loicHercogener** [comment]
Hello,

when i recreate a node originator fields I don't have the new ui but the old one which create error. How can i fix that.

**Comment by den1jkee** [comment]
Hi,
Could you please provide the following files:
1. JSON file of Rule Chain with the originator fields node
2. install.log and thingsboard.log file
Thanks.

Best regards,
Denys

**Comment by loicHercogener** [comment]
[install.log](https://github.com/thingsboard/thingsboard/files/12867863/install.log) the update is at : 2023-10-10 10:41:15,045
[thingsboard.zip](https://github.com/thingsboard/thingsboard/files/12867911/thingsboard.zip)

[common_geofencing.json](https://github.com/thingsboard/thingsboard/files/12867915/common_geofencing.json) rule chain

**Comment by den1jkee** [comment]
Hi,
As I said earlier, for some reason, your rule node was not properly updated during the upgrade process.
I've attached modified rule chain with working nodes.
The changes was in **fieldsMapping**  changed to **dataMapping** and also you need to add for some nodes instead of **fetchToData: false** -> **fetchTo: "METADATA" (or "DATA")**
![image](https://github.com/thingsboard/thingsboard/assets/113901187/a857641c-3c4b-4a91-a08e-1b1ddd357ff9)
and after changes its should have a view like that:
![image](https://github.com/thingsboard/thingsboard/assets/113901187/89a95898-753c-4ded-ab58-5f68ece3e16b)
[common_geofencing.json](https://github.com/thingsboard/thingsboard/files/12869394/common_geofencing.json)
In addition, you can delete this field `"configurationVersion": 1,` for updating your rule node while importing, but it is not recommend option.
Best regards,
Denys

**Comment by loicHercogener** [comment]
I have find the error. I just need to clear all cookies.

**Comment by den1jkee** [comment]
Hi @loicHercogener ,
Can you confirm that everything is working as expected after clearing all cache and cookies?
Also, in Lifecycle events node is Started?

Best regards,
Denys

**Comment by loicHercogener** [comment]
Yes all is working after clean the cache

**Comment by evanderbird** [comment]
hi guys, can you tell me where this cache & cookies, how to clear it?
