### ISSUE TITLE
[Question] Error when upgrading from 3.5.1 to 3.6.0 (with Docker)

### ISSUE THREAD

**Issue by SmartieTV** [thingsboard/thingsboard#9452]
**Component**

 * Installation (Upgrade)

**Description**
When upgrading from 3.5.1 to 3.6.0, I receive an error, preventing the upgrade from completing:

`$ docker run -it -v ~/.mytb-data:/data --rm thingsboard/tb-postgres upgrade-tb.sh
Starting Postgresql...
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2023-10-18 19:39:14.911 UTC [12] LOG:  starting PostgreSQL 12.16 (Debian 12.16-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-10-18 19:39:14.915 UTC [12] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-10-18 19:39:14.915 UTC [12] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2023-10-18 19:39:14.915 UTC [12] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2023-10-18 19:39:15.058 UTC [12] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-18 19:39:15.251 UTC [13] LOG:  database system was interrupted; last known up at 2023-10-18 19:32:07 UTC
2023-10-18 19:39:15.438 UTC [13] LOG:  database system was not properly shut down; automatic recovery in progress
2023-10-18 19:39:15.464 UTC [13] LOG:  redo starts at 0/805F3E68
2023-10-18 19:39:15.471 UTC [13] LOG:  invalid record length at 0/80617520: wanted 24, got 0
2023-10-18 19:39:15.471 UTC [13] LOG:  redo done at 0/806174E8
2023-10-18 19:39:15.650 UTC [12] LOG:  database system is ready to accept connections
 done
server started
Postgresql is ready
Starting ThingsBoard upgrade ...
  ______    __      _                              ____                               __
 /_  __/   / /_    (_)   ____    ____ _   _____   / __ )  ____   ____ _   _____  ____/ /
  / /     / __ \  / /   / __ \  / __ `/  / ___/  / __  | / __ \ / __ `/  / ___/ / __  /
 / /     / / / / / /   / / / / / /_/ /  (__  )  / /_/ / / /_/ // /_/ /  / /    / /_/ /
/_/     /_/ /_/ /_/   /_/ /_/  \__, /  /____/  /_____/  \____/ \__,_/  /_/     \__,_/
                              /____/

 ===================================================
 :: ThingsBoard ::       (v3.6.0)
 ===================================================

Starting ThingsBoard Upgrade from version 3.6.0 ...
Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 3.6.0
	at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:268)
	at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Unexpected error during ThingsBoard installation!
waiting for server to shut down....2023-10-18 19:41:31.607 UTC [12] LOG:  received fast shutdown request
2023-10-18 19:41:31.683 UTC [12] LOG:  aborting any active transactions
2023-10-18 19:41:31.696 UTC [12] LOG:  background worker "logical replication launcher" (PID 19) exited with exit code 1
2023-10-18 19:41:31.706 UTC [14] LOG:  shutting down
2023-10-18 19:41:32.086 UTC [12] LOG:  database system is shut down
 done
server stopped
`

As I'm not even remotely an expert with Docker (and TB), I don't know how to combat this. 
I have also attempted applying some recommendations of this thread, so far without any luck: #3347 

Thanks for your help. 

**Environment**
 * OS:  Ubuntu 22.04.03 LTS, Docker 24.0.6
 * ThingsBoard: 3.5.1 to 3.6.0 (CE, Postgres DB)

**Comment by mykhailokornieiev** [comment]
Hi. First of all, check if you really previously used Thingsboard CE 3.5.1, because it's necessary to make upgrades from version to version one by one. The order of upgrades is described in this document https://thingsboard.io/docs/user-guide/install/upgrade-instructions/
Also, check your ~/.mytb-data/.upgradeversion, in case of 3.5.1->3.6 upgrade its value must be 3.5.1, so the output in logs must write " fromVersion 3.5.1", but in your case it write "unsupported fromVersion 3.6"
After that try to repeat the steps from this document unsupported

**Comment by SmartieTV** [comment]
Hi, thanks for your help.
The TB-CE version is currently 3.5.1, at least that's what the "Admin Dashboard" is showing,
(interestingly, it also states that I'm running the newest version):
<img width="479" alt="SC1" src="https://github.com/thingsboard/thingsboard/assets/50147612/9ee23a55-5af9-49ac-8189-c8a4603736cc">

For this reason I thought it would be fine to just update to the newest version (3.6) according to [this document](https://thingsboard.io/docs/user-guide/install/docker/#upgrading).

**Comment by SmartieTV** [comment]
Got back to this topic and found the issue: 
~/.mytb-data/.upgradeversion contained "3.6.0". I changed it to "3.5.1" and this fixed the issue. 
The bug regarding the incorrect "Version is up to date" notice (see screenshot above) has remained in version 3.6.0...
