### ISSUE TITLE
[Question] error after psql database migrator

### ISSUE THREAD

**Issue by thieleon** [thingsboard/thingsboard#9482]
**Component**
Thingsboard PE

 * Installation

**Description**
I'm trying to migrate thingsboard to a hybrid model of cassandra and postgres. For that I used the [migrator tool provided by thingsboard](https://github.com/thingsboard/database-migrator). The migrator works fine, I was able to import the data into the seperate cassandra server.  I installed postgres on another server ran the `/usr/share/thingsboard/bin/install/installer.sh`. Thingsboard is starting fine and is "working" (at least it's accessible from the browser). 

Then I stopped thingsboard, imported the database dump to postgres, but thingsboard is now not able to start anymore: _license error_.
So I thought I need to run the install again. In that installer I now get the following errors:
1. the first error is ENUM "FLOW" not found. This was solved as suggested [in this thread ](https://github.com/thingsboard/thingsboard/issues/478) `DELETE FROM public.component_descriptor WHERE type = 'FLOW';`
2. after solving error 1, I now get this error: 

```
:~# /usr/share/thingsboard/bin/install/install.sh 
 :: ThingsBoard Professional Edition ::       (v3.2.2PE)
 ===================================================

Warning: Nashorn engine is planned to be removed from a future JDK release
Starting ThingsBoard Installation...
Installing DataBase schema for entities...
Installing SQL DataBase schema part: schema-entities.sql
Installing SQL DataBase schema indexes part: schema-entities-idx.sql
Installing DataBase schema for timeseries...
Installing Cassandra DataBase schema part: schema-ts.cql
Loading system data...
Unexpected error during ThingsBoard installation!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:281)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:531)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:154)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy161.findByDefaultTrue(Unknown Source)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantProfileDao.findDefaultTenantProfile(JpaTenantProfileDao.java:88)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantProfileDao$$FastClassBySpringCGLIB$$de80341a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
        at org.thingsboard.server.dao.sql.tenant.JpaTenantProfileDao$$EnhancerBySpringCGLIB$$e7cb83a1.findDefaultTenantProfile(<generated>)
        at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl.findDefaultTenantProfile(TenantProfileServiceImpl.java:179)
        at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl.findOrCreateDefaultTenantProfile(TenantProfileServiceImpl.java:159)
        at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl$$FastClassBySpringCGLIB$$67564a4a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
        at org.thingsboard.server.dao.tenant.TenantProfileServiceImpl$$EnhancerBySpringCGLIB$$5127660.findOrCreateDefaultTenantProfile(<generated>)
        at org.thingsboard.server.service.install.DefaultSystemDataLoaderService.createDefaultTenantProfiles(DefaultSystemDataLoaderService.java:174)
        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:251)
        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2303)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2056)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2018)
        at org.hibernate.loader.Loader.doQuery(Loader.java:948)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
        at org.hibernate.loader.Loader.doList(Loader.java:2849)
        at org.hibernate.loader.Loader.doList(Loader.java:2831)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2663)
        at org.hibernate.loader.Loader.list(Loader.java:2658)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1414)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1625)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1593)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1641)
        at jdk.internal.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:409)
        at com.sun.proxy.$Proxy216.getSingleResult(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:196)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        ... 29 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: column tenantprof0_.isolated_tb_core does not exist
  Position: 165
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
        ... 62 common frames omitted
```
I don't know what to do or try next. Every thing I tried failed. How am I supposed to move the postgres database from one server to another? I read those threads:

- https://github.com/thingsboard/thingsboard/issues/6598
- https://github.com/thingsboard/thingsboard/issues/3641

but they seems to have a different problem. 

What should I do?

**Environment**

 * OS:  debian 10
 * ThingsBoard: 3.2.2PE
 * Browser: -

**Comment by pon0marev** [comment]
You did not provide a license error log, so it is not clear why you had a license error. This often happens when the thingsboard is run on different servers with the same key. The following instructions solve most cases of license issues:
1. Stop your ThingsBoard service
`sudo systemctl stop thingsboard`

2. Delete license data file
`sudo rm -f /usr/share/thingsboard/bin/instance-license.data`

3. On the[ License portal](https://license.thingsboard.io/) locate and deactivate the current active instance ID (MANAGE INSTANCES button) to make the license key free for usage). DO NOT DELETE License KEY itself, DO NOT CHANGE the instance count. 

4. Start ThingsBoard service again
`sudo systemctl start thingsboard`

To migrate, you need to perform:
+ Prepare the new server: Standart Thingsboard new Installation procedure [Installing ThingsBoard PE on Ubuntu](https://thingsboard.io/docs/user-guide/install/pe/ubuntu/) 

+ Start migration: shut down current Thingsboard and make DB backup https://github.com/thingsboard/ThingsboardSupport/tree/main/databases

+ Transfer the database to the new server

+ Disable the current Instance ID on the License Portal

+ Reconfigure domain names to the new IP

+ Restore the database from the transferred backup on the new instance.

+ Start Thingsboard on the new server

+ Check data in UI for consistency


### How to create a simple Postgres backup:

```
pg_dump -v -U postgres -h 127.0.0.1 -d thingsboard > thingsboard-$(date +'%m-%d-%y_%H:%M').sql
(paste your postgres password)
```

### How to restore the Postgres database:
`psql -U postgres -h localhost -d thingsboard < thingsboard-13-06-2023.sql`

The data from the backup needs to be restored to an empty database. Note that you do not need to execute the install script after restoring the database from a backup.
