### ISSUE TITLE
[Question] Rule node extension can't be loaded in AWS ARM EC2 instance

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard#9537]
**Component**

 * Generic

**Description**
Rule node extension with the following dependency can't be loaded in AWS ARM EC2 instance, and thingsboard.log is totally empty, same jar file works fine with Intel and AMD instances.

```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <main.dir>${basedir}</main.dir>
        <thingsboard.version>3.6.0</thingsboard.version>
        <lombok.version>1.18.18</lombok.version>
        <guava.version>31.1-jre</guava.version>
        <!--         TEST SCOPE         -->
        <spring-boot-starter-test.version>2.7.10</spring-boot-starter-test.version>
        <jupiter.version>5.8.2</jupiter.version> <!-- keep the same version as spring-boot-starter-test depend on jupiter-->
        <awaitility.version>4.1.0</awaitility.version>
        <commons-io.version>2.11.0</commons-io.version>
        <netty.version>4.1.91.Final</netty.version>
        <spring-data-redis.version>2.7.10</spring-data-redis.version>
        <protobuf.version>3.21.9</protobuf.version>
    </properties>
....
....
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>9.2.0</version>
            <scope>compile</scope>
        </dependency>
```

```
java.lang.ClassNotFoundException: org.thingsboard.rule.engine.node.external.TbFirebaseCloudMessageNode
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:171)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:64)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:68)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$tryInit$1(TbActorMailbox.java:90)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Environment**

 * OS:
 ```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
# uname -a
Linux ip-172-31-70-163 6.2.0-1015-aws #15~22.04.1-Ubuntu SMP Fri Oct  6 23:21:18 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
 * ThingsBoard: 3.6.0

**Comment by maksonlee** [comment]
don't know why, but it seems to work if we change the version of firebase admin sdk from 9.2.0 to 8.0.1.

**Comment by maksonlee** [comment]
more exactly, extension included firebase admin sdk versions after 9.0.0 don't work with ThingsBoard 3.6.0 on ARM instance.

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
