### ISSUE TITLE
MQTT stop working in TB 2.0.4 when using performance-test

### ISSUE THREAD

**Issue by issacsonjj** [thingsboard/thingsboard#961]
I have TB 2.0.4 installed on Ubuntu 17.10 (i7, 16GB) and tested it with [performance-test](https://github.com/thingsboard/performance-tests), configuration was

```
restUrl=http://localhost:58080

mqttUrls=tcp://localhost:51883

deviceCount=1000

publishTelemetryCount=300

publishTelemetryPause=1000

username=tenant@thingsboard.org

password=tenant
```

In performance-test I got a lot of exception log like   

```
Exception in thread "hawtdispatch-DEFAULT-2" Exception in thread "hawtdispatch-DEFAULT-4" Exception in thread "hawtdispatch-DEFAULT-1" java.lang.IllegalStateException: No connection listener set to handle message received from the server.
        at org.fusesource.mqtt.client.CallbackConnection.createListenerNotSetError(CallbackConnection.java:951)
        at org.fusesource.mqtt.client.CallbackConnection.access$000(CallbackConnection.java:73)
        at org.fusesource.mqtt.client.CallbackConnection$1.onPublish(CallbackConnection.java:96)
        at org.fusesource.mqtt.client.CallbackConnection.toReceiver(CallbackConnection.java:911)
        at org.fusesource.mqtt.client.CallbackConnection.processFrame(CallbackConnection.java:808)
        at org.fusesource.mqtt.client.CallbackConnection.access$1700(CallbackConnection.java:73)
        at 

org.fusesource.mqtt.client.CallbackConnection$6.onTransportCommand(CallbackConnection.java:425)
        at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:713)
        at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592)
        at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
        at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
        at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
java.lang.IllegalStateException: No connection listener set to handle message received from the server.
        at 

org.fusesource.mqtt.client.CallbackConnection.createListenerNotSetError(CallbackConnection.java:951)
        at org.fusesource.mqtt.client.CallbackConnection.access$000(CallbackConnection.java:73)
        at org.fusesource.mqtt.client.CallbackConnection$1.onPublish(CallbackConnection.java:96)
        at org.fusesource.mqtt.client.CallbackConnection.toReceiver(CallbackConnection.java:911)
        at org.fusesource.mqtt.client.CallbackConnection.processFrame(CallbackConnection.java:808)
        at org.fusesource.mqtt.client.CallbackConnection.access$1700(CallbackConnection.java:73)
        at 

org.fusesource.mqtt.client.CallbackConnection$6.onTransportCommand(CallbackConnection.java:425)
        at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:713)
        at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592)
        at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
        at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
        at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
java.lang.IllegalStateException: No connection listener set to handle message received from the server.
        at 

org.fusesource.mqtt.client.CallbackConnection.createListenerNotSetError(CallbackConnection.java:951)
        at org.fusesource.mqtt.client.CallbackConnection.access$000(CallbackConnection.java:73)
        at org.fusesource.mqtt.client.CallbackConnection$1.onPublish(CallbackConnection.java:96)
        at org.fusesource.mqtt.client.CallbackConnection.toReceiver(CallbackConnection.java:911)
        at org.fusesource.mqtt.client.CallbackConnection.processFrame(CallbackConnection.java:808)
        at org.fusesource.mqtt.client.CallbackConnection.access$1700(CallbackConnection.java:73)
        at 

org.fusesource.mqtt.client.CallbackConnection$6.onTransportCommand(CallbackConnection.java:425)
        at org.fusesource.hawtdispatch.transport.TcpTransport.drainInbound(TcpTransport.java:713)
        at org.fusesource.hawtdispatch.transport.TcpTransport$6.run(TcpTransport.java:592)
        at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
        at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
        at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
```

Finally this test won't finish because no more telemetry will be pushed to TB. 

```
2018-07-25 14:28:57                                        1055s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=24482  KO=0     )
> publish                                                  (OK=24482  KO=0     )

---- Scenario Name -------------------------------------------------------------
[####----------------------------------------------------------------------]  6%
          waiting: 0      / active: 935    / done:65
```

If reduce "deviceCount" to a lower value(10, for example), no exception will occur and the test will be OK. 

**The issue doesn't occur on TB 1.4.**

**Comment by LeoMorgan113** [comment]
Hi @issacsonjj,

Fixed in v3.2.2.
Keep on update: https://thingsboard.io/docs/reference/releases/
