### ISSUE TITLE
[Bug] org.thingsboard.server.dao.exception.DataValidationException: Validation error: alarmId must not be null 

### ISSUE THREAD

**Issue by thanhbinh89** [thingsboard/thingsboard#9655]
*This is my device profile:
![image](https://github.com/thingsboard/thingsboard/assets/15308247/06c7ff2f-cc9e-40d0-94bb-e1ea1923296f)

*Explain:
capture: image jpeg (base64 string)
criticalCameraEn: notify enable flag

*Rule chain debug failure (at "Action - device profile" node):
org.thingsboard.server.dao.exception.DataValidationException: Validation error: alarmId must not be null
	at org.thingsboard.server.dao.service.ConstraintValidator.validateFields(ConstraintValidator.java:59)
	at org.thingsboard.server.dao.service.ConstraintValidator.validateFields(ConstraintValidator.java:53)
	at org.thingsboard.server.dao.alarm.BaseAlarmService.validateAlarmRequest(BaseAlarmService.java:476)
	at org.thingsboard.server.dao.alarm.BaseAlarmService.updateAlarm(BaseAlarmService.java:92)
	at org.thingsboard.server.dao.alarm.BaseAlarmService$$FastClassBySpringCGLIB$$fa70d6a2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at org.thingsboard.server.dao.alarm.BaseAlarmService$$EnhancerBySpringCGLIB$$4771c23e.updateAlarm(<generated>)
	at org.thingsboard.server.service.telemetry.DefaultAlarmSubscriptionService.updateAlarm(DefaultAlarmSubscriptionService.java:93)
	at org.thingsboard.rule.engine.profile.AlarmState.calculateAlarmResult(AlarmState.java:239)
	at org.thingsboard.rule.engine.profile.AlarmState.createOrClearAlarms(AlarmState.java:112)
	at org.thingsboard.rule.engine.profile.AlarmState.process(AlarmState.java:78)
	at org.thingsboard.rule.engine.profile.DeviceState.processTelemetry(DeviceState.java:270)
	at org.thingsboard.rule.engine.profile.DeviceState.process(DeviceState.java:140)
	at org.thingsboard.rule.engine.profile.TbDeviceProfileNode.onMsg(TbDeviceProfileNode.java:135)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:153)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:101)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.doProcess(RuleNodeActor.java:60)
	at org.thingsboard.server.actors.service.ContextAwareActor.process(ContextAwareActor.java:41)
	at org.thingsboard.server.actors.TbActorMailbox.processMailbox(TbActorMailbox.java:142)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by mykhailokornieiev** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity. If it is still relevant, feel free to open a new ticket with a full description of your request.
