### ISSUE TITLE
onRuleMsg java.lang.IllegalStateException: Rule chain is not active!

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#973]
java.lang.IllegalStateException: Rule chain is not active!
	at org.thingsboard.server.actors.shared.ComponentMsgProcessor.checkActive(ComponentMsgProcessor.java:85)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:103)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:72)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:45)
	at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:43)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ashvayka** [comment]
I've seen this sometimes when one of the rules in rule chain is not able to initialize. Check rule nodes lifecycle messages.

**Comment by mfalkvidd** [comment]
I got the same problem but reported it in the user discussion forum instead. Adding reference in case it helps someone: https://groups.google.com/forum/m/#!topic/thingsboard/81kuj5CmXQo

**Comment by mfalkvidd** [comment]
![img_2455](https://user-images.githubusercontent.com/893502/43490845-8841a6d4-9522-11e8-9cda-751957a703e1.PNG)

Looks like the script failed to start the first time it was created (due to syntax error), and later updates did not (re)start the script?

**Comment by caoyingde** [comment]
org.thingsboard.rule.engine.api.TbNodeException: java.lang.RuntimeException: Failed to connect to MQTT broker at 47.106.149.52:1884.
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.init(TbMqttNode.java:73)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:117)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:58)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onUpdate(RuleNodeActorMessageProcessor.java:73)
	at org.thingsboard.server.actors.service.ComponentActor.onComponentLifecycleMsg(ComponentActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:42)
	at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:43)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Failed to connect to MQTT broker at 47.106.149.52:1884.
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.initClient(TbMqttNode.java:126)
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.init(TbMqttNode.java:71)
	... 18 more

**Comment by mfalkvidd** [comment]
@caoyingde sorry for barging in on your thread. I found the cause of my problem, I had a //-style comment in my code. Turns out that gives syntax error, which results in the rule not starting. I changed the comment to use /* ... */ which works. I'll stay out of your thread now :-)

**Comment by caoyingde** [comment]
@mfalkvidd Do you remember the file class that triggered the problem? I did not find the error code of the annotation.

**Comment by mfalkvidd** [comment]
```
java.lang.IllegalArgumentException: Can't compile script: javax.script.ScriptException: <eval>:9:2 Expected } but found eof
 }
  ^ in <eval> at line number 9 at column number 2
	at org.thingsboard.server.service.script.RuleNodeJsScriptEngine.<init>(RuleNodeJsScriptEngine.java:48)
	at org.thingsboard.server.actors.ruleChain.DefaultTbContext.createJsScriptEngine(DefaultTbContext.java:157)
	at org.thingsboard.rule.engine.filter.TbJsFilterNode.init(TbJsFilterNode.java:48)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:117)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:58)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onUpdate(RuleNodeActorMessageProcessor.java:73)
	at org.thingsboard.server.actors.service.ComponentActor.onComponentLifecycleMsg(ComponentActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:42)
	at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:43)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by caoyingde** [comment]
My latest version does not use "return msg.Temp >= 61695; // Test comment" fragment.

**Comment by caoyingde** [comment]
@ashvayka @mfalkvidd 
onLifecycleMsg:
===================================
org.thingsboard.rule.engine.api.TbNodeException: java.lang.RuntimeException: Failed to connect to MQTT broker at 47.106.143.1:1884.
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.init(TbMqttNode.java:73)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:117)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:58)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onUpdate(RuleNodeActorMessageProcessor.java:73)
	at org.thingsboard.server.actors.service.ComponentActor.onComponentLifecycleMsg(ComponentActor.java:97)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:42)
	at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:43)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Failed to connect to MQTT broker at 47.106.143.1:1884.
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.initClient(TbMqttNode.java:126)
	at org.thingsboard.rule.engine.mqtt.TbMqttNode.init(TbMqttNode.java:71)
	... 18 more

**Comment by ppoektos** [comment]
@caoyingde @mfalkvidd @ashvayka 
Hi.
I've the same issue while using MQTT external node in my rule.
![Screenshot_20190717_110802](https://user-images.githubusercontent.com/1829833/61358599-59115100-a883-11e9-8853-c5b8f7306986.png)
The REST API CALL node works well but MQTT node has errors in Lificycle and Error event types:

> Rule chain is not active!

and

> Failed to connect to MQTT broker at ''

How to debug this?
In Transformation node I don't have any comments in code:
```
metadata.Voltage = msg.voltage;
return {msg: msg, metadata: metadata, msgType: msgType};
```
There is content of OUT events of "Get V" Transformation node:
![Screenshot_20190717_111851](https://user-images.githubusercontent.com/1829833/61359427-f325c900-a884-11e9-95fe-d3adf66ca84a.png)
![Screenshot_20190717_111931](https://user-images.githubusercontent.com/1829833/61359432-f5882300-a884-11e9-927d-3238bf5871e1.png)

**Comment by songkemail** [comment]
@ppoektos mqtt clientid length must less than 23 characters
