### ISSUE TITLE
Things Board local instance is not working properly

### ISSUE THREAD

**Issue by SuneethaYamani** [thingsboard/thingsboard#996]
Hi,
`I installed thingsboard locally in windows 10.Every half hour once i need to restart service.OtherWise I am not getting response from service`

**Comment by SuneethaYamani** [comment]
@vparomskiy ,
```
What Database are you using (HSQL DB, Cassandra or Postgres)?---HSQL DB
How many requests/devices are connected to the thingsboard?-- 3 devices
Could you please share thingsboard log files. It is not an expected behavior and the system should be stable.------------
2018-08-07 17:52:07,839 [Akka-akka.actor.default-dispatcher-23] WARN  akka.actor.OneForOneStrategy - null
2018-08-07 17:52:10,576 [Akka-akka.actor.default-dispatcher-23] ERROR akka.actor.ActorCell - changing Resume into Create after akka.actor.ActorInitializationException: exception during creation
2018-08-07 17:52:18,068 [Akka-akka.actor.default-dispatcher-23] ERROR o.t.server.actors.tenant.TenantActor - Unknown failure
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
	at akka.actor.ActorCell.create(ActorCell.scala:606)
	at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:130)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:374)
	at akka.actor.dungeon.FaultHandling$class.faultResume(FaultHandling.scala:102)
	at akka.actor.ActorCell.faultResume(ActorCell.scala:374)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:466)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException: null
2018-08-07 17:52:29,652 [pool-21-thread-3] INFO  o.h.e.j.b.internal.AbstractBatchImpl - HHH000010: On release of batch it still contained JDBC statements
2018-08-07 17:52:38,979 [Akka-akka.actor.default-dispatcher-23] WARN  akka.actor.OneForOneStrategy - null
2018-08-07 17:52:46,479 [Akka-akka.actor.default-dispatcher-23] ERROR akka.actor.ActorCell - changing Resume into Create after akka.actor.ActorInitializationException: exception during creation
2018-08-07 17:55:24,676 [pool-15-thread-2] WARN  o.t.s.dao.alarm.BaseAlarmService - [5e03d410-9a3a-11e8-9e00-19bfa5cfbb88] Failed to delete relation. Status: [ACTIVE_UNACK]
2018-08-07 17:59:35,815 [pool-21-thread-3] ERROR c.g.c.u.concurrent.AggregateFuture - Input Future failed with Error
java.lang.OutOfMemoryError: Java heap space
2018-08-07 17:59:35,815 [Akka-akka.actor.default-dispatcher-28] WARN  akka.actor.OneForOneStrategy - null
2018-08-07 17:57:30,274 [Akka-rule-dispatcher-107] WARN  o.t.s.d.relation.BaseRelationService - Failed to query relations: [EntityRelationsQuery(parameters=RelationsSearchParameters(rootId=7de41a00-93d8-11e8-9d40-991883b61f12, rootType=DEVICE, direction=TO, relationTypeGroup=COMMON, maxLevel=1), filters=[EntityTypeFilter(relationType=Contains, entityTypes=[ASSET])])]
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:78)
	at org.thingsboard.server.dao.relation.BaseRelationService.findRelationsRecursively(BaseRelationService.java:529)
	at org.thingsboard.server.dao.relation.BaseRelationService.findByQuery(BaseRelationService.java:405)
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy108.findByQuery(Unknown Source)
	at org.thingsboard.rule.engine.util.EntitiesRelatedEntityIdAsyncLoader.findEntityAsync(EntitiesRelatedEntityIdAsyncLoader.java:39)
	at org.thingsboard.rule.engine.metadata.TbGetRelatedAttributeNode.findEntityAsync(TbGetRelatedAttributeNode.java:52)
	at org.thingsboard.rule.engine.metadata.TbEntityGetAttrNode.onMsg(TbEntityGetAttrNode.java:54)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.onRuleChainToRuleNodeMsg(RuleNodeActorMessageProcessor.java:108)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.onRuleChainToRuleNodeMsg(RuleNodeActor.java:72)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActor.process(RuleNodeActor.java:45)
	at org.thingsboard.server.actors.service.ContextAwareActor.onReceive(ContextAwareActor.java:43)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Also - 'not getting response' - is it request timeout, or HTTP status code 404/500 ----------request time out
```

**Comment by vparomskiy** [comment]
According to log file you do not have enough memory. Please write how much memory is consumed by Thingsboard process and how men requests are generated to the Thingsboard
