### ISSUE TITLE
[Bug] NullPointerException when registering LwM2M client in queue mode

### ISSUE THREAD

**Issue by Rhyaldir** [thingsboard/thingsboard#9975]
**Description**
When a LwM2M device sends a "registration" message with queue mode enabled a null pointer exception is thrown in the lwm2m-transport service. Due to this exception the device is still shown as inactive and the configured attributes are not read. 

However, the client has received a "2,01 Created" response with a location path. Therefor from the clients point of view the registration was successfull.

Then the device sends an "registration update" message, the device attributes are read and the device is shown as Active.

If the same configuration is used, but the client does not use queue mode, the "registration" message is processed properly and the device is directly shown as Active.

**Server Environment**
* Own setup
  * Docker cluster deployment
  * Version: 3.6.2 / 3.6.3-SNAPSHOT (build from source)
  * Ubuntu 22.04

**Devices**
* Leshan-client-demo
* Nordic nRF9160-DK

**Connectivity**
  * LwM2M (using coap, without security)

**To Reproduce**
Steps to reproduce the behavior using the leshan-client-demo:
1. Create a LwM2M device profile adding a `Device #3_1.2`Object`  and select a few resources as attributes.
2. Create a device using the device profile as created in step 1. Set the "Endpoint Client Name" in Device Credentials (for example "testdevice") and select "No Security" Security mode.
3. Click Add
4. Run the leshan-client-demo in queue mode
  ```
  java -jar leshan-client-demo.jar -u localhost:5685 -n testdevice -q
  ```
5. Note the client reports the client has Registered.
  ```
                    LeshanClient 2024-01-11 09:26:56,338 [INFO] Starting Leshan client ...  
oapOscoreClientEndpointFactory 2024-01-11 09:26:56,341 [WARN] Experimental OSCORE feature is enabled.  
       DefaultEndpointsManager 2024-01-11 09:26:56,360 [INFO] New CoAP over UDP endpoint based on Californium library with very experimental support of OSCORE created, 
 for server coap://localhost:5685 at coap://0.0.0.0:34642.  
                  LeshanClient 2024-01-11 09:26:56,362 [INFO] Leshan client[endpoint:testclient] started.  
     DefaultRegistrationEngine 2024-01-11 09:26:56,362 [INFO] Trying to register to coap://localhost:5685 ...  
     DefaultRegistrationEngine 2024-01-11 09:26:56,404 [INFO] Registered with location '/rd/cL2BAxNvj2'.  
     DefaultRegistrationEngine 2024-01-11 09:26:56,404 [INFO] Next registration update to coap://localhost:5685 in 53s...  
  ```
6. The lwm2m-transport service reports an exception
  ```
  2024-01-11 08:26:56,400 [CoapServer(main)#7] INFO  o.t.s.t.l.server.LwM2mServerListener - [testclient] onAwake
2024-01-11T08:26:56.401365788Z 2024-01-11 08:26:56,401 [CoapServer(main)#7] INFO  o.t.s.t.l.s.c.LwM2mClientContextImpl - [testclient] initialized new client.
2024-01-11T08:26:56.401759119Z 2024-01-11 08:26:56,401 [CoapServer(main)#7] ERROR o.e.l.core.response.SendableResponse - Exception while calling the reponse sent callback
2024-01-11T08:26:56.401770603Z java.lang.NullPointerException: null
2024-01-11T08:26:56.401774645Z 	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
2024-01-11T08:26:56.401777894Z 	at org.thingsboard.server.transport.lwm2m.server.client.LwM2mClientContextImpl.doGetAndCache(LwM2mClientContextImpl.java:373)
2024-01-11T08:26:56.401780677Z 	at org.thingsboard.server.transport.lwm2m.server.client.LwM2mClientContextImpl.getProfile(LwM2mClientContextImpl.java:362)
2024-01-11T08:26:56.401783216Z 	at org.thingsboard.server.transport.lwm2m.server.client.LwM2mClientContextImpl.onUplink(LwM2mClientContextImpl.java:464)
2024-01-11T08:26:56.401785670Z 	at org.thingsboard.server.transport.lwm2m.server.client.LwM2mClientContextImpl.awake(LwM2mClientContextImpl.java:188)
2024-01-11T08:26:56.401788287Z 	at org.thingsboard.server.transport.lwm2m.server.uplink.DefaultLwM2mUplinkMsgHandler.onAwakeDev(DefaultLwM2mUplinkMsgHandler.java:449)
2024-01-11T08:26:56.401790839Z 	at org.thingsboard.server.transport.lwm2m.server.LwM2mServerListener$2.onAwake(LwM2mServerListener.java:89)
2024-01-11T08:26:56.401793241Z 	at org.eclipse.leshan.server.queue.PresenceServiceImpl.setAwake(PresenceServiceImpl.java:119)
2024-01-11T08:26:56.401795742Z 	at org.eclipse.leshan.server.queue.PresenceStateListener.registered(PresenceStateListener.java:47)
2024-01-11T08:26:56.401806372Z 	at org.eclipse.leshan.server.registration.RegistrationServiceImpl.fireRegistered(RegistrationServiceImpl.java:74)
2024-01-11T08:26:56.401809327Z 	at org.eclipse.leshan.server.registration.RegistrationHandler$1.run(RegistrationHandler.java:86)
2024-01-11T08:26:56.401811766Z 	at org.eclipse.leshan.core.response.SendableResponse.sent(SendableResponse.java:47)
2024-01-11T08:26:56.401814020Z 	at org.eclipse.leshan.server.californium.registration.RegisterResource.handleRegister(RegisterResource.java:188)
2024-01-11T08:26:56.401816409Z 	at org.eclipse.leshan.server.californium.registration.RegisterResource.handlePOST(RegisterResource.java:103)
2024-01-11T08:26:56.401818734Z 	at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:219)
2024-01-11T08:26:56.401821078Z 	at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51)
2024-01-11T08:26:56.401823731Z 	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:106)
2024-01-11T08:26:56.401826870Z 	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:207)
2024-01-11T08:26:56.401831204Z 	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
2024-01-11T08:26:56.401834153Z 	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
2024-01-11T08:26:56.401836851Z 	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:488)
2024-01-11T08:26:56.401839448Z 	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:296)
2024-01-11T08:26:56.401841726Z 	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
2024-01-11T08:26:56.401844043Z 	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:140)
2024-01-11T08:26:56.401846770Z 	at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:302)
2024-01-11T08:26:56.401849163Z 	at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:289)
2024-01-11T08:26:56.401851395Z 	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290)
2024-01-11T08:26:56.401853726Z 	at org.eclipse.californium.core.network.CoapEndpoint$6.run(CoapEndpoint.java:1311)
2024-01-11T08:26:56.401856012Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-01-11T08:26:56.401858324Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-01-11T08:26:56.401860994Z 	at java.base/java.lang.Thread.run(Thread.java:829)
  ```

**Expected behavior**
The exception should not have been thrown, and the divice should have been shown als Active directly

**Comment by Rhyaldir** [comment]
B.t.w. I hope to add a pull request soon, as I think I have found the cause of the issue.

**Comment by Rhyaldir** [comment]
It has been solved. See #9977
